### ISSUE TITLE
Destructive variable not passing through to Modal button component 

### ISSUE THREAD

**Issue by cargix1** [Shopify/polaris-react#1002]
# Issue summary
When using the App Bridge to control our Modals we pass through the destructive property on the primaryAction, but the button doesn't visually reflect a destructive button. 

## Expected behavior

We would expect to see a button styled like this: 

<img width="177" alt="screenshot 2019-02-11 at 16 29 30" src="https://user-images.githubusercontent.com/9730290/52577531-38e3ee80-2e1a-11e9-94cf-99d4ff578ec8.png">

## Actual behavior

We currently just see a normal primary button appear: 

<img width="318" alt="screenshot 2019-02-11 at 16 26 02" src="https://user-images.githubusercontent.com/9730290/52577394-ec98ae80-2e19-11e9-94ec-245cd85e7939.png">

## Steps to reproduce the problem

Below is the code to replicate. Create a modal using the App Bridge. Set the "destructive" param on either the primary of secondary actions and notice when you open the modal the buttons don't appear red. 

```
const okButton = Button.create(this.context.polaris.appBridge, {
  label: 'Confirm, disable rates',
  destructive: true,
  onAction: () => console.log('cancel')
});

const cancelButton = Button.create(this.context.polaris.appBridge, {
  label: 'Cancel',
  onAction: () => console.log('cancel')
});

const modalOptions = {
  title: 'My modal',
  message: 'Hello World',
  size: Modal.Size.Medium,
  footer: {
    buttons: {
      primary: {okButton},
      secondary: [cancelButton]
    }
  }
};
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.6.0
- Browser: Chrome (latest)
- Device: Macbook Pro
- Operating System: Mojave

**Comment by dpersing** [comment]
Hi @cargix1! You'll want to take a look at the documentation for actions via App Bridge instead of Polaris for your destructive style: https://help.shopify.com/en/api/embedded-apps/app-bridge/actions/button#button-style

**Comment by cargix1** [comment]
Thanks @dpersing!!! Not sure how I missed that :)
