### ISSUE TITLE
Add a 12px (base * 3) spacing option to spacing-data in Sass map

### ISSUE THREAD

**Issue by elizabethletourneau** [Shopify/polaris-react#1007]
# Feature request summary

There have been a few occurrences where we have needed a rem(12px) padding or margin however it is not currently a listed option in `spacing-data` map in spacing.scss

## Rationale

This requires discussion if we should add a new option and if that's the case the naming of the variables will need to change:

![11-58-bskkl-75n92](https://user-images.githubusercontent.com/31415362/52593035-f4565400-2e15-11e9-9346-a3f03c2b66b7.jpg)

Example of usage:
In `Card` in the header and footer
In `Banner`
In `Button`
In `DatePicker`
In `Select`
In `SkeletonBodyText`

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by elizabethletourneau** [comment]
@kaelig @solonaarmstrong @ry5n CC'ing on this to discuss further.  This issue may be bigger than just adding a middle variable since the naming of it could cause confusion and if in that case all the variable names needed to shift we would need to change all the occurrences in all of polaris.

**Comment by solonaarmstrong** [comment]
I'm pretty sure I also ran into a need for 12px in range slider dual input: https://github.com/Shopify/polaris-react/pull/987

It comes up now and then.

**Comment by ry5n** [comment]
If we can come up with an acceptable name for this, I’d be OK with it.

**Comment by solonaarmstrong** [comment]
I thought about it a bit.

`base-tight` (with a fun musical connotation)
`less-tight`

?

(I'm actually surprised that these didn't follow the color naming convention. `tighter` instead of `extra-tight`, but I digress).

**Comment by ry5n** [comment]
What do we gain by adding this?

**Comment by solonaarmstrong** [comment]
Consistency, ease. But it's not the end of the world to use `rem(12px)`.

**Comment by ry5n** [comment]
I’m OK with `base-tight`

**Comment by ry5n** [comment]
We’ll need to also update the [spacing page on the style guide](https://polaris.shopify.com/design/spacing#spacing-in-code).

**Comment by BPScott** [comment]
If we're going all in on this, then we should update polaris-tokens to include `base-tight` too

**Comment by solonaarmstrong** [comment]
Add to Polaris tokens: https://github.com/Shopify/polaris-tokens/pull/48
Import token in spacing function: coming soon
Use new value: https://github.com/Shopify/polaris-react/pull/1044
