### ISSUE TITLE
[Multiple components] [For elements] Add sidekick variants

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react#10152]
Add Sidekick variants for highlighting fields that have been filled in by Sidekick.
```[tasklist]
### Tasks
- [x] Text field
- [x] Rich text editor
- [x] Selected segment/customer, product, etc. (for discounts)
- [x] Select
- [x] Radio
- [x] Checkbox
- [ ] Tag
- [ ] Index tag
- [x] RangeSlider
```
<img width="544" alt="Changes" src="https://github.com/Shopify/polaris-internal/assets/1327837/89ea5b7e-0f02-49b0-9b35-1caa3cd1ef4b">

**Comment by jonrundle** [comment]
@matallo added rich text editor to the list as well as the segment/product picker in the discounts view that Felipe mentioned in the sync. I have mocks for this when needed.

Also re-ordered the list to be more priority order imo

**Comment by discomancer** [comment]
[Figma designs](https://www.figma.com/file/NgdbDC5egkw8T5oHiq4mWR/Sidekick%3A-Production?node-id=13313%3A67917&mode=dev)

**Comment by mathildebuenerd** [comment]
@matallo Do you know what's the status of adding sidekick variant to the `Select` element?

**Comment by matallo** [comment]
I'll add it to my backlog but unfortunately I had to change priorities. `Select` is next on my list
