### ISSUE TITLE
Breadcrumb title bar does not utilize AppProvider linkComponent prop

### ISSUE THREAD

**Issue by juliantrueflynn** [Shopify/polaris-react#1028]
# Issue summary

Title bar link does not use `linkComponent` from `AppProvider` prop. If this is expected behavior please let me know so I can put this as a request.

This ticket might be related to [this one](https://github.com/Shopify/polaris-react/issues/952).

![title bar](https://user-images.githubusercontent.com/2691129/52688206-6ff1f700-2f23-11e9-86cd-e5338a41b259.png)
*Picture of which title link I am referencing as issue*

## Expected behavior

Link for title bar and breadcrumbs should utilize `linkComponent` prop provided from AppProvider.

## Actual behavior

When clicked it causes a full page refresh because it behaves like a normal link. This is an issue because if using React Router history the full page refresh loses history (which results in requesting stylesheet, scripts, etc. again).

## Steps to reproduce the problem

I wrote in ReadMe how to setup the app to reproduce the problem. Note: You need to view the app in Shopify Admin area. https://github.com/juliantrueflynn/shopify-koa-app-example/tree/error__title-link/complete-app

1. Open app in Shopify Admin
2. Click link in title bar
3. In browser console the event is not logging when clicking title bar link, you can also look in the browser Network Tab to see it requesting stylesheets and scripts again (from full page refresh).

## Reduced test case

https://github.com/juliantrueflynn/shopify-koa-app-example/tree/error__title-link/complete-app Note: You need to view the app in Shopify Admin area.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.7.0
- Browser: Chrome
- Device: Desktop
- Operating System: Ubuntu 16.04

**Comment by jbasko** [comment]
https://github.com/Shopify/polaris-react/issues/998

**Comment by danrosenthal** [comment]
It definitely looks like the `Breadcrumb` component, which is rendered inside the `Page` `Header` component should be using the `Link` provided through `AppProvider`. I haven't looked deeply into the issue, but this may also be the root cause of #998, as @jbasko has pointed out

**Comment by juliantrueflynn** [comment]
My bad, I read through tickets but I guess I missed theirs. This ticket can be closed.

**Comment by danrosenthal** [comment]
> My bad, I read through tickets but I guess I missed theirs. This ticket can be closed.

Sorry if I wasn't clear. This **does** appear to be an issue, I was only suggesting it might be related to #998. Going to reopen until this issue is resolved

**Comment by AndrewMusgrave** [comment]
At first glance this seems like an app bridge issue since the bread crumb is coming from app bridge (not rendered from polaris). @Shopify/app-bridge is it possible to use libraries like react-router with app brdige?

**Comment by vividviolet** [comment]
@AndrewMusgrave the full app reload cannot be avoided currently. We are working on a solution in App Bridge to allows apps to handle their own redirects which will be more compatible with react-router. We will update this issue when the solution has been shipped in App Bridge.

**Comment by AndrewMusgrave** [comment]
Awesome, thanks for the quick response @vividviolet 🙏

**Comment by qw-in** [comment]
For those looking for a workaround: 

Using `@reach/router` but should be universal

```jsx
<Page
  breadcrumbs={[
    { onAction: () => navigate('/foo'), content: 'FOO' },
  ]}
/>
```
