### ISSUE TITLE
[Card] actions not displayed if the card doesn't have a title or it's empty

### ISSUE THREAD

**Issue by jbasko** [Shopify/polaris-react#1031]
# Issue summary

Perhaps `title` is mandatory for `Card` (documentation doesn't say so), but if you don't specify it or you leave it empty, the card actions don't show up in the top right corner of the card.

## Expected behavior

I would expect them to show up anyway or have an error on empty title.

## Steps to reproduce the problem

    <Card
        sectioned
        title=""
        actions={[
            {content: "Do something", url: "/"}
        ]}
    >
        Card Content
    </Card>

## Specifications

- Are you using the React components? Y
- Polaris version number: 3.7.1
- Browser: Chrome
- Device: Mac
- Operating System: OS X

**Comment by danrosenthal** [comment]
@jbasko thanks! You've definitely found a bug. Looking at this line: https://github.com/Shopify/polaris-react/blob/master/src/components/Card/Card.tsx#L52, the condition should look for `title || actions`, not just `title` to render the `Header` component. Would you be willing to put up a pull request fixing this? We'd certainly appreciate it

**Comment by jbasko** [comment]
Thanks. I just did exactly the one liner you suggested (PR linked above). I'm afraid I don't know how to efficiently test it as I'm not up to speed with JS in the last 4-5 years.

**Comment by danrosenthal** [comment]
> Thanks. I just did exactly the one liner you suggested (PR linked above). I'm afraid I don't know how to efficiently test it as I'm not up to speed with JS in the last 4-5 years.

Seeing this comment now, after addressing #1032. I'm happy to add the test if you'd like.
