### ISSUE TITLE
[Documentation] Improve documentation of public subcomponents

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react#1035]
As highlighted in #1030, outside of the examples we provide, most subcomponents that are technically part of the public API are not documented. Exceptions are `Stack.Item`,`ResourceList.Item`, `ResourceList.FilterControl`, `Topbar.Menu`, and `TopBar.SearchField`.

Subcomponents that should be documented: 
- [ ] `Autocomplete.TextField` and `Autocomplete.ComboBox`
- [ ] `Dropzone.FileUpload` **
- [ ] `FormLayout.Group`
- [ ] `Layout.Section` and `Layout.AnnotatedSection` **
- [ ] `List.Item` **
    - Only accepts children
    - Is **required**
        - Without wrapping `List` children in a `List.Item`, they will not be wrapped in a `li` element and therefore won't be styled or read by screen readers as list items. This needs to be noted because it contrasts our other component APIs (like `Stack` and `Tabs`), which auto-wrap children.
- [ ] `Modal.Dialog` and `Modal.Section`
- [ ] `Navigation.Item` and `Navigation.Section` (`Navigation.UserMenu` is [deprecated](https://github.com/Shopify/polaris-react/pull/887))
- [ ] `Popover.Pane`
- [ ] `Tabs.Panel`
- [ ] `TopBar.UserMenu` (pending--replacing deprecated `Navigation.UserMenu`) ** 

_* Note - This list is not exhaustive of all subcomponents in the public API. These are the ones with props (other than `children`)._

For reference, here is a list of other subcomponents. Their only API is to accept children.
- `Popover.Section`, use when you need some but not all children to be wrapped in a padded container (set the `sectioned` prop on `Popover` if you want all children wrapped in a section)
- `Scrollable.ScrollTo`, use to programmatically scroll to a child of a `Scrollable`

cc @kvendrik (for `Topbar.UserMenu` in case it's not already documented in one of your PRs)
cc @elizabethletourneau (** Highest priority to document )

**Comment by yourpalsonja** [comment]
Short term fix: Let's go and create documentation in the parent components README, we can always copy/paste those later.

Long term fix: Redo of styleguide.

@VanjaMitrovic @sadiesaurus @selenehinkley do you have time to work with any devs to write some docs for these components at an upcoming doc workshop?

**Comment by sadiesaurus** [comment]
@yourpalsonja I'm happy to work with a dev on getting this going! Will try for next week.
