### ISSUE TITLE
[Stack] wraps items when it shouldn't

### ISSUE THREAD

**Issue by jbasko** [Shopify/polaris-react#1038]
Maybe I'm using `Stack` when it's not meant to be used, but I believe this falls under the category of "small-scale layout tasks".

I want to replicate the layout I see in the Partners dashboard, under Resources, Get Started which is a basically a flex box of two items: a paragraph of text potentially broken down in lines and a button on the right that applies to the whole paragraph. Here's a plain HTML, CSS example:

https://codepen.io/anon/pen/WPgJqw

`Stack` doesn't allow me to do it. Instead it lets the text paragraph spread as wide as the button on the right allows:

https://codesandbox.io/s/n73krox544

What am I missing here?

## Steps to reproduce the problem

See codepen and codesandbox

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.7.1
- Browser: Chrome
- Device: -
- Operating System: -

**Comment by chloerice** [comment]
Hey @jbasko, thanks for raising this. When I add `wrap={false}` to the `Stack` with much wider text, the layout mirrors the one you see in the available tools card you mentioned. The same doesn't work as expected in the card that is in a regular width layout section, as there's a bug in the version 72 of Chrome that pushes children out of flex containers (see #1024).

https://codesandbox.io/s/0qxwvv8mjv

<img width="1440" alt="screen shot 2019-02-14 at 12 21 27 pm" src="https://user-images.githubusercontent.com/18447883/52804781-17217c00-3053-11e9-82ce-9ee19e63ab31.png">

**Comment by jbasko** [comment]
Thanks @chloerice for looking into this and for providing a working example!

So, it's not an issue with `Stack`, just not the right markup by me. The example you gave in codesandbox works on my Chrome 72.0.3626.109 with both the primary width layout section as well as full width layout section or I misunderstood you.

**Comment by chloerice** [comment]
Oh great!! I think I may need to update my browser 😅

**Comment by chloerice** [comment]
I see, I'd forgotten to place the `p` in a `Stack.Item` with the `fill` prop set and remove the `TextContainer`* (which I also forgot to mention I'd done in my reply to you!).

*Since that component just puts margin between text, so since there was only one text element it's not needed.
