### ISSUE TITLE
Reducing Polaris bundle size

### ISSUE THREAD

**Issue by Rafi993** [Shopify/polaris-react#10390]
## Issue summary

* When you import a component from Polaris like
```
import { AppProvider } from '@shopify/polaris
```

with a Nextjs app, it seems to increase the bundle size drastically since other components that are not getting used are also added to the bundle.
* The bundle size could be improved drastically if we could import the required component directly

```
import AppProvider from '@shopify/polaris/AppProvider'
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: `^11.11.0`
- Browser:
- Device:
- Operating System:

**Comment by Rafi993** [comment]
I was able to figure out this issue. This is not an issue in the Polaris library. It was tree shaking properly

**Comment by wissem** [comment]
@Rafi993 I run into the same issue after upgrading Polaris. I'm not using NextJS but it might be related to tree shaking not working properly. How were you able to solve it?
