### ISSUE TITLE
Create interactive `Color` palette

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react#10410]
Based on [original comment](https://github.com/Shopify/polaris/issues/10146#issuecomment-1692150608)

![Image](https://github.com/Shopify/polaris/assets/4642404/a278b6ef-ce15-491e-8b95-172823ad5380)

Build off of the existing `Colors` markdown component found in `/design/colors` to create an [interactive color palette](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=315%3A30700&mode=design&t=ZxxnpDPra4zGQizx-1)

**Comment by sam-b-rose** [comment]
@tjonx @yurm04 can we consider this closed or is there still work to be done on the color picker/contrast checker?
