### ISSUE TITLE
Orientation issue in collection image preview

### ISSUE THREAD

**Issue by siddhantbajaj** [Shopify/polaris-react#1058]
# Issue summary

Collection image preview sometimes show wrong orientation. However on reloading, image with correct orientation is displayed.

Related: https://github.com/Shopify/core/issues/4031

## Expected behavior

Collection image preview should always image in correct orientation.

## Possible cause

Some digital camera photos are often saved as JPEG with an EXIF "orientation" tag, which defines the orientation of image. 

`URL.createObjectURL(image)` ignores this `orientations` tag therefore we sometimes get image preview in wrong orientation.

Line: https://github.com/Shopify/web/blob/master/app/sections/Collections/CollectionShow/components/CollectionImageCard/CollectionImageCard.tsx#L352

## Steps to reproduce the problem

- [Video](https://screenshot.click/11-41-inov9-qrmdv.mp4)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number:
- Browser: Chrome
- Device: Web
- Operating System: Mac os

@chloerice, @maxariss

**Comment by chloerice** [comment]
Before saving, the `Dropzone.FileUpload` presents files and images with an `img` sized according to the `Dropzone.size`. There may be some performance drawbacks, but we could extract orientation from image blob's exif data. @siddhantbajaj how is orientation handled for the image displayed after upload? I'm guessing imagemagick handles that?

**Comment by siddhantbajaj** [comment]
> There may be some performance drawbacks we need to assess, but we could extract orientation from the blob's exif data.

I have a PR for it and can use some feedback there. - https://github.com/Shopify/web/pull/10811

> There may be some performance drawbacks we need to assess, but we could extract orientation from the blob's exif data. @siddhantbajaj how is orientation handled for the image displayed after upload? I'm guessing imagemagick handles that?

Right now to create a preview link of the image we use `URL.createObjectURL(image)` but that ignores exif orientation attribute so we sometimes get wrong orientation. After hitting save, the image is uploaded in the storage (with correct orientation) and we use storage link to display the image correctly.

**Comment by siddhantbajaj** [comment]
> This sounds like it is probably an issue with the consuming implementation
Agreed not exactly a polaris issue but something to be fixed in web. Closing it.
