### ISSUE TITLE
[FormLayout] Fix spacing between form elements

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react#10618]
## Issue summary
We need to increase the space between form elements from 8px (200) to 16px (400).

**Comment by FaycalSabaou** [comment]
👋 Hello @heyjoethomas @chloerice, just wanted to revive this issue. It's impacting the user experience of our forms for onboarding and remediation of Shopify Payments and Shopify Capital. Would it be possible to look into this. I appreciate your help! 
cc @adandach @shawn-shellenbarger

**Comment by johanstromqvist** [comment]
@tjonx, @zecarlostorre and I discussed the spacing between and around form layouts and the revised value is `300`.

- The original issue was that `200` was too tight, causing unclear grouping between form layout items.
- The suggested `400` is too loose, often rendering forms to be sparse, as well as causing unclear hierarchy between wrapping groups that also use `400` (such as between form layouts and card sections).
- `300` is a compromise that meet grouping and hierarchy needs most of the time

^ these issues were mentioned in the original discussion but were probably lost along the way.

![image](https://github.com/Shopify/polaris/assets/38329124/d5efc337-de68-4340-be14-d86bfa42531b)

**Comment by chloerice** [comment]
Once we ship the Polaris v12 upgrade in Web, I'll be able to merge and ship a patch upgrade.
