### ISSUE TITLE
Remove support for custom Shopify SVG format

### ISSUE THREAD

**Issue by amrocha** [Shopify/polaris-react#1061]
Shopify imports SVGs with the following format:

```
{
  viewBox: [string],
  body: [body],
}
```

We've asked around and it seems nobody is aware of a reason why it needs to be this way, and we can switch to a more standard format.

We can't just remove it though, because sewing-kit uses this format in its SVG loader, so that would be a very disruptive change to the rest of Shopify.

The proposed order of steps to remove this is:
 - [x] Add support for SVGR to `polaris-react` (#1042 )
 - [x] Add support for SVGR to `sewing-kit` (https://github.com/Shopify/sewing-kit/pull/1208)
 - [x] Deprecate support for the old format in `polaris-react`
 - [x] Remove support for the old format in `polaris-react` in a major release (#1604)

@BPScott

**Comment by BPScott** [comment]
🎉
