### ISSUE TITLE
Images in cards should have rounded in corners, except for do/dont

### ISSUE THREAD

**Issue by tjonx** [Shopify/polaris-react#10627]
## Issue summary
Images in cards should have their corners rounded.

![image](https://github.com/Shopify/polaris/assets/67433661/d3070766-8f2c-477b-9fb3-346910811c67)

## Expected behavior

![image](https://github.com/Shopify/polaris/assets/67433661/4693542b-77f6-4b12-a2d2-93f35c45088d)

## Notes

We can add the corners in the images, but then the scaling would be off.

**Comment by johanstromqvist** [comment]
I'm exporting images without border radius. Seem like a good practice to decouple assets from style.

**Comment by yurm04** [comment]
As far as I can tell this is fixed in production. Going to close this ticket but feel free to re-open if it's not actually fixed or I've misunderstood the ask

![Image](https://github.com/Shopify/polaris/assets/4642404/6337ac77-6edc-4ff7-9a89-c2f3f40dcdec)
