### ISSUE TITLE
Polaris styles CSS Topbar components CSS missing

### ISSUE THREAD

**Issue by tabrez96** [Shopify/polaris-react#1062]
# Issue summary

We are using polaris-react version 3.5.0 and we are using CSS from the provided CDN link : 
https://sdks.shopifycdn.com/polaris/3.5.0/polaris.min.css. In this case, the topbar components like user menu and searchField has broken CSS and I just figured out that the CSS for `Polaris-TopBar__SearchField`, `Polaris-UserMenu-UserMenu` class and few other classes are missing.

## Expected behavior
User menu component in topbar should be aligned and rendered properly as shown in the documentation example.

## Actual behavior
Currently, on using CSS from CDN, the user menu and search field's CSS is broken.

## Steps to reproduce the problem

Use CSS from CDN by adding the link in index.html like 
`<link rel="stylesheet" href="https://sdks.shopifycdn.com/polaris/3.5.0/polaris.min.css" />`

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.5.0
- Browser: Chrome
- Device: MacBook Pro
- Operating System: macOS Mojave 10.14.3

**Comment by AndrewMusgrave** [comment]
Hi @tabrez96 I'm not sure why the styles are missing in that release, however they appear to be present in `3.6.0.0`. Are you able to upgrade?

**Comment by AndrewMusgrave** [comment]
I'm going to close the issue for now. Feel free to reopen if you need more assistance.
