### ISSUE TITLE
Embedded component border (admin nav UI bug)

### ISSUE THREAD

**Issue by ptcampbell** [Shopify/polaris-react#1072]
The admin nav has lost its right border which has the undesired effect of the horizontal rule ending in no man's land. It looks fine in the rest of the admin (pages, products etc.) but for embedded apps, due to the styling of the toolbar, it feels less seamless and polished than it was before:

<img width="224" alt="screen shot 2019-02-19 at 8 21 14 pm" src="https://user-images.githubusercontent.com/876594/53130591-90234680-351f-11e9-8a34-145318ebfe7e.png">

Since the section outside the iframe cannot be styled, any manual addition of a left border results in an odd looking square which doesn't go all the way to the navbar component. 

Is it possible to either reintroduce the border-right in the nav while an embedded app is open — or to remove the border-bottom from the embedded app toolbar?

**Comment by ry5n** [comment]
We’re working on some options to address this. Shouldn’t be too long.

**Comment by ptcampbell** [comment]
Thank you!

**Comment by yourpalsonja** [comment]
@ptcampbell I'm moving this to fixed and closing it, it was addressed in https://github.com/Shopify/polaris-react/pull/1096!
