### ISSUE TITLE
Update broken link in docs

### ISSUE THREAD

**Issue by seandogg** [Shopify/polaris-react#1079]
On this [page](https://help.shopify.com/en/api/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris), find the sentence: `Your app will use a library called Shopify App Bridge to communicate with Shopify.` The link is 404, whereas I found this: https://help.shopify.com/en/api/embedded-apps/app-bridge

Cheers

**Comment by AndrewMusgrave** [comment]
cc/ @markiiikram Is this owned by your team?

**Comment by markiiikram** [comment]
Thanks @AndrewMusgrave. Will fix. Thank you!

cc: @katiedavis

**Comment by markiiikram** [comment]
Thanks for reporting this bug @seandogg. It should now be fixed. 👍
