### ISSUE TITLE
[polaris.shopify.com] Feedback (on /icons)

### ISSUE THREAD

**Issue by redpandatronicsuk** [Shopify/polaris-react#10803]
The black icons have low contrast to the background color in dark mode. 
<img width="458" alt="image" src="https://github.com/Shopify/polaris/assets/8609582/fc8b08fb-c54b-45a5-aecd-09b921be4aa4">

**Comment by chloerice** [comment]
Thanks for flagging this @redpandatronicsuk! Closing as this is a duplicate of https://github.com/Shopify/polaris/issues/10689
