### ISSUE TITLE
[Autocomplete][v1] ComboBox uses tabindex=0 which causes tabbing issues with AutoComplete

### ISSUE THREAD

**Issue by adamcarchibald** [Shopify/polaris-react#1089]
# Issue summary
ComboBox in AutoComplete has `tabindex=0` which causes the wrapping ComboBox to be highlighted when tabbing into the AutoComplete component.

https://github.com/Shopify/polaris-react/blob/master/src/components/Autocomplete/components/ComboBox/ComboBox.tsx#L266

## Behavior
Tabbing into AutoComplete should allow text input without having to press tab a second time.

[Video with tabindex](https://screenshot.click/screencast_2019-02-22_15-12-51.mp4)
[Video without tabindex, expected behaviour](https://screenshot.click/screencast_2019-02-22_15-14-49.mp4)

## Reduced test case

[CodeSandbox with an AutoComplete you can tab into](https://codesandbox.io/s/lxxwom7907?fontsize=14)

**Comment by ry5n** [comment]
@dpersing Any chance you could take a look?

**Comment by dpersing** [comment]
@ry5n It looks like I mentioned the `tabindex` in the original PR review in the old repo (https://github.com/Shopify/polaris-react-deprecated/pull/1902#pullrequestreview-145488628), but that item didn't make it into the summary accessibility issue that I moved over to this repo (#789).

Agreed that the extra `tabindex="0"` is unnecessary and probably confusing. Additional work is needed, but removing that in the short term would be totally cool. 👍

**Comment by ry5n** [comment]
@adamcarchibald If you’re interested it sounds like a straightforward fix, feel free to open a PR. Otherwise we’ll get to it as soon as possible.

**Comment by adamcarchibald** [comment]
@ry5n sounds good i'll submit one

**Comment by yourpalsonja** [comment]
I've checked with @adamcarchibald to see if this can be closed, since it looks like a PR has been merged, just not sure it's the right one!

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.

**Comment by dpersing** [comment]
@dleroux We should keep an eye on the ARIA 1.2 (currently in draft) spec for combobox for future work: https://www.w3.org/TR/wai-aria-practices-1.2/#combobox
