### ISSUE TITLE
Issue with embedded app 

### ISSUE THREAD

**Issue by AndreyYeryomin** [Shopify/polaris-react#1093]
# Issue summary

When i try execute  example from https://polaris.shopify.com/components/structure/page for embedded app. My code in this [link:](https://files.fm/u/rxvdzzec)

apiKey and shopOrigin is correct. I get this ![screenshot 12](https://user-images.githubusercontent.com/18416551/53394887-369c9b00-39a9-11e9-8dfa-6f12e3ede277.png)
If i downgrade polaris to 2.12.1 - all is ok.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.9.0
- Browser: Google Chrome Version 72.0.3626.119 
- Device: iMac
- Operating System: OS X El Capitan ver 10.11.4

**Comment by ry5n** [comment]
Thanks for filing the issue @AndreyYeryomin. Any chance you could include your JS code directly in the issue? Thanks

**Comment by AndreyYeryomin** [comment]
@ry5n 

`import React from 'react';
import ReactDOM from 'react-dom';
import {AppProvider ,Page} from "@shopify/polaris";

ReactDOM.render(
    <AppProvider
        apiKey="b2218bb6342596bb557ed104561203c5"
        shopOrigin="devit-dev.myshopify.com"
        forceRedirect={true}

    >
        <Page
            breadcrumbs={[{content: 'Products'}]}
            title="Product reviews"
            primaryAction={{
                content: 'Save',
                disabled: true,
            }}
            secondaryActions={[{content: 'Duplicate'}, {content: 'Upgrade'}]}
            actionGroups={[
                {
                    title: 'Promote',
                    actions: [
                        {
                            content: 'Share on Facebook',
                            onAction: ()=>{console.log('share facebook')}
                        },
                        {
                            content: 'Share on Pinterest',
                            onAction: ()=>{console.log('share Pinterest')}
                        },
                    ],
                },
            ]}
        >
            <p>Page content</p>
        </Page>
    </AppProvider>,
    document.getElementById('app')
);
`

**Comment by ry5n** [comment]
Thanks @AndreyYeryomin. I’ll dig into this and we’ll get back to you with next steps.

**Comment by AndreyYeryomin** [comment]
@ry5n can you fix this issue? i still has this problem when i trying set my apikey and shopOrigin.
![Screenshot (14)](https://user-images.githubusercontent.com/18416551/54983965-7f4e7080-4fb6-11e9-92f9-704222e30923.png)

**Comment by AndreyYeryomin** [comment]
i just trying execute simple example from polaris documentation

**Comment by AndreyYeryomin** [comment]
i need to resolve this problem, because i working with embedded app, and i cant finish this app until you don`t resolve this problem.

**Comment by chloerice** [comment]
Hey @AndreyYeryomin, the first screenshot seems to just be a problem of loading on an unsupported device, but the second browser screenshot doesn't give any clues of what's going on. 

Does your app run locally when you remove `apiKey` and `shopOrigin`? What error(s) are you getting in your browser console and/or in your terminal?

**Comment by AndreyYeryomin** [comment]
@chloerice Yes. When i remove "apiKey" and "shopOrigin" from AppProvider properties, all works well. But i want to use AppBridge for integration with parent window.
 
**My device:** 
- Browser: Google Chrome Version 72.0.3626.119
- Device: iMac
- Operating System: OS X El Capitan ver 10.11.4

**Comment by chloerice** [comment]
> Overlay displayed in front of iframe with application, but application continue working under overlay with broken some features. E.g. page actions buttons from standart "Polaris Page" component stop displayed anywhere.

Hmmm, it sounds like what you're describing there the move of the page actions etc into the topbar above the iframe (that's intentional).

I'll reach out to the App Bridge team for help on this, as they're familiar with embedded app set up and what can go wrong.

**Comment by henrytao-me** [comment]
@chloerice @AndreyYeryomin I believe your app is blacklisting to use App Bridge right now. That's why you see above error.

**Comment by AndreyYeryomin** [comment]
Hey @chloerice @ry5n do you have any information about this problem?

**Comment by AndreyYeryomin** [comment]
Example:
![Screenshot (20)](https://user-images.githubusercontent.com/18416551/56270375-a18f6600-60fe-11e9-8d9f-d79aaa9bfdae.png)
 My result:
![Screenshot (21)](https://user-images.githubusercontent.com/18416551/56270479-def3f380-60fe-11e9-9d65-a92f5d51c452.png)

I still have issue with rendering Page component...

**Comment by chloerice** [comment]
Hey @AndreyYeryomin, when you set the `apiKey` on the `AppProvider` component, it delegates rendering the actions and top bar to the App Bridge. But since you're looking at your app in a stand alone context right now I'm not sure why the actions aren't showing. Can you open a new issue since this is unrelated?

**Comment by AndreyYeryomin** [comment]
> ... **We’ve opted LangShop SandBox Dev back in to App Bridge use**.  ...
Hey , anyone.  I have same problem in my staging app ![Screenshot (14)](https://user-images.githubusercontent.com/18416551/54983965-7f4e7080-4fb6-11e9-92f9-704222e30923.png).  Earlier you enabled AppBridge for my dev app (LangShop SandBox Dev). This problem was solved. Now, we are using beta application (App ID: 1785247, App Name: LangShop SandBox Beta) and it has the same problem with AppBridge. Can you enable using AppBridge for this app? And what should we do when we will release our code to the live application? Thanks.

**Comment by chloerice** [comment]
Hey @AndreyYeryomin! The App Bridge team is working on fixing this for you now. Would you like your production app opted into App Bridge as well? If so, let me know the App ID for it as well and I'll pass along.

**Comment by AndreyYeryomin** [comment]
Hey @chloerice ! Thanks. My production App ID : 1150322

**Comment by chloerice** [comment]
> Hey @chloerice ! Thanks. My production App ID : 1150322

Your production app and beta app have both been removed from App Bridge opt out and should be good to go!
