### ISSUE TITLE
Orders list layout: sort placement

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react#1095]
Related to -> [Polaris list filters GH issue](https://github.com/Shopify/web/pull/9901)

## Problem

The Orders list today uses column headers. This page has recently been updated to react but does still have the column headers and, as a result, the sort placement has been moved to be inline with filter and search.

With the introduction of shortcut filters and the new placement of the `Save` button, there isn't much space for the addition of the sort.

![orders-list-current](https://user-images.githubusercontent.com/8629173/53434574-ecc1ae00-39c4-11e9-87f5-bae0e8776630.png)

## Solution

@ry5n Explored several different direction for how we can handle the sort control.

We are currently exploring the idea of the mini sort button.

**1. Mini sort button**
https://shopify.invisionapp.com/share/AMQPWPOR3TX

**Pros**
- Visually and spacially fits into the current design

**Cons**
- There are a lot of controls in a tight area
- There is some inconsistency between mobile and desktop

![image](https://user-images.githubusercontent.com/8629173/53435884-db2dd580-39c7-11e9-87b4-4304b012f96c.png)

2. Sort select below filters 
https://shopify.invisionapp.com/share/B4QPWS6PG5Q

3. Sort in the column headers
https://shopify.invisionapp.com/share/TCQPT259Z7V

---

**Todo**
- [x] Desktop designs
- [x] Mobile web designs
*Note: Sorting is most likely going to stay the same on mobile web = will remain a select dropdown. The way this is built makes it difficult to manipulate.*

---
**Feb 20, 2019: Sort placement decision**
> Ryan Frederick [12:17 PM]
Yesterday we reached consensus on the way forward for sorting: we’ll use the short mini sort button to the right of the save button. The sort button will open a popover with a regular choice list (radios).

https://shopify.invisionapp.com/share/52OSL7SUGE4#/347220269_Orders_-_Minisort_-right-_2_-menu-

**Comment by sarahill** [comment]
I chatted a little with @AdamWhitcroft about the sort layout in Slack. I want to move the conversation here so everyone can weigh in.



### Some relevant parts of our convo below:

**Adam Whitcroft**
- I worry about the number of controls at the top of the one with the `Sort` button
- that’s pretty hectic
- those table headers… would it not make more sense to just use clicking those for sorting?
- since we’re adding them back in, potentially
- might as well stick with tabular convention?


**Sara Hill**
Yea, that's interesting. The biggest reason to separate them was to keep the ability to have additional sorting options rather can being constrained by the columns shown in the list.

Ryan did some other stuff around column header sorting too. I'll dig that and send it over. I think that's preferred approach but there are some scope/timing constraints for now


**Adam Whitcroft**
Oh i’ll bet!

i feel like offering sorting options not presented in columns might be weird though - the columns dictate what data is presented on the page, so i know what my sort options are. why would i need more? how is that list populated? etc


**Sara Hill**
Would you lean toward leaving sort in the column headers when the headers are present? I'm wondering if that's actually a limitation of the resource list. Since it wasn't intended to have column headers, that may not have been something we accounted for originally.

Here's the exploration with more robust sort in the column headers https://shopify.invisionapp.com/share/TCQPT259Z7V (edited) 


**Adam Whitcroft**
I feel like if we do show headers, they should be the controls for sorting the columns. if we don’t show the headers, the sort dropdown makes a lot of sense

but we should be consistent in either always having headers, or not; a mix and match might be weird

**Comment by ry5n** [comment]
If we do support columns in resource lists, they’ll be optional. We’ll have to support 2 ways of sorting on lists. Ideally those 2 ways would feel similar enough to not make people think when using one or the other.

Maybe something like this (top row is with columns, bottom row is without):

![image](https://user-images.githubusercontent.com/804014/53766172-fb0d3f80-3e86-11e9-9bc0-fa59e2b435db.png)

However, we had to scope this out of Better List Filters. In a medium-term future I’d also like to try getting rid of the “save filters” button and move saving/editing/deleting into the tabs themselves, basically what @AdamWhitcroft [explored a while ago](https://shopify.invisionapp.com/d/main#/console/13802456/292942742/preview).

**Comment by sarahill** [comment]
I'm going to close this issue for now. This is something we'll most likely want to revisit but we can re-open or create a new issue at that time.
