### ISSUE TITLE
DropZone.FileUpload errors using TypeScript

### ISSUE THREAD

**Issue by hgezim** [Shopify/polaris-react#1098]
# Issue summary
When using TypeScript, component `DropZone.FileUpload` requires properties `polaris`, and `contex`.

The example specified in [Drop zone docs](https://polaris.shopify.com/components/actions/drop-zone), shows this error in TypeScript:

> Type '{}' is missing the following properties from type 'Readonly<CombinedProps>': polaris, contextts(2739)

## Expected behavior
No error should be shown when `DropZone.FileUpload` is used with no properties.

## Actual behavior
This error is shown:

> Type '{}' is missing the following properties from type 'Readonly<CombinedProps>': polaris, contextts(2739)

## Steps to reproduce the problem

1. Setup a TypeScript react project using VS Code.
1. Use the following code to create a React app:

```
<AppProvider theme={theme}>
    <DropZone label="Picture">
            <DropZone.FileUpload />
        </DropZone>
</AppProvider>
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.9.0
- Browser: 
- Device:
- Operating System: Mac OS 10.14.3
- TypeScript: 3.3.1
- VS Code:  1.31.1

**Comment by AndrewMusgrave** [comment]
Hi @hgezim . Polaris is currently on ts `v3.1.6`, we have a few issue to address before updating.

**Comment by AndrewMusgrave** [comment]
Closing this issue for now. We'll address it when updating TS 🎉
