### ISSUE TITLE
[Icon]: New icon <icon-name>

### ISSUE THREAD

**Issue by jannamoreau16** [Shopify/polaris-react#11015]
### How will these icons be used?

This icon is for the new "Test Drive" feature that will live in org settings. This icon will be used within the top level settings list

Test drive is a new feature that will allow CCS & Plus merchants the ability to test selected features before they are released to their stores. Merchants can test these features in their development stores, and when ready they can add to all their stores within a 6 month period. 

[Design files](https://www.figma.com/file/WScC5YXq0Ox4ZiCAaPq8KW/Feature-Previews?type=design&node-id=789%3A26635&mode=design&t=xcbTuohO0dRlfsjH-1)
[Vault page](https://vault.shopify.io/gsd/projects/37119)

Icon ideas:
- Car steering wheel
- Car or car dashboard
- Winding Road
- Car keys
We are open to any of these icon concepts

### Icon name

Test drive

### What type of icon set?

Major (20x20)

### Icon description

**Wayfinding:** Used to help direct the merchants to the test drive page within settings

**Concept:** A great icon for this feature could be a steering wheel or a car dashboard. This icon would represent the idea of exploring or trying out something, similar to test driving a car. Another option could be an icon depicting a road or a winding path, symbolizing the journey of testing and experiencing a product or software. A key could also be a great icon, symbolizing the control to unlock something more and getting control of your features.

### Icon keywords

testing, preview

### Icon SVG code

```shell
<svg>...</svg>
```

**Comment by heyjoethomas** [comment]
Hey @jannamoreau16 if this is ready to contribute feel free to double check the [design specs](https://www.figma.com/file/fVIazfJNe3AOJTJmBKgTO9/Polaris-Gen-3-Icons?type=design&node-id=15287-119&mode=design&t=usOXD5jgVv6zcM2o-11) and then [contribute](https://polaris.shopify.com/contributing/icons) to the UI Kit as well as Polaris Icons with a PR

**Comment by heyjoethomas** [comment]
Being tracked [here](https://github.com/Shopify/polaris/issues/11214)
