### ISSUE TITLE
<Button /> giving errors on `url` prop

### ISSUE THREAD

**Issue by joshbedo** [Shopify/polaris-react#1102]
Trying to create a basic <Button /> element and added the prop `url='/campaigns/22'` but for some reason i'm seeing an error about a missing `to` property? 

```
The prop `to` is marked as required in `Link`, but its value is `undefined`
```

Polaris v2.7.0

**Comment by AndrewMusgrave** [comment]
Hi @joshbedo , we don't define prop types for our components or have a `to` prop. Is it possible your using a custom `linkComponent` and this error is coming from `react-router`?

**Comment by ry5n** [comment]
@joshbedo We need more information to help resolve this issue. If you can provide it, please re-open and we can help further.

**Comment by joshbedo** [comment]
Hey guys, sorry for the late response I'm using an older version of polaris where the `to` property is required. Seems like in the newer versions it was switched over to `url`

**Comment by ry5n** [comment]
Thanks for the clarification @joshbedo. If you’d like to upgrade to a newer version of Polaris and run into any issues, we’re happy to help. There is also a `#polaris` channel in the Shopify developers Slack at shopifypartners.slack.com that may be helpful. 💜
