### ISSUE TITLE
[polaris.shopify.com] Feedback (on /components/layout-and-structure/page?example=page-with-destructive-secondary-action)

### ISSUE THREAD

**Issue by raquelbreternitz** [Shopify/polaris-react#11034]
Hi, I think the code example on this section is broken?

**Comment by kyledurand** [comment]
It is 😢 It will be patched when 12.0.1 gets shipped https://github.com/Shopify/polaris/releases/tag/%40shopify/polaris%4012.0.1

**Comment by raquelbreternitz** [comment]
Very exciting, thank you Kyle! Just trying to share some examples around, I'll await 12.01!
