### ISSUE TITLE
[ResourceList] Make input field use type search instead of text

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react#1110]
# Feature request summary

The `ResourceList` provides a mechanism for search and it's likely desirable to make the `input` of type `search` for that particular component. Right now, it's using the default of type `text`.

## Rationale

By making the input of type `search` you would gain the benefits of a clear button (and escape key shortcut) from browsers that support it and the markup is also more semantically correct.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by mbaumbach** [comment]
It may make sense to extract the `SearchField` used in the `TopBar` or at least take some of the properties from it like:
```
autoCapitalize="off"
autoComplete="off"
autoCorrect="off"
```
I'm happy to work on a PR for this, but I thought it might be best to open the feature request and get some discussion on the following questions before diving into any code changes:

1. Is this even desired?
1. Should a shared component be used for the `TopBar` and the `ResourceList`, or is the styling too different?
1. What additional props might be relevant to make the search input more appropriate?

**Comment by AndrewMusgrave** [comment]
Using `type=“search”` makes perfect sense to me. This is something I wanted to add while using `ResourceList` in the admin but the default styling needs some work so we had to decided it out. @danrosenthal how does this fit in with the filters work your doing?

**Comment by dpersing** [comment]
@AndrewMusgrave I suspect the additional styling work would be out of scope for the current filters work, since the look of the form itself isn't changing for now. I think this would be a great to work in as we continue to work on the resource list!

**Comment by danrosenthal** [comment]
@AndrewMusgrave sorry for the delayed response. Devon is right that this is a bit out of scope for our project, but it's something that I think would make sense to add. It also aligns with adding a clear button on the text input.
