### ISSUE TITLE
[TextField] Add prop for clear button

### ISSUE THREAD

**Issue by tmlayton** [Shopify/polaris-react#1115]
# Feature request summary

Add prop to include a clear button like this:

![image](https://user-images.githubusercontent.com/344839/53624996-cbc0af00-3bb6-11e9-9008-149d5fa01326.png)
![image](https://user-images.githubusercontent.com/344839/53625063-f4e13f80-3bb6-11e9-97c7-e1424a18f27f.png)

## Rationale

This is already being done in various places, but requires a custom component because of the limitation of `TextField`

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by AndrewMusgrave** [comment]
Their was a similar feature request a couple days ago #1110

**Comment by yourpalsonja** [comment]
Closin' this b/c it's a dupe!
