### ISSUE TITLE
[Modal] Expose onScrolledToBottom on Modal from it's Scrollable implementation

### ISSUE THREAD

**Issue by posth** [Shopify/polaris-react#1116]
# Modal

If using [Scrollable](https://polaris.shopify.com/components/behavior/scrollable) as the **Modal's** content, it's `onScrolledToBottom` handler won't get triggered.

The **Modal** component implements it's own **Scrollable** [here](https://github.com/Shopify/polaris-react/blob/master/src/components/Modal/Modal.tsx#L254)

Maybe exposing that implementation's handler as a new prop on **Modal** may enable consumers of **Modal** to play around with infinite scrolling, for example.

## Examples

[Here is an example](https://codesandbox.io/s/n31x1mn0q4?fontsize=14) that uses **Scrollable** with a handler wrapped within the **Modal**.  The **Scrollable** handler does not get called when reaching the bottom.

The issue seems to be related to the content within **Scrollable** being dynamically generated, because [here is an example](https://codesandbox.io/s/kovqvozkpv) that has fixed content where the behavior is as expected.

[Here is an example](https://codesandbox.io/s/523xw3wpp4) of **Scrollable** on its own triggering the handler.

**Comment by AndrewMusgrave** [comment]
This makes sense to me. It'll prevent nesting `Scrollable` which may be weird UI issues. I think it'll be a great addition 😄

**Comment by AndrewMusgrave** [comment]
Looks like you'r already started a WIP pr so i'll assign this issue to you @posth

**Comment by posth** [comment]
Hey @AndrewMusgrave thanks for the quick feedback!  

Yes I went ahead and created a quick PR https://github.com/Shopify/polaris-react/pull/1117 for it
