### ISSUE TITLE
[polaris.shopify.com] Animation for "Interactions are quick" is jumpy

### ISSUE THREAD

**Issue by tjonx** [Shopify/polaris-react#11176]
## Issue summary

The page content in the "Interactions are quick" section under [Pro design language](https://polaris.shopify.com/design/pro-design-language#craft-juicy-interactions) jolts and makes the animation feel jumpy.

## Expected behavior

The content section should not jolt.

**Comment by zecarlostorre** [comment]
@tjonx I updated the animation in [the drive](https://drive.google.com/drive/folders/1zWYVuV3FnbNNtJeQSHxwZRWzGKl9wu3k)

Also attaching it here, in case it's more convenient:
https://github.com/Shopify/polaris/assets/55551051/46375198-47bf-422d-b8bb-4759d4ac2ae0
