### ISSUE TITLE
[Icon]: New icon components for Badge progress pips

### ISSUE THREAD

**Issue by albchu** [Shopify/polaris-react#11184]
### How will these icons be used?

In the designs for the RUM dashboard (Shopify/web), we are utilizing the Badge `progress` pips as the quality indicator for merchant storefronts. This is shown in the following views:

<img width="447" alt="image" src="https://github.com/Shopify/polaris/assets/5607117/beb6d73c-b45d-43ab-9199-ec05a75aeb97">
<img width="1175" alt="image" src="https://github.com/Shopify/polaris/assets/5607117/7a7fe92e-8816-4ca5-89af-d34b404b4e82">

In a separate hover label, we wish to use the pips as an extension of this usage to highlight deeper information. 
<img width="739" alt="image" src="https://github.com/Shopify/polaris/assets/5607117/3bc5c04a-c190-408d-9e18-640afa6ff929">

Unfortunately the implementation of these pips are localized to the `Badge` component in Polaris 12. This means we need to duplicate these svg definitions rather than being able to import from `polaris-icons`.

https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Badge/Badge.tsx#L40-L60

### Icon name

Progress

### What type of icon set?

Unsure

### Icon description

Used to denote the progress as shown in badges

### Icon keywords

incomplete, partiallyComplete, complete

### Icon SVG code

```shell
https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Badge/Badge.tsx#L40-L60
```

**Comment by bernardojoaogarcia** [comment]
This is currently being addressed in the Micro icons issue.

**Comment by alex-page** [comment]
Closing this issue as it is now considered a duplicate of https://github.com/Shopify/polaris-internal/issues/1072
