### ISSUE TITLE
TextField readOnly prop ignored when type="number"

### ISSUE THREAD

**Issue by matt-neill** [Shopify/polaris-react#1118]
# Issue summary

When the `type="number"` prop is present on the TextField component, the `readOnly` prop does not disable or remove the number steppers.  The user can still click the up/down arrows to change the field's value.

## Expected behaviour

Similar to how `disabled` fields are treated when `type="number"`, remove the number steppers to prevent the value from being changed.

## Actual behaviour

The user can click the up/down arrows (the number steppers) to change the field value, despite the `readOnly` prop being present.

## Steps to reproduce the problem

1.  Create a TextField component
1.  Add the `type="number"` prop
1.  Add the `readOnly` prop
1.  Click the up/down arrows (the number steppers) and see the field's value change

## Reduced test case

Check out this [Codesandbox project](https://codesandbox.io/s/p3689vv2m7)

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 3.9.0
- Browser: Chrome 72.0.3626.109
- Device: MacBook Pro
- Operating System: macOS Mojave (10.14)

**Comment by chloerice** [comment]
Hi @matt-neill, [removing the `onChange` prop](https://codesandbox.io/s/ojvp71nv3y) on the `readOnly` `TextField` prevents the steppers from incrementing/decrementing, but they still aren't disabled as I'd expect them to be in a `readOnly` number component. Thanks for raising this!!

**Comment by cloneali** [comment]
Can I work on this one?

**Comment by chloerice** [comment]
@cloneali Absolutely! Ping me on the PR when you're ready for review 😃

**Comment by cloneali** [comment]
Cool. Can you assign me this issue? As I am not a member or collaborator in this project. Thanks.

**Comment by chloerice** [comment]
Ahh right looks like it's not possible to actually assign this to you, but it's clear from the comments that you're taking it on, so there shouldn't be anyone doubling up 👍
