### ISSUE TITLE
ResourceList shows nothing when empty

### ISSUE THREAD

**Issue by AKarmanov** [Shopify/polaris-react#1120]
# Issue summary

If I have an empty array fed to resource list I see nothing.

## Expected behavior

I suspect it should show some kind of empty message and keep header displayed to allow filtering etc. after all I do specify resource name so something like "Couldn't find resourceName.plural" or something like that would be appropriate.

## Actual behavior

As soon as items becomes `[]` (an empty array) everything disappears.

## Steps to reproduce the problem

1. Go here https://codesandbox.io/s/236qy68230?module=App.js
2. Set items to `[]`
3. Observe everything disappear

## Specifications

- Are you using the React components? (Y/N):Y
- Polaris version number: 3.9.0 
- Browser: Chrome
- Device: Desktop
- Operating System: Ubuntu

**Comment by dleroux** [comment]
Thanks for bringing this up @AKarmanov. We do take this into consideration when there's filtering https://codesandbox.io/s/qkxk9j5z8w?fontsize=14 but not when there isn't. As you can see we do use the resource name in that scenario.  The reasoning is that without filtering the list only renders/updates on initial load and the developer can handle rendering the list or not based on the results. Is there a usecase where that may not be the case? 

Let me ping a few designers for thoughts on this as well: @sarahill @ry5n

**Comment by AKarmanov** [comment]
In my case I was planning on using an "alternateTool" to provide custom options for the list, I can technically move it out or try to use a filter (which has search field which I don't need).

I think that ignoring presence of the list is a bit harsh though. The user doesn't know that there is a list in that area and if I have other components, say a pagination component right below it is still visible, unless I hide it that is. These are my thoughts.

**Comment by dleroux** [comment]
👍 I agree with you that showing nothing at all may be confusing. Not sure the current `empty search` image we have would be appropriate in this case scenario. I'll let others way in a well, but it's probably best we do output something because outputting something custom will still be possible.

**Comment by chloerice** [comment]
Gonna link this to the new empty state work => #1570
