### ISSUE TITLE
[Icon]: New icons for privacy features

### ISSUE THREAD

**Issue by annettasillard** [Shopify/polaris-react#11215]
### How will these icons be used?

The privacy team is going to ship a new surface in admin Settings, where we'd need 4-5 new relevant icons. 
Context here:
https://www.figma.com/file/2HD4Y8xLSjbmN2BWDrFc3o/Customer-privacy---centralised?type=design&node-id=3419-255885&mode=design&t=YS4C0Na8ogiL1ilV-0

### Icon name

Customer privacy

### What type of icon set?

Major (20x20)

### Icon description

Concept and Wayfinding

### Icon keywords

customer privacy, privacy

### Icon SVG code

```shell
<svg>...</svg>
```

**Comment by annettasillard** [comment]
Hey @heyjoethomas, 
I would love some help with new icons for a new admin Settings page, both in terms of concepts and design. We're aiming to ship in mid January. Happy to schedule a call soon to talk about our options.

**Comment by zecarlostorre** [comment]
@annettasillard, we're doing a series of icon updates, and I'd love to include these in the same batch.

Can you set up some time with me, for us to look into this?

**Comment by alex-page** [comment]
@zecarlostorre @annettasillard lets make this happen. Would love to have this image approved and good to go by EOD tomorrow if we want it in the library.

**Comment by zecarlostorre** [comment]
@alex-page This will likely take a bit longer to get the icons ready, since we're talking about multiple icons that need to be creates and reviewed/approved by stakeholders.

@annettasillard will come back to us when she has a better idea on the metaphors.
The good news is that these will only be needed for winter editions, so we have a bit time to get these right.

**Comment by alex-page** [comment]
All good. No rush. This work will likely be in a follow up release for icons. I will make it clear on our project board that this is not going to happen immediately.

**Comment by lgriffee** [comment]
@annettasillard @zecarlostorre @alex-page Should this issue still remain open?

**Comment by lgriffee** [comment]
Closing this issue. Feel free to reopen if needed!
