### ISSUE TITLE
Modal Docs update

### ISSUE THREAD

**Issue by alexdover** [Shopify/polaris-react#1121]
Just a quick one - it would be great if you could make it clearer in the docs that the `children` props are only supported for stand-alone app use only. I have just spend some time trying to debug and work out why my modal wasn't showing and then noticed the message in brackets! Or make the example based on an embedded app, which I suspect most people will be using.

**Comment by HParker** [comment]
There does seem to be a section with a embedded app example [here](https://polaris.shopify.com/components/overlays/modal#section-use-in-an-embedded-application), but I agree it could be more prominent.
