### ISSUE TITLE
ResourceItem click snaps back to the top of the resourceList [Urgent issue]

### ISSUE THREAD

**Issue by da3ba** [Shopify/polaris-react#11233]
## Issue summary

I'd like to prevent the default behavior that happens when I click on a resourceItem, currently when I click it and the resourceList is scrollable it snaps to the top of the list which is weird, I want to prevent this but don't know how, the event that the onClick returns has a value of integer 1 so I can't use the method preventDefaullt!!

## Expected behavior

If this is not a default behavior then please suggest a workaround as this is an urgent matter for us. If it is default then how to prevent it.

## Actual behavior
When clicking on a resourceItem in a scrollable resourceList then it snaps to the first element on top.

## Steps to reproduce the problem

Try the following sandbox:

https://codesandbox.io/p/sandbox/wizardly-mcnulty-2yk53x?file=%2Findex.tsx

Scroll down and click on a resource item, it will snap and get back to the top of the list.

## Reduced test case

Just try a simple resourceList with resourceItems to the the point that the list is scrollable.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: Any
- Browser: Chrome
- Operating System: Windows

**Comment by iamphonghg** [comment]
You better fork a sandbox.

**Comment by da3ba** [comment]
@iamphonghg , Here it is: https://codesandbox.io/p/sandbox/wizardly-mcnulty-2yk53x?file=%2Findex.tsx
You can scroll down and click on a resource item, you'll notice that it snaps and gets back to the top of the list.

**Comment by iamphonghg** [comment]
Do you notice that the url for the resource item is "#"? That's the reason. @da3ba

**Comment by da3ba** [comment]
Thanks @iamphonghg that was the reason, I appreciate the help :)
