### ISSUE TITLE
Better control over field width

### ISSUE THREAD

**Issue by michaelgrigoriev** [Shopify/polaris-react#1123]
# Feature request summary

Field width should be flexible to accommodate more realistic entries. 

## Rationale

We have standard full-width fields that don't work super well and wouldn't score very high from a usability standpoint given variability in possible inputs and meaning of those fields. The field should be closer to actual realistic entries so that users don't misinterpret the significance of the field. Additionally, ultra long fields for short inputs look akward, especially with connected fields.

Currently, we have examples of fields that would realistically only contain a max 3 units of input, but are full width across a card.

Check out this article (point #4) on field width. https://uxplanet.org/10-rules-for-efficient-form-design-e13dc1fb0e03

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by danrosenthal** [comment]
Things can get pretty ugly in cases like this:

|gross|
|-|
|![image](https://user-images.githubusercontent.com/594960/53760959-4e38bf80-3e92-11e9-9d5c-d7ecc8d379fe.png)|

cc: @sarahill @ry5n

**Comment by ry5n** [comment]
Bang on.

For the moment, it’s possible to have some control over overall field width using `FormLayout.Group` and some empty spans: https://codesandbox.io/s/0q865n15pw

However, it’s only a rough approximation of what you’re after. Ideally we want a way to hint to the field what width it should be, while still allowing a parent layout to have some control. (At small screen widths we might want to force the field to be full width.) I’m not sure how best to achieve both of these things.
