### ISSUE TITLE
[Icon]: New icon <google>, <criteo>, <meta>

### ISSUE THREAD

**Issue by annaofthewoods** [Shopify/polaris-react#11242]
### How will these icons be used?

The Audience app needs additional logo icons to reflect all the third party(3P) platforms it supports.

These icons will be used in buttons to denote that the action needs to be completed on the 3P ad manager. These buttons will close out a UI change request from Carl Rivera  and Andrea Mangini. [See thread](https://vault.shopify.io/gsd/reviews/29168#gsd_comment_66211)

These icons will be used alongside existing social logos already in Polaris

<img width="490" alt="Screenshot 2023-11-27 at 11 18 47 AM" src="https://github.com/Shopify/polaris/assets/18662293/8499b39b-947c-44b4-835b-0efbd7a249a4">

### Icon name

Google, Criteo, Meta

### What type of icon set?

Major (20x20)

### Icon description

**Concept**
Part of the 'logos' collection in the 'main set' and used to represent 3P platforms. However, these may not be considered 'social' like others in the list.

### Icon keywords

google, criteo, meta

### Icon author

Anna de Medeiros

### Icon Figma link

https://www.figma.com/file/5yI6BKnBU5oUV8PXpVqYn8/3P-platform-links?type=design&node-id=62%3A3251&mode=design&t=DjcHe3FDh3M4Ljd2-1

### Icon SVG code

```shell
<svg>...</svg>
```

**Comment by alex-page** [comment]
In the past we had a strong opinion that logos should not be a part of the icon library. Not against adding logos but there is a lot of logos that we could add to the library. Should we open this can of worms? How do we know what icons are valuable to add and what are not?

**Comment by alex-page** [comment]
@zecarlostorre some additional logos from the admin. I think some can be replaced when we fix up currentColor but if there are gaps please add them to this issue if we want to add logos.

```
export {default as FacebookLogoMinor} from './facebook-logo-minor.svg?react';
export {default as HydrogenMajor} from './hydrogen-major.svg?react';
export {default as PinterestLogoMinor} from './pinterest-logo-minor.svg?react';
export {default as RedditLogoMinor} from './reddit-logo-minor.svg?react';
export {default as TwitterLogoMinor} from './twitter-logo-minor.svg?react';
export {default as InstagramLogoMinor} from './instagram-logo-minor.svg?react';
export {default as SnapchatLogoMinor} from './snapchat-logo-minor.svg?react';
export {default as TikTokLogoMinor} from './tiktok-logo-minor.svg?react';
export {default as TumblrLogoMinor} from './tumblr-logo-minor.svg?react';
export {default as VimeoLogoMinor} from './vimeo-logo-minor.svg?react';
export {default as YouTubeLogoMinor} from './youtube-logo-minor.svg?react';
```

**Comment by zecarlostorre** [comment]
@alex-page I think there's some value in adding these to our set, mainly to avoid folks from adding their own versions and using them in weird sizes, that will make the UI look jarring.

I think we can draw the line saying we only support social media/sales channels, since those are the cases that I expect an overlap with commerce use cases.

@heyjoethomas @sarahill - any thoughts on this?

**Comment by annaofthewoods** [comment]
Criteo might be a bit of the outlier in this set if we stick to the above criteria. We can always maintain that one in our end if that makes more sense. Let me know.

**Comment by alex-page** [comment]
If the icon is going to be used by multiple teams and in multiple places it would be best to add it. If we are unsure, we can always let your team maintain the icon and add it at a future time when we notice an uptick in usage.

**Comment by alex-page** [comment]
@zecarlostorre seems like folks want these added based on 👍 reactions. Lets get a zip together and add these icons.

**Comment by zecarlostorre** [comment]
Here it is @alex-page [Logo-icons.zip](https://github.com/Shopify/polaris/files/13548703/Logo-icons.zip)

@annaofthewoods I already added them to the Figma Library, I made small adjustments and tagged you as a reviewer. Let me know if you see anything strange.

**Comment by zecarlostorre** [comment]
@alex-page one question for you:

We had all the logos with the prefix `Social`, because they were all social media, but if we're expanding the logos we support, do you think it makes sense to rename all the logos that currently look like this `SocialName` to be `LogoName` instead?

**Comment by alex-page** [comment]
@zecarlostorre it depends on our plans for future icons. I don't mind either approach. `Social` is narrow to social media logos and we definitely could add things like payment logos e.g. Apple Pay. Do we then add `PaymentApple` 🤷 

@heyjoethomas do you have any opinions on `Social` vs `Logo`?

**Comment by heyjoethomas** [comment]
> @heyjoethomas do you have any opinions on `Social` vs `Logo`?

Logo as the prefix makes sense to me.

**Comment by alex-page** [comment]
@heyjoethomas @zecarlostorre sounds good to me. I am going to keep `SocialPostIcon` and `SocialAdIcon` as they are not logos. Let me know if there are any concerns.

**Comment by alex-page** [comment]
@annaofthewoods @heyjoethomas @zecarlostorre all the changes are in this commit https://github.com/Shopify/polaris/pull/11138/commits/2fc0b42b9570c01fdc537ce4415cf9f65624b3ed Let me know if there are any issues.

**Comment by zecarlostorre** [comment]
Legend! Thanks @alex-page!
I'll update the icon library accordingly.

**Comment by annaofthewoods** [comment]
Thanks everyone, this looks great!

I kept trying to approve the Figma changes but it kept hitting me with errors.

**Comment by lgriffee** [comment]
Just adding this here for my own project documenting purposes: 
![Screenshot 2023-12-07 at 11 07 16 AM](https://github.com/Shopify/polaris/assets/21976492/9b04ebdd-f012-483c-8c24-4730248eca4f)

**Comment by alex-page** [comment]
The work is done and it will be released with Polaris icons v8

**Comment by alex-page** [comment]
Forked logo icons in `shopify/web` that have replacements in Polaris

- [x] `FacebookLogoMinor`
- [ ] `HydrogenMajor`
- [x] `PinterestLogoMinor`
- [ ] `RedditLogoMinor`
- [x] `TwitterLogoMinor`
- [x] `InstagramLogoMinor`
- [x] `SnapchatLogoMinor`
- [x] `TikTokLogoMinor`
- [x] `TumblrLogoMinor`
- [x] `VimeoLogoMinor`
- [x] `YouTubeLogoMinor`
- [ ] `ShopMinor`

**Comment by lgriffee** [comment]
Adding "blocked" tag since this issue is dependent on #11088 which is also currently blocked.

**Comment by lgriffee** [comment]
- https://github.com/Shopify/polaris/issues/11088 has shipped! 🥳
