### ISSUE TITLE
[ComboBox] Keypress test suite has false positives

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react#1124]
# Issue summary

[These async functions](https://github.com/Shopify/polaris-react/blob/e7a4eb852df5f0935c8dca7b7f1794b888e9af51/src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx#L431) are not ever invoked, so the `expect` lines in them aren't ever hit.

**Comment by AndrewMusgrave** [comment]
We noticed this [awhile ago](https://github.com/Shopify/polaris-react/pull/480#discussion_r232341581) although I wasn't aware the pr never shipped 😬 If I recall @danrosenthal mentioned previously writing up a brief to refactor `AutoComplete` with Tim?

**Comment by danrosenthal** [comment]
That's right @AndrewMusgrave, the issue for that is [here](https://github.com/Shopify/polaris-react/issues/689). @tmlayton mentioned he had it nearly done in a recent chat

In the mean time, we should consider just reverting this commit: https://github.com/Shopify/polaris-react/commit/f894f347c3fd61a10519ef4078bc6bc37884ede9

**Comment by AndrewMusgrave** [comment]
It looks like the PR added some key handlers as well. Do we think it's more worthwhile to make all the tests run and skip ones that fail for now?

**Comment by danrosenthal** [comment]
From what I can tell, each of those cases was already handled by vanilla event handlers. Can you confirm?

**Comment by AndrewMusgrave** [comment]
👀

**Comment by AndrewMusgrave** [comment]
It looks like the events we're previously handled however they were on the `combobox` opposed to `document`. Seems the PR [may include](https://github.com/Shopify/polaris-react-deprecated/pull/2364/files#diff-76b2ad40e33f2b380b15d0bf5a7cd41dR181) a `popover` bug fix (not positive without digging into it)

**Comment by chloerice** [comment]
Yeah, I'd rather just fix the tests. Just need to trigger the listener component and 🔥 the listener map mock.

**Comment by AndrewMusgrave** [comment]
I'll take a look today and see if I can refactor the breaking tests

**Comment by AndrewMusgrave** [comment]
@chloerice Sorry I totally missed the fact you assigned this to yourself 😨
