### ISSUE TITLE
Small screen responsive issue with Navigation 

### ISSUE THREAD

**Issue by lizkhoo-shop** [Shopify/polaris-react#11257]
## Issue summary

On smaller screen/browser size, the Navigation menu top item has an extra line when the subnav item is selected. Also, the top level item is duplicated.

## Expected behavior

No line on the top item of Navigation and no duplication of top item.

## Actual behavior
<img width="445" alt="29-33-7wlq2-j3ugg" src="https://github.com/Shopify/polaris/assets/80916759/630f0bc4-85a3-4b15-a214-7c40a86d4653">

## Steps to reproduce the problem

1. Open Admin
2. Select any navigation item
3. Make your browser window narrow enough to collapse Navigation
4. Reopen Navigation to see the bug

**Comment by sophschneider** [comment]
This was fixed in https://github.com/Shopify/polaris/pull/11206. Original issue https://github.com/Shopify/polaris-internal/issues/1220
