### ISSUE TITLE
Button - external not parsed correctly

### ISSUE THREAD

**Issue by owlyowl** [Shopify/polaris-react#11291]
## Issue summary

When trying to use external in the Remix App Template with a `Button` the typing is correct and `external` is a boolean.

When rendering in the browser it renders the link but `target` isn't present and the `url` property still is.
`<a data-polaris-unstyled="true" class="Polaris-Button Polaris-Button--primary" url="https://www.shopify.com/" href="https://www.shopify.com/"><span class="Polaris-Button__Content"><span class="Polaris-Button__Text">Hi!</span></span></a>`

## Expected behavior

Button should open URL in an external window and markup should render correctly

## Actual behavior

![image](https://github.com/Shopify/polaris/assets/1916426/c35f8587-3e38-40e7-9d35-9105f2f4c7b8)
![image](https://github.com/Shopify/polaris/assets/1916426/18830856-ed37-4831-9d25-d7cbf8d43bd6)

## Steps to reproduce the problem

1. Create a Button like so ```<Button variant="primary" url={myUrl} external>Hi!</Button>```

## Specifications

- Are you using the React components? (Y): Yes
```
@shopify/polaris: ^12.0.0 => 12.0.0
react: ^18.2.0 => 18.2.0
react-dom: ^18.2.0 => 18.2.0
```

**Comment by axis80** [comment]
This issue is still present in Polaris 13.9.3.  Can this issue be reopened?
