### ISSUE TITLE
[Collapsible] Accordion animation not smooth

### ISSUE THREAD

**Issue by ry5n** [Shopify/polaris-react#1133]
When animating a `Collapsible` section, if it has spacing (margin, padding) around the content that is being animated, it causes jank:

![jank](https://user-images.githubusercontent.com/344839/58289103-48a09680-7d6a-11e9-88f3-845bf0295469.gif)

Reduced test case: https://codesandbox.io/s/stoic-mirzakhani-v4ino

**Comment by alex-page** [comment]
I'd be keen to look into this.

This is usually a problem with accordion moving multiple elements below it. This causes a repaint on the entire section and janky animation. We could probably replicate this on a page with a lot of content below and accordion, or a page with multiple accordions being triggered by one toggle.

We also might be able to make this slightly more performant using [FLIP](https://css-tricks.com/animating-layouts-with-the-flip-technique/#article-header-id-1).

**Comment by johanstromqvist** [comment]
I share the assessment. The uneven transition is likely due to two transitions unintentionally happening in sequence, and that there probably are opportunities to prevent jank.

I'd happily pair with you on this @alex-page! We could identify other places where such repaints happen, make that example of perf bottleneck, and develop a UX Dev guideline for `transform` usage and `FLIP`.

**Comment by ry5n** [comment]
For the [Better List Filters project](https://github.com/Shopify/polaris-react/projects/2), this is something we need to fix ASAP in order to ship, so I’d prefer to tackle this at the project level before broadening scope.

@danrosenthal Could you use the help on diagnosing this?

**Comment by sarahill** [comment]
Issue with activator height with no badge vs. badge. Need to make a design decision around this.

**Comment by ry5n** [comment]
Can confirm this is not an issue with the Polaris component, but with the particular design on this project.

**Comment by tmlayton** [comment]
Doing a bit more digging into this, looks like two issues at hand. The first is related to the badges being present in the selector, the other is animating content with padding (and margins?). Likely, using FLIP would fix the latter.

### With badge (project specific issue)
![with badge](https://user-images.githubusercontent.com/344839/58289091-3d4d6b00-7d6a-11e9-9979-e63fbb8151b4.gif)

### Jank
![collapsible issue](https://user-images.githubusercontent.com/344839/58289100-44747900-7d6a-11e9-8a00-c77c1eb58704.gif)

### Jank (reduced test case)
![jank](https://user-images.githubusercontent.com/344839/58289103-48a09680-7d6a-11e9-88f3-845bf0295469.gif)

**Comment by tmlayton** [comment]
I updated this issue to be about addressing the bug in `Collapsible` and will create another issue about the `ListFilters` component. Will move this issue out of the ListFilters project.
