### ISSUE TITLE
[List filters] Save filters button icon and copy

### ISSUE THREAD

**Issue by ry5n** [Shopify/polaris-react#1139]
There was a typo in the content spec that led to some of copy for the save filters button being incorrect.

#### Expected

| All tab | Untitled tab | Saved tab |
| --- | --- | --- |
| <img width="136" alt="screen shot 2019-03-06 at 12 43 13 pm" src="https://user-images.githubusercontent.com/804014/53912250-6da82780-400d-11e9-91cb-ab0f2105b7e8.png"> | <img width="136" alt="screen shot 2019-03-06 at 12 43 52 pm" src="https://user-images.githubusercontent.com/804014/53914924-97fce380-4013-11e9-9344-5367f2df055d.png"> | <img width="142" alt="screen shot 2019-03-06 at 1 35 12 pm" src="https://user-images.githubusercontent.com/804014/53915420-bc0cf480-4014-11e9-8794-491ad0471c6b.png"> |

#### Actual

| All tab ⚠️ | Untitled tab ⚠️ | Saved tab ✅ |
| --- | --- | --- |
| <img width="133" alt="screen shot 2019-03-06 at 1 32 41 pm" src="https://user-images.githubusercontent.com/804014/53915221-68021000-4014-11e9-87b1-7dd5c87e1d93.png"> | <img width="138" alt="screen shot 2019-03-06 at 1 33 41 pm" src="https://user-images.githubusercontent.com/804014/53915297-7ea86700-4014-11e9-8d6e-2f61963b2de3.png"> | <img width="136" alt="screen shot 2019-03-06 at 1 34 29 pm" src="https://user-images.githubusercontent.com/804014/53915365-9c75cc00-4014-11e9-9325-829fc9d62372.png"> |

**Comment by ry5n** [comment]
@VanjaMitrovic Can you double-check I have this right?

**Comment by VanjaMitrovic** [comment]
expected is 👍

**Comment by danrosenthal** [comment]
Icons fixed here: https://github.com/Shopify/web/pull/11804
