### ISSUE TITLE
Index table row navigation with dataPrimaryLink only works once

### ISSUE THREAD

**Issue by jaret32** [Shopify/polaris-react#11406]
## Issue summary

When clicking on an index table row containing a link element with `dataPrimaryLink` and `target="_blank"`, the link opens in a new tab. After navigating back to the application and clicking on the index table row again, nothing happens. The application must be refreshed before the link will open again.

## Expected behavior

The link should open in a new tab again.

## Actual behavior

Nothing happens.

## Steps to reproduce the problem

1. Click on the index table row (not the link)
2. The link should open in a new tab
3. Navigate back to the application
4. Click on the index table row again (not the link)
5. Nothing happens

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

[Reduced test case](https://codesandbox.io/p/sandbox/shopify-polaris-react-typescript-playground-forked-9kd8k5)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 12.6.0
- Browser: Chrome
- Device: MacBook Air M1 2020
- Operating System: macOS Ventura 13.1

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 75.78 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.21 - ~/Documents/victron-energy-shopify/node_modules/.bin/yarn
    npm: 9.9.2 - ~/Documents/victron-energy-shopify/node_modules/.bin/npm
  Browsers:
    Chrome: 120.0.6099.199
    Safari: 16.2
  npmPackages:
    @shopify/polaris: ^12.0.1 => 12.0.1 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
```

**Comment by chloerice** [comment]
Duplicate, closing in favor of https://github.com/Shopify/polaris/issues/4345
