### ISSUE TITLE
[List Filters] Make width of the popover the same across states (set a min-width for larger breakpoints)

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#1156]

**Comment by gil--** [comment]
A min-Width for mobile would be nice too. Currently running into this issue:

### Desktop:

<img width="266" alt="Screen Shot 2019-04-07 at 11 57 32 AM" src="https://user-images.githubusercontent.com/3484527/55686219-6639ae00-592c-11e9-81ef-fe8d7d063dae.png">

### Mobile
<img width="163" alt="Screen Shot 2019-04-07 at 11 57 41 AM" src="https://user-images.githubusercontent.com/3484527/55686222-6df95280-592c-11e9-8072-25c928fb676b.png">

**Comment by danrosenthal** [comment]
@gil--, this is an issue for an internal project (a practice we'll be getting moving away from going forward). Would you mind filing a separate issue for the `min-width` issue?
