### ISSUE TITLE
Page component max width on the subTitle

### ISSUE THREAD

**Issue by Vanley** [Shopify/polaris-react#11594]
### Summary

There is newly introduced change https://github.com/Shopify/polaris/pull/11567 to the subTitle in the Page component which is setting max-width to 45ch which in bigger screen resolution creates unpleasant line break.

### Expected behavior

SubTitle should be allowed to grow if there are no buttons on the right.

### Actual behavior

On bigger screen resolutions width limit in this form creates awkward line break with lots of empty space.
![image](https://github.com/Shopify/polaris/assets/9288093/da0a9a31-44e1-465d-9153-755d9bc23767)

### Steps to reproduce

Use React Page Component with subTitle longer than 45 characters.
https://polaris.shopify.com/sandbox?code=N4IgLgFgpgtlDOIBcBtEAbA9gYwIbqiSgDsQBdAGhAHcBLAE0kVQHYA2ADjIF8g

### Are you using React components?

None

### Polaris version number

12.14.0+

### Browser

any

### Device

any

**Comment by Vanley** [comment]
Related to this change https://github.com/Shopify/polaris/pull/11567 @raphaelghub @mrcthms

**Comment by Vanley** [comment]
still valid with Polaris version 12.19.0

**Comment by pritika55** [comment]
@Vanley i was having the same issue but i believe this was fixed in 12.17.0! https://github.com/Shopify/polaris/pull/11602 for reference

**Comment by Vanley** [comment]
@pritika55 it fixing some, but sadly not all. 
When there is at least one action button on the right then subtitle is still only 45ch in size. Which on medium and bigger screens subtitle is wrapped to second line leaving lots of empty space on the right side as per 
https://polaris.shopify.com/sandbox?code=N4IgLgFgpgtlDOIBcBtEAbA9gYwIbqiSgDsQBdAGhAHcBLAE0kVQHYA2ADjIF8g
