### ISSUE TITLE
[List filters] Anayltics tracking, tagging

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react#1163]

**Comment by StephPoce** [comment]
**To be tracked**
These are the things we (Sonja & Steph) talked with Ali Wytsma about:

- Opt in/Update later
- Allow Sharing/Skip
- Switch Back
- Feedback link (open)

Filtering Actions:
- option/facet selection (checkbox/radio)
- Search queries (filter orders field)
- Popover opens
- Filter 'Sheet' open/close
- Collapsible opens in sheet
- Sort open and selection
