### ISSUE TITLE
New component: ExpandingDiv

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#1169]
## Problem

When adding and removing filters, it is unclear what is happening to the list. The transition of adding tags, removing tags, and updating the list of results is jarring and confusing.

![Screen Capture on 2019-03-13 at 09-52-25](https://user-images.githubusercontent.com/8629173/54284181-df382680-4575-11e9-9322-4ac990b18dae.gif)

## Possible solution

An `ExpandingDiv` component, which would animate between its height changes.

Example uses:

```tsx
<ExpandingDiv>
  {myDynamicContent}
</ExpandingDiv>
```

This component would have the exact same default properties as a `div`, but as its height changed due to child elements being added, removed, or modified the transition would be animated.

**Comment by sarahill** [comment]
@johanstromqvist Your guidance on this would be much appreciated.

**Comment by johanstromqvist** [comment]
@sarahill Let's pair up on this.

**Comment by tmlayton** [comment]
This can also apply to the badges in the collapsible togglers. We show a badge for applied values in the toggler when the collapsible is closed. When opening, the height quickly shifts and appears to be animation jank:

![jank](https://user-images.githubusercontent.com/344839/58289959-e09f7f80-7d6c-11e9-82e3-d4c246d90806.gif)

**Comment by tmlayton** [comment]
Just repurposed this issue to be a new component proposal for `ExpandingDiv` and added a section "Possible solution" with details about how this might work.
