### ISSUE TITLE
[List filters] Test with locations enabled

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#1170]

**Comment by ry5n** [comment]
Locations themselves are now out of beta, so don’t require beta flags. To test, I started with React routed enabled (“internal routes”) and the following flags turned on:

- `better-list-filters-opt-in`
- `new_admin_order_index_route` 

I didn’t add more than one order.

Then, 🎩 

- I went to Settings > Locations and added a location called “Paris warehouse” using a real address in Paris
- On the orders list page, I added different combinations of filters and made sure the results made sense
- I switched the location filter to the default location and did more filtering
- I switched the location filter to the Paris location and changed filters

I noticed some issues with the location switcher, but no issues with the filtering functionality or appearance that haven’t been logged elsewhere.
