### ISSUE TITLE
[List filters] Usability testing with merchants

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react#1174]
We are working with Seneca on getting a plan together for merchant testing.

- [x] Which merchants are we testing with
- [x] Research plan
- [x] Tasks for merchant testing
- [x] Recruiting email
- [x] Schedule sessions

**Comment by senecabrandi** [comment]
recruitment list: https://docs.google.com/spreadsheets/d/1VPQI8hBhDztlnMsSiSB7gG1dTQTGhTFzQHKDuoiaejo/edit?usp=sharing

**Comment by senecabrandi** [comment]
research plan: https://docs.google.com/document/d/1dJV3dAfghkIbPAFWJ11SV6PTvSJwjznpTBDuJLOYG1M/edit?usp=sharing

**Comment by senecabrandi** [comment]
report:
https://docs.google.com/presentation/d/1fVBrKuAuRwzU5vy3DrEjMuBIAcivU3rBL5qJfbJpggs/edit?usp=sharing
