### ISSUE TITLE
Request manual translations for feedback form

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react#1175]
[Request manual translation](https://vault.shopify.com/Manual-Translation-Requests-in-Smartling)

**Comment by sarahill** [comment]
The following `.txt` files have been submitted for translation in Smartling.

[Send feedback - for translation.txt](https://github.com/Shopify/polaris-react/files/2962850/Send.feedback.-.for.translation.txt)

[Send feedback on switch back - for translation.txt](https://github.com/Shopify/polaris-react/files/2962851/Send.feedback.on.switch.back.-.for.translation.txt)


Confirmation of submission
![image](https://user-images.githubusercontent.com/8629173/54301143-bffcc180-4594-11e9-8dd9-5247c4cf1f3c.png)

**Comment by tmlayton** [comment]
I’m not sure if the merchant feedback forms support i18n: https://merchant-feedback.shopify.com/admin/feedback_forms/86/edit

**Comment by sarahill** [comment]
Some of the translations are done so I went ahead and created forms  for those languages:
French, German, Italian, Spanish

![image](https://user-images.githubusercontent.com/8629173/54560537-f07b9b80-4998-11e9-9e2e-dcac29f49734.png)

**Comment by sarahill** [comment]
@tmlayton Here are the feedback forms for the different languages:

- Better list filters
- Better list filters - FR
- Better list filters - IT
- Better list filters - DE
- Better list filters - ES
- Better list filters - pt-BR
- Better list filters - zh-CN
- Better list filters - zh-TW
- Better list filters - pt-PT

Working on the switch feedback forms.

**Comment by sarahill** [comment]
@tmlayton translated forms for when merchant switches back:
List filters switch back feedback
List filters switch back feedback
List filters switch back feedback
List filters switch back feedbackList filters switch back feedback
