### ISSUE TITLE
[List filters] Feedback form questions

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react#1176]
We are providing two paths for the merchant to provide feedback on the new filters.

1. Once the merchant opts into the new filters, they will be able to leave feedback at any point. A link to `Send feedback` will be in the `Early access` banner.

2. If the merchant decides to `Switch back`, we will give them a path to `Send feedback` in the confirmation toast.

The feedback forms are one way we are collecting qualitative feedback from merchants.

**Comment by VanjaMitrovic** [comment]
The WIP content doc (under V3)
https://docs.google.com/document/d/15-Jm_KvgnwDGBOYMUaIpC1yu2LCMOmh8mUphaUnDUv8

**Comment by sarahill** [comment]
Related to https://github.com/Shopify/polaris-react/issues/1175#issue-419690149

**Comment by VanjaMitrovic** [comment]
New doc with final questions. Feel free to comment: https://docs.google.com/document/d/1gl-L8ODAV3teCwowZtGIKsHqlwsPJsC2YYETQ9xwcbU/edit

**Comment by sarahill** [comment]
👍 This look good to me. If everyone is cool with it I say we go ahead and start submitting this for translation.

**Comment by ry5n** [comment]
This looks really good to me, and I’m happy shipping with it 🎉

**Comment by StephPoce** [comment]
@sarahill We're good to go on this. There was a small change based on feedback from Kyle but the doc has been updated and it's ready for translation.

**Comment by sarahill** [comment]
Sounds great! I'm going to close this issue and handle the translation submission in #1175
