### ISSUE TITLE
[List filters] fix translations on `ListFilters` component

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#1178]
`Cannot read property 'translate' of undefined`

This bug can be reproduced in production on the Order/index react route under the `better-list-filters` beta flag.

**Comment by danrosenthal** [comment]
|still broken|😢| 
|-|-|
|<img width="1552" alt="Screen Shot 2019-03-14 at 9 51 13 AM" src="https://user-images.githubusercontent.com/1403188/54362128-c8a9d200-463e-11e9-8170-999c1077a7c3.png">|<img width="1552" alt="Screen Shot 2019-03-14 at 9 50 06 AM" src="https://user-images.githubusercontent.com/1403188/54362151-d19aa380-463e-11e9-9f27-2de4be46e29e.png">|

@tmlayton it appears my fix did not work

**Comment by danrosenthal** [comment]
Checking with @nimzco to see if we can get to the bottom of this.

**Comment by danrosenthal** [comment]
[Bugsnag error here](https://app.bugsnag.com/shopify/shopify-web-client/errors/5c8a5bd3692895001991628a?filters%5Bevent.since%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.since%5D%5B%5D%5Bvalue%5D=30d&filters%5Berror.status%5D%5B%5D%5Btype%5D=eq&filters%5Berror.status%5D%5B%5D%5Bvalue%5D=open&filters%5Bsearch%5D%5B%5D%5Btype%5D=eq&filters%5Bsearch%5D%5B%5D%5Bvalue%5D=cannot&filters%5Bsearch%5D%5B%5D%5Btype%5D=eq&filters%5Bsearch%5D%5B%5D%5Bvalue%5D=read&filters%5Bsearch%5D%5B%5D%5Btype%5D=eq&filters%5Bsearch%5D%5B%5D%5Bvalue%5D=property&filters%5Bsearch%5D%5B%5D%5Btype%5D=eq&filters%5Bsearch%5D%5B%5D%5Bvalue%5D=%27translate%27&event_id=5c8a5bd30037779a9fab0000)

**Comment by danrosenthal** [comment]
Unfortunately that does not seem to have been the issue either @nimzco. It's still broken in prod

**Comment by danrosenthal** [comment]
```
Nima Izadi [1:00 PM]
… :confused:

what about
```export default withI18n()(ListFilters);````
instead of
```export default compose(withI18n())(ListFilters) as ReactComponent<Props>;```
(edited)

Dan Rosenthal [1:03 PM]
I will give that a try

Nima Izadi [1:03 PM]
Maybe compose has a weird problem somehow
¯\_(ツ)_/¯
And while you’re on it, maybe even move that:
```import {withI18n, WithI18nProps} from '@shopify/react-i18n';```
down a couple of lines
Maybe some magic will happen :joy:

Dan Rosenthal [1:04 PM]
lol, I’ll try both

Nima Izadi [1:05 PM]
:crossed:

Dan Rosenthal [1:05 PM]
```Gord Pearson [1:05 PM]
Not at my desk. Best guess is a circular import, or incorrect destructuring of i18n methods. #shopify-web can provide assistance.```
I’ll try your suggestions, then circle back with #shopify-web

Nima Izadi [1:06 PM]
Oh wait, maybe you have `react-i18n` in your component and in the component that uses your component and that makes the thing break :thinking_face:

Dan Rosenthal [1:06 PM]
I definitely do

Nima Izadi [1:06 PM]
Mmmmm
I don’t know how to fix circular imports though… (edited) 
```

Conversation with Nima about the problem. A couple things to look into.

**Comment by danrosenthal** [comment]
Looks like that last attempt didn't resolve either.

**Comment by nimzco** [comment]
😭

**Comment by danrosenthal** [comment]
|confirmed fixed in production|
|-|
|![Screen Shot 2019-03-15 at 9 16 52 AM](https://user-images.githubusercontent.com/1403188/54434475-bbefb180-4704-11e9-9854-1e6ed4ec5ff5.png)|

**Comment by nimzco** [comment]
Geez, that fix... Well done @tmlayton ! 🎉
