### ISSUE TITLE
[List filters] Add "Clear" button to each accordion section

### ISSUE THREAD

**Issue by ry5n** [Shopify/polaris-react#1182]
For list filter categories that are radios, the “Any” option represents the default state (no filtering of that category).

| Expected | Actual |
| --- | --- |
| In filters that are radios, “Any” should be selected by default | No option is selected by default |
| Selecting “Any” adds a filter tag (for example: “Any order”) | Selecting “Any” should remove the filter tag for that category (it should also clear the corresponding URL param) |

**Comment by ry5n** [comment]
@danrosenthal @yourpalsonja Can we chat about this? I want to see if this is going to be hard for any reason

**Comment by danrosenthal** [comment]
This should be pretty straightforward to implement, and wouldn't take much time. My only concern is that merchants might not intuitively understand that `any` maps to no filter in that set applied. Would the absence of a badge (as confirmation of an action taken) be confusing?

**Comment by ry5n** [comment]
I’m not the user, but this is one case where I would definitely be surprised if it was confusing

**Comment by danrosenthal** [comment]
On further thought/exploration, this is impossible given the current setup. The selected state for these choice lists is derived from the applied filters (since they come in as query parameters). If clicking the `any` choice resulted in the removal of that applied filter, the choice would instantly go from selected to not selected, which would be very strange as a user. The only alternative I can think of would be to separately manage `any` choices' selected state, which would get really nasty. I think this is not a change we should make.

@tmlayton, thoughts on this? I have a solid understanding of the architecture of this component and am not seeing any alternatives, but sometimes you see things I don't see.

**Comment by tmlayton** [comment]
An "Any" tag or clearing the tag is functionally the same. I get the idea of wanting any to clear the tags when selecting any and making that a default, but I’m reluctant to make that change now given how complex the logic is around these choice lists and we are a few days away from polish. I see this is a medium or low priority and would prefer to tackle this when we refactor and extract to Polaris.

**Comment by ry5n** [comment]
It may be functionally the same, but the tag being present for “any” would encourage an incorrect mental model of this. Any is supposed to represent the default, non-filtered state. This is fundamental to the design and I consider it blocking.

If we can’t build this as intended, can we have a button below the choice list that says “clear” or something instead?

**Comment by tmlayton** [comment]
If it’s functionally the same, it is not blocking.

**Comment by tmlayton** [comment]
> If we can’t build this as intended

This is the first I'm hearing of this.

> can we have a button below the choice list that says “clear” or something instead?

We have a clear all button

**Comment by ry5n** [comment]
Discussed in person to help clarify. We agreed that the current state is not perfect, but also that the desired behavior described in the issue isn’t currently technically feasible. I missed documenting this properly in the spec, which led to the misunderstanding. Sorry for the incomplete communication there, and for coming across as rather adamant in my comments.

We agreed to take a different approach: remove the “any” option, and include a plain button in each accordion section to clear the filters for that section. That lets merchants reset a single filter to its default state, and sidesteps the technical issues.

**Comment by tmlayton** [comment]
Updated the title based on what we discussed
