### ISSUE TITLE
Add an optional 'key' attribute to Select component options

### ISSUE THREAD

**Issue by dominiceden** [Shopify/polaris-react#1186]
# Feature request summary

<Select> components currently accept an array of options, where each element in the array is an object with the format `{label: 'Label', value: 'value'}`. React insists that each item in an array must have a unique key. In Polaris, this key is the same as the `value` attribute in the object so objects with the same value but different names are flagged by React.

I propose adding a third attribute to this object called `key`, which would allow us to override the default attribute of `key` being set to the same as the `value` attribute.

## Rationale

International phone number dialling codes is the main issue - there are countries with the same code (e.g. Kazakhstan and Russia) so presenting options like this in a list causes React errors.

I expect it would be a simple, non-breaking fix as it's an optional attribute and would be happy to do it.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by AndrewMusgrave** [comment]
Hi @dominiceden what component are you having key collisions in? React key usage is internal only so we don't need to use `value` as the keys value. Perhaps we could find an alternative rather than extending the API.

**Comment by dominiceden** [comment]
Hi @AndrewMusgrave  yes, in the Select component. I map over an array of international dialling codes and have collisions there as many of the values (e.g. 7) are the same for different countries. 

Here's my code:
```
<Select
                label="International phone dialling code"
                options={[{ label: '', value: '' }].concat(
                  INTERNATIONAL_DIALLING_CODES.map(item => ({
                    label: `${item.name} (+${item.countryDialCode})`,
                    value: `${item.countryDialCode}`,
                  }))
                )}
                error={organizationFormErrors['phone_country_dial_code']}
                onChange={value => {
                  handleItemChange(
                    'Organization',
                    'phone_country_dial_code',
                    value
                  );
                }}
                value={selectedOrganization.phone_country_dial_code}
              />
```

I could of course add some kind of salt in in the mapping function and then remove it before submit, but it seems a little messy.
