### ISSUE TITLE
Strange margin when using InlineGrid

### ISSUE THREAD

**Issue by trnc-ck** [Shopify/polaris-react#11879]
### Summary

When using `<InlineGrid />` with `<CalloutCard />`s, the first CalloutCard has a strange bottom margin. We display two cards in 2 columns, but the even if we add more cards, the first cards has this margin. Content of the CalloutCards has the same height.

### Expected behavior

CalloutCards should have the same height.

### Actual behavior

<img width="984" alt="Screenshot 2024-04-11 at 10 23 06" src="https://github.com/Shopify/polaris/assets/435783/986a89c1-d2d1-46cb-a530-9893d9e1b360">
<img width="597" alt="Screenshot 2024-04-11 at 10 20 12" src="https://github.com/Shopify/polaris/assets/435783/a63dc168-ca8e-4eae-9ae1-43001557e1f5">

### Are you using React components?

None

### Polaris version number

13.0.0

### Browser

Chrome, Firefox

### Device

Macbook Pro M3

**Comment by kyledurand** [comment]
If you use dev tools you can see that the second callout card has a margin top. Sibling callout cards are meant to be stacked with a gap between. CalloutCard was built before we had layout primitives so it comes with some layout css which helped in the past.

If you design needs cards that are side by side you should use `Card` directly and layout the content with our layout components
