### ISSUE TITLE
[Card] / Extra top padding in Card section

### ISSUE THREAD

**Issue by loic-d** [Shopify/polaris-react#1204]
# Issue summary

In the `Card` component, there is extra padding at the top in the section.

<img width="588" alt="Screen Shot 2019-03-15 at 2 52 36 PM" src="https://user-images.githubusercontent.com/3925905/54455405-19e6be00-4732-11e9-8ef9-cfe03c47ee94.png">
<img width="596" alt="Screen Shot 2019-03-15 at 2 53 22 PM" src="https://user-images.githubusercontent.com/3925905/54455412-1c491800-4732-11e9-9b95-390d0e50bc3c.png">

## Expected behavior

There should not be extra spacing at the top of the card section.

## Actual behavior

There is extra spacing at the top of the card section.

Could be related to https://github.com/Shopify/polaris-react/pull/1082

## Steps to reproduce the problem

1. Add content to a `Card` component

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.10
- Browser: Chrome
- Device: Mac OS X
- Operating System:

**Comment by tmlayton** [comment]
It does look like a bit too much space, but this is the expected behavior. Here is an example using v3.5.0 https://codesandbox.io/s/m77q5yzvyy.

I’m going to close for now, but feel free to reopen if you think this should be addressed.

**Comment by loic-d** [comment]
@tmlayton I see your point. I still feel that it the UI is not matching our Discounts UX requirements. Maybe the solution is to increase the spacing after the `Banner` to make it less awkward?

Try https://codesandbox.io/s/y7p9o983pz. I am using a `ChoiceList` instead of a paragraph and it looks a bit off.

**Comment by loic-d** [comment]
cc/ @papoirier for visibility. You originally flagged the issue.
