### ISSUE TITLE
[List filters] [a11y] Sheet blends into page in High Contrast

### ISSUE THREAD

**Issue by dpersing** [Shopify/polaris-react#1213]
When the sheet is viewed in windows High Contrast with Edge, it blends into the page header and list, making it slightly difficult to pick out. This is caused by relying on a background color alone to distinguish it from the content underneath.

<img width="1872" alt="View of the sheet in Edge" src="https://user-images.githubusercontent.com/1462085/54459407-d7b68000-4723-11e9-8de2-231de7ef6feb.png">

<img width="1872" alt="High contrast view of the sheet" src="https://user-images.githubusercontent.com/1462085/54459314-9625d500-4723-11e9-9302-8c65316e56c4.png">

Giving the sheet a transparent left border (`border: 1px solid transparent`) or any border using the `-ms-high-contrast` query will make a border appear in High Contrast so the sheet is easier to discern.

**Comment by dpersing** [comment]
We looked at browser stats and decided the impact is small enough to not prioritize this for release just now, and any short-term fixes would be bandaid-y for a lot of reasons. When we do redesign work for the new brand we’ll avoid implementations that cause issues with borders by default.

**Comment by dpersing** [comment]
This has been addressed in the sheet component (#1250) but still needs to be rolled out to production.

**Comment by tmlayton** [comment]
This will be addressed by #1167
