### ISSUE TITLE
web app created with polaris sample code

### ISSUE THREAD

**Issue by shahab65** [Shopify/polaris-react#1218]
hello
I found polaris yesterday and I have been studding its docs since then.
And now I want to ask can I found some web app created by polaris?
for example is shopify admin dashboard an open source project? 
It can be very inspiring for me in designing react web apps for shopify.
If yes where can I find it?
If no how can I find another web app created with polaris?
thank you

**Comment by alex-page** [comment]
Hey @shahab65 thanks for creating your first issue!

I agree that examples help when you are getting started with something new as of right now I am not sure of any web apps that are open source. The admin dashboard is not open source unfortunately.

In the future it might be a great idea to list some examples of open source third party applications using Polaris. I will make a note of this and share it with the team.

As I said before I am not sure of any examples however we have wrote a blog post recently on [building an application user interface with Polaris](https://www.shopify.ca/partners/blog/use-polaris-to-build-an-app-ui). We also maintain a great getting started [application tutorial that uses Polaris components](https://help.shopify.com/en/api/tutorials/build-a-shopify-app-with-node-and-react).

If you want more information feel free to reopen the issue.
