### ISSUE TITLE
built in js library for i18n

### ISSUE THREAD

**Issue by shahab65** [Shopify/polaris-react#1222]
hello 
I want to create my first shopify app with create-react-app and polaris.
in my last projects I have used react-intl and [lingui/react](https://github.com/lingui/js-lingui) for
having i18n.
Now my question is:
does react-polaris comes with built-in solution for having i18n or I can use any library that I want
for having multi language store

thanks

**Comment by GuiguiWeb** [comment]
i18n utilities for React handling translations, formatting, and more : https://github.com/Shopify/quilt/tree/master/packages/react-i18n

With an i18n object, the app provider component will override default English translations : https://polaris.shopify.com/components/structure/app-provider

**Comment by AndrewMusgrave** [comment]
Hi @shahab65 as Guigui mentioned we provide english translations for all our components with the option to pass a transition diction to `AppProvider` and `@shopify/react-i18n` is our `i18n` utility.

**Comment by shahab65** [comment]
thank you. 
I am  happy with lingui/react but of course I will check polaris built-in solution out
