### ISSUE TITLE
Navigation for embedded apps

### ISSUE THREAD

**Issue by mikeyhew** [Shopify/polaris-react#1223]
# Feature request summary

Provide some way to do navigation for embedded apps that doesn't trigger a full page reload. One option is to provide a polaris component for these navigation links that looks the same as the built-in ones. There may be a way to communicate with the parent window and handle click events from the built-in navigation links, but that's a decision someone who works at Shopify would have to make.

## Rationale

Shopify lets you create navigation links for your embedded app [in the partners dashboard](https://help.shopify.com/en/api/embedded-apps/app-extensions/navigation/create-navigation-link). One of the problems with these links is that they trigger a full page reload for the app iframe. Many Polaris apps are single-page apps that can navigate more snappily using the history API, and it would be nice if there were a way to take advantage of that without rolling your own navigation links.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by fchienvuhoang** [comment]
Yes, Voted for you, we want to build app with not full reload page!!!

**Comment by dleroux** [comment]
Thanks @mikeyhew. Closing as we do with feature requests but it is not forgotten.
