### ISSUE TITLE
[Breadcrumbs] Author README for use on public Styleguide

### ISSUE THREAD

**Issue by beefchimi** [Shopify/polaris-react#1228]
https://github.com/Shopify/polaris-react/pull/2295 exported Breadcrumbs for public consumption. We did not introduce a README in that PR, and as such, we are keeping this _hush hush_ until we have one _(no CHANGELOG entry)_.

@selenehinkley / @dleroux is this something you have expertise on?

**Comment by ry5n** [comment]
@beefchimi This isn’t in the Polaris team’s plans right now. Is there some urgency for this?

**Comment by beefchimi** [comment]
No urgency on my end.
