### ISSUE TITLE
[DataTable] Sortable column headings clickable area is inconsistent with styling

### ISSUE THREAD

**Issue by andrewlo** [Shopify/polaris-react#1230]
# Issue summary

When a DataTable column is sortable, hovering over the column header with your mouse changes the color and reveals the sorting icon, indicating that it is clickable.

However, the area where it is actually clickable is smaller than the area where the hover styles are applied, making the user think they can click to sort when they can't

In this GIF I'm clicking, it has no effect until it's right on the text label:

![sortable-data-table-click](https://user-images.githubusercontent.com/1470768/54713008-010c4d00-4b24-11e9-9da5-6d33dbbdecf7.gif)

## Expected behavior

The clickable area & hover style area are the same

## Actual behavior

The clickable area is smaller than the hover style area

## Steps to reproduce the problem

1. can see on any sortable DataTable

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

**Comment by ry5n** [comment]
Thanks for catching this @andrewlo; it’s definitely an issue. The click/touchable area should extend to the edges of the table header cell. We’d welcome PRs to address this! 🙏
