### ISSUE TITLE
DatePicker range with single date allows continued selection

### ISSUE THREAD

**Issue by CameronGorrie** [Shopify/polaris-react#1239]
# Issue summary
In a ranged `DatePicker` component selecting a single day by clicking it twice shouldn't continue to show the selection highlight.

## Expected behavior
Selecting a day twice should behave the same as selecting a range, or the same as `allowRange: false`

## Actual behavior
![datePickerClickIssue](https://user-images.githubusercontent.com/3865674/54789681-a9e0a800-4c09-11e9-8ec0-5273d6db919b.gif)

## Steps to reproduce the problem
1. Click the date you want to select once
2. Click it twice
3. Observe that the date selection hover still happens

## Reduced test case
```tsx
// PlayGround.tsx
import * as React from 'react';
import {DatePicker} from '../src';

interface State {}

export default class Playground extends React.Component<{}, State> {
  state = {
    month: 1,
    year: 2018,
    selected: {
      start: new Date('Wed Feb 07 2018 00:00:00 GMT-0500 (EST)'),
      end: new Date('Wed Feb 07 2018 00:00:00 GMT-0500 (EST)'),
    },
  };

  render() {
    const {month, year, selected} = this.state;

    return (
      <DatePicker
        month={month}
        year={year}
        onChange={this.handleChange}
        onMonthChange={this.handleMonthChange}
        selected={selected}
        allowRange
      />
    );
  }

  handleChange = (value) => {
    this.setState({selected: value});
  };

  handleMonthChange = (month, year) => {
    this.setState({
      month,
      year,
    });
  };
}
```

**Comment by ry5n** [comment]
That’s subtle but definitely seems like a bug. To clarify, the problem is that if I have a range-enabled picker, and click the same date as the start and end date, the range should be confirmed and considered “complete”. Instead, the UI behaves as if the user can still pick the ending date?

**Comment by CameronGorrie** [comment]
Yep that's correct! 

It may also be nice for the `onChange` callback to supply an argument for when the end date is selected i.e. you want to close the `DatePicker` once the range selection has been made `onChange?(date: Range, rangeSelected: Boolean): void;`

**Comment by ry5n** [comment]
Excellent! Glad we’re on the same page. 

> nice for the onChange callback to supply an argument for when the end date is selected 

That would be nice! I created an issue for that so we can track it separately: #1270
