### ISSUE TITLE
Root breadcrumb click in an embedded app

### ISSUE THREAD

**Issue by michielgerritsen** [Shopify/polaris-react#1241]
Hi,

Is it possible to catch a click on the root breadcrumb in an embedded app? By root breadcrumb i mean the name of the app, in this example the text `My Cool App`

<img width="150" alt="Schermafbeelding 2019-02-28 om 21 21 37" src="https://user-images.githubusercontent.com/5858697/54867351-8e97a900-4d7f-11e9-8e0a-c89213a1beae.png">

I want to redirect the users to the index of my app, but it seems i'm unable to catch this click, nothing happens. In the documentation there is also nothing stated about this.

Thanks

**Comment by gf3** [comment]
hi @michielgerritsen—this is a feature we're looking into in App Bridge. it's still under active development but we can update you here when something is released. in the meantime, the root breadcrumb (app name) should be clickable when there is another breadcrumb present, and it should redirect the user to your app URL
