### ISSUE TITLE
Lazy loading support for optionList component [onScrollToBottom function]

### ISSUE THREAD

**Issue by siddhantbajaj** [Shopify/polaris-react#1245]
# Feature request summary

Related to https://github.com/Shopify/web/issues/11967

We want to implement Lazy loading for option list component. Currently it does not support this as it's unordered list. Wrapping it in a scrollable component might work.

## Rationale

---
Merchants have a large number of tags in their shop. Right now we only show 250 in the list, we created an endpoint to query all the tags belonging to the shop. Plan was to show all the tags in the autocomplete list but the performance was bad for 5k tags as it takes a lot of time render all the options. If option list can support lazy loading that would be a perfect solution.

cc @chloerice

**Comment by chloerice** [comment]
Hey @siddhantbajaj 👋 `Autocomplete` supports lazy loading via the `onLoadMoreResults` prop.

**Comment by chloerice** [comment]
@siddhantbajaj [Here's a sandbox for example](See [this sandbox](https://codesandbox.io/s/21omo7y01n) for an example.) of this since there isn't an example in the docs. While making this, I found a bug--the `onLoadMoreResults` prop is only getting invoked on when you reach the bottom of the list via keyboard, not via scroll 😣. I'll open a separate issue for that.

**Comment by siddhantbajaj** [comment]
Ahhh thanks a lot @chloerice !!! Do you think it's a small fix or will it take some time. I am asking because if it will take some time we have an alternate temporary fix (https://github.com/Shopify/web/issues/11967#issuecomment-476370619) for our case that we can implement for now.

**Comment by chloerice** [comment]
> Ahhh thanks a lot @chloerice !!! Do you think it's a small fix or will it take some time. I am asking because if it will take some time we have an alternate temporary fix ([Shopify/web#11967 (comment)](https://github.com/Shopify/web/issues/11967#issuecomment-476370619)) for our case that we can implement for now.

It was a straightforward fix, see #1248 & #1249 👍.

**Comment by siddhantbajaj** [comment]
Awesome, thanks you so much @chloerice for taking this up. :-)
