### ISSUE TITLE
License question in 2024

### ISSUE THREAD

**Issue by slince** [Shopify/polaris-react#12469]
### Summary

Hello everyone

Thanks for your work, polaris is a great react ui framework.  but  there are some restrictions on using polaris outside of the shopify project.

> The rights granted above may only be exercised to develop and distribute applications that integrate or interoperate with Shopify software or services, and in the case of external, stand-alone applications that do not embed directly inside Shopify, the rights granted above may only be exercised to develop and distribute applications that are dissimilar and visually distinct from Shopify products and services (including the internal administration page of a Shopify merchant store), as determined by Shopify in its sole discretion.

From the above description, it seems that it is allowed to be used outside of shopify, But from the previous license-related issues, I have seen two statements:

### Not allowed to use in non-Shopify related projects

https://github.com/Shopify/polaris/issues/2934#issuecomment-618070369
https://github.com/Shopify/polaris/issues/2767#issuecomment-607594181

### Yes, but the style needs to be modified

https://github.com/Shopify/polaris/issues/4092#issuecomment-849965706

Can someone explain if I am allowed to use polaris for other projects and if so, what should I do. 😄 

### Are you using React components?

None

**Comment by heyjoethomas** [comment]
It is allowed as long as you aren't building something that looks or acts like Shopify. However, Polaris is not a general framework like Material UI. It has strong opinions, components and api's specifically for the Shopify admin so you may find that it isn't the best option for an different project.

**Comment by heyjoethomas** [comment]
**Clarification**
The license includes two limits:
1. The rights granted above may only be exercised to develop and distribute applications that integrate or interoperate with Shopify software or services; and
2. in the case of external, stand-alone applications that do not embed directly inside Shopify, (there is an additional restriction that) the rights granted above may only be exercised to develop and distribute applications that are dissimilar and visually distinct from Shopify products and services (including the internal administration page of a Shopify merchant store), as determined by Shopify in its sole discretion.
