### ISSUE TITLE
[ResourceList] Bulk actions doesn't disappear when the list is empty

### ISSUE THREAD

**Issue by meecrobe** [Shopify/polaris-react#1252]
# Issue summary

When empty state of ResourceList is rendered (`items` property equals `[]`), bulk actions component with checkbox remains visible with text `Showing 0 {{ resource name }}`.
It disappears after clicking on it or after next render with 0 search results.

## Expected behavior
Only empty state must be rendered.

## Steps to reproduce the problem
Sandbox: https://codesandbox.io/s/n01xx425qj

1. Type something into the search input that will definitely cause empty result.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.11.0
- Browser: Version 73.0.3683.86 (Official Build) (64-bit)
- Device: iMac (21.5-inch, Late 2012)
- Operating System: macOS Mojave 10.14.3 (18D109)

**Comment by AndrewMusgrave** [comment]
I'm taking a look at a few `ResourceList` issues, this week and next. I'll add this to the list.
