### ISSUE TITLE
ResourceList placeholder prop

### ISSUE THREAD

**Issue by Rchristiani** [Shopify/polaris-react#1256]
# Feature request summary
Adding a `placeholder` prop to the `ResourceList` to allow users to set their own messages in the search area.

## Rationale

![image](https://user-images.githubusercontent.com/1775147/55096847-05d78080-5091-11e9-86b2-4af280986c0a.png)

Adding a prop like this would allow users to customize the placeholder text shown in the search area. Right now it defaults to the value in the `resourceName` prop.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by danrosenthal** [comment]
I think this should be added to `ResourceList`'s context, making it accessible through a consumer. And `FilterControl` ought to get the value through context. Does anyone have an alternative solution?

cc: @dleroux

**Comment by dleroux** [comment]
The prop would be on the `ResourceList.FilterControl` component as oppose to just the `ResourceList`

**Comment by Rchristiani** [comment]
@danrosenthal @dleroux I think it makes sense to add it to the `FilterControl` I think because that is what is needed to get this UI to appear.

**Comment by danrosenthal** [comment]
Yup, that makes sense to me 🚢

**Comment by AndrewMusgrave** [comment]
Sorry I'm a little late to the party. I think it makes sense to have the prop on `FilterControl` as well
