### ISSUE TITLE
[PolarisTokens] Consume duration tokens once released

### ISSUE THREAD

**Issue by beefchimi** [Shopify/polaris-react#1258]
This `polaris-tokens` PR adds `duration` values:
https://github.com/Shopify/polaris-tokens/pull/54

Once this is merged and released, we should update `polaris-react` to utilize these values.

Essentially, we apply the same technique found in:
https://github.com/Shopify/polaris-react/blob/master/src/styles/foundation/spacing.scss

To the `duration.scss` file:
https://github.com/Shopify/polaris-react/blob/master/src/styles/foundation/duration.scss

I did a quick scan of the codebase and didn't see any other relevant changes. Its possible we may consider making the `Toast.tsx` duration values available through the `polaris-tokens` duration... but thats up for debate.

**Comment by kaelig** [comment]
`@shopify/polaris-tokens@2.4.0-beta.1` is out - it could be worth having a PR in polaris-react to test the beta does work as expected. @beefchimi is that something you'd be comfortable doing?
