### ISSUE TITLE
[Datepicker] Add onChange callback for date range selection

### ISSUE THREAD

**Issue by ry5n** [Shopify/polaris-react#1270]
In #1239, @CameronGorrie had a good suggestion to have a callback for when a date range selection is made, in order to be able to close a picker (popover) in cases where that’s the entire merchant interaction.

> It may also be nice for the onChange callback to supply an argument for when the end date is selected i.e. you want to close the DatePicker once the range selection has been made onChange?(date: Range, rangeSelected: Boolean): void;

👍

**Comment by CameronGorrie** [comment]
Alternative approach: if the `end` value remained null until selected the developer can decide what to once a valid range has been selected instead of relying on an additional arg. At the moment the first click in a range enabled DatePicker sets both start and end values
