### ISSUE TITLE
Previous button of the Pagination component has unnecessary right border

### ISSUE THREAD

**Issue by meecrobe** [Shopify/polaris-react#1276]
# Issue summary

Previous button of the Pagination component has unnecessary right border when `nextTooltip` property is set.

## Expected behavior

1px border between Prev and Next buttons.

![pywy3w8o7q - CodeSandbox 2019-04-04 13-39-53](https://user-images.githubusercontent.com/8003440/55549712-32b61400-56df-11e9-97a1-2b5fabb85cef.png)

## Actual behavior

2px border between the buttons. Border radius of the Next button set to 0.

![pywy3w8o7q - CodeSandbox 2019-04-04 13-40-04](https://user-images.githubusercontent.com/8003440/55549726-3a75b880-56df-11e9-8b2f-6552f3d82a9f.png)

## Steps to reproduce the problem
Sandbox: https://codesandbox.io/s/pywy3w8o7q

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.11.0
- Browser: Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)
- Device: iMac (21.5-inch, Late 2012)
- Operating System: macOS Mojave 10.14.3 (18D109)

**Comment by ruairiphackett** [comment]
There's also an issue with `margin-left` and `border-radius` as its assumed the buttons will be siblings, with the styling based on `first-child` and `last-child`. As a result several styles aren't applied properly, with the next button getting styles for both `first-child` and `last-child` & not receiving the negative `margin-left` for `:not(:first-child)`.

[Relevant code](https://github.com/Shopify/polaris-react/blob/master/src/components/Pagination/Pagination.scss#L159-L171)

![https://screenshot.click/2019-04-05_11-10-25.png](https://screenshot.click/2019-04-05_11-10-25.png)

There's also similar issues when a `previousTooltip` is present:

![https://screenshot.click/2019-04-05_11-45-50.png](https://screenshot.click/2019-04-05_11-45-50.png)

or both tooltips:

![https://screenshot.click/2019-04-05_11-47-45.png](https://screenshot.click/2019-04-05_11-47-45.png)

Similarly there are issues with the `plain` buttons when they have tooltips.

**Comment by ruairiphackett** [comment]
Related issue here: https://github.com/Shopify/polaris-react/issues/1279
