### ISSUE TITLE
implicitSubmit option for Form component not working

### ISSUE THREAD

**Issue by marschattha** [Shopify/polaris-react#1278]
# Issue summary
implicitSubmit option for Form component is not working.
I tried toggling it to both true and false but if I press enter on a TextField component that is not multiline it submits the form.

## Expected behavior

Pressing enter should not submit form with `<From implicitSubmit={false}>`.

## Actual behavior
Form is submitted.

## Steps to reproduce the problem

1. Make a form component with `<From implicitSubmit={false}>`
2. Place a TextField component inside it.
3. In browser pressing enter in the TextField will cause the form to submit.

## Reduced test case

[CodeSandbox template](https://codesandbox.io/s/52mrl63p8x?module=App.js)
## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.9.0
- Browser: Chrome
- Device: Laptop
- Operating System: Ubuntu 18

**Comment by baranema** [comment]
this still does not work

**Comment by kyledurand** [comment]
Can you PR a fix for this @marschattha or @baranema?
