### ISSUE TITLE
[Pagination] Inconsistent button style on mobile depending on presence of tooltips

### ISSUE THREAD

**Issue by ruairiphackett** [Shopify/polaris-react#1279]
# Issue summary

The styling of the previous and next buttons in the `Pagination` component is dependent on whether or not tooltips are specified for each button.

It stems from the fact that buttons with tooltips are wrapped in another component and when they get rendered to the DOM they are wrapped in a `span` element. This means the flex attribute here doesn't work as intended: https://github.com/Shopify/polaris-react/blob/master/src/components/Pagination/Pagination.scss#L24

## Expected behavior

The button styling should not be affected by the presence of tooltips. I'm unsure what the expected style on mobile is as the example `Pagination` components have different styles on mobile too. It is likely that the intended style is that of the `Default pagination` example:

![https://screenshot.click/2019-04-05_15-11-34.png](https://screenshot.click/2019-04-05_15-11-34.png)

## Actual behavior

Using the examples included in the codesandbox below, here are how they are actually styled:

![https://screenshot.click/2019-04-05_14-57-11.png](https://screenshot.click/2019-04-05_14-57-11.png)

## Steps to reproduce the problem

1. Add `Pagination` components with different combinations of previous and next tooltips present (included in the codesandbox below)
1. View on a device with screen width [< 450px](https://github.com/Shopify/polaris-react/blob/master/src/components/Pagination/Pagination.scss#L19)

## Reduced test case

This sandbox includes different combinations of buttons/tooltips: https://codesandbox.io/s/qzlr5z1049

## Specifications

- Are you using the React components? (Y/N): y
- Polaris version number: v3.12.0
- Browser: Chrome 73.0.3683.86
- Device: Macbook
- Operating System: OSX 10.14.4

## Related issue

https://github.com/Shopify/polaris-react/issues/1276

**Comment by ruairiphackett** [comment]
The [use of a `WrapperComponent`](https://github.com/Shopify/polaris-react/blob/master/src/components/Tooltip/Tooltip.tsx#L86) by the `Tooltip` component is problematic here when trying to use `inline-flex` as the `flex` attribute needs to be applied to the child elements.

**Comment by asalisbury** [comment]
We're also experiencing this issue on all of the online store listing pages (https://github.com/Shopify/online-store-web/issues/3649)
