### ISSUE TITLE
Redundant build test

### ISSUE THREAD

**Issue by beefchimi** [Shopify/polaris-react#1280]
Was reading through some tests and I noticed what appears to be a redundant or unfinished test.

The following tests appear to be testing the exact same thing - they just happen to be looking at different component files:
- https://github.com/Shopify/polaris-react/blob/master/tests/build.test.js#L29-L31
- https://github.com/Shopify/polaris-react/blob/master/tests/build.test.js#L48-L50

The only difference here is `Icon.scss` vs `ResourceList.scss`. However, the latter's description is:

> generates a component entry point for each component

That is definitely not what the test is doing - it is only looking at a single component.

Should we remove this `ResourceList` test or fix it to actually check against multiple files?

**Comment by yourpalsonja** [comment]
I'm pinging @ismail-syed on this, since he wrote one of the tests (Dom wrote the other one). If you two wanna figure it out and open a PR, that would be awesome!

On a sidenote, I'm also re-labelling based on our new [guidelines, here](https://docs.google.com/document/d/10Isykczvydj1YLvdxEYpeNEaiksGlKfeKp8VO4_gvw8/edit#).

**Comment by beefchimi** [comment]
@ismail-syed any insight here?

**Comment by tmlayton** [comment]
We are safe to remove one of these tests

**Comment by ismail-syed** [comment]
> Should we remove this ResourceList test or fix it to actually check against multiple files?

IIRC, we just arbitrarily picked a component. Either of those suggestions is ok with me.

**Comment by tmlayton** [comment]
This has been fixed
