### ISSUE TITLE
Inconsistency around page breadcrumbs

### ISSUE THREAD

**Issue by tjoyal** [Shopify/polaris-react#1281]
# Issue summary

According to https://github.com/Shopify/polaris-react/issues/331

> Unfortunately this is a limitation of the EASDK. It only accepts one level of breadcrumb.

On the other hand on the doc: https://polaris.shopify.com/components/structure/page

The documentation:
> Array of type: (CallbackAction | LinkAction)[]

And the example:
> <Page  breadcrumbs={[{content: 'Products', url: '/products'}]}

## Expected behavior

Either accept an array and support it, or receive a single item.

## Actual behavior

Accept an array of elements, only render the last one.

<img width="1354" alt="Screen Shot 2019-04-05 at 3 25 59 PM" src="https://user-images.githubusercontent.com/207902/55645003-f4941f80-57c6-11e9-8eaf-fe009cef5f55.png">

**Comment by chloerice** [comment]
Thanks for the request, @tjoyal. We treat all feature requests as part of our backlog, so I’ll close this issue for now. 

**we encourage everyone who wants this feature to continue to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.
﻿
💜
