### ISSUE TITLE
[Frame] Legacy context api and extra rendering

### ISSUE THREAD

**Issue by jim-chou-shopify** [Shopify/polaris-react#1282]
# Issue summary
[Frame.tsx](https://github.com/Shopify/polaris-react/blob/master/src/components/Frame/Frame.tsx#L73
) uses legacy context api and it causes extra rendering for children components when updating context.

References: 
[Avoiding unnecessary renders with React context](https://frontarm.com/james-k-nelson/react-context-performance/#to-render-or-not-to-render)
>The new context API’s <Context.Provider> components is a bit smarter about re-rendering than your average component. In fact, there is only a single scenario in which it will re-render its children:
<Context.Provider> will only re-render if its children prop does not share reference equality with its previous children prop.
Notably, <Context.Provider> will not re-render if its value changes while its children stay the same. In this case, only the associated <Context.Consumer> components will re-render. This makes it possible to update a context’s consumers without requiring that the entire app be re-rendered.

## Expected behavior
- Making the form dirty triggered nav bar to update context of Frame
- Only components that consume frame context should render again (EX: ContextBar)

## Actual behavior
Updating frame context causes children to render again.

- Making the form dirty triggered nav bar to update context of Frame
- It rendered children components that didn't change
![legacy-context-problem](https://user-images.githubusercontent.com/39597748/55664080-b6aeef80-57f6-11e9-961f-6ab2917b942a.gif)

## Steps to reproduce the problem

1. Use frame to wrap components
1. Update context
1. All children not consuming context render again

## Reduced test case

Legacy context: https://codesandbox.io/s/r7j229norq
New context: https://codesandbox.io/s/42x6p4v2x0

Legacy context rerender children
New context only render children when its not equal by reference

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.11.0
- Browser: Chrome
- Device: Mac Pro
- Operating System: macOS 10.14.4

**Comment by AndrewMusgrave** [comment]
👋 `Frame` and it's subcomponents have already been moved to the new context, however it's a breaking and and will have to be included in polaris `v4`.

**Comment by jim-chou-shopify** [comment]
@AndrewMusgrave Great! Is there a release date?

**Comment by AndrewMusgrave** [comment]
Sorry `v4` is still in the early stages and we don't have a set date yet @jim-chou-shopify
