### ISSUE TITLE
[Autocomplete][v1] Selection issue when scrolling

### ISSUE THREAD

**Issue by adamcarchibald** [Shopify/polaris-react#1288]
# Issue summary
When selecting from a drop down list, if an option was previously selected and you are required to scroll to select a different option, the option is not selected on click.

## Expected behavior
Clicking any option immediately selects it.

## Actual behavior
 ![](https://screenshot.click/2019-04-08_16-37-56.gif)

[Code Sandbox](https://codesandbox.io/s/o72r5v862q)

## Steps to reproduce the problem

1.  Select an option high up in the options list
2. Reopen the options list and scroll near the bottom of the list
3. Attempt to select this option

**Comment by simoncereska** [comment]
Hi,
do you have any idea for a temporary solution?

**Comment by simoncereska** [comment]
Looks like when click event is fired, event.target is pointing to ul (a _this.handleClick function on @shopify/polaris/index.es.js line 4496) and this causes if statement to return, so my solution was to change element that contains scrollbar. The following code worked for me:

`
.Polaris-Popover__Content { height: auto !important; max-height: 2000em !important; }
.Polaris-OptionList__Options { max-height: 29.5em; }
`

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.

**Comment by sambostock** [comment]
Reopening this, because it was closed as stale without confirmation it was fixed.
