### ISSUE TITLE
[INTL] Allow multiple locales into the bundle

### ISSUE THREAD

**Issue by nimzco** [Shopify/polaris-react#1292]
# Feature request summary

Right now, `polaris-react` only has `en.json` translations. If we add other languages (see https://github.com/Shopify/polaris-react/pull/1291), we might blow up the bundle.
We need to find a way to be able to have any number of translations in the bundle. This could be by having them load asynchronously when the local changes.

## Rationale

We want people using Polaris and creating embedded app in the admin to serve multi locale experience.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by michelleyschen** [comment]
just fyi, there is a way of doing translation currently, but with its down side.

```
<AppProvider
  i18n={{
    Polaris: {
      ResourceList: {
        showing: '{itemsCount} {resource} affichés',
        defaultItemPlural: 'articles',
        defaultItemSingular: 'article',
      },
    },
  }}
>
```

**Comment by michelleyschen** [comment]
Notably the translations will applied for the entire application. (ie. if you have two `ResourceList` that need slightly different text, this method won't allow for it, we will need to provided component level overwrite for the text.)

**Comment by danrosenthal** [comment]
This has been fixed, and can now be closed
