### ISSUE TITLE
[Autocomplete][v1] Highlighting selection with mouseUp outside of Autocomplete.TextField cause options pop out bug

### ISSUE THREAD

**Issue by adamcarchibald** [Shopify/polaris-react#1293]
# Issue summary
If an option is selected in Autocomplete and the user highlights that options with a mouseDown and up event but the up event occurs outside of the Autocomplete.TextField component the pop over never appears, as there is likely no onFocus event.  You are however free to delete the selected option.  

## Expected behavior
If a use is able to press delete/backspace after highlighting an option the pop over should reaper onChange.

## Actual behavior
![](https://screenshot.click/2019-04-09_11-19-32.gif)

Did not include a code sanbox as this can be replicated directly on https://polaris.shopify.com/components/forms/autocomplete

## Steps to reproduce the problem
1. Select an option
1. Highlight the option with a mouseDown and mouseUp making sure the mouseUp is not inside the Autocomplete.TextField
1. Press delete key, try typing in a new option to autocomplete

## Notes
This and https://github.com/Shopify/polaris-react/issues/1265 may have similar fixes

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.

**Comment by sambostock** [comment]
Reopening this because it was closed as stale without confirmation that it was fixed.
