### ISSUE TITLE
VideoCard

### ISSUE THREAD

**Issue by ncpope** [Shopify/polaris-react#1305]
# VideoCard

Card variation that allows for thumbnail and playing activity.

### Inactive preview

<img width="809" alt="Screen Shot 2019-04-10 at 16 21 14" src="https://user-images.githubusercontent.com/1903724/55920053-259c9780-5bad-11e9-9a6f-21b7a6cd2fda.png">

### Actively playing

<img width="777" alt="Screen Shot 2019-04-10 at 16 21 35" src="https://user-images.githubusercontent.com/1903724/55920054-259c9780-5bad-11e9-80ac-53ed97e4ba71.png">

## Props

List props and type declarations:

> - **videoID** (required): `string` defaults to `null`
> - **source** (required): `string` defaults to `youtube`

**Comment by chloerice** [comment]
Thanks for the request, @ncpope. We treat all feature requests as part of our backlog, so I’ll close this issue for now.

**We encourage everyone who wants this feature to add a 👍** to the original issue report. We take your collective interest into account when we look at what to work on next. In the meantime, PRs are always welcome 💜
