### ISSUE TITLE
[Modal] Animation of modal entering not working in some conditions

### ISSUE THREAD

**Issue by nonjene** [Shopify/polaris-react#1308]
# Issue summary

When open a modal in some conditions ([reproduction](https://codesandbox.io/s/m7n0q878k8)), the fade up animation effect is seems be interrupted.

After debugging, it seems the transition of stage `.Polaris-Modal-Dialog--entering` is not needed, then add `transition: none` to this css selector, the problem fixed.

here is the sandbox reproduction: [https://codesandbox.io/s/m7n0q878k8](https://codesandbox.io/s/m7n0q878k8)

## Expected behavior

Always show the modal's entering animation.

## Actual behavior

Not always show the modal's entering animation.

## Steps to reproduce the problem

1. go to the reproduction example
1. click the `persist actions` in the resource list
1. click `open modal`
1. the modal showed without animation

Hack the problem:

1. click the `Add the fix of modal transition` button
1. click again of the persist actions's `open modal`
1. the animation work

## Reduced test case

[https://codesandbox.io/s/m7n0q878k8](https://codesandbox.io/s/m7n0q878k8)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.12.0, 3.xx
- Browser: chrome version 74
- Device: macbook
- Operating System: macos

**Comment by chloerice** [comment]
Hey @nonjene, I believe this was fixed by #2076. Please reopen if you are still able to reproduce with v4.2.0 or higher.
