### ISSUE TITLE
Promoted Bulk Actions don't disable when disabled: true

### ISSUE THREAD

**Issue by jineshshah36** [Shopify/polaris-react#1316]
# Issue summary

Including `disabled: true` in `promotedBulkActions` does not disable the action

## Expected behavior

Including `disabled: true` in `promotedBulkActions` should disable that action

## Actual behavior

The `disabled` prop is being overridden incorrectly (https://github.com/Shopify/polaris-react/blob/ee00f38d32259712d473dc32d6c60fced34710ab/src/components/ResourceList/components/BulkActions/BulkActions.tsx#L293)

## Steps to reproduce the problem

1. Disable a promotedBulkAction

## Reduced test case

https://codesandbox.io/s/1omv7zl24q

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.12.0
- Browser: Chrome
- Device: Macbook Pro
- Operating System: MacOS

**Comment by AndrewMusgrave** [comment]
Thanks for reporting the issue 🙏

**Comment by jineshshah36** [comment]
https://github.com/Shopify/polaris-react/pull/1317 Fixes it
