### ISSUE TITLE
Spacing on ResourceList.Item actions isn't the same as Card actions

### ISSUE THREAD

**Issue by jkeussen** [Shopify/polaris-react#1345]
# Issue summary

Persistent actions in ResourceList.Item is not aligned with other right aligned buttons like the Card actions.

## Expected behavior

I'd expect that all right aligned actions in a Card should have the same spacing.

## Actual behavior

The ResourceList.Item action has more padding than the Card actions, making them not aligned.

## Steps to reproduce the problem

1. Add a card
2. Add an action to the card 
3. Add a ResourceList, with items that have `persistAction` on it
4. See the actions not being aligned

## Reduced test case

I've made an example here:
https://codesandbox.io/s/21xx5rxo10

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: Latest

cc: @sarahill

**Comment by ruairiphackett** [comment]
Here's the culprit: https://github.com/Shopify/polaris-react/blob/9e2d57e45aafdd3a07e802c87b9d292fa69833c4/src/components/ResourceItem/ResourceItem.scss#L191

It doesn't look like it needs `persistsActions` to be true however.

It gives `.Polaris-ResourceList-Item__Actions` a `right` value of `1.2rem`

![https://screenshot.click/2019-08-20_14-47-17.gif](https://screenshot.click/2019-08-20_14-47-17.gif)

I can put in a PR to fix it when I get back from vacation next week.
