### ISSUE TITLE
[Autocomplete][v1] Keyboard navigation is laggy and skips options

### ISSUE THREAD

**Issue by sylvhama** [Shopify/polaris-react#1346]
# Issue summary

If you navigate up / down it will sometimes feel laggy and even skip an element.

## Expected behavior

Each keystroke should navigate to the next option within a reasonable amount of time.

## Actual behavior

CF summary

## Steps to reproduce the problem

1. Visit https://polaris.shopify.com/components/forms/autocomplete
1. Click on the search example
1. Try to navigate up and down with your keyboard within options

## Reduced test case

https://codesandbox.io/s/k9446943k3?module=App.js

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 3.13.0
- Browser: Chrome (latest)
- Device: Macbook Pro
- Operating System: MAC OS

**Comment by yourpalsonja** [comment]
Hey @sylvhama, we're looking into fixing up Autocomplete soon! I'm going to set this ticket up with the right labels so the team is aware of it when the time comes.

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.
