### ISSUE TITLE
Website links to previous UI kit release

### ISSUE THREAD

**Issue by sogen** [Shopify/polaris-react#1359]
# Issue summary
Website:
https://polaris.shopify.com/resources/polaris-ui-kit#navigation
links to v3.12.0:
https://github.com/Shopify/polaris-react/releases/download/v3.12.0/Sketch.UI.Kit.zip

## Expected behavior
website links to v3.13
https://github.com/Shopify/polaris-react/releases/download/v3.13.0/Sketch.UI.Kit.zip

**Comment by AndrewMusgrave** [comment]
👋 Hi @sogen, normally when we do a release we'll update polaris in the style-guide as well. Unfortunately it looks like we haven't gotten to it yet. From what I understand it's @alex-page plan to update it monday. For the time being you can access our assets [here](https://github.com/Shopify/polaris-react/releases/tag/v3.13.0). Sorry for the inconvenience!
