### ISSUE TITLE
[Popover] `handleScrollOut` triggered unexpectedly

### ISSUE THREAD

**Issue by tmlayton** [Shopify/polaris-react#1367]
<img src="https://user-images.githubusercontent.com/344839/56769587-7c39d200-6766-11e9-8ae3-dba3d9f5b835.GIF" width="200" />

This appears to be caused by the keyboard opening and scrolling of the viewport which triggers `handleScrollOut` and closes the popover.

<img width="1824" alt="Screen Shot 2019-04-25 at 2 32 02 PM" src="https://user-images.githubusercontent.com/344839/56769831-40533c80-6767-11e9-99cf-aded664b59d8.png">

Suggested fix: Do an early return in `handleScrollOut` if the popover contains focus.

**Comment by andrewmcgov** [comment]
Hey @tmlayton 👋 

I cant seem to duplicate this one. The popover stays open when the keyboard opens:

https://screenshot.click/2019-05-15_16-22-02-u6900.mp4

Testing with this codesandbox
https://codesandbox.io/s/ctm5s

Mobile link:
https://ctm5s.codesandbox.io/

Has this maybe been fixed already?

**Comment by tmlayton** [comment]
Hey @andrewmcgov, I can’t reproduce anymore either, at least not in the latest iOS. Here is my reduced test case: https://jj957x52mw.codesandbox.io/

Maybe there was an update to iOS which prevented the keyboard overlay from considering elements out of the viewport?

**Comment by tmlayton** [comment]
I tried to recreate the original state when I found this in web and can’t reproduce there either. Going to consider this resolved. Thanks for looking into it!
