### ISSUE TITLE
Issue with embedded app (Page, Toast)

### ISSUE THREAD

**Issue by AndreyYeryomin** [Shopify/polaris-react#1368]
Hey anyone, i have some issue with embedded app, when i set my **apiKey** and **shopOrigin** in **AppProvider**, all my actions hide. I used this example from polaris documentation, below you will see result (hided page title, breadcrumbs, primary, secondary actions). When i used **Toast** component it never show. 
Example:
![Screenshot (20)](https://user-images.githubusercontent.com/18416551/56270375-a18f6600-60fe-11e9-8d9f-d79aaa9bfdae.png)
 My result:
![Screenshot (21)](https://user-images.githubusercontent.com/18416551/56270479-def3f380-60fe-11e9-9d65-a92f5d51c452.png)
- Are you using the React components? (Y/N):Y
- Polaris version number:3.11.0
- Browser:Chrome
- Device:iMac
- Operating System:El Capitan 10.5

**Comment by danrosenthal** [comment]
Hey @AndreyYeryomin, this behavior all appears to be expected. Both of these components, when an APIKey is given to the AppProvider, delegate their rendering to Shopify's web client through the App Bridge. The appearance of page is as expected, and will look more complete within the Shopify admin. Toast will not render at all when an APIKey is present and your application is not embedded within the Shopify admin.

For more, see the docs entries on these components when in use in an embedded application:
- [Page](https://polaris.shopify.com/components/structure/page#section-use-in-an-embedded-application)
- [Toast](https://polaris.shopify.com/components/feedback-indicators/toast#section-use-in-an-embedded-application)

**Comment by AndreyYeryomin** [comment]
Hey @danrosenthal, but my app is embedded in Shopify admin.
![download](https://user-images.githubusercontent.com/18416551/57059783-750f4880-6cbf-11e9-8006-d2bc22b2ac3f.png)

**Comment by danrosenthal** [comment]
@Shopify/app-bridge is there someone from your team who might be able to troubleshoot here with @AndreyYeryomin.

cc: @markiiikram

**Comment by vividviolet** [comment]
@AndreyYeryomin could you double check the `apiKey` and `shopOrigin` to make sure they are correct? The `shopOrigin` should be the shop url without the 'https://'.

**Comment by AndreyYeryomin** [comment]
@vividviolet  , i check it. 

![shopify](https://user-images.githubusercontent.com/18416551/57123933-6e023c00-6d8c-11e9-8cd3-99a1bc1ce26f.gif)

**Comment by hannachen** [comment]
Hi @AndreyYeryomin, I'm filling in for @vividviolet for the day. Thanks for creating the gif, the API key looks to be correct 🤔I was hoping to read some of the warnings in the logs of your gif, but the text is too tiny. I'm curious, what is your app URL? Do you by chance have different domains/subdomains to handle different parts of your app?

**Comment by AndreyYeryomin** [comment]
Hi @hannachen , i use only one domain for my app. (langshop-shopify-app.dev-test.pro)

**Comment by vividviolet** [comment]
@AndreyYeryomin It looks like your app is calling [`ShopifyApp.init`](https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk/methods#shopifyapp-init-config) somewhere. This is a legacy call which locks the app down into a legacy EASDK app and  makes it incompatible with App Bridge. 

Your app can either use App Bridge or EASDK but not both at the same time. Are you able to track that call down and remove it?
