### ISSUE TITLE
[Popover] TextField in Popover may be covered by iOS keyboard

### ISSUE THREAD

**Issue by ry5n** [Shopify/polaris-react#1370]
# Issue summary

When a popover component contains a text field, the field may be covered by the virtual keyboard in mobile browsers, preventing the user from seeing what they’re typing.

## Expected behavior

The field with focus should be moved into view with the keyboard up, so the user can see what they’re typing.

## Actual behavior

On mobile web browsers, especially iOS Safari, popovers that contain text fields may end up making it hard for people to type because the keyboard may cover the field. There is also something (possibly scroll-locking?) that prevents manually scrolling the field into view with the keyboard up. 

![popover-mobile-keyboard-iphone-5s](https://user-images.githubusercontent.com/804014/56819986-d72c0180-6818-11e9-98ad-1dbbdafe98fd.gif)

## Steps to reproduce the problem

1. On a page with several screenfuls of content, place a popover that contains a textfield.
1. In iOS Safari, tap the text field to focus it. The keyboard may cover the field. If it doesn’t, try again—it seems to be inconsistent even with the same interface and session.
1. When the keyboard covers the field, try manually scrolling to the field.

## Reduced test case

Haven’t had time to put one together. Happy to do so if this is hard to reproduce.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.12.0
- Browser: iOS Safari
- Device: iPhone X and iPhone SE (simulator)
- Operating System: iOS 12.2

**Comment by ry5n** [comment]
@StephPoce Here’s an example of popover problems on mobile web.

**Comment by yohanmishkin** [comment]
I believe this may have broke when iOS jumped from 12.1 to 12.2.

**Comment by tmlayton** [comment]
After some exploration as part of #1367 this appears to be fixed. Using https://jj957x52mw.codesandbox.io/ as the reduced test case we cannot recreate this issue.
