### ISSUE TITLE
[Avatar] Add content guidelines for `initials` prop

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-react#1374]
## Feature request summary

Documentation for initials in the Avatar component:

<img width="55" alt="Screenshot 2019-04-26 13 10 08" src="https://user-images.githubusercontent.com/85783/56833869-a782f680-6824-11e9-99ec-d390f476870e.png">

## Rationale

[The avatar component](https://polaris.shopify.com/components/images-and-icons/avatar) can display initials when an avatar image isn't available or fails to load.

See rendering: https://codesandbox.io/s/lyyon178jl?module=App.js

We need content guidelines for developers and designers to populate initials correctly:

- internationalization: how many characters should we display depending on the locale / full name's origin?
- "politeness": recommend a list of restricted terms? (for example, we could recommend to avoid initials such as `BS` and `FU`, and fall back to `B` and `F` instead)

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by ry5n** [comment]
There is some discussion of how to handle initials in Japanese in https://github.com/Shopify/shopify/issues/159004

The need is more complex now, as more locales are now supported which may have other guidelines.

In terms of avoiding culturally inappropriate combinations, I wonder if we should switch to just a single letter. It would be simpler (and avoid running out of space with some combinations too, like MM)
