### ISSUE TITLE
[Autocomplete][v1] Selection only works on second click for long lists

### ISSUE THREAD

**Issue by sylvhama** [Shopify/polaris-react#1379]
# Issue summary

If your list of options has a scroll bar. Options at the bottom of the scroll view will require two clicks to be selected.

## Expected behavior

It should update the state on first click.

## Actual behavior

See https://codesandbox.io/s/0y0v9mn8ov 

## Steps to reproduce the problem

1. Click on the field
1. Scroll to the bottom of the option list
1. Select an option

## Reduced test case

See https://codesandbox.io/s/0y0v9mn8ov 

## Specifications

- Are you using the React components? (Y/N): yes
- Polaris version number: 3.13
- Browser: Chrome
- Device: Mac Book Pro
- Operating System: Mac OS

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.
