### ISSUE TITLE
[Autocomplete][v1] the enter keystroke event should not bubble up

### ISSUE THREAD

**Issue by sylvhama** [Shopify/polaris-react#1380]
# Issue summary

When using the keyboard to select an option; pressing enter will trigger the parent form's onSubmit. I think we should call `stopPropagation()` of the event so it does not bubble up to the form.

## Expected behavior

Select the option and **don't** trigger the for submission.

## Actual behavior

Select the option and trigger the for submission.

## Steps to reproduce the problem

1. Click on the field
1. Navigate with your keyboard
1. Press enter

## Reduced test case

See https://codesandbox.io/s/oqmom5qrxz

## Specifications

- Are you using the React components? (Y/N): yes
- Polaris version number: 3.13
- Browser: Chrome
- Device: Mac Book Pro
- Operating System: Mac OS

**Comment by KidkArolis** [comment]
Just for context, in case it's helpful, I had to do something similar in my codebase. I had to modify KeypressListener to listen to `keydown` event in case of Enter, because that's what triggers form submit, it's too late to stopPropagation() on `keyup`.

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.
