### ISSUE TITLE
[DataTable] horizontal scroll is not persistent across renders

### ISSUE THREAD

**Issue by jimmyn** [Shopify/polaris-react#1387]
## Issue summary

Each render of DataTable parent component causes a vertical scroll to reset. This results in very confusing user experience in cases where actions ore inputs are present in the table row

![Screen Recording 2019-04-30 at 11 05](https://user-images.githubusercontent.com/5391775/56948152-f340e300-6b37-11e9-9f04-8ea29f40eaa3.gif)

## Expected behavior

The vertical scroll should be persistent across renders. One possible solution would be to expose [preservedScrollPosition](https://github.com/Shopify/polaris-react/blob/master/src/components/DataTable/DataTable.tsx#L60) and a callback when this value is updated

## Reduced test case

[![Edit yp159mp6l9](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yp159mp6l9?fontsize=14)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.13.0
- Browser: Chrome 73.0.3683.103 (Official Build) (64-bit)
- Device: MacBook Pro 
- Operating System: macOS Mojave 10.14.4

**Comment by chloerice** [comment]
This is no longer reproducible. Please reopen if you experience this problem after upgrading to the latest version.
