### ISSUE TITLE
[TextField] <textarea /> vertically expands forever

### ISSUE THREAD

**Issue by beefchimi** [Shopify/polaris-react#1391]
The `Resizer` functionality of a `multiline` `<TextField />` is great, but... it expands infinitely!

In our app, we have had to target the `textarea` in CSS to apply a `max-height`, which works perfectly! The `Resizer` will continue to work ONLY UNTIL the `max-height` is reached. Then, the `<textarea />` remains locked in at that height and provides the native browser `<textarea />` content scrolling.

Do we intend to make this a concern of the consumer's CSS? I'm curious if Polaris should be handling this within the component? Should Polaris provide a sensible `max-height` value - or perhaps even provide a new prop to make this value configurable through the API? If we handled it internally, we would also have the benefit of not needing to update the inline `height` style when that `max-height` is exceeded.

A second concern - and this may have a11y benefits - is we set `resize: none;` on the `<textarea />`... I feel like it is preferable UX to give the user control of resizing the `<textarea />`.

cc/ @dpersing + @ry5n

**Comment by dpersing** [comment]
I'd definitely prefer if we can preserve the default resize functionality for our textareas. The element is a bit visually ambiguous without it, and users might be surprised when the container resizes as they are typing but they can't resize it themselves.

**Comment by tmlayton** [comment]
Interesting, if this is needed we should add a prop. Applying via CSS is not what we want. What is you max-height? Can you link the PR?

**Comment by ry5n** [comment]
I always thought we were making things easier for both users and implementors by having our text field serve the function of both text input and text area. I also thought that auto-grow textareas would be better than having to manually resize them. After building forms on mobile web for a couple years, I grew to really dislike scrolling textareas (or really any secondary scroll areas within a scrollable page).

I’m open to being wrong on any or all of these though—or for having more nuance/control over the exact behavior, like with a prop ^^

**Comment by beefchimi** [comment]
@ry5n I agree with the above _with conditions_. At a certain point, an auto-expanding input is going to expand _toooooo muuuuuuch_.

As for the "resize handler", I've always preferred it personally - but that might be subjective. I'll pass that back over to @dpersing who has some more objective reasoning for its application.

**Comment by dpersing** [comment]
I like the idea of auto-growing the container as a person types like we do, _but_ not having that be the only way the size/shape can be controlled. If a user is trying to do a lot of things in a small space (like a sidebar, or a modal) being able to use the default controls to resize a text area they're not currently using to make room for other stuff is really helpful.

**Comment by ry5n** [comment]
> At a certain point, an auto-expanding input is going to expand toooooo muuuuuuch.

That makes sense, but I wonder if making it scroll is the only solution. At least for small screens, a separate edit view just for that field might be better. But that may not work for every use case either.

For auto-growing, if we could restore the native resize handle (which I guess would act as an override, turning off the auto-grow behavior), that could be really cool.
