### ISSUE TITLE
Update `Validate on submit` example screenshots in documentation

### ISSUE THREAD

**Issue by pauyeung** [Shopify/polaris-react#1399]
## Issue summary
`Validate on submit`: Multiple example screenshots don't reflect Polaris guidelines
https://polaris.shopify.com/patterns-and-guides/error-messages#section-validate-on-submit 

## Banner text
<img width="907" alt="Screen Shot 2019-05-02 at 4 15 10 PM" src="https://user-images.githubusercontent.com/16708256/57106119-9b9ea500-6cfa-11e9-9168-969597436da4.png">
Banner content guidelines show a single error situation when it wouldn't exist. Using a multiple error situation would be more clear

## Invalid field
<img width="613" alt="Screen Shot 2019-05-02 at 4 02 04 PM" src="https://user-images.githubusercontent.com/16708256/57106171-bd982780-6cfa-11e9-9a26-f26584916f93.png">
Missing error text below an invalid field

**Comment by mirualves** [comment]
Updating the copy with @selenehinkley. Will be ready by the end of the week.

**Comment by mirualves** [comment]
Updated the following images to the `Error messages` sections of the style guide:

![input-validation@2x](https://user-images.githubusercontent.com/5349023/57795886-12816800-7715-11e9-9133-cd4b5b051a61.png)
![validation-banner-content-do@2x](https://user-images.githubusercontent.com/5349023/57795887-12816800-7715-11e9-9490-9b532ffc3b36.png)
![validation-banner-content-dont@2x](https://user-images.githubusercontent.com/5349023/57795888-12816800-7715-11e9-9f18-8f17109d67b7.png)
![validation-banner-red@2x](https://user-images.githubusercontent.com/5349023/57795889-1319fe80-7715-11e9-9697-9988e3280d6e.png)

@selenehinkley, can you please help me double check if everything is correct?
