### ISSUE TITLE
[Resource list] print stylesheet

### ISSUE THREAD

**Issue by ry5n** [Shopify/polaris-react#1401]
Some people print out lists of resources in order to do work away from a computer. When printing, some interactive elements in a resource list take up space on the paper, which wastes paper, ink, and makes it harder to see more things at once.

## Issue summary

We should figure out which elements are not useful to merchants when a list is printed, and hide those using a print stylesheet.

## Expected behavior

We should probably hide the following elements when printing:

- Selection checkboxes (even if merchants want to use the list as a checklist, they can write in the margins)
- Filter control buttons
- The sort control and “additional action” element

We may want to _not hide_ identifiers that provide context for filtered lists:

- Filter search field
- Applied filter tags

## Actual behavior

Nothing is hidden when printing.

## Steps to reproduce the problem

TBD

## Reduced test case

TBD

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

**Comment by kyledurand** [comment]
Can I tack on to this if we're tackling some print styles or should I create a new issue?

It's mainly around `Page` print styles 
![image](https://screenshot.click/68747470733a2f2f63646e2d7374642e64707263646e2e6e65742f66696c65732f6163635f35323539322f316d75594177_13901830_2019-05-03_09-21-50.png)

**Comment by ry5n** [comment]
Thanks Kyle! These suggestions make sense to me. Strictly speaking, print styles for the page title and page-level actions would be implemented in the `Page` component. Banners would either need to be handled case-by-case in Shopify Web, or we’d need to introduce some kind of formal “hide when printing” slot—but I’m not sure how to think about that yet. I’d prefer to go with case-by-case for now.

For next steps, I think it would be best to open a separate issue for print styles in the `Page` component. Would you be willing to copy-paste the above ^ about page title etc. into a new issue?

**Comment by ry5n** [comment]
I’d suggest the title `[Page] print stylesheet`

**Comment by dpersing** [comment]
@ry5n Sounds like we can close this issue in favor of @kyledurand's?

**Comment by kyledurand** [comment]
My changes only affect the ported ResourceList we have in web. This issue will track the Polaris version. The other issue I created is for `Page` print styles only
