### ISSUE TITLE
[Modal] Modal primaryAction doesn't support loading prop

### ISSUE THREAD

**Issue by ryanlanglois** [Shopify/polaris-react#1410]
## Issue summary
The `primaryAction` on the `Modal` component doesn't support a `loading` prop.

## Expected behavior
Adding a `loading` prop to the primary action should show the button in a loading state, like what happens in the admin.

## Actual behavior
Loading state doesn't work.

## Steps to reproduce the problem

1. Add a `loading` prop to the `primaryAction` of a `Modal`

**Comment by dpersing** [comment]
Hi @ryanlanglois! Could you provide a bit of background on what you're looking to support with this functionality? Thanks.

**Comment by ryanlanglois** [comment]
@dpersing yes, I'm showing a confirmation Modal before deleting an object in my app. I'm trying to match the UX of the Shopify admin. For an example directly from the Shopify admin:

- Navigate to a collection detail view
- Click `Delete collection` in the footer
- Click `Delete collection` when the modal pops up. The delete button gets a loading state while the collection is being deleted.

This functionality doesn't seem possible in Polaris at the moment because the `primaryAction` doesn't accept a `loading` prop like other button components do.

**Comment by dpersing** [comment]
Hi @ryanlanglois,

The destructive pattern is a bit different, and isn't actually baked in to the default modal at present. For your use case, I'd suggest using the `loading` prop so that the whole modal goes into a kind of "loading" state. You can toggle on that prop and see it in action in our [examples for the modal](https://polaris.shopify.com/components/overlays/modal).

**Comment by ryanlanglois** [comment]
@dpersing unfortunately that only works for stand-alone apps, and my app is embedded in the admin.

It's not a major issue, but it feels inconsistent so I wanted to bring it to your attention.

**Comment by dpersing** [comment]
Ah ha! Thanks for the clarification, @ryanlanglois. I'll tag this for us to take a closer look.

**Comment by tomgs** [comment]
+1 for this. If I understand correctly, this should allow me to add the loading spinner to a button in a modal's primary action, much like a regular button, right? If so then I need this. :)

**Comment by dpersing** [comment]
Hi @tomgs! We definitely do. Check out our [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md)!

**Comment by BPScott** [comment]
Looks like loading is already supported as a primaryAction: https://codesandbox.io/s/flamboyant-moon-colsv

primaryAction implements ComplexAction, which implements LoadableAction.

@tomgs Can you try and implement use the loading property of `primaryAction` in your app and see if it works?

**Comment by tomgs** [comment]
Ah, interesting @BPScott - I'll take a look. Will be back:)

**Comment by alex-page** [comment]
@ryanlanglois @tomgs thanks for raising this. This is an issue with `AppBridgeAction` and not `ComplexAction`. I am going to make a PR to address this.

**Comment by alex-page** [comment]
@ryanlanglois @tomgs this feature should be available by the end of the week.

**Comment by alex-page** [comment]
This should be released today.
