### ISSUE TITLE
ResourcePicker to allow pre-selection of products by id

### ISSUE THREAD

**Issue by uri3000** [Shopify/polaris-react#1411]
## Feature request summary

Need a way to preselect products inside the resource picker

## Rationale

Take this user flow into consideration:
1. User opens the resource picker
2. User selects 3 products and closes the resource picker
3. A text field near the resource picker now says "3 products selected"
4. The user opens the resource picker again in hope to update or change his/her selection
5. The user doesn't see any selected products
EXPECTED:
5. The user should see the same products which he/she selected on step 2. 

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dpersing** [comment]
Hi @uri3000! Thanks for your request. I've added it to our backlog and we'll take a closer look.

**Comment by spinlock99** [comment]
@dpersing is the backlog public? I need to have initial selected products in the ResourcePicker too so I'd love to keep track of it.

Thanks!
