### ISSUE TITLE
[Navigation] Bottom of list gets cut off on iOS

### ISSUE THREAD

**Issue by beefchimi** [Shopify/polaris-react#1413]
It would appear as though we have some "100%" height style getting messed with by the strange iOS viewport height. There is a gap at the bottom of the Navigation that makes for an awkward looking whitespace:

<img src="https://user-images.githubusercontent.com/643944/57242588-e6256780-7001-11e9-982b-53e146420858.png" width="240" alt="" />

I believe opening the Navigation on mobile will enable `body` "scroll locking", which causes the iOS "browser chrome" to reappear/remain visible.

**Comment by ruairiphackett** [comment]
@beefchimi Do you know what device & iOS version this happened on? I tried to reproduce on the iPhone XS with iOS 12 and couldn't:

https://screenshot.click/31-19-jzye3-mf2nq.gif

**Comment by beefchimi** [comment]
This would have been on an iPhone X... but im not sure exactly what iOS version. I will need to test if the issue is still present when I get the chance.
