### ISSUE TITLE
Document configuration of i18n on AppProvider for pulling in translations and remove english as default

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#1418]
Related to this comment: https://github.com/Shopify/polaris-react/pull/1358#issuecomment-488477477, we want to clearly document the approach for pulling in non-english translations to the `AppProvider`. We may consider making `i18n` a required prop, and removing the default English translations.

**Comment by danrosenthal** [comment]
cc: @AndrewMusgrave

**Comment by AndrewMusgrave** [comment]
Going to tackle this on `Friday || Monday` and put together a MVP. If we're making i18n a required prop we'll want to bunch this into `v4`

**Comment by tmlayton** [comment]
Going to remove myself as an assignee on this. Let me know if there is something you need me to do and I will slot it in.
