### ISSUE TITLE
[Color system] purple

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#1420]
## Context

Purple and its variants are only used two times in the system.

- `Icon` (purple variant)
- `Avatar` (purple variant)

### Usage

- Lighter `#F6F0FD` - 0
- Light `#E3D0FF` - 0
- Purple `#9C6ADE` - 2
- Dark `#50248F` - 0
- Darker `#230051` - 0
- Text `#50495A` - 0

## Recommendation

Remove purple `Icon` and `Avatar` variants and :fire: purple and each of its variants from the system.

**Comment by kaelig** [comment]
Codename: purpless 💟

**Comment by danrosenthal** [comment]
|Purple icon|
|-|
|<img width="31" alt="Screen Shot 2019-05-08 at 3 57 40 PM" src="https://user-images.githubusercontent.com/1403188/57404962-4a375f80-71ab-11e9-8100-16eeaf82895e.png">|

**Comment by ry5n** [comment]
According to the [style guide on color usage](https://polaris.shopify.com/design/colors#section-color-usage):

“Purple is used as our primary graphing color. It is not used in other types of data visualization such as trend signifiers.”

@mirualves Can you confirm if this is still true of data visualization work you’ve seen recently?

If true, we shouldn’t necessarily remove it from the design system until we can replace it with a more complete color paletter for data viz.

**Comment by mirualves** [comment]
That's correct. Purple `#9C6ADE (RGB 156, 106, 222)` is the primary color for data visualization in Overview dashboard, sparklines on Reports index, bar/line charts on Reports, and Customer behavior chart on Live view.
It also shows up on the Live view box at the top of the page.

<img width="745" alt="Screenshot 2019-05-09 13 41 10" src="https://user-images.githubusercontent.com/5349023/57475081-9cd35300-7261-11e9-9693-4bfbe0654c77.png">

**Comment by danrosenthal** [comment]
This is great context, thanks @ry5n and @mirualves!

**Comment by danrosenthal** [comment]
Closed in favor of https://github.com/Shopify/polaris-react/issues/1593
