### ISSUE TITLE
[Color system][Badge][Banner] inconsistent color usage and variant options

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#1430]
Currently the use of colors to convey variants with the same meaning is inconsistent across the `Badge` and `Banner` components. In some cases, a different color us used to convey the same variant across these components. In other cases, the same variants are not available in both components.

We should make this consistent across components so merchants can reliably associate color with the severity of badges and banners.

## Default

Default is consistent in its use of sky across both components, and should be left as-is.

|Badge|Banner|
|-|-|
|<img width="80" alt="Screen Shot 2019-05-08 at 3 12 14 PM" src="https://user-images.githubusercontent.com/1403188/57401678-291f4080-71a4-11e9-9563-99d87c406158.png">|<img width="895" alt="Screen Shot 2019-05-08 at 3 12 06 PM" src="https://user-images.githubusercontent.com/1403188/57401686-32101200-71a4-11e9-8912-3e6751c97c81.png">|

## Information

|Badge|Banner|
|-|-|
|<img width="101" alt="Screen Shot 2019-05-08 at 1 44 22 PM" src="https://user-images.githubusercontent.com/1403188/57398800-e0648900-719d-11e9-8d17-f6f92533f1ee.png">|<img width="895" alt="Screen Shot 2019-05-08 at 2 31 16 PM" src="https://user-images.githubusercontent.com/1403188/57398849-f70ae000-719d-11e9-8d7e-9c929130b1cb.png">|

Badge uses blue as its base color, while banner uses teal. Using teal for badge as well as banner would create more consistency while improving color contrast in the information variant of the badge component.

## Attention

|Badge|Banner|
|-|-|
|<img width="99" alt="Screen Shot 2019-05-08 at 2 33 16 PM" src="https://user-images.githubusercontent.com/1403188/57398968-47823d80-719e-11e9-99fb-9f6f8e8d07ae.png">|No such variant|

The badge component uses yellow to communicate the attention variation, while the banner component has no such variant. The banner component uses yellow to communicate a warning state.

## Warning

|Badge|Banner|
|-|-|
|<img width="128" alt="Screen Shot 2019-05-08 at 2 34 56 PM" src="https://user-images.githubusercontent.com/1403188/57399065-8a441580-719e-11e9-9b78-e5775ce013ca.png">|<img width="896" alt="Screen Shot 2019-05-08 at 2 35 04 PM" src="https://user-images.githubusercontent.com/1403188/57399080-9203ba00-719e-11e9-8b81-0aa2752f3c45.png">|

The badge component uses orange as a base color to communicate a warning state, while the banner component uses yellow to communicate a warning state. For the badge component, yellow communicates the attention state as shown above.

## Critical

|Badge|Banner|
|-|-|
|No such variant|<img width="894" alt="Screen Shot 2019-05-08 at 2 39 06 PM" src="https://user-images.githubusercontent.com/1403188/57399393-1d7d4b00-719f-11e9-80f5-816eca7134c3.png">|

While the badge component does not have a critical variant, the banner component uses red to communicate a critical variant. 

**NB** The rails implementation does have a critical variant for badge which uses red as its base color.

## Success

Success is consistent in its use of green across both components, and should be left as-is.

|Badge|Banner|
|-|-|
|<img width="135" alt="Screen Shot 2019-05-08 at 3 02 39 PM" src="https://user-images.githubusercontent.com/1403188/57400828-608ced80-71a2-11e9-883b-ecc747401440.png">|<img width="896" alt="Screen Shot 2019-05-08 at 3 02 47 PM" src="https://user-images.githubusercontent.com/1403188/57400837-6682ce80-71a2-11e9-8167-77b4f5905c53.png">|

## Overall recommendation

Unify the use of color and variants across these components.

|Variant|Color|Badge|Banner|
|-|-|-|-|
|Default|Sky| ☑️| ☑️|
|Information|Teal| ☑️| ☑️|
|Attention|Yellow| ☑️| ☑️|
|Warning|Orange| 🔥| 🔥|
|Critical|Red| ☑️| ☑️|
|Success|Green| ☑️| ☑️|

### Consider eliminating `warning`

- its use-case is unclear 
- removing it would simplify decision making for designers, and make meaning clearer for merchants

**Eliminating the `warning` variant would also allow us to remove orange from the color palette**, as orange is only used for the warning badge, and for variants of icon and avatar.

**Comment by danrosenthal** [comment]
## Information

|Badge|Banner|
|-|-|
|<img width="101" alt="Screen Shot 2019-05-08 at 1 44 22 PM" src="https://user-images.githubusercontent.com/1403188/57398800-e0648900-719d-11e9-8d17-f6f92533f1ee.png">|<img width="895" alt="Screen Shot 2019-05-08 at 2 31 16 PM" src="https://user-images.githubusercontent.com/1403188/57398849-f70ae000-719d-11e9-8d7e-9c929130b1cb.png">|

Badge uses blue as its base color, while banner uses teal. Using teal for badge as well as banner would create more consistency while improving color contrast in the information variant of the badge component.

**Comment by danrosenthal** [comment]
## Attention

|Badge|Banner|
|-|-|
|<img width="99" alt="Screen Shot 2019-05-08 at 2 33 16 PM" src="https://user-images.githubusercontent.com/1403188/57398968-47823d80-719e-11e9-99fb-9f6f8e8d07ae.png">|No such variant|

The badge component uses yellow to communicate the attention variation, while the banner component has no such variant. The banner component uses yellow to communicate a warning state.

**Comment by danrosenthal** [comment]
## Warning

|Badge|Banner|
|<img width="128" alt="Screen Shot 2019-05-08 at 2 34 56 PM" src="https://user-images.githubusercontent.com/1403188/57399065-8a441580-719e-11e9-9b78-e5775ce013ca.png">|<img width="896" alt="Screen Shot 2019-05-08 at 2 35 04 PM" src="https://user-images.githubusercontent.com/1403188/57399080-9203ba00-719e-11e9-8b81-0aa2752f3c45.png">|

The badge component uses orange as a base color to communicate a warning state, while the banner component uses yellow to communicate a warning state. For the badge component, yellow communicates the attention state as shown above.

**Comment by danrosenthal** [comment]
## Critical

|Badge|Banner|
|-|-|
|No such variant|<img width="894" alt="Screen Shot 2019-05-08 at 2 39 06 PM" src="https://user-images.githubusercontent.com/1403188/57399393-1d7d4b00-719f-11e9-80f5-816eca7134c3.png">|

While the badge component does not have a critical variant, the banner component uses red to communicate a critical variant. **NB** The rails implementation does have a critical variant for badge which uses red as its base color.

**Comment by danrosenthal** [comment]
cc: @ry5n @jessebc @allylane @sarahill

**Comment by danrosenthal** [comment]
## Overall recommendation

Unify the use of color and variants across these components.

|Variant|Color|
|-|-|
|Information|Teal|
|Attention|Yellow|
|Warning|Orange|
|Critical|Red|

Alternatively, we could consider eliminating a state like `warning`, and only offer `information`, `attention`, and `critical`. Color recommendations would remain the same.

**Comment by danrosenthal** [comment]
## Success

Success is consistent across both components, and should be left as-is.

|Badge|Banner|
|-|-|
|<img width="135" alt="Screen Shot 2019-05-08 at 3 02 39 PM" src="https://user-images.githubusercontent.com/1403188/57400828-608ced80-71a2-11e9-883b-ecc747401440.png">|<img width="896" alt="Screen Shot 2019-05-08 at 3 02 47 PM" src="https://user-images.githubusercontent.com/1403188/57400837-6682ce80-71a2-11e9-8167-77b4f5905c53.png">|

**Comment by ry5n** [comment]
In general this makes sense. In particular, making each color mean the same thing across components is really important. (There’s at least [one existing issue about the color discrepancies](https://github.com/Shopify/polaris-ux/issues/110)).

Don’t forget that teal has come to mean “new” (even though it’s a it broken with the change of the new badge to grey), and we have a grey base color for badges and banners.

Finally, I don’t think it’s necessary to offer each component with every status. For example, maybe a “new” banner doesn’t make sense because banners are inherently for higher-importance communication, and we never want “new” hints to hit that hard. I think k this is why some statuses are absent from some components today. If this idea holds, it could be really helpful to document, since it helps reinforce the purpose of each component.

**Comment by danrosenthal** [comment]
Good call @ry5n, I've updated this to reflect the default variant of both of these components and how it consistently uses sky.

I've left the new variant of badge out of this discussion as it feels a bit set apart from the rest of these variants. I agree that there doesn't need to be a new variant for banner.

**Comment by danrosenthal** [comment]
https://github.com/Shopify/polaris-ux/issues/110 is interesting, as it advocates using blue for information. I disagree with that, as unifying around teal for information would result in an overall simpler color system. Blue feels inappropriate for this as it is current used for text links currently.

**Comment by danrosenthal** [comment]
cc: @alex-page @AndrewMusgrave

**Comment by alex-page** [comment]
@danrosenthal this is great i've been watching the colour system issues all day!

I sit somewhere in the middle. I feel like blue is the colour for information however teal is pretty much blue :). Bootstrap also uses teal for information but they use blue for primary alerts. This is because there buttons use the same colour palette as the rest of there components:
https://getbootstrap.com/docs/4.3/components/alerts/#link-color

This might be worth exploring across a few components as we also do colours for our toasts and other components based on these system wide alerts.

**Comment by ry5n** [comment]
Remember that currently we make a distinction between “info” which really means advice or tip, and “new” which is used for new features. If we want to merge the 2 that’s maybe a larger UX question

**Comment by danrosenthal** [comment]
No immediate action needs to be taken here. Closing.
