### ISSUE TITLE
[Color system] orange

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#1433]
## Context

- [Orange is used for the `Badge` component's warning variant](https://github.com/Shopify/polaris-react/issues/1430)
- Orange is also used to generate Avatar and Icon variants

### Usage

- Lighter `#FCEBDB` - 0
- Light `#FFC58B` - 1
- Orange `#F49342` - 2
- Dark `#C05717` - 2
- Darker `#4A1504` - 0
- Text `#594430` - 1

## Recommendations

- eliminate `warning` as a variant of the `Badge` component
- eliminate all orange variants of the `Icon` and `Avatar` components
- remove orange from the system

**Comment by danrosenthal** [comment]
## Components

|badge|icon|
|-|-|
|<img width="127" alt="Screen Shot 2019-05-08 at 4 21 46 PM" src="https://user-images.githubusercontent.com/1403188/57405959-b4e99a80-71ad-11e9-9c57-c2b113ece031.png">|<img width="33" alt="Screen Shot 2019-05-08 at 4 21 32 PM" src="https://user-images.githubusercontent.com/1403188/57405980-badf7b80-71ad-11e9-902b-3e327d76bd9b.png">|

**Comment by ry5n** [comment]
I’m finding it hard to draw the line from the context given here, to the recommendation to remove orange from the system.

Removing orange and `warning` badges would have a significant impact on the merchant experience in some important places, like the orders list page:

<img width="1058" alt="Screen Shot 2019-05-09 at 10 36 52 AM" src="https://user-images.githubusercontent.com/804014/57474213-76ec8500-7246-11e9-8bf2-32f777d1476c.png">

**Comment by danrosenthal** [comment]
Sorry about that, should have given more context. The context here is that it is minimally used in the system, basically just on this badge. I want us to challenge the assumption that we need orange.

Given your example, I think we could push against the validity of how important orange badges are to this particular merchant experience. If yellow badges are used for attention, couldn't the pending badge use `yellow`? Why does the merchant need to be warned that the payment is pending?

For the `Partially fulfilled` badge, why is an attention badge with a partially filled pip and the different content not enough?

**Comment by ry5n** [comment]
It’s great to challenge the need for things like this!

@erapago what do you think about the impact to merchants on the order list page, if Polaris removed orange from the badge statuses?

**Comment by erapago** [comment]
Honestly given that the chargeback badges are yellow, and arguably much more critical information than a partial fulfillment (much closer to actually being a warning), I don't see this is as a big issue to switch this at all.

**Comment by erapago** [comment]
Maybe chargebacks _should_ be orange though. That's pretty critical information.

**Comment by danrosenthal** [comment]
> Would we get a critical badge as a trade-off?

I think so

**Comment by mherlihey** [comment]
Agreed that the use of orange isn't particularly useful on the index. The `Partially fulfilled` and `Pending` states should be yellow. Yellow represents work to do and is represented the way on the order show page. You can see here the orange is out of place.
![Screenshot 2019-05-10 12 00 39](https://user-images.githubusercontent.com/22602517/57540690-432f5f00-731b-11e9-9289-9aa2fe131093.png)

That being said, other than chargebacks there is also `Expiring` that I can see the case made for the orange badge.
<img width="1126" alt="Screenshot 2019-05-10 12 03 06" src="https://user-images.githubusercontent.com/22602517/57540849-acaf6d80-731b-11e9-8626-c7b6438e58e2.png">

**Comment by AdamWhitcroft** [comment]
I like the idea of a simpler palette for our actions, but using the third colour as an addendum or modifier to special cases (`Authorized` in yellow, with a secondary `Expiring` in orange is real nice).

If we set all base payment and fulfillment badges to use either yellow or grey, I think we should probably make `Partially paid` yellow too.

**Comment by erapago** [comment]
Maybe we can think about which badges are alerts, which are critical, and think about removing the red strikethrough for canceled orders.

I would be very curious to hear some thoughts about why we would need three classifications of "warnings" though. Is it because we discourage the use of red/critical?

**Comment by danrosenthal** [comment]
From what I'm hearing, orange warning badges are, at best, not particularly useful, and could either be replaced by a less severe variation of badge that is currently available, or a more severe (unavailable) critical badge. The case of `expiring` makes particular sense as a critical badge, since it needs to have action taken on it immediately.

At their worst, orange badges appear to be confusing and inconsistent in their application.

As a next step, I would like to open a pull request that deprecates the warning badge (with the intention of removing it in the next major version), and introduces a critical badge. So far I have not seen any objection to a critical badge. It's also present in rails implementation of Polaris, so I'm not convinced its omission wasn't an oversight on our part.

@mherlihey, @AdamWhitcroft, @erapago, @ry5n any objection to that as a plan?

**Comment by danrosenthal** [comment]
Closed in favor of https://github.com/Shopify/polaris-react/issues/1593
