### ISSUE TITLE
Navigation hover and active states

### ISSUE THREAD

**Issue by jessebc** [Shopify/polaris-react#1487]
Related to:
https://github.com/Shopify/polaris-react/pull/1304

- It appears that on some pages (products, customers, settings) the hover state of main nav items is blue instead of the intended gray. 
- The bold for an active nav item now feels a bit too bold. Dialing it back to what we had before would be sufficient. 
- The cursor at times does not change to a hover state (pointer). I haven't been able to reliably repoduce this one.

**Comment by danrosenthal** [comment]
> It appears that on some pages (products, customers, settings) the hover state of main nav items is blue instead of the intended gray.

This is likely more of the polaris rails `a` styles taking precedence. We'll likely want to explicitly declare the `color` for all states so that there aren't cases where it is incorrect.

**Comment by ry5n** [comment]
@yourpalsonja Can you take a look?

**Comment by dleroux** [comment]
The bold has been sticking out to me as well. Are there no concerns with it potentially wrapping when selected? Especially with internalization.

**Comment by danrosenthal** [comment]
|:tophat:|:tophat:|
|-|-|
|![Screen Shot 2019-05-22 at 9 03 45 AM](https://user-images.githubusercontent.com/1403188/58176617-a81a7b80-7c70-11e9-8e49-1a244e015902.png)|![Screen Shot 2019-05-22 at 9 06 40 AM](https://user-images.githubusercontent.com/1403188/58176746-f62f7f00-7c70-11e9-96df-dceccce53480.png)|

> The bold has been sticking out to me as well. Are there no concerns with it potentially wrapping when selected? Especially with internationalization.

LGTM

**Comment by danrosenthal** [comment]
|:tophat:|
|-|
|![bold-nav](https://user-images.githubusercontent.com/1403188/58176969-735af400-7c71-11e9-991b-f3c083271c00.gif)|

Oh I see what you mean now! Yeah that is gross
