### ISSUE TITLE
[ResourceList] Item checkboxes not "enabling" after loading, possible regression?

### ISSUE THREAD

**Issue by jineshshah36** [Shopify/polaris-react#1518]
## Issue summary

items that are added when the resourcelist's "loading" prop is "true" remain disabled even after loading is set to false.

## Expected behavior

items should have their disabled state updated after loading is set to false.

## Actual behavior

items that are added when the resourcelist's "loading" prop is "true" remain disabled even after loading is set to false.

(I suspect the custom shouldComponentUpdate introduced this problem because we did not see it before that change)

## Steps to reproduce the problem

1. Visit the codesandbox link below
2. You will notice that there is at least one item in the selectedItems state
3. Click the load button to trigger a new item being added "lazily"
4. You will see the new item added.
5. Click stop to "stop" loading
6. Inspect the checkbox in thew new item (you will notice it is disabled and did not get properly updated)

## Reduced test case

https://codesandbox.io/s/cool-currying-9pqd4

## Specifications

```bash
System:
    OS: macOS Mojave 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 19.38 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
Browsers:
    Chrome: 74.0.3729.157
    Chrome Canary: 76.0.3796.0
    Firefox: 66.0.5
    Safari: 12.1
    Safari Technology Preview: 12.2
```

**Comment by danrosenthal** [comment]
cc: @AndrewMusgrave

**Comment by jineshshah36** [comment]
Just checked this, not sure when but it was fixed.
