### ISSUE TITLE
[ResourceList] turn on/off selection with a separate property

### ISSUE THREAD

**Issue by vict-shevchenko** [Shopify/polaris-react#1536]
## Feature request summary

At this moment, if I want my ResorceList items to be selectable and "Select All" checkbox in the header I have to provide either "bulkActions" or "promotedBulkActions" or both properties.

I believe this setting should be controlled by a single property let say "selectable: true".

## Rationale

My case: I have 2 Resources Lists, user can proceed further after selection something from both of them. To achieve this - ResourceLists are controlled components, and I have a single validation and button one level above them.  But this list does not have any bulkActions, still have to have a checkboxes for items.

Other case: very long list where action buttons are at the end of the list. Now the user needs to scroll back to to to apply an action.

In general, this makes ResourceList more flexible component. And allows selection without a need to provide "bulkActions" or "promotedBulkActions". Then its up to develper how to handle selection mechanism and selected results.

At this moment I have to pass a dummy bulkAction and hide Actions with css - that is a really ugly solution.

## Implementation
 
I found its possible to extend the current component with additional property without breaking change. if one of:
- bulkActions
- promotedBulkActions
- selectable

properties provided - there will be a selection mechanism enabled.

If you consider this valuable - I can make a PR.

Thanks a lot.
---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by danrosenthal** [comment]
Hey @vict-shevchenko, thanks for the issue! This is pretty interesting. `selectable` could make sense as a prop, but I'm curious to learn more about how you would use this. Would you mind providing a paired down example of how you're currently doing this? I'm interested to see what your implementation looks like. Something using [Code Sandbox](https://codesandbox.io/s/new) would be awesome! 😎

**Comment by vict-shevchenko** [comment]
Sure. I will come back to you tomorrow.

**Comment by vict-shevchenko** [comment]
Hi @danrosenthal , sorry for such a delay from my side. The primary job sometimes takes a lot of time.
Here is a codesandbox representing my simplified case. https://codesandbox.io/s/modest-silence-k2yd5 

Thanks a lot.

**Comment by danrosenthal** [comment]
Thanks a lot for taking the time to put this together @vict-shevchenko, this makes a lot of sense.

I think `selectable` makes sense as a prop, but I would like to make sure that when this is `true` and there are no bulk actions, we render a checkbox with a label as the header. We would do this to continue to allow select/deselect all, and to provide a count of the number of resources selected.

If that feels like something you'd like to take on, I encourage you to open a pull request. We'll give you some support and direction to help move this along towards our desired outcome. How does that sound?

**Comment by vict-shevchenko** [comment]
Sounds good 👍. I will take my time to work on this one.
