### ISSUE TITLE
Remove tap-highlight for mobile

### ISSUE THREAD

**Issue by lemonmade** [Shopify/polaris-react#1541]
## Feature request summary

I find the tap highlight on mobile (darkened highlight on links that are active) to be very distracting compared to the much nicer activation styles we have for mouse-based interaction. This can in theory be changed with the [`-webkit-tap-highlight-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color) property.

## Rationale

Polaris interaction styles are way nicer than the browser defaults.

**Comment by tmlayton** [comment]
We already do this for [buttons in polaris-rails](https://github.com/Shopify/polaris-rails/blob/d7e47de66d426612cd686e990aab0fab3dacdbec/app/assets/stylesheets/polaris/ui-kit/common/_button.scss#L175), seems like an oversight in polaris-react. 

With the visually pressed state for buttons, the interaction is really nice on touch. https://polaris-rails.shopify.com/components/button

**Comment by tmlayton** [comment]
Put up a draft PR https://github.com/Shopify/polaris-react/pull/1545 so we could start playing with this and see what changes we would want to make to the active styles.

**Comment by dpersing** [comment]
Moving this issue to In progress since there's a PR in the works.

**Comment by tmlayton** [comment]
Going to put this down for now. For anyone who wants to pick it up see #1545 for changes to plain button and link states before we remove the tap highlight
