### ISSUE TITLE
Color picker selects text outside of picker while dragging in Safari

### ISSUE THREAD

**Issue by brian-lyn** [Shopify/polaris-react#1542]
## Issue summary

When dragging the color picker in Safari text elements outside of the color picker container are highlighted. 

## Expected behavior

When dragging the color picker, text elements should not be highlighted. 

## Actual behavior

![screencast 2019-05-21 11-16-05](https://user-images.githubusercontent.com/35280190/58108660-38e25000-7bba-11e9-8bc9-7ab08d977412.gif)

## Steps to reproduce the problem

1. Add ColorPicker component and adjacent text element to project
2. Open project in Safari
3. Click and drag the color picker and bring mouse outside of the picker to hover over text

## Reduced test case

https://codesandbox.io/s/shopify-polaris-react-typescript-playground-sqfcn?fontsize=14

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.15
- Browser: Safari Version 12.0.3 (14606.4.5)
- Device: Macbook Pro
- Operating System: MacOS 10.14.3

**Comment by alexieyizhe** [comment]
I'd like to take a stab at this if possible @tmlayton

**Comment by tmlayton** [comment]
All you @alexieyizhe!

**Comment by alexieyizhe** [comment]
I've opened a PR that will address this bug^^
