### ISSUE TITLE
Update Help Documentation

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react#1543]
Updates to help documentation related to list filters

https://help.shopify.com/en/manual/orders/fulfill-orders

cc: @VanjaMitrovic @sadiesaurus

**Comment by tmlayton** [comment]
There might be other pages, too. That was just the first one I could find.

**Comment by dpersing** [comment]
@sarahill Do we have enough info on how to do this to start? I seem to recall there's an email address to ping with Help Center requests.

**Comment by tmlayton** [comment]
Just bumping on this one, we are wrapping up the outstanding items on the project this week so if someone could pick this up that would be amazing

**Comment by VanjaMitrovic** [comment]
The docs are done but are hidden. I'll unhide them in the help repo.
https://help.shopify.com/en/manual/orders/new-filters

**Comment by VanjaMitrovic** [comment]
@halligators will take care of the content in the Help Center. thanks, Hal!

**Comment by VanjaMitrovic** [comment]
Fixed! https://github.com/Shopify/help/pull/10016
