### ISSUE TITLE
Drop Zone - Option to show drop overlay when object is dragged into page

### ISSUE THREAD

**Issue by lukashlavacka** [Shopify/polaris-react#1550]
## Feature request summary

**This is different than `dropOnPage`**

Drop zone could have an option that would display overlay when compatible object is dragged into the page, not only when object is dragged over the drop zone component.

Validation should be incorporated so that overlay is not displayed for incompatible drop zones.

## Rationale

During our work we added some small drop zones that are not clear that are drop zone (changing image of variant by dragging image over its thumbnail). The proposed option would make it clear where the drop zones are once user starts dragging object into the page.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dpersing** [comment]
Hi @lukashlavacka! Could you share a screenshot or example of the small drop zone behavior you're running into? And perhaps an example of the behavior you'd like to see if you've got one?

**Comment by lukashlavacka** [comment]
Goal of my suggestion is to increase discoverability of small drop zones on the page. In our case we are allowing drop on a resource list thumbnail. The dropzone changes only once you drag image over the thumbnail but it's hard to discover this functionality.

<details>
<summary>Before dragging a file</summary>

![overlay-before-blurred](https://user-images.githubusercontent.com/1924660/58574553-32815300-820e-11e9-9eb8-40dea47c22b2.png)

</details>
<details>
<summary>After dragging a file over the page</summary>

![overlay-after-blurred](https://user-images.githubusercontent.com/1924660/58574564-38773400-820e-11e9-8689-df9ebe8389d1.png)

</details>

**Comment by dpersing** [comment]
@sarahill What do you think? I like this idea! (Thanks so much for adding the visuals, @lukashlavacka!)

**Comment by sarahill** [comment]
This is great! This makes a lot of sense especially for these smaller dropzones that don't have a ton of discoverability, as you mentioned, without explicitly dropping an image on top.
