### ISSUE TITLE
Actions do not show up on 9.7" iPads in portrait mode

### ISSUE THREAD

**Issue by alekseyg** [Shopify/polaris-react#1554]
## Issue summary

When opening a Shopify app in the admin interface for a shop on a 9.7" iPad in portrait mode in Safari, the actions do not show up in the bar. In Chrome on desktop they do show up with the same exact resolution. In landscape mode, the actions also show up on the iPad. This doesn't affect the 11" iPad Pro or the iPhone XR. I haven't tried it on other iPads or iPhones.

## Expected behavior

Actions should show up in a bar right underneath the bar with the app name and "..." menu item.

![image](https://user-images.githubusercontent.com/68075/58200323-6c3ee080-7c87-11e9-8be8-bc3422157e0f.png)

## Actual behavior

The actions do not show up.

![image](https://user-images.githubusercontent.com/68075/58200383-8aa4dc00-7c87-11e9-829a-2650ed0b2790.png)

## Steps to reproduce the problem

1. Open Safari on 9.7" iPad
1. Log into Shopify admin
1. Launch an embedded app that utilizes actions

## Reduced test case

I'm not sure I can do this with an embedded app and just any browser as codesandbox doesn't embed the app in a Shopify Admin interface and this bug seems to be very specific to a browser and resolution combination.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.13.0
- Browser: Safari
- Device: 9.7" iPad
- Operating System: iOS 12.2

**Comment by mbaumbach** [comment]
@alekseyg Are the actions in the "..." menu? That's where secondary page actions go when viewing the embedded app in the Shopify mobile app.

**Comment by alekseyg** [comment]
@mbaumbach No, the actions are not in the "..." menu. This is in vanilla Safari, not in the Shopify mobile app. I haven't tried it in the mobile app on a 9.7" iPad, but I have tried it on an 11" iPad Pro, which doesn't exhibit this bug in either mobile app or in Safari, because the 11" iPad Pro triggers the landscape media breakpoint even in portrait mode. Here is what the "..." menu contains in the browser whether or not the actions are there.

![image](https://user-images.githubusercontent.com/68075/58207945-98169200-7c98-11e9-8fdd-6c7c91f2bcc5.png)

**Comment by mbaumbach** [comment]
@alekseyg I figured it was worth a shot to see if they were there. That's very strange!

**Comment by alekseyg** [comment]
@mbaumbach Yeah, that's what I thought initially as well. My guess is that the bug is probably in the Shopify Admin interface, but I don't know where to report that, so I reported here. The strangest part to me is that it only happens at a specific resolution on a specific device. The same resolution on a desktop browser doesn't exhibit the same bug.

**Comment by alekseyg** [comment]
I did some more mucking around with different iOS devices and found that the iPhone 6/6S/7/8 Plus in landscape mode also trigger the same media width breakpoint as the 9.7" iPads (and presumably all generations of the iPad Mini), but the iPhone does display the actions just like Chrome did on desktop at a width of 768px (iPhone 6-8 Plus has a width of 736px in landscape).

![image](https://user-images.githubusercontent.com/68075/58209541-1d4f7600-7c9c-11e9-874c-ff1bdb01d5f2.png)

**Comment by alekseyg** [comment]
I found where in the Admin interface the action bar is being hidden but I haven't figured out why it is hidden. On other devices, this CSS rule doesn't come up in the dev tools.

![image](https://user-images.githubusercontent.com/68075/58211013-943a3e00-7c9f-11e9-99f5-d2f6df0d0224.png)

**Comment by tmlayton** [comment]
Hey @alekseyg and @mbaumbach thanks so much for the issue and context. Please feel free to continue to discuss, but there is nothing we can do about this within Polaris React so I will be closing this issue. We simply delegate to the App Bridge TitleBar action (https://help.shopify.com/en/api/embedded-apps/app-bridge/actions/titlebar) so this is an issue they will have to fix on their end. 

They take issues through the Shopify forums https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology.

---

For more context on App Bridge and Polaris, we will be deprecating its usage in Polaris and will instead offer React wrappers for each of the App Bridge actions from a different package (`@shopify/app-bridge-react`). Read more about it here: https://github.com/Shopify/polaris-react/issues/814#issuecomment-493249756
