### ISSUE TITLE
Banner content clarification

### ISSUE THREAD

**Issue by caitlinmullen** [Shopify/polaris-react#1556]
**Problem**

There aren't definitive guidelines around different types of content within banners (headings, body content, links), and banner content is applied inconsistently across the product.

A long-lost Slack conversation in #product-content drew attention to the issue of when it's appropriate to use just a heading, just body content, links, combinations of 2 elements, or all 3. What is the relationship between these 3 content elements within banners?

Additionally, we want to explore some scenarios in which banner content breaks the usual patterns. Usually a heading follows the short noun-verb sentence pattern, but sometimes headings are complete sentences with a period (particularly when body content is absent). Let's try to identify other patterns in banners and try to figure out when a particular style is most appropriate.

**Examples**

Polaris banner with just body content:
![Screen Shot 2019-03-20 at 10 39 35 AM](https://user-images.githubusercontent.com/46533597/54693146-83811680-4afc-11e9-88c8-1073c9edbaae.png)

Polaris banner with heading and link:
![Screen Shot 2019-03-20 at 10 40 31 AM](https://user-images.githubusercontent.com/46533597/54693204-9dbaf480-4afc-11e9-8df0-8470e336d53f.png)

------------

Side note: This may also be a good time to explore writing more explicit guidelines for when to use certain styles of banners in less specific scenarios (i.e. banners other than critical/warning banners).

**Comment by virginiastart** [comment]
We should also have a pattern for what we say when a dismissible banner is dismissed. Right now, we have a few variations:

![unit-price warning banner confirmation](https://user-images.githubusercontent.com/11656248/58252038-26d7ed00-7d33-11e9-922c-c83bc15a668b.png)
<img width="721" alt="Screen Shot 2019-05-22 at 1 36 09 PM" src="https://user-images.githubusercontent.com/11656248/58252044-28a1b080-7d33-11e9-8572-18787a3e14be.png">

cc: @selenehinkley

**Comment by selenehinkley** [comment]
Thanks for adding to the issue, @virginiastart! For now this issue is part of the [Polaris backlog](https://github.com/orgs/Shopify/projects/485?fullscreen=true) so if anyone is interested in working out a pattern and contributing to the design system let me know and I can help them. In the meantime I'll be prioritizing a bigger project.

**Comment by caitlinmullen** [comment]
I'm interested in picking this up again, and I'll probably be better equipped to now that I'm actually working on Core. It might take a bit before I can give it some focused attention, but I'd be happy to collaborate (or let it go if someone else is interested in tackling this sooner).

**Comment by selenehinkley** [comment]
That would be fabulous, @caitlinmullen. @VanjaMitrovic, @sadiesaurus and I are going to start using every second Friday to do content quality assurance and you're welcome to join us if you're looking for a dedicated time to work on patterns :)

**Comment by caitlinmullen** [comment]
Sounds great, would love to join!
