### ISSUE TITLE
[v4][Page] Change singleColumn prop to narrowWidth

### ISSUE THREAD

**Issue by AndrewMusgrave** [Shopify/polaris-react#1572]
## Issue summary

`Page` has a prop named `singleColumn` and it's very deceptive. Page doesn't control layout and has nothing to do with columns. Tim and I have discussed renaming this prop `narrowWidth` to better represent its use.

Deprecation/Upgrade path
- Add `narrowWidth` to the component API and map it to `singleColumn`
- Remove `singleColumn` from documentation and replace it with `narrowWidth` (we'll have to properly compose our types to continue allowing `singleColumn`)
- Use deprecation warnings to inform consumers that `singleColumn` will be replaced with `narrowWidth` in `v5`

Using this approach consumers reading our documentation will start to use `narrowWidth` instead of `singleColumn`. Consumers will have an entire major version to change `singleColumn` to `narrowWIdth`.

**Comment by tmlayton** [comment]
I like this pattern. We should consider making it part of our https://github.com/Shopify/polaris-react/blob/master/documentation/Deprecation%20guidelines.md

**Comment by AndrewMusgrave** [comment]
I think so too. @chloerice created the guidelines for `console.warn` so maybe she has some opinions on deprecations as well?
