### ISSUE TITLE
[Navigation.Item] Add test for resize/navigationBarCollapsed

### ISSUE THREAD

**Issue by AndrewMusgrave** [Shopify/polaris-react#1585]
See https://github.com/Shopify/polaris-react/pull/1502#discussion_r284481567

**Comment by dpersing** [comment]
@AndrewMusgrave Do we have enough info on this issue for someone to start work?

**Comment by AndrewMusgrave** [comment]
The link goes to the previous test that is now skipped with an explanation 😄
