### ISSUE TITLE
[Sheet] Allow left or right

### ISSUE THREAD

**Issue by gil--** [Shopify/polaris-react#1609]
## Feature request summary

Would ya'll be open to me creating a PR which adds support for stickying the Sheet component to the left or right for desktop? Right now the CSS is all hardcoded with [right: 0](https://github.com/Shopify/polaris-react/blob/master/src/components/Sheet/Sheet.scss#L16) so I'd just add a helper class for right or left based on a prop, `location={left|right}`

## Rationale

I'd like to use the sheet as a sort of Hamburger menu which I'd want stuck to the left on desktop.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by danrosenthal** [comment]
Hey @gil--, my initial reaction is that this seems like a reasonable request, but I have a couple of concerns

- Aligning left would conflict with the placement of our `Navigation` component
- The described use-case (sounds like navigation) strikes me as not being consistent with the intended use of `Sheet`

Can you tell me a little more about what you're building? Why/how doesn't the existing `Navigation` component meet your needs?

**Comment by gil--** [comment]
It would be for all sizes as I'm building a "fullwidth" experience that has horizontal scrolling and requires as much horizontal scrolling as possible. Here's some sample screenshots (**NOTE** order data is randomly generated using fake data so not leaking any personally identifiable information):

<img width="1280" alt="Screen Shot 2019-06-03 at 8 44 09 PM" src="https://user-images.githubusercontent.com/3484527/58843821-3401af80-8642-11e9-970d-4b2806ef5c2e.png">
<img width="355" alt="Screen Shot 2019-06-03 at 8 44 27 PM" src="https://user-images.githubusercontent.com/3484527/58843822-3401af80-8642-11e9-88e9-0ba3f50ecec0.png">

Top left where "My Dashboard" is located would ideally be replaced with a "Menu" button which when clicked would show the `Sheet` flyout from left with the `Navigation` component inside. Here is a quick mockup where Sheet is mounted on left:

<img width="798" alt="Screen Shot 2019-06-03 at 9 05 25 PM" src="https://user-images.githubusercontent.com/3484527/58844043-6069fb80-8643-11e9-8ecd-392224a3613d.png">

There's just not enough room to keep it visible at all times on any breakpoint. I've considered just rolling something custom but would be ideal to re-use where possible to avoid increasing the # of JS/CSS.

**Comment by danrosenthal** [comment]
> I don't want to shove unwanted props/behavior into core Polaris so maybe it's just time to roll something custom for my nav.

I think that makes sense for now @gil--. I'll go ahead and close this as we do with all feature requests. If folks also have a need for this, they can upvote with a 👍 on the original comment.

If we see a lot of support for this, I can see us approaching a resolution that would look more like a modification to the `Navigation` component to support its use without the `Frame`, and the ability to force it to always render collapsed regardless of screen size. I think that would be more powerful, but the code changes necessary are non-trivial, as `Navigation`'s width is baked into a lot of our media queries.
