### ISSUE TITLE
[RollupActions] Abstract out some Page > Header code

### ISSUE THREAD

**Issue by beefchimi** [Shopify/polaris-react#1639]
I have a use case for the `Page > Header` in an app, independent from the `Page` component.

### Initial reaction

Having looked through the code, one approach could be simply pulling `Header` out of `Page` and renaming it `PageHeader`. Now, `Page` can still utilize the sibling component, and apps can utilize `PageHeader` in the manner described above.

### More considered reaction

Having chatted over Slack, I think the better solution might be to keep `Header` as an unexposed child of `Page`... and instead, pull out some of the code from `Header` to be more reusable across the library.

The perfect candidate for this are the `Action` and `ActionGroup` sub-components of `Header`. These could both be moved up into a new `RollupActions` component.

With these "building blocks" in place, `Page > Header` can remain where it is, but be cleaned up to reuse the new component, and I could then just roll my own `Header`.

A more in-depth conversation can be found here:
https://shopify.slack.com/archives/C8H54T86Q/p1559833670026100

**Comment by danrosenthal** [comment]
I’m definitely in favour of this approach. Feels like the right level of abstraction and would create tremendous flexibility for teams whose needs aren’t met by the existing Page componwnt
