### ISSUE TITLE
Sidebar active page highlight is highlighting inaccessible pages on Staff account

### ISSUE THREAD

**Issue by evansimoni** [Shopify/polaris-react#1642]
## Issue summary
I'm logged in as a Staff account and don't have access to Online Store or Point of Sale, but they're highlighted with the active page highlight.

![screencapture-indiaswag-myshopify-admin-apps-2019-06-06-15_47_38](https://user-images.githubusercontent.com/5864178/59061888-8a553500-8872-11e9-8454-121d69c55e2a.png)

## Expected behavior

It's not highlighted

## Actual behavior

It's highlighted

## Steps to reproduce the problem

1. Login to [this shop](https://indiaswag.myshopify.com/admin/apps) as Evan Simoni
2. Look at the sidebar

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser: Version 74.0.3729.169 (Official Build) (64-bit)
- Device: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
- Operating System: MacOS Mojave 10.14.5

## Related issue
https://github.com/Shopify/polaris-react/pull/1304

**Comment by chloerice** [comment]
Hey @evansimoni! Gonna ping you directly about this.
