### ISSUE TITLE
Multiline TextField component can't be simulate test

### ISSUE THREAD

**Issue by Justinidlerz** [Shopify/polaris-react#1667]
## Issue summary
I'm using the TextField component then set the `multiline` property was true.  
I want to test my form components.  
When I simulating the change event for the `textarea` element. It does not update the data. 
For example:
![image](https://user-images.githubusercontent.com/7475347/59319232-7ab76f80-8cfc-11e9-8591-c84e130f6ca8.png)
It has thrown an error:

Error: expect(jest.fn()).toBeCalled()
Expected mock function to have been called, but it was not called.

## Expected behavior
It should update the data and submit the form then the function will be called.

## Actual behavior
It has thrown an error:

Error: expect(jest.fn()).toBeCalled()
Expected mock function to have been called, but it was not called.

## Steps to reproduce the problem

1. Write a component use the TextField component then set the `multiline` property was true.  
2. Write a tester for this component and simulating the change event for the `textarea` element.

**Comment by AndrewMusgrave** [comment]
Hi Justin, you can set the textfield's value then simulate the change.
```js
...
wrapper.find('input').getDOMNode().value = 'two'
wrapper.find('input').simulate('change')
...
```

**Comment by Justinidlerz** [comment]
@AndrewMusgrave 
I tried that, but it's doesn't work too. : (  
```
wrapper.find('textarea').getDOMNode().value = 'new value';
wrapper.find('textarea').simulate('change');
```
I using the component with `multiline` property so it's a Textarea element.  

I'm using the [Formik](https://github.com/jaredpalmer/formik) to manage the form status now.

**Comment by blaze-nitd** [comment]
This is not resolved. Please help. Its bringing nightmares in testing.
