### ISSUE TITLE
PositionOverlay incorrectly calculating the left value for right aligned components with scroll bars

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#1673]
## Issue summary

The position overlay is having problems with the calculation of the width of the element. The menu items wrap onto two lines instead of one, and resizing the browser causes all kinds of oddness when the left value is changed to `right: 0;`.

Here is an example of the problem in web:
![HbAAMp](https://user-images.githubusercontent.com/19199063/59374755-8dd93800-8d1a-11e9-9242-00357c1be04e.gif)

## Expected behavior

The menu items do not wrap when there is a scrollbar. In version `4.0.0` we fixed this using the `MutationObserver`.

## Actual behavior

Menu items are wrapping, scroll bar is visible.

## Steps to reproduce the problem

1. Enable view scrollbars, or use firefox
1. Open web and click the user menu in the top right
1. See the menu items wrapping onto two lines

**Comment by alex-page** [comment]
I have figured out why this is happening. 

We set a `left` value on the `PositionedOverlay` based on the result of `calculateHorizontalPosition`. If we have a page that is 1200px wide and the left value is 1100px the menu will grow to have a width of 100px. Setting a `min-width` on the menu fixes this however it is causing the calculation to work harder as it now has a width to account for when calculating the left position.

The way this should work is when a user sets `preferredAlignment = 'right'` the `PositionedOverlay` should be calculating the horizontal position from the `right`. The above problem could be solved by setting:
```
left: auto !important;
right: 0;
```

**Comment by kvendrik** [comment]
Same issue: https://github.com/Shopify/polaris-react/issues/955. Will close that in favour of this.

**Comment by chloerice** [comment]
See latest status of fix for this issue in the PR https://github.com/Shopify/polaris-react/pull/1692#issuecomment-510934111

**Comment by dleroux** [comment]
This was the PR that added the preferredAlignment: https://github.com/Shopify/polaris-react-deprecated/pull/1390
