### ISSUE TITLE
Tabs do not collapse when using safari on iPhone

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#1677]
## Issue summary

On safari iOS we have a problem with tabs not collapsing into the little three dot menu.

<img width="422" alt="Screen Shot 2019-06-12 at 3 21 27 PM" src="https://user-images.githubusercontent.com/19199063/59385493-74dc8100-8d32-11e9-98eb-7fc35422f35c.png">

## Expected behavior

Tabs should collapse.

## Actual behavior

Tabs do not collapse.

## Steps to reproduce the problem

1. Open the [tabs page in the styleguide](https://polaris.shopify.com/components/navigation/tabs) on iOS or iPhone

**Comment by mbaumbach** [comment]
This also happens in embedded apps in the Shopify iOS app due to it being rendered within Safari.
