### ISSUE TITLE
[Button] "Plain destructive button" example should have Android & iOS screenshot

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-react#1681]
Seen on https://polaris.shopify.com/components/actions/button

![Screen Shot 2019-06-13 at 11 00 19 AM](https://user-images.githubusercontent.com/85783/59456194-aacd4400-8dca-11e9-8d63-94393f4a8560.png)

**Comment by chloerice** [comment]
It looks like we just need to separate the plain destructive variants from the destructive button screenshots. What's the process for making iOS/Android component screenshots? I notice that the images are all a certain dimension. Would it be the wrong approach to create the plain destructive assets by modifying the existing screenshots to be two separate images?

Current screen shots that could be split:

|  iOS | Android  |
|---|---|
|<img width="376" alt="Screen Shot 2019-06-17 at 5 41 43 PM" src="https://user-images.githubusercontent.com/18447883/59639061-16474680-9128-11e9-87f5-1dc9dee7f9b6.png">|<img width="395" alt="Screen Shot 2019-06-17 at 5 40 45 PM" src="https://user-images.githubusercontent.com/18447883/59639068-1e9f8180-9128-11e9-9b8c-aa1a7880571c.png">|
