### ISSUE TITLE
[Range slider] "Dual thumb range slider" example should have iOS/Android screenshots

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-react#1682]
Seen on https://polaris.shopify.com/components/forms/range-slider

![Screen Shot 2019-06-13 at 11 05 02 AM](https://user-images.githubusercontent.com/85783/59456415-1c0cf700-8dcb-11e9-9388-d7caa125f05b.png)

**Comment by see-mack** [comment]
So we have a dev component that's not used in any app for the slider on iOS but it's not in the iOS UI kit. For android, it doesn't exist as a dev component _or_ in the UI Kit for android.
