### ISSUE TITLE
[Text field] "Text field with right aligned text" example should have iOS/Android screenshots

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-react#1683]
Seen on https://polaris.shopify.com/components/forms/text-field

![Screen Shot 2019-06-13 at 11 05 53 AM](https://user-images.githubusercontent.com/85783/59456479-3d6de300-8dcb-11e9-91f7-d0d2dac86f06.png)

**Comment by see-mack** [comment]
We don't use right-aligned text fields on mobile unless it's for Right-To-Left languages. I'll remove it from the android/ios section of the docs.
