### ISSUE TITLE
Giant font while rendering

### ISSUE THREAD

**Issue by sambazargan** [Shopify/polaris-react#1689]
A bit odd to explain and could be with my app design rather than an issue with Polaris, but here goes.

My app is embedded and using react router. After clicking a link component I get a big flash and then a normal looking screen. For example I have a resource list, and it seems like the font goes giant and then snaps into place. Wondering if anyone has experienced this? I load my css using ES6 import and using web pack hot reload

**Comment by dpersing** [comment]
Hi @sambazargan! Thanks for your patience. Are you still running into this issue? Can you share what browser(s) you're seeing it in? Thanks!

**Comment by sambazargan** [comment]
Hi Devon,

Last time I checked yes. Has it been reported elsewhere?

Sent from my iPhone

On Aug 20, 2019, at 5:20 PM, Devon Persing <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @sambazargan<https://github.com/sambazargan>! Thanks for your patience. Are you still running into this issue? Can you share what browser(s) you're seeing it in? Thanks!
