### ISSUE TITLE
[Contextual Save Bar] Ability to provide component as button content

### ISSUE THREAD

**Issue by darrenhebner** [Shopify/polaris-react#1694]
## Feature request summary
I'm looking to implement this 'saving' state on the secondary action. Currently the prop only takes a string.

If I pass a React component we end up getting an infinite loop because this check can't handle a React component: https://github.com/Shopify/polaris-react/blob/master/src/components/ContextualSaveBar/ContextualSaveBar.tsx#L28

<img width="360" alt="Screen Shot 2019-06-17 at 3 30 31 PM" src="https://user-images.githubusercontent.com/4441303/59631054-e0e52d80-9114-11e9-8e48-c97f2fd5ec47.png">

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by AndrewMusgrave** [comment]
👋 Would taking an action work for you? Similar to other components (e.g. [page](https://polaris.shopify.com/components/structure/page/primaryAction))

**Comment by AndrewMusgrave** [comment]
@ddgwilli I had a chat with Darren and he said accepting an action rather than a react node would work for him
