### ISSUE TITLE
Modal dialogue

### ISSUE THREAD

**Issue by ptcampbell** [Shopify/polaris-react#1698]
_tl;dr_
When moving to app-bridge-react, please consider supporting modals which accept React content.

---

I see that the Modal component is being deprecated. I can understand why you would want to do this, but I can't actually find `@shopify/app-bridge-react` anywhere and am wondering what is actually going to change? 

Will the components be any different to the existing ones? Since they cater specifically for embedded app experiences, will there be appetite on Shopify's end for providing a richer experience? (e.g. forms)

I guess I am hoping for an official way of doing this, but am also wondering if I should give up on this and design around the problem. Which would be a shame because it's a pretty common pattern within your own admin UI.

There are workarounds, but I am worried that they may stop working if the API changes. That is why I think it's important to consider supporting it "officially".

Here is an example of what I mean by a rich experience. 

![image](https://user-images.githubusercontent.com/876594/59655934-d9dc1080-9150-11e9-933b-0abbe0b33ce5.png)

**Comment by BPScott** [comment]
Modal, and all other components for use in an embedded context (Loading, Page, ResourcePicker, Toast) will continue to exist as they are in @shopify/app-bridge-react.

The repo for app-bridge-react is currently private, but you can see the contents of the package at https://unpkg.com/@shopify/app-bridge-react@1.6.5/

**Comment by dpersing** [comment]
Hi @ptcampbell! @BPScott's comment above includes some context and guidance. Resources are also available at https://help.shopify.com/en/api/embedded-apps/app-bridge

**Comment by tmlayton** [comment]
> When moving to app-bridge-react, please consider supporting modals which accept React content.

Hey @ptcampbell this is something we’ve talked about a bit over the last couple years, but not sure if it is something the App Bridge team is considering. I suspect it is unlikely, though. The way to achieve this is with iframe content, in which you can still own all of the UI. This is done via the `src` prop.

> Will the components be any different to the existing ones?

There have been some minor improvements, but largely the components remain the same in `@shopify/app-bridge-react`. I would say the biggest change is `Page` (which delegates to the title bar action in an embedded context) is now `TitleBar`, specifically meaning you can easily use both components.

> wondering if I should give up on this and design around the problem

I would suggest working around the problem and making use of the `src` prop and the iframe content.

If you are curious to know more about why we decided to split this out, take a look at https://github.com/Shopify/polaris-react/issues/814.

**Comment by tmlayton** [comment]
In terms of App Bridge feature requests, the best place for now is the [Shopify APIs and SDKs forum](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology).

**Comment by ptcampbell** [comment]
@tmlayton I think splitting the packages is a good idea, but it's disappointing we can't pass through React elements. Oh well, thanks for the response. I'll find a way.
