### ISSUE TITLE
[Page Component] Add an identifying image to the page component

### ISSUE THREAD

**Issue by jaxee** [Shopify/polaris-react#1711]
## Feature request summary

Add an image next to the title of the `<Page />` component.
Proposed (rough) design:
![image](https://user-images.githubusercontent.com/12052693/59790338-be325080-929d-11e9-85d7-1e1bf06434ea.png)

## Rationale

This would allow for visual identification of the purpose of the page, such as:
- Customer avatars
- App icons
- Merchant avatars

cc @katbuilt @djirdehh

**Comment by jaxee** [comment]
### Implementation Details
Prop name: `image`
Type: SVG | Avatar | Thumbnail | null

Open to suggestions in regards to the types allowed.

### Question
Should the embedded app only `icon` prop be opened up to all page components instead of creating an `image` prop?

**Comment by jaxee** [comment]
### Other possible solutions
1. [Above] Adding to the Page API with a new prop for the visual identifier
2. Find a way to use a more granular layer to build up the page header out of smaller pieces

**Comment by ry5n** [comment]
@jaxee and I chatted briefly about the options to implement this, as it makes sense for the apps use case. The Polaris team will help assess and assist. Thanks!

**Comment by dleroux** [comment]
Question about this: In the example, the text is vertically aligned with the thumbnail. What happens when the text wraps or has a subtitle, that causes it to be higher than the thumbnail. Working on a solution but right now it's always aligned to the top: https://github.com/Shopify/polaris-react/pull/1880
