### ISSUE TITLE
Link modifies color of SVG child

### ISSUE THREAD

**Issue by carysmills** [Shopify/polaris-react#1724]
## Issue summary

I was trying to use the Link component around the a component that has a Polaris icon inside of it. But [this mixin](https://github.com/Shopify/polaris-react/blob/master/src/components/Link/Link.scss#L2)modified the fill of my SVG.

Maybe this is intentional, but it probably means the placeholder component in web should be reworked 

## Expected behavior
I should be able to use a Link around an SVG/icon without it modifying the color.

<img width="84" alt="Screen Shot 2019-06-21 at 2 59 20 PM" src="https://user-images.githubusercontent.com/12213371/59945317-31ba9600-9435-11e9-8aac-ee37b107e0b8.png">

## Actual behavior
It modifies the color

<img width="95" alt="Screen Shot 2019-06-21 at 3 04 14 PM" src="https://user-images.githubusercontent.com/12213371/59945514-ddfc7c80-9435-11e9-8e35-f24320fb1975.png">

<img width="211" alt="Screen Shot 2019-06-21 at 3 04 51 PM" src="https://user-images.githubusercontent.com/12213371/59945551-f66c9700-9435-11e9-923f-b5113927d6da.png">

## Steps to reproduce the problem
Wrap a Link around a Polaris Icon

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by BPScott** [comment]
ping @ry5n, I think this is one for you as this was added in #1247. Perhaps we should only force the recolor within the IconLockup class instead of the whole Link?

**Comment by ry5n** [comment]
^ Yes, that’s likely the fix here. I can open a PR.
