### ISSUE TITLE
Contributing: Is the Slack channel still active?

### ISSUE THREAD

**Issue by martenbjork** [Shopify/polaris-react#1731]
## Issue summary

The [How to Contribute](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md#how-to-get-in-touch) page says that the Slack channel is the best way join in on the Polaris conversion. The GitHub Issues bot (**probot-shopify**) also references that channel in its auto-replies (*“You can also join #polaris on the Shopify Partners Slack.”*).

However, when I asked Shopify support about it, they responded that: *“I've been digging around and am being told that this no longer a thing.”*

- Is the channel still active?
- Is there some other, open channel for Polaris related talk?

**Comment by kaelig** [comment]
Thank you for asking, @martenbjork! The Polaris channel still exists but it's not active (url: https://shopifypartners.slack.com/messages/C8PTBMWNR).

There are 145 people in it, but I'm not sure why it's so calm. The Polaris team infrequently posts in that Slack team, and we also monitor the channel in case anything comes up.

As far as I know, there aren't any other public Slack teams/channels about Polaris.

**Comment by martenbjork** [comment]
All right, @kaelig, thanks for the quick reply! Registration to that Slack channel is limited to a few domains, so not possible for anyone to join, right?

<img width="321" alt="Skärmavbild 2019-06-26 kl  15 37 51" src="https://user-images.githubusercontent.com/875708/60184450-64470300-9828-11e9-8371-fa5282544cd0.png">

Anyway, I'll dive into the issues and roadmap and see how I can help. Feel free to close this issue!
