### ISSUE TITLE
Change progress bar color

### ISSUE THREAD

**Issue by ulazimir** [Shopify/polaris-react#1735]
## Feature request summary
I want to be able to change progress bar color.

I want to use progress bar as some resource usage indicator. I want to be able to change progress bar color depending on resource usage percent, e.g. if resource usage is less then 80% - green, if resource usage is more then 80% - yellow, if resource usage is 100% - red. Is there a way to implement that? 

## Rationale

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dpersing** [comment]
Hi @ulazimir! Thanks for your patience. This isn't a feature that currently comes with the progress bar, but it's something we can definitely keep in mind, since we have other features that use color/text/icons to convey states.
