### ISSUE TITLE
[Autocomplete][v1] Mouse down on option briefly closes the option popover

### ISSUE THREAD

**Issue by lukashlavacka** [Shopify/polaris-react#1736]
## Issue summary

Mouse down on option briefly closes the option list popover when it should stay open.

## Steps to reproduce the problem

1. https://polaris.shopify.com/components/forms/autocomplete
2. Focus autocomplete
3. Mouse down on option
4. (optional) Mouse up

## Expected behaviour

After mouse down I expect option list to stay open.

## Actual behaviour

After mouse down option list briefly closes and then opens

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.
