### ISSUE TITLE
[a11y] Tabs have invalid aria-controls values

### ISSUE THREAD

**Issue by dpersing** [Shopify/polaris-react#1748]
## Issue summary

The tab component uses `aria-controls` to connect tabs to their related tab-panels. However, since the tab panel content doesn't exist in the DOM until it's called by the user by activating a tab, the values of unselected tabs' `aria-controls` are technically invalid.

## Expected behavior

ARIA attributes that rely on element `id` values will point to `id` values that exist on the page.

## Actual behavior

The tab component has `aria-controls` attributes that point to `id` values that don't exist on the page.

## Steps to reproduce the problem

1. Navigate to the tabs page: https://polaris.shopify.com/components/navigation/tabs
1. Use an automated tool like [Accessibility Insights for Web](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?hl=en) or `axe-core` (which runs in Storybook) or use the web inspector to view `aria-controls`/`id` pairs in the DOM.

## Recommendation

This issue will keep coming up in automated tests. The most straightforward fix would be to always include the tab panels with the appropriate `id` values in the DOM and hide them with `hidden` or similar. [See the ARIA 1.1 authoring guidelines for examples.](https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-2/tabs.html)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.17.0+
- Browser: All
- Device: All
- Operating System: All

**Comment by dpersing** [comment]
@alex-page, I'm curious if this got flagged in pa11y, since I didn't see it in the 💩list discussion?

**Comment by alex-page** [comment]
It is flagged by pa11y but required more work then a quick fix :)

**Comment by dpersing** [comment]
Realized this issue is duplicating https://github.com/Shopify/polaris-react/issues/1748! Closing it.
