### ISSUE TITLE
[Pagination] Add label prop

### ISSUE THREAD

**Issue by Tetsuro** [Shopify/polaris-react#1760]
## Feature request summary

Add a `label` prop to the Pagination component. 

## Rationale

Allows for a label to provide more information regarding pagination. For example, we can use it to show `X of X pages`. 

![image](https://user-images.githubusercontent.com/351842/60538856-6a7e2900-9cd9-11e9-9ee6-c887081424c9.png)

## Implementation details

- prop name: `label?` 
- prop type: string

The `aria-live` attribute can be used to read out the label to screen reader users.

![](https://user-images.githubusercontent.com/351842/60367395-195df480-99bc-11e9-8f3c-344d3e90b6aa.gif)

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by beefchimi** [comment]
For reference, this is implemented in `online-store-ui`:
https://github.com/Shopify/online-store-ui/pull/230

The PR should be relatively easy to follow, as Tetsuro cloned the component in the first commit, then made adjustments in all subsequent commits.
