### ISSUE TITLE
[Page] Allow SecondaryActions to be a dropdown (or allow control of SecondaryActions/ActionGroup Ordering)

### ISSUE THREAD

**Issue by brandon-yetman** [Shopify/polaris-react#1762]
## Feature request summary

Currently, a dropdown menu within the Page header component must be an `ActionGroup`, and the current implementation forces all `ActionGroups` to be ordered after `SecondaryActions`. It is not possible for a `SecondaryAction` to be a dropdown menu.

The requested feature is to either allow for a `SecondaryAction` to optionally be a dropdown, or allow control over the ordering of `ActionGroups` and `SecondaryActions`.

## Rationale

Issue that brought up this feature request is tracked here: https://github.com/Shopify/core/issues/7110

In short, for the OrderDetails React port project, the current ERB OrderDetails page has a "Print" secondary action which is sometimes a single action, or is a dropdown containing many print options (based on whether an order has ShippingLabels).

e.g.
<img width="652" alt="Screen Shot 2019-07-02 at 3 45 15 PM" src="https://user-images.githubusercontent.com/51451780/60542001-d021e380-9ce0-11e9-81b5-1bb996130c40.png">

There is currently no way to replicate this functionality, at least in terms of controlling `Print` to always be the first action if it is an ActionGroup.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by brandon-yetman** [comment]
PR for this issue is here https://github.com/Shopify/polaris-react/pull/2057

**Comment by chloerice** [comment]
Closed by #2057
