### ISSUE TITLE
[Page] `icon` prop should be deprecated

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react#1776]
## Issue summary

The `Page.icon` prop was originally an "embedded app only" prop for apps to add their logos to the app bar next to the app name (`title`).

<img width="422" alt="Screen Shot 2019-07-03 at 11 05 58 AM" src="https://user-images.githubusercontent.com/18447883/60604950-a7542980-9d86-11e9-9f6e-c8e3e39005ae.png">

Since the release of the App Bridge, the app icon is no longer parsed from `Page.icon`. Instead, it is supposed to be uploaded in the app developer's Partner Dashboard, as clarified in #1690. 

As such, the `icon` prop should be deprecated since it no longer does anything. 

## Expected behavior

A deprecation warning with a link to instructions for how to upload the app icon in the Partner Dashboard should print to the console when the `icon` prop is set on `Page`.
## Actual behavior

The `icon` is not rendered in the embedded app bar, with no indication of why.

**Comment by BPScott** [comment]
I thought it did that already? https://github.com/Shopify/polaris-react/blob/master/src/components/Page/components/Header/Header.tsx#L99-L102

**Comment by BPScott** [comment]
Icon has been removed for some time
