### ISSUE TITLE
Banner throws error in console about not matching headers in client and server

### ISSUE THREAD

**Issue by Jurgyte** [Shopify/polaris-react#1781]
## Issue summary
I get this warning: 
<img width="767" alt="Screenshot 2019-07-03 at 11 59 27" src="https://user-images.githubusercontent.com/20574603/60662502-3cc5eb00-9e65-11e9-8727-7b3ba3f20b92.png">

I have a component with Banner and a loop which renders a few child components. The child component contains two Banners (with a condition case to render banners) and some content.

## Expected behavior

It seems warning comes from the second banner.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: "@shopify/polaris": "^3.15.0",
- Browser: Chrome
- Device: Laptop
- Operating System: MacOS

**Comment by BPScott** [comment]
Thanks for the report.

This is a known issue, see #1761 and #1283.

I'm going to close this as a duplicate as the other two issues already document this behaviour.
