### ISSUE TITLE
[ResourceList] resourceName should also accept a string

### ISSUE THREAD

**Issue by patsissons** [Shopify/polaris-react#1786]
## Issue summary

The `singular` and `plural` approach does not fit all use cases. To support other scenarios without duplicating the resource name we can adjust the prop to consume a string instead of the object it currently consumes. 

## Expected behavior

```tsx
<ResourceList
  resourceName="aircraft"
  // ... 
/>
```

## Actual behavior

```tsx
<ResourceList
  resourceName={{plural: 'aircraft', singular: 'aircraft'}}
  // ... 
/>
```

**Comment by laurenmayers** [comment]
^ Unassigning myself for now, as after discussion with @dfmcphee, I'm not sure of the benefits of changing this prop:
- There are still valid use cases for defining `singular` & `plural`, and without the built-in option, developers would need to add conditional rendering to `resourceName` to handle this. 
- We should  also consider the impact of removing `singlular` & `plural` properties on translations/other languages where the differences might be significant. 
- It would be a breaking change as we'd be changing the prop type (although I'm not sure if this is easily handled having not worked in polaris-react before). 

 cc @patsissons

**Comment by patsissons** [comment]
I think my intent with this issue was to change `resourceName` type to `string | {plural: string, singular: string}`. That said, this is such a minor issue that reflecting on it again now feels like it should be closed.

**Comment by movermeyer** [comment]
Related to https://github.com/Shopify/polaris-react/issues/4031
