### ISSUE TITLE
App Bridge components give type error for version

### ISSUE THREAD

**Issue by kj** [Shopify/polaris-react#1787]
## Issue summary

I'm trying to upgrade my app following the deprecation notices of App Bridge components, however I'm facing the following error:

![error](https://user-images.githubusercontent.com/628170/60688259-ad770280-9e79-11e9-8663-83fb103f30b7.png)

I tried to strip the app down to seemingly the most basic example and I still receive this error whenever I try to use an app bridge component inside `Provider`.

```
<AppProvider> 
  <Provider config={{apiKey, shopOrigin}}>
    <Loading /> 
  </Provider>
</AppProvider>
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.18.0
- App Bridge version number: 1.6.6
- Browser: Chromium 75
- Device:
- Operating System: Linux

**Comment by kj** [comment]
Okay, I was using this bundler, mainly for it's speed over Webpack (which had worked perfectly up until now):

https://github.com/fuse-box/fuse-box

I was using this configuration:

```
  
const {FuseBox, QuantumPlugin, TerserPlugin} = require('fuse-box');
const fuse = FuseBox.init({
  homeDir: 'src',
  output: 'assets/$name_$hash.js',
  // https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers
  // https://kangax.github.io/compat-table/es2016plus/
  target: 'browser@es2015', // required for for...of;
  hash: true,
  sourceMaps: true,
  useTypescriptCompiler: true,
  plugins: [
    process.env.NODE_ENV === 'production' && QuantumPlugin({
      bakeApiIntoBundle: 'bundle',
      cache: false, // for source maps
      treeshake: true,
    }),
    process.env.NODE_ENV === 'production' && TerserPlugin({
      keep_classnames: true, // prevent mangling for page class names in routes.js
    }),
  ],
});
fuse.bundle('bundle').instructions('> index.jsx');
fuse.run();
```

I switched to Webpack, and I'm no longer getting the error.

**Comment by dpersing** [comment]
@kj Thanks so much for updating the issue! Glad you found a solution.
