### ISSUE TITLE
[Bulk Actions] move BulkActions component to Polaris

### ISSUE THREAD

**Issue by sijad** [Shopify/polaris-react#1792]
## Feature request summary

now that filters moved to Polaris (#1510), is it possible to move BulkActions to Polaris too?

## Rationale

there is other situations that BulkActions can be useful other than Resource list. 

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dleroux** [comment]
Thanks you @sijad. This definitely has come up before and something we'd most likely support. However, we don't have it planned at the moment. I'll close this as we do with all our feature request and upvote it. If ever you end up doing this in your project let us know.
