### ISSUE TITLE
Embedded Video Player

### ISSUE THREAD

**Issue by 416serg** [Shopify/polaris-react#1804]
## `<VideoPlayer/>` ? 🤷‍♂ 

VideoPlayer can be used to embed instructional/tutorial videos within applications.

### Embedded Video in a Modal

<img width="1344" alt="Screen Shot 2019-07-09 at 3 07 43 PM" src="https://user-images.githubusercontent.com/3760543/60916002-57c89e80-a25b-11e9-8163-68ff815db76f.png">

## Props

List props and type declarations:

- **url** (required): `string` – url of the video to supply to the iframe. Hosting videos is going to be an issue since there is no standardized way of hosting videos AFAIK. (The careers page)[https://www.shopify.com/careers] uses Wistia to host the video.
- **aspectRatio** (optional): `AspectRationEnum` – something like `21by9 | 16by9 | 4by3 | 1by1`

**Comment by dpersing** [comment]
Hi @416serg! Thanks for your patience. We don't have a current plan to implement a video component, but I'll tag this issue so we can track it with other feature requests. Thanks so much for taking the time and providing some great context and prop recs.

**Comment by bquinch** [comment]
I don't understand. You ask us to make videos to explain the apps but you don't create a video component ?
