### ISSUE TITLE
ResourcePicker updating resourceType

### ISSUE THREAD

**Issue by jrbuhl93** [Shopify/polaris-react#1814]
## Issue summary

The ResourcePicker does not update to the correct resource type when dynamically changing the ResourceType in React (eg "Product" to "Collection"). Even when importing ResourcePicker from @shopify/app-bridge-react.

## Expected behavior

When I update a state variable or computed variable that is used for the ResourceType of the ResourcePicker, the rendered ResourcePicker should use the updated ResourceType.

## Actual behavior

The ResourcePicker still uses the original ResourceType.

## Steps to reproduce the problem

1. Use this code in jsx: 
<ResourcePicker
          resourceType={this.state.resource_type}
          showVariants={false}
          open={this.state.open}
          onSelection={(resources) => this.handleSelection(resources)}
          onCancel={() => this.setState({ open: false })}
        />
2. Update the state's resource_type, say from "Product" to "Collection".
3. Update the state's open to true.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.18.0
- Browser: chrome
- Device: macbook pro 2015
- Operating System: macOS Mojave version 10.14.5

**Comment by jrbuhl93** [comment]
Here is a workaround I am using:

{(resource_type === "Collection") && (
          <ResourcePicker
            resourceType="Collection"
            showVariants={false}
            open={this.state.open}
            onSelection={(resources) => this.handleSelection(resources)}
            onCancel={() => this.setState({ open: false })}
          />
)}
{(resource_type === "Product") && (
          <ResourcePicker
            resourceType="Product"
            showVariants={false}
            open={this.state.open}
            onSelection={(resources) => this.handleSelection(resources)}
            onCancel={() => this.setState({ open: false })}
          />
)}

I'll leave this issue open for now, since I don't know if the ResourceType not updating is intended behavior.

**Comment by Popesites** [comment]
Hey @jrbuhl93 I had the same problem, found your work around on Google, thanks for sharing!

**Comment by VictorBaudot** [comment]
Why was this issue closed? I also get this problem.

**Comment by BPScott** [comment]
This issue was closed because the ResourcePicker has long been deprecated and we've pushed people to use the one from `@shopify/app-bridge-react`. As of v5 ResourcePicker was completely removed from the polaris-react codebase.

You should reraise this issue with the team who maintain `@shopify/app-bridge-react` https://github.com/Shopify/shopify-app-bridge
