### ISSUE TITLE
ResourcePicker is broken with App-Bridge version 1.6.6

### ISSUE THREAD

**Issue by MattLiang** [Shopify/polaris-react#1819]
## Issue summary

The polaris `ResourcePicker` does not work when using `@shopify/polaris` v3.18.0 and `@shopify/app-bridge-react` v1.6.6 (Our app-bridge version is also 1.6.6).

To give some context, we’re doing a package upgrade sweep and previously imported `ResourcePicker` from Polaris. In the console, we saw the warning:
```
index.es.js:17290 Deprecation: `ResourcePicker` is deprecated and will be removed in v5.0. Use `ResourcePicker` from `@shopify/app-bridge-react` instead. For example, `import {ResourcePicker} from '@shopify/app-bridge-react';
````

The component containing the `ResourcePicker` is wrapped with the `AppBridgerProvider` from `app-bridge-react`.

We thought because this is a deprecation warning, the component would still function, but it did not. We needed to modify our code to import `ResourcePicker` from app-bridge-react instead.

Looking at polaris-react’s dependencies, it specifies App Bridge ^1.3.0

## Expected behavior

Can interact with the the ResourcePicker

## Actual behavior

Cannot interact with the ResourcePicker in any way

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: v3.18.0
- App-bridge version: v1.6.6
- App-bridge-react version: v1.6.6
- Browser: Version 75.0.3770.100 (Official Build) (64-bit) 
- Device: Macbook
- Operating System: 10.14.5

**Comment by BPScott** [comment]
The Provider and the app-bridge components you use must come from the same package, you can't intermix them (e.g. using the Provider from `shopify/app-bridge-react` and using ResourcePicker from `@shopify/polaris`.

You must do either:

Both come from polaris:

```js
import {AppProvider, ResourcePicker} from '@shopify/polaris';

<AppProvider apiKey="abc" shopOrigin="example.com">
  <ResourcePicker /* ... */>
  </ResourcePicker
</AppProvider>
```

Both come from app-bridge-react:

```js
import {Provider, ResourcePicker} from '@shopify/app-bridge-react';

<Provider config={{apiKey: 'abc', shopOrigin: 'example.com'}}>
  <ResourcePicker /* ... */>
  </ResourcePicker
</AppProvider>
```


I appreciate that deprecation message is not very clear that both must be changed at the same time. I'll see if we can clarify that message.
