### ISSUE TITLE
[Image] is undocumented

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react#1826]
## Issue summary

The `<Image />` component needs documentation. It's a great little component that when used properly, i.e. with source sets could be great for performance optimizations. It looks like there's a cross origin behaviour that could be helpful to document as well.

**Comment by AndrewMusgrave** [comment]
An additional note: before we release documentation we may want to rethink [spreading props](https://github.com/Shopify/polaris-react/blob/01d6f7b81559d822e5c16e365fd3be3bc6092693/src/components/Image/Image.tsx#L36) onto the image. It's the only component we do this in, and will also apply styles (className, styles, etc).

**Comment by kyledurand** [comment]
Example of how to use the sourceSet prop for documentation

```tsx
<Image
  alt=""
  source="https://images.unsplash.com/photo-1518107784960-eb57c673a7ba?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60"
  sourceSet={[
    {
      source:
        'https://images.unsplash.com/photo-1510798831971-661eb04b3739?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      descriptor: '568w',
    },
    {
      source:
        'https://images.unsplash.com/photo-1533155870708-1fd99390f81b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      descriptor: '780w',
    },
    {
      source:
        'https://images.unsplash.com/photo-1517480625158-292a09aee755?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
      descriptor: '3x',
    },
  ]}
/>
```

I noticed we've also gotten rid  of the `sourceSetSizes` prop that the original component had at some point. This would look like:

`sourceSetSizes="(max-width: 568px) 80vw, (max-width: 780px) 80vw, (max-width: 1050px) 80vw, 50vw"`

I'm not sure we really need that but it would be good to look into at some point. [Here's the link to the original PR](https://github.com/Shopify/web/pull/519/files)
