### ISSUE TITLE
ResourcePicker for ProductVariant needs to show the product name

### ISSUE THREAD

**Issue by alexdover** [Shopify/polaris-react#1833]
I know this issue has been raised before (https://github.com/Shopify/polaris-react/issues/905) but it seems it has now been closed and as far as I can tell there was no feedback on when it might be addressed.

It seems to me that not showing the product name in the variant picker makes it extremely difficult, if not impossible, for a merchant to select the correct variant.

The way the product picker shows the variants is perfect, but it isn't possible to restrict the merchant to only selecting a single variant.

For my use case, I need to allow the merchant to select a variant so it would be really helpful to know if this is going to be addressed by Shopify and if so when so that I can decide if I wait for the 'native' resource picker to be updated or if I go ahead and engineer my own solution.

Thanks in advance for any help you can provide

**Comment by markiiikram** [comment]
Thanks for the issue @alexdover. The Polaris component has now been deprecated, App Bridge now renders and controls the `ResourcePicker` https://help.shopify.com/en/api/embedded-apps/app-bridge/actions/resourcepicker. As their repo is currently not open source I'm pinging @gf3 to communicate the best place to surface these issues.

**Comment by alexdover** [comment]
Thanks - any pointers on where we can log this issue for attention would be much appreciated.

**Comment by gf3** [comment]
the shopify forums is the best place until we can get our repo open sourced ↓

https://community.shopify.com/c/Shopify-APIs-SDKs/

**Comment by ltakens** [comment]
+1 On this request to show full titles (product name + variant title) on ResourcePicker.ResourceType.ProductVariant

<img width="684" alt="Screenshot 2020-10-07 at 20 24 53" src="https://user-images.githubusercontent.com/12794611/95372100-63ca6280-08db-11eb-9f09-e9047957ba9b.png">

I guess for now we'll have to build our own variant picker component.
