### ISSUE TITLE
Autocomplete TextField overrides autoComplete attribute

### ISSUE THREAD

**Issue by samjrdn** [Shopify/polaris-react#1834]
## Issue summary

The `Autocomplete.TextField` component forces the `autoComplete` attribute to `false` (`"off"`), which is a value Chrome has been known to ignore.

A fix was added for the base TextField component in #1259 to allow a `string` value for `autoComplete`.

## Expected behavior

Chrome should not be displaying autofill suggestions on top of autocomplete results. Because Chrome does not respect the `autoComplete` attribute having a value of `"off"`, as it should, we should allow setting this attribute to other string values, the same way we allow it to be set for the base `TextField`.

## Actual behavior

Setting the `autoComplete` attribute to an arbitrary string value will be ignored and the `autoComplete` attribute will get a value of `off`.

## Steps to reproduce the problem

1. Create an `Autocomplete.TextField` component with an `autoComplete` prop of `"disabled"`
1. Create an `Autocomplete` component with a `textField` prop set to the component created above
1. Render the Autocomplete and observe in Chrome dev tools the `TextField` input has a `autoComplete` attribute of `"off"`, instead of `"disabled"`

[CodeSandbox example](https://codesandbox.io/s/autocompletetextfield-hyobo)

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.19.0
- Browser: Chrome
- Device: MacbookPro
- Operating System: macOS

**Comment by markiiikram** [comment]
Hey @samjrdn, Thanks for creating the issue. We'll be looking into it shortly.

**Comment by BPScott** [comment]
Good spot. Can you take a tophat test steps in https://github.com/Shopify/polaris-react/pull/1839 and see if that PR fixes your issue.
