### ISSUE TITLE
How to stopPropagation in the popover's actionlist while using ResourceList

### ISSUE THREAD

**Issue by yzzhuo** [Shopify/polaris-react#1842]
## Summary
I use  ResouceList, every ResourceItem has URL property, so when Resource Item was clicked, page will be navigated to the target page.
But there is a popover in the resourceList.Item. I want to avoid triggering the event bind to resourceList.Item, just want to trigger the  ActionList's own event.

there's no event parameter available on the ActionListItem's onClick function, so How should I stopPropagation here?

## Reduced test case
CodeSandbox: https://codesandbox.io/s/clever-visvesvaraya-btn19?fontsize=14

**Comment by Duong-GM** [comment]
You can do something like this 
```
<div
        onClick={(e) => {
          e.stopPropagation();
        }}
      >
        <OptionList
          onChange={(a) => {
            setSelected(a);
            togglePopoverActive();
          }}
          options={options}
          selected={[selected]}
          allowMultiple={false}
        />
      </div>
```
This indirect approach will make sure the event can't be propagating any further down.
