### ISSUE TITLE
Library requires Yarn to install, docs wrong.

### ISSUE THREAD

**Issue by SecondeJK** [Shopify/polaris-react#1843]
## Issue summary

According to the docs, you can use Yarn or npm to install the library's dependencies, but you can't.

## Expected behavior

npm or Yarn both complete when running `install`.

## Actual behavior

npm errors because of a Yarn convention using `alias`

<details>ERR! Invalid dependency type requested: alias</details>

## Steps to reproduce the problem

1. `https://github.com/Shopify/polaris-react.git`
2. `npm i`
3. `Yarn install`

It's probably worth noting that since this project was originally using npm and has switched to Yarn, Yarn also issues a warning that the lock file was generated by npm, which is nor recommended. This gives an inconsistency for which tooling we're supposed to be using.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: 
- npm version: 6.4.1
- Operating System: Ubuntu 18.04

**Comment by BPScott** [comment]
Hi @SecondeJK, could you link to the location where we're offering that install documentation?

**Comment by SecondeJK** [comment]
Hi @BPScott, it's almost the first thing you see when you view the repo:
https://github.com/Shopify/polaris-react/blob/master/README.md#installation

**Comment by SecondeJK** [comment]
@BPScott This can probably be closed - I was cloning the repo then running npm on it.

**Comment by BPScott** [comment]
Yep, those instructions are for installing polaris into your own project, not steps for doing setup within this project. We don't force consuming projects to use a particular package manager.
