### ISSUE TITLE
[Filters] Button width changes when popover is active

### ISSUE THREAD

**Issue by tmlayton** [Shopify/polaris-react#1853]
The new [`Filters` component](https://polaris.shopify.com/components/lists-and-tables/filters) has a concept for "shortcut" filters which adds a button/popover in the filter bar to quickly access the filter. The last (right-most) shortcut filter has a visual bug in the button when activating the popover:

![filters bug](https://user-images.githubusercontent.com/344839/61337168-0e42fb00-a7e9-11e9-943d-aa78b2b490e1.gif)

### Reduced test case

https://codesandbox.io/s/epic-cookies-333ch

**Comment by alexieyizhe** [comment]
Hey @tmlayton I'm up for fixing this. Is there a reproducible example? I can't seem to reproduce when it's just a standalone button with a popover.

**Comment by tmlayton** [comment]
👋 Hey @alexieyizhe! That would be awesome, and sorry I quickly opened the issue so there is no information. The issue is with the new `Filters` component: https://polaris.shopify.com/components/lists-and-tables/filters and is reproducible in the latest Chrome, Firefox, and Safari as far as I tested. Will update the description.

**Comment by alexieyizhe** [comment]
Sweet, apologies for late reply but I'll have a look later today

**Comment by alexieyizhe** [comment]
Hey @tmlayton, bit late but I put in a PR^^ to fix this issue. The check that's failing is a Percy snapshot comparison, but I can't seem to approve the change. Check it out when you have the time!
