### ISSUE TITLE
@shopify/polaris-icons in MenuActionDescriptor[]

### ISSUE THREAD

**Issue by GuiguiWeb** [Shopify/polaris-react#1856]
## Issue summary

The @shopify/polaris-icons package doesn't work in MenuActionDescriptor[] and old method (add string) is deprecated.

## Expected behavior
![alt text](https://i.ibb.co/k2jnyjC/Capture-d-e-cran-2019-07-17-a-17-22-34.png)
Display the icon correctly with @shopify/polaris-icons.

## Actual behavior
If i use old method (add string), i have a console warning.
`Deprecation: passing the string "notes" into <Icon source> is deprecated and will be removed in the next major version. Pass in the "NotesMinor" React Component from the @shopify/polaris-icons package instead.`

If i use @shopify/polaris-icons, the icon does not appear.
![alt text](https://i.ibb.co/y0KQNjg/Capture-d-e-cran-2019-07-17-a-17-22-43.png)

## Steps to reproduce the problem

1. Create page component with actionGroups
1. Add a [menu action](https://polaris.shopify.com/components/structure/page/actionGroups/actions) with icon
1. Use @shopify/polaris-icons for the icon

## Reduced test case

https://codesandbox.io/s/issue-jud4g?fontsize=14

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.20.0
- Browser: Google Chrome 75.0
- Device: Macbook Pro
- Operating System: macOS Mojave 10.14

**Comment by BPScott** [comment]
In your code you have `icon: { NotesMinor }`. That's an object containing NotesMinor, when it should be the value of NotesMinor: `icon: NotesMinor`
