### ISSUE TITLE
Webpack example does not compile

### ISSUE THREAD

**Issue by Shakahs** [Shopify/polaris-react#1863]
## Issue summary

Webpack example does not compile. I believe it is a Babel configuration issue, and this plugin needs to be enabled:

https://babeljs.io/docs/en/babel-plugin-proposal-class-properties

## Expected behavior

Webpack example to compile

## Actual behavior

`ERROR in ./src/App.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/shak/dev/libraries/polaris-react/examples/webpack/src/App.js: Support for the experimental syntax 'classProperties' isn't currently enabled (18:9):`

https://github.com/Shopify/polaris-react/blob/8c32fafbfc19b78906d9894321cbee548506f897/examples/webpack/src/App.js#L18

## Steps to reproduce the problem

1. Clone master @ 8c32fafbfc19b78906d9894321cbee548506f897
1. cd examples/webpack
1. yarn && yarn start

## Reduced test case

N/A

## Specifications

```bash
  System:
    OS: Linux 5.1 Fedora 30 (Workstation Edition) 30 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 1.31 GB / 15.35 GB
    Container: Yes
    Shell: 3.0.2 - /usr/bin/fish
  Binaries:
    Node: 10.16.0 - /usr/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0
  npmPackages:
    @shopify/polaris: ^3.10.0 => 3.10.0 
    react: ^16.8.4 => 16.8.4 
    react-dom: ^16.8.4 => 16.8.4 
```

**Comment by jordanskole** [comment]
I think I just ran into this issue as well, with @shopify/polaris ^3.14.0 A few days ago my project was compiling fine. I haven't made any changes to my project since then. 

`yarn build` *i think* is working okay, but I am afraid to test. I am not sure what

**Comment by dleroux** [comment]
Thank you for reporting this @Shakahs, we'll look into this.
