### ISSUE TITLE
We don't currently respect `target` in primaryFooterAction

### ISSUE THREAD

**Issue by 0ptimusrhyme** [Shopify/polaris-react#1867]
## Issue summary

When passing an object to `primaryFooterAction` in a `Card` component, we do not respect the `target` parameter.

As an example, this:

```js
      <Card sectioned primaryFooterAction={{
        content: 'Create Delivery',
        target: 'ADMIN_PATH',
        url: '/orders',
      }}>
```
... will render a button pointing to the app's domain.

## Expected behavior

When setting a `target`, we expect to respect the parameter to dynamically build the target link/button.

## Actual behavior

We instead point the link to the app's domain as the default behaviour, as if we never specified the `target` parameter.

## Steps to reproduce the problem

1. Create a react app with `@shopify/polaris-react` imported
1. Place the above component in your **embedded** app's component structure, make sure to specify `target: "ADMIN_PATH"` as an example.
1. The button will not point to an admin path.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.20.0
- Browser: Chrome 75
- Device: MacBook Pro (15-inch, 2018)
- Operating System: OSX Mojave 10.14.5

CC @daniedleroux as discussed

**Comment by BPScott** [comment]
Gut feel: I think this might be related to our UnstyledLink overwriting any targets that get set on it https://github.com/Shopify/polaris-react/blob/master/src/components/UnstyledLink/UnstyledLink.tsx#L33-L36

**Comment by dleroux** [comment]
Going to close this since we know it isn't an issue just unsupported at the moment.

**Comment by chloerice** [comment]
For future reference:

> @tmlayton: Hey folks, app bridge actions on cards is not supported. To do this app bridge navigation from a card and any other link within the page itself, dispatch a [Redirect action](https://help.shopify.com/en/api/embedded-apps/app-bridge/actions/navigation/redirect).
