### ISSUE TITLE
Add a prop to the `EmptyState` component to expand details text

### ISSUE THREAD

**Issue by TheVedhaGuy** [Shopify/polaris-react#1878]
## Feature request summary
Add a prop to the `EmptyState` that would add the ability for content to not be squished (refer to image below)

## Rationale
I have a use case where I would like to fit more subheadings and content than just the default Heading that we can supply. Currently the `EmptyState` has a right margin in the `Details` section. I would like to propose adding a prop that would essentially set this value to 0 which would allow more content to fit snug against a picture (if there was one).

Current behaviour:
![image](https://user-images.githubusercontent.com/14185832/61816921-55e60a00-ae1b-11e9-9bc2-50bbdc9dfccc.png)

With the prop passed in:
![image](https://user-images.githubusercontent.com/14185832/61816952-66968000-ae1b-11e9-9d1f-490de2e83876.png)

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by tmlayton** [comment]
Hey @TheVedhaGuy, I could see this prop being something like `spacing: "tight" | "loose"` similar to some of the other components.

But, could you post screenshots from the actual design? My two main concerns here are: 

1. we would be making this change because we are trying to add too much content to the empty state
1. with the text being that close, it possibly overlapping the image at various viewport sizes

**Comment by sarahill** [comment]
I agree with @tmlayton 's thoughts on this. A spacing prop could work but I would encourage you to work with a content strategist to see if the content can be adjusted.

We offer content clinics for this as well if you don't have a dedicated content strategist https://vault.shopify.io/pages/1063-Content-clinics

**Comment by TheVedhaGuy** [comment]
Discussed with Tim offline. I'll close this for now
