### ISSUE TITLE
[Frame] Global Ribbon Height does not get set to 0 if globalRibbon is set to null

### ISSUE THREAD

**Issue by jineshshah36** [Shopify/polaris-react#1888]
## Issue summary

--global-ribbon-height does not get set to zero if you start with a ribbon and then remove it by setting the prop to null

## Expected behavior

--global-ribbon-height should be set to zero

## Actual behavior

--global-ribbon-height remains the same because of the following (within Frame.tsx):

```ts
private setGlobalRibbonHeight = () => {
    // globalRibbonContainer no longer exists because the globalRibbon prop is null
    const {globalRibbonContainer} = this;
    // as a result, it never adjusts the height
    if (globalRibbonContainer) {
      this.setState(
        {
          globalRibbonHeight: globalRibbonContainer.offsetHeight,
        },
        this.setGlobalRibbonRootProperty,
      );
    }
  };
```
## Steps to reproduce the problem

1. Add a globalRibbon with a non-zero height
1. remove it by toggling a state value
1. the padding height remains

## Reduced test case

Here is a[CodeSandbox template](https://codesandbox.io/s/great-feistel-zrzmv) of the issue.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.20.0
- Browser: Chrome
- Device: Macbook Pro
- Operating System:  MacOS

**Comment by jineshshah36** [comment]
Any update on this?

**Comment by danrosenthal** [comment]
Hey @jineshshah36, no movement here, but we're happy to accept a pull request if you'd like to fix
