### ISSUE TITLE
badge or helpText not displayed for Page secondaryActions

### ISSUE THREAD

**Issue by jeffblake** [Shopify/polaris-react#1889]
## Issue summary

badge or helpText does not display in a Page's secondaryActions

See sandbox
https://codesandbox.io/embed/nameless-cookies-mn2e8

**Comment by BPScott** [comment]
The actions appear when the actions are collapsed and hidden in the popover, but not when at wide layouts when the actions display underneath the title

**Comment by jeffblake** [comment]
Ah, got it. It would be great to have at least the badge in wide layouts, e.g. to display a count for a resource.

**Comment by BPScott** [comment]
I'm not sure if their omission in wide layouts is a bug or not :) I was just a little confused when I opened your example and because it was the collapsed view by default everything seemed to work.

**Comment by chloerice** [comment]
Thanks for raising this, @jeffblake! This is a problem with the typing of the `secondaryActions` from when `Page` `Header`internals were changed in #1653. `helpText` and `badge` are only supported in the `items` of `actionGroups`. Fixing now!
