### ISSUE TITLE
The Stack is wrapping null children with a Stack.Item, which can create layout problems

### ISSUE THREAD

**Issue by perrupa** [Shopify/polaris-react#1890]
## Issue summary

The `Stack` component wraps children that evaluate to `null` with a `Stack.Item`, creating strange layout problems when some components are conditionally rendered.

## Expected behavior

The `Stack` component wraps children that evaluate to `null` with a `Stack.Item`

## Actual behavior

Components that return null are not rendered, but a `Stack.Item` is rendered around the `null` value they return.

## Examples

[`null` children are not wrapped in an `Item`](https://codesandbox.io/s/infallible-liskov-t0h3u)
[children that evaluate to `null` ARE wrapped in an `Item`](https://codesandbox.io/s/silly-lederberg-kxqsv)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: ^3.16.0

```bash
▶ npx envinfo --system --binaries --browsers --npmPackaes react,react-dom,@shopify/polaris
npx: installed 1 in 1.864s

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 695.54 MB / 16.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.13.0 - ~/.dev/yarn/1.13.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 75.0.3770.142
    Chrome Canary: 77.0.3865.0
    Firefox: 66.0.3
    Safari: 12.1.1
  npmPackages:
    @shopify/polaris: ^3.16.0 => 3.16.0
    react: 16.8.6 => 16.8.6
    react-dom: ^16.8.0 => 16.8.6
```

## Research/Best guesses?

The [`Item` wrapping logic here](https://github.com/Shopify/polaris-react/blob/master/src/components/Stack/Stack.tsx#L55-L58) uses `wrapWithComponent`.

I'm not sure if that's _exactly_ where the bug lies, but my guess would be that [this line here](https://github.com/Shopify/polaris-react/blob/master/src/utilities/components.tsx#L11-L13) is the root of the problem. It checks that the component **is** null, but not whether or not it evaluates to null.

**Comment by yishus** [comment]
👋 I'm running into a similar issue with a [small example](https://codesandbox.io/s/musing-sound-3xtm1?file=/App.js) over here. Is this something that we would not be fixing?

**Comment by chloerice** [comment]
Hi all 👋🏽 We've had to revert the fixes for this issue due to regressions downstream in the admin and will not be shipping further attempts. [Conditionally render the children](https://codesandbox.io/s/dont-render-null-children-kmq1o?file=/App.js) you wrap in a `Stack` from the parent (instead of from the child component) to avoid rendering ghost `Item`s.
