### ISSUE TITLE
Font size too small

### ISSUE THREAD

**Issue by Ifmr24** [Shopify/polaris-react#1891]
## Issue summary

When using polaris and bootstrap, the font size looks too small, how could I fix this?
if I use a <Heading element = "h1"> </Heading> component
it looks like 10px
the buttons and inputs and everything also looks small

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number:  ^3.20.0
- Browser: Chrome and Firefox
- Device: PC
- Operating System: Win 10

https://i.imgur.com/h78RJPf.png

**Comment by BPScott** [comment]
Par of Polaris' [global styling](https://github.com/Shopify/polaris-react/blob/master/src/styles/global.scss#L24) sets the html font-size to 10px (and thus 1rem =10px). I suspect that Bootstrap assumes a base html font-size of 16px.

There's no way around that, either Bootstrap of Polaris's components will be out of proportion, you won't be able to use both design systems on the same page.

We do some work to change our base font size to be 16px (back to the browser default) but that has been paused pending us working out some migration paths. For now you're stuck sorry.

**Comment by kaelig** [comment]
Related:

- https://github.com/Shopify/polaris-react/issues/431
- https://github.com/Shopify/polaris-react/pull/1590
