### ISSUE TITLE
DropZone.FileUpload actionHint glitch

### ISSUE THREAD

**Issue by jeffblake** [Shopify/polaris-react#1892]
## Issue summary

Still very green with React, but I think I found a bug with the `DropZone.FileUpload` component. If you trigger a lot of renders to the `DropZone`, e.g. by changing the state, the default `actionHint` "or drop images to upload" will flash back and forth between the `actionHint` that I've set.

## Expected behavior

The default `actionHint` is never displayed

## Actual behavior

See code sandbox here: https://codesandbox.io/embed/priceless-moser-jwulq

## Steps to reproduce the problem

1. Change color picker value
1. Observe the actionHint

## Reduced test case

https://codesandbox.io/embed/priceless-moser-jwulq

This is forked from the "Drop zone with image file upload" example here: https://polaris.shopify.com/components/actions/drop-zone#navigation
with a color picker added to demonstrate the bug

## Specifications

- Are you using the React components? (Y/N): y
- Polaris version number: 3.2
- Browser: chrome
- Device: mbp
- Operating System: osx

**Comment by BPScott** [comment]
Looks like we've got a bug with how we compute our `getDerivedStateFromProps` in FileUploader. The actionHint value gets forgotten whenever you rerender the component - such as when the state of a parent component changes. One render, shows the user's actionHint, the next shows the default, then goes back to the user's actionHint (and back and forth forever).

It looks particularly bad with the ColorPicker in your demo as moving the color picker triggers onChange events for every pixel you move the color slider leading to a very aggressive flickering.

A more minimal reproduction, available in [this codesandbox](https://codesandbox.io/s/boring-https-84mdf), you can see this effect by clicking the button:

```js
import React, { useState, useCallback } from "react";
import { DropZone } from "@shopify/polaris";

export default function Container() {
  const [counter, setCounter] = useState(0);

  const handleClick = useCallback(() => {
    setCounter(counter + 1);
  }, [counter]);

  return (
    <React.Fragment>
      <p>
        Click this button repeatedly, and watch the actionHint toggle back and
        forth between the user value provided and the default
      </p>
      <button onClick={handleClick}>Count: {counter}</button>
      <DropZone.FileUpload actionHint="changed hint" />
    </React.Fragment>
  );
}

```

**Comment by jeffblake** [comment]
That's it! 

Also, it would be great if we could pass an image source to the `DropZone.FileUpload`. This would provide an easy, visually appealing way to show a currently uploaded image thumbnail, and allow the user to click the button to upload a different one if desired.

**Comment by BPScott** [comment]
> Also, it would be great if we could pass an image source to the DropZone.FileUpload. This would provide an easy, visually appealing way to show a currently uploaded image thumbnail, and allow the user to click the button to upload a different one if desired.

The DropZone example already offers this behavior by the looks of it the https://polaris.shopify.com/components/actions/drop-zone - you can build your own "this file has been uploaded" preview, including potentially uploading multiple files.

I think this one might fall under the "we don't want to be too opinionated, let the user build exactly what they want" banner :)

**Comment by BPScott** [comment]
Looks like when we refactored in FileUpload in make it a functional component in our verison-4.0.0 branch we ended up fixing this!. This sandbox is using 4.0.0-rc and the bug doesn't occur: https://codesandbox.io/s/lucid-frost-uvzzr

**Comment by chloerice** [comment]
> Looks like when we refactored in FileUpload in make it a functional component in our verison-4.0.0 branch we ended up fixing this!. This sandbox is using 4.0.0-rc.0 and the bug doesn't occur: https://codesandbox.io/s/lucid-frost-uvzzr

Sounds like this is good to close 👍
