### ISSUE TITLE
Resource List does not updated on bulk action setState

### ISSUE THREAD

**Issue by Tzelon** [Shopify/polaris-react#1893]
## Issue summary
Trying to use bulk action to update ResourceList.Items properties, but the Items does not render the newest data.
**Happens only in embedded apps**

## Expected behavior
Should render the newest data.

What actually happens?
Only after deselecting the items the newest data rendered.
http://g.recordit.co/0sEEPAV4Mr.gif

## Steps to reproduce the problem
Trying Toggle Show action.

**Happens only in embedded apps**

## Reduced test case
https://codesandbox.io/s/shopify-polaris-react-typescript-playground-z06oe

## Specifications

- Are you using the React components? (**Y**/N):
- Polaris version number: 3.20
- Browser: Chrome
- Operating System: Windows

**Comment by 8eecf0d2** [comment]
The test case appears to be working https://recordit.co/vu88iFccfB

> **Happens only in embedded apps**

Does this mean not in the test case?

**Comment by Tzelon** [comment]
Yes. 
You will need to copy the code to an embedded app.

**Comment by yochail** [comment]
For anyone arriving here, I used the workaround described [here ](https://github.com/Shopify/polaris-react/issues/2357), meaning setting the resourceItem key property as the changed value
