### ISSUE TITLE
[Tooltips] Pointing arrow get partially covered on WYSIWYG editor

### ISSUE THREAD

**Issue by mirualves** [Shopify/polaris-react#1894]
## Issue summary

Some of the tooltips “positioned pointing arrow” get partially covered.

![pointer-covered](https://user-images.githubusercontent.com/5349023/62144750-57eb1580-b2c0-11e9-81a9-127b68a0e2ea.PNG)
![pointer-not-covered](https://user-images.githubusercontent.com/5349023/62144756-59b4d900-b2c0-11e9-92e0-5e205cb285cf.PNG)

## Steps to reproduce the problem

1. Go to the products section
2. Click "Add a product"
3. Hover the WYSIWYG buttons

**Comment by ruairiphackett** [comment]
Are you sure this is in React and not rails @mirualves? I think the tooltip arrow was removed in this PR: https://github.com/Shopify/polaris-react-deprecated/pull/1845

**Comment by mirualves** [comment]
You are right! Thanks for the context :)
