### ISSUE TITLE
[Page] The Primary Button looks squished with long page Title's

### ISSUE THREAD

**Issue by jaxee** [Shopify/polaris-react#1904]
Issue summary

The Page component's primary button's text wraps down instead of the button wrapping under the title. This looks interesting when pages have long title names and a long primary button:

![image](https://user-images.githubusercontent.com/12052693/62225482-82070b00-b386-11e9-9c14-062d41cbce72.png)

## Expected behavior

Button wrapping underneath the title

## Actual behavior

Button text wraps

## Steps to reproduce the problem

1. Add a long title to the page component
2. Add a primary button

## Specifications

- Are you using the React components? (Y/N): Y
- Browser: Chrome
- Device: Desktop

**Comment by markiiikram** [comment]
Hey @jaxee, Thanks for filing this issue. Feel free to assign it to yourself and submit a PR for a fix, but it's been added to the backlog if you don't have time. :)

**Comment by yzzhuo** [comment]
@markiiikram I would like to fix this bug for I have encountered the same problem.

**Comment by yzzhuo** [comment]
but I wonder if I only make the `Button text` no wraps, the width of the button cannot be controlled, so need I set a max-width of the button?

**Comment by markiiikram** [comment]
Hey @yzzhuo, I believe the fix would be to keep the button as is, but have it wrap under the title when the title and/or viewport reaches a certain ratio/size. @jaxee - can you post a snippet of the code you're using? I'm thinking it's the [Page component](https://polaris.shopify.com/components/structure/page) in a non-embedded app, but I'd like to confirm.
