### ISSUE TITLE
onKeyPress not exposed for TextField

### ISSUE THREAD

**Issue by sijad** [Shopify/polaris-react#1916]
## Issue summary

I'm trying to let user select/add current value of `Autocomplete.TextField` to a list by pressing `Enter` button, but `onKeyPress` is not assignable to `TextField` therefore it's not possible...

## Expected behavior

it should be possible to set `onKeyPress` to `TextField` via props.

## Actual behavior

there's no `onKeyPress` props for `TextField`

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.21.0
- Browser: Firefox
- Operating System: Linux

```bash
  System:
    OS: Linux 5.2 Arch Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 2.00 GB / 15.43 GB
    Container: Yes
    Shell: 3.0.2 - /usr/bin/fish
  Binaries:
    Node: 10.16.0 - ~/.config/nvm/10.16.0/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.10.1 - ~/.config/nvm/10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Firefox: 70.0a1
```

**Comment by chloerice** [comment]
Hey @sijad, the way to do this is by using the `onSelect` prop on the [`Autocomplete`](https://polaris.shopify.com/components/forms/autocomplete) component, not on the `TextField`. Pressing the enter/return or space key on a selected option invokes the callback set on `Autocomplete.onSelect`.

**Comment by sijad** [comment]
In my case `onSelect` does not fiered when user Enter in text field, pressing enter submits the form. User is typing something and wants to add it to a list by pressing Enter but instead form submits. Another usecase for having `onKeyPress` is to add tags by typing `,` in text field similar to shopify store panel in add new Order form.

**Comment by dan-gamble** [comment]
Hey @sijad,

One way I've got around the `onKeyPress`, `onKeyDown`, `onKeyUp` issue is wrapping the `<TextField />` in a `<div>` like this:

```jsx
function handleChoiceKeyDown (e, body) {
  const enterIsPressed = e.keyCode === 13

  if (enterIsPressed) {
    e.preventDefault()

    handleAddChoice(body)
  }
}

<div
  onKeyDown={e => 
    handleChoiceKeyDown(e, {
      data: {
        title: choice,
        order: choices.length,
        option_type: optionType,
      },
    })
  }
>
  <TextField
    label="Choice"
    value={choice}
    onChange={handleChoiceChange}
    clearButton
    onClearButtonClick={clearChoice}
    connectedRight={
      <Button
        onClick={() =>
          handleAddChoice({
            data: {
              title: choice,
              order: choices.length,
              option_type: optionType,
            },
          })
        }
      >
        Add Choice
      </Button>
    }
  />
</div>
```

It's not ideal but works 👍
