### ISSUE TITLE
[Tabs.Item][UnstyledLink] Tries to `focus()` component

### ISSUE THREAD

**Issue by AndrewMusgrave** [Shopify/polaris-react#1935]
## Issue summary

`Tabs.Item` [tries to focus](https://github.com/Shopify/polaris-react/blob/5c2afee8f7f09450daeb50b550fdbfaf600b21a3/src/components/Tabs/components/Item/Item.tsx#L24) either a `button` or `UnstyledLink`. However `UnstyedLink` is a functional component without an imperative handle.

## Possible Solution

Use `useImperativeHandleHook` and add a focus method. The [focusing logic](https://github.com/Shopify/polaris-react/blob/5c2afee8f7f09450daeb50b550fdbfaf600b21a3/src/components/Tabs/components/Item/Item.tsx#L23) may need to change slightly.

**Comment by tanhengyeow** [comment]
I would like to work on this issue since it hasn't been worked on for some time 😄

**Comment by AndrewMusgrave** [comment]
That would be awesome @tanhengyeow , just assigned you to the issue 😄
