### ISSUE TITLE
[ActionMenu] Extract MenuAction out of ActionMenu

### ISSUE THREAD

**Issue by Tetsuro** [Shopify/polaris-react#1942]
### Summary

There is a style of button/action called [MenuAction](https://github.com/Shopify/polaris-react/blob/master/src/components/ActionMenu/components/MenuAction/MenuAction.tsx) used within the ActionMenu component that could benefit from being extracted into its own component. 

In the Online Store UI project, we ended up extracting it into its component (https://github.com/Shopify/online-store-ui/pull/526) and added some enhancements to make the active state a bit more noticeable. If the Polaris team decides to move forward with this proposal, it _should_ be easy to copy over to Polaris!

### Screenshots

state | image
-------|------
normal | ![image](https://user-images.githubusercontent.com/351842/62725000-3ede1500-b9e2-11e9-98db-63be6645aab4.png)
hover | ![image](https://user-images.githubusercontent.com/351842/62725033-52897b80-b9e2-11e9-8644-b1ed00e457ac.png)
active | ![image](https://user-images.githubusercontent.com/351842/62724865-eeff4e00-b9e1-11e9-926b-882eab818b53.png)
active (in OS-UI) | ![image](https://user-images.githubusercontent.com/351842/62725386-0b4fba80-b9e3-11e9-90c9-9025188f8c0e.png)

**Comment by yourpalsonja** [comment]
Moving into backlog for now, while we figure out the best way forward for this. CC @AndrewMusgrave  @dleroux @beefchimi we should revisit this!
