### ISSUE TITLE
Remove public Sass API

### ISSUE THREAD

**Issue by BPScott** [Shopify/polaris-react#1982]
The Sass API came from a world where it was extracted out from the shopify app without much thought around "how will this work as a library across multiple apps". It is hard to change, questionably documented and causes complexity for build systems like sewing-kit.

Let's kill it.

Consuming apps should either consume token values from polaris-tokens, or copy our existing mixins into their app to continue working.

See Vault: https://vault.shopify.io/projects/8877 for project info

**Comment by tmlayton** [comment]
We are going to hold off on this for now. We still want to to do this work, but we need to spend time working out good upgrade paths and have other higher priorities right now.

**Comment by BPScott** [comment]
Still a plan

**Comment by BPScott** [comment]
Still a thing that should be addressed
