### ISSUE TITLE
[ContextualSaveBar] Height-limited layout causes action overflow

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react#1983]
## Issue summary

There's a very limited room for content in `ContextualSaveBar` on small screens due to its set height of 56px (matching the height of the `TopBar` that it overlays). 

### [Reduced test case](https://6umrn.csb.app/)

If action content is more than one word, it can end up overflowing. For short word use cases #1967 fixes this issue, but it's not hard to break the layout due to the fact that it's non-wrapping. As the button content grows it quickly completely overlaps the `message` content completely.

<img width="375" alt="Screen Shot 2019-08-16 at 12 19 20 PM" src="https://user-images.githubusercontent.com/18447883/63185887-15983700-c029-11e9-9153-61201ac39794.png">

We mitigate this in the `Page` header by rolling up all actions but the primary into an ellipsis popover. But rolling up the discard and save actions would not improve the UX, it would another step for merchants to get to the actions we're aiming to surface.

#### Icon only actions

<img width="360" alt="Screen Shot 2019-08-16 at 1 52 25 PM" src="https://user-images.githubusercontent.com/18447883/63193171-c4913e80-c03a-11e9-8241-d275c91919b5.png">

#### Stack message and action container and allow actions to wrap

<img width="374" alt="Screen Shot 2019-08-16 at 3 30 07 PM" src="https://user-images.githubusercontent.com/18447883/63193188-cc50e300-c03a-11e9-8dcf-05f0d4d588b3.png">

**Comment by yourpalsonja** [comment]
@ry5n pinging you to take a look at the design solutions proposed by Chloe here!

**Comment by ry5n** [comment]
The most flexible solution is to allow the buttons to wrap. That’s my recommendation for now.
