### ISSUE TITLE
[Modal] onLoadIframe cross-origin error when loading embedded app iFrame

### ISSUE THREAD

**Issue by PabloVallejo** [Shopify/polaris-react#1985]
## Issue summary

When loading an iFrame (Embedded app) into the Polaris modal, it triggers a cross-origin error.

![image](https://user-images.githubusercontent.com/1751074/63224852-1bf8f100-c198-11e9-8108-dccd950b6c88.png)

Section of code erroring: https://github.com/Shopify/polaris-react/blob/master/src/components/Modal/Modal.tsx#L339

## Expected behavior

Cross-origin error is not triggered and the callback `onIframeLoad` is fully executed.

## Actual behavior

Code errors and the `iFrameLoad` callback is not triggered, preventing initialization of the modal based on App config.

<details>
Uncaught DOMException: Blocked a frame with origin "https://oribama.myshopify.com" from accessing a cross-origin frame.
    at handleIFrameLoad (https://cdn.shopifycloud.com/web/assets/latest/vendors~Admin-a118ebfef6acd3deebea7bd10437b673d2301e9e1c45060f647428e5c4ea8ecb.js:1:64659)
    at Object.<anonymous> (https://cdn.shopifycloud.com/web/assets/latest/vendors~error~main~redirectLoop-855cc25b25078356e3c4decda25e9fba16232eec3bfc9c80e2d1b484db77b1bf.js:14:1192)
</details>

## Steps to reproduce the problem

1. Install an embedded app, (Buy button or Google Shopping).
2. Go to the products details page in React.
3. From the actions, open the app link that shows the modal.
4. Open the dev tools console and see the cross-origin error.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.16.0
- Browser: Chrome: 76.0.3809.100

**Comment by danrosenthal** [comment]
Here's a link to the thread discussing this problem: https://shopify.slack.com/archives/C8H54T86Q/p1566219183271300, and here is a 1:1 conversation I had with @gf3 on how this could be fixed:

```
Gianni Chiappetta:  hey dan, i think the issue we’re discussing is a legitimate polaris bug that might be worth addressing

the easiest fix is probably to wrap the code that accesses iframe.contentWindow.document.body.scrollHeight in a try/catch

Dan Rosenthal:  My only concerns are that the bug doesn't have significant enough impact to put people on fixing it at the moment, since we are going to be removing all the app bridge delegation in a forthcoming major release.
This is likely to be released in the next couple of months, and will remove the problem entirely from the Polaris end

Gianni Chiappetta:  so as far as i can tell this is unrelated to that, and will still exist after that removal

Dan Rosenthal:  interesting, why is that the case?
pardon my naivety on how this works

Gianni Chiappetta:  well it seems to me that this issue exists because they are loading a standard polaris iframe modal (no app bridge at all) BUT the modal’s origin is different from theirs (looks like polaris assumes you are opening an iframe modal on the same origin). then polaris tries to reach inside the modal iframe to get the height, but it can’t due to the origin mismatch. so instead there is an error and the height is never set

Dan Rosenthal:  how would a try catch fix this?

Gianni Chiappetta:  polaris could try to grab the height as it does now, but if there’s an error it can set a default height instead and carry on
```

**Comment by dleroux** [comment]
This is tricky. We currently have `rc4` shipped but not ready to have an official `v4` release. We can make this `rc5` but I would like to be certain of what an acceptable default height should be. Not too familiar with how many of these apps might open in a modal like this so it's difficult to say. @gf3 any thoughts?

**Comment by gf3** [comment]
@dleroux from what i understand, _currently_ there are only a couple apps using this feature so the blast radius should be relatively small. we're [currently using this as a default modal iframe height](https://github.com/Shopify/web/blob/1617c9b80602a410347f6512a5ebbb068791bd1c/app/sections/Apps/EmbeddedApp/components/Modal/Modal.tsx#L10) in web

**Comment by gf3** [comment]
also just noticed this in the same file: https://github.com/Shopify/web/blob/1617c9b80602a410347f6512a5ebbb068791bd1c/app/sections/Apps/EmbeddedApp/components/Modal/Modal.tsx#L51-L55

**Comment by PabloVallejo** [comment]
Thanks for taking a look at this @gf3, @danrosenthal and @dleroux! 

The proposed solution makes sense to me as when not setting the height of the modal in https://github.com/Shopify/polaris-react/blob/master/src/components/Modal/Modal.tsx#L339, the `onIframeLoad` callback is triggered correctly hence modal initialization works correctly.
