### ISSUE TITLE
[TextField] Max and Min have the wrong type

### ISSUE THREAD

**Issue by cbolton97** [Shopify/polaris-react#1988]
## Issue summary

`min` and `max` should allow for `number|string`, not just `number`.

This prevents using `min` and `max` for a native date input, [which is allowed](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#max).

**Comment by BPScott** [comment]
React types `JSX.IntrinsicElements['input']['max']` (and min) as  [number|string](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3cd6ad7fa49791641e198f0b28592245b14cd825/types/react/index.d.ts#L1956-L1958). I don't think we should try and be too clever here, and keep it as simple as possible by allowing `number|string`.

**Comment by tmlayton** [comment]
I would reframe this issue as a bug fix instead of a feature request. And to build off of @BPScott’s point, I think we want to type as `number|string`, simply pass the string value through to the input, and let the native element handle it accordingly.
