### ISSUE TITLE
[Color system] Deprecate Sass API

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#2017]
#### Border width
- border-width (⚠️ needs token values before deprecation)

#### Borders
- border (⚠️ alias safe to deprecate once border width has tokens)

#### Colors
- color (👍 safe to deprecate, use tokens directly, but maybe should wait until after color system)
- color-multiply (👍 safe to deprecate, copy to project)
- ms-high-contrast-color (⚠️ has foundational color data)

#### Duration
- duration (👍 safe to deprecate, use tokens directly)

#### Easing
- easing (⚠️ needs token values before deprecation)

#### Filters
- filter (👍 safe to deprecate, use tokens directly, weird because tokens use same name as colors)

#### Layout
- layout-width (⚠️ has foundational data, needs token values before deprecation)
- top-bar-height (⚠️ could be considered foundational data)
- mobile-nav-width (⚠️ does math on `dismiss-icon-size`, which could be considered foundational data)
-nav-min-window-corrected (⚠️ references an existing layout width, which would need to be made a token before deprecation)

#### Shadows
- shadow (⚠️ needs token values before deprecation)

#### Spacing
- spacing (👍 safe to deprecate, use tokens directly)

#### Typography
- font-family (👍 safe to deprecate, use tokens directly)
- line-height (⚠️ has foundational data, needs discussion if it should be a token)
- font-size (⚠️ has foundational data, needs discussion if it should be a token)

#### Utilities
- rem (👍 safe to deprecate, no token concerns)
- px (👍 safe to deprecate, no token concerns)
- em (👍 safe to deprecate, no token concerns)
- available-names (⚠️ each `foundation` function depends on this)
- map-extend (👍 only `color` depends on this, safe to deprecate)

#### Z-index
- z-index (⚠️ has foundational data, needs discussion if it should be a token)

### Shared
These are all safe to deprecate (👍) without token concerns excluding `state` and `thumbnail-size`, which need a bit of discussion, and should probably be in `foundation` instead of `shared`. Should also discuss if `control-height` and `control-slim-height` should be considered foundational.

#### Accessibility
- Visually-hidden

#### Breakpoints
- breakpoint
- page-content-breakpoint-before
- page-content-breakpoint-after
- breakpoint-after
- breakpoint-before
- frame-with-nav-when-not-max-width
- page-when-not-max-width
- page-content-when-layout-stacked
- page-content-when-layout-not-stacked
- page-content-when-partially-condensed
- page-content-when-not-partially-condensed
- page-content-when-fully-condensed
- page-content-when-not-fully-condensed
- frame-when-nav-displayed
- frame-when-nav-hidden

#### Button
- high-contrast-button-outline
- button-base
- base-button-disabled
- button-filled
- button-filled-disabled
- button-outline
- button-outline-disabled
- button-full-width
- plain-button-background
- plain-button-backdrop
- unstyled-button

#### Controls
- control-height (⚠️ could be considered foundational data)
- control-slim-height (⚠️ could be considered foundational data)
- control-vertical-padding
- control-icon-transition
- control-backdrop

#### Forms
- unstyled-input
- range-track-selectors
- range-thumb-selectors

#### Icons
- icon-size (⚠️ could be considered foundational data)
- recolor-icon
- color-icon (⚠️ dependencies on `color` and `filter`, ask Dave Newton)

#### Interaction State
- state (⚠️ has external data, replaced by color system, should be considered foundational)

#### Layout
- layout-flex-fix
- safe-area-for
- after-topbar-sheet

#### Links
- unstyled-link

#### Lists
- unstyled-list

#### Page
- page-padding-not-fully-condensed
- page-padding-not-partially-condensed
- page-layout
- page-content-layout
- page-title-layout
- page-header-layout
- page-header-has-navigation
- page-header-without-navigation
- page-header-has-secondary-actions
- page-actions-layout

#### Printing
- when-printing
- when-not-printing
- hidden-when-printing

#### Skeleton
- thumbnail-size (⚠️ could be considered foundational data)
- skeleton-shimmer
- skeleton-content
- skeleton-page-secondary-actions-layout
- skeleton-page-header-has-secondary-actions
- skeleton-page-header-layout

#### Typography
- when-typography-not-condensed (⚠️ foundational data)
- when-typography-condensed (⚠️ foundational data)
- text-style-caption
- text-style-heading
- text-style-subheading
- text-style-input
- text-style-body
- text-style-button
- text-style-button-large
- text-style-display-x-large
- text-style-display-large
- text-style-display-medium
- text-style-display-small
- text-emphasis-placeholder
- text-emphasis-subdued
- text-emphasis-strong
- text-emphasis-normal
- text-breakword
- truncate
- print-hidden

**Comment by danrosenthal** [comment]
Closed in favor of https://github.com/Shopify/polaris-react/issues/1982
