### ISSUE TITLE
[Color system] Dark mode coordination

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#2042]
At this point we should know for sure the master brand color system will work, and work with dark mode, and we should coordinate with Web (Donnie’s team) App Bridge on how shops can toggle and save their light/dark mode preference and communicate it via App Bridge

**Comment by tmlayton** [comment]
We met with the relevant teams, will open new issues when clear what work needs to be done.

**Comment by DazWorrall** [comment]
@tmlayton where can those of us interested in following along look for updates on this?

**Comment by danrosenthal** [comment]
@DazWorrall #polaris-color-system on slack is your best bet!

**Comment by tmlayton** [comment]
@DazWorrall for a project board view: https://github.com/orgs/Shopify/projects/485?card_filter_query=%5Bcolor+system%5D and project overview and updates: https://vault.shopify.io/projects/7859.
