### ISSUE TITLE
Adding rel attribute to the link, button, banner components

### ISSUE THREAD

**Issue by darol100** [Shopify/polaris-react#2084]
## Feature request summary

As right now, there is no way to use the `rel"` attribute to the link, button, banner components. It will be nice to be able to pass the rel attribute like this: 

```
<Link 
   url="https://help.shopify.com/manual" 
   external={true} 
   rel="noopener noreferrer"
>fulfilling orders</Link>
```

```
<Banner
  title="USPS has updated their rates"
  action={{
     content: 'Learn more', 
     external: true, 
     url:"https://help.shopify.com/manual",   
      rel: "noopener noreferrer"
 }}
  status="info"
  onDismiss={() => {}}
>
  <p>Make sure you know how these changes affect your store.</p>
</Banner>
```
## Rationale
There are some security benefits that we get with the rel` attribute.  Here are some of the reasons from a Google post:

> - rel="noopener" prevents the new page from being able to access the window.opener property and ensures it runs in a separate process.
> - rel="noreferrer" attribute has the same effect, but also prevents the Referer header from being sent to the new page. See Link type "noreferrer".
> 

Source: [Links to cross-origin destinations are unsafe
](https://developers.google.com/web/tools/lighthouse/audits/noopener)

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by darol100** [comment]
It looks like this is not need it. If you pass the external={true} this will automatically add the `rel="noopener noreferrer"`. Closing this PR.

**Comment by chriscodeweb** [comment]
The external property seems to be depreciated and does not set the rel="noopener noreferrer" anymore to a link.

**Comment by shftlvch** [comment]
I have the same behaviour as @chriscodeweb, plus `react-dom.development.js:86 Warning: Received 'true' for a non-boolean attribute 'external'. ` from react-dom.

**Comment by Filipp95** [comment]
So what about now? 
External is deprecated as was written higher. Is it possible it would be added?
