### ISSUE TITLE
"Download Icon" Request

### ISSUE THREAD

**Issue by amyshea** [Shopify/polaris-react#2142]
## Component name 
Download icon

Short intro description (try and keep to two sentences): A number of partners, most recently Walmart, have requested a download icon for use in their apps. The closest icon we have is 'import' which is not descriptive of the action. The use case that came up recently is, Walmart is looking to allow merchants to download an excel reference spreadsheet of Tax Codes as they fill in Tax Codes for unique products.

**Comment by BPScott** [comment]
Hi @amyshea, New icon requests go into the polaris-icons repo, could you [open an issue in there](https://github.com/Shopify/polaris-icons/issues/new/choose) using the "Suggest an icon" template.

We've spotted a [need for a download icon before](https://github.com/Shopify/polaris-icons/pull/362#discussion_r294505160) but there's still some open questions on what that Icon looks like, if you could reference that comment in your issue that'd be great, thanks.
