### ISSUE TITLE
Carousel component

### ISSUE THREAD

**Issue by sajan1231** [Shopify/polaris-react#2146]
There is no Carousels component in the library. so i think it would be nice to add a Carousel component.
Thank you.

**Comment by kaelig** [comment]
Hi @sajan1231, could you please provide more information on the use cases you have as well as the type of functionality you'd be expecting from such a component?

**Comment by sajan1231** [comment]
Hi @kaelig, this component can we used as the hero section of a store in which we can show the popular product deals, offers, etc. and it automatically shows the images, as well as someone, can click on the next and back buttons to scroll through these. I hope it makes sense.
Thank you.

**Comment by tmlayton** [comment]
Hi @sajan1231, just curious can you provide a link to your store that is using Polaris React? I’d love to see it!

I have been thinking about this problem, but not as a carousel rather as panels. It would be the inverse of our tabs components, in that you provide each panel and a prop for the current index. Changing the index would animate to the corresponding panel. I was thinking the component would require you to bring your own controls so it is unopinionated about the interface, although opinionated about the animation. That way it is a behavior component, similar to Collapsible.

**Comment by sajan1231** [comment]
Hi sir actually i don't have a store i am new to programming and like this
polaris library. But i found that it doesn't have any carousal component. i
was creating one project then i used bulma carousal and some other css
libraries, so i thought if i will get an carousal component then i just
have to use polaris nothing else then that. i found most of the components
accept carousal so i asked.
Thank you.
