### ISSUE TITLE
Document Sticky

### ISSUE THREAD

**Issue by tmlayton** [Shopify/polaris-react#2149]
## Feature request summary

`Sticky` is already a top level component, just not documented. I think others would find it quite helpful as a "behavior" component.

## Rationale

As we move to smaller, more composable components allowing for creative assembly, `Sticky` is a non-trivial problem which we’ve solved well and should document its use.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by tmlayton** [comment]
Still a thing

**Comment by iblecher** [comment]
still a thing :)
