### ISSUE TITLE
Port the existing TagTextField component from web to Polaris

### ISSUE THREAD

**Issue by tleunen** [Shopify/polaris-react#2154]
## Component name

We currently have a TagTextField component in web that are used in a few other internal projects. Because of this, it would make sense to move/port the component into Polaris itself to make it easier for anyone to use it.

Pretty sure this could benefit our partners as well for their apps.

**Comment by dleroux** [comment]
Thanks for bringing this up @tleunen. Since this is a feature request I will close this (feel free to upvote) but it's not forgotten. I'm actually going to be taking up the Autocomplete work and tags have come up. So I will definitely keep this in mind.
