### ISSUE TITLE
Button, plain, monochrome, disclosure & loading is borkened

### ISSUE THREAD

**Issue by arthurgouveia** [Shopify/polaris-react#2190]
## Issue summary

The following code produces a filled loading SVG:

```jsx
<div style={{color: '#bf0711'}}>
  <Button plain monochrome loading disclosure>
    Try again
  </Button>
</div>
```

## Expected behavior

Not having a square.

## Actual behavior

<img width="129" alt="Screen Shot 2019-09-24 at 3 19 04 PM" src="https://user-images.githubusercontent.com/642737/65543187-ae4e8c00-dede-11e9-8e7a-2e4b5b8b38d6.png">

## Steps to reproduce the problem

Use the code state above.

## Reduced test case

https://codesandbox.io/s/97nmz?module=App.js

**Comment by tmlayton** [comment]
Looks like once `loading` to this combination of props, it visually breaks:

![button](https://user-images.githubusercontent.com/344839/65625663-1e155300-df81-11e9-8af8-8d3dd367d528.gif)

**Comment by arthurgouveia** [comment]
changed the title ~Button, plain, monochrome, disclosure & loading is borken~ Button, plain, monochrome, disclosure & loading is broken

but `borken` was so much nicer 😭

**Comment by tmlayton** [comment]
I prefer borken as well 😄

**Comment by tmlayton** [comment]
Still an issue
