### ISSUE TITLE
[Color system] Assess usability of color role naming conventions with product designers and developers

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#2198]
Work with @senecabrandi and @hayhughes to assess the usability of the color system from a design perspective. Recruit designers from the Polaris team to assess the color system naming convention, apply the colors in a design, and provide feedback on the naming conventions used.

**Comment by dleroux** [comment]
cc @sarahill

**Comment by danrosenthal** [comment]
@dleroux did you mean to close this?

**Comment by dleroux** [comment]
Nope I did not.

**Comment by danrosenthal** [comment]
https://docs.google.com/document/d/1-OLLS90htVqK7bIpWYp0XxMW-f9BbSlJM3lGe98ccqo/edit
