### ISSUE TITLE
[Color system] Review generated color variants and application of color with Creative Direction team and iterate until aligned

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#2199]
Review the generated color variants after completion of #2034 and the application of color in a subset of components after completion of #2197 with @jessebc and other pertinent members of the Creative Direction team. Iterate on the generated variants in order to achieve a visually appealing color palette, and align on color values and names.

**Comment by alex-page** [comment]
Can I be involved in this as well.

**Comment by danrosenthal** [comment]
This issue can now be closed, following a sprint with creative directions, and ongoing collaboration on the color system output.
