### ISSUE TITLE
Embedded Modal font sizing

### ISSUE THREAD

**Issue by 416serg** [Shopify/polaris-react#2205]
## Issue summary

We've implemented [`EmbeddedModal`](https://github.com/Shopify/google-shopping/blob/master/app/ui/packages/%40shopify/polaris-next/EmbeddedModal/EmbeddedModal.tsx) which renders font sizes based on it's width, rather than the width of the full screen

## Expected behavior

Font size should be sized based on window width, rather than modal width

<img width="1501" alt="Screen Shot 2019-09-27 at 10 53 26 AM" src="https://user-images.githubusercontent.com/3760543/65780626-1f2cb880-e118-11e9-82f5-2ea6e828c4f6.png">

## Actual behavior

Font size is getting styling for smaller screen sizes

<img width="1502" alt="Screen Shot 2019-09-27 at 10 52 58 AM" src="https://user-images.githubusercontent.com/3760543/65780632-218f1280-e118-11e9-935b-ad7b2909600d.png">

## Steps to reproduce the problem

1. Go to https://416serg.myshopify.com/admin/apps/new-google-shopping-dev/settings
2. In the Product Feed settings section, click the "Change" button
3. See modal with font size issues

## Specifications

```bash
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 89.45 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.10.1 - ~/.dev/yarn/1.10.1/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0
    Safari: 13.0.1
  npmPackages:
    @shopify/polaris: 3.15.0 => 3.15.0 
    react: 16.8.3 => 16.8.3 
    react-dom: 16.8.3 => 16.8.3 

```

**Comment by markiiikram** [comment]
Thanks @416serg!
