### ISSUE TITLE
Remove 20px padding on Dual thumb range slider component example

### ISSUE THREAD

**Issue by HYPD** [Shopify/polaris-react#2221]
## Issue summary
Dual thumb range slider has an additional 20px padding at the top of the card. 

```
return (
    <Card sectioned>
      <div style={{marginTop: '20px'}} onKeyDown={handleEnterKeyPress}>
```

None of our other cards follow this pattern, and it might be confusing for anyone using this pattern. I think we should remove the 20px padding. cc @sarahill 

https://polaris.shopify.com/components/forms/range-slider

## Expected behavior

<img width="839" alt="CleanShot 2019-10-02 at 14 51 49@2x" src="https://user-images.githubusercontent.com/970304/66072992-2c84e100-e524-11e9-8cd2-ddb7e0d18148.png">

## Actual behavior

<img width="902" alt="CleanShot 2019-10-02 at 14 50 49@2x" src="https://user-images.githubusercontent.com/970304/66072983-242ca600-e524-11e9-9c53-b5082588bc43.png">

**Comment by chloerice** [comment]
Hey @HYPD! My guess is that the top margin is there so there's some extra space above the tooltip that renders when the sliders are focused or dragged. The tooltips don't overflow the card though, so I don't see any reason not to remove it. I can open a quick PR.

Looks like there's some mention of the dual range slider on the mobile tabs of the RangeSlider docs that shouldn't be there. @see-mack is there a dual range slider for the native Polaris components, or should I fix that example to only show for Web?

<img width="882" alt="Screen Shot 2019-10-02 at 3 59 03 PM" src="https://user-images.githubusercontent.com/18447883/66077380-d61ca000-e52d-11e9-9854-8b8a55434792.png">

**Comment by HYPD** [comment]
@chloerice Ahh that makes sense, but could we add a title to the card so the area doesn't look so bare?

**Comment by chloerice** [comment]
> @chloerice Ahh that makes sense, but could we add a title to the card so the area doesn't look so bare and it affords that tooltip some extra space?

Totally 💯

**Comment by see-mack** [comment]
@chloerice We don't have a mobile component built for Polaris that I know of but sliders are a common component for mobile. I think it's worth keeping it in the Polaris docs at least so that designers know it's available. It will be easy to build once someone has need of it.
