### ISSUE TITLE
[Autocomplete] API explorations

### ISSUE THREAD

**Issue by dleroux** [Shopify/polaris-react#2247]
In the first part of our exploration, it was [decided we would use a compound component to build the new Autocomplete](https://github.com/Shopify/polaris-react/pull/2241). 

This issue is to explore the possible API.

**Comment by dleroux** [comment]
Looking at the current API, I believe the following will satisfy the same requirements. I will further explore this while outlining the interactions and accessibility requirements. This is by no means final. Feedback is welcomed.

```
<Autocomplete  activator={} loading>
     <Loading /> {/* loading ? Spinner overlay : null */}
     <EmptyState /> {/* Autocomplete mode && no options ? Empty state : null */}
     <ListBox
          onScrolledToBottom={() => void} // cb for when list scrolled to bottom. Most likely `loadingMoreOptions` to true
          loadingMoreOptions
        >
          <Option action={}></Option>
          <Section title={}>
            <Option selected disabled value={}></Option>
            <Option value={}></Option>
          </Section>
          <Option loading></Option> {/* loadingMoreOptions ? Spinner ListBox Options : null */}
     </ListBox>
</Autocomplete>
```

**Comment by danrosenthal** [comment]
Can `Action` and `LoadingOption` just be `Button` components?

**Comment by dleroux** [comment]
I'll check with @Devon, But I'm thinking there will need to render a list item with a specific role for the Listbox. At first I had them as just `Options` with props but then it makes the `Option` unclear plus I want to make sure `value` is required.

Without looping though children and cloning, whatever we put inside the `<ListBox/>` will need  to render the required mark-up. Buttons would need to be passed as props, which is also a possibility.

**Comment by dleroux** [comment]
The following outlines the intention of each of the props.

While building the prototype I'm seeing a significant amount of values that need to be shared on context, causing rerenders that could affect performance. 

The most notable difference with the current Autocomplete API  is that we decided to provide the ComboBox with a Listbox as a child as opposed to an `Option` prop. As this API gets implemented there are chances that the benefits of composing will be outweighed by performance. In which case we would revert back to the prop approach. In which case the API might change slightly.

### ComboxBox:
```
/** Allow more than one option to be selected */
allowMultiple: boolean;

/** The text field component that activates the Listbox */
activator={<Textfield />} 

/** Provides the text field with the inline hint (based on first option provided) */
inline: boolean;

/** identifies the matching text in the option */
highlightMatches: boolean;

/** Callback when the end of the list is reached */
onScrollToBottom={() => void}

/** Callback when an option is selected */
onOptionSelected={(value: string) => void}>
```

**Inline** and **highlightMatches**  might have a negative impact on performance. 
- For `inline` the intention is to provide the value of the first option. To optimize, if needed, we could change this to explicitly provide the value of the inline hint
- For `highlightMatches` we may remove the prop and recommend the data being provided be formatted to highlight the matches.

**Comment by jineshshah36** [comment]
I was going to comment this in a separate issue about the current autocomplete component, but since you guys are rewriting it, I figured I would comment here.

It would be great if, under the hood, the autocomplete component used a datalist HTML element. You can connect a datalist to an input so that the options in the datalist appear as suggestions for the input on mobile keyboards.

Example here: (https://blog.teamtreehouse.com/creating-autocomplete-dropdowns-datalist-element)

**Comment by dleroux** [comment]
Thanks @jineshshah36. The project is on hold at the moment. When it picks up again I'll take a look to see if this is a viable solution for mobile. It doesn't allow for the flexibility we need on desktop but for mobile, it might just be. Thanks!

**Comment by jineshshah36** [comment]
I appreciate the response, that makes sense. I agree it's not very useful on non-mobile devices

**Comment by dleroux** [comment]
Closing since this project as been on hold but the API is pretty solid.
