### ISSUE TITLE
Month and Day Titles not displaying when using Datepicker Component

### ISSUE THREAD

**Issue by zarubiak** [Shopify/polaris-react#2271]
I'm using the Datepicker component and it will display my calendar with only the year in the title, as displayed below:
<img width="266" alt="Screen Shot 2019-10-09 at 5 38 47 PM" src="https://user-images.githubusercontent.com/36527059/66530239-c405a900-eabb-11e9-8468-2ac663f711f1.png">
I am looking for functionality similar to what is displayed in the Polaris Datepicker documentation and on a **Shopify Admin Page --> Orders --> More Filters --> Date**, as displayed below:
<img width="368" alt="Screen Shot 2019-10-09 at 5 39 21 PM" src="https://user-images.githubusercontent.com/36527059/66530322-22328c00-eabc-11e9-9412-6d65005312c4.png">
I'm hoping to be able to display month beside year and a separate row underneath the title which displays the days of the week. Thanks in advance for any help!

**Comment by BPScott** [comment]
We display [the month by default](https://www.chromaui.com/component?appId=5d559397bae39100201eedc1&name=All%20Components%7CDate%20picker&buildNumber=1342) but it is pulled in as a translation string.

Are you setting a i18n option on your `<AppProvider>` per the README: https://github.com/shopify/polaris-react#usage
