### ISSUE TITLE
Building a library based on Polaris 4.x

### ISSUE THREAD

**Issue by fourstacks** [Shopify/polaris-react#2272]
## Issue summary

At my company we’ve built a set of custom components that wrap Polaris components so that we don’t have to duplicate certain layouts and functionality across apps.  These packages work fine on Polaris 3.x but break using Polaris 4.x

## Expected behavior

We’ve built these components into standalone libraries that we pull in using NPM. 

The first library is a set of common components including a wrapper around  `Provider` (we’re embedding our apps using React App Bridge) and `AppProvider` that sets up some common global configuration and includes things like a global app Toast component.  You can see a gist containing the code for this component here:

[UiAppProvider - wraps the app bridge Provider component and the Polaris AppProvider component · GitHub](https://gist.github.com/fourstacks/ef48eccc224cb43e0bffadf902353757)

(Note that this gist is a version of the wrapped component that's been updated to be compatible with v4.x with the inclusion of the required `i18n ` prop on `AppProvider`)

The other library is  a form builder component that allows us to create Polaris forms using a JS config file to cut down on the boilerplate we need to write in projects.  We’re hoping to open source this once we’ve got past this issue.

Both libraries work just fine when both they and the consuming project are running on Polaris v3.x.

## Actual behavior

Since the update to v4.x we are encountering errors that we’ve been unable to get to the bottom of.

The general crux of these errors are that components that are within our UIAppProvider wrapper component seem to think they are not wrapped by a Polaris AppProvider component.  For example a project component returning this:

```tsx
return (
    <UiAppProvider title={title}>
        <Page title={title}>
            <p>Things are borked :(</p>
        </Page>
    </UiAppProvider>
);
```

Will cause the page component to spit out a console error to the effect of:

`<details>Uncaught MissingAppProviderError: No Theme was provided. Your application must be wrapped in an <AppProvider> component.</details>`

If I swap out our `UiAppProvider ` component for a regular `AppProvider` directly from Polaris everything works as expected.

However if I were to then add our form builder component as the content for the `Page` we’d end up getting a similar error to the above (only this time for the `Form` component that acts as the top level element for our form builder component).

My initial thoughts are that this is due to the move towards using hooks in Polaris 4.x.  

I had similar(ish) problems with another library called InertiaJS which I solved by ensuring that our core library doesn’t bundle another copy of React or InertiaJS and instead lists those libraries as peerDependencies.  I also ensured that the consuming project resolved only it’s own versions of those libraries and everything then worked as expected.

I’ve tried doing the same with Polaris for both our libraries but to no avail and I’m getting a bit stumped.  I might be missing an obvious gotcha to do with React hooks (or context which I’m guessing you’re probably using too) but I can’t see what it is.

Any help much appreciated!

## Steps to reproduce the problem

1. Create a standalone package with a component that wraps and configures `AppProvider`
2. Pull this package into a consuming project using Polaris (either via NPM or locally via NPM link)
3. Use the wrapped `AppProvider` component and nest a Polaris `Page` component within it
4. This should result in an error similar to the one mentioned above. 

## Reduced test case

Without creating a stripped down test case package and publishing it I can't really supply a reduced test case though happy to do this work if it's the only way to resolve the issue

## Specifications

- Are you using the React components? Y
- Polaris version number: 4.5.0
- Browser: Chrome
- Device: Macbook Pro
- Operating System: MacOS Mojave

**Comment by BPScott** [comment]
Hi @fourstacks,

Your gist looks pretty reasonable and I'd expect it to, as long as you're running React >= 16.9. Those useTheme() etc hooks don't do anything special - just pull a value from a Context that is provided by the AppProvider. Moving from v3 to v4 we changed to use modern context instead of legacy context to help enable that.

Could you provide a codesandbox demo that recreates your issue? This [CodeSandbox template](https://codesandbox.io/s/nb5c6) will be a good starting point. That'll help with getting something running that I can help diagnose.

**Comment by fourstacks** [comment]
Hi @BPScott, thanks for the quick reply - much appreciated - and thanks too for prompting me to sort out a reduced test case.  I've just spent a couple of hours doing some more testing on this and the TL;DR version is that I've now got things working - you can go ahead and close this.

I'm not really sure exactly what the problem was but my suspicion is that it was related to the way I was building my libraries for distribution.  I was using Laravel Mix to handle most of my build process with only minimal Webpack configuration to output to UMD.

In the course of creating a reduced use case I looked around for a more appropriate build setup and came across this [typescript library starter](https://github.com/bitjson/typescript-starter) which I used to build the library.  This outputs to CommonJS and to es6 modules neither of which are pre-bundled.

As this allows the consuming project (using Webpack) to do tree shaking and it doesn't bundle dependencies such as react, Polaris etc either it circumvents the issue I mentioned in the OP I'd had with InertiaJS where things broke due to two copies of React being present on the page.

If anyone else is having similar issues and comes across this then the bottom line seems to be - don't pre-bundle your library when building for distribution.  Export it as  CommonJS and/or ES6 and let the consuming project handle bundling.  You may want to include Polaris as a peerDependency in your package.json.

Appreciate this might not suit everyone creating a library but it seemed to do this trick for us.
