### ISSUE TITLE
Show Popover markup in HTML examples

### ISSUE THREAD

**Issue by dfmcphee** [Shopify/polaris-react#228]
# Issue summary

We don't show the generated HTML for the Popover and Action list examples.

## Expected behavior

The popover markup is included in the given HTML example.

## Actual behavior

The popover markup is omitted from the given HTML.

## Steps to reproduce the problem

1. Go to https://polaris.shopify.com/components/actions/action-list#navigation
1. Switch to the HTML tab

**Comment by ry5n** [comment]
It looks like this may still be unresolved. Reopening

**Comment by dfmcphee** [comment]
This should be actually fixed now 🎉
