### ISSUE TITLE
[Button] render button in focused state

### ISSUE THREAD

**Issue by sijad** [Shopify/polaris-react#2280]
## Feature request summary

allow render a `Button` in its focused state.

## Rationale

1. buttons that opens a popover need to be in their focused state when popover opened.
2. sometimes button need to be in focused state a in WYSIWYG editor toolbar.

![2019-10-11-21:40:06-screenshot](https://user-images.githubusercontent.com/7693001/66674353-906b8000-ec6f-11e9-8efd-8218e58dbdd6.png)

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dleroux** [comment]
Hi @sijad, Thanks for the feature request but it looks like you'll be able to do this when this PR merges: https://github.com/Shopify/polaris-react/pull/2148. I'll close this for now, reopen it that isn't the case.
