### ISSUE TITLE
[TextField] `min`, `max`, `step` and `aria-invalid="false"` shouldn't appear in the markup

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-react#2282]
## Issue summary

Attributes `min`, `max` and `step` should only appear in the generated markup when appropriate.

~It's also possible that we could get rid of `aria-invalid="false"`: @dpersing what do you think?~

Edit: we should also get rid of `aria-invalid="false"`, as per @dpersing's comment below.

## Expected behavior

```html
<input id="PolarisTextField2" class="Polaris-TextField__Input" value="Jaded Pixel">
```

## Actual behavior

```
// These attributes show up in the markup:
min="-Infinity" max="Infinity" step="1" aria-invalid="false"
```

```
<input id="PolarisTextField2" class="Polaris-TextField__Input" min="-Infinity" max="Infinity" step="1" aria-invalid="false" value="Jaded Pixel">
```

## Steps to reproduce the problem

1. Go to https://polaris.shopify.com/components/forms/text-field
1. In the code playground, switch to the HTML view

**Comment by dpersing** [comment]
@kaelig I am totally cool with getting rid of `aria-invalid="false"`. It's usually used inappropriately (like on page load), and I think it can cause a lot of confusion. If it's something we want to support, we should probably do it through a separate prop.

**Comment by kaelig** [comment]
Thank you @dpersing, I updated the issue accordingly!
