### ISSUE TITLE
[ResourceList] Undesirable space in "more filters" modal in Safari (macOS/iOS)

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-react#2286]
## Issue summary

In the example "Resource List with all of its elements", when opening the modal and expanding the accordion, a white space shows up where it shouldn't.

Related: #2264 #2284 

## Expected behavior

![Screen_Shot_2019-10-08_at_11_54_05_AM](https://user-images.githubusercontent.com/85783/66424395-693c5680-e9c2-11e9-8bf4-a1f4dbc21726.png)

## Actual behavior

<img width="963" alt="Screen Shot 2019-10-14 at 11 59 36 AM" src="https://user-images.githubusercontent.com/85783/66775971-2246d900-ee7a-11e9-8d04-6f0ce9dc7f74.png">

## Steps to reproduce the problem

1. Using Safari, go to https://polaris-react.herokuapp.com/?path=/story/all-components-resource-list--resource-list-with-all-of-its-elements
2. Click **More filters**
3. Expand **Tagged with**

**Comment by shui91** [comment]
@kaelig I'll take a stab at this one as well then! Might as well fix all the related issues with `Filters` 😛

**Comment by shui91** [comment]
@kaelig just following up on this issue as I have a PR open for it that will resolve this undesirable space. 

As a result of the fix, I discovered another issue (referenced above) where the selected Filter doesn't display the highlighted border. Hopefully that doesn't block #2292  for this fix though
