### ISSUE TITLE
[Filters] `:focus` pseudoclass is not applied in FireFox and Safari on button click

### ISSUE THREAD

**Issue by shui91** [Shopify/polaris-react#2293]
## Issue summary

While fixing a related issue with Safari not behaving the same as Chrome and Firefox in issue #2286 . I noticed that the Dark Purple `box-shadow` property that is applied on Chrome does not display on FireFox and Safari.

The reason this happens is because FireFox and Safari handle event clicks differently than on Chrome and [doesn't apply a focus event on click](https://stackoverflow.com/questions/42758815/safari-focus-event-doesnt-work-on-button-element).

I brought this issue up as a separate issue instead of attempting to fix this in #2292 because I could see this as a more wide-spread issue and because I'm not sure what the best approach would be to fixing this issue.

One solution seems to be applying a `tabIndex` to the `button` element, but when I tried it locally, it didn't work and I'm not confident that that would be the best solution since that would potentially affect/change current a11y.

Another solution (for this component, but doesn't seem to be applicable across other components), could be to change the pseudoclass in use from `:focus` to `:active`..

I'd still like to be assigned to this issue, I'd just appreciate some pointers as I'm unfamiliar with the Shopify team would want to approach this as per your team's best practices.

## Expected behavior
Screen shot from Chrome
<img width="554" alt="image of expected box shadow on focus from Chrome" src="https://user-images.githubusercontent.com/11592023/66803187-be50fe80-eed3-11e9-86db-03c48501e5b4.png">

<details>
<summary>GIF of expected behavior on Chrome</summary>

![chrome-gif](https://user-images.githubusercontent.com/11592023/66803528-b6458e80-eed4-11e9-91eb-124826b0455d.gif)
</details>

## Actual behavior
Screenshot from Safari
<img width="642" alt="No box-shadow applied on focus on Safari" src="https://user-images.githubusercontent.com/11592023/66803580-d7a67a80-eed4-11e9-9cd0-b7e677c6070d.png">

<details>
<summary>GIF of actual behavior on Safari</summary>

![safari-gif](https://user-images.githubusercontent.com/11592023/66803500-9f06a100-eed4-11e9-81b3-0f1c92d00904.gif)
</details>

## Steps to reproduce the problem

1. Go on Safari
2. https://polaris-react.herokuapp.com/?path=/story/all-components-filters--filtering-with-a-data-table
3. Click more filters
4. Select a filter 
5. Notice no Purple box-shadow is applied to the currently focused element

## Specifications

- Are you using the React components? (Y/N): Y (`Filters`)
- Polaris version number: 4.5.0
- Browser: Safari
- Device: Macbook Pro
- Operating System: Mojave

**Comment by dleroux** [comment]
Hi @shui91,

I agree with you that tabIndex might not be the right solution. How about instead of replacing `:focus` with `:active` just applying the CSS to both selectors? Since Chrome does apply `:focus` on`:active` it would be consistent across browsers.

**Comment by shui91** [comment]
Sounds good @dleroux! I was hesitant to implement that solution as it felt a bit naive and I'm not familiar enough with the UI library to have been confident that wouldn't break or violate some design rule the Shopify team had implemented :)

**Comment by dleroux** [comment]
@shui91, thanks for checking in but never worry about contributing. We really appreciate the contributions! If anything isn't right it will be caught in review.
