### ISSUE TITLE
ResourceList Component missing resourceName in header

### ISSUE THREAD

**Issue by nathanieldeal** [Shopify/polaris-react#2294]
## Issue summary

ResourceList Component missing resourceName in header

The resourceName was available in @shopify/polaris/3.2.1

It is no longer showing in version 4.0.0 or 4.5.0

![Screen Shot 2019-10-15 at 11 43 13 AM](https://user-images.githubusercontent.com/1265720/66847490-736dd000-ef41-11e9-8801-56b4e21122a4.png)

## Steps to reproduce the problem

Load ResourceList component code from https://polaris.shopify.com/components/lists-and-tables/resource-list#navigation

Install  @shopify/polaris/4.0.0 or above

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.0.0 and above
- Browser: Chrome
- Device: Macbook Mid 2017
- Operating System: High Sierra
- React:  16.10.2

**Comment by danrosenthal** [comment]
👋 Thanks for the issue @nathanieldeal. Can you please provide a reduced test case in a [CodeSandbox](https://codesandbox.io/s/84ypy?module=App.js) so we can attempt to reproduce the issue you're experiencing?

**Comment by nathanieldeal** [comment]
@danrosenthal Of course its working in sandbox :) Thanks for the link I'll play around with the dependencies to see if I can find any conflicts.

**Comment by nathanieldeal** [comment]
No bueno :( Looks like it on my side. Thanks for your help!
