### ISSUE TITLE
Add loading indicator to Pagination

### ISSUE THREAD

**Issue by patsissons** [Shopify/polaris-react#2316]
## Feature request summary

When paging a remote date source we often want to also render an additional loading indicator while the next or previous page is being fetched. This would be best supported directly by the `Pagination` component with a new `loading` prop.

## Rationale

This would eliminate some custom external implementation to swap out the `Pagination` component while loading, by allowing the `Pagination` component to fully provide the loading indicator in a reasonable layout.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by mbaumbach** [comment]
We had a similar need to temporarily make the `Pagination` unavailable, but opted to just set the `hasNext` and `hasPrevious` to `false` making the component appear disabled.

We found that hiding it entirely or showing a loading indicator was a bit jarring from a user perspective, but that's probably more personal preference than anything.

**Comment by patsissons** [comment]
by adding some styles to make sure the layout dimensions don't change, i found that the UX is not nearly as jarring (though i'll defer to others to confirm that opinion). I think the concept of adding a `loading` prop is still valid regardless, we just may want to build a better UX for what does `loading` mean to `Pagination`.

(demo below from a prototype in web)
![Demo](https://user-images.githubusercontent.com/5505280/67054104-4adc0680-f0f8-11e9-9557-db8588854482.gif)
