### ISSUE TITLE
[Sheet] allow change width

### ISSUE THREAD

**Issue by sijad** [Shopify/polaris-react#2324]
## Feature request summary

allow pass additional prop to change Sheet width in desktop mode.

edit: as Sheet uses Portal it's not possible to customize it via css classes.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by sijad** [comment]
[drawer](https://blueprintjs.com/docs/#core/components/drawer) is good example.

**Comment by dleroux** [comment]
Hi @sijad, can you tell me more about your use case for this?

**Comment by sijad** [comment]
we want to implement something like this: https://codepen.io/nicklassandell/pen/cqlGk (please try clicking on a thread to see the Sheet)

we want let users open threads and navigate between them as fast as possible and see other threads titles too. we don't want navigate to another screen.

the problem with the modal in this case is that when the modal is open much of threads titles are not visible anymore.

**Comment by dleroux** [comment]
@danrosenthal since you were part of developing the sheet, did varying width come up?

**Comment by danrosenthal** [comment]
It didn't come up, but I am starting to see the value in it after looking at @sijad's example. Long-form reading experiences definitely feel better inside a half width sheet than a quarter width sheet.

I'm less inclined to open it up fully to "varying" widths, and have the API be more limited.

Perhaps something like:

```tsx
export type Width = 'quarter' | 'half';

export interface SheetProps {
  /** How wide to render the sheet in desktop view */
  width?: Width;
  /** Whether or not the sheet is open */
  open: boolean;
  /** The child elements to render in the sheet */
  children: React.ReactNode;
  /** Callback when the backdrop is clicked or `ESC` is pressed */
  onClose(): void;
  /** Callback when the sheet has completed entering */
  onEntered?(): void;
  /** Callback when the sheet has started to exit */
  onExit?(): void;
}
```

**Comment by sijad** [comment]
`full` would be useful too:

```js
export type SheetWidth = 'quarter' | 'half' | 'full';
```

**Comment by danrosenthal** [comment]
> `full` would be useful too

What's the use-case for `full`?

**Comment by sijad** [comment]
I meant full screen `Sheet`

**Comment by danrosenthal** [comment]
> I meant full screen Sheet

Right, I understand. I meant what is the use case for a full screen `Sheet`. Consider that an important part of the use-case of a `Sheet` is that it does not fully obstruct the view of the elements behind it, since it has a relationship to those elements.

**Comment by sijad** [comment]
sorry, I miss read you comment, I don't have a use case in my project, but it is probably useful, both webbase, atlastkit support full screen drawer.

**Comment by danrosenthal** [comment]
Until we have a clear use-case for it, we should differ adding `full` width, perhaps indefinitely.

**Comment by sijad** [comment]
this seems to be easy to implement, I can take this if you want.

**Comment by danrosenthal** [comment]
That'd be great, thanks @sijad! Please ping me on the PR when you want feedback or review

**Comment by ctrlaltdylan** [comment]
Any update on this? Would love to have this property accessible to make my sheet usable.

Without scrolling, I need to pack information into the width of the sheet, but attempting to alter the width of the component just makes the component overflow to the right and out of the view of the browser..

![Screen Shot 2020-11-15 at 10 10 09 AM](https://user-images.githubusercontent.com/2694734/99188610-c577bb00-272a-11eb-9c42-e3f5a4faf07d.png)
