### ISSUE TITLE
Typescript build errors migrating to app-bridge-react

### ISSUE THREAD

**Issue by ptcampbell** [Shopify/polaris-react#2331]
I'm struggling to migrate to the `@shopify/app-bridge-react` package for my embedded app. 

Following [this example ]( https://help.shopify.com/en/api/embedded-apps/app-bridge/react-components)(was not easy to find by the way) leads me to this error for` <AppProvider/>`:

```
JSX element type 'AppProvider' is not a constructor function for JSX elements.
Type 'AppProvider' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.
```

And the `<Provider/>` from `'@shopify/app-bridge-react'`:

```
JSX element type 'Provider' is not a constructor function for JSX elements.
Type 'Provider' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.

JSX element class does not support attributes because it does not have a 'props' property.
```

I wondered if I should be using a particular version of Typescript. I'm on 3.5.3.

**Comment by BPScott** [comment]
This sort of thing tends to happen when you've got multiple versions of `@types/react` in your lock file. Try ensuring you're using only one version of that package. If you're using yarn https://github.com/atlassian/yarn-deduplicate can help: `npx yarn-deduplicate yarn.lock --packages @types/react`

**Comment by ptcampbell** [comment]
I'm not using yarn but I nuked `node_modules` and removed `package-lock.json` to no avail.

I also tried different versions of React — matched the `react`, `react-dom`, `@types/react` and Typescript versions to the ones used in this repo. 

For what it's worth this is my package.json…

```
        {
	"private": true,
	"scripts": {
           ////
	},
	"devDependencies": {
		"@shopify/polaris": "^4.6.1",
		"ajv": "^6.6.2",
		"axios": "^0.18",
		"babel-core": "^6.26.0",
		"babel-preset-react": "^6.23.0",
		"bootstrap": "^4.2.1",
		"cross-env": "^5.2.1",
		"jquery": "^3.2",
		"laravel-mix": "^4.1.4",
		"lodash": "^4.17.11",
		"popper.js": "^1.16.0",
		"react": "^16.8.6",
		"react-dom": "^16.8.6",
		"styled-components": "^3.4.10",
		"ts-loader": "^5.3.2",
		"tslint": "^5.20.0",
		"tslint-eslint-rules": "^5.4.0",
		"tslint-react": "^3.6.0",
		"typescript": "~3.5.1",
	},
	"dependencies": {
		"@types/react": "^16.8.15",
		"@types/react-dom": "^16.8.4",
		"@reach/router": "^1.2.1",
		"@sentry/browser": "^5.7.1",
		"@shopify/app-bridge-react": "^1.9.0",
		"@types/node": "^11.13.22",
		"@types/reach__router": "^1.2.6",
		"@types/webpack-env": "^1.14.1",
		"array-move": "^2.1.0",
		"overmind": "^20.0.0",
		"overmind-react": "^21.0.0",
		"query-string": "^6.8.3",
	}
}
```

**Comment by 8eecf0d2** [comment]
FWIW I get the same issue as above with _only_ `@shopify/polaris` installed and no other libraries which depend on `@types/react` - I've tried with a minimal repro on a Macbook in an Apple store and get the same result.

**Comment by ptcampbell** [comment]
I tried a new project too. Same problem.

**Comment by BPScott** [comment]
Heya folks, would one of you be able to provide me with a repository that reproduces your problem?

I'm can't reproduce it in this demo: https://codesandbox.io/s/shopify-polaris-appbridge-lniz3

**Comment by dunckr** [comment]
Thanks for the demo @BPScott.

Using your example's `tsconfig.json` fixed it for me. Cheers

**Comment by ptcampbell** [comment]
Crikey, sorry I missed this @BPScott — I'll double check the `tsconfig.json`
