### ISSUE TITLE
ResourcePicker returns "Your store doesn’t have any products yet." for some stores

### ISSUE THREAD

**Issue by Popesites** [Shopify/polaris-react#2332]
I'm having a troubling issue with the ResourcePicker component all of a sudden. It has been working completely fine up until today, with no changes to my app that would cause this error.

So I've been getting this error when attempting to search a store's inventory for products: 

<img width="629" alt="Screen Shot 2019-10-20 at 10 40 35 PM" src="https://user-images.githubusercontent.com/17707366/67179293-bb9a5180-f38a-11e9-8625-2b5a16837361.png">

Note that this was returning results as recently as yesterday.

Here is the response I'm getting for the request being made to /admin/internal/web/graphql/core

`{"data":null,"errors":[{"message":"access denied","locations":[{"line":4,"column":5}],"path":["shop","collections"]}],"extensions":{"cost":{"requestedQueryCost":103,"actualQueryCost":0,"throttleStatus":{"maximumAvailable":5000.0,"currentlyAvailable":5000,"restoreRate":250.0}}}}`

and here is the request being made

`{"operationName":"CollectionResourcePicker","variables":{"searchQuery":"","hasPublicationId":false,"publicationId":null,"first":50},"query":"query CollectionResourcePicker($first: Int!, $searchQuery: String = \"\", $after: String, $hasPublicationId: Boolean = false, $publicationId: ID = \"gid://shopify/Publication/0\") {\n  shop {\n    id\n    collections(first: $first, query: $searchQuery, after: $after, sortKey: TITLE) {\n      edges {\n        cursor\n        node {\n          ...CollectionResourceDisplay\n          publishedOnPublication(publicationId: $publicationId) @include(if: $hasPublicationId)\n          __typename\n        }\n        __typename\n      }\n      pageInfo {\n        hasNextPage\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment CollectionResourceDisplay on Collection {\n  id\n  title\n  image {\n    altText\n    transformedSrc(maxWidth: 200, maxHeight: 200)\n    __typename\n  }\n  __typename\n}\n"}`

Now, when I attempt to search for a specific product, the following happens:

1. I receive this Toast error message
<img width="679" alt="Screen Shot 2019-10-20 at 10 40 40 PM" src="https://user-images.githubusercontent.com/17707366/67179344-d8368980-f38a-11e9-9b9b-b1acc4c3015e.png">

2. I receive this error message in the console
`Uncaught Error: GraphQL error: access denied`

<img width="1666" alt="Screen Shot 2019-10-20 at 10 40 49 PM" src="https://user-images.githubusercontent.com/17707366/67179372-f00e0d80-f38a-11e9-91c4-aead599d2475.png">

**Comment by Popesites** [comment]
It should be noted that this is only happening on a few stores, it is not happening on all of my users' stores.

**Comment by mbaumbach** [comment]
We've seen this many times as well. For many of our customers, logging out of Shopify/clearing their cookies seems to do it. I'm not sure if it's an issue where the total number of cookies exceeds the 4kb allowed limit of the browser or what.

We haven't be able to reproduce in our own environments and when we request access to their shops it works for us as well, but we've had plenty come across this.

**Comment by mbaumbach** [comment]
Interesting, it failing in multiple browsers kind of breaks the theory of the cookie limit being the problem.

**Comment by dleroux** [comment]
Thanks for reporting this @Popesites. Looking into where the issue could be coming from. I will get back to you shortly.

**Comment by dleroux** [comment]
I've reported this in an internal repo as it isn't Polaris.
