### ISSUE TITLE
Datepicker jump in Firefox

### ISSUE THREAD

**Issue by carysmills** [Shopify/polaris-react#2333]
## Issue summary
Since web was upgraded to Polaris 4.3, the overview dashboard, finances summary and finances reports datepickers have had an issue with focusing on select of the days in Firefox. The focus ends up on the bottom of the page, making it impossible to select a day.

See gif and more details in the first part of this issue https://github.com/Shopify/store/issues/10573

Note: I added a temporary fix [here](https://github.com/Shopify/web/pull/19864/files#diff-ed56dee96d87ac7a90075d49476dbff8R36) in web. Happy to add this to Polaris but not sure if it is the right solution and dealing with the actual root problem.

## Expected behavior
You should be able to select a day without the datepicker jumping and closing

## Actual behavior
![Oct-21-2019 09-55-44](https://user-images.githubusercontent.com/12213371/67211603-06e34d00-f3e9-11e9-8720-4cfb9e608b4d.gif)

## Steps to reproduce the problem
Revert this web PR https://github.com/Shopify/web/pull/19864 locally (my temporary fix, which cloned the Polaris component and added `{preventScroll: true}` to the `focus` method). Visit `admin/dashboards` using Firefox and see the issue.

## Reduced test case
I haven't been able to create a reduced test case

## Specifications

- Are you using the React components? (Y/N): yes
- Polaris version number: 3.4 and above
- Browser: Firefox
- Device: web
- Operating System: Mac 10.14.6

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by alex-page** [comment]
```
FAIL app/sections/Analytics/components/DatePicker/tests/DatePicker.test.tsx (5.551s, 629 MB heap size)
  ● <DatePicker /> › renders only the popover component when condensedPage is not true
 
    expect(received).toContainReactComponent(expected)
 
    Expected the React element:
      <withI18n(WithMonorail) />
    To contain component:
      <Popover />
    But no matching <Popover /> elements were found.
 
      54 |     const wrapper = await mountWithAppContext(<DatePicker {...mockProps} />);
      55 |
    > 56 |     expect(wrapper).toContainReactComponent(Popover);
         |                     ^
      57 |     expect(wrapper).not.toContainReactComponent(Sheet);
      58 |   });
      59 |
 
      at Object.it (app/sections/Analytics/components/DatePicker/tests/DatePicker.test.tsx:56:21)
```
