### ISSUE TITLE
TextField display error

### ISSUE THREAD

**Issue by kekexunxun** [Shopify/polaris-react#2338]
## Issue summary

TextField width error
`<Stack.Item fill><TextField /></Stack.Item>`

I used `<Stack.Item fill></Stack.Item>` to contain `<TextField />`, but when the `<TextField error={true}>` error prop is positive and the focus is on the TextField component, it's width came to narrow down.

## Expected behavior

it's width stay still

I add this css to temporarily solve this problem
`
.Polaris-Stack__Item--fill .Polaris-TextField--error {
  flex: 1 1 auto !important;
}
`

**Comment by kekexunxun** [comment]
![image](https://user-images.githubusercontent.com/44473551/67275666-aee63c80-f4f5-11e9-8f1b-62f6f56f6956.png)

polaris 4.6.1
chrome 77

but when i try to copy the code to codesandbox, the error disappeared. and it still came up in my project.

here's the code https://codesandbox.io/s/gallant-dream-tk7by?fontsize=14

**Comment by dleroux** [comment]
Hi @kekexunxun, the sandbox code doesn't contain the error message you have on your screen. I added myself and it does render correctly. That said, I have a feeling a bug with Stack that will be in the next release should fix your issue. I'll ping once the release is out and you can confirm the fix.

**Comment by kekexunxun** [comment]
Thank you~
And there's another issue about Data Table.
When I render Data Table with the sortable prop, the table tr's border-bottom-line is not straight. You can find it on the shopify component page https://polaris.shopify.com/components/lists-and-tables/data-table and choose sortable table example.
![image](https://user-images.githubusercontent.com/44473551/67353061-367a8c80-f584-11e9-903a-78b33f0550aa.png)

first, I use this css to fix this problem
`
table th {
  border-bottom-width: 1px !important;
}
`
but when I used component in the table th, this doesn't work
so I tried to use
`
.Polaris-DataTable__Heading {
  padding: 0 1.6rem !important;
}
`
to fixed the bottom-line-view

**Comment by kekexunxun** [comment]
@dleroux try that codesandbox url again, I added my error info into it. And the textField error showed

**Comment by kekexunxun** [comment]
step 1: click save
step 2: focus the username TextField

**Comment by AndrewMusgrave** [comment]
cc/ @dleroux

**Comment by dleroux** [comment]
Hi @kekexunxun can you confirm your first issue has been fixed? If so I'm thinking we should close this and open another issue for the DataTable just so it doesn't get lost.
