### ISSUE TITLE
[ResourceList] / ResourceItem popover alignment

### ISSUE THREAD

**Issue by stephbaker** [Shopify/polaris-react#2363]
## Issue summary

The `ResourceItem` popover in a `ResourceList` offsets when a title takes up more than 1 line (for example a long title on a device screen)

## Expected behavior

The popovers for each `ResourceItem` should all stay aligned even when titles are more than one line.

<img width="407" alt="Screen Shot 2019-10-25 at 10 45 49 AM" src="https://user-images.githubusercontent.com/42748054/67584783-547af500-f71c-11e9-9e90-8608e87ca265.png">

## Actual behavior

The popovers have different widths and don't align themselves in a straight column

<img width="373" alt="Screen Shot 2019-10-25 at 9 47 08 AM" src="https://user-images.githubusercontent.com/42748054/67584656-1e3d7580-f71c-11e9-8099-61ae35051caf.png">

## Steps to reproduce the problem

1. Shorten your ResourceList so the title becomes 2 lines
1. Observe the popover

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

[Seen here](https://codesandbox.io/s/heuristic-moon-pywx3)
<img width="461" alt="Screen Shot 2019-10-25 at 10 43 12 AM" src="https://user-images.githubusercontent.com/42748054/67584660-209fcf80-f71c-11e9-96d1-1b4080a63b6f.png">

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.7.1
- Browser: Chrome
- Device: Web Browser (or simulating small width device)
- Operating System: Mac OS

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by dleroux** [comment]
Thank you for reporting this @stephbaker ! I actually got a quick PR up while investing #2370
