### ISSUE TITLE
ResourceList showHeader displays header, but its empty

### ISSUE THREAD

**Issue by artyrcheek** [Shopify/polaris-react#2371]
## Issue summary

when showHeader for resourceList is set to true, i get an empty header with no text inside it

## Expected behavior

I get a header saying: showing x items

## Actual behavior

<details>
      <summary>Empty Header</summary>
<img width="1660" alt="Screenshot 2019-10-28 at 16 31 40" src="https://user-images.githubusercontent.com/29695801/67697439-74224f80-f9a0-11e9-8bb0-0d6edb76113a.png">
    </details>

I get an empty header

## Steps to reproduce the problem

<details>
      <summary>Code</summary>
<img width="1680" alt="Screenshot 2019-10-28 at 15 45 00" src="https://user-images.githubusercontent.com/29695801/67697255-2a396980-f9a0-11e9-9902-83772720037a.png"
>
    </details>

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: 4.7.1
- Browser: chrome
- Device: MacBook
- Operating System:  osx

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.13 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Safari: 12.1.2
  npmPackages:
    @shopify/polaris: ^4.7.1 => 4.7.1
    react: ^16.11.0 => 16.11.0
    react-dom: ^16.11.0 => 16.11.0

```

**Comment by kouloughli-hemza** [comment]
i had the same issue before , and the fix was simple ;
in your <AppProvider> you need to add i18n props ;
`
import en from '@shopify/polaris/locales/en.json';
<AppProvider
                    theme={ThemeConfig}
                    i18n={en}
                >
<AppProvider/>
`
