### ISSUE TITLE
Resource Picker - Server errors when updating collections

### ISSUE THREAD

**Issue by wmceff** [Shopify/polaris-react#2378]
## Issue summary

Our support team has been reporting merchants experiencing a "Server Error" toast that appears while searching in the Resource Picker in our app. The error in the console is "Error writing result to store for query" - I've linked to a video containing the error below.

Unfortunately, we haven't found any way to reliably reproduce the problem outside of merchants' shops that report the problem. It seems to occur when they make updates to their collections or products and then revisit the app in the same session. Due to this, if there is another place I should report this issue, please let me know.

## Expected behavior

Searching the resource picker works without server errors.

## Actual behavior

Searching the resource picker occasionally results in server errors.

[Example screen capture video of error](http://files.pxu.co/2610ebbbff13)

## Steps to reproduce the problem

We haven't been able to reliably reproduce this, but at least 5 merchants have opened support tickets about the issue.

## Reduced test case

See linked video in 'Actual Behaviour'

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.4.0
- Browser: Multiple
- Device: Multiple
- Operating System: Multiple

**Comment by freemer** [comment]
I am able to fairly regularly reproduce using the following steps:

1. Open a Collection picker in-app
1. Edit a collection (just the title is fine)
1. Navigate back to app
1. Open a Collection picker.

Should show `Your store doesn’t have any collections yet.` Trying any search term should throw the above error. Refreshing the page fixes the issue.

**Comment by ignacio-chiazzo** [comment]
👋 We have implemented a fix for this. Please let me know if you still see it.
