### ISSUE TITLE
Incorrect documentation for emptyState imageContained prop

### ISSUE THREAD

**Issue by jeffcharles** [Shopify/polaris-react#2380]
## Issue summary

The documentation for `emptyState` `imageContained` says ```/** The image to use for large screens */
  imageContained?: boolean;``` in https://github.com/Shopify/polaris-react/blob/master/src/components/EmptyState/EmptyState.tsx#L20. To me, that description does not make sense for a boolean and seems like it's a copy paste error from the `largeImage` prop above it.

## Expected behavior

The description of the `imageContained` prop should accurately describe what the boolean for that prop represents.

## Actual behavior

`The image to use for large screens` is the description that appears.

## Steps to reproduce the problem

1. Visit https://polaris.shopify.com/components/structure/empty-state
1. Find `imageContained` on the page
1. Read the description for that prop

**Comment by chloerice** [comment]
Fixed by #2477
