### ISSUE TITLE
Infinite Loop When Using Multiple Tabs Components

### ISSUE THREAD

**Issue by Popesites** [Shopify/polaris-react#2388]
I seem to be hitting an infinite loop error when attempting to toggle two separate Tabs components simultaneously.

Here's a basic outline of the code:

`import { Tabs } from "@shopify/polaris";`
`import React from 'react';`
`class Test extends React.Component {`
    `state = {`
        `selectedTabOne: 0,`
        `selectedTabTwo: 0`
    `}`
    `render() {`
        `const tabs = [`
            `{`
                `id: 'testone',`
                `content: 'Buttons',`
                `accessibilityLabel: 'Buttons',`
                `panelID: 'buttons',`
            `},`
            `{`
                `id: 'testtwo',`
                `content: 'testtwo',`
                `accessibilityLabel: 'testtwo',`
                `panelID: 'testtwo',`
            `}`
        `];`
        `const tabsTwo = [`
            `{`
                `id: 'testthree',`
                `content: 'testthree',`
                `accessibilityLabel: 'testthree',`
                `panelID: 'testthree',`
            `},`
            `{`
                `id: 'testfour',`
                `content: 'testfour',`
                `accessibilityLabel: 'testfour',`
                `panelID: 'testfour',`
            `}`
        `];`
        `return (`
            `<>`
                `<Tabs tabs={tabs} selected={this.state.selectedTabOne} onSelect={(value) => { this.setState({ selectedTabOne: value }) }}>{tabs[this.state.selectedTabOne].content}</Tabs>`
                `<Tabs tabs={tabsTwo} selected={this.state.selectedTabTwo} onSelect={(value) => { this.setState({ selectedTabTwo: value }) }}>{tabsTwo[this.state.selectedTabTwo].content}</Tabs>`
            `</>`
        `)`
    `}`
`}`
`export default Test;`

Steps to reproduce:

1. Toggle first Tabs Component
2. Toggle second Tabs Component

That should result in the infinite loop spitting the following error in console: 

`Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

**Comment by dleroux** [comment]
Hi @Popesites, I created a sandbox with your code and can't reproduce your issue:

https://codesandbox.io/s/flamboyant-browser-62tlo?fontsize=14

Can you see if you can?
