### ISSUE TITLE
ResourceItem

### ISSUE THREAD

**Issue by gerwinbrunner** [Shopify/polaris-react#2396]
## Feature request summary

A ResourceItem should have the option disabled. 
This should change the the background to i.e subdued and make the cursor on hover to a pointer.

## Rationale

In a ResoucreList there might be an option that does not make sense to select, but should still be displayed for completeness.

An example of this would be the following scenario:
List all fulfillemts of an order and disable the fulfillments that do not require to be shipped.
Those lines will just have a text explaining why they are not needed.
All other fulfillments with physical products will be "enabled" and clickable.

<img width="976" alt="Screenshot 2019-11-04 at 21 28 12" src="https://user-images.githubusercontent.com/75502/68155498-1e264c80-ff4a-11e9-97b3-cc78d145ef65.png">

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by brechtwaeghe** [comment]
Would be a great feature. I have the same issue on my orders overview with for example an incorrect address.

**Comment by jsina** [comment]
@gerwinbrunner for changing cursor you can wrap the resourceItem with `<div ...` and handle the cursor with style on  it
```
    <div className="JobItem">
      <ResourceItem
        id={`${id}`}
        persistActions
        shortcutActions={shortcutActions}
        url={''}
      >
......
```
`example.css `
```
.JobItem > .Polaris-ResourceItem {
  cursor: auto;
}
```
