### ISSUE TITLE
Color Picker is not working if at page load it was hidden with "display: none" css property

### ISSUE THREAD

**Issue by Feuerstarter** [Shopify/polaris-react#2422]
## Issue summary

If at page load color picker is being hidden in the block with "display: none" property, it's not working properly (newValue object is always the same from onChange())

## Expected behavior

Color picker was hidden in Advanced Settings component wich renders (or not) by "display" css property. Expected normal behavior.

## Actual behavior

Color picker only works if "display" property is set to "initial" on the page load.
Hidden on-load Color Picker is not working.

## Steps to reproduce the problem

1. Create div, place Color Picker inside
1. Create a button wich changes "display" css property to make div visible or hidden by click
1. Now color picker will only works if "display" was set to "initial" on the page load. Setting it to "none" at the page load makes it broken

## Working solution
Using js conditions instead of css styling
Example: 

```
constructor(props) {
    super(props);
    this.state = {
      isAdvOpened: false
    };
  }
  toggleAdvancedSettings() {
    this.setState({
      isAdvOpened: !this.state.isAdvOpened
    });
  }
```

```
{this.state.isAdvOpened && <AdvancedSettings />}

<Button onClick={() => this.toggleAdvancedSettings()}>
     Advanced Settings
</Button>
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.7.3
- Browser: Chrome
- Device: PC
- Operating System: Windows 10

**Comment by dleroux** [comment]
Thanks for reporting this @Feuerstarter 

At a quick glance I feel like this should be handled by the consumer. Many of our components do calculations when they mount and if the component is hidden using `display: none` then those calculations can't occur. If you change your div to visibility hidden everything works as designed:

https://codesandbox.io/s/vigilant-leaf-51klc?fontsize=14&hidenavigation=1&theme=dark

Any reason why this wouldn't work for you?

**Comment by Feuerstarter** [comment]
Thanks, @dleroux.
Yeah, with "visibility: hidden" everything works fine, but this is not what I needed.
I had "Advanced Settings" component wich should only appear (and take some place) only after user clicks to toggle it, so "visibility: hidden" was not an option, because block (div) hidden with "visibility" still takes place on the page, while block hidden with "display: none" does not.
https://codesandbox.io/s/cool-banzai-i8opi?fontsize=14&hidenavigation=1&theme=dark
Anyway, JS "&&" condition is the best way to do this in React and it works, so probably where is should be a mention about "display: none" in polaris docs - that would be enough

**Comment by dleroux** [comment]
Thanks @Feuerstarter. I had never thought about that use case, thank you for bringing it up. I'll mention it to the team.
