### ISSUE TITLE
[Filters] Drawer items in 4.8.0 doesn't open properly, collapsable height is set incorrectly.

### ISSUE THREAD

**Issue by afleischer** [Shopify/polaris-react#2426]
## Issue summary

Styles appear to be incorrectly being applied to Polaris-Collapsable tags within the Drawer of a Filter component. This leads to the filter list overrunning the following filter dropdown button.
See screenshots for additional details

## Expected behavior

When clicking on a filter in the drawer, the following filter should slide down to make room for the filter options. 

## Actual behavior

![image](https://user-images.githubusercontent.com/2811273/68723598-dae16480-056d-11ea-98ae-176dcd673fb7.png)

The issue is likely linked to how the max-height is set. In 4.8, the max-height of 0 is NOT being overwritten by what appears to be height: auto set on the Polaris-Collapsable element.

![image](https://user-images.githubusercontent.com/2811273/68723788-85f21e00-056e-11ea-938c-e20afea95cc3.png)

## Steps to reproduce the problem

1. Include a <Filters> component in a Polaris react app
2. Select the "More Filters" button to the right of the search input and filter dropdowns
3. Click on a filter option.

This problem does NOT occur in 3.21.0 (our prior version) all else being equal.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.8.0
- Browser: Chrome
- Device: Macbook Pro
- Operating System: Mac OS X

**Comment by dleroux** [comment]
Hi @afleischer, do you have code sandbox that I can see this in action? I tried to reproduce locally and it's behaving as expected for me.

**Comment by afleischer** [comment]
@dleroux This was in an embedded app and so placing it within a Sandbox would likely be misleading- does the Shopify team have an internal embedded app sandbox to check this on?

**Comment by dleroux** [comment]
I see. It's interesting how this is only inside app. Thanks for clarifying.
