### ISSUE TITLE
DatePicker name of month not showing

### ISSUE THREAD

**Issue by SylarRuby** [Shopify/polaris-react#2446]
## Issue summary
DatePicker name of month not showing

## Expected behavior
I expect to see the name of the month as per [example](https://polaris.shopify.com/components/forms/date-picker).

## Actual behavior
[See actual issue](https://codesandbox.io/s/polaris-datepicker-no-month-name-b3dbg).

## Polaris Version
^4.8.0

**Comment by chloerice** [comment]
Hey @SylarRuby 👋 It looks like the `AppProvider` doesn't have the required `i18n` prop set. Here is a [forked version of the code sandbox you made](https://codesandbox.io/s/polaris-datepicker-no-month-name-3gtup) with the English translations set on the `i18n` prop. All Polaris component translations for Shopify Admin supported languages are available to import from the package.

Here's the [guide for Localizing Shopify Apps](https://help.shopify.com/en/api/guides/localization#2-how-shopify-sends-the-locale-to-apps). Along with retrieving the current session's locale from the `associated_user` in the authentication callback, you can also query for the list of a shop's locales from [`QueryRoot.shopLocales`](https://help.shopify.com/en/api/graphql-admin-api/reference/queryroot?api[version]=2019-10#shoplocales-2019-10) if you're using the Shopify GraphQL API, or the `primary_locale` from the [Shop route](https://help.shopify.com/en/api/reference/store-properties/shop) of the Shopify REST API.
