### ISSUE TITLE
Want to add the button in Layout.AnnotatedSection

### ISSUE THREAD

**Issue by yu-coder** [Shopify/polaris-react#2456]
## Issue summary

I am using `Layout.AnnotatedSection`.
I want to add the button with the title and description on the left side.

## Expected behavior

https://codesandbox.io/s/6xy2d?module=App.js
Is it possible to add a button?

## Actual behavior

I tried to add the button with `actions`, `primaryAction`, `secondaryAction` attributes but I couldn't add.

**Comment by BPScott** [comment]
The description accepts any ReactNode so you can pass jsx into it

```tsx
export default class App extends React.Component {
  render() {
    const description = (
        <div>
        Shopify and your customers will use this information to contact you.
        <Button>Hi</Button>
        </div>
      );
    
    return (
      <Layout>
  <Layout.AnnotatedSection
    title="Store details"
    description={description}
  >
    <Card sectioned>
      <FormLayout>
        <TextField label="Store name" onChange={() => {}} />
        <TextField type="email" label="Account email" onChange={() => {}} />
      </FormLayout>
    </Card>
  </Layout.AnnotatedSection>
</Layout>
    );
  }
}

```

**Comment by yu-coder** [comment]
@BPScott wow, it works.
Thank you!
