### ISSUE TITLE
[Sheet] [a11y] Focus should stay within the component container

### ISSUE THREAD

**Issue by mirualves** [Shopify/polaris-react#2463]
## Issue summary

The [`Sheet` component](https://polaris.shopify.com/components/overlays/sheet) behaves similar to the modal when it comes to trapping the focus. Tabbing backwards traps the focus while tabbing forward doesn't. The focus should stay in the sheet, moving forwards and backwards.

## Expected behavior
Forward and backwards: trap the focus in the Sheet.

## Actual behavior
Forward: does not trap the focus in the Sheet and includes the browser chrome.
Backwards: traps the focus in the Sheet.

**Comment by dpersing** [comment]
For reference, the original accessibility spec for the better list filters project, which included the creation of the sheet, called for treating the sheet like a modal from a keyboard perspective: https://docs.google.com/document/d/1aJVzBW4_RhFkbK34owKaHGgMaCW327o15cb4GPjIzkE/edit#heading=h.780m6wpvn95d

**Comment by LauraAubin** [comment]
Fixed with https://github.com/Shopify/polaris-react/pull/2555
