### ISSUE TITLE
EmptyState imageContained incorrect helper text 

### ISSUE THREAD

**Issue by jtsmills** [Shopify/polaris-react#2475]
## Issue summary
<img width="901" alt="image" src="https://user-images.githubusercontent.com/16560985/69738979-cfc23300-112e-11ea-8484-9fab9983258e.png">

The helper text for `imageContained` in the polaris public documentation is the same as the `largeImage` helper text. 

## Expected behavior
The helper text that is applicable for the `imageContained` prop is presented.

**Comment by chloerice** [comment]
Hey @jtsmills! Sorry for the confusion here, it looks like the description of the `imageContained` boolean prop was accidentally duplicated from the `largeImage` string image path prop. 

The `EmptyState` `largeImage` prop is an optional prop for you to set the source of a different image to display on larger screen sizes. Any text that you want to display in the `EmptyState` will need to be nested as a child.

**Comment by jtsmills** [comment]
Thanks @chloerice :)
