### ISSUE TITLE
Showing the field with 50% size in the line

### ISSUE THREAD

**Issue by yu-coder** [Shopify/polaris-react#2479]
## Issue summary
I am going to show the field with `50% size` of the line in the form using `FormLayout`

## Expected behavior

https://codesandbox.io/s/vibrant-goldstine-ojcwe?fontsize=14&hidenavigation=1&theme=dark
I could show **First Name** field in the line by hiding **Last Name** field with CSS.
This is one of the solutions but I think this is not a good way.

## Actual behavior

I tried using ### Layout, Stack but couldn't show the field properly without hiding other fields with CSS.

**Comment by BPScott** [comment]
Use the `condensed` prop on `FormLayout.Group` to fit multiple fields onto the same line. You can see this in action on the "Condensed field group" example on https://polaris.shopify.com/components/forms/form-layout


```
export default function App() {
  return (
    <FormLayout>
      <FormLayout.Group condensed>
        <TextField label="First Name" onChange={() => {}} />

        <TextField label="Last name" onChange={() => {}} />
      </FormLayout.Group>
      <TextField type="email" label="Account email" onChange={() => {}} />
    </FormLayout>
  );
}

```

**Comment by yu-coder** [comment]
Thank you, @BPScott
