### ISSUE TITLE
Add a new definition of customers to Polaris

### ISSUE THREAD

**Issue by conniecerf** [Shopify/polaris-react#2483]
## Feature request summary
A few months back I asked @selenehinkley to unpublish the definitions of customer we had in Polaris as they didn't reflect how we think of customers in the Shopify admin. We should now replace the definition with a shiny new one that better reflects what customers on Shopify are.

Write a short description of the feature here ↓

###Customer

A person or organization becomes a customer and appears on the Customers page when they engage with a merchant in an identifiable way. This could be because they:

- were added or imported by the merchant
- started a purchase but abandoned it at checkout
- placed an order
- create a customer account
- subscribed to the merchant's mailing list

## Rationale

Customers aren't just people who have purchased and we need to be consistent in how we refer to them across Shopify so that merchants understand why someone appears in their customer list.

Audit here: https://docs.google.com/document/d/1C_Bf6q8551-NyrFO9f3pEAQahKskIU1zYFdeAFZfu0s/edit#

Explain the benefit of this feature

Customer is widely used across Shopify and should not be interchanged with terms like buyer or shopper.

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by selenehinkley** [comment]
Hey @conniecerf! This is good timing. Andy and I are adding the merchant-to-customer guidelines this week. Here's the PR:

We included a short description of buyer and customer to differentiate them (in the Vocabulary considerations section):

A ‘buyer’ interacts with multiple Shopify stores or has a direct relationship with Shopify, such as through Shopify Pay.

In contrast, a ‘customer’ is someone who interacts with one Shopify store or on a per-store basis.

My question is, could we combine our customer definitions to be aligned? We grabbed this sentence from the [buyer definition doc](https://docs.google.com/document/d/1288GxjR9FIyAofMyxcjcxkifa3miZIBLsqnQwqDCM-A/edit?ts=5bd71beb#)

**Comment by andyhealey26** [comment]
Yeah, it makes sense to combine the definitions. Couple of thoughts:
1. Could the middle sentence be removed? "In the Shopify admin, a customer appears on the Customers page when they engage with a merchant in an identifiable way. 
2. I think we agreed that how we use customer carries over in to how the marketing team use shopper - ie someone who visits a store but doesn't necessarily engage in any of the ways described in the bullet points. As these content guidelines are applicable beyond checkout (eg Evi is using them as a basis for the search discovery components) then do we need to include those use-cases somehow?

**Comment by conniecerf** [comment]
Hi Andy, yup when I chatted to our lovely marketing colleagues we agreed that shopper and customer aren't quite the same. A `shopper` would become a customer once they create an account, subscribe or abandon a checkout before that they are not identifiable so they are a 'potential customer' or a shopper. Yeah these guidelines should definitely be applicable beyond checkout but there is also the ways we classify customers in POS and admin to consider and browsers won't count as a customer for those purposes so it's tricky.

**Comment by selenehinkley** [comment]
Let's all work on aligning the definitions here (I made some updates based on the above convo but get in there and re-word it wherever it makes sense):

Merchant to customer section:
In contrast, a ‘customer’ is a person or organization who interacts with one Shopify store or on a per-store basis.

Vocabulary section:
###Customer

A person or organization who interacts with one Shopify store or on a per-store basis. In the Shopify admin and POS, a customer appears on the Customers page when they engage with a merchant in an identifiable way. This could be because they:

- were added or imported by the merchant
- started a purchase but abandoned it at checkout
- made a purchase
- create a customer account
- subscribed to the merchant's mailing list

**Comment by conniecerf** [comment]
Ok I tried to have my cake and eat it too by marrying the holistic customer term which we will continue to use with the more nuanced term Merchants need in certain places in the admin. If this is too long we could cut the POS and Shopify admin bit entirely and just leave that level of detail for merchant-facing guidance (our docs are currently inaccurate).

###Customer

A person or organization who interacts with one Shopify merchant or on a per-store basis.

For example: Customers will get a discount if they enter a code at checkout.

In the Shopify admin and POS, a customer appears on the Customers page when they engage with a merchant in an identifiable way. This could be because they:

- were added or imported by the merchant
- started a purchase but abandoned it at checkout
- made a purchase
- create a customer account
- subscribed to the merchant's mailing list

Tip: Avoid using "returning customer" (or other adjectives that imply a customer must have made a purchase) in contexts where merchants need a precise understanding of how their business is operating like analytics or segmentation.

**Comment by selenehinkley** [comment]
That sounds good to me! @andyhealey26?

**Comment by andyhealey26** [comment]
Could "one Shopify merchant or on a per-store basis" be a bit more plain language?
Also does POS need to be spelled out as Point-of-Sale (POS)?

**Comment by selenehinkley** [comment]
@andyhealey26 mind taking a pass at making it plain language? Yep, we can spell out POS

**Comment by andyhealey26** [comment]
I'm not totally clear what _per-store basis_ means here :)

Would _interacts with a Shopify merchant's store_ work? @conniecerf

**Comment by conniecerf** [comment]
Oh yeah I just added that in because I thought it was the offish buyer doc definition. Ideally we'd stay away from store entirely and go with `interacts with a merchant's sale channel`, it that too clinical?

**Comment by selenehinkley** [comment]
ooo I like `sales channel`. We have it defined in the vocabulary list already so people could look that term up as well

**Comment by conniecerf** [comment]
Yeah this looks good! In terms of `one Shopify merchant` I wonder if just `a Shopify merchant` does the trick. Looking at it now one might feels a little prescriptive, like they can have visited more than one merchant and still be a customer, one feels more valuable if we are defining customer against `buyer`. Thought @andyhealey26 ?

**Comment by andyhealey26** [comment]
Yeah agreed, so
_A person or organization who interacts with a Shopify merchant or their sale channel._ ?

**Comment by conniecerf** [comment]
Hey pals, is there anything else I have to do on this now that we've agreed on a lovely definition?

**Comment by conniecerf** [comment]
##Final definition

A person or organization who interacts with a Shopify merchant or their sales channel.

For example: Customers will get a discount if they enter a code at checkout.

In the Shopify admin and POS, a customer appears on the Customers page when they engage with a merchant in an identifiable way. This could be because they:

- were added or imported by the merchant
- started a purchase but abandoned it at checkout
- made a purchase
- create a customer account
- subscribed to the merchant's mailing list

Tip: Avoid using "returning customer" (or other adjectives that imply a customer made a purchase) in contexts where merchants need a precise understanding of how their business is operating like analytics.

**Comment by andyhealey26** [comment]
Looks good to me. Selene's out for holidays now.
Tiny thing, can you swop "operating like" for "operating, such as"
