### ISSUE TITLE
will there be any changes to license?

### ISSUE THREAD

**Issue by sijad** [Shopify/polaris-react#2488]
I've read all of prior license questions regarding using Polaris in standalone applications.
as there's some activity such as [🌈 Polaris for everyone](https://github.com/Shopify/polaris-react/issues?q=label%3A%22%F0%9F%8C%88+Polaris+for+everyone%22&utf8=%E2%9C%93), can you please let us know if there's going to be any changes to Polaris license?

**Comment by alex-page** [comment]
Hi @sijad! Thanks for reaching out! We have not planned any changes to the license. 

Polaris for Everyone is a team at Shopify that is working to add some new functionality and flexibility to the components. We hope to be able to share more information in the future.

If you have any feedback on the license or there is anything you are trying to achieve that the license is stopping you from doing, please let me know.

I'm going to close the issue, but feel free to keep the conversation going 👍

**Comment by haikyuu** [comment]
That's too bad. Seems like Shopify is going the old Microsoft route. Losing developers like this is not a smart move.
Shopify relies on developers to grow.

There is no future for proprietary software in the developer ecosystem. I hope this decision will be reconsidered.

**Comment by alex-page** [comment]
Hey @haikyuu, what challenges do you face from the current license?

**Comment by haikyuu** [comment]
I'm building a custom ecommerce website. And I'd like to build the admin interface using Polaris. But I can't do that because of the license.

My project isn't related to shopify at all
