### ISSUE TITLE
[Banner] Secondary action CSS broken on Firefox

### ISSUE THREAD

**Issue by carolopolo** [Shopify/polaris-react#2493]
## Issue summary

- On Firefox, the CSS of the `secondaryAction` of a banner breaks on click, before redirecting to the url

## Expected behavior

- The `secondaryAction` CSS should not break before redirecting to the url

## Steps to reproduce the problem

1. https://codesandbox.io/s/infallible-faraday-92uld
2. Please open the above on Firefox and observe that when you click on the `secondaryAction` of a banner, the CSS breaks before redirecting to the url

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by tmlayton** [comment]
The focus styles include a negative margin + padding to create the background around in inner span, which cause a line wrap in Firefox because there is not enough space in the container.
