### ISSUE TITLE
Unable to mount any of the React components from app-bridge-react

### ISSUE THREAD

**Issue by srameshr** [Shopify/polaris-react#2525]
## Issue summary

Tried mounting, ```<Loading />```, ```<Modal />``` and ```<ResourcePicker />```  and nothing seems to work. I don't see anything in the UI.

```
import React, { Component, Suspense, lazy } from 'react';
import {
  AppProvider as PolarisAppProvider, Page
} from '@shopify/polaris';
import { ResourcePicker, TitleBar, Modal, Provider as ShopifyReactAppBridgeProvider, Loading } from '@shopify/app-bridge-react';


class Test extends Component {
  render() {
    return (
      <div>
        <h1>Hello world</h1>
        <TitleBar title="My page title"/>
        <Loading />
        <Modal title="My modal" message="Hello world!" open />

        <ResourcePicker
          resourceType="Product"
          showVariants={true}
          allowMultiple={true}
          open={true}
          onSelection={() => null}
          onCancel={() => null}
        />    
      </div>
    )
  }
}

class App extends Component {

  render() {
    const shopifyConfig = { apiKey: 'mykey', shopOrigin: 'store.myshopify.com', forceRedirect: false };

    return (
        <PolarisAppProvider i18n={{}}>
            <ShopifyReactAppBridgeProvider config={shopifyConfig}>
                <Test />
            </ShopifyReactAppBridgeProvider>
        </PolarisAppProvider>
    )
  }
}
```
## Expected behavior
All the components should be rendered and not just ```hello world```

## Actual behavior
Only ```hello world``` is rendered. Rest of the components are not. 

## Steps to reproduce the problem

1. Follow the code pasted above.

## Reduced test case

NONE

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.2.1 and app-bridge-react is .11.2
- Browser: Chrome
- Device: Mac book pro
- Operating System: Mojave

**Comment by AndrewMusgrave** [comment]
👋 Hey, the app bridge components work if you comment out `<PolarisAppProvider i18n={{}}>` and what does your network tab look like in the dev tools?

**Comment by srameshr** [comment]
I tried that. It is not working. Network tab is basically empty.

**Comment by AndrewMusgrave** [comment]
It seems this is a problem with app bridge cc/ @Shopify/app-bridge

**Comment by vividviolet** [comment]
@srameshr I cannot reproduce the issue. Can you double-check your API key to ensure that it's matching what's been set in the Partner's dashboard?

Also, if your app is a Node app, you can set an environment variable `NODE_ENV === 'development'` in order to enable the debug mode of App Bridge which might help diagnose the issues.

**Comment by srameshr** [comment]
@vividviolet 
I can still reproduce it.

**Comment by meecrobe** [comment]
Same here.
Any updates on this, @vividviolet @AndrewMusgrave?

**Comment by srameshr** [comment]
@meecrobe 
They don't reply here usually. Either post a duplicate on their community Q&A site or debug into the the component.

**Comment by AndrewMusgrave** [comment]
👋 Going to see if I can get someone from the app-bridge to take a look

**Comment by iainmcampbell** [comment]
I also cannot reproduce this. Copy/pasted the code, including the exact App Bridge and Polaris versions in the original post.

I notice `forceRedirect` is set to `false` in the example code.  All of the App Bridge React components in the example code will only render when the app is loaded inside Shopify. If the app is loaded on its own, nothing will be rendered. @srameshr @meecrobe, when you experience this issue, is your app loaded inside Shopify?

**Comment by srameshr** [comment]
@iainmcampbell I did set forceRedirect to true. It actually redirects to Shopify embedded app page. But inside the embedded app page the the resource picker does not render. 

Also, why is resource picker not a part of Polaris? Is it because cross site requests cant be made from other apps which are not embedded? Is there any plans to make ResourcePicker available outside of embedded apps?

**Comment by iainmcampbell** [comment]
> I did set forceRedirect to true. It actually redirects to Shopify embedded app page. But inside the embedded app page the the resource picker does not render.

Ah, ok. Are you serving your app from the same domain you entered under App Settings in Partners Dashboard? If not, communication between your app and Shopify Admin will be blocked. Also, try checking the browser console for errors.

> Also, why is resource picker not a part of Polaris? Is it because cross site requests cant be made from other apps which are not embedded? Is there any plans to make ResourcePicker available outside of embedded apps?

Polaris is a UI library. Resource Picker uses Polaris UI components, but builds a ton of functionality on top, which is way out of scope for Polaris. If you'd like to use a resource picker outside of Shopify Admin, you’ll need to build your own using the Admin API.

**Comment by srameshr** [comment]
> Ah, ok. Are you serving your app from the same domain you entered under App Settings in Partners Dashboard? If not, communication between your app and Shopify Admin will be blocked. Also, try checking the browser console for errors.

Actually yes. We tried building an embedded app initially and our first approach was just trying to mount inside the embedded app page under the whitelisted domain. There are no console errors or network request. 

In the end we decided to port our app to outside of Shopify embedded page so this is not an issue any more.
