### ISSUE TITLE
Is there any way to change the background color of the tooltip?

### ISSUE THREAD

**Issue by yu-coder** [Shopify/polaris-react#2526]
I want to change the **background** color of the **tooltip**.
But there are only options for **light** and **black** by `light={false}`

Is there any way to change the **background** color of the tooltip?

**Comment by AndrewMusgrave** [comment]
Hi @yu-coder currently the only way to change the background color of the tooltip component is the `light` prop.

**Comment by yu-coder** [comment]
@AndrewMusgrave I see.
