### ISSUE TITLE
ContextualSaveBar on a fullWidth Page

### ISSUE THREAD

**Issue by brechtwaeghe** [Shopify/polaris-react#2533]
## Feature request summary

I'm using the AppBridge ContextualSaveBar in a new embedded app.
The fullWidth Page attribute is used on several pages , this way there is more space available to edit all input fields. 

When the ContextualSaveBar pops up the content width of the ContextualSaveBar is not the same as the container width of the page content. Would it be possible to add a fullWidth option in the ContextualSaveBar? Or detect if the ContextualSaveBar is on a Page with fullWidth enabled?

<img width="1393" alt="Screenshot 2019-12-09 at 10 38 57" src="https://user-images.githubusercontent.com/177378/70613795-8b906180-1c09-11ea-9539-de8518c35ccd.png">

Demo: https://codesandbox.io/s/festive-elion-ybi2x

## Rationale

It's visually more logical if both save buttons (ContextualSaveBar & PageActions) would be aligned right & the title of the ContextualSaveBar would be aligned with the title of the page.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by alex-page** [comment]
Hey @brechtwaeghe thanks for bringing this up. I have made a PR to address this. Sorry for the lack of reply, really appreciate you making this issue. 💯

**Comment by brechtwaeghe** [comment]
Hi @alex-page thanks a lot for looking into this. Our pages will look much better with this fix.
Will this be published in @shopify/app-bridge/actions as well? Because I'm using this package to display the ContextualSaveBar.

**Comment by alex-page** [comment]
Yes, I am hoping to work with that team to update Polaris so it is a part of app-bridge.

**Comment by alex-page** [comment]
This should be available in app-bridge early next week.

**Comment by alex-page** [comment]
It should be released tomorrow!
