### ISSUE TITLE
[Collapsible] Collapsible animations are Janky when parent quickly updates

### ISSUE THREAD

**Issue by Flufd** [Shopify/polaris-react#2566]
## Issue summary

The animation on the collapsible suffers from stuttering when the containing component makes an update/re-render quickly after changing the `open` prop on the component.

It's hard to see but it looks like this is caused by the max-height being set to 0px for a short time after being set to the full height on the component.

I originally encountered this when triggering some data loading when opening the `Collapsible`, so the container had a `useEffect` where the value being passed to the `open` prop was one of the hook dependencies. My workaround is to debounce the data fetch by 300 ms (the same as the opening animation)

## Expected behavior
The animation should be smooth.

## Actual behavior
The animation either looks janky or is missed altogether

## Reduced test case
Codesandbox here https://codesandbox.io/s/polaris-collapsible-jank-x56sb

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 4.8.0 (seems to be in latest rc too)
- Browser:Chrome
- Device:
- Operating System:Mac OSX

**Comment by Flufd** [comment]
This is still an issue in the latest version of Polaris.

**Comment by Ahad-patel** [comment]
it is still an issue, but you can solve using this method
https://codesandbox.io/p/sandbox/polaris-collapsible-jank-forked-582s3q
