### ISSUE TITLE
Navigation always reload page

### ISSUE THREAD

**Issue by thieuanh1995hn** [Shopify/polaris-react#2575]
Hello guys. Can you help me with the navigation.
- The original way to setup a item in navigation is
```javascript
{    
      label: "Shipments",
      icon: ShipmentMajorMonotone,
      url: "/shipments",
      selected: location.pathname.trim() === "/shipments",
    }
```
- With above way when click shipments on navigation it's always reload page so i change to my way
```javascript
    {
      label: "Shipments",
      icon: ShipmentMajorMonotone,
      url: "javascript:void(0)",
      selected: location.pathname.trim() === "/shipments",
      onClick: () => history.push('/shipments')
    }
```
It did not reload page but show some warning . Can some way equal to do by original way ?

**Comment by chloerice** [comment]
Hi @thieuanh1995hn, thanks for raising this. Is this happening within an embedded app (using AppBridge), or are you working on a stand-alone app (one that is not embedded within an iframe in the Shopify Admin)? 

If your app is embedded, the info in [this related issue](https://github.com/Shopify/polaris-react/issues/998) may help.

**Comment by thieuanh1995hn** [comment]
@chloerice  it's just normal react website using Polaris. It has not related to Shopify App but it will.

**Comment by BPScott** [comment]
@thieuanh1995hn what router are you using? react-router?

**Comment by suresh-ums** [comment]
{
              label: "Shipments",
              icon: CustomersMajor,
              selected: this.isNavURLMatched("shipments"),
              url: "", 
              onClick: () => { 
                 this.setState({ navigationMenuClick: true });
                  redirect.dispatch(
                    Redirect.Action.APP,
                   "/shipments?shop=" + this.props.router.query.shop
                    ); 
              },
            },
