### ISSUE TITLE
Icon color is of less priority when in a button component

### ISSUE THREAD

**Issue by SylarRuby** [Shopify/polaris-react#2586]
When an `Icon` is placed inside a `Button` component with the `plain` prop `true`, the Icon color is of less priority. [See example](https://codesandbox.io/s/agitated-glade-orx5s).

I expect when I add a color prop to an icon, within a button, I see the expected color. In this case, white.

This culprit is `.Polaris-Button--plain svg` in the compiled css. I could override but wondering if this is the expected behaviour?

```scss
.Polaris-Button--plain svg {
    fill: #006fbb;
}
```

**Comment by gavinsmith** [comment]
This is still an issue, not sure if it can be re-opened.

**Comment by timup** [comment]
Late to the party, but one way to handle this is to render the icon as a child of the button rather than as a prop...

```jsx
<Button plain>
    <Icon color={"interactive"} source={EditMinor} />
</Button>
```

**Comment by md604** [comment]
> Late to the party, but one way to handle this is to render the icon as a child of the button rather than as a prop...
> 
> ```js
> <Button plain>
>     <Icon color={"interactive"} source={EditMinor} />
> </Button>
> ```

Does not work in TS version. Button's children are of type string or string[] :(
