### ISSUE TITLE
Popover prevents scrolling by scrollbar when virtualized list is being used

### ISSUE THREAD

**Issue by robin-drexler** [Shopify/polaris-react#2605]
## Issue summary

Popover prevents scrolling by scrollbar when virtualized list is being used. Scrolling gets stuck after a certain, small amount has been scrolled.

Actually it prevents scrolling whenever something modifies the subtree `onScroll` inside a popover. This happens to be the case in `react-virtualized` as it needs to display the appropriate items based on the scroll position. This definitely happens in Chrome and Safari and is not an issue in Firefox. Scrolling using the touch pad works just fine, too.

We already conducted some debugging which you can find in the `reduced test cases` section.

## Expected behavior
Scrolling using scrollbar should work.

## Actual behavior
Scrolling stuck when scrollbar is being used.

<details>

  <summary>gif</summary>
      <img src="https://user-images.githubusercontent.com/474248/71984245-756cc580-31f6-11ea-9833-995e287f779e.gif" alt="scrolling being stuck">
</details>

## Reduced test case

We have prepared a few test cases. It seems like the issue is being caused by the `PopoverOverlay` changing the container's `display` from `block` to `flex` when it's measuring on subtree change (those changes happen to take place on scroll when a library like react-virtualized is used). This then seems to cause some browsers to stop the scrolling.

[PopoverOverlay applying the class during measuring](https://github.com/Shopify/polaris/blob/4262c5dce4da1af7470f4a374636228cdd8e29b5/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx#L196).

[The `display` switch to `block` in css](https://github.com/Shopify/polaris-react/blob/4262c5dce4da1af7470f4a374636228cdd8e29b5/src/components/Popover/Popover.scss#L48-L52)

### Test case 1 - virtualized list
This is the closest [to the actual error that we have.](https://github.com/Shopify/shopify/issues/221766) It uses react-virtualized.
https://codesandbox.io/s/nice-hodgkin-7sylo

### Test case 2 - modifying subtree when scrolling
Test case without react-virtualized that adds new items when you scroll and has the same issue. 
https://codesandbox.io/s/young-cache-mr6ej

### Test case 3 - without polaris
Showcasing that simply changing `display` from `block` to `flex` (or vice versa) while scrolling causes the odd behavior.

https://codesandbox.io/s/async-sky-xiroz

I don't have a lot of context on the Popover etc. but wondered if we could use `flex` while we are measuring as well? Wouldn't we want to measure under the same conditions as the element will be in after measuring?

## Specifications

- Are you using the React components? (Y/N): y
- Polaris version number: 4.10.2
- Browser: Chrome 79 / Safari 13
- Device: Mac
- Operating System: Catalina

**Comment by dhmacs** [comment]
@robin-drexler I'm using Polaris v4.25.1 and I still have the same issue (works in Firefox but not in Chrome).
