### ISSUE TITLE
[Banner] Make banners collapsible

### ISSUE THREAD

**Issue by JonathanGin52** [Shopify/polaris-react#2613]
## Feature request summary
Make banners collapsible. A banner in the collapsed state only displays its title.

Example: 
![image](https://user-images.githubusercontent.com/26397946/72187392-8455a280-33c5-11ea-8cce-482945670c3f.png)

## Rationale
Banners are great for displaying important information, however they take up precious screen real-estate. A banner's body can contain helpful details, however once acknowledged, the user should be able to hide the banner body, while the title remains as a reminder / call to action.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by AndrewMusgrave** [comment]
cc/ @sarahill @mirualves
