### ISSUE TITLE
autoFocus on Select

### ISSUE THREAD

**Issue by devchris** [Shopify/polaris-react#2615]
## Feature request summary

It would be really nice to have the `autoFocus` option on the `Select` component as well. The same way as it's working on the `TextField` component.

## Rationale

Increases User Experience - gives users the ability to tab through forms.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by AndrewMusgrave** [comment]
Hi @devchris , rather than an `autoFocus` prop how could you feel about a more imperative approach. E.g `select.focus()`

**Comment by devchris** [comment]
@AndrewMusgrave , that would work too 👍
