### ISSUE TITLE
[Modal] smaller prop

### ISSUE THREAD

**Issue by patsissons** [Shopify/polaris-react#2620]
## Feature request summary

`Modal` supports a `larger` prop to stretch the modal dialog wider, but offers no similar `smaller` prop to squish the dialog slimmer.

## Rationale

This can be particularly desirable when a modal is used for form entry and the expected field inputs are relatively small, this allows us to avoid a lot of wasted horizontal space.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by LauraAubin** [comment]
A possible guideline for a smaller modal could be,

> Use the `small` modal if there are fewer elements that all sit on their own row

cc @sarahill
