### ISSUE TITLE
Document the markdown parsing process

### ISSUE THREAD

**Issue by lpoulter** [Shopify/polaris-react#2634]
## Feature request summary

I'm trying to better understand how the mdx files are processed. I've look at the config files in `./storybook` but it feels that are some bit's missing. How for instance are is the list of Props added and made interactive or how is the Edit in code sandbox button generated.  

## Rationale

To help myself and others contribute.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by kaelig** [comment]
Hi Laurie, thank you for showing you'd like to contribute 💟 

The code that does what you're referring to is stored in a private repository (Shopify/polaris-styleguide), which deploys to https://polaris.shopify.com.

We don't have any plans to open-source this side of Polaris at the moment, so if you have any feedback or suggestions, this public repository is the best place to do so.
