### ISSUE TITLE
TextField will not render value prop if passed a number

### ISSUE THREAD

**Issue by pklitscher** [Shopify/polaris-react#2664]
## Issue summary

`<TextField/>` will not render value when passed a number. This happens even if `type="number"'

## Expected behavior

When a number is passed to the value prop `<TextField/>` should render the value

## Actual behavior

No value is rendered

## Steps to reproduce the problem

1. Go to code sandbox
2. Type in number or use buttons to increment 

## Reduced test case

https://codesandbox.io/s/shopify-polaris-textfield-number-issue-u7kve

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.11.0
- Browser: Chrome: 79.0.3945.79
- Device: Laptop
- Operating System: Windows 10

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.21 GB / 15.86 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
  npmPackages:
    react: ^16.12.0 => 16.12.0
    react-dom: ^16.12.0 => 16.12.0
```

**Comment by devchris** [comment]
Looks like this was intended behavior:
https://github.com/Shopify/polaris-react/pull/2598/files#diff-ce1bd24f5c7c2bd4b9fb5d55a5aa97aeR186-R189

**Comment by Feuerstarter** [comment]
Same issue after updating from 4.10.2 to 4.11.0.
All the "input-type: number" textfields have stopped working at all.
TextFields just fail displaying any variable from redux store for me.

**Comment by Feuerstarter** [comment]
Found solution:
I have number variables in my redux store.
Before I were passing numbers directly to the textfield, and then parsing a string coming from textfield back to the number to store and work with it properly.
Now I pass my number variables to the textfield after parsing them to the string:
`value={String(
     this.props.boosterTable.currentItem.dismissTime
)}`

**Comment by pklitscher** [comment]
> Just parse your number to the string before passing it to the TextField "value" prop.

Yes my solution for every number input now is 

```
const [myValue setMyValue] = useState(3)

const handleChange = useCallback((val) => setMyValue(Number(val)), [setMyValue])

<TextField value={myValue.toString()} onChange={handleChange}/>
```
Not ideal but some values I want stored as numbers

**Comment by BPScott** [comment]
Heya @pklitscher, 

As you've already found out TextField only supports passing a string into its value, [per its type](https://github.com/Shopify/polaris-react/blob/b2f5994f3bc7e6848d58227b0601c18380ebf71d/src/components/TextField/TextField.tsx#L43), and the solution is to call `toString()` on what you pass in.

**Comment by brayhoward** [comment]
Maybe y'all should consider creating a new component called `NumberField` if your not willing to allow `TextField` to render a number anymore.

**Comment by brayhoward** [comment]
### NumberField

```ts
import React from "react";
import { TextFieldProps, TextField } from "@shopify/polaris";

const isNumber = (val: any) => !Number.isNaN(val);
interface INumberFieldProps
  extends Omit<TextFieldProps, "type" | "value" | "onChange"> {
  onChange(value: number, id: string): void;
  value?: number;
}
export default function NumberField(props: INumberFieldProps) {
  const { onChange, value, ...restProps } = props;
  const valueAsString = isNumber(value) ? value!.toString() : "";

  return (
    <TextField
      {...restProps}
      type="number"
      value={valueAsString}
      onChange={(val, id) => {
        const parsedVal = val ? parseInt(val) : null;

        const isNumber = !!(parsedVal && !Number.isNaN(parsedVal));

        isNumber && onChange(parsedVal as number, id);
      }}
    />
  );
}

```

**Comment by ctrlaltdylan** [comment]
Yup confirming the same issue using v4.16.1

**Comment by mariomx3** [comment]
This doesn't seem to be fixed at all.  So we're expected to pass a string in and convert to a number everytime?

**Comment by s-prestele-tqgg** [comment]
4 years later and we are still converting strings to numbers. Is there really no other way!?
