### ISSUE TITLE
Revisiting Banner's withinContentContainer context

### ISSUE THREAD

**Issue by tleunen** [Shopify/polaris-react#2670]
## Feature request summary

This is a follow-up of a discussion that has been done here https://github.com/Shopify/polaris-react/issues/1303, and also on the internal slack ([here for reference](https://shopify.slack.com/archives/CQK6FNLJK/p1579110674060500)).

The idea is that the current implementation using a context works great to force a specific styling of the banner instead of letting the choice to the consumer. But this only work when the `Banner` is inside other Polaris components, such as the `Card` or the `Navigation`. This doesn't work well when the consumer doesn't use these components which set the right context value.

For example, every time we want to use the `Banner` with its specific "in content" style, we're forced to write something like this:
```jsx
<WithinContentContext.Provider value>
  <Banner status="critical" title={message} icon={CircleAlertMajorTwotone} />
</WithinContentContext.Provider>
```

This works, but this is far from being consumer friendly. One of the reason is because the context is currently "hidden". It's exported as `_SECRET_INTERNAL_WITHIN_CONTENT_CONTEXT`. But the other reason is because, as a consumer, it's looks weird to wrap the banner in a context like that instead of using a prop to set the specific style.

While I do understand the reasoning behind the context, I wonder if this should be more categorized as a "best practice" documented somewhere on the website. Like, "If you render a banner inside a `Card`, you should render the banner with this xxx specific prop", without enforcing it.

Any thoughts?

cc @danrosenthal @BPScott

**Comment by tleunen** [comment]
Keep this open.

**Comment by BPScott** [comment]
Probot. no.
