### ISSUE TITLE
Align button to the right

### ISSUE THREAD

**Issue by monodisco** [Shopify/polaris-react#2680]
## Issue summary

I need to align the submit button to the right

## Expected behavior

If I put in my browser something like float: "right", the button gets align to the right. That is the behavior that I'm looking for.

## Actual behavior

I have this code: 

            <Layout.AnnotatedSection
              title=""
              description=""
              style={{ float: "right" }}
            >
              <Button submit>Submit</Button>
            </Layout.AnnotatedSection>

And the Button keeps on the left side, the style has no effect.

How can I fix it?

**Comment by LauraAubin** [comment]
👋Hello!

Have you tried using the [`Stack`](https://polaris.shopify.com/components/structure/stack) component for this?

```
<Stack distribution='trailing'>
  <Button>foo</Button>
</Stack>
```

**Comment by monodisco** [comment]
Thanks!! That solved my problem
