### ISSUE TITLE
[Button] Split button example in documentation disappears on click

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react#2688]
## Issue summary

When clicking the connected disclosure on the split button example, the button disappears and no popover appears.

## Expected behavior

Clicking the connected disclosure should show the popover with menu items should appear.

## Actual behavior

Clicking the disclosure causes the button to disappear, however a click on the regular part of the button works fine. This appears to be due to not enough height being available for the popover to appear as everything works fine if you click the "Edit in sandbox" button and try it there.

![split_button](https://user-images.githubusercontent.com/48250/73475804-0ef34700-435f-11ea-860f-7360e59ae7eb.gif)

## Steps to reproduce the problem

1. Visit https://polaris.shopify.com/components/actions/button
1. Select "Split button" in the Examples dropdown.
1. Click the connected disclosure part of the button.

## Reduced test case

A reduced test case is on the examples page.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.12.0
- Browser: Google Chrome Version 79.0.3945.130
- Device: MacBook Pro
- Operating System: macOS Catalina 10.15.3

**Comment by chloerice** [comment]
Fixed by #2791
