### ISSUE TITLE
Contextual Save Bar - for App Bridge React

### ISSUE THREAD

**Issue by chrisandrewca** [Shopify/polaris-react#2697]
Polaris contextual save bar for App Bridge React. The docs recommend to use the app bridge flavour of the contextual save bar rather than the component provided in Polaris. The app bridge GitHub seems private so I thought I'd pop this here to contribute back to the community.

## Required components

> - Context from '@shopify/app-bridge-react'
> - ContextualSaveBar from '@shopify/app-bridge/actions'

## Props

List props and type declarations:

> - **isShown** (required): `boolean` - show or hide the bar
> - **save** (required): `array` - first a function to call when save is clicked followed by the functions dependencies
> - **discard** (required): `array` - first a function to call when discard is clicked followed by the functions dependencies

```
import { useContext, useEffect, useState } from 'react'
import { Context as ShopifyContext } from '@shopify/app-bridge-react'
import { ContextualSaveBar } from '@shopify/app-bridge/actions'

function useContextualSaveBar(save, discard) {
  const [shouldSave, setShouldSave] = useState(false);
  const [shouldDiscard, setShouldDiscard] = useState(false);

  useEffect(() => {
    if (shouldSave) {
      save[0]();
      setShouldSave(false);
    }
  }, [shouldSave, ...save]);

  useEffect(() => {
    if (shouldDiscard) {
      discard[0]();
      setShouldDiscard(false);
    }
  }, [shouldDiscard, ...discard]);

  return [() => setShouldSave(true), () => setShouldDiscard(true)];
}

const SaveBar = ({ isShown, save, discard }) => {

  const [onSave, onDiscard] = useContextualSaveBar(save, discard);
  const app = useContext(ShopifyContext);

  const create = () => {
    const options = {
      message: 'Unsaved changes',
      saveAction: {
        disabled: false,
        loading: false,
      },
      discardAction: {
        disabled: false,
        loading: false,
        discardConfirmationModal: true,
      },
    };
    return ContextualSaveBar.create(app, options);
  };

  const [saveBar] = useState(create());

  useEffect(() => {
    const saveUnsub = saveBar.subscribe(
      ContextualSaveBar.Action.SAVE,
      onSave
    );

    const discardUnsub = saveBar.subscribe(
      ContextualSaveBar.Action.DISCARD,
      onDiscard
    );

    return () => {
      saveUnsub();
      discardUnsub();
    };
  }, []);

  if (isShown) {
    saveBar.dispatch(ContextualSaveBar.Action.SHOW);
  } else {
    saveBar.dispatch(ContextualSaveBar.Action.HIDE);
  }

  return null;
}

export default SaveBar
```

**Comment by jeffblake** [comment]
I would love to see the contextual save bar as a react component!

**Comment by BPScott** [comment]
Hi folks, please raise this with the app-bridge maintainers at https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology

**Comment by coler-j** [comment]
There isn't any movement on the Bridge side of adding this component: https://community.shopify.com/c/Shopify-APIs-SDKs/Polaris-Component-for-Contextual-Save-Bar-App-Bridge/m-p/831699#M53914

**Comment by iainmcampbell** [comment]
Hi Coler, you can follow this issue on the new [App Bridge issue tracker](https://github.com/Shopify/shopify-app-bridge/issues/3) here on Github.
