### ISSUE TITLE
Please allow specifying `required` for TextField and Select

### ISSUE THREAD

**Issue by chaddjohnson** [Shopify/polaris-react#2699]
## Feature request summary

This would enable specifying whether a TextField is required via the `required` attribute. This would enable developers to choose to use either HTML5-based form validation or custom form validation.

While not everyone may agree with using this approach, I strongly feel it should be an option for developers using Shopify Polaris to rely on HTML5-based form validation. I feel that developers should be able to decide for themselves how they want to perform form validation.

For example, I am using [this hook](https://www.npmjs.com/package/react-html-form-validation-hook) to facilitate display of error messages by relying on [constraint-based validation](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation). This significantly reduces complexity and increases simplicity of large forms.

## Rationale

Forms can get pretty big. It's really nice to have the option of associating form validation rules directly with form elements via props such as `type`, `minLength`, `maxLength`, `min`, `max`, `pattern`, and `required`.

Shopify already supports all of the above props (for TextField) except `required`. It would be a very simple change to also pass this flag through to the element.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by chaddjohnson** [comment]
Here is my current workaround:

```jsx
import { useRef, useEffect } from 'react';
import PropTypes from 'prop-types';
import { TextField as PolarisTextField } from '@shopify/polaris';

const TextField = ({ required, ...props }) => {
  const ref = useRef();

  useEffect(() => {
    const element = ref.current;
    const input = element && element.querySelector('input');

    if (input) {
      input.required = required;
    }
  }, [ref, required]);

  return (
    <div ref={ref}>
      <PolarisTextField {...props} />
    </div>
  );
};

TextField.propTypes = {
  required: PropTypes.bool.isRequired
};

TextField.defaultProps = {
  required: false
};

export default TextField;
```

**Comment by chaddjohnson** [comment]
Rethinking this. Relying on `required` may be focusing too much on the DOM instead of data.

After studying [Formik](https://jaredpalmer.com/formik), [React Hook Form](https://react-hook-form.com/), and [@shopify/react-form](https://www.npmjs.com/package/@shopify/react-form), I understand how it makes sense to rely on validation rules separate from the component.

**Comment by bakura10** [comment]
@chaddjohnson , with Remix pushing more to use native browser feature, can this be re-considered?
