### ISSUE TITLE
401 When installing via npm

### ISSUE THREAD

**Issue by phsoul** [Shopify/polaris-react#2700]
## Issue summary

Cannot install polaris library via npm

## Expected behavior
Should install the library

Paste the results here:

```bash
npm install @shopify/polaris --save
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://packages.shopify.io/shopify/node/npm/@shopify%2fpolaris
```

**Comment by BPScott** [comment]
Looks like you're trying to pull polaris from our internal packagecloud instead of the public npm registry and you've not got the auth token to do that. Do `rm ~/.npmrc && dev up` to get a new auth token and to re-setup your registry
