### ISSUE TITLE
[AutoComplete] Clicking with a mouse takes focus away from the Textfield

### ISSUE THREAD

**Issue by dleroux** [Shopify/polaris-react#2701]
## Issue summary
When clicking using a mouse on one of the options in a multi-select AutoComplete, focus gets lost on the Textfield and remains on the input that was clicked.

![AutoComplete](https://user-images.githubusercontent.com/1229901/73662560-0a35d800-466a-11ea-9951-0ffd002df9ec.gif)

## Expected behavior

Focus remains in the Textfield and pressing the spacebar on an`active` option should select that option.

## Actual behavior

Focus gets stuck on the input that was clicked.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by ETatskyi** [comment]
this bug is still relevant, can anyone check it?
https://monosnap.com/file/lfpP6Qa9xl2a5Ya5G4UCtBadl4Uead
