### ISSUE TITLE
Date Picker not showing the month label and week label.

### ISSUE THREAD

**Issue by eebasadre20** [Shopify/polaris-react#2708]
Hi here,

I'm migrating our app to Shopify Polaris.
I use the Date Picker component but I'm having a problem as the month and week labels are not showing.

![image](https://user-images.githubusercontent.com/5001556/73715423-ded8e900-474e-11ea-8d50-ea78fb64e4ad.png)

https://codesandbox.io/s/flamboyant-bash-54tq4  - I follow the implementation given in the docs.

Any idea about this will be a great help.

Thanks

**Comment by AndrewMusgrave** [comment]
Hi, @eebasadre20 if you see lines `4` & `9` in `index.js` we're importing translations and passing them to `AppProvider`. Is it possible your application is missing that?

**Comment by eebasadre20** [comment]
> Hi, @eebasadre20 if you see lines `4` & `9` in `index.js` we're importing translations and passing them to `AppProvider`. Is it possible your application is missing that?

Yay! Totally, you're right @AndrewMusgrave .. Thanks!
