### ISSUE TITLE
[AutoComplete] Dropdown not closing in Modal

### ISSUE THREAD

**Issue by devchris** [Shopify/polaris-react#2710]
## Issue summary

The Dropdown of the autocomplete is not closing after choosing an item of the autocomplete inside a Modal.

## Expected behavior

After clicking on an item, the dropdown should automatically close.

## Actual behavior

The dropdown doesn't close and stays open.

## Steps to reproduce the problem

Implement an AutoComplete inside a Modal.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.13.1
- Browser: Chrome  79.0.3945.130
- Device: Macbook Pro
- Operating System: Catalina (macOS 10.15.1)

**Comment by sijad** [comment]
any news on this one?
We're facing same behavior.

**Comment by sijad** [comment]
this has been fixed in new version, probably by #2681

**Comment by ryanphuggins** [comment]
We are experiencing this issue in Polaris 5.10.1.

@sijad Is this still working as expected for you?

**Comment by sijad** [comment]
@ryanphuggins sorry, I'm not using this library anymore.
