### ISSUE TITLE
Expose and allow use of ref with TextField and Select components

### ISSUE THREAD

**Issue by chaddjohnson** [Shopify/polaris-react#2711]
## Feature request summary

Provide the ability to specify a `ref` prop for TextField and Select components (and possibly others).

## Rationale

Many form validation libraries rely on use of `ref` with input fields, yet Polaris does not provide a `ref` prop. This is problematic and makes form validation difficult, and our options for validating forms are limited.

I found and very much like the [react-form](https://github.com/Shopify/quilt/tree/master/packages/react-form) package which is part of [quilt](https://github.com/Shopify/quilt). It works well with Shopify Polaris and facilitates validation well -- in particular by allowing specification of validation rules as well as the use of spread to add props to components (e.g., `...fields.name` will add props such as `value`, `onChange`, `onBlur`, and others). I greatly appreciate Shopify providing this and hope Shopify continues to develop the package.

However, I still do feel it may make sense to at least consider exposing `ref` for `TextField` and `Select`, and perhaps also `Checkbox`, `RadioButton`, and others. This would facilitate use of other form validation libraries such as [Formik](https://jaredpalmer.com/formik), [React Hook Form](https://react-hook-form.com/), and others in Polaris-based apps.

Additionally, **I recommend Shopify extends its [Polaris documentation](https://polaris.shopify.com/) to cover form validation and mention the react-form quilt package**. It took me a while to discover that this package even exists, and I would have saved several days of work had I known.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by JamesDullaghan** [comment]
I would also +1 this as I ran into it lately and it's not very clear as to why this is the case!

Thanks for creating an issue that can hopefully be reopened!

**Comment by muchisx** [comment]
I need this !
