### ISSUE TITLE
Change color and arrow direction in DataTable

### ISSUE THREAD

**Issue by monodisco** [Shopify/polaris-react#2717]
## Issue summary
I have a DataTable that looks like this: 

![Captura de pantalla 2020-02-05 a las 20 49 34](https://user-images.githubusercontent.com/12752411/73877542-26e43280-4859-11ea-8d56-377e7356b63f.png)

and I want to show the data of the column "Diff" in green with arrow up when the percentage is positive and red with arrow down when percentage is negative

## Expected behavior

I need something like this, the image was taken from the shopify style guide:

![diff](https://user-images.githubusercontent.com/12752411/73877808-a6720180-4859-11ea-8602-5150f3de5c77.png)

## Actual behavior

Is there any way to show the data this way? I couldn't find a way to make it work...

**Comment by chloerice** [comment]
Hey @monodisco 👋 The values of the data in your `rows` arrays can be React nodes, check out this 
[code sandbox](https://codesandbox.io/s/custom-datatable-cell-content-3mic8).

**Comment by monodisco** [comment]
Thanks @chloerice !! That is exactly what I was lookng for :)
