### ISSUE TITLE
Shortcut actions for resource list are hidden even on a wide window

### ISSUE THREAD

**Issue by attaboy** [Shopify/polaris-react#2726]
## Issue summary
I opened https://polaris.shopify.com/components/lists-and-tables/resource-list#all-examples and looked at the "Resource list with item shortcut actions", and I was confused because I wasn't seeing any shortcut actions on hover. It turns out they are only visible if the resource list meets a minimum width, which because of the available space on the Polaris guide site, means that my window must be
about 1400px wide before the shortcut actions are visible at all.

1350px:
![image](https://user-images.githubusercontent.com/71433/73985250-b4329000-4908-11ea-8f1e-d5e4507d7a62.png)

1400px+:
![image](https://user-images.githubusercontent.com/71433/73985223-a3821a00-4908-11ea-86af-2a4e1ca5d455.png)

## Expected behavior
The shortcut actions should be visible at smaller sizes when possible and/or the documentation should be clearer. It says "are not shown on small screen devices", but with a 1350px-wide window, I am not obviously on a small screen! 🙂

**Comment by chloerice** [comment]
Hi @attaboy 👋 Sorry for the confusion! Because the playground is rendered in an `iframe`, in the case of the style guide the width of the playground is what affects the component media queries, not your device's screen width.

**Comment by attaboy** [comment]
@chloerice I understand why it’s happening—but maybe there could be a clearer explanation? I honestly thought something was broken at first.

**Comment by tkejr** [comment]
Facing same issue
