### ISSUE TITLE
[Color system] Decorative colors

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react#2730]
Decorative colors and how we use them in the system need to be explored.

We currently support decorative colors for avatars but this will not scale to more expressive areas like Merchant onboarding to the product or the introduction of a new feature.

Marketing already has a system around how to use decorative colors. Let's explore this as a potential option and how it might work with our color system.

@jessebc @martenbjork @mirualves @see-mack @kathleenbabin @danrosenthal

**Comment by danrosenthal** [comment]
This still needs attention
