### ISSUE TITLE
Footer help 

### ISSUE THREAD

**Issue by raghu-c** [Shopify/polaris-react#2732]
## In which page can we use footer help

![1](https://user-images.githubusercontent.com/59169757/74127019-6fa43e80-4bff-11ea-8299-c2f36f1c7c74.jpg)

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by chloerice** [comment]
Hi @raghu-c 👋Any page can use this component. See the [component documentation](https://polaris.shopify.com/components/navigation/footer-help) for best practices and content guidelines.

**Comment by raghu-c** [comment]
> Hi @raghu-c 👋Any page can use this component. See the [component documentation](https://polaris.shopify.com/components/navigation/footer-help) for best practices and content guidelines.

Thanks :)
