### ISSUE TITLE
Text field of type 'number' expects a string!!!

### ISSUE THREAD

**Issue by AKarmanov** [Shopify/polaris-react#2749]
## Issue summary

When you create a text field of type 'number' it expects a string which is an enormous contradiction.

## Expected behavior
One would expect a number field to take a number and not a string, it was like that in previous version. So a big step back happened, which simply doesn't make sense. If HTML inputs have an option to be number only so must your input fields. A string in a number field is not an option in 2020!  

It messes up your program a lot especially if you need those numbers to be actual numbers in case you do further processing of the data (I now have to parse it on way in and on way out, which is stupid extra work!!!).

## To reproduce

Go [here](https://codesandbox.io/s/epic-feather-uq0or) (official documentation) and change value in 'useState' to a number, refresh and the input doesn't show the number.

## Version 
4.13.1

**Comment by BPScott** [comment]
Hi @AKarmanov,

Please see https://github.com/Shopify/polaris-react/issues/2664#issuecomment-579530825 for some context why TextField only accepts a string - and has done so since its creation according to its TypeScript types.

**Comment by AKarmanov** [comment]
> Hi @AKarmanov,
> 
> Please see [#2664 (comment)](https://github.com/Shopify/polaris-react/issues/2664#issuecomment-579530825) for some context why TextField only accepts a string - and has done so since its creation according to its TypeScript types.



> Hi @AKarmanov,
> 
> Please see [#2664 (comment)](https://github.com/Shopify/polaris-react/issues/2664#issuecomment-579530825) for some context why TextField only accepts a string - and has done so since its creation according to its TypeScript types.

I have code working (an actual app) with previous version where I pass a number.
