### ISSUE TITLE
Displaying Incorrect Suggested Tags in Multiple tag autocomplete

### ISSUE THREAD

**Issue by takashi-osako** [Shopify/polaris-react#2764]
## Issue summary
Displaying incorrect Suggested Tags while typing in text field

https://codesandbox.io/s/priceless-bouman-plndu?fontsize=14&hidenavigation=1&theme=dark

## Expected behavior
Displaying string match Suggested Tags
![image](https://user-images.githubusercontent.com/3707576/75002801-a6fec080-5433-11ea-8c5d-bf55fac40968.png)

## Actual behavior
Displaying unrelated tag
![image](https://user-images.githubusercontent.com/3707576/75002817-b716a000-5433-11ea-8a9b-cea3b73052eb.png)

## Steps to reproduce the problem

1. this may be re-produceable when the element is loaded first time.  Multiple try may not show the symptom.  (reload or reload frame when it is necessary)
1. start type "e" then "f"

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.13.1
- Browser: Chrome Version 80.0.3987.87
- Device: 
- Operating System: mac OS Mojave version 10.14.6

```bash

```

**Comment by alllx** [comment]
Hey team I have the same issue with single selected option of `Autocomplete` component. It looks like `Autocomplete` component is mutating passed options to it. I added temporary fix to use `_.deepClone` every time I pass options to `Autocomplete`.  You can check the behaviour in this brunch : https://github.com/Shopify/handshake-supplier-web/pull/565 by removing `deepClone` and typing and deleting search.
