### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by cstffx** [Shopify/polaris-react#2767]
After read some previous issues I am a lite confuse. if I want to use Polaris outside of Shopify apps will I need to change colors, borders and fonts? Or I can use this repository as is.

**Comment by yourpalsonja** [comment]
You’ll need to modify Polaris so that the app looks like your own, not ours. Where did your initial confusion come from, we should probably make sure it's clear for everyone.

**Comment by yourpalsonja** [comment]
@cstffx are you planning on using Polaris to build a Shopify-related app, or is this for outside use?

**Comment by TheMisir** [comment]
I'm also using Polaris as a UI kit for a project that's not related to Shopify.

**Comment by nunomaia** [comment]
> use the Polaris Design Guidelines solely to develop, test, and distribute software applications, websites, and interfaces that interoperate or integrate with Shopify’s hosted commerce platform available via www.shopify.com

Allowing Polaris to be used in open source project that not related to Shopify’s, would be a amazing.

**Comment by kaelig** [comment]
Thank you for your question, @cstffx, as well as for your comments @nunomaia and @TheMisir – At the moment, Polaris’s license doesn't allow using Polaris outside of a Shopify-related project, whether the styling is customized or not.
