### ISSUE TITLE
[Tag] Expose an optional onClick handler

### ISSUE THREAD

**Issue by posth** [Shopify/polaris-react#2772]
## Feature request summary

- To expose an `onClick` optional prop on the `Tag.tsx` [component](https://github.com/Shopify/polaris-react/blob/master/src/components/Tag/Tag.tsx).
- To display a `disabled` style on a tag that is clickable but disabled.

## Rationale

Consumers can add more functionality to the **Tag** component and not be only limited to remove tags.

For example, scenario:

| ![tagsSelectionExample](https://user-images.githubusercontent.com/5506721/75186790-a9ed0000-5716-11ea-85d2-3f7b605bfef5.gif)|
|---|

## Possible implementation

Because the `onRemove` is already exposed as an optional prop, we'd have to prioritize `onRemove` as the **Tag** render if both `onClick` and `onRemove` are passed.

If only `onClick` is passed, it'll render this new **Tag** render, with a possible greyed out un-clickable disabled state.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by chloerice** [comment]
Hey @posth 👋 Thanks for raising this! I think it totally makes sense to expand the API of `Tag` 💯. 

Right now the current API assumes that tags are `removable`, so first instincts would be to:

- add a boolean `removable` prop (@default true) that conditionally renders the remove button
- update the `onRemove` prop description (commented in props interface in the `Tags.tsx` file) to specify that this callback is called on click or keypress of the remove button rendered when `removable` is true.
- add an `onClick` prop described as a callback called on click or keypress of the tag content container.

**Comment by posth** [comment]
@chloerice I've linked a PR and I'll tag you on it 😃
