### ISSUE TITLE
TextField: onChange Event: newValue not found in case of hyphen, plus and 'e', when type is number

### ISSUE THREAD

**Issue by manish-nx** [Shopify/polaris-react#2786]
## Issue summary
The onChange prop of TextField is not returning any updated value when type prop is "number" and entered value is either hyphen (-), plus (+) or 'e' character.

It is expected that the TextField component will accept hyphen (-), plus (+) or 'e' character even when the input type is "number". But, what if I want these values from the onChange prop?

The onChange prop of TextField is not returning any updated value when type prop is "number" and entered value is either hyphen (-), plus (+) or 'e' character.

## Expected behavior
The onChange prop of TextField is should return any updated value when type prop is "number" and entered value is either hyphen (-), plus (+) or 'e' character.

It should return the updated value, even if the entered value is either hyphen (-), plus (+) or 'e' character. If we are allowing the user to enter these values, then we should also get the updated value.

## Actual behavior
The onChange prop of TextField is should return any updated value when type prop is "number" and entered value is either hyphen (-), plus (+) or 'e' character.

## Steps to reproduce the problem

1. Use the TextField component with type="number" prop
1. Enter either hyphen (-), plus (+) or 'e' character
1. The onChange prop is not returning any updated value

## Reduced test case

[CodeSandbox Link](https://codesandbox.io/s/funny-mestorf-2nrib)
Inside App.js
Enter either hyphen (-), plus (+) or 'e' character in the TextField and check the console logs.
No updated value is printed in logs

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: 4.10.0
- Browser: Chrome 80.0.3987.122 (Official Build) (64-bit)
- Device:  MacBook Pro A1398 
- Operating System:  macOS version 10.14.6 (32-bit) 

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.69 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
Browsers:
    Chrome: 80.0.3987.122
    Firefox: 73.0.1
    Safari: 12.1.2
npmPackages:
    @shopify/polaris: 4.10.0 => 4.10.0
    react: 16.12.0 => 16.12.0
    react-dom: 16.12.0 => 16.12.0
```

**Comment by mkatrenik** [comment]
I will also add, that TextField[type=number] doesn't allow to enter comma as decimal point separator, which is valid at least in most of europe.

**Comment by robgoodberry** [comment]
Came across this behaviour myself. Assuming it was a Polaris bug based on finding this, I set up a regular input like:

```
<input type='number' value={quantity} onChange={(e) => {handleEditingItemQuantityChange(e.target.value)}} />
```

and experienced the same thing, at which point I found https://stackoverflow.com/questions/52003841/why-doesnt-event-target-value-include-and-e-for-number-inputs

Just thought I would comment.. I think this might not be a Polaris thing 🤷‍♂️
