### ISSUE TITLE
Should Autocomplete reverse options when popover positioned above?

### ISSUE THREAD

**Issue by sambostock** [Shopify/polaris-react#2797]
## Issue summary

The `<Autocomplete />` component renders a search result list when values are typed in. It is likely that the implementer would order these results by relevance. This works well when the Combobox Popover is displayed **below**:

![image](https://user-images.githubusercontent.com/8219340/75572606-1a529480-5a29-11ea-85d1-dff0fe633047.png)

The most relevant result is rendered closest to the input field.

## Expected behavior

The ordering of the results should be reversed, such that the most relevant result is rendered closest to the input field even when the Combobox Popover is rendered **above**:

![image](https://user-images.githubusercontent.com/8219340/75572701-466e1580-5a29-11ea-9332-ba69f1f69011.png)

## Actual behavior

The results are displayed from top to bottom, regardless of if the Combobox Popover is **above** or **below**, resulting in the most relevant result being displayed furthest away from the input, when positioned **above**.

![image](https://user-images.githubusercontent.com/8219340/75572726-5128aa80-5a29-11ea-9e91-ff9f1a03d3e7.png)

## Steps to reproduce the problem

1. Use `<Autocomplete />` to display search results by relevance
1. Force to position `above`, either through `preferredPosition` prop, or by placement of the component in the view port
1. Notice result ordering is awkward, and most relevant result is furthest.

## Reduced test case

[This CodeSandbox](https://codesandbox.io/s/polaris-autocomplete-above-vs-below-p6t9g) provides an example of various positions and orderings.

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 4.14.0
- Browser: Chrome
- Device: MacBook Pro
- Operating System: macOS

**Comment by AndrewMusgrave** [comment]
cc/ @dleroux

**Comment by dleroux** [comment]
I don't think that is the case. If we look at it from an accessibility perspective, keyboard interactions should remain the same. The down arrow should be bringing the user to the most relevant entry, in both cases, this would be 123. Clicking down arrow on the example with the popover at the top and have the focus go to the least relevant entry could lead to come confusion for keyboard users.

**Comment by chloerice** [comment]
> I don't think that is the case. If we look at it from an accessibility perspective, keyboard interactions should remain the same. The down arrow should be bringing the user to the most relevant entry, in both cases, this would be 123. Clicking down arrow on the example with the popover at the top and have the focus go to the least relevant entry could lead to come confusion for keyboard users.

^ 💯 The keyboard will still navigate the option list top to bottom regardless of its placement above or below the textfield.
