### ISSUE TITLE
Feature request : Adding colors to filter tags for Filters component

### ISSUE THREAD

**Issue by Prabhashishsingh** [Shopify/polaris-react#2812]
## Feature request summary:

Making it possible to control/configure the colours to filtered tags for Filters component can help convey different meaning or value each tag holds for the user

Example:

<img width="1346" alt="Screen Shot 2020-03-05 at 7 27 09 PM" src="https://user-images.githubusercontent.com/57496850/76039214-bbee5000-5f19-11ea-89ec-783240cd346f.png">

In the above example,
Colors are used for tags under 'source' to distinguish the different Data Assets each tagged source holds for data scientists. 
- Starscream refers to 'modelled data'
- Longboat refers to 'raw data'
- Monorail also refers to 'raw data'
- Mode refers to 'report'

Each of these different data sources hold different kind of data assets which in turn hold very different meaning for the data scientists. Colored tags can make them easily discernable.

This is a use-case for an internal tool we are building to centralize all data assets within Shopify and hope this function can be used by other teams as well.

**Comment by chloerice** [comment]
Cc-ing @sarahill @danrosenthal for design and color role thoughts as I can see the API for this going two ways: adding a `status` prop like on `Badge`, or adding a `color` prop like on `Icon` (I lean toward the flexibility of the latter).

**Comment by danrosenthal** [comment]
My preference would be to keep this component pretty agnostic about color, and instead opt for using the theme provider to theme the component as needed.

Using the code below in the `Playground`, **with New Design Language turned on** gets very close to the intended results. Consumers could even have their own local component, which just served a `Tag` wrapped in a `ThemeProvider`. It could take a `color` prop and pass that prop on to the included theme provider, and there you have it. Or you could offer a defined API of colors, and they could still work the same way.

```tsx
import React from 'react';
import {Page, Stack, Tag, ThemeProvider} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      <Stack>
        <ThemeProvider theme={{colors: {secondary: '#F4E48A'}}}>
          <Tag>Starscream</Tag>
        </ThemeProvider>
        <ThemeProvider theme={{colors: {secondary: '#A4BFFF'}}}>
          <Tag>Longboat</Tag>
        </ThemeProvider>
        <ThemeProvider theme={{colors: {secondary: '#50FD91'}}}>
          <Tag>Longboat</Tag>
        </ThemeProvider>
      </Stack>
    </Page>
  );
}
``` 

| 🌈 |
|-|
|![Screen Shot 2020-03-11 at 2 22 33 PM](https://user-images.githubusercontent.com/1403188/76450233-d144fd80-63a3-11ea-9378-02f3c0374784.png)|

**Comment by chloerice** [comment]
I didn't realize the `ThemeProvider` could theme components that weren't listening for specific key in the theme object, this is super cool ✨
