### ISSUE TITLE
Components using Portal when a child of a nested ThemeProvider can have missing colors

### ISSUE THREAD

**Issue by tmlayton** [Shopify/polaris-react#2816]
Nested `ThemeProviders` rely on inheritance by only adding the color variables that need to be overwritten in an effort to avoid DOM bloat. This works great except for portals which grab the nearest theme context which may only have a partial or missing color palette.

There is also a possible undefined CSS `color` prop on the portal node because `textColor` in context can be `undefined`

![image](https://user-images.githubusercontent.com/344839/76153862-6a63d380-6087-11ea-9aa8-f5c1b7b07dae.png)

**Comment by danrosenthal** [comment]
@WillsonSmith this looks like the problem you've run into with making a dark modal.

**Comment by WillsonSmith** [comment]
Oh yeah I did run into this. Noticed last week that it was affecting _all_ portals and not just the modal I was working on. Didn't have much time to look into it. 👀

**Comment by tmlayton** [comment]
A few options: 

1. Keep both a cascaded palette and local palette in context by merging the the local (and possibly partial) palette with the ancestor’s palette. That way there is always a complete and correct palette to pass to the portal and continue to rely on the cascade for rest of the DOM to avoid 200+ variables on every theme provider node or
1. We do just that, put every variable on every theme provider node since perhaps the negative side effects are negligible.
1. Create a `StylePortal` for the `ThemeProvider` to write CSS variables in a style block scoped to a unique class for that given `ThemeProvider` node. This way regular portal containers just have class names added and same with the `ThemeProvider` nodes. The approach for which classes have which variables could follow option 1 or 2.

```html
<html>
  <head>
    <style data-portal-id="overrides">
       .overrides {
         --p-none: none;
         /* and so on */
       }
    </style>
    <style data-portal-id="theme1">
       .theme1 {
         --p-background: black;
         --p-text: white;
         /* and so on */
       }
    </style>
    <style data-portal-id="theme2">
       .theme2 {
         --p-text: gray;
       }
    </style>
  </head>
  <body>
    <div class="overrides theme1"> <!-- AppProvider -->
      <button>Popover 1</button>
      <div class="theme2">
        <button>Popover 2</button>
      </div>
    </div>
    <div data-portal-id="1" class="overrides theme1"></div>
    <div data-portal-id="2" class="overrides theme1 theme2"></div>
  </body>
</html>
```
