### ISSUE TITLE
Redirect to the theme editor?

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris-react#2823]
## Issue summary

I am trying to create a redirect to the theme editor, by using the following code:

```
action={
              {
                content: 'Add a feed to my store',
                onAction: () => redirect.dispatch(Redirect.Action.ADMIN_PATH, `/themes/${this.props.theme.id}/editor`)
              }
            }
```

## Expected behavior

I would expect the merchant to be redirected to the theme editor.

## Actual behavior

While this actually redirect to the theme editor, the theme editor hangs up and does not show any content. Apparently, this may be due to this error:

<img width="1557" alt="Capture d’écran 2020-03-11 à 00 02 50" src="https://user-images.githubusercontent.com/1198915/76326279-c3ec2c80-632b-11ea-86a2-1a07bab2e1ad.png">

Is there any way to create such a link inside an embedded app? :)

**Comment by vividviolet** [comment]
@bakura10 can you confirm that accessing the them editor directly works without errors? The App Bridge redirect action doesn't do anything else besides updating the browser url to the provided url

**Comment by bakura10** [comment]
Yes, it does by going directly to the same page with a full page reload instaed of the redirect. Can't really explain why :p.
