### ISSUE TITLE
Feature request : making visibility of "More Filters" button in Filters component configurable

### ISSUE THREAD

**Issue by karengabrielyan** [Shopify/polaris-react#2826]
## Feature request summary

Making it possible to control/configure the visibility of the More Filters button in Filters component.

![image](https://user-images.githubusercontent.com/23406394/76444709-ba4ddd80-639a-11ea-9106-161aa024cbd7.png)

## Rationale

We are using Polaris components in Shopify-internal applications which assume the screen size is fairly large.
Some of the filters we'd like to have will include multiple control properties. And in such case it's beneficial to not have the "More Filters" button show up all the time.

Would be great to have a prop which controls the default visibility of that button.
Maybe have it show up if the width of Filters component goes below some threshold, but hide it when the control is wide enough?

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by rickitan** [comment]
Hi @karengabrielyan, Have you started working on this issue? If not, I'll tackle it.

**Comment by karengabrielyan** [comment]
> Hi @karengabrielyan, Have you started working on this issue? If not, I'll tackle it.

Hi @rickitan , no I haven't started yet, would only get to it in a week. Please, feel free to take it.

**Comment by karengabrielyan** [comment]
Thank you folks for accepting and delivering this feature!!
