### ISSUE TITLE
List page issue in polaris.

### ISSUE THREAD

**Issue by mani2889** [Shopify/polaris-react#2830]
We have a photos list page in the project. We get the page alignment issue. If we have 5 images, We want to strict four images in the first row and the 
![photos_123](https://user-images.githubusercontent.com/23354948/76497545-33176d00-6461-11ea-8e69-9cae84da7d7e.png)
remaining 1 image in the second row.

If we put down the second image. It is taking the full width. so the last image expands with full width.

**Comment by BPScott** [comment]
Stack is an abstraction over flexbox, and that's how flexbox works. I suggest rolling your own css grid solution to lay these images out. https://codepen.io/BPScott/pen/EXdJrK is a example of how to do that
