### ISSUE TITLE
Navigation selects active item via startsWith(item.location) instead of equality check 

### ISSUE THREAD

**Issue by balupton** [Shopify/polaris-react#2850]
## Issue summary

Taking the example of https://polaris.shopify.com/components/navigation/navigation and updating the urls so they are distinct results in https://codesandbox.io/s/naughty-ramanujan-4oyun?fontsize=14&hidenavigation=1&theme=dark

``` javascript
import React from 'react';
import {Navigation} from '@shopify/polaris';
import {HomeMajorMonotone, OrdersMajorTwotone, ProductsMajorTwotone} from '@shopify/polaris-icons';

export default class App extends React.Component {
  render() {
    return (
      <Navigation location="/orders">
  <Navigation.Section items={[{
    url: '/',
    label: 'Home',
    icon: HomeMajorMonotone
  }, {
    url: '/orders',
    label: 'Orders',
    icon: OrdersMajorTwotone,
    badge: '15'
  }, {
    url: '/products',
    label: 'Products',
    icon: ProductsMajorTwotone
  }]} />
</Navigation>
    );
  }
}
```

## Actual behavior

Which incorrectly activates both `Home` and `Orders`:

<img width="363" alt="Screen Shot 2020-03-17 at 9 15 52 pm" src="https://user-images.githubusercontent.com/61148/76846359-7d02b780-6894-11ea-82d0-49d41172ae42.png">

So it seems that the location check is done via a `navigationLocation.startsWith(item.location)` rather than an equality check

## Expected behavior

Home to be selected and nothing else.

## Reduced test case

https://codesandbox.io/s/naughty-ramanujan-4oyun?fontsize=14&hidenavigation=1&theme=dark

## Specifications

- Are you using the React components? (Y/N): y
- Polaris version number:  4.16.0
- <img width="369" alt="Screen Shot 2020-03-17 at 9 19 24 pm" src="https://user-images.githubusercontent.com/61148/76846672-fbf7f000-6894-11ea-82f0-9fd87df1a2e0.png">
- Browser: Chrome Version 80.0.3987.132 (Official Build) (64-bit)
- Device: Macbook
- Operating System: macOS Catalina

**Comment by mc2259** [comment]
I am facing the same issue. Can someone please post the solution here ?
