### ISSUE TITLE
Expose colors over context and create hook

### ISSUE THREAD

**Issue by carysmills** [Shopify/polaris-react#2851]
## Feature request summary
Re: [this Slack conversation](https://github.com/Shopify/polaris-ux/issues/408). Insights, Plus and other teams using data viz and other custom components will need access to the new design system colors in JavaScript, in order to pass them to some other components, including HighCharts, d3 implementations, Polaris Viz and possibly other kinds of components.

The colors could be added to the context that the Theme Provider provides and exposed as a hook, to be consumed directly or using an HOC.

The alternative would be to use `useContext(ThemeContext)` where consumers need the colors, however this won't be possible directly in some components such as those from Polaris Viz, since Polaris is not a dependency of Polaris Viz.

cc @danrosenthal @thomfoolery 

## Rationale
This will give a unified approach to implementing the new color system in React.

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by danrosenthal** [comment]
Will RGB strings (`rgba(92, 95, 98, 1)`) be acceptable as colors, or will you need another color type for this?

**Comment by BPScott** [comment]
we already have a useTheme() hook that we use internally - https://github.com/Shopify/polaris-react/blob/master/src/utilities/theme/hooks.tsx.

I'm not sure currently if we want to just expose that publicly or only expose something else. I guess something else that only handles colors as we wouldn't want to expose the logo and other stuff atm.

**Comment by carysmills** [comment]
@danrosenthal RGB or hex codes would be great for this!

**Comment by jprosevear** [comment]
Would like to be able to access the logo to insert in sign in and sign up pages

**Comment by carysmills** [comment]
Just wanted to followup on this since the new design language rollout is coming up. Has there been any progress?

**Comment by BPScott** [comment]
FAO @alex-page / @kyledurand

**Comment by alex-page** [comment]
@carysmills this isn't on our roadmap. I am going to close this but if there is any functionality that is blocking with the new design language let me know.
