### ISSUE TITLE
Resource Picker Documentation - Make deprecated status more apparent

### ISSUE THREAD

**Issue by brettbullock** [Shopify/polaris-react#2857]
## Feature request summary
The deprecation status of the ResourcePicker component should be more apparent to the reader by showing this status within the loading window of the page.

We are deprecating ResourcePicker but at first glance (and even with some scrolling down to see the full example and some props), the deprecation statement doesn’t catch the readers eye. 
https://polaris.shopify.com/components/overlays/resource-picker#navigation

## Rationale
This will inform readers quicker (and with a higher % of success) of the deprecated status, the rationale, and the suggested component moving forward.

**Comment by nickatrokit** [comment]
It would be nice to know what is replacing it? How can users select products in the future?

**Comment by kaelig** [comment]
As of Polaris React 5.0, please use this component instead: https://shopify.dev/tools/app-bridge/react-components/resourcepicker

Closing this issue as v5 is coming soon.
