### ISSUE TITLE
How to add a button in the embedded app menu section?

### ISSUE THREAD

**Issue by raghu-c** [Shopify/polaris-react#2858]
## Issue summary
How to add a button in the embedded app menu section?

## Expected behavior
The button should be added to the embedded app menu section. 
![embedded-app](https://user-images.githubusercontent.com/59169757/77042214-4e462780-69e1-11ea-8478-709d01e89e48.jpg)

## Actual behavior
There is no option to add a button in the backend part. The reference image attached. 
![menu](https://user-images.githubusercontent.com/59169757/77042143-31115900-69e1-11ea-8d26-22488e9a7ea8.jpg)

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by mbaumbach** [comment]
You can accomplish this with the `TitleBar` component from the `@shopify/app-bridge-react` project.

**Comment by raghu-c** [comment]
Thanks, @mbaumbach. It's working

**Comment by prats8m2** [comment]
> You can accomplish this with the `TitleBar` component from the `@shopify/app-bridge-react` project. See https://shopify.dev/tools/app-bridge/react-components/titlebar

I am using title bar Component to show actions on my embedded app.I have two issues.
1: I want to change the "Actions" text to "Settings".(If i am giving title to actions groups it is showing under the dropdown action).
2: I want two secondary button, but if I am adding more button in secondaryAction it got added to ActionsGroup dropdown.

Here is my Code:
 ```
<Container>
        <div className="App">
          <AppProvider>
            <Provider
              config={{
                apiKey: API_KEY,
                shopOrigin: shopOrigin,
                forceRedirect: true
              }}
            >
              <Page>
                <TitleBar
                  title="My App using up-to-date code"
                  breadcrumbs={[{ content: "Breadcrumb" }]}
                  primaryAction={{ content: 'Foo', url: '/foo' }}
                  secondaryActions={[{ content: 'Bar3', url: '/bar' }]}
                  actionGroups={[{ title: 'Settings', actions: [{ content: 'Baz2', url: '/baz' }] }]}
                />
              </Page>
            </Provider>
          </AppProvider>
        </div>
      </Container>

```
Please suggest how can I solve my issue.
