### ISSUE TITLE
Improve Navigation & Related Utilities

### ISSUE THREAD

**Issue by 8eecf0d2** [Shopify/polaris-react#2866]
## Feature request summary

Currently there is no well documented way for handling browser navigation in a React Embedded App, especially navigation between the Embedded App and Shopify Admin. Below is a simple list of what I think makes for good browser navigation within the context of a React Embedded App.

 - Native Anchor tags (eg, `<a />`)
 - Keyboard Shortcut support (eg, <kbd>Meta</kbd>+<kbd>Click</kbd> opens in new tab)
 - Transparent API for navigating the Shopify window (parent document)
 - Browser history (eg, Back / Forwards)

## Rationale

I would categorise this feature request as **_"a basic browser right"_**, in this instance being able to navigate as the browser intended. I think we can all agree that websites which do not support <kbd>Meta</kbd>+<kbd>Click</kbd> and or "copy link address" are at the very least disappointing to deal with.

The types of Embedded Apps I (and many others) develop are used daily by hundreds if not thousands of support staff and improving navigation would significantly improve their efficiency, workflows and reduce frustration, all while being a minor technical issue for us to overcome.

I also see this as an accessibility issue, I suppose it might not be categorised in that way but considering all of the accessibility related work I see in here I'm surprised this hasn't got a mention yet.

## Partial Solution

The guts of this is already possible, below is the approach I use to fix this issue (more or less):

**`component/link.tsx`**
```typescript
import * as React from "react";

import { useShopifyDomain, useShopifyNavigation } from "hooks/shopify";

export type LinkProps = {
  type: "admin" | "app";
  path: string;
};

export const Link: React.FunctionComponent<LinkProps> = (props) => {
  const shopifyNavigation = useShopifyNavigation();
  const shopifyDomain = useShopifyDomain();

  const basepath = props.type === "admin" ? "/admin" : `/admin/apps/${SHOPIFY_APP_NAME}`;

  const url = new URL(`https://${shopifyDomain}${basepath}${props.path}`);

  const handleClick = (event: React.MouseEvent<HTMLAnchorElement>): void => {
    if (!event.metaKey) {
      event.preventDefault();
      shopifyNavigation(props.type, props.path);
    }
   // ... other key combinations ...
  };

  return (
    <a
      href={url.href}
      onClick={handleClick}
    >
      {props.children}
    </a>
  );
};
```

**`hooks/shopify.ts`**
```typescript
import * as React from "react";
import { useHistory } from "react-router-dom"; // can be any router library with History API support
import { Context } from "@shopify/app-bridge-react";
import { Redirect, History } from "@shopify/app-bridge/actions";

export const useShopifyDomain = (): string => {
  const url = new URL(window.location.ancestorOrigins[0]); // is there a better way?

  return url.hostname;
};

export const useShopifyNavigation = (): useShopifyNavigation.NavigateFunction => {
  const appBridgeContext = React.useContext(Context);
  const shopifyRedirect = Redirect.create(appBridgeContext);
  const shopifyHistory = History.create(appBridgeContext);
  const routerHistory = useHistory();

  const navigate: useShopifyNavigation.NavigateFunction = (type, path) => {
    switch (type) {
      case "admin":
        return shopifyRedirect.dispatch(Redirect.Action.ADMIN_PATH, path);
      case "app":
        shopifyHistory.dispatch(History.Action.PUSH, path);
        return routerHistory.push(path);
    }
  };

  return navigate;
};
```

This works by always generating the full url for a given `<Link />` and always using the `.myshopify.com` domain.

When an `"app"` link is used the `useShopifyNavigation` hook will call the Shopify History and Embedded App History (no full-page load.)

When an `"admin"` link is used the `useShopifyNavigation` hook will call the Shopify Redirect (no full-page load.)

When a key is pressed and a link is used we can listen for that and let the `<Link />` component's `<a />` tag natively navigate the browser.

An additional benefit of using the `.myshopify.com` domain within the `<Link />` component is that links to the Embedded App which open in a new tab or window go directly to the Embedded App within Shopify and **not** the Embedded App's host which with `forceRedirect` would redirect them back to the Embedded App in Shopify.

The solution above doesn't fix everything, numerous Polaris components (eg, `<ResourceList.Item />`) do not allow for this behaviour because they're using "dumb" navigation components that do not play nicely with History API's or use `<a />` tags.

## Related Notes

I have read [the docs](https://shopify.dev/tools/app-bridge/react-components/client-router) for the `useClientRouting` and related APIs from App Bridge React but it doesn't solve this issue and also I've found isn't worth using when trying to solve this issue.

The documentation also didn't make a whole lot of sense to me:

> If your app uses client-side routing, such as React Router, then you need to override this behaviour to avoid unnecessary full-page reloads.

This isn't true and a weird statement to make, you don't need it to avoid full-page reloads within the Embedded App frame.

The documentation also doesn't provide an example with any actual routing, just routers that point to other routers, this seems limited.

---

_Thanks for reading and thanks for all the great work on Polaris, it's an awesome library! 🌻_

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by resistorsoftware** [comment]
HELLO!

I am pretty new to React and I am now at the point where I need a simple link in my simply resource item. eg... user clicks link and goes to /admin/collections/123456789

From what I can tell, this is not possible with Polaris, React and App Bridge React. 

SUCH A SIMPLE THNG... yet I have ZERO chance of making that link, as it seems impossible to d without being a well-seasoned brain in all this. 

The above code seems like it addresses my screaming need. But I am not used to Typescript, that looks like more years applied just to return to this point in time of, I CANNOT MAKE A LINK... 

Could someone kindly make a CODEPEN of how to make a link with Polaris in an Emdedded App... 

PLEASE!!!
