### ISSUE TITLE
Tooltip with long text seems t have no padding-bottom

### ISSUE THREAD

**Issue by sylvhama** [Shopify/polaris-react#2869]
## Issue summary

[Tooltip](https://polaris.shopify.com/components/overlays/tooltip) with long text seems t have no padding-bottom.

![Screen Shot 2020-03-23 at 3 19 45 PM](https://user-images.githubusercontent.com/5626729/77354835-da29bd80-6d19-11ea-9ac7-1a021cf32d50.png)

You can open this [codesandbox](https://codesandbox.io/s/goofy-cdn-w2fbq) on Chrome or Safari to reproduce the bug.

**Comment by thayannevls** [comment]
Hello @sylvhama, there's someone working on this issue? I would like to try to solve this one :smile:

**Comment by sylvhama** [comment]
@thayannevls feel free, btw I've noticed that it might not be just a padding issue, it seems that long texts will be cut :/

**Comment by thayannevls** [comment]
This is the desired behavior or can I change it to not be cut?

**Comment by sylvhama** [comment]
This is just my opinion, I am not part of Polaris team. I guess the goal is to not let people having giant tooltips. But I would rather have no limit, it should be up to each developer to be responsible when using it.

**Comment by thayannevls** [comment]
I agree @sylvhama. I removed the limit and it's working just fine but I will wait someone from the core team to comment on this issue

**Comment by sylvhama** [comment]
You can open a PR so someone will review it and they / you can decide to merge it or not.
