### ISSUE TITLE
Number textfield got empty when upgrading to 4.16.1, when I tried 4.5.0, it is working normally

### ISSUE THREAD

**Issue by thomas-avada** [Shopify/polaris-react#2877]
Please look at this image: http://prntscr.com/rpahx9

**Comment by BPScott** [comment]
This is by design in order to ensure consistency between the `value` prop and the argument that the function specified in the `onChange` prop receives.  Please see https://github.com/Shopify/polaris-react/issues/2664#issuecomment-579530825 for more information.
