### ISSUE TITLE
FavoriteMajorMonotone and FavoriteMajorTwotone missing from @shopify/polaris-icons

### ISSUE THREAD

**Issue by josharmitage** [Shopify/polaris-react#2889]
FavoriteMajorMonotone and FavoriteMajorTwotone missing from @shopify/polaris-icons
(https://polaris-icons.shopify.com/?icon=FavoriteMajor)

`export 'FavoriteMajorMonotone' was not found in '@shopify/polaris-icons'`

Versions:
@shopify/polaris: 4.16.0
@shopify/polaris-icons: 3.10.0

**Comment by BPScott** [comment]
For the record, looks like they're there to me https://unpkg.com/browse/@shopify/polaris-icons@3.10.0/dist/index.mjs#L245
