### ISSUE TITLE
April 2020 - Polaris and Embedded Apps - Good/Bad choice?

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#2904]
I have a bunch of Apps to make in the next few months. 

I used Polaris < version 3. I understand that it is now approaching version 5. My main questions are:

1. It seems Shopify is moving away from Embedded Apps. Am I wasting my time trying to use Polaris as an Embedded App? 
2. I still have no clue what is going on with this Shopify App Bridge and Polaris. Is there a clear description of what works in terms of Polaris and the App Bridge moving into the future.

I remain scared and skeptical of using this React Polaris library but if Shopify can point out how it is available and a good choice for embedded Apps in 2020+ I would try it again. 

Otherwise, if it is only suitable for stand-alone Apps outside the Shopify admin, could you let me know so I can decide if I want to expend the effort to go there. 

It seems Shopify drops hints that they are fed up with Embedded Apps in 2020 and want to drop them altogether, so I would rather spend effort on using something that gets me past all that sooner rather than later. 

Thanks

**Comment by awebartisan** [comment]
To answer you first question:

- Shopify is not moving away from Embedded Apps(concept). They are deprecating Embedded App SDK (EASDK) and offering same functionalities via Shopify App Bridge.
-  Shopify App Bridge is not intended replace EASDK. It comes with "backward compatibility layer" that listens for legacy EASDK. [Read more](https://shopify.dev/tools/app-bridge/migrating)
- For future, its highly recommended to use Shopify App Bridge.

To answer 2nd question:

- There are few components like Modal, TopBar, Toast etc. for which we needed help of EASDK in past [link](https://shopify.dev/tools/embedded-app-sdk/getting-started)
- Now that EASDK is deprecating, we get these components from **Shopify App Bridge**
- Shopify App Bridge is fully compatible with **Polaris React**
- Read all about it here [https://shopify.dev/tools/app-bridge/react-components](https://shopify.dev/tools/app-bridge/react-components)

**Comment by resistorsoftware** [comment]
Ya, well, all that is nice, but the fact is, maintaining my Apps with App Bridge or EASDK is still painful due to browsers. Have you experienced the pain of Safari and Chrome? I was more concerned Shopify is moving away from the hassle of the <iframe> element containing Apps to something else. If so, it makes no difference about App Bridge or EASDK, as they are tied to this old <iframe> concept. Maybe I am wrong, and we'll get answers tomorrow from CTO.
