### ISSUE TITLE
Resource Picker should allow hiding initial query

### ISSUE THREAD

**Issue by bartcoppens** [Shopify/polaris-react#2909]
## Feature request summary

Allow consumers to decide if the initial query should be displayed to the user and if the user should be able to change the query.

## Rationale

Two reasons for this:
- Most (close to all really) end-users of the resource picker are not familiar with the query language that can be used
- In some use cases, it is not desirable that the end-user can change the query. Example: a picker that allows selecting one of the variants of a specific product. The query would filter to the correct product. Or a picker that allows selecting a collection from a list of collections that meet specific criteria.

The following discussion on the forum shows interest in this feature from a number of contributors: https://community.shopify.com/c/Shopify-APIs-SDKs/App-Bridge-ResourcePicker-InitialQuery-not-hidden-on-subsequent/m-p/700913

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by vpaul18** [comment]
Any updates ?

**Comment by ryanrphillips** [comment]
This is now possible using the resource picker via App Bridge: https://github.com/Shopify/shopify-app-bridge/issues/249
