### ISSUE TITLE
Embedded App Layout

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#2915]
I am trying out Polaris V4 in an Embedded App. 

Simply rendering <AppProvider> <Provider> <Layout> components with some cards and other Polaris components inside the layout. My App has polaris css. 

So it renders, but there are no margins or padding, everything renders full-width of the embedded app space. I see the layout css removes all margins top, bottom and sides. 

So things look kinda weird. So what I am asking is this. Am I supposed to make up CSS to make Polaris look good in an embedded app? I just want components like cards, resource lists and sections to have spacing around them so they don't look all bunched together.

**Comment by christocracy** [comment]
Screenshot?

**Comment by resistorsoftware** [comment]
True, I submit no screenshot with that request. I stand by my query though. In the Embedded context, 

    <AppProvider>
      <Provider config={config}>
        <TitleBar title="Dashboard" />
        <Layout>
          <Layout.Section>
            <Card title="Manually add a Mookie Lead" sectioned>
               ... stuff in Card components


and then putting things into Card elements, it just does not look or space right. And I already filed another similar request for why ResourceItems render so lame. The CSS of an H2, H3 is the same as a p tag? 

I do this

     import '@shopify/polaris/styles.css';

Now I am wondering what else I have to do, to make my layouts look better. As it stands, I have a 5 element form and a resource list on the screen and while I don't need a 32" monitor to use that, it is so SPARSE and there is so much whitespace, it is like I need to offer a switch that dials down that spread to as if I was on a mobile device. Seriously. When I type in a name to a text field, do I really need 100% width input field? 

I guess I am just not getting it. Having seen the web of 1996, 2006, 2016 and now 2020, it is hard to accept things still being so wonky out of the box.

**Comment by BPScott** [comment]
Sounds like you need to wrap your `Layout` with a [`Page`](https://polaris.shopify.com/components/structure/page) to constrain its dimensions.

Perhaps viewing our [Page Layouts](https://polaris.shopify.com/experiences/layout#section-standard-page-layouts) section will be helpful to demonstrate how you can combine the Page and Layout components to create different sorts of content.

**Comment by resistorsoftware** [comment]
I wrapped the <Layout> in a <Page> and that did make it look better. Thanks
