### ISSUE TITLE
Using Formik - Help a Brother Out

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#2930]
So now I realize Polaris has no thoughts on form validation. Roll your own. Ok. So Formik looks popular. Give it a spin! OK. So I lay down the very minimal basics of a test and it fails. While I can submit my form, I cannot type into the inputs. For some reason Formik does not play nice with Polaris? Is this really a thing? In the end, the render has a label and an input. What am I missing? 

[Demo](https://codesandbox.io/s/reverent-morse-e3p6c?file=/App.js:0-510)

    import { useFormik } from 'formik';    // ya a new toy

    const formik = useFormik({
      initialValues: {
        firstName: ''
      },
      onSubmit: values => {
        alert(JSON.stringify(values, null, 2));   // the form does submit to here
      },
    });

    <TextField
      id="firstName"
      name="firstName"
      type="text"
      value={formik.values.firstName}
      onChange={formik.handleChange}
      label="First Name"
    />

So that form element looks good. Like Polaris tells it to, but it does not work. What's up?

**Comment by resistorsoftware** [comment]
I suppose the long and short of it is, screw Formik, use this instead? [Shopify forms](https://github.com/Shopify/quilt/tree/master/packages/react-form)

**Comment by BPScott** [comment]
I've not used Formik but a read of their docs suggests that [their `handleChange` method expects to be passed a React.ChangeEvent as its first and only argument](https://jaredpalmer.com/formik/docs/api/formik#handlechange-e-reactchangeeventany--void). That's matches what you get back from the onChange event of a regular `<input>` element, however [`<TextField>`](https://polaris.shopify.com/components/forms/text-field/)'s onChange event doesn't expect an instance of React.ChangeEvent as its first argument - it expects the value stored in the text field.

So you need to write a little wrapper to transform that value you're getting, into something formik can do something about. See https://codesandbox.io/s/little-shadow-imoqm for two examples of doing this

**Comment by resistorsoftware** [comment]
Thanks! I never would've figured that out with the energy I have these days, dredging up the deeper implementation details like that. It is so refreshing to get responses so fast that just answer my Noob questions. Awesome.
