### ISSUE TITLE
Is Polaris free to use outside of Shopify ? 

### ISSUE THREAD

**Issue by fmontada** [Shopify/polaris-react#2934]
## Issue summary
Hi team Is Polaris free to use outside of Shopify ecosystem ? 
We would like to use for our next Project, in case of the answer is no, are you guys planning to have a pay version license ?

**Comment by devchris** [comment]
https://polaris.shopify.com/legal/license

**Comment by fmontada** [comment]
> https://polaris.shopify.com/legal/license

@devchris Good morning thanks for reply, is not clear for us base on the License link if it can be use or not, can you help us to understand it 

Also we noticed the the react-Polaris has a different License ?

Thanks

**Comment by awebartisan** [comment]
Reading both licenses, I think "Polaris Design" guidelines and its Components are only to be used for applications which are, in any way,  related to Shopify. 

>You may not use the Polaris Design Guidelines (i) to develop, test, or distribute an external, stand-alone Application (“External Application”) unless such External Application is not identical to and is dissimilar and visually distinct from Shopify products and services.

But it will be identical because of Polaris styles, right?

**Comment by chloerice** [comment]
Hi @fmontada 👋 Use of Polaris is restricted to Shopify-related projects, whether the styling is customized or not.
