### ISSUE TITLE
Unable to customize EmptySearchState for ResourceList

### ISSUE THREAD

**Issue by mbswart** [Shopify/polaris-react#2937]
## Feature request summary
I am working on ResourceList component and I am trying to customize its empty state when no items are found and filters are applied. 

It looks like there isn't any way to inject your own component or customize the EmptySearchResult to create something like this:
![image](https://user-images.githubusercontent.com/42705997/79893278-d600c680-83d1-11ea-95d6-28a4fbb861ac.png)

I know this was brought up here: https://github.com/Shopify/polaris-react/issues/1704 but it looks like it has been labeled iceboxed and closed. Wondering if adding functionality to inject a custom empty search result state or making the emptySearchResult customizable is possible. Thanks!

---

**Comment by 8eecf0d2** [comment]
The **ResourceList** component now has [`emptySearchState`](https://polaris.shopify.com/components/lists-and-tables/resource-list#prop-emptySearchState) and [`emptyState`](https://polaris.shopify.com/components/lists-and-tables/resource-list#prop-emptyState) props which allow you to provide your own markup when there are no items.

It's also relatively easy reuse _or recreate_ the [built-in **EmptySearchState**](https://github.com/Shopify/polaris-react/tree/master/src/components/EmptySearchResult) component, to keep things consistent.

Hope it helps!
