### ISSUE TITLE
TextField component onChange is not called after refocused on POS.

### ISSUE THREAD

**Issue by TravisSalad** [Shopify/polaris-react#294]
# Issue summary
After clicking into TextField in POS more than once without blurring, the onChange event no longer fires.

## Expected behavior
onChange should still function regardless of how many times TextField has been focused.

## Actual behavior
If TextField is focused more than once without blurring, onChange no longer fires.

## Steps to reproduce the problem
1. In POS, click on TextField and enter text.
2. Close keyboard and blur TextField.
3. Click on TextField again and regain focus.
4. Move cursor while TextField is focused or click on input again.
5. Type into text field and onChange no longer fires.

## Specifications

- Polaris version: "^1.12.2"
- React version: "^15.6.1"
- Device: iPad
- Operating System: multiple (tested on 9 and 11)

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by ry5n** [comment]
Thanks for catching this. I’ve added this issue to our todo list to look at with our POS engineers. Stay tuned.
