### ISSUE TITLE
[Filters] Enable individual tags for each selected option on an allowMultiple filter

### ISSUE THREAD

**Issue by emmaorhun** [Shopify/polaris-react#2950]
## Feature request summary
Make it possible to have separate Tags per filter in the Filters component. This dilemma occurs when you enable `allowMultiple` on the Choicelist under a filter. 
In the example on the Polaris documentation site (https://polaris.shopify.com/components/lists-and-tables/filters) when `allowMultiple` is enabled there is only one tag for that entire filter and all the selected options are under one label, I'd like the functionality of having each option as it's own Tag.
You are able to tweak it to have each option have it's own Tag but then the Clear button of the filter becomes unclickable.

<img width="643" alt="Screen Shot 2020-04-28 at 12 39 22 PM" src="https://user-images.githubusercontent.com/31415327/80513667-6482c400-894d-11ea-9bf8-d2cc200f1026.png">
^^ an example of the multiple tags and an unclickable clear button in action

## Rationale

In the app I'm working in I started getting involved because we use the Filters component and we have each filter option as it's own Tag but we had a bug where our Clear button was not clickable. The design of having each option as it's own filter tag is really attractive when there are a lot of options and you are allowed to select multiple but you might want to remove some options quickly with the X button on the tag but not all of them. Now you are forced to choose between appending every selected option of a filter under one tag or not having a clickable Clear button for that filter.
I need every `appliedFilter` to have it's own key because the key is what gets passed to the callback in onRemove.

I raised this issue up on Discourse here for more context (with images): https://discourse.shopify.io/t/clear-button-on-filters-component-not-clickable/7982/5

## What's causing this?
This happens because each `appliedFilter` is going to have it's own key that isn't going to match the key of the filter it's under and the Clear button is only enabled when the key of an `appliedFilter` matches the key of the filter it belongs to. `appliedFilters` is simply an array of all the selected filter options.  

A few solutions could be:
* Move the appliedFilters field under each filter object in the filters array. This way the `appliedFilters` wouldn't be just an abstract array of all selected options but would have a reference to the filter it's under and you'd be able to give each one it's own key easily
* Allow the `onRemove` field to accept a callback gets a variable passed in manually.
This is accepted: `onRemove: myCallback`
This is not accepted at the moment: `onRemove: myCallback(myVariable)` 
This would be good cause still keep the key of the `appliedFilter` that's used for relating it back to the filter it belongs to and enabling the Clear button but I could still have a custom `onRemove` action when the x on a tag is clicked
* Add an extra field to the `AppliedFilterInterface` to differentiate the key of the filter it's referencing and it's own key that would get used for the `onRemove()`

Let me know if I should clarify anything, I know this was a lot of text!

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by alex-page** [comment]
I also had this problem. Thanks for the awesome documentation and write up. Are you interested in making a PR for this?

**Comment by alex-page** [comment]
This should be resolved with the `clear` button functionality added to filters.
