### ISSUE TITLE
ResourceList is really buggy 

### ISSUE THREAD

**Issue by srameshr** [Shopify/polaris-react#2956]
## Issue summary
1. ResourceList does not render any labels either on sort or select.
2. onSortChange freezes the entires browser when called with a setState and a callback

## Expected behavior

Render as expected 

## Actual behavior

Breaks with missing labels, events not firing, browser freeze onSortChange

## Steps to reproduce the problem

1. Look at the sandbox links below

## Reduced test case

No labels rendered: https://codesandbox.io/s/shopify-polaris-react-typescript-playground-2e3xw?file=/src/index.tsx:1112-1123

Breaking: https://codesandbox.io/s/hopeful-leftpad-hdp03?file=/App.js:264-275

## Specifications

```

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 944.41 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.2 - node_modules/.bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Safari: 13.1
  npmPackages:
    @shopify/polaris: ^4.21.0 => 4.21.0 
    react: ^16.13.0 => 16.13.0 
    react-dom: ^16.13.0 => 16.13.0 
```

**Comment by raysaavedra-work** [comment]
i'm also experiencing this. ResourceList freezes the page - usually happens when I select a resource item or when I scroll to bottom.

**Comment by deanbarrow** [comment]
Did anyone ever find a workaorund for this?

**Comment by deanbarrow** [comment]
Actually I just found the latest release solved this issue for me:
https://github.com/Shopify/polaris-react/releases/tag/v4.25.1

**Comment by palashkulsh** [comment]
very buggy
