### ISSUE TITLE
[Card.Section] Destructive action icon should be red

### ISSUE THREAD

**Issue by dispix** [Shopify/polaris-react#2958]
## Issue summary

Make card section action icons colors consistent with their text.

## Expected behavior

The delete icon should be red, as is the text.

## Actual behavior

The delete icon keeps the default blue color.
![image](https://user-images.githubusercontent.com/11643701/80752978-c6e5eb00-8b2c-11ea-91e8-309acd982c70.png)

## Steps to reproduce the problem

```tsx
<Card.Section
  actions={[
    { content: 'Edit', icon: EditMinor },
    { content: 'Delete', icon: DeleteMinor, destructive: true },
  ]}
/>
```

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 4.21.0

```bash
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 137.96 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
    Safari: 13.1
```

**Comment by jacquesporveau** [comment]
I will begin working on this.

**Comment by jacquesporveau** [comment]
Hey @dispix, I've taken a quick look at this and I am not sure that this is actually a bug but instead could be working as intended. 

Do you happen to have a source that you can reference that says that this icon should be red? Maybe some docs or a style guide?

**Comment by dispix** [comment]
There's no specific mention that a button's icon should share the same color as its text but that seemed to be in the spirit of [this section of the documentation](https://polaris.shopify.com/design/colors). Plus, it seems very disturbing to mix color in a single component and may almost lead the user to believe there is two distinct components.

**Comment by jacquesporveau** [comment]
Sounds good. I'm going to try and get someone from Shopify to confirm that you are correct with your expected behaviour and then if that goes through I can take another look at solving this one.

**Comment by jacquesporveau** [comment]
@tmlayton 

Sorry about the ping but I don't really know how to get ahold of Shopify folk. Maybe you guys could make a community Slack or something. 

Anyways, could you or someone from Shopify weigh in on the conversation above?

**Comment by tmlayton** [comment]
No worries, pinging myself or someone else on an issue works just fine! The icon should be red, this is indeed a bug.

**Comment by sidlaryea** [comment]
Thanks!
