### ISSUE TITLE
Resource Picker source

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#2970]
Assume I have an access token to a Shop's collections. So my source of products would be

shopA.myshopify.com/admin/collections/123456789

I am currently logged into merchant shopB now, with an access token to Shop A. 

How would I go about modifying the ResourcePicker, so that when rendered in the App of Shop B, it shows off the products from the collection in Shop A, for which I have an access token? 

Is that possible or do I need to re-invent the wheel and make a ResourcePicker that can do that?

**Comment by vividviolet** [comment]
Hi David,

The Resource Picker is meant to retrieve collections/products from the current shop. Unfortunately it's not possible to show resources from another shop.

**Comment by resistorsoftware** [comment]
Ok.. no trouble. I will instead direct the queries to an API call, and that call under the hood can call the other shop and get the resources... I guess this means I now need to learn something like Apollo to manage the paging of the resources...
