### ISSUE TITLE
How to use Router

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#2978]
I am having trouble with React routing and Polaris App. I have an App that renders a router. 

    <AppProvider>
      <BrowserRouter>
        <Provider config={config}>
          <Router/>
        </Provider>
      </BrowserRouter>
    </AppProvider>

The Router is pretty simple:

    function Router(props) {
       const { location } = props;
       useRoutePropagation(location);
       return (
         <Switch>
           <Route exact path="/" component={Home} />
           <Route exact path="/events" component={Events} />
           <Route component={NotFound} />
         </Switch>
       )
     };
     export default withRouter(Router);

When I hit the home page, the Home component renders. On my home component I render a Link to /events but when I click that link, the App jumps to my internal server App route, and does not stay inside the React Polaris App... huh? Can anyone point out to me how React routing and Polaris work in this case? I thought by including the useRoutePropagation hook, everything would stay in sync and local on the front-end.

What am I missing here?

**Comment by BPScott** [comment]
I added some docs to help with this last week, but as we've not done a release since then they're not on polaris.shopify.com just yet.

https://github.com/Shopify/polaris-react/pull/2967/files

**Comment by resistorsoftware** [comment]
Perfect... Thanks!
