### ISSUE TITLE
Help with Router 

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#2979]
I have my React App working internally. Using the BrowserRouter and Polaris modifications to Link as per:

When a link is clicked in my App, the URL in browser changes, and the App works. So I see something correct like this:

[Polaris Link for App Bridge](https://github.com/Shopify/polaris-react/pull/2967/files?short_path=7a936f0#diff-7a936f09d89747421f1ed11ca7e51421
)

So when I click links in my App, they render the correct Router components. And it all seems good. An example of this is my event details page... /event/1152

https://fuzzywumpus.myshopify.com/admin/apps/fuzzywumpus-localhost/event/1152

So my dummy question I need help with, is if I refresh the browser or hit enter on that URL it goes to the underlying App and tries to load up route /event/1152 which is something I do not want. I want the App to respond. How come the request is going to the backend? What do I have to do to keep those requests being serviced by the Router? 

Excuse my ignorance of how React Routing works! I am a noob with React so obvous things elude me.

**Comment by resistorsoftware** [comment]
I made a wildcard route for my server, serving all my front-end to the root. Seems to take care of the refresh.. .not sure how totally great that is, but if that is the trick, so be it.

**Comment by BPScott** [comment]
> I made a wildcard route for my server, serving all my front-end to the root. Seems to take care of the refresh.. .not sure how totally great that is, but if that is the trick, so be it.

Yep that's what you're supposed to do.
