### ISSUE TITLE
ResourcePicker

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#2984]
There does not seem to be easy access to the resource picker buttons. Cancel is fine. But Add is not the verbiage that makes sense to me. I prefer the **Select** which should really be Select Product, or the awkward ProductVariant or Collection depending on the resourceType. 

So how does one override the **Add** button and change it to  **Select** or something?

**Comment by BPScott** [comment]
Doesn't looks like there's anything relevant on their API https://shopify.dev/tools/app-bridge/react-components/resourcepicker

**Comment by vividviolet** [comment]
@resistorsoftware You can use the `actionVerb` option and set it to `ResourcePicker.ActionVerb.Add`. For example:
```
<ResourcePicker resourceType="Product" actionVerb={ResourcePicker.ActionVerb.Add} />
``` 

Our docs are out of date unfortunately.

**Comment by resistorsoftware** [comment]
In my experience, the forums take a very long time to surface answers, you get noise in the signal, and so it seems counter-intuitive to ask questions there when the very community into developing and using Polaris are at Github here. If the forums were actually a source of relief to technical questions of a specific nature, I would gladly indulge. Thanks for the suggestion.
