### ISSUE TITLE
Tag component doesn't have a removable option

### ISSUE THREAD

**Issue by artyrcheek** [Shopify/polaris-react#2986]
## Issue summary

when a onRemove prop is passed to the tag component it adds a `Polaris-Tag--removable` class but it doesn't do anything, and the onRemove is never able to be triggered

## Expected behavior

when an onRemove prop is passed, the tag should show a close icon on the right hand side that should be clickable

## Actual behavior

The tag is added but nothing is change

## Steps to reproduce the problem

1. add a tag component
2. add a onRemove prop

## Reduced test case

https://lpy7b.csb.app/

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.22
- Browser: Chrome
- Device: Macbook pro osx
- Operating System: osx

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 323.41 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 75.0
    Safari: 12.1.2
  npmPackages:
    @shopify/polaris: ^4.17.0 => 4.22.0
    react: ^16.13.1 => 16.13.1
    react-dom: ^16.13.1 => 16.13.1

```

**Comment by chloerice** [comment]
Hey @artyrcheek 👋 Can you link to the sandbox? I can't see the code you've used with the link provided. Did you set both `onClick` and `onRemove` on the `Tag`? [Tags can be removable or clickable but not both](https://codesandbox.io/s/focused-golick-o03v2?file=/App.js).

**Comment by artyrcheek** [comment]
My bad 🤦

**Comment by chloerice** [comment]
> My bad 🤦

Not at all, @artyrcheek, we need to make this clearer! I'll add an example for removable tags and add some clarity to the prop descriptions so it's clear `onClick` and `onRemove` are mutually exclusive.
