### ISSUE TITLE
[Filters] Make the 'Clear' button on a ChoiceList optional

### ISSUE THREAD

**Issue by emmaorhun** [Shopify/polaris-react#2989]
## Feature request summary

Make the clear button on a filter disappear if I need it to!

## Rationale

On a filter where one option must always be selected, I don't want to have the 'Clear' button there especially when it is never clickable. 

<img width="448" alt="Screen Shot 2020-05-14 at 3 24 42 PM" src="https://user-images.githubusercontent.com/31415327/81977854-a91e8880-95f8-11ea-9316-b0f829490b99.png">

^^ This is a screenshot of my current example for wanting this feature. My filter is a Choicelist with radio buttons where there will  always be a selection made. I think it makes the situation a lil less comfortable for the user to have to see a disabled feature they will never interact with.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by AndrewMusgrave** [comment]
@sanaasy We should be able to complete this in our ux-pairing. Let's take a look!

**Comment by AndrewMusgrave** [comment]
cc/ @sanaasy

**Comment by gyoqueiroz** [comment]
We have a case where the dropdown should have none or one selected and still we want the `Clear` button to be enabled so we don't have to remove it via applied filters. Is it something that should be explored as well?

**Comment by emmaorhun** [comment]
@gyoqueiroz If these options are within a multi-choice list (using checkboxes) the clear button will remain. In cases where there are radio buttons (radio buttons signify that there will always be one option selected) there will be no clear button. It sounds like you are using checkboxes so your use-case won't change, but let me know otherwise!
