### ISSUE TITLE
TextField in Popover autofocus not working when used in a Sheet

### ISSUE THREAD

**Issue by globo-software** [Shopify/polaris-react#2994]
## Issue summary
 

I created a TextField in Popover, and the Popover in a Sheet. But I can't focus on the text field. 
See this code sandbox pls: https://codesandbox.io/s/fervent-waterfall-2n67t?file=/App.js

**Comment by matomesc** [comment]
I'm running into the same issue but the Popover is inside a Modal - looks like form elements inside the Popover can't be focused.
