### ISSUE TITLE
Polaris date picker buttons are missing in Android webview

### ISSUE THREAD

**Issue by jbtwo** [Shopify/polaris-react#2997]
## Issue summary

A partner has reported that when viewing the Polaris date picker component in an Android webview, the buttons are missing. The Mobile Shopify app renders embedded apps in a webview, and this is where he observed the behaviour

## Expected behavior

[![alt](https://screenshot.click/20-05-sntvt-5r53i.png)](https://screenshot.click/20-05-sntvt-5r53i.png)

## Actual behavior

[![alt](https://screenshot.click/20-05-tsrix-lc0u6.png)](https://screenshot.click/20-05-tsrix-lc0u6.png)

## Steps to reproduce the problem

1. Download any embedded app that uses the polaris date picker. I used [this](https://apps.shopify.com/theme-scientist) one, but tested on others as well. If you use this app, be sure to pick the `standard` pricing plan
2. Open the test store in the Mobile Shopify app for Android, navigate to the apps page, and launch the newly installed app.
3. For the Theme Scientist app, tap "Theme A/B" testing, then tap the "Start Day" field to bring up the date picker
4. You should see that the date picker is missing the 3 buttons at the bottom

## Specifications

Sorry this is my first issue in this repo, I didn't get the polaris version or react information when I was in contact with the merchant. Please let me know if I should get in contact again and get it, since the issue is replicable in other apps I'll hold off for now.

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser: Android Webview (within Mobile Shopify app)
- Device: Google Pixel 3
- Operating System: Android 10

**Comment by kyakaze** [comment]
The issue is still around for native date-picker on Android app (embedded view). The buttons at the bottoms are invisible but still clickable.
