### ISSUE TITLE
Link to Polaris broken

### ISSUE THREAD

**Issue by peterleilei86** [Shopify/polaris-react#2999]
## Issue summary

Link to Polaris components page is broken on `build-a-shopify-app-with-node-and-react` tutorial page [here](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris) 

<img width="474" alt="Screen Shot 2020-05-22 at 3 17 52 PM" src="https://user-images.githubusercontent.com/26579337/82702607-4eacaa00-9c40-11ea-8f73-b44d6cbdb185.png">

**Inspecting the element shows the link contains white spaces in between, which it shouldn't.**

## Expected behavior

Clicking on the link should take me to Polaris components page

## Actual behavior

Firefox: nothing happens when clicking on the link.
Chrome: clicking on the link takes me to this url: `https://polaris.shopify.com%20/%20components%20/%20get%20-%20started` 

## Steps to reproduce the problem

1. Go to [here](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris)
2 Scroll down to `Add a settings toggle` section
3. In step 1 tip section, click on the link to view _Polaris website_

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): N/A
- Polaris version number: N/A
- Browser: Firefox
- Device: Macbook Pro
- Operating System: MacOS Catalina

**Comment by kaelig** [comment]
Thank you for pointing this out! A fix is on its way and should be shipped shortly ❤️
