### ISSUE TITLE
Is there any way to show/hide password of Textfield with type="password"

### ISSUE THREAD

**Issue by codemicky** [Shopify/polaris-react#3038]

**Comment by kaelig** [comment]
👋 this feature isn't supported or planned, can you say more about your use-case?

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by LeibmanYosi** [comment]
Password should be dotted in order of people behind you won't be able to read it, but you need to be sure you don't have any misspellings, it's better to have the option to see what's there. That is achieved by a dynamic "type" field, but style-wise we need to create a new button outside of the input field or some ugly play on the suffix prop with onClick, so official implementation can be really beneficial.

**Comment by officiallybijen** [comment]
You may simply use type attribute now. Don't know if it was supported before but now it does.
<TextField type="password" />
