### ISSUE TITLE
<SettingToggle> component doesn't take in an ID properly

### ISSUE THREAD

**Issue by will-quanstrom** [Shopify/polaris-react#3044]
## Issue summary

The SettingToggle component only registers an id passed into it sometimes.

## Expected behavior

The Setting Toggle Action prop can take in an:

id
type: string
A unique identifier for the action

This id can then be accessed through event.target.id once the button that SettingToggle renders is clicked.

## Actual behavior

I map() through an array, creating a new SettingToggle component for each index of array. Each index has a unique id with is passed into the SettingToggle id prop, but when the button which renders is clicked, only sometimes does the id exist under the event.target.id, and other times it's simply empty: "".

**Comment by kaelig** [comment]
Hi @wanderlust22, thank you! Can you please provide an example on codesandbox.io so someone can confirm the issue and recreate it?
