### ISSUE TITLE
CDN-styles readme is outdated and references Polaris 4.0.0 which doesn't work with examples, needs to be updated to 4.25.0

### ISSUE THREAD

**Issue by derrickrc** [Shopify/polaris-react#3050]

**Comment by derrickrc** [comment]
Link here: https://github.com/Shopify/polaris-react/tree/master/examples/cdn-styles

**Comment by kaelig** [comment]
Thank you @derrickrc for pointing this out! A fix is on its way here: https://github.com/Shopify/polaris-react/pull/3068
