### ISSUE TITLE
How to Use Modal in App Bridge context

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#3053]
I render Modal from App Bridge React in a component. The modal gets its content from a src URL. The src URL points to a file that renders a form with validation, a success handler and a cancel handler. 

If the form submits successfully how the heck do I communicate that to the parent Modal? It has no Props sent to the component that rendered via the src. 

What is the secret to using a Modal in this case?

Modal from the App Bridge React has no Modal.section like the App Bridge version. So is the only choice here to get Context and pass that around?

**Comment by shai-caazam** [comment]
Hi @resistorsoftware  - did you find a way to close the Modal? Can you share some code?
