### ISSUE TITLE
Mobile menu items toggle

### ISSUE THREAD

**Issue by vitalijalbu** [Shopify/polaris-react#3055]
## Issue summary

On mobile menu, items that have dropdown sub-items, must be hidden if clicking another item.

![IMG_3860](https://user-images.githubusercontent.com/40239902/84660460-2b141100-af19-11ea-8ee7-351ecf0ccdc7.jpeg)

## Specifications

- Are you using the React components? (Y/N): YES
- Polaris version number: 4.2.5
- Browser: Chrome
- Device: iphone 11
- Operating System: ios

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by kaelig** [comment]
Hi @vitalijalbu – can you provide code (ideally, on CodeSandbox) that illustrates what you're trying to achieve? It would greatly help people reproduce the issue.

**Comment by vitalijalbu** [comment]
https://codesandbox.io/s/magical-nobel-w0p0n

Try to minimize screen do responsive, and you will see subitems menu toggle issue.

![Schermata 2020-06-23 alle 14 41 15](https://user-images.githubusercontent.com/40239902/85404717-aac85e00-b55f-11ea-830e-67cc6409a8da.png)

**Comment by kaelig** [comment]
Thank you – but I'm not seeing that in the CodeSandbox you shared: there are only two navigation items.

<img width="241" alt="Screen Shot 2020-06-23 at 11 01 08 AM" src="https://user-images.githubusercontent.com/85783/85438451-e142b080-b540-11ea-8a44-591abc4e796c.png">

Can you try again?

**Comment by vitalijalbu** [comment]
sorry,
https://codesandbox.io/s/magical-nobel-w0p0n

Il giorno mar 23 giu 2020 alle ore 20:01 Kaelig Deloumeau-Prigent <
notifications@github.com> ha scritto:

**Comment by kaelig** [comment]
Thank you!

The `location` prop is what informs what navigation sections are open/closed.

Here's an example where `location` is set to `/marketing` and the marketing section is opened.

https://codesandbox.io/s/keen-brook-ls2hh?file=/App.js

I hope this helps!
