### ISSUE TITLE
Pass thru data-testid for cypress testing

### ISSUE THREAD

**Issue by gerwinbrunner** [Shopify/polaris-react#3056]
## Feature request summary

it would be really great if all `data-...` props to a component would be passed thru.

## Rationale

To do automated testing with i.e. cypress you would need in some cases to set the data-testid prop on specific elements.

This is not possible to do with just the id prop (multiple elements of the same kind) 
or with plain xpath expressions.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by lhincapie0** [comment]
👍

**Comment by dkarter** [comment]
Can this issue be reopened please?

**Comment by airhorns** [comment]
This would be really great to address!

**Comment by gerwinbrunner** [comment]
Any update on this?

**Comment by gerwinbrunner** [comment]
It seems to work on Box but on Page the data-* attributes are filtered out :/

**Comment by gerwinbrunner** [comment]
I'm still very interested in this!
Any chance that could happen?
