### ISSUE TITLE
Embedded app navigation bar flickering

### ISSUE THREAD

**Issue by Tristan-temp** [Shopify/polaris-react#3065]
## Issue summary

I'm following along with the React/Node app tutorial for embedded apps but I'm noticing issues with the navigation bar in Chrome (Safari seems to work fine). When clicking links in the bar, multiple elements in the bar itself are refreshed in addition to the iframe. This creates a janky flickering effect when switching tabs. Am I missing something here?

## Expected behavior

I expect the top bar and navigation links to remain mostly static when switching between pages, as seen here: https://github.com/Shopify/polaris-react/pull/1349. This behaviour is visible in Safari, but not in chrome (except for brief moments).

## Actual behavior

<details>
    <summary>Navigation bar flickers in embedded app when navigation between pages on chrome</summary>
    <img src="https://media.giphy.com/media/QYdcVwZEEaaGhNsdZn/giphy.gif" alt="Navigation bar flickers in embedded app when navigation between pages, chrome">
</details>

## Steps to reproduce the problem

Follow the react/node [app tutorial](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react) along until step 4. Sample code [here](https://github.com/Tristan-temp/shopify-embedded-app-demo). Switch between navbar links in chrome to see the bar quickly vanish and reappear in the page, creating a flickering effect.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.10.2
- Browser: Chrome
- Device: Mac, and windows
- Operating System: macOS 10.15, Windows 10.0.18363

```bash
  System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 542.86 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Safari: 13.0.4
  npmPackages:
    @shopify/app-bridge-react: ^1.15.0 => 1.13.1
    @shopify/polaris: ^4.12.0 => 4.10.2
    next: ^9.2.1 => 9.1.7
    react: ^16.12.0 => 16.12.0
    react-dom: ^16.12.0 => 16.12.0
```

**Comment by kaelig** [comment]
Thank you for sharing your issue here! If someone from the community could jump in and provide guidance on how they solved this, it'd be fantastic.

@Tristan-temp can you please push your latest code to the repository (at the time of writing this, I'm only seeing one annotated section instead of 2 as described in your issue)?

**Comment by Tristan-temp** [comment]
Thanks for the response! The code is up to date: there are two pages, index.js and annotated-layout.js. The page contents do not seem to affect the behaviour.

When switching between pages it makes sense that the title bar and iframe need updating, since different pages will have different titles and content. However, the navigation bar is statically defined from the shopify partner admin, so it doesn't really make sense that it should ever be updated, except for the rare time when a change is detected from that admin.

**Comment by BPScott** [comment]
Hi @Tristan-temp, this sounds like an issue with AppBridge integration, rather than something related to Polaris components, can you please raise an issue in their issues repo: https://github.com/Shopify/shopify-app-bridge
