### ISSUE TITLE
Datatable in card does not span full width

### ISSUE THREAD

**Issue by jeffblake** [Shopify/polaris-react#3066]
## Issue summary

When using a DataTable in a card, with few columns, the cumulative width of the header cells do not occupy the full width of the card container.

## Expected behavior

Width of table is 100% inside card, with "Inventory" right aligned to line up with the `totals` row.

## Actual behavior

<img width="679" alt="Screen Shot 2020-06-19 at 6 51 49 AM" src="https://user-images.githubusercontent.com/620564/85140245-db279980-b1f9-11ea-84b6-ed28b58dd9e9.png">
<img width="692" alt="Screen Shot 2020-06-19 at 6 53 10 AM" src="https://user-images.githubusercontent.com/620564/85140253-de228a00-b1f9-11ea-8f28-a75e7cf3e973.png">
<img width="814" alt="Screen Shot 2020-06-19 at 6 53 17 AM" src="https://user-images.githubusercontent.com/620564/85140259-e1b61100-b1f9-11ea-9aba-14b2f401a10f.png">

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.26.1
- Browser: Chrome
- Device:  Macbook pro
- Operating System: macOS

**Comment by chloerice** [comment]
Hi @jeffblake 👋 Can you share a CodeSandbox of what you've screenshot?

**Comment by jeffblake** [comment]
@chloerice sorry my fault! My `totals` array had one too many items! Closing.
