### ISSUE TITLE
Resource Picker show selected items as checked

### ISSUE THREAD

**Issue by greghesp** [Shopify/polaris-react#3067]
## Feature request summary

The Resource Picker lets you select resources, however it has no way to distinguish which items are already selected.

This request is to add a property called `selectedIds` where you can pass the Shopify IDs of the products into the component, which shows them as checked when the picker is opened.

When the user closes the picker, the `onSelection` property works the same, returning any selected products.  Should a product be de-checked, this would no longer be in the value returned from onSelection

## Rationale

At the moment the Resource Picker shows all products by default, as unchecked.  Implementing this change would mean the developer does not have to separately manage the list of selected ID's elsewhere

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by resistorsoftware** [comment]
I like this issue as it touches on mine too. I would love to render items, with some simply being unselectable. So like rendering as preselected, we could have item states. 

- unchecked, selectable
- unchecked, unselectable
- checked, selectable

Would be nice.

**Comment by arslaniftikhar** [comment]
👋Any change for this to be developed? We're also looking for this feature of the pre-selection of products when the product picker launches.
We would appreciate any update on this.

**Comment by resistorsoftware** [comment]
I think this is now part of ResourcePicker. I think there is an array of selected item ids you can provide? Just read something about that. Maybe...

**Comment by resistorsoftware** [comment]
Sad that such a simple and useful pattern is Iceboxed. I get it. Make your own components. Sure. We do. But this kind of stuff is so handy, and that pattern so useful for a baked in Shopify thing. Oh well.
