### ISSUE TITLE
[Stack] Revisit how stacks handle Fragments

### ISSUE THREAD

**Issue by AndrewMusgrave** [Shopify/polaris-react#3074]
## Issue summary

Stack wraps it's children elements in an Item component. However the purpose of `React.Fragment` is to wrap multiple elements without adding additional markup. We'll want to ignore fragments when wrapping children.

## Reproduction

https://codesandbox.io/s/solitary-meadow-q23vh?file=/App.js

## Expected behavior

* Fragments are not wrapped in a `Stack.Item`

## Actual behavior

* Fragments are wrapped in a `Stack.Item`

**Comment by KasparIsSo** [comment]
The same is true for Popovers and passing in fragmentized `Popover.Pane`

https://codesandbox.io/s/quirky-mccarthy-ttrwo?file=/App.js

I can open a new issue if that's preferred
