### ISSUE TITLE
Dropzone Remove Item

### ISSUE THREAD

**Issue by greghesp** [Shopify/polaris-react#3079]
## Feature request summary

Fairly self explanatory.  Current Dropzone has no way to remove an uploaded item. Feature would give users the ability to remove an already uploaded item.

Adding a remove button within the Dropzone child does not work, because it registers the click within the dropzone, therefore opening the file dialog window

## Rationale

If a user uploads an item by mistake, the only way they can currently remove it is by reloading the page.  Not very user friendly.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by sandysameh** [comment]
did any one find a solution ?
