### ISSUE TITLE
App Bridge Modal has problem with setupModalAutoSizing

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#3083]
## Issue summary

Open up a Modal, which contains an image element. Get the App Bridge context, and using that, use the setupModalAutoSizing function inside the modal content component.

## Expected behavior

Modal should open and have auto-adjusted its size to the screen, the iframe of the modal should have a height of correct proportions to the window. 

## Actual behavior

The Modal opens and often the image is rendered perfect in the modal,  but most of the time the modal opens and the iframe height is set to 0px hiding all the content. Closing the modal and then re-opening it always renders a perfectly sized Modal. So it is apparently only on first opening some new content that it fails to size properly.

## Steps to reproduce the problem

1. Open a model in a component from App Bridge Actions

`import { Modal } from '@shopify/app-bridge/actions';`
`import { Context } from '@shopify/app-bridge-react';`

```
    const appBridge = useContext(Context)

    const handleClick = useCallback((imageSrc) => {
      const modalOptions = {
        title: 'Zoomer Collection',
        path: `/media?url=${imageSrc}`
       }
       const myModal = Modal.create(appBridge, modalOptions);
       myModal.dispatch(Modal.Action.OPEN);
     })
```

2. in the /media route, the component there, opens up the App Bridge context and fires off the setupModalAutoSizing

```
import React, {
  useContext,
} from "react"
var qs = require('qs')
import {
  Card,
} from '@shopify/polaris'
import { setupModalAutoSizing } from '@shopify/app-bridge-utils';
import { Context } from '@shopify/app-bridge-react';

export default function Media(props) {
  const appBridge = useContext(Context)
  setupModalAutoSizing(appBridge)
  const url = qs.parse(props.location.search, { ignoreQueryPrefix: true }).url
  return (
    <Card>
      <img className="object-contain" src={url} alt="Zoomer Collection" />
    </Card>
  )
}
```

One can see that the size of modal is not consistent!! Why is rendering a height of 0px on the modal iframe element?

## Reduced test case

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.20.1
- Browser: FF
- Device: computer
- Operating System:   MacOS

```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 14.55 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 75.0.66.100
    Chrome: 83.0.4103.116
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    @shopify/polaris: ^4.20.1 => 4.20.1
    react: ^16.13.1 => 16.13.1
    react-dom: ^16.13.1 => 16.13.1

**Comment by resistorsoftware** [comment]
Moved to the App Bridge aspect of Polaris...

**Comment by resistorsoftware** [comment]
This remains an issue for Polaris 5 and app-bridge-react 1.21.2

**Comment by BPScott** [comment]
Please raise app-bridge issues to the app-bridge team in https://github.com/Shopify/shopify-app-bridge

**Comment by resistorsoftware** [comment]
I did. No response there. So I simply wanted to remind the crowd here, since this is Polaris React, and maybe an eyeball on the issue here will translate to an eyeball there on it. Unless the two shall never meet. Which would be strange.
