### ISSUE TITLE
shopify polaris navigation

### ISSUE THREAD

**Issue by solutionwin2020** [Shopify/polaris-react#3088]
Hi i actually working on react and shopify polaris but i am unable to make navigation or routes. the routes which i make is load the page can anyone tell how to make routes with shopify polaris navigations. Here is code.

<Navigation location="/">
  <Navigation.Section
    items={[
      {
        url: '/setting',
        label: 'setting',
        icon: HomeMajorMonotone,
      },
      {
        url: '/filter',
        label: 'filter',
        icon: OrdersMajorTwotone,
        badge: '15',
      },
      {
        url: '/search',
        label: 'search',
        icon: ProductsMajorTwotone,
      },
    ]}
  />
</Navigation> 

and Route file
class RoutesPage extends React.Component
{
    render()
    {
        return(
        <Router>
          <Switch>
            <Route path="/settings">
                <SettingPage />
              </Route>
              <Route path="/search">
                <SearchPage />
              </Route>
              <Route path="/filter">
                <FilterTables />
              </Route>
              </Switch>
        </Router>
        );
    }
}

export default RoutesPage;

**Comment by BPScott** [comment]
We don't provide any routing library, That's up to you. You probably want [react-router](https://reacttraining.com/react-router/web/guides/quick-start). You'll need to [configure AppProvider's linkComponent](https://polaris.shopify.com/components/structure/app-provider#using-linkcomponent) to integrate with the router you choose.

**Comment by junix13** [comment]
Has anyone actually made this work? I have tried and it's not working.

**Comment by sshaw** [comment]
> Has anyone actually made this work? I have tried and it's not working.

@junix13 I have it working under `@shopify/polaris@7.5.0` using [the example linked to](https://polaris.shopify.com/components/structure/app-provider#using-linkcomponent) above. Key point is to massage the props to ~confirm~ conform to the underlying link component.

**Comment by st-baonguyen** [comment]
> I have it working under @shopify/polaris@7.5.0 using [the example linked to](https://polaris.shopify.com/components/structure/app-provider#using-linkcomponent) above. Key point is to massage the props to confirm conform to the underlying link component.

@BPScott  @sshaw @junix13  have you run it yet?. I have same issue too. My version is `@shopify/polaris@9.12.2`

**Comment by sshaw** [comment]
@st-baonguyen yes working for me using the example from the docs: 

```jsx
function Link({children, url = '', external, ref, ...rest}) {
  // react-router only supports links to pages it can handle itself. It does not
  // support arbirary links, so anything that is not a path-based link should
  // use a reglar old `a` tag
  if (external || IS_EXTERNAL_LINK_REGEX.test(url)) {
    rest.target = '_blank';
    rest.rel = 'noopener noreferrer';
    return (
      <a href={url} {...rest}>
        {children}
      </a>
    );
  }

  return (
    <ReactRouterLink to={url} {...rest}>
      {children}
    </ReactRouterLink>
  );
}

<AppProvider i18n={enTranslations} linkComponent={Link} theme={theme}>
...
```

Not sure about your version. Mine is: `@shopify/polaris@7.5.0` and `react-router-dom@6`.

**Comment by st-baonguyen** [comment]
@sshaw Thank you for your replying
I got an error at `linkComponent={Link}` when using this example 
```
Type '({ children, url, external, ref, ...rest }: { [x: string]: any; children: any; url?: string; external: any; ref: any; }) => Element' is not assignable to type 'LinkLikeComponent'.
  Type '({ children, url, external, ref, ...rest }: { [x: string]: any; children: any; url?: string; external: any; ref: any; }) => Element' is not assignable to type 'FunctionComponent<LinkLikeComponentProps>'.
    Types of parameters '__0' and 'props' are incompatible.
      Type 'PropsWithChildren<LinkLikeComponentProps>' is not assignable to type '{ [x: string]: any; children: any; url?: string; external: any; ref: any; }'.
        Property 'children' is optional in type 'LinkLikeComponentProps & { children?: ReactNode; }' but required in type '{ [x: string]: any; children: any; url?: string; external: any; ref: any; }'
```
And i tried by add a default param = null and it working, do you think it is correctly?
```
function Link({children = null , url = '', external = false, ref = null, ...rest}) {
   ...
}
```

**Comment by sshaw** [comment]
Ugh TypeScript.

> And i tried by add a default param = null and it working, do you think it is correctly?

In this case it looks like the problem is Polaris' `LinkLikeComponentProps` interface makes `children` optional but the `Link` wrapper has it required.  So `children = null` would make it optional so seems to make sense as a solution as the HTML spec allows `a` element's without children: 

```html
<a id="my-anchor"></a>
<!-- More amaaaazing HTML -->
<a href="#my-anchor">Foo</a>
```

But keep in mind that I try to stay away from TypeScript. It's a productivity killer, really :neckbeard:
