### ISSUE TITLE
Repository URL for @shopify/app-bridge-react is broken

### ISSUE THREAD

**Issue by chaddjohnson** [Shopify/polaris-react#3096]
## Issue summary

The Homepage and Repository URLs for [@shopify/app-bridge-react](https://www.npmjs.com/package/@shopify/app-bridge-react) are broken and have been broken for quite some time. The package, however, is clearly in active development (published 2 days ago), yet there is no definitive source the community may refer to.

I see [react-app-bridge-universal-provider](https://github.com/Shopify/quilt/tree/master/packages/react-app-bridge-universal-provider) in Shopify Quilt, but I think that is a different package.

## Expected behavior

The Homepage and Repository links should be correct.

I don't know if this is the correct place to list this issue. If it is not, please point me to the correct GitHub project.

**Comment by BPScott** [comment]
The repository url is correct, however it is a private repository. Documentation for app-bridge-react can be found at https://shopify.dev/tools/app-bridge/react-components.

The team responsible for app-bridge (which is a different team to team that maintains this repo) are currently in the process of creating a space for publicly raised issues so they can better engage with the developer community. (FAO @vividviolet)
