### ISSUE TITLE
Modal close doesn't work when there is no title

### ISSUE THREAD

**Issue by junaidatique** [Shopify/polaris-react#3110]
## Issue summary
where there is no title in the Modal, there is some CSS problem and the cross sign doesn't work. 

On the polaris model has an option in which it doesn't have a title. but when there is no title and footer action, there is no way to close the modal. 

## Expected behavior
even if there is no title or footer, the close icon should work. 

there is some CSS problem that needs to be fixed. 
## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by kvendrik** [comment]
Hey @junaidatique!

As you can see [in this example](https://codesandbox.io/s/lingering-morning-ddvr8?file=/App.js) even without a `title` the cross icon works, the only requirement the component has for the cross button to work is for the consumer to set an `onClose` callback.

I do agree that we don't have great support for a no-title use-case as the button's styling starts to look a bit off. Internally we currently don't require better support for no-title use cases but we're always open to contributions!

I will close this for now, feel free to reopen if you have further questions.
