### ISSUE TITLE
Dropzone accept not working as I expected

### ISSUE THREAD

**Issue by nikolacojcic99** [Shopify/polaris-react#3125]
## Issue summary

I am going to make **Dropzone** to accept only **excel(.xls,.xlsx)** files.

This is the code I used.
```
<DropZone 
  accept="application/vnd.ms-excel" 
  errorOverlayText="File type must be .xls or xlsx"
  allowMultiple={false} 
  onDrop={this.handleDrop} 
>
  {addedFiles}
  {fileUpload}
</DropZone>
```

## Expected behavior

I expected that it should work on any **OS** and it should work even any **App**/**Program** for reading **excel** files is not installed.

## Actual behavior

I have tested on 2 **OS** - **macOS** and **Windows**.
It worked on **macOS** and **LibreOffice** App is installed on **macOS**.
But it didn't work on **Windows** and **Office** is not installed on **Windows**

**Comment by rabbit0321** [comment]
I have meet the same issue.
It doesn't recognize mime for .rar neither: application/x-rar-compressed, application/octet-stream
