### ISSUE TITLE
[Bug] Badge font weights slightly different with new design langauge

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#3131]
## Issue summary

While tophatting my color update PR @kyledurand noticed that when using the new design langauge the badge font weights are different for some badges.
https://github.com/Shopify/polaris-react/pull/3127#pullrequestreview-453310526

## Expected behavior

Badge font weight should be consistent.

## Actual behavior

When looking at the examples the badge font weight is inconsistent.

## Steps to reproduce the problem

1. Open the badge example
1. Look at the font weights in different browsers

## Specifications

- Are you using the React components? (Y):
- Polaris version number: 5.0.0
- Browser: Firefox
- Device: Macbook
- Operating System: OSX

**Comment by kaelig** [comment]
I couldn't reproduce this on a non-Retina external monitor with the latest macOS, Chrome, Firefox. I couldn't reproduce either on the latest Chrome Android on a high dpi screen (Pixel 2 XL).

Page tested: https://5d559397bae39100201eedc1-mmanoiyuuf.chromatic.com/iframe.html?id=all-components-badge--all-examples

**Comment by kyledurand** [comment]
The link you shared didn't have the new design language enabled @kaelig just making sure you're testing the right things or maybe we need to update the issue to specify that it's only happening with the new DL enabled @alex-page

**Comment by alex-page** [comment]
This link should replicate the issue 🤞

https://5d559397bae39100201eedc1-mmanoiyuuf.chromatic.com/iframe.html?id=all-components-badge--all-examples&contexts=New%20Design%20Language=Enabled%20-%20Light%20Mode
