### ISSUE TITLE
Module not found: Can't resolve '@shopify/polaris/styles.css'

### ISSUE THREAD

**Issue by ShahinGh** [Shopify/polaris-react#3134]
## Issue summary
I've followed the [Build a shopify app with node and react](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris), however when I add `import '@shopify/polaris/styles.css';` into my `_app.js` it will throw an error that `Module not found: Can't resolve '@shopify/polaris/styles.css'`

## Expected behavior
It should require the CSS files and apply them to the components

## Actual behavior
The styles don't apply to my components

## Steps to reproduce the problem

I just followed the tuturial here's my code: 
**_app.js**
``` import App from 'next/app';
import Head from 'next/head';
import { AppProvider } from '@shopify/polaris';
import { Provider } from '@shopify/app-bridge-react';
import '@shopify/polaris/styles.css';
import translations from '@shopify/polaris/locales/en.json';
import Cookies from 'js-cookie';


class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props;
    const config = { apiKey: API_KEY, shopOrigin: Cookies.get("shopOrigin"), forceRedirect: true };
    return (
      <React.Fragment>
        <Head>
          <title>Sample App</title>
          <meta charSet="utf-8" />
        </Head>
        <Provider config={config}>
          <AppProvider i18n={translations}>
            <Component {...pageProps} />
          </AppProvider>
        </Provider>
      </React.Fragment>
    );
  }
}

export default MyApp;
```
**next.config.js**
```
require("dotenv").config();
const withCSS = require('@zeit/next-css');
const webpack = require('webpack');

const apiKey = JSON.stringify(process.env.SHOPIFY_API_KEY);

module.exports = withCSS({
  webpack: (config) => {
    const env = { API_KEY: apiKey };
    config.plugins.push(new webpack.DefinePlugin(env));
    return config;
  },
});
```

**package.json**
```
"dependencies": {
    "@shopify/app-bridge-react": "^1.25.0",
    "@shopify/koa-shopify-auth": "^3.1.65",
    "@shopify/polaris": "^5.0.0",
    "@zeit/next-css": "^1.0.1",
    "dotenv": "^8.2.0",
    "isomorphic-fetch": "^2.2.1",
    "js-cookie": "^2.2.1",
    "koa": "^2.13.0",
    "koa-session": "^6.0.0",
    "next": "^9.4.4",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
```

**Comment by mbaumbach** [comment]
@ShahinGh For Polaris 5, the import has changed from:

```javascript
import '@shopify/polaris/styles.css'
```
to
```javascript
import '@shopify/polaris/dist/styles.css'
```

You may want to check out the [migration guide](https://github.com/Shopify/polaris-react/blob/master/documentation/guides/migrating-from-v4-to-v5.md) as the tutorial may be slightly out of date.

**Comment by BPScott** [comment]
Thanks for the heads up @ShahinGh. I'll update the docs to account for the changed css import path.

**Comment by BPScott** [comment]
Docs have been updated with the new path!

**Comment by ShahinGh** [comment]
Your welcome @BPScott

**Comment by Kirill-Od** [comment]
> @ShahinGh For Polaris 5, the import has changed...

Thanks!!!

**Comment by aqoraan** [comment]
I'm still getting this error, even after using the new path:
![image](https://user-images.githubusercontent.com/26302517/106634185-34291f80-6588-11eb-8d5e-7b22d26e2b10.png)

**Comment by rapita** [comment]
Try use CDN:
`
            <React.Fragment>
                <Head>
                    ...
                    <link rel="stylesheet" href="https://unpkg.com/@shopify/polaris@6.0.1/dist/styles.css" />
                </Head>
                ...
                </React.Fragment>
`

**Comment by ptiger10** [comment]
Update: the path is currently 
`import '@shopify/polaris/build/esm/styles.css'`

**Comment by avibz1987** [comment]
Never heard of path changing in versioning updates... 
For sure, not in main files which are imported directly by most of this package users...

**Comment by nyrsimon** [comment]
> Update: the path is currently `import '@shopify/polaris/build/esm/styles.css'`

Worked for me on shopify polaris version 9.12.2
