### ISSUE TITLE
Icons in secondaryActions & actionGroups should accept config options

### ISSUE THREAD

**Issue by paulisloud** [Shopify/polaris-react#3148]
## Feature request summary

At present when configuring a `Page` using `secondaryActions` and `actionGroups`, icons can only be rendered with their default view (i.e. color). The `icon` parameter of each `action` should accept either the icon reference (as it does presently), or a config, allowing us to customize the icon display (i.e. color)

```jsx
<Page
  title="The title"
  secondaryActions={[
    {
      content: "Secondary action",
      accessibilityLabel: "Secondary action",
      icon: { source: CircleAlertMajorMonotone, color: "inkLightest" },
      onAction: () => alert("Seconary action"),
    },
  ]}
  actionGroups={[
    {
      title: "More actions",
      accessibilityLabel: "More actions",
      actions: [
        {
          content: "Do another action",
          accessibilityLabel: "Do another action",
          icon: AccessibilityMajorMonotone,
          onAction: () => alert("Adding vessel authorization"),
        }
      ]
    }
  ]}
>
  ...
</Page>
```

## Rationale

Users will not always want these icons to display at the default options (i.e. color, backdrop)

**Comment by kaelig** [comment]
Hi Paul, thank you for using Polaris and posting this feature request!

For context, my understanding is that the current restrictions are here to support design decisions and coherence across flows. Before changing the API to be more open, it would be useful to know more about what you're trying to solve.

Can you share one or several use-cases where you saw the need for this behavior (possibly using screenshots)?

**Comment by paulisloud** [comment]
Sure, my goal is just to be able to use the `color` field, available to [icons-as-component](https://polaris.shopify.com/components/images-and-icons/icon#navigation).

To me, it is less consistent to have these fields available in one place, and not in another. For example, I implement a design based on the assumption that I can control color values, but then when I want to use icons in the header actions, I find that they are uncustomizable.

Here is a screenshot of how I am using them. These are the icons I would like to be able to customize the color of.

<img width="1021" alt="Screen Shot 2020-08-03 at 6 02 56 PM" src="https://user-images.githubusercontent.com/1498200/89202960-0ef52d80-d5b4-11ea-89ae-7ca3203a1ea9.png">

Also, FYI, the `FraudProtectMajorMonotone` and associated icons (available here) are not exported from the `@shopify/polaris-icons` package.

**Comment by paulisloud** [comment]
This should still be open.
