### ISSUE TITLE
App Bride error on Safari "APP::ERROR::INVALID_CONFIG: shopOrigin must be provided"

### ISSUE THREAD

**Issue by GherghelAndrei** [Shopify/polaris-react#3159]
## Issue summary
I'm trying to auth my shopify app on Safari but it doesn't work. I get an error related to App Bridge. In Chrome and Mozilla it works, but on Safari it doesn't. I'm using Koa for backend and koa-shopify-auth node package for auth.

Here is a screenshot with the error
<img width="1048" alt="Screen Shot 2020-08-07 at 7 01 10 PM" src="https://user-images.githubusercontent.com/18439989/89665140-dd949e80-d8e0-11ea-97e6-62ebce5add65.png">

It's strange because I get this error during auth. On Chrome everything is working. If i go to Admin Dashboard and open my already authorized app on safari it works. The only problem is during authorization.

Here are some pictures with the code, I'm serving react from koa:
<img width="412" alt="Screen Shot 2020-08-07 at 7 07 38 PM" src="https://user-images.githubusercontent.com/18439989/89665382-4a0f9d80-d8e1-11ea-860a-54012b0d9bd0.png">

<img width="678" alt="Screen Shot 2020-08-07 at 7 06 09 PM" src="https://user-images.githubusercontent.com/18439989/89665340-382dfa80-d8e1-11ea-82e0-63e1a64aedb3.png">

## Expected behavior
The application should redirect to iframe and then App Bridge Provider get shopOrigin from Cookies and work.

## Actual behavior
App Bridge tries to get shopOrigin from cookies before redirecting to iframe and fails. 

## Steps to reproduce the problem

1. Open Safari and try to auth an app using koa-shopify-auth
1. Wait to get redirected to the iframe
1. Get the error in the console

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number:
- Browser: Safari
- Device: MacBook Pro
- Operating System:  macOS Mojave 10.14

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by BPScott** [comment]
For app-bridge problems please raise an issue in https://github.com/shopify/shopify-app-bridge
