### ISSUE TITLE
Address the use of italics in the Product Content guidelines

### ISSUE THREAD

**Issue by Jen-Bader** [Shopify/polaris-react#3160]
## Feature request summary
Add Product Content guidelines that recommend against using italics within product copy. 

## Rationale

Avoid using italics in product copy for the following reasons:
- Accessibility: italics don't get announced by screen readers
- Translation: other languages (e.g., Chinese, Korean, Japanese) don't use italics. Also, translators could overlook the italics and miss the intention for the including italics entirely.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by Jen-Bader** [comment]
Hi, is this something that can be addressed @jjgali?

**Comment by jjgali** [comment]
Hi, @Jen-Bader! Happy to help. If you have it, can you send me: 
- A proposal of the specific guidelines you want to add (and where you think they should live in the style guide)
- A link to any previous discussions/consensus on this topic, whether it be a GitHub issue, Slack thread, etc.

Thanks!
