### ISSUE TITLE
Github release 5.2.0 missing release notes

### ISSUE THREAD

**Issue by qw-in** [Shopify/polaris-react#3177]
Just a quick note that the `5.2.0` release does not have the release notes from the changelog

[github releases](https://github.com/Shopify/polaris-react/releases)
[changelog](https://github.com/Shopify/polaris-react/blob/master/CHANGELOG.md#520---2020-08-12)

**Comment by iamaminemesbah** [comment]
No release notes?

**Comment by kaelig** [comment]
Thank you for letting us know 👍  – I just updated the release notes: https://github.com/Shopify/polaris-react/releases/tag/v5.2.0
