### ISSUE TITLE
[TextField] Can't override icon prefix color

### ISSUE THREAD

**Issue by akmalhazim24** [Shopify/polaris-react#3180]
## Issue summary
TextField component with Icon prefix color not grayed as expected in Shopify search TextField.

If the TextField prefix using plain string, the color is grayed. However, when using the Icon together with the prefix (which in this case accepts React.ReactNode), it's not grayed like on Shopify screens.

## Expected behavior
TextField with Icon prefix grayed on any state.

![image](https://user-images.githubusercontent.com/34267739/90507588-b794b700-e188-11ea-91b2-8690a7744410.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/34267739/90506481-f0339100-e186-11ea-92da-36af3cc4ed6f.png)

## Steps to reproduce the problem

1. Use a TextField component and add an Icon as the prefix

## Reduced test case
```
<TextField
                prefix={<Icon source={SearchMinor} />}
                placeholder="Search products"
                value={searchProduct}
                onChange={setSearchProduct}
                connectedRight={<Button>Browse products</Button>}
              />
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 5.1.0
- Browser: Chrome 84.0.4147.125
- Device: MacBook Pro 2018
- Operating System: macOS 10.15.6

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 64.75 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 74.0.1
    Safari: 13.1.2
  npmPackages:
    @shopify/polaris: ^5.1.0 => 5.1.0 
    react: 16.13.1 => 16.13.1 
    react-dom: 16.13.1 => 16.13.1 
```

**Comment by kaelig** [comment]
Thank you, I can reproduce the issue. I was going to suggest you to use the `color` prop on the `Icon` component but it is overridden by `.Polaris-TextField svg`.

See reduced test case: https://codesandbox.io/s/wizardly-villani-rp6nm?file=/App.js

![Screen Shot 2020-08-18 at 5 03 33 PM](https://user-images.githubusercontent.com/85783/90577143-eb65e180-e174-11ea-94d1-262f760b58d2.png)

I'll change the title of this issue to ensure it's representative of the underlying issue.
