### ISSUE TITLE
[new DL] Navigation updates

### ISSUE THREAD

**Issue by yesenia-perezcruz** [Shopify/polaris-react#3188]
Updated type sizes and hover states
Nav goes back to being on the page background rather than on white

![Screen Shot 2020-08-20 at 8 56 05 AM](https://user-images.githubusercontent.com/47306956/90772775-03e41200-e2c3-11ea-93b2-9179fa1c8fd1.png)

**Comment by abhishekjakhar** [comment]
Can I pick this up?
