### ISSUE TITLE
[new DL] Make page background color darker

### ISSUE THREAD

**Issue by yesenia-perezcruz** [Shopify/polaris-react#3190]
Update page background to be slightly darker and more saturated

New hex- F4F5F6

![Screen Shot 2020-08-20 at 8 54 09 AM](https://user-images.githubusercontent.com/47306956/90772556-ba93c280-e2c2-11ea-9c99-6087f06c8ce1.png)

**Comment by abhishekjakhar** [comment]
Can I pick this up?
