### ISSUE TITLE
[new DL] Secondary button style styling update

### ISSUE THREAD

**Issue by yesenia-perezcruz** [Shopify/polaris-react#3191]
Secondary button style is no longer flat, and now has a slightly raised outline. 

- [ ] Change background color to white

- [ ] Add border

- [ ] Add dropshadow

![Screen Shot 2020-08-20 at 8 51 35 AM](https://user-images.githubusercontent.com/47306956/90772321-80c2bc00-e2c2-11ea-9bf9-2884a8df6769.png)

**Comment by kyledurand** [comment]
With this update we've got some similarities between default button and outline button. 

The major differences being:
- Outline button has a transparent background
- Outline has less drastic hover / pressed background changes

![image](https://user-images.githubusercontent.com/6844391/91445972-d4924f80-e844-11ea-99c0-28e55bbaea71.png)
![image](https://user-images.githubusercontent.com/6844391/91446216-2e931500-e845-11ea-8b41-ec79dac3942b.png)

Just thinking out-loud here but we definitely still need both variations. Outline button is used in places like within the banner where the banner background color needs to show through the button. 

And second, based mostly on [this comment](https://github.com/Shopify/polaris-react/pull/3202#pullrequestreview-476313478) and a brief chat with @alex-page . We may need some more alignment between text fields and default buttons. Where a connected field has a darker top border and button has a much more subtle box shadow

![image](https://user-images.githubusercontent.com/6844391/91447211-6c446d80-e846-11ea-8ccb-5cb4c49ebd93.png)
