### ISSUE TITLE
[new DL] Add subtle depth to input styles

### ISSUE THREAD

**Issue by yesenia-perezcruz** [Shopify/polaris-react#3192]
Update input styles to add subtle depth 

Before/after

![Screen Shot 2020-08-20 at 8 57 43 AM](https://user-images.githubusercontent.com/47306956/90772963-40b00900-e2c3-11ea-9cc5-b5b9f5e1a959.png)

**Comment by abhishekjakhar** [comment]
Can I pick this up?

**Comment by alex-page** [comment]
Hey @abhishekjakhar! We are currently rolling out a fix for this and I have a PR locally that I will put it up soon. Please continue reaching out in issues, In the future I would love you to drop in and pick up any issues like this!

**Comment by abhishekjakhar** [comment]
Hi @alex-page , I am looking for opportunities for contributing on UI and UX related things, I will keep commenting on issues to know if there is any for me, thank you! 
I would really love to pickup any issue and raise a PR for it.
