### ISSUE TITLE
[new DL] Remove inset box shadow in text fields

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-react#3194]
In the old DL, textfields have a subtle inset box shadow.

This was left in the new DL, both in polaris-react and polaris-rails.

- Polaris React: https://polaris-react.herokuapp.com/?path=/story/all-components-text-field--all-examples
- Polaris Rails: https://polaris-rails.shopify.com/components/text_field

Screenshot of the styles in polaris-react:
![Screen Shot 2020-08-20 at 9 08 00 AM](https://user-images.githubusercontent.com/85783/90800646-cb940200-e2c9-11ea-9a94-36c25e3fdcd6.png)

**Comment by abhishekjakhar** [comment]
Can I pick this up?

**Comment by alex-page** [comment]
Sorry @abhishekjakhar!! I am including this in my previous PR. If you want to get involved, just make PR's. Don't feel like you need to ask in the issue to contribute.
