### ISSUE TITLE
[new DL] ResourceList top bar container is truncated when sticky

### ISSUE THREAD

**Issue by loic-d** [Shopify/polaris-react#3196]
## Issue summary

In the new design language, the `ResourceList` top bar container (with resource items count + sort options) is truncated when sticky.

<img width="1010" alt="Screen Shot 2020-08-24 at 1 25 17 PM" src="https://user-images.githubusercontent.com/3925905/91081217-c2ca6580-e614-11ea-9401-5512eb085294.png">

I can reproduce the issue in production.

## Expected behavior

The top bar container should not be truncated.

## Actual behavior

The top bar container is truncated at the top.

## Steps to reproduce the problem

1. You can reproduce this issue on the Customers List page in the web admin

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
 System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 257.60 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
    Yarn: 1.21.1 - ~/.dev/yarn/1.21.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 77.0
    Safari: 13.1
  npmPackages:
    @shopify/polaris: 5.2.0 => 5.2.0 
    react: ~16.11.0 => 16.11.0 
    react-dom: ~16.11.0 => 16.11.0 
```

**Comment by BPScott** [comment]
It looks like the sticky-manager sets its topbar offset on initial page rendering. Thus it doesn't account for the Dev UI "toggle into new DL mode" switch

@loic-d would you be able to check if this issue occurs if you load the page with the new_design_langage beta enabled rather than opting into it within DevUI?

**Comment by loic-d** [comment]
I am running into the same issue when loading the page with `new_design_langage`

<img width="1419" alt="Screen Shot 2020-08-24 at 2 42 41 PM" src="https://user-images.githubusercontent.com/3925905/91083309-12f6f700-e618-11ea-94db-1abcce733747.png">

**Comment by kyledurand** [comment]
Addressed in https://github.com/Shopify/polaris-react/pull/3198
