### ISSUE TITLE
Date and Time picker

### ISSUE THREAD

**Issue by sky93** [Shopify/polaris-react#3209]
## Issue summary
I'm trying to implement start date and end date for my app discount. I searched through Polaris component but I couldn't find the one that Shopify uses.

## Expected behavior
I want to create a date and time picker like the one in Shopify discount section.

![image](https://user-images.githubusercontent.com/8404511/91841835-41a04d80-ec68-11ea-883f-826c388e2b57.png)

## Actual behavior

I used textfield with type of date. But it's not look like Shopify implementation.
https://codesandbox.io/s/shopify-polaris-react-typescript-playground-forked-03x5w

![image](https://user-images.githubusercontent.com/8404511/91842452-57624280-ec69-11ea-9e40-927b4bcdd8d7.png)

## Specifications

- Are you using the React components? Yes
- Polaris version number: 5.2.1
- Browser: Chrome 85
- Device: Desktop
- Operating System: Windows

**Comment by kazuyaseki** [comment]
This might not be the best way to do this, but I found using TextField with readonly property can produce similar output. onFocus handler is triggered when clicked

```
<TextField
  label="label"
  value=""
  readOnly
  onChange={() => {}}
  prefix={<Icon source={CalendarMajor} />}
  onFocus={() => {
    // show Datepicker component
  }}
/>
```

**Comment by bashunaimiroy** [comment]
For what it's worth, this would be useful today in a Shopify App I'm building. I'm surprised it doesn't exist

**Comment by shelley-verisart** [comment]
+1 on this. It's crazy that there's no combined date and time picker.

**Comment by gabeb03** [comment]
[Gadget](https://gadget.dev/) built a custom Polaris date/time picker: 

<img height="400" alt="image" src="https://github.com/user-attachments/assets/91f126d9-7183-4b06-b645-e452a814317c">

You can checkout the code for that component [here](https://github.com/gadget-inc/js-clients/blob/main/packages/react/src/auto/polaris/inputs/PolarisAutoDateTimePicker.tsx).
