### ISSUE TITLE
[new DL] DropZone example, when adding a file illustration needs to be updated

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#3210]
## Issue summary

The illustration in the example when uploading any file that isn't an image needs to be updated.

## Expected behavior

Uses the new illustration pattern.

## Actual behavior

![Screen Shot 2020-09-01 at 9 49 38 AM](https://user-images.githubusercontent.com/19199063/91859441-7694ac00-ec38-11ea-85fc-9a4f471ff1f1.png)

## Steps to reproduce the problem

1. Go to the [DropBox](http://polaris-react.herokuapp.com/?path=/story/all-components-drop-zone--all-examples) page and drag an svg file into the dropzone
1. The image uses the old illustration

**Comment by alekmackie** [comment]
The existing `note` icon in Polaris Icons is used elsewhere to represent a `document`, so I think it fits well here, too. That way, it should also be updated automatically when we ship the filled icons. 

Ideally, the content inside the dropzone would have some padding between it and the edge of the dropzone. Rough mockup to illustrate:

<img width="493" alt="Screen Shot 2020-09-01 at 12 29 20 PM" src="https://user-images.githubusercontent.com/5382363/91897185-c5e5d700-ec4e-11ea-832c-013197333e6a.png">

**Comment by alex-page** [comment]
This is blocked by https://github.com/Shopify/polaris-react/pull/3328, once that is merged we can update `app/components/LineItemImage/LineItemImage.tsx` to use the correct icon.
