### ISSUE TITLE
[New DL] Inline banner focus ring border radius doesn’t match banner itself 

### ISSUE THREAD

**Issue by ry5n** [Shopify/polaris-react#3213]
## Issue summary

The focus ring on the Banner component doesn’t match the radius of the component.

## Expected behavior

Looks like the component border radius needs to be larger, rather than the focus ring needing to be smaller.

## Actual behavior

![Screen Shot 2020-09-01 at 7 05 38 PM](https://user-images.githubusercontent.com/804014/91923989-8804a500-ec86-11ea-9d67-c523deb88830.png)

## Steps to reproduce the problem

1. Use the keyboard (Tab and Shift-Tab) to focus any banner

**Comment by alex-page** [comment]
This is fixed in https://github.com/Shopify/polaris-react/pull/3274

**Comment by ry5n** [comment]
🎉  😄
