### ISSUE TITLE
Add event parameter to the onChange event handlers

### ISSUE THREAD

**Issue by haseebanwar** [Shopify/polaris-react#3235]
## Feature request summary
Please add event parameter to the `onChange` event handlers of `TextField, Select` etc. components

Right now the onChange event handler receives `value` and `id` of the field where `id` is auto-generated by Polaris library. It is quite intimidating to set the value of a field with the auto-generated id.

## Rationale

If the event parameter is passed or the `name` of the field is passed, the code for updating the state for that field becomes much simpler. Currently with `Formik` or another form library, you have to do this for a field to be updated.

```
<Formik
  initialValues={{ name: ''}}
  validationSchema={RuleGroupSchema}
>
  {({ values, handleChange }) => (
    <Field
      name="name"
      label="Name"
      value={values.name}
      onChange={(value) =>
               handleChange({
               target: { id: 'name', value },
           })
       }
    />
    <Button submit>Submit</Button>
  )}
</Formik>
```
But if the `event` parameter is passed the code can be reduced to:

```
<Formik
  initialValues={{ name: ''}}
  validationSchema={RuleGroupSchema}
>
  {({ values, handleChange }) => (
    <Field
      name="name"
      label="Name"
      value={values.name}
      onChange={handleChange}
    />
    <Button submit>Submit</Button>
  )}
</Formik>
```

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by jhaastrup** [comment]
@haseebanwar  do you have an idea if this feature request has been fulfilled ? 
I am trying to use Formik with polaris form and i want to add a select field.

**Comment by haseebanwar** [comment]
@jhaastrup to my knowledge. It has not been fulfilled.
