### ISSUE TITLE
[new DL] Revert link and button link underline changes

### ISSUE THREAD

**Issue by jessebc** [Shopify/polaris-react#3239]
## Add underline prop for the link component

The link component is styled the same regardless of where it is being used. I think we should have the link component default to no underline, but add a prop to add an underline for when it is used in a string of text. 

When a link is part of a string of text, it requires an underline to stand out from the rest of the text and signify that it is interactive. 

![Screen Shot 2020-09-11 at 2 27 59 PM](https://user-images.githubusercontent.com/1591075/92960111-04437900-f43b-11ea-9b46-be570eec1c9d.png)

At other times, a link is included as a stand alone snippet of text either in a card or along side another action. In these cases, the location of the link is strong enough to signify that it is interactive. Having too many underlined links on a page introduces visual noise and is distracting. 

![Screen Shot 2020-09-11 at 2 29 38 PM](https://user-images.githubusercontent.com/1591075/92960311-6603e300-f43b-11ea-8eb1-486342d5e275.png)

**Comment by adriancerejo** [comment]
Hey could I take a shot at this issue?

**Comment by alex-page** [comment]
Hey @adriancerejo as this is a regression from past changes I think we should be responsible for fixing it. In the future If you see an issue you want to work on, please make a pull request 🚀 

---

Here is some extra context on this issue from @marytal 

> In production, with beta flag enabled:
> ![image](https://user-images.githubusercontent.com/8573756/93479360-d5f1ed80-f8c1-11ea-815e-454a55e0a567.png)
> 
> Figma: 
> ![image](https://user-images.githubusercontent.com/8573756/93479302-c5da0e00-f8c1-11ea-9046-0690149fbd6b.png)
> 
> Code being rendered above:
> https://github.com/Shopify/shopify/blob/27e5fb5553e005a4c10f28534bb56b6918edfabf/components/domains/app/views/admin/settings/domains/_traffic_redirect.html.erb#L7
> 
> Links should be either underlined by default or have the option to be underlined.
