### ISSUE TITLE
[new DL] Segmented buttons should not have a gap

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#3243]
> The reason they are shown differently in Figma today is because Figma doesn't do negative auto-layout spacing. Segmented buttons should look like this.
> 
> ![Screen Shot 2020-09-11 at 2 40 27 PM](https://user-images.githubusercontent.com/1591075/92961134-c182a080-f43c-11ea-856b-d8640f24c260.png)
> 
> I think we can want to stop connecting allll the fields though.
> 
> So instead of this:
> 
> ![Screen Shot 2020-09-11 at 2 41 48 PM](https://user-images.githubusercontent.com/1591075/92961261-f7278980-f43c-11ea-933d-301763302c5f.png)
> 
> we would do something like this:
> 
> ![Screen Shot 2020-09-11 at 2 41 36 PM](https://user-images.githubusercontent.com/1591075/92961282-fe4e9780-f43c-11ea-93ab-68314728ebef.png)

**Comment by cherrychau** [comment]
Other examples could be found on the "Create shipping label" page. 

**Under package and weight**

<img width="593" alt="Screen Shot 2020-09-15 at 4 07 34 PM" src="https://user-images.githubusercontent.com/51451924/93267875-51488780-f77a-11ea-9dcc-4176907ff28d.png">

**Custom forms modal**

<img width="287" alt="Screen Shot 2020-09-15 at 5 44 16 PM" src="https://user-images.githubusercontent.com/51451924/93268401-198e0f80-f77b-11ea-9506-4d675afd8511.png">

**Comment by cherrychau** [comment]
Hey @alex-page , I checked today and saw that the issue still persists on the Create shipping label page.

<img width="629" alt="Screen Shot 2020-09-30 at 3 13 42 PM" src="https://user-images.githubusercontent.com/51451924/94729393-969ab680-032f-11eb-8a15-14b31856ed68.png">
