### ISSUE TITLE
Can't click to text field if it's in a Popover in a Modal.

### ISSUE THREAD

**Issue by hoainam12k** [Shopify/polaris-react#3250]
## Issue summary

Can't click to text field if it's in a Popover in a Modal.

## Steps to reproduce the problem

1. Create a modal
1. Create button to active popover in the modal
1. Add textfield in popover
1. Open modal -> Open popover -> Can't click to textfield to change the text

## Reduced test case

Please check this [CodeSandbox](https://codesandbox.io/s/nifty-almeida-n63lo?file=/src/App.js).

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 5.2.1
- Browser: Firefox / Chrome
- Device: Macbook pro
- Operating System: Mac Mojave / Catalina

**Comment by nhcuongng** [comment]
I have the same problem. Is there any solution?
