### ISSUE TITLE
[new DL] Resource list items don't have have focus ring

### ISSUE THREAD

**Issue by AndrewMusgrave** [Shopify/polaris-react#3257]
Resource list items don't have focus rings anymore

![Screen Recording 2020-09-15 at 04 29 02 PM](https://user-images.githubusercontent.com/24610840/93262303-fd39a500-f771-11ea-9ff3-874f49917c5d.gif)

**Comment by alex-page** [comment]
@AndrewMusgrave do you know anyway to fix this quickly?

Removing this line shows the focus but breaks all the functionality. From what I can tell we need to raise the focus to a parent above the `ItemWrapper` so it is not affected by the `overflow: hidden`.

https://github.com/Shopify/polaris-react/blob/72748e3ddb7d60433ba6ed9d9895b390ffa7a283/src/components/ResourceList/ResourceList.scss#L209

**Comment by alex-page** [comment]
@AndrewMusgrave I made a draft PR, getting a bit stuck but I have moved the `overflow: hidden;` so it should now be showing the focus ring. It's still not showing so I'm looking into it.
