### ISSUE TITLE
[new DL] ActionList active items don't have the right style 

### ISSUE THREAD

**Issue by tleunen** [Shopify/polaris-react#3258]
## Issue summary

The current background of an active item is a dark grey. And it seems, after a discussion on slack with @jessebc that the right color should be blue.

> That should be a blue background and ideally we’d add a tick/check as well.

I'm not so sure about adding a checkmark automatically when the item is active, because that might lead to more problems for consumers maybe?

Slack thread: https://shopify.slack.com/archives/C01976E38NA/p1600262131088900

**Comment by jessebc** [comment]
Here's what I'm thinking from a design pov

![Screen Shot 2020-09-16 at 10 04 19 AM](https://user-images.githubusercontent.com/1591075/93348280-02473480-f804-11ea-9a96-94329d83913c.png)

https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/Admin-Design-Language-Web-Components?node-id=254%3A694

**Comment by jessebc** [comment]
![Screen Shot 2020-09-18 at 11 21 55 AM](https://user-images.githubusercontent.com/1591075/93615263-2a1fcf00-f9a1-11ea-9894-2e3277097d54.png)

I've updated the design in Figma to reflect the same design we use for an option list.
