### ISSUE TITLE
[Navigation] Larger nav items on mobile

### ISSUE THREAD

**Issue by jessebc** [Shopify/polaris-react#3265]
Just discovered that the UI Kit was incorrectly displaying each display item on mobile as 32px. They should be 40px. Type size should be 15px equivalent. 

https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/Admin-Design-Language-Web-Components?node-id=6879%3A1792

**Comment by ashwinnarayanan2001** [comment]
Hi Jesse! Just a quick clarification, what do you mean exactly by each 'display item'?

**Comment by jessebc** [comment]
Oops. That was suppose to be "Displaying each **nav** item".
