### ISSUE TITLE
App bar title no longer rendering 

### ISSUE THREAD

**Issue by JesseNoseworthy** [Shopify/polaris-react#3266]
Originally raised over [Slack](https://shopify.slack.com/archives/CQK6FNLJK/p16003633672470000).

<img width="373" alt="Screen Shot 2020-09-17 at 1 25 54 PM" src="https://user-images.githubusercontent.com/17211269/93505802-5415ba80-f8e9-11ea-8e53-ea3d26e6ca3a.png">

It looks like the app bar title is no longer rendering (see screenshots below):

**Before (example from a `staging` environment):**

<img width="1676" alt="Screen Shot 2020-09-17 at 1 21 16 PM" src="https://user-images.githubusercontent.com/17211269/93505878-74457980-f8e9-11ea-8768-085d4ad97c73.png">

**Currently (example from a `development` environment):**

<img width="1677" alt="Screen Shot 2020-09-17 at 1 21 24 PM" src="https://user-images.githubusercontent.com/17211269/93505871-70b1f280-f8e9-11ea-93f1-b6bd92b0590c.png">

**Comment by alex-page** [comment]
Amazing, thanks Jesse. It looks like this is the component you need https://shopify.dev/tools/app-bridge/react-components/titlebar. There is a section on “Using <TitleBar> with the Polaris <Page> component” 🚀.

Feel free to close the issue if you have no further problems.

**Comment by JesseNoseworthy** [comment]
Closing. Thanks again! 🙏
