### ISSUE TITLE
[new DL] Focus state extends to the information around the field.

### ISSUE THREAD

**Issue by cherrychau** [Shopify/polaris-react#3270]
When clicking on the information around the textfield, the focus state surrounds the information. I've only noticed this behaviour with this particular field. You can replicate this by going into the Create shipping label page, and clicking "Edit customs information (must be an international order).

![editcustomsinformation](https://user-images.githubusercontent.com/51451924/93530704-0494b600-f90c-11ea-8c19-cd7a12d553c7.gif)

**Comment by alex-page** [comment]
@cherrychau this is unrelated to polaris, this would be in the implementation. Is there a `tabindex` on the wrapping container.
