### ISSUE TITLE
[new DL] Media icon from an Option list item is not "colored" when selected

### ISSUE THREAD

**Issue by tleunen** [Shopify/polaris-react#3321]
## Issue summary

Even if the `media` is a ReactNode, I think that Polaris should automatically update the color for any icons in the option when selected?

![image](https://user-images.githubusercontent.com/1972567/94298499-3f15d880-ff34-11ea-89ce-f68b055a500f.png)

**Comment by alex-page** [comment]
@tleunen this should be fixed now http://polaris-react.herokuapp.com/iframe.html?id=all-components-action-list--action-list-with-destructive-item&contexts=New%20Design%20Language%3DEnabled%20-%20Light%20Mode
