### ISSUE TITLE
Missing Dependency When Running Example Typescript App

### ISSUE THREAD

**Issue by fiveNinePlusR** [Shopify/polaris-react#3334]
## Issue summary

Basically an copy of this issue https://github.com/Shopify/polaris-react/issues/3130 except it happens from a fresh pull of the master branch of this repository and in one of the example apps. It's possible some of the other example apps have this issue as well.

## Expected behavior

cd examples/create-react-app-ts-react-testing/

yarn install or npm install

yarn start or npm run should start the server without an error

## Actual behavior

yarn start and npm run both error with the following:

<details>
./node_modules/@shopify/polaris/dist/styles.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/@shopify/polaris/dist/styles.css)
Error: Cannot find module '@shopify/browserslist-config'
Require stack:
- /Users/testuser/project/examples/polaris-react/examples/create-react-app-ts-react-testing/node_modules/browserslist/node.js
- /Users/testuser/project/examples/polaris-react/examples/create-react-app-ts-react-testing/node_modules/browserslist/index.js
- /Users/testuser/project/examples/polaris-react/examples/create-react-app-ts-react-testing/node_modules/postcss-browser-comments/index.cjs.js
- /Users/testuser/project/examples/polaris-react/examples/create-react-app-ts-react-testing/node_modules/postcss-normalize/index.cjs.js
- /Users/testuser/project/examples/polaris-react/examples/create-react-app-ts-react-testing/node_modules/react-scripts/config/webpack.config.js
- /Users/testuser/project/examples/polaris-react/examples/create-react-app-ts-react-testing/node_modules/react-scripts/scripts/start.js
    at Array.reduce (<anonymous>)</details>

## Steps to reproduce the problem

1. cd examples/create-react-app-ts-react-testing/
1. yarn install
1. yarn start or npm run should start the server without an error
1. browse localhost:3000

## Reduced test case

the example app examples/create-react-app-ts-react-testing/ in the repo

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number:
├─ @shopify/polaris-icons@3.12.0
├─ @shopify/polaris-tokens@2.12.3
├─ @shopify/polaris@5.0.0
│  ├─ @shopify/polaris-icons@^3.10.0
│  ├─ @shopify/polaris-tokens@^2.12.3
- Browser: Firefox
- Device: Mac
- Operating System: macOS

**Comment by BPScott** [comment]
This was fixed in https://github.com/Shopify/polaris-react/pull/3132 which was released as part of v5.1.0. We just need to update the example to use a newer version of `@shopify/polaris`.

**Comment by harismh** [comment]
FYI: This same issue happens in the create-react-app example as well. Running yarn install && yarn start yields:

```
Failed to compile.

./node_modules/@shopify/polaris/dist/styles.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/@shopify/polaris/dist/styles.css)
Error: Cannot find module '@shopify/browserslist-config'
    at Array.reduce (<anonymous>)
```

Upping `@shopify/polaris` in the CRA's package.json from `^5.0.0` to `^5.1.0` fixes the problem. Happy to submit a PR for this if that isn't done already.

**Comment by BPScott** [comment]
If you want to submit a PR that'd be great, thank you! Can I request that you bump the version in all projects in the examples folder. It'd be good to keep them all in sync.

**Comment by harismh** [comment]
@BPScott Done: https://github.com/Shopify/polaris-react/pull/3362 

Don't think this warrants any changelog updates.
