### ISSUE TITLE
Consistency in Resource Items

### ISSUE THREAD

**Issue by jessebc** [Shopify/polaris-react#3336]
Each index view currently has a slightly different visual treatment. 

![Frame 11](https://user-images.githubusercontent.com/1591075/94690230-d9439b00-02fd-11eb-8bad-0548cc521eb8.png)

We need to align these views to be consistent across each resource. The figma link below outlines states for mouse states, selected states as well as archived and cancelled states. 

In priority order we should focus on:
1. Title: font-weight, color, text-decoration
2. Surface: Use the same hover, pressed, selected states across resources. 

Figma link to different states:
https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/Admin-Design-Language-Web-Components?node-id=23386%3A41

Screenshot of default states. Figma doc also contained archived and cancelled states. 

![Screen Shot 2020-09-30 at 9 45 36 AM](https://user-images.githubusercontent.com/1591075/94693437-b61aea80-0301-11eb-9e57-249b47f8d644.png)

**Comment by alex-page** [comment]
Thank you Jesse 🙌

**Comment by alex-page** [comment]
We can also revert this https://github.com/Shopify/web/pull/30222

**Comment by alex-page** [comment]
This is also included https://github.com/Shopify/polaris-react/issues/3579
