### ISSUE TITLE
Fine tuning button and text-field

### ISSUE THREAD

**Issue by jessebc** [Shopify/polaris-react#3364]
The top border of text inputs are still a tad too harsh. In the future when we redesign the filter component, we can update these styles. For right now we'll work to improve on what we have. 

![Screen Shot 2020-10-02 at 9 43 52 AM](https://user-images.githubusercontent.com/1591075/94929993-c95dbf80-0493-11eb-95aa-aed7d67dce29.png)

Can we work on this one together @martenbjork ?

**Comment by martenbjork** [comment]
@jessebc Done! This is how the colors look in the latest build:

<img width="261" alt="Screen Shot 2020-10-07 at 11 24 33 AM" src="https://user-images.githubusercontent.com/875708/95351958-bbdb7780-088f-11eb-8d2e-445baa713ad3.png">
<img width="230" alt="Screen Shot 2020-10-07 at 11 24 49 AM" src="https://user-images.githubusercontent.com/875708/95351961-bc740e00-088f-11eb-9f15-e0ee5106ab25.png">
