### ISSUE TITLE
Button icon loading in dark mode looks broken

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#3381]
The icon is not the correct color

![Screen Shot 2020-10-06 at 8 39 44 AM](https://user-images.githubusercontent.com/19199063/95202967-0c7ba380-07b0-11eb-9266-c728d9305bb6.png)

This also needs to be implemented in rails.

**Comment by kyledurand** [comment]
`--p-icon-on-interactive` is probably the value we want here
