### ISSUE TITLE
[new DL] White space around the page title

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#3383]
![screen_shot_2020-10-05_at_9 51 45_am](https://user-images.githubusercontent.com/19199063/95203905-5fa22600-07b1-11eb-9140-04bda2f53d63.png)

![spacing](https://user-images.githubusercontent.com/19199063/95203955-734d8c80-07b1-11eb-8bbb-5f746f1d4a12.gif)

**Comment by jessebc** [comment]
Would it be possible to have the meta data go full width and sit underneath the buttons?

Something like this?

![image](https://user-images.githubusercontent.com/1591075/95205819-e6580280-07b3-11eb-98b0-379fabf94ea2.png)

**Comment by kyledurand** [comment]
@jessebc Yep, it's just not using the new header prop but I have a follow up PR in web that makes use of it here: https://github.com/Shopify/web/pull/32433. I just need to rebase and get another 👍  before it ships
