### ISSUE TITLE
Triggering multiple flash notices only shows first

### ISSUE THREAD

**Issue by wardoost** [Shopify/polaris-react#339]
# Issue summary

When 2 [`easdk.showFlashNotice()`](https://github.com/Shopify/polaris/blob/master/documentation/Embedded%20apps.md#easdkshowflashnotice) calls happen quickly after each other only the first flash notice is shown.

## Expected behavior

The flash notices stack on top of each other or the last flash notice replaces the first flash notice message. An option could be added to let the developer choose behaviour happens.

## Actual behavior

Only the first flash notice is displayed.

## Steps to reproduce the problem

1. Make a button in your embedded app call `easdk.showFlashNotice(<your-message>)`
1. Click the button twice within 3 seconds

## Specifications

- Polaris version: v2.0.0
- React version: 16.3.2
- Browser:  Google Chrome v66.0.3359.181
- Device: Macbook Pro
- Operating System: macOS High Sierra

**Comment by ry5n** [comment]
Thanks for reporting this @wardoost. It looks like an issue with the EASDK itself. I’ll ask one of the EASDK engineers working on it to look into it further.

**Comment by danrosenthal** [comment]
Closing this issue in favor of the linked AppBridge issue.
