### ISSUE TITLE
[Collapsible] Open filters animation is janky

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#3390]
![janky-slide](https://user-images.githubusercontent.com/19199063/95243747-14067100-07df-11eb-8a55-94664754c307.gif)

http://polaris-react.herokuapp.com/iframe.html?id=all-components-filters--all-examples&contexts=New%20Design%20Language%3DEnabled%20-%20Light%20Mode&viewMode=story

**Comment by johanstromqvist** [comment]
![janky-collapsible](https://user-images.githubusercontent.com/38329124/95248050-b6752300-07e4-11eb-9fcb-5bcdc858da66.gif)

- Seems to be a conflict with the dimensions of parent and child container.
- Don’t think it needs to be fixed. Better to remove the problem.
- The most clear and efficient solution would be to just uncover/cover the content, similar to how the close transition is defined but without fade effect.
- We should design a standardized pattern for this. Similar need in main navigation, and surely in other places too.

**Comment by alex-page** [comment]
This was resolved in https://github.com/Shopify/polaris-react/pull/3779
