### ISSUE TITLE
[new DL] Textfield has a darker top border

### ISSUE THREAD

**Issue by tleunen** [Shopify/polaris-react#3396]
## Issue summary

We can currently see it in the admin and it creates a weird contrast with other elements such as buttons or dropdown beside it.
![image](https://user-images.githubusercontent.com/1972567/95327333-def72e80-0871-11eb-8a41-6907c697faad.png)

According to figma, the field shouldn't have any different border-top color.
https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/Admin-Design-Language-(Web)%3A-Components?node-id=376%3A12

Here's the issue:
![image](https://user-images.githubusercontent.com/1972567/95327463-14038100-0872-11eb-8a9e-c95a4c72ac12.png)

**Comment by alex-page** [comment]
@tleunen we are still iterating these values but this is currently intended. I'll let you know if we make any additional changes.
