### ISSUE TITLE
Buttons in banners have underlined text

### ISSUE THREAD

**Issue by AdamWhitcroft** [Shopify/polaris-react#3423]
Just noticed our banner buttons have underlined text.

<img width="951" alt="Screen Shot 2020-10-08 at 9 58 10 AM" src="https://user-images.githubusercontent.com/861526/95468766-d889b500-094c-11eb-946f-d948f407c659.png">

**Comment by alex-page** [comment]
This will be in the next release. Thanks @AdamWhitcroft
