### ISSUE TITLE
[ResourceList] Invalid HTML rendered in ResourceList component

### ISSUE THREAD

**Issue by francinen** [Shopify/polaris-react#3445]
## Issue summary
I ran a Lighthouse accessibility audit on a page using the Resource List, and it detected an issue with the component's markup: It's expecting the component's `ul` node to only contain `li`, `script`, or `template` elements but we're rendering other types of elements as well.

![image](https://user-images.githubusercontent.com/8534230/95598194-a431f980-0a1d-11eb-9053-b958b960c640.png)

## Expected behavior
According to MDN, `div`s are not permitted content for unordered lists; it should only contain `li`, `script`, or `template` elements: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul

However, `div`s and other flow content are permitted children for `li` elements.

![image](https://user-images.githubusercontent.com/8534230/95598868-5f5a9280-0a1e-11eb-9368-9ecadf3b276b.png)

We can consider refactoring the markup to avoid nesting `div`s inside the `ul`. The markup used in the Polaris Rails component reflects the ideal solution:

|Polaris React|Polaris Rails
|---|---
|![image](https://user-images.githubusercontent.com/8534230/95598519-012daf80-0a1e-11eb-8970-bc73e9e407e3.png)|![image](https://user-images.githubusercontent.com/8534230/95599328-ed367d80-0a1e-11eb-8511-d0539397d854.png)

## Steps to reproduce the problem

1. Run a Lighthouse accessibility audit on a page that uses the Resource List component.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by dfmcphee** [comment]
Looking at the `AppList`'s [ResourceListItem](https://github.com/Shopify/web/blob/master/app/sections/Apps/AppList/components/AppIndexResourceList/components/AppIndexResourceListItem/AppIndexResourceListItem.tsx#L205) it looks like they are rendering that wrapping `div`. We recently started throwing a warning in dev if consumers do this, so that will most likely have to be updated there.
