### ISSUE TITLE
Alignment issues using Stack component

### ISSUE THREAD

**Issue by reflog** [Shopify/polaris-react#348]
# Issue summary

![image](https://user-images.githubusercontent.com/109876/41102945-ab9e0cb2-6a70-11e8-85f8-8343d5acbad3.png)

## Expected behavior

Items should align

## Steps to reproduce the problem

Here's a demonstration: https://codesandbox.io/s/m7p2mz1qny

## Specifications 

- Polaris version: 2.1.1
- React version: 16.3
- Browser: Chrome
- Device: Desktop
- Operating System: Win10

I've tried different combinations of alignment options, with no luck. 
Any suggestions?

Thanks!

**Comment by mattchidley** [comment]
We also have experienced the same problem.

I think the problem is that the labels for the TextField components added a "margin" where your garbage button does not.

Our fix was just to wrap the button in a div with a margin of 29px. But I do agree that polaris should come up with a property we can add onto the component to lower it / align it with the rest of the components in the FormLayout Group.

**Comment by ry5n** [comment]
Currently there isn’t an official solution, but I think we’ve run into this before ourselves. I knocked out a quick prototype: https://codesandbox.io/s/73yy6q90x6

It still breaks under some circumstances (long field labels) but I’m wondering if this is something along the right lines.

**Comment by solonaarmstrong** [comment]
Cleaning up issues. I'm not sure this is actually a bug. The alignment is set to `fill`, which uses `align-items: stretch`, which stretches items to fills the container, but **still respects min-width/max-width**. I don't think the intention would be to stretch a button's height and distort it.

The text field is being treated as one item within the stack, including its label, so it would take some tweaking to align the button. Something like:

```
<Stack
            alignment="leading"
            distribution="fill"
            spacing="tight"
            wrap={false}
          >
            <TextField label="Field 1" onChange={() => {}} />
            <TextField label="Field 2" onChange={() => {}} error="error" />
            <TextField label="Field 3" onChange={() => {}} />
            <div style={{margin: '20px 0'}}>
              <Button icon="delete" destructive />
            </div>
          </Stack>
```
