### ISSUE TITLE
Page alignment and spacing tweaks

### ISSUE THREAD

**Issue by AdamWhitcroft** [Shopify/polaris-react#3481]
The status pills in our page headers are bottom-heavy in terms of alignment (`Paid` and `Unfulfilled`).

![Group 3](https://user-images.githubusercontent.com/861526/96009433-a7a6f580-0e0e-11eb-9399-859263876f5b.png)

As an additional small note, the Next/Prev buttons aren't the same height at the Back button.

**Comment by jppellerin** [comment]
I'm adding this one as well: Secondary action's `hover` state overlaps the status pills when they are too close to one another (see right-most status `Archivée`)

![image](https://user-images.githubusercontent.com/4185657/96116816-0f188000-0eb7-11eb-9b05-62419051c61a.png)

This is from the Order Details page (no problem in English as all words fit very well).
