### ISSUE TITLE
[New DL] Custom themes being overridden

### ISSUE THREAD

**Issue by SelenaJL** [Shopify/polaris-react#3485]
## Issue summary
Turning on the new design language in Web's `AppProvider` renders a containing div with inline variable styles set to the new DL colors. However, custom overrides in subcomponents (i.e. the `ThemeProvider`) do not change the variables in their containing divs. Instead, they seem to match the new DL styles.

See [this sandbox](https://codesandbox.io/s/kind-bas-161m3?file=/App.js:7382-7406) for a clear example of the expected/actual behaviour outlined below.

## Expected behavior
1. Set `features={{ newDesignLanguage: true }}` in the `AppProvider`
2. Use the `ThemeProvider` to override the TopBar background to red (#f00)
3. Observe the containing div includes this custom style and thus the TopBar background is now red

## Actual behavior
1. Set `features={{ newDesignLanguage: true }}` in the `AppProvider`
2. Use the `ThemeProvider` to override the `TopBar` background to red (#f00)
3. Observe the containing div doe snot include the custom style and thus the TopBar background is still white (as per the new DL colors)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.1.1
- Browser: any
- Device: any
- Operating System: any

**Comment by alex-page** [comment]
This is how it is intended to work. I am going to follow up with @SelenaJL for their problem.
