### ISSUE TITLE
Icon updates on customer page

### ISSUE THREAD

**Issue by allylane** [Shopify/polaris-react#3505]
<img src="https://user-images.githubusercontent.com/17570703/96305343-bf77a880-0fcb-11eb-8cbf-dda705675fda.PNG" width="400px">

**Comment by alex-page** [comment]
Can't get the rails customer page to load in production. This might of been a weird state you got into @allylane if you can find this in another store please let me know.

**Comment by alex-page** [comment]
<img width="681" alt="screen_shot_2020-10-28_at_10 57 39_am" src="https://user-images.githubusercontent.com/19199063/97454540-40f50200-190d-11eb-86b1-228598de212b.png">
