### ISSUE TITLE
Horizontal scrolling on Detail pages - Web view

### ISSUE THREAD

**Issue by allylane** [Shopify/polaris-react#3506]
![IMG_2717](https://user-images.githubusercontent.com/17570703/96305436-e03ffe00-0fcb-11eb-95d1-5f038d12ba3b.PNG)

**Comment by kpeatt** [comment]
This is happening on all indexes. I tested Products and Customers as well as the Logistics subpage indexes. ![image](https://user-images.githubusercontent.com/447683/96522840-4df55f80-1242-11eb-8e12-289edc6ecbf5.png)

**Comment by bizsanford** [comment]
👋 Adding additional info 

Shouldn’t be able to scroll indexes left and right on mobile web:
- Side scroll issue + gets stuck on right side exists for: orders, products, customers
- Side scroll issue (but bounces back) exists for: inventory, gift cards
- _(For reference, no issues on these indexes: draft orders, abandoned checkouts, purchase orders, transfers, collections, discounts)_
