### ISSUE TITLE
No built-in way to dismiss callout cards

### ISSUE THREAD

**Issue by andrewpye** [Shopify/polaris-react#353]
The "best practices" documentation for the `CalloutCard` component state that cards "should be dismissable so merchants can get rid of cards about features they’re not interested in". However, unlike other components (e.g. `Banner`), there doesn't seem to be any built-in way to dismiss the callout card. What's the recommended way of doing this?

**Comment by vladucu** [comment]
This would be really nice, I would also add that a more generic popover at the top-right with various actions would be even better (like Shopify Admin home page has)

example
<img width="730" alt="screen shot 2018-06-19 at 2 00 08 am" src="https://user-images.githubusercontent.com/160955/41566578-cebc2ab0-7364-11e8-9565-38813d58ca5a.png">

**Comment by chloerice** [comment]
@andrewpye Thanks for raising this. I'll add this to our internal project board.

**Comment by ry5n** [comment]
Marking this as a bug rather than a feature request as it’s something the component should be capable of.
