### ISSUE TITLE
[PageActions] destructive actions look different in old DL

### ISSUE THREAD

**Issue by sylvhama** [Shopify/polaris-react#3538]
<img width="977" alt="Screen Shot 2020-10-21 at 9 59 27 AM" src="https://user-images.githubusercontent.com/5626729/96731656-818cd280-1385-11eb-9823-56a4d71f9b28.png">
<img width="272" alt="Screen Shot 2020-10-21 at 10 00 16 AM" src="https://user-images.githubusercontent.com/5626729/96731661-82256900-1385-11eb-979d-a92ccf040af6.png">

**Comment by ashwinnarayanan2001** [comment]
Going to close this issue because we're moving to an Outlined Destructive Action (https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/Admin-Design-Language-(Web)%3A-Components?node-id=922%3A4327)
