### ISSUE TITLE
Tooltip only accepts string contents

### ISSUE THREAD

**Issue by YannCedric** [Shopify/polaris-react#3541]
## Feature request summary

It would be nice to have the Tooltip component accept React.Node or something more general than a string.

<img width="257" alt="Screen Shot 2020-10-21 at 11 48 38 AM" src="https://user-images.githubusercontent.com/22302788/96744740-5dd08900-1393-11eb-895a-79895435b2ea.png">

## Rationale

This would allow to show shortcuts in the tooltip or things like that. 
(See https://github.com/Shopify/online-store-ui/pull/2172#discussion_r508653773)

**Comment by emma-boardman** [comment]
I would be worried about the accessibility implications here - the tooltip needs to be accessible via "hover, focus, tap, or click." [1], but the PreviewModeSelector currently relies on focus, tap, or click to open. 

Restricting the tooltip to hover only (in order to maintain the focus, tap, and click activation of the PreviewModeSelector) would prevent keyboard or assistive technology users from accessing the tooltip content.

[1] https://polaris.shopify.com/components/overlays/tooltip

**Comment by BPScott** [comment]
We've had plenty of cases where we type component arguments as being stricter than what React allows for.  Generally this was to err on the side of "it's easier to allow for new functionality than to stop people using existing functionality". In many cases we've accepted PRs for updating typings from `string`s to `React.ReactNode`s (e.g. #2325).

 I'm slightly wary of doing this for Tooltip's content prop as keeping it typed to string forces people to make sure they don't get tempted to write long form or styled content into the tooltip text as text is most readable and accessible. 


@alex-page, @kyledurand , @dleroux Thoughts? How do you fee about loosening this type?

**Comment by alex-page** [comment]
I think it is sensible, even being able to add `<Icon>` may be useful at times.

**Comment by kyledurand** [comment]
I'm down for that change. We need to trust that consumers will do the right thing when it comes to a11y

**Comment by dleroux** [comment]
Yes, I agree too. The use-case presented is a valid one.

**Comment by BPScott** [comment]
Yay consensus! @YannCedric wanna send us a PR?

**Comment by YannCedric** [comment]
Yep 
So, before I do so, I want to mention that the particular use-case for which this was needed has been reverted, and we may not need this change anymore in https://github.com/Shopify/online-store-ui/pull/2172#discussion_r508653773.

But for the general use-case, should I still submit the pr ?

**Comment by BPScott** [comment]
Yeah this feels like it'll be useful to anybody else.
