### ISSUE TITLE
Error: 'No Features were provided.'

### ISSUE THREAD

**Issue by spunkyshooter** [Shopify/polaris-react#3548]
## Issue summary
https://prnt.sc/v4kemu See the image: Due to undefined in the (1) line, the features in (2) would be undefined.
Hence it always throws error.

## Steps to reproduce the problem

1. import { Page} from "@shopify/polaris";
2. Just use Page component. 

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 5.8.6
- Browser: Chrome
- Device: -
- Operating System: Windows

### Error logs
Server Error
Error: No Features were provided.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
useFeatures
file:///E:/project/node_modules/@shopify/polaris/dist/index.js (855:11)
Page
file:///E:/project/node_modules/@shopify/polaris/dist/index.js (13456:7)
processChild
file:///E:/project//node_modules/react-dom/cjs/react-dom-server.node.development.js (3353:14)
resolve
file:///E:/project/node_modules/react-dom/cjs/react-dom-server.node.development.js (3270:5)
ReactDOMServerRenderer.render
file:///E:/project/node_modules/react-dom/cjs/react-dom-server.node.development.js (3753:22)
ReactDOMServerRenderer.read
file:///E:/project/node_modules/react-dom/cjs/react-dom-server.node.development.js (3690:29)
```bash

```

**Comment by BPScott** [comment]
Your whole app needs to be wrapped in an AppProvider component, which provides the features set to the context.
