### ISSUE TITLE
Remove automated a11y test exceptions

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#3565]
## Issue summary

We need to fix all of these issues in our examples

https://github.com/Shopify/polaris-react/blob/6824807f63ce6e02be3522fb0b818f7eebe51b43/scripts/accessibility-check.js#L86-L157

## Expected behavior

There is no need for exceptions.

## Actual behavior

There is a bunch of issues that need to be addressed across Polaris.

**Comment by BPScott** [comment]
@dfmcphee found a handful of these fixes in #3284, but we removed them before merging the PR so they'd be good quick follow ups
