### ISSUE TITLE
Tooltip HTML Example is missing markup for the tooltip portion

### ISSUE THREAD

**Issue by vcosolapova** [Shopify/polaris-react#357]
# Issue  summary
The HTML example for the [tooltip](https://polaris.shopify.com/components/overlays/tooltip) is missing tooltip markup.

## Expected behaviour
The HTML example should show markup for both: the link that triggers the tooltip, as well as, the tooltip itself.

## Actual behaviour
The HTML example only shows markup for the link that triggers the tooltip:

`<div style="padding: 75px 0px;"><span><button class="Polaris-Link" tabindex="0" aria-describedby="TooltipContent1">Order #1001</button></span></div>`

## Steps to reproduce the problem
1. Navigate to https://polaris.shopify.com/components/overlays/tooltip
2. Click on HTML tab of the example

**Comment by solonaarmstrong** [comment]
Thank you for bringing this is to our attention.

**Comment by dfmcphee** [comment]
This should be fixed now in the style guide.

**Comment by chloerice** [comment]
(The style guide fix depends on #774, which has shipped to master but won't be fixed in the style guide until the next release.)
