### ISSUE TITLE
[New DL] Orders list visual treatment for open vs closed orders should be more discernible

### ISSUE THREAD

**Issue by AdamWhitcroft** [Shopify/polaris-react#3579]
Prior to design language changes, the orders index had a pretty clear visual difference between open and archived (closed) orders.

Blue = open
Grey = archived

<img width="488" alt="Screen Shot 2020-10-28 at 3 05 57 PM" src="https://user-images.githubusercontent.com/861526/97484561-3ea39f80-192f-11eb-854c-76d5ca27bcb0.png">

Merchants making use of our auto-archiving feature (or manually archiving) have let us know they find the new style harder to quickly parse.

<img width="584" alt="Screen Shot 2020-10-28 at 3 09 36 PM" src="https://user-images.githubusercontent.com/861526/97484806-9f32dc80-192f-11eb-9b6a-4d1f551ba6e9.png">

**Comment by alex-page** [comment]
@kyledurand assigning you as you were working on resource items.

**Comment by kyledurand** [comment]
I think this can be closed now, this is how it looks in production:

![image](https://screenshot.click/Felted_-_Slim_Wallets__Orders__Shopify_2020-11-11_09-51-26.png)

@AdamWhitcroft feel free to re-open this if it still doesn't meet merchants needs

**Comment by AdamWhitcroft** [comment]
I forget where we landed on styles, could you break down each of those lines for me @kyledurand ?

**Comment by kyledurand** [comment]
For sure, here's the [figma file](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/Admin-Design-Language-(Web)%3A-Components?node-id=23386%3A41) as well.

In order from top to bottom in the screenshot above we'd have default first, then cancelled, then archived, then cancelled and archived.

**Comment by AdamWhitcroft** [comment]
Is open and archived the same font weight?

**Comment by kyledurand** [comment]
Yep good catch. I'll address that here: https://github.com/Shopify/web/pull/34670

The update will look like this:
![image](https://screenshot.click/Shop_1__Orders__Shopify_2020-11-11_17-10-26.png)
