### ISSUE TITLE
ResourceList loading overlay appears under content

### ISSUE THREAD

**Issue by lhoffbeck** [Shopify/polaris-react#3605]
## Issue summary
On the [ResourceList](https://polaris.shopify.com/components/lists-and-tables/resource-list) component, the loading spinner 
and overlay don't appear above the resourcelist content. In my (naive) investigation, it looks like the issue is that `SpinnerContainer` has `z-index: 3` and LoadingOverlay has `z-index: 2`, but the `Polaris-ResourceItem__Container` also has `z-index: 2` so there's a conflict.

## Expected behavior
Loading spinner and overlay should appear above all ResourceList content. (note: I've adjusted the overlay color so it's easier to see)
<img width="986" alt="Screen Shot 2020-11-05 at 1 10 15 PM" src="https://user-images.githubusercontent.com/3619012/98279700-4800bd80-1f68-11eb-8ff2-1d5d236af554.png">

## Actual behavior
Spinner appears over content but overlay appears underneath.
<img width="1000" alt="Screen Shot 2020-11-05 at 1 08 50 PM" src="https://user-images.githubusercontent.com/3619012/98279626-2f90a300-1f68-11eb-8e71-1645ce0a5054.png">

## Reduced test case

https://codesandbox.io/s/compassionate-monad-2pxxn?file=/App.js

## Specifications

```bash
  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 226.77 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.4 - ~/.dev/yarn/1.22.4/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 86.0.4240.183
    Chrome Canary: 88.0.4316.0
    Firefox: 82.0.2
    Firefox Developer Edition: 83.0
    Safari: 13.1.1
  npmPackages:
    @shopify/polaris: ^5.10.0 => 5.10.0 
    react: ~16.14.0 => 16.14.0 
    react-dom: ~16.14.0 => 16.14.0 
```

**Comment by amrocha** [comment]
Thank you so much for the detailed issue! I'll see if we can find a time to look at this before the next major release
