### ISSUE TITLE
Push IndexTable and IndexProvider into master

### ISSUE THREAD

**Issue by GhostApps** [Shopify/polaris-react#3637]
## Feature request summary

#3097 describes an IndexTable that I would like to try out but it seems to be stuck in PR purgatory, please merge it in as experimental or give an estimate of when I can expect it maybe @AndrewMusgrave is best placed to do this?

## Rationale

#2738 shows why it was introduced

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by EdwardGoomba** [comment]
@GhostApps `IndexTable` is now in release `6.1.0` if you were still looking to use it.

@AndrewMusgrave This can be closed?
