### ISSUE TITLE
[Button] add iconPosition support

### ISSUE THREAD

**Issue by robertmeessen** [Shopify/polaris-react#3665]
## Button

Add iconPosition support to display icons on the right side as proposed in this feature request: https://github.com/Shopify/intl-shipping-methods/issues/910

Before / After:

![image](https://user-images.githubusercontent.com/72969127/100640888-2f04e580-3337-11eb-9222-45d049f92e5a.png)

## Added Props

List props and type declarations:

> - **iconPosition** (optional): `left` | `right` defaults to `left` – sets the order of the icon markup inside the button

**Comment by tejesh0** [comment]
![image](https://github.com/Shopify/polaris/assets/6937958/e5a458a8-a205-4f11-a429-7e4a8dc548fe)

https://shopify.dev/docs/apps/design-guidelines/user-experience/onboarding

@robertmeessen @BPScott  the onboarding docs suggest button with suffix icons. Do design team have second thoughts on their decision?
