### ISSUE TITLE
What are these warnings all about?

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#3735]
I am trying to use Polaris 5 but am having all sorts of bad issues with it. Not necessarily Polaris, who really knows. I see these warnings and have no clue what they mean. 

remote         warning " > @shopify/app-bridge-react@1.28.0" has incorrect peer dependency "react@^16.0.0".
remote:        warning " > @shopify/polaris@5.12.0" has incorrect peer dependency "react@^16.9.0".
remote:        warning " > @shopify/polaris@5.12.0" has incorrect peer dependency "react-dom@^16.9.0".

Does not sound good to me. What is the reason for me seeing all these warnings anyway? Words like incorrect are scary.

**Comment by BPScott** [comment]
Those are coming from your package manager. It seems like you're using a version of React that isn't supported by those packages. [Here's some info on peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/).

Are you using React 17 by any chance? we've not yet gotten around to testing and supporting React 17 yet. You'll need to use React >=16.9.0 and < 17.

Why is returned when you run `yarn why react`

**Comment by resistorsoftware** [comment]
I did not ask for React 17... it was donated to me by something though... note that this project was spawned by Shopify App so I can only assume (perhaps incorrectly) it came from there. 

 yarn why react
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "react"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react@17.0.1"
info Has been hoisted to "react"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "364KB"
info Disk size with unique dependencies: "412KB"
info Disk size with transitive dependencies: "440KB"
info Number of shared dependencies: 3
✨  Done in 0.47s.

**Comment by BPScott** [comment]
Well no what generator you're using but in your package.json react and react-dom should both be `^16.9.0` if you want to get rid of those peer dependency warnings

**Comment by djnorrisdev** [comment]
Has this been tested with react 17 yet?
