### ISSUE TITLE
src/types Color export

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#3848]
As mentioned by @BPScott 

> For weird legacy never-got-around-to-fixing-it reasons everything in this file is exported publicly. So Color remains exported but now has a very different shape. Will that cause more problems than an error of "Color is no longer exported" from this file?
> 
> I'm thinking it might, and it'd be easier to keep this named as NewDesignLanguageColor.

My feeling is that with `v6.0.0` we should be removing `NewDesignLanguageColor` as it doesn't mean anything to our users. The question to answer is do we replace the `Color` values, rename the `Color` export or stop exporting the value.

**Comment by BPScott** [comment]
I'm all for stopping exporting it if possible.

Ideally we should stop blindly reexporting everything in [src/types.ts](https://github.com/Shopify/polaris-react/blob/b0fd0e3a6e389ca83fc02a59c4df5c08cde24d90/src/index.ts#L3), and instead have explicit exports for what we want to expose.
