### ISSUE TITLE
How am I supposed to show / hide mobile navigation via the TopBar component?

### ISSUE THREAD

**Issue by eugene-kim** [Shopify/polaris-react#3853]
## Issue summary

Given the documentation on the [TopBar component](https://polaris.shopify.com/components/structure/top-bar#navigation) it's unclear to me how I'm supposed to utilize the `onNavigationToggle` prop to show / hide mobile navigation.

Does the TopBar component somehow utilize the navigation component instance passed into the `Frame` component (Based on the [source](https://github.com/Shopify/polaris-react/blob/28e8653633331b5b3023a8fd1ce78853aeb2f08d/src/components/TopBar/TopBar.tsx) it doesn't look like it)? Or is this unrelated and am I supposed to create my own mobile navigation component that I show / hide via `onNavigationToggle`?

Thanks

**Comment by kyledurand** [comment]
Hey Eugene, checkout how the `DetailsPage.tsx` page works https://github.com/Shopify/polaris-react/blob/master/playground/DetailsPage.tsx#L207-L213

`Frame` handles the overall state and also needs some props https://github.com/Shopify/polaris-react/blob/master/playground/DetailsPage.tsx#L672-L673

You're right though we can probably improve the documentation around this

**Comment by eugene-kim** [comment]
Ah, I see. Thank you!
