### ISSUE TITLE
DataTable first column content is not vertically aligned

### ISSUE THREAD

**Issue by silvainSayduck** [Shopify/polaris-react#389]
# Issue summary

In the first column of `DataTable`s, cell content is not vertically aligned, which results in visually annoying results when there is a higher cell elsewhere in the row. 

## Expected behavior

Just like all other cells in the `DataTable`, the content of cells in the first column should be vertically aligned.

## Actual behavior

The content of cells in the first column of a `DataTable` is top aligned.

## Steps to reproduce the problem

See live example of the issue here: https://codesandbox.io/s/xj8pjr6nrq.
## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.5.0
- Browser: Chrome 67.0.3396.99
- Device: MacBook Pro (Retina, 15-inch, Mid 2015)
- Operating System: MacOS High Sierra v. 10.13.6 (17G65)

**Comment by chloerice** [comment]
Hi @silvainSayduck, thanks for raising this issue! I've added it to our internal project board. We'll keep this issue updated as we work on the fix.

**Comment by dfmcphee** [comment]
This should be fixed as of polaris-react 3.0.0
