### ISSUE TITLE
Inconsistent capitalization of "metadata"

### ISSUE THREAD

**Issue by ryanwilsonperkin** [Shopify/polaris-react#3893]
## Issue summary

The `Page` component's props capitalize the word "metadata" inconsistently. `titleMetadata` capitalizes only the "M"  but `additionalMetaData` capitalizes both the "M" and the "D"

## Expected behavior

I would expect the second prop to be named `additionalMetadata`

## Actual behavior

It is named `additionalMetaData`

## Steps to reproduce the problem

N/A

## Reduced test case

N/A

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 5.13.0
- Browser: All
- Device: All
- Operating System: All

**Comment by h7y** [comment]
I think this can be closed now. :)

**Comment by BPScott** [comment]
`additionalMetaData` has been renamed to `additionalMetadata` in v6
