### ISSUE TITLE
Enzyme issues after upgrading to Polaris V5.15.0

### ISSUE THREAD

**Issue by coler-j** [Shopify/polaris-react#3913]
## Issue summary

After upgrading from `4.13.1` to `5.15.0` when I run tests with `enzyme` I get the following error:

> Method “type” is meant to be run on 1 node. 2 found instead.

```
      11 | 
      12 | export function shallowWithAppProvider(node: React.ReactElement, context?: any) {
    > 13 |   return shallow(node, {
         |          ^
      14 |     wrappingComponent: PolarisTestProvider,
      15 |     wrappingComponentProps: context
      16 |   })

      at ShallowWrapper.single (node_modules/enzyme/src/ShallowWrapper.js:1652:13)
      at ShallowWrapper.type (node_modules/enzyme/src/ShallowWrapper.js:1388:17)
      at deepRender (node_modules/enzyme/src/ShallowWrapper.js:294:15)
      .......
      at deepRender (node_modules/enzyme/src/ShallowWrapper.js:302:19)
      at getContextFromWrappingComponent (node_modules/enzyme/src/ShallowWrapper.js:321:22)
      at makeShallowOptions (node_modules/enzyme/src/ShallowWrapper.js:359:7)
      at new ShallowWrapper (node_modules/enzyme/src/ShallowWrapper.js:393:21)
      at shallow (node_modules/enzyme/src/shallow.js:10:10)
      at shallowWithAppProvider (src/__tests__/utils/enzyme.util.ts:13:10)
      at Object.<anonymous> (src/components/my-component.spec.tsx:52:15)

```

## Expected behavior

My tests should run successfully as they did prior to upgrading polaris.

## Actual behavior

My `enzyme` wrapper is structured like this (as per the examples):

```
export function shallowWithAppProvider(node: React.ReactElement, context?: any) {
  return shallow(node, {
    wrappingComponent: PolarisTestProvider,
    wrappingComponentProps: context
  })
}
```

The issue triggers if I pass a simple component like:

```
function TestComponent() {
    return null
}
```

## Specifications

```bash
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 443.20 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.10 - ~/Documents/GitHub/MYPROJECT/node_modules/.bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 88.0.4324.96
    Safari: 14.0.1
  npmPackages:
    @shopify/polaris: ^5.15.0 => 5.15.0 
    react: ^16.12.0 => 16.14.0 
    react-dom: ^16.12.0 => 16.14.0 
    enzyme": ^3.11.0 => ^3.11.0
    enzyme-adapter-react-16 => 1.15.2
```

**Comment by coler-j** [comment]
Update:
At first I thought it was maybe related to also upgrading `@shopify/react-form` (to the release that uses `esm` modules) at the same time, however I have isolated this change to just `polaris`. Is `PolarisTestProvider` not a single node?

**Comment by BPScott** [comment]
[PolarisTestProvider is several context providers in a trenchcoat](https://github.com/Shopify/polaris-react/blob/main/src/components/PolarisTestProvider/PolarisTestProvider.tsx#L94).

It's top level item is also a Fragment if you're not electing to run in strict mode. Perhaps `shallow` doesn't like that.

Our examples show this working in mount](https://github.com/Shopify/polaris-react/blob/main/examples/create-react-app/src/tests/utils/enzyme.js), but there isn't a demo for shallow.

We stoped using Enzyme's shallow for testing ourselves years ago so I'm not to sure about how that should work.

**Comment by coler-j** [comment]
Thanks @BPScott i've moved the upgrade to my backlog for now so will swing back (hopefully) when I get back to it. It sounds like the strict mode will likely resolve it.
