### ISSUE TITLE
Horizontal shadow missing for scrollable component

### ISSUE THREAD

**Issue by swapkats** [Shopify/polaris-react#392]
# Issue summary

The Scrollable component doesn't add a shadow for horizontally scrolling components.

## Expected behaviour

There should be a shadow if provided as prop identical to the top and bottom shadows in case of vertical scrolling component.

## Actual behavior

There's no shadow for horizontal scrolling components

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.5.0
- Browser: Chrome
- Device: MacBook Air
- Operating System: MacOS Mojave

---

**Comment by tmlayton** [comment]
Hi @swapkats, thanks for the feature request!

We are not currently planing to add this so I’ll close this issue for now, but **we encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.

💜

**Comment by danrosenthal** [comment]
Closing this to reflect previous comments indicating it should be closed
