### ISSUE TITLE
EmptyState image doesn't look correct on Safari

### ISSUE THREAD

**Issue by janklimo** [Shopify/polaris-react#3954]
Using Polaris 6.0.1 the `EmptyState` component image expands outside of the parent container.

Example from the [docs](https://polaris.shopify.com/components/structure/empty-state):

**Chrome**

<img width="853" alt="Screen Shot 2021-02-02 at 19 17 12" src="https://user-images.githubusercontent.com/7811733/106599186-4b1d4100-658b-11eb-9f02-5ad9b0c04292.png">

**Safari**

<img width="788" alt="Screen Shot 2021-02-02 at 19 18 40" src="https://user-images.githubusercontent.com/7811733/106599322-7b64df80-658b-11eb-8b90-963184556ef8.png">

**Comment by kyledurand** [comment]
Thanks @janklimo these were definitely overlooked. Empty state should be rendered within a card now which fixes the safari issue. I liked to a PR that fixes this

**Comment by kyledurand** [comment]
This closed automatically when I merged that PR it should be fixed in the styleguide when the next version of polaris is released

**Comment by aaronadamsCA** [comment]
This PR increases the need to resolve #2611. Wrapping my `EmptyState` with `Card` "fixes" the image positioning issue, but it also makes my SVG images disappear completely 🙂
