### ISSUE TITLE
[IndexTable] Sticky column headers are misaligned

### ISSUE THREAD

**Issue by lhoffbeck** [Shopify/polaris-react#3991]
## Issue summary
On the IndexTable component, the sticky column headers are misaligned with the column content after resizing the browser window. It looks like the problem is that the sticky column header widths are calculated on pageload and aren't updated on resize.

Related web issue [#37885](https://github.com/Shopify/web/issues/37885)

https://user-images.githubusercontent.com/3619012/107650520-918a3400-6c4c-11eb-9ab6-ebd36f777e16.mp4

## Expected behavior
Sticky column headers should align with columns after window resize

## Actual behavior
Column headers are misaligned with columns after resize

## Steps to reproduce the problem

1. Open up an indextable instance (e.g. /admin/collections on shopify admin)
2. Resize your browser window
3. Scroll the indextable until the sticky headers appear

## Specifications
```bash
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 223.27 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.13.0 - ~/.dev/yarn/v1.13.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 88.0.4324.150
    Chrome Canary: 90.0.4414.0
    Firefox: 85.0.1
    Firefox Developer Edition: 85.0
    Safari: 13.1.3
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-dom: ^16.9.0 => 16.9.0 
```

**Comment by AndrewMusgrave** [comment]
Interesting, I don't see/can't reproduce it on the orders page. @lsit Can you repro this on your index table implementation?

**Comment by lsit** [comment]
Ya I can reproduce on the Products list https://screenshot.click/21-02-4rnu7-waeed.mp4
