### ISSUE TITLE
DatePicker component no month label

### ISSUE THREAD

**Issue by mEnriquez2020** [Shopify/polaris-react#4001]
## Issue summary
I'm using the DatePicker component on new version 6.0.1 and the month label is not showing. https://prnt.sc/zbtct7

**Comment by skrabakl-shopify** [comment]
Hi, @mEnriquez2020 on the screenshot it looks like you have some custom styles applied to the component - the left-hand side of the calendar is bold. Could you share a codesanbox where you can reproduce this thing?

**Comment by mEnriquez2020** [comment]
Hi @happykoder, thank you for your feedback. Please see the issue here. https://codesandbox.io/s/date-picker-hjidb?file=/App.js

The issue occurs when the DatePicker is wrapped within the AppProvider

**Comment by mEnriquez2020** [comment]
I found an answer here. https://github.com/Shopify/polaris-react/issues/2708#issuecomment-582070149
