### ISSUE TITLE
Using Tailwind with Polaris

### ISSUE THREAD

**Issue by konrain** [Shopify/polaris-react#4017]
## Overview
I'm looking to add tailwind on top of polaris, keep getting issues with PostCSS. 

postcss.config.js:
```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```
┃ error - ./node_modules/@shopify/polaris/dist/styles.css
┃ TypeError: Invalid PostCSS Plugin found at: plugins[0]

┃ (.../postcss.config.js)
┃     at Array.forEach (<anonymous>)

## Labels
- [`Type: Bug` ] 

### Scope

- Is this issue related to a specific package?

  - [Package: Shopify Polaris & PostCSS]

**Comment by dustineichler** [comment]
Delete your `postcss` config and import your tailwind.css file directly. Restart your server.
