### ISSUE TITLE
Correct typo in content guide

### ISSUE THREAD

**Issue by Jen-Bader** [Shopify/polaris-react#4026]
## Issue summary
Correct visual example typo in the content/Actionable language/OK vs. accept section. 

**Change CTA copy**
**from:** "Ok"
**to**: "OK"

![image](https://user-images.githubusercontent.com/55419135/109581591-6bb8b800-7ab1-11eb-824f-8caff312990b.png)

**Comment by galanggg** [comment]
Hi @Jen-Bader, how I can help with this issue?

**Comment by Jen-Bader** [comment]
Hi @galanggg, thanks for reaching out. 
Update that needs to be made is to change CTA copy
from: "Ok"
to: "OK"

So changing the lower case "k" to upper case "K".

**Comment by galanggg** [comment]
Hi @Jen-Bader For the visual example, do I change it in the storybook?

**Comment by jjgali** [comment]
@Jen-Bader I was able to successfully update the image. Thanks so much for flagging this!
