### ISSUE TITLE
IndexProvider Component leaves whitespace during selection

### ISSUE THREAD

**Issue by tylerrowsell** [Shopify/polaris-react#4029]
## Issue summary

The index provider leaves white space at the bottom of the container when things are selected. 
https://github.com/Shopify/web/issues/37552

It seems to be caused when the sticky header appears there is a `transformY` applied to the table that moves it up but the parent height doesn't adjust.

https://user-images.githubusercontent.com/17143722/109712883-8ef56d00-7b6e-11eb-883b-5e73e51f5d5f.mov

## Expected behavior

No whitespace should appear.
## Actual behavior

Whitespace appears

## Steps to reproduce the problem

1) Go to files/products index page and select an item. 
2) Whitespace appears on the bottom of the page. 

## Specifications

npx: installed 1 in 1.151s

  System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 248.93 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    Yarn: 1.22.5 - ~/.dev/yarn/1.22.5/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 88.0.4324.192
    Safari: 14.0.3
  npmPackages:
    @shopify/polaris: 6.0.1 => 6.0.1
    react: ~16.14.0 => 16.14.0
    react-dom: ~16.14.0 => 16.14.0

**Comment by pamelahicks** [comment]
The IndexTable shown in the screenshot is not referencing the IndexTable from this package (I checked the source). This IndexTable doesn't have that whitespace.
