### ISSUE TITLE
DataTable show error Cannot read property 'scrollWidth' of null in console log

### ISSUE THREAD

**Issue by duythien0912** [Shopify/polaris-react#403]
# Issue summary

![scrollWidth](https://user-images.githubusercontent.com/20185622/44256203-aed41800-a232-11e8-937e-d3460f096e5a.png)

![error](https://user-images.githubusercontent.com/20185622/44256924-c0b6ba80-a234-11e8-9ada-babc18092bce.png)

When use DataTable

## Actual behavior
DataTable show error Cannot read property 'scrollWidth' of null in console log 

## Steps to reproduce the problem
Copy Examples in https://polaris.shopify.com/components/lists-and-tables/data-table

## Specifications

- Are you using the React components? (Y/N):y
- Polaris version number:2.5.0
- Browser: Chrome
- Device: Laptop
- Operating System: Linux

**Comment by tmlayton** [comment]
Thanks for reporting the issue @duythien0912. I opened an issue to track internally and we will post back here when it is resolved.
