### ISSUE TITLE
DropZone - the option `allowMultiple` ignored on drag and drop multiple files

### ISSUE THREAD

**Issue by abalmus** [Shopify/polaris-react#404]
# Issue summary
The option (allowMultiple) for DropZone component ignored on drag and drop files. If you try setting this option to false it still allows you to drop multiple files. 

## Expected behavior
If `allowMultiple` option is set to false DropZone component should restrict adding more then one file.

## Actual behavior
It is possible to drop multiple files even if `allowMultiple` is set to false.

## Steps to reproduce the problem

1. Insert DropZone component to your app.
2. Set allowMultiple option to false
3. Drag and Drop multiple files to DropZone

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.5.0
- Browser: Chrome 68.0.3440.106
- Device: Mac Pro
- Operating System: macOs High Sierra 10.13.5

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by tmlayton** [comment]
Thanks for the issue @abalmus, I’ve opened an internal issue and we will post back here when it is addressed.
