### ISSUE TITLE
`Portal` does unnecessary work to trigger `onPortalMounted()`

### ISSUE THREAD

**Issue by lemonmade** [Shopify/polaris-react#4064]
Right now, `Portal` triggers `onPortalMount` in an effect, conditional on the result of calling `useIsMountedRef()`: https://github.com/Shopify/polaris-react/blob/main/src/components/Portal/Portal.tsx#L25-L29. I assume this check is supposed to be gated on `isMounted.current`, since `isMounted` is always truthy. However, I don't think that check is needed at all, because an effect is never run unless the component is mounted.

cc/ @dfmcphee

**Comment by dfmcphee** [comment]
Good catch. That should only need the `useEffect` itself and not use `useIsMountedRef` at all.
