### ISSUE TITLE
ButtonGroup with Icon and Text children are missaligned

### ISSUE THREAD

**Issue by indiragp** [Shopify/polaris-react#4079]
## Issue summary

When you create a ButtonGroup with size="slim" where one Button is text and the other button is an Icon, in a full-screen view the buttons are not-aligned. This works well for any bigger button sizes and when the screen is small (inspecting on chrome on a phone view).

## Expected behavior

When creating a ButtonGroup if one Button is text and another button is an Icon, they should be aligned
<img width="738" alt="Screen Shot 2021-03-23 at 11 45 15 AM" src="https://user-images.githubusercontent.com/7685495/112184531-4a894a00-8bcd-11eb-9668-3fe611210453.png">

## Actual behavior

There is a 1px missalignment between the button with text and the button with an Icon
<img width="734" alt="Screen Shot 2021-03-23 at 11 44 41 AM" src="https://user-images.githubusercontent.com/7685495/112184547-4fe69480-8bcd-11eb-875a-cd0ef9ab69ac.png">

## Reduced test case

[CodeSandbox](https://codesandbox.io/s/boring-chaplygin-uvlb0?file=/App.js) to reproduce the issue.

## Specifications

- Are you using the React components? (Y/N):Y 
- Polaris version number: 6.1.0
- Browser: Chrome:89.0.4389.90
- Device: MacBook Pro
- Operating System: macOS 10.15.7

**Comment by indiragp** [comment]
Some notes about the issue: 
The height for the text button is 28px, where as the height for the button with the icon is 29px.
Another differences are that the Polaris_Button_Content for the text one is 16px and. the Polaris_Button_Content for the icon is 20px.
Some of the things that fix this alignment are:
1. Updating the size of the `Polaris-Icon` to 19px
2. Setting the Polaris-ButtonGroup__Item height to 28px
3. From the Polaris-ButtonGroup__Item removing the html, body line-height: 2rem;
4. Adding a margin top of 1px to the last button.
5. In Polaris-ButtonGroup__Item there is an applied css: 
```
@media (min-width: 40em)
html, body {
     font-size: 1.4rem;
}
```
Removing this applied style the rest of the applied font-size applied is 1.5 rem and the buttons get aligned again.

This bug was originally reported as: [#2194](https://github.com/Shopify/intl-cross-border/issues/2194)
I've reported this on [Slack](https://shopify.slack.com/archives/C4Y8N30KD/p1616096977076500) but didn't get a response.

**Comment by tylernoseworthy** [comment]
Hey I am just revisiting this bug that is also outlined in this issue https://github.com/Shopify/core-issues/issues/28798. Is anyone on the team able to take a look at it? or should I just put up a PR? cc @nickpresta

**Comment by tylernoseworthy** [comment]
Going to pick up this issue.

**Comment by tylernoseworthy** [comment]
> Some notes about the issue: The height for the text button is 28px, where as the height for the button with the icon is 29px. Another differences are that the Polaris_Button_Content for the text one is 16px and. the Polaris_Button_Content for the icon is 20px. Some of the things that fix this alignment are:
> 
> 1. Updating the size of the `Polaris-Icon` to 19px
> 2. Setting the Polaris-ButtonGroup__Item height to 28px
> 3. From the Polaris-ButtonGroup__Item removing the html, body line-height: 2rem;
> 4. Adding a margin top of 1px to the last button.
> 5. In Polaris-ButtonGroup__Item there is an applied css:
> 
> ```
> @media (min-width: 40em)
> html, body {
>      font-size: 1.4rem;
> }
> ```
> 
> Removing this applied style the rest of the applied font-size applied is 1.5 rem and the buttons get aligned again.
> 
> This bug was originally reported as: [#2194](https://github.com/Shopify/intl-cross-border/issues/2194) I've reported this on [Slack](https://shopify.slack.com/archives/C4Y8N30KD/p1616096977076500) but didn't get a response.

@chloerice out of these above potential fixes, what do you think would be the best solution?

**Comment by tylernoseworthy** [comment]
This only really seems to be an issue with Buttons that have the slim variant.

**Comment by chloerice** [comment]
> @chloerice out of these above potential fixes, what do you think would be the best solution?

Hey @tylernoseworthy!! 👋🏽 I checked out the updates you pushed to the PR and the negative margin does work, but feels like a deep reach (but then again, so does all of the Sass in that Button stylesheet 😬) that may not be effective for custom icons that might not adhere to the sizing we use internally. I tested adding `line-height: normal;` to `.Item` in the `ButtonGroup` stylesheet and it fixes the issue as well so I would vote for that route.

<details>
<summary>(Click to view playground code for the screenshot below 👀)</summary>

```jsx
import React from 'react';
import {DeleteMinor} from '@shopify/polaris-icons';

import {Page, Layout, Card, Icon, Button, ButtonGroup} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      <Layout>
        <Layout.Section>
          <Card>
            <Card.Section title="Slim buttons">
              <ButtonGroup segmented>
                <Button size="slim">Remove</Button>
                <Button icon={<Icon source={DeleteMinor} />} size="slim" />
                <Button icon={<Icon source={DeleteMinor} />} size="slim">
                  Remove
                </Button>
                <Button disclosure size="slim">
                  More actions
                </Button>
              </ButtonGroup>
            </Card.Section>

            <Card.Section title="Default buttons">
              <ButtonGroup segmented>
                <Button>Remove</Button>
                <Button icon={<Icon source={DeleteMinor} />} />
                <Button icon={<Icon source={DeleteMinor} />}>Remove</Button>
                <Button disclosure>More actions</Button>
              </ButtonGroup>
            </Card.Section>

            <Card.Section title="Large buttons">
              <ButtonGroup segmented>
                <Button size="large">Remove</Button>
                <Button icon={<Icon source={DeleteMinor} />} size="large" />
                <Button icon={<Icon source={DeleteMinor} />} size="large">
                  Remove
                </Button>
                <Button disclosure size="large">
                  More actions
                </Button>
              </ButtonGroup>
            </Card.Section>

            <Card.Section title="Full width buttons">
              <ButtonGroup fullWidth segmented>
                <Button>Remove</Button>
                <Button icon={<Icon source={DeleteMinor} />} />
                <Button icon={<Icon source={DeleteMinor} />}>Remove</Button>
                <Button disclosure>More actions</Button>
              </ButtonGroup>
            </Card.Section>

            <Card.Section title="Outline buttons">
              <ButtonGroup segmented>
                <Button outline>Remove</Button>
                <Button outline icon={<Icon source={DeleteMinor} />} />
                <Button outline icon={<Icon source={DeleteMinor} />}>
                  Remove
                </Button>
                <Button outline disclosure>
                  More actions
                </Button>
              </ButtonGroup>
            </Card.Section>

            <Card.Section title="Plain buttons">
              <ButtonGroup segmented>
                <Button plain>Remove</Button>
                <Button plain icon={<Icon source={DeleteMinor} />} />
                <Button plain icon={<Icon source={DeleteMinor} />}>
                  Remove
                </Button>
                <Button plain disclosure>
                  More actions
                </Button>
              </ButtonGroup>
            </Card.Section>
          </Card>
        </Layout.Section>
      </Layout>
    </Page>
  );
}
```

</details>

<img width="1352" alt="Screen Shot 2022-01-21 at 4 41 26 PM" src="https://user-images.githubusercontent.com/18447883/150603887-a4e545df-ad23-4748-9d20-b89900596217.png">

**Comment by tylernoseworthy** [comment]
@chloerice thanks for looking into those solutions!! I agree, wasn't overly happy on doing any styles within `Button`. It seemed like all the fixes were simple enough, but may have had impacted other components negatively. Going to update the PR with the `line-height: normal` fix
