### ISSUE TITLE
CircleMinus icon is missing

### ISSUE THREAD

**Issue by johnnunns** [Shopify/polaris-react#410]
Not sure if it just hasn't been added yet, but it seems the icon "circleMinus" is missing as an option for your component. Our designer created a mock page for us to build that uses your styling kit which includes that icon variation. Let me know where I should go from here. Thanks!

<img width="346" alt="screen shot 2018-08-27 at 2 56 23 pm" src="https://user-images.githubusercontent.com/24666478/44688752-09772c00-aa0a-11e8-970a-256c52793fa0.png">

**Comment by ry5n** [comment]
Thanks for flagging this. I’ve opened an issue internally to sync up the Sketch file and the released code. In the meantime, I’ve attached the icon SVG and some notes on how to use it.

### Icon file

[Polaris-icons-circle-minus.zip](https://github.com/Shopify/polaris/files/2329995/Polaris-icons-circle-minus.zip)

### Notes

The [icon component](https://polaris.shopify.com/components/images-and-icons/icon#navigation) expects a pretty specific structure: an object, that has a `viewBox` and a `body` property. How you supply that depends on if you’re using a bundler like [Webpack](https://webpack.js.org) or not. 

If you’re using Webpack, you can add the [`@shopify/images` package](https://www.npmjs.com/package/@shopify/images) and use `@shopify/images/icon-loader` to load the icons from an `import` statement.

If you’re not using Webpack, the simplest way is to manually write out the icon in the expected shape:

```js
const icon = {
  viewBox: '0 0 20 20',
  body: '<path />', // everything in the SVG other than the `<svg>` tag itself
};

<Icon source={icon} />
```

**Comment by ry5n** [comment]
I can confirm we’re actively working on improvements to how we distribute icons, and we’ll have more on that in the future. For now, I’ll close this as resolved for the immediate question. Please re-open if you have more questions.
