### ISSUE TITLE
Autocomplete `off` has inconsistent application in chrome

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#4107]
## Issue summary

As brought up by @utkarshsaxena93 and @whizkydee when using `autocomplete="nope"` they do not get the expected experience in google chrome. When using the correct value `autocomplete="off"` they get the correct experience but that causes regressions in other applications.

We need to find the root cause of what is changing the autocomplete behavior so we can consistently hide the autocomplete functionality correctly.

## Expected behavior

One solution for `autocomplete="off"`

## Actual behavior

Sometimes `autocomplete="nope"` works, other times `autocomplete="off"` works and in other situations people use `autocomplete="OFF"` to work around the `nope` return.

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by utkarshsaxena93** [comment]
@dfmcphee is planning to revert the PR for now
