### ISSUE TITLE
 Long words go outside of <TextContainer> on mobile or small widths

### ISSUE THREAD

**Issue by imgntn** [Shopify/polaris-react#413]
# Issue summary

If you put in a long word inside of a ```<TextContainer>```, it doesn't break and the text goes outside of the bounds of the text container.  This could be an issue if you've got a long string you need to show, for example a full url you want to display that doesn't contain any dashes. It feels a bit broken with even a moderate length URL in there.

This can be fixed with some additional CSS on the specific element --```word-break:break-all```, or any kind of ```break-all```.

Not sure where this falls on your spectrum of handle ourselves vs. handle in Polaris?    Thanks!

## Expected behavior
All text should be inside of ```<TextContainer>``` elements.

## Actual behavior

A long string goes outside of the container

![capture](https://user-images.githubusercontent.com/843228/44939513-b15a6580-ad3a-11e8-8eb9-67accba88669.PNG)

## Steps to reproduce the problem 

1. Go to the TextContainer documentation [https://polaris.shopify.com/components/titles-and-text/text-container#navigation](url)
2. Inspect the example text and replace with a long string w/o dashes such as ```https://github.com/Shopify/polaris/tree/master/src/components```
3. Decrease the width of the test element to its minimum on desktop, or look at it in a mobile emulator or on a phone
4. Observe that the text goes off screen
5. Try replacing the ```<p>``` with a ```<Link>``` as well - the element used seems not to matter

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.6.1
- Browser: Chrome, Shopify Android App
- Device: Desktop + Mobile 
- Operating System: Win10 + Android

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dpersing** [comment]
Hi @imgntn! Thanks so much for logging this. We'll take a look!

**Comment by dfmcphee** [comment]
This should be fixed as of polaris-react 2.6.0
