### ISSUE TITLE
Allow onAction to be specified for clicks on app title within the Shopify.Bar area

### ISSUE THREAD

**Issue by jjt** [Shopify/polaris-react#416]
# Feature request summary

Allow a callback or `onAction` function that is called when a user clicks on the app title that can prevent navigation so that SPAs can handle routing without a full request cycle.

## Rationale

In this example application, the user is in a route with a `<Page title="Settings">` component. This results in the Shopify Bar area displaying `USOhHeckYesAPP / Settings`, with `USOhHeckYesAPP` being a link to the root of the embedded app:

![image](https://user-images.githubusercontent.com/399469/45057108-9f820680-b049-11e8-8be6-6d4b4dc21266.png)

When a user clicks on `USOhHeckYesAPP`, it navigates the iframe away from the current page and reloads the page. This is okay for apps with a traditional request cycle, but for single page applications that route through `pushState` and `replaceState`, it's jarring to have a full refresh.

This feature would allow embedded apps to specify an `onAction` callback to be executed when a user clicks on the application title, and allow the embedded application to route via `pushState`/`replaceState` like a modern SPA.

Thank you for coming to my TED talk.

**Comment by jjt** [comment]
Note: this is assuming there is no current way to do this as per #415

**Comment by rnovacek** [comment]
Any progress on this? It really breaks the flow of our app - it's a Single Page Application so there are no page loads, but when user clicks a page title, then there's a bit of jumpy behavior (the second row of header disappears for a second) before the page reloads.

It would be great if we could add a custom behavior to title click (as we can for the breadcrumbs).

**Comment by tim-phillips** [comment]
Apparently #1349 fixes this. I haven't tried it yet myself though.

**Comment by tmlayton** [comment]
Hey all, thanks for this issue and makes sense. This would be a feature request for the App Bridge team. We simply use the `TitleBar` action under the hood and are limited by their API. https://help.shopify.com/en/api/embedded-apps/app-bridge/actions/titlebar

They accept feature requests through the Shopify forums: https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology

> Apparently #1349 fixes this. I haven't tried it yet myself though.

As far as I know, this is still not possible, at least according to the docs.

---

For more context, we will be removing app bridge delegation entirely from Polaris as of v5 and offer React wrappers around the App Bridge actions from a different package: `@shopify/app-bridge-react`. See this comment for more details https://github.com/Shopify/polaris-react/issues/814#issuecomment-493249756
