### ISSUE TITLE
Spinner on numeric TextField doesn't support press-and-hold

### ISSUE THREAD

**Issue by andrewpye** [Shopify/polaris-react#420]
# Feature request summary
Make spinner buttons on numeric text fields respond to being pressed and held down, instead of only firing a single click event when the button is released.

## Rationale
Currently pressing and holding the spinner on a `TextField` with `type="number"` doesn't continually increment/decrement the value displayed:

![numeric-text-field-spinner](https://user-images.githubusercontent.com/5737342/45231913-9ac98680-b2c5-11e8-8b59-92939e4b2f5a.gif)

However, we feel that most users would expect to be able to press and hold the spinner buttons to change the value more quickly than having to click multiple times. For example, in one of our apps, we have numeric text fields which control the positioning of a component on screen, and in that case, being able to hold the spinner down to "slide" the component around the screen is a useful ability to have.

**Comment by solonaarmstrong** [comment]
Thank you for your suggestion. I have created a feature request.

**Comment by ry5n** [comment]
This is a great idea. We’ve just made the switch to start accepting pull requests :tada:  This is one I’d definitely like to see.
