### ISSUE TITLE
Focus box is mis-sized when using unminified Polaris CSS

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/polaris-react#4232]
## Issue summary
When I build Polaris using minimal CSS tooling, focus boxes aren't wrapping text:

<img width="482" alt="Shop 1 ~ Products ~ Shopify 2021-05-27 16-23-33" src="https://user-images.githubusercontent.com/673655/119892222-eace5880-bf07-11eb-90e3-28c5fd65bd2e.png">

Looking at the generated CSS, it's generating property values that are flagged a `invalid` by Chrome:

```
  top: calc(-1 * calc(0 + 0.1rem));
```

<img width="281" alt="Shop 1 ~ Products ~ Shopify 2021-05-27 16-25-08" src="https://user-images.githubusercontent.com/673655/119892422-1d785100-bf08-11eb-9276-185938c3506c.png">

## Expected behavior
Focus boxes should wrap text.

## Actual behavior
Focus boxes do not wrap text. I can work around this by adding [`postcss-calc`](https://github.com/postcss/postcss-calc) to my stack, but I'd rather not 😸 

## Specifications

- Are you using the React components? Y
- Polaris version number: 6.4.0
- Browser: Chrome
- Device: Macbook Pro / ☁️ 
- Operating System: MacOS (Big Sur) / Ubuntu

```bash
npx: installed 1 in 0.854s

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (32) x64 Intel(R) Xeon(R) CPU
    Memory: 29.25 GB / 125.91 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  npmPackages:
    @shopify/polaris: 6.4.0 => 6.4.0
    react: ~16.14.0 => 16.14.0
    react-dom: ~16.14.0 => 16.14.0
```

**Comment by BPScott** [comment]
We already compile with postcss-calc so this sounds like a bug in postcss-calc and polaris needs to update to a newer versiion. That's probably also going to beget updating to postcss@8 and @shopify/postcss-plugin@4.1.0

**Comment by GoodForOneFare** [comment]
Stuff like autoprefix, flexbugs, and comment removal aren't useful to spinx (or Storybook) 🤷  If tooling _must_ use our configs, the defaults should be revised and/or more configurable.

**Comment by alex-page** [comment]
We got you.

**Comment by BPScott** [comment]
> If tooling *must* use our configs

I agree that stuff shipped by libraries shouldn't depend on this stuff. we've adjusted the offending mixin to work without needing to be processed by postcss
