### ISSUE TITLE
[Page] Introduce `bottomBorder` prop

### ISSUE THREAD

**Issue by winterlamon** [Shopify/polaris-react#4238]
## Feature request summary

Introduce a prop to the `Page` component that adds a border between the page header and the content children.

```jsx
<Page {...PageProps} bottomBorder />
```

![Screen Shot 2021-06-01 at 4 18 48 PM](https://user-images.githubusercontent.com/16295605/120385191-18931300-c2f5-11eb-95a9-ed631aa92cc9.png)

## Rationale

Recent design mocks for sell pages within admin have included a border between the page title and the content. I have been able to apply the styles to specific instances using some hacky CSS by wrapping the `Page` component and adding a class that targets the content-wrapping node. However, this approach to apply the styling is very brittle since it can be affected by changes to `Page` styles or class names, how Polaris classes are composed, etc. 

```scss
.PageWrapper {
  [class^='Polaris-Page__Content'] {
    border-top: border();
  }
}
```

I'd like to request a `bottomBorder` prop (default: `false`) added to the `Page` component, so there's no need for unstable style hacks. I'm happy to contribute.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by EdwardGoomba** [comment]
This would be great - we have similar designs with a border between page titles and cards for example. Currently I am adding an hr or styling an empty div to make this work.
