### ISSUE TITLE
Recently, I found that the indextable component of Polaris has problems when displaying, how can I solve it?

### ISSUE THREAD

**Issue by LXJ-heartbeats** [Shopify/polaris-react#4247]
## Issue summary

<img width="623" alt="b2705b5bbba5d2a75016c594c4a2980" src="https://user-images.githubusercontent.com/68101582/120775795-21ceea80-c556-11eb-9b31-2b8e366c4e20.png">

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by pamelahicks** [comment]
It seems that `position: sticky` is suddenly not playing nice with `box-shadow` 🤔

**Comment by EdwardGoomba** [comment]
## Specifications

System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 9.74 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.2 - ~/.nodenv/versions/12.18.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nodenv/versions/12.18.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 85.0
    Firefox Developer Edition: 90.0
    Safari: 14.0.3

As mentioned by @pamelahicks - issue is only currently present in current version of Chrome.
