### ISSUE TITLE
DropZone can't add same file again when remove file from state

### ISSUE THREAD

**Issue by jzsplk** [Shopify/polaris-react#425]
# Issue summary
Try to add a remove button to clear the files uploaded. Can not add the same file again with click Popover after I have removed it. The onDrop props is ignored.

## Expected behavior
Expected I can remove a file from DropZone and I can upload it again.

When I remove the file from state outside the DropZone, the state inside the DropZone ignore the onDrop function for the same file id.

## Steps to reproduce the problem

1. make a fileDropZone with DropZone component
2. add a remove function, to clear the files in state in Example component.
3. use the remove function, and try to add file again with click Popover of DropZone
it's a sample for this bug:
https://codesandbox.io/s/01nmwypl8l
## Specifications

- Are you using the React components? (Y/N):Y
- Polaris version number:2.8.0
- Browser: Chrome
- Device: MacBook Pro
- Operating System: macOs HIGH SIERRA 10.13.6

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dpersing** [comment]
Thanks for the request, @jzsplk. We’re not actively working on this right now, but we treat all feature requests as part of our backlog.

I’ll close this issue for now, but **we encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.

💜

**Comment by dpersing** [comment]
Hi @jzsplk! Using your example, I'm able to re-upload a file using the native dialog that appears when the "Add image" text is clicked, as well as by dragging and dropping. Are you still experiencing this issue?

**Comment by jzsplk** [comment]
@dpersing Hi, still experiencing this issue. You are able to re-upload cause my example has been modify by somebody. In the modified example , DropZone is closed when file uploaded. But I need to keep the DropZone so user can continue to upload with it. I have modified the example back.

**Comment by dpersing** [comment]
Hi @jzsplk, It looks like I'm still able to upload the same image multiple times. Do you perhaps have a different sandbox that hasn't been altered?

Also, are you using the small-format Drop zone for allowing users to add multiple images? I'd recommend using one of the larger versions if users are meant to upload multiple files.

**Comment by dpersing** [comment]
Hi @vladucu! I'm able to repro with your example. Thanks! I'll share with the team.

**Comment by manishsundriyal** [comment]
Yes, I am also facing the same issue. In my case when a file is rejected by the customValidator is uploaded again then, it's not working.
