### ISSUE TITLE
Issue with CRA, cause `polaris-icons` updated to 4.6.0

### ISSUE THREAD

**Issue by pierreneter** [Shopify/polaris-react#4276]
## Issue summary

The `polaris-icons` dependency of `polaris-react` (https://www.npmjs.com/package/@shopify/polaris-icons) just updated to 4.6.0.

```jsonc
// ...
"dependencies": {
    "@shopify/polaris-icons": "^4.1.0",
// ...
```

has changed on icons built files:

4.5.0 `@shopify/polaris/node_modules/@shopify/polaris-icons/dist/icons/AbandonedCartMajor.svg.mjs` 

```js
import React from 'react';
```

4.6.0 `@shopify/polaris/node_modules/@shopify/polaris-icons/dist/icons/AbandonedCartMajor.svg.mjs`

```js
import * as React from 'react';
```

It makes CRA compile error:

```bash
Can't import the named export 'createElement' from non EcmaScript module (only default export is available)
```

<img width="1041" alt="Screen Shot 2021-06-24 at 2 45 09 PM" src="https://user-images.githubusercontent.com/12815768/123223106-cf507080-d4fa-11eb-8dcf-ca80a5ab1c2e.png">

## Expected behavior

CRA compiles successfully

## Actual behavior

CRA cannot compile

## Steps to reproduce the problem

1. Install `@shopify/polaris` to a CRA project.
2. Use `import { FormLayout } from "@shopify/polaris";`
3. Error show on the terminal: 

```bash
Failed to compile.

../node_modules/@shopify/polaris/node_modules/@shopify/polaris-icons/dist/icons/AbandonedCartMajor.svg.mjs
Can't import the named export 'createElement' from non EcmaScript module (only default export is available)
```

## Reduced test case

https://github.com/pn-space/shopify-polaris at https://github.com/pn-space/shopify-polaris/blob/main/src/App.tsx

## Specifications

- Are you using the React components? (Y/N): yes
- Polaris version number:`6.5.0`
- Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)
- Device: MacBook Pro (15-inch, 2018)
- Operating System: macOS Big Sur version 11.4 (20F71)

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0
    Yarn: 1.22.10
    npm: 7.14.0
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.1
    Safari: 14.1.1
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-dom: ^16.9.0 => 16.9.0
    @shopify/polaris: ^6.5.0 => 6.5.0
```

## Related to

https://github.com/facebook/create-react-app/issues/10356

**Comment by trungdunghbvn** [comment]
Me too
![image](https://user-images.githubusercontent.com/30406686/123237778-290b6780-d508-11eb-99d6-d8fb7371ed57.png)

**Comment by alex-page** [comment]
Hey v4.6.1 of `polaris-icons` has shipped now. This should be resolved.
