### ISSUE TITLE
Embedded app modal components do not display.

### ISSUE THREAD

**Issue by shawnhind** [Shopify/polaris-react#430]
# Issue summary

When creating a modal in an embedded shopify app the components nested within the modal do not display and instead only a blank modal appears.  I have tried ChoiceLists and TextFields in the modal.

## Expected behavior

I expect the nested components to be displayed in the modal like the examples show.

## Actual behavior

The modal is blank.

There is a warning appearing in the javascript console saying that the src for the modal is blank but I'm not sure why this is needed if I'm only nesting components inside of it and not a web page.

## Steps to reproduce the problem

1.  Create an embedded application with a page.
1.  Follow the example instructions to create a modal and have it display on a button click.
1.  The modal will be empty.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: Newest
- Browser: Chrome
- Device: Laptop
- Operating System: OpenSUSE Tumbleweed

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by mbaumbach** [comment]
@shawnhind The modals don't currently support nested React components in embedded apps. It's discussed a bit in #383 and includes a workaround too.

**Comment by shawnhind** [comment]
@mbaumbach The polaris component documentation examples show nested components.  Is that a mistake?

**Comment by ry5n** [comment]
@mbaumbach that’s a good summary of the situation, thanks. @shawnhind if you haven’t already, please take a look at the discussion in #383. It may help you work around this limitation. Like I expressed in that issue, we’re not jazzed about how this currently works, and we are working on improvements. But iframes are tricky—and are unfortunately a necessity here. When we’re able to ship something better, we absolutely will. Thank you! 🙏

**Comment by avibz1987** [comment]
Is this still the official solution? 3 years later?
