### ISSUE TITLE
[Bug] ResourceList and IndexTable hover states should be the same

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react#4319]
## Issue summary

The `ResourceList` and `IndexTable` components have two different hover states.

## Expected behavior

The interaction states should be the same.

## Actual behavior

`ResourceList` items are gray when hovered, while `IndexTable` items are blue when hovered.

| ResourceList | IndexTable |
|---|---|
|<img width="740" alt="Screen Shot 2021-07-15 at 6 18 12 PM" src="https://user-images.githubusercontent.com/18447883/125865060-95ec4491-8624-4001-82fa-7d17edca9b0b.png">|<img width="741" alt="Screen Shot 2021-07-15 at 6 17 57 PM" src="https://user-images.githubusercontent.com/18447883/125865085-2f7e36a9-7063-4019-b872-d13bd25f0fdc.png">|

## Steps to reproduce the problem

1. View the `ResourceList` docs and hover over items in the examples
2. View the `IndexTable` docs and hover over items in the examples

**Comment by juwanpetty** [comment]
Hey @chloerice to make these components consistent with each other are we favoring the `ResourceList` behavior over the `IndexTable`

**Comment by chloerice** [comment]
Hey @juwanpetty! 👋🏽 That's a great question, asking the team 👀

**Comment by kyledurand** [comment]
@AdamWhitcroft or @jessebc might be able to share some opinions around this.

**Comment by juwanpetty** [comment]
Closing, this issue has been tackled

**Comment by alex-page** [comment]
@juwanpetty are you actively pushing forwards this work?

**Comment by juwanpetty** [comment]
Hey @alex-page, I currently have a draft PR that needs to be updated

**Comment by alex-page** [comment]
@juwanpetty is there any chance you could get this shipped this week?

**Comment by juwanpetty** [comment]
Hey, just now seeing this, I can get it shipped out this week!

**Comment by juwanpetty** [comment]
@alex-page ready for review here: https://github.com/Shopify/polaris-react/pull/4452

**Comment by alex-page** [comment]
Closing this issue!
