### ISSUE TITLE
Filter popover not calculating position correctly

### ISSUE THREAD

**Issue by danny-williams** [Shopify/polaris-react#4340]
## Issue summary

As I apply filters, the popover pane moves, but the dropdown selection does not. It sort of floats in space, detached from its parent. This seems broken. Screenshot below to illustrate.
![Screen Shot 2021-07-27 at 9 52 39 AM](https://user-images.githubusercontent.com/35507776/127156706-b430e40b-4c37-420a-bf2b-4e2b47c3d050.png)

## Expected behavior

I'd expect the child dropdown to move with the parent popover. See screenshot above for reference. The whole component should feel like one.

## Actual behavior

See screenshot above.

## Steps to reproduce the problem

1. Turn on orders_saved_views beta flag
1. Apply a filter to the table
1. Observe how the selection dropdown doesn't move with the filter pane.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser: Chrome
- Device: Macbook pro
- Operating System: macOs

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by alex-page** [comment]
Closing this issue as @AndrewMusgrave merged a PR to resolve it. https://github.com/Shopify/polaris-react/pull/4357

**Comment by AndrewMusgrave** [comment]
Thanks @alex-page 🙇
