### ISSUE TITLE
ResourceList: Loading spinner position is not updated.

### ISSUE THREAD

**Issue by nonjene** [Shopify/polaris-react#436]
# Issue summary

When ResourceList's items update, loading spinner's position does not recalculated.
[here is reproduction](https://codesandbox.io/s/38mjnnlmmm)

## Expected behavior

spinner should in the middle of the list when the list length changed.

## Actual behavior

not in the middle.

## Steps to reproduce the problem

1. set initial list items to be empty.
1. set list items async, which is not empty.
1. add loading state.
1. issue occur: loading spinner is not in the middle.

## Specifications

- Are you using the React components? (Y):
- Polaris version number: v2.10.0
- Browser: Chrome
- Device: macbook
- Operating System: macOS

**Comment by solonaarmstrong** [comment]
Hi @nonjene 

Thank you for opening an issue. I'm not clear if the spinner position in your sandbox is from the initial load of list items or a rerendering of a new list?

**Comment by nonjene** [comment]
Hi @solonaarmstrong 

Sorry not making it clear in the sandbox.  I have update the [reproduction](https://codesandbox.io/s/38mjnnlmmm)
The spinner position is a rerendering of a new list, the issue appear when the initial list items is empty.

**Comment by solonaarmstrong** [comment]
This is fixed in our next release.
