### ISSUE TITLE
Any documentation on how to deploy this?

### ISSUE THREAD

**Issue by joshbedo** [Shopify/polaris-react#4363]
Does any documentation exist on how to deploy this to something like AWS? I've been looking around on Google and Youtube and not finding much info. TIA!

**Comment by alex-page** [comment]
Are you trying to use the components or deploy the storybook website? You could google search deploying storybook?

**Comment by joshbedo** [comment]
@alex-page Im using the shopify-cli to start a polaris project and then need to deploy that to AWS. Haven't found a whole lot of info on deploying it.

**Comment by alex-page** [comment]
@joshbedo this would be a great topic for discussion in the [Shopify App forum](https://community.shopify.com/c/Shopify-Apps/bd-p/shopify-apps)? Polaris is just the user interface so it's not the best place to ask about deployment of projects.

**Comment by joshbedo** [comment]
@alex-page posted it in the forum but the forum doesn't seem very active. Posted days ago and no replies or anything.

**Comment by alex-page** [comment]
Ahhh dang 😔. I am unfamilliar with AWS. I have shipped applications to Vercel before. What part of deployment are you getting stuck on?
