### ISSUE TITLE
Vanilla implementation with interactive components

### ISSUE THREAD

**Issue by ry5n** [Shopify/polaris-react#437]
Polaris can be implemented in 2 ways using this library:

1. React components (recommended)
2. CSS-only implementation

## Problem

The CSS-only implementation can be used with any framework or tech stack, by adding the Polaris CDN styles and writing HTML that matches the output visible on [polaris.shopify.com](https://polaris.shopify.com/components/forms/tag#navigation) (by clicking the “HTML” button on the code samples).

The downside of the CSS-only implementation is [you need to write your own JavaScript](https://github.com/Shopify/polaris/issues/432) for any components with interactivity.

## Request

Create a “vanilla” implementation of Polaris that isn’t dependent on a framework or front-end library like React (or Vue, Angular, etc).

**Comment by ry5n** [comment]
We’re not actively working on this, but this issue exists to evaluate your interest in a framework-agnostic version of Polaris. **We encourage everyone who feels this would be easier to adopt than React to add a 👍** to the issue report above.

We’ll close this soon (as we do all inactive feature requests). Your votes will help us determine where this sits on the roadmap, so please express your interest. In addition, feel free to comment on your specific circumstances—knowing more about why this will also help inform us. 💜

**Comment by jtreminio** [comment]
I've been searching and cataloging all UI design systems I can find that are:

* React-first
* Typescript-first

There's several that are React-first, with most being straight JS or Flow. A few support Typescript via 3rd-party Types, and most of those are broken or lag far behind the official library.

Very few are actually Typescript-native, yours being one of them.

Anyway, to my point: I know this library is focused on building Shopify-related pages, but it's beautiful enough, and is React/Typescript, that I am working on building a non-ecommerce FOSS with it, that is basically an admin/dashboard app for controlling stuff.

Love the work. Thank you for doing it!

**Comment by ry5n** [comment]
As with all feature requests, I’ll close this for now. If you’d like to see this happen, please add your voice by :+1: upvoting the issue description. We take this into account when setting priorities for future work. Thanks! 💜

**Comment by multiplehats** [comment]
> 

Totally hear you on that. I kinda wanted to port it to Svelte, but it seems like an incredibly time sink lol.
