### ISSUE TITLE
Failure to build with Vite.js

### ISSUE THREAD

**Issue by vfonic** [Shopify/polaris-react#4417]
## Issue summary

I'm using Vite.js, actually [Vite Ruby](https://vite-ruby.netlify.app/), as my Rails js/ts(x) bundler.
I've added `@shopify/polaris` via yarn and, if I import any `@shopify/polaris` component, my Vite build fails.

## Expected behavior

The build should pass.

## Actual behavior

<details>
<summary>Could not resolve '../../images/upload-arrow.svg.js' from node_modules/@shopify/polaris/dist/esm/components/DropZone/components/FileUpload/FileUpload.js</summary>

```
Removed vite cache and output dirs:
        /Users/viktor/Developer/shopify_apps/ada_shopper/public/vite-dev
        /Users/viktor/Developer/shopify_apps/ada_shopper/tmp/cache/vite
        /Users/viktor/Developer/shopify_apps/ada_shopper/node_modules/.vite
Building with Vite ⚡️
vite v2.5.0 building for development...
transforming...
✓ 264 modules transformed.
Could not resolve '../../images/upload-arrow.svg.js' from node_modules/@shopify/polaris/dist/esm/components/DropZone/components/FileUpload/FileUpload.js
error during build:
Error: Could not resolve '../../images/upload-arrow.svg.js' from node_modules/@shopify/polaris/dist/esm/components/DropZone/components/FileUpload/FileUpload.js
    at error (/Users/viktor/Developer/shopify_apps/ada_shopper/node_modules/rollup/dist/shared/rollup.js:151:30)
    at ModuleLoader.handleResolveId (/Users/viktor/Developer/shopify_apps/ada_shopper/node_modules/rollup/dist/shared/rollup.js:19843:24)
    at /Users/viktor/Developer/shopify_apps/ada_shopper/node_modules/rollup/dist/shared/rollup.js:19792:22
    at async Promise.all (index 7)
    at async ModuleLoader.fetchStaticDependencies (/Users/viktor/Developer/shopify_apps/ada_shopper/node_modules/rollup/dist/shared/rollup.js:19790:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/Users/viktor/Developer/shopify_apps/ada_shopper/node_modules/rollup/dist/shared/rollup.js:19766:9)
    at async Promise.all (index 19)
    at async ModuleLoader.fetchStaticDependencies (/Users/viktor/Developer/shopify_apps/ada_shopper/node_modules/rollup/dist/shared/rollup.js:19790:34)
    at async Promise.all (index 0)

Build with Vite failed! ❌
```
</details>

I opened `@shopify/polaris` in `node_modules` and indeed, `images/upload-arrow.svg.js` is nowhere to be found. Any idea how I could fix this issue?

PS I managed to get the `@shopify/polaris` to work, but only on version 5.0.0. It would be great to be able to use the latest version. Any help would be greatly appreciated! Thanks!

## Steps to reproduce the problem

1. Create a new Rails app
1. Replace Webpacker with Vite Ruby
1. Add `@shopify/polaris`
2. Try to import any `@shopify/polaris` component

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

I looked at the CodeSandbox example, but it's using Polaris v2.x and I couldn't load styles when I switched to v6.6.0. It would be great if someone could fix the CodeSandbox.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 6.6.0
- Browser: /
- Device: /
- Operating System: macOS

**Comment by vfonic** [comment]
I see that the import in the original src imports correctly:
https://github.com/Shopify/polaris-react/blob/main/src/components/DropZone/components/FileUpload/FileUpload.tsx#L8

But locally dist doesn't seem to have `images` directory.

**Comment by BPScott** [comment]
That file looks like it exists in the npm package: https://unpkg.com/browse/@shopify/polaris@6.6.0/dist/esm/components/DropZone/images/upload-arrow.svg.js. Are you sure it is absent in your node_modules directory?

**Comment by vfonic** [comment]
That's odd!  I realized that, if I run `yarn install` using yarn v1.22.10, then I won't have `images/upload-arrow.svg.js` in `@shopify/polaris`. I ran `npm install` and it indeed added the directory. I then ran `yarn install` again and it would remove the `images` directory. 🤷‍♂️ 

I ended up upgrading to yarn 3 and now everything seems to be working. (except for the HMR)

Thanks!
