### ISSUE TITLE
Add primaryAction prop to SkeletonPage component

### ISSUE THREAD

**Issue by calebstdenis** [Shopify/polaris-react#443]
# Feature request summary
The `SkeletonPage` component should have a `primaryAction` prop corresponding to that of the `Page` component. Its type should be a boolean to indicate whether or not a primary action should appear in the Page skeleton.

## Rationale
It seems odd for `SkeletonPage` to have a `secondaryActions` prop for this purpose, but no `primaryAction`. If a given page has a primary action, one might want it to appear in the skeleton.

**Comment by solonaarmstrong** [comment]
Thank you @calebstdenis. I've opened an internal issue with your feature request.

**Comment by elizabethletourneau** [comment]
This will be available the next release. 👍

**Comment by danrosenthal** [comment]
No need to keep this open, since this is releasing soon and we close feature requests anyway.
