### ISSUE TITLE
Probably wrong pictures in Polaris documentation

### ISSUE THREAD

**Issue by noff** [Shopify/polaris-react#4444]
Spacing doc https://polaris.shopify.com/design/spacing#navigation has 2 same pictures for `text container` and `stack` components
![image](https://user-images.githubusercontent.com/937186/131019342-5bee58f3-afef-4254-9e3a-872654d3efcc.png)

Icons doc https://polaris.shopify.com/design/icons#navigation has same pictures for `Use established icons` and `Limit variations`
![image](https://user-images.githubusercontent.com/937186/131019666-6ec23592-ed3c-4580-9bf0-96276b9a1361.png)

Same for `major icons` and `mini icons`
<img width="614" alt="image" src="https://user-images.githubusercontent.com/937186/131019769-183dfb6f-d2f6-4903-9757-79b0c199bde8.png">

**Comment by alex-page** [comment]
@noff thank you legend! We fixed this up but forgot to close this issue. Appreciate you.
