### ISSUE TITLE
CRA 2 SVG import doesn't seem to work with Icon source

### ISSUE THREAD

**Issue by mbriggs** [Shopify/polaris-react#449]
# Issue summary

The recommended way to use a custom icon is to do something like this

```js
import icon from "./icon.svg";
import { Icon } from "@shopify/polaris";

<Icon source={icon} />
```

Create React App v2 uses [SVGr](https://github.com/smooth-code/svgr) to [create react components out of svg imports](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-svgs).

I may just be being dumb, but I don't see any way to make the two libraries work with each other.

## Expected behavior

It would be nice if `<Icon source />` supported the react components generated by SVGr, but really any solution of getting custom icons into Polaris when using CRA2 would be great.

## Actual behavior

You get no result from `<Icon/>`

## Steps to reproduce the problem

1. create a new CRA app
1. attempt to use a custom SVG with `Icon`

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: tried on both latest version of 2, and 3 beta 
- Browser: Chrome 69
- Device: Macbook Pro
- Operating System: OSX

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dleroux** [comment]
Again @mbriggs Thank you! 👍 I've opened an internal issue for this as well.

**Comment by lemarier** [comment]
Hi guys!

Any progress on that or any workaround?

Thanks !!
