### ISSUE TITLE
404 error on the CLA page

### ISSUE THREAD

**Issue by m4thieulavoie** [Shopify/polaris-react#4495]
## Issue summary

The CLA link found in [this page](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request) ([https://cla.shopify.com/](https://cla.shopify.com/)) resolves a 404

![image](https://user-images.githubusercontent.com/44816587/134912806-47ba5168-b935-4988-9027-6306d5c9a440.png)

If the issue is simply that the url changed, I'm happy to open a PR with the right url 👍 

## Expected behavior

The link should redirect to a page allowing to sign the CLA

## Actual behavior

The link redirects to a 404 page

## Steps to reproduce the problem

1. Go to the [contribution page](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request)
1. Click on `sign a CLA`

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by m4thieulavoie** [comment]
That seems to have been solved, closing the issue
