### ISSUE TITLE
[Page] Destructive secondary actions aren't visible

### ISSUE THREAD

**Issue by ryanwilsonperkin** [Shopify/polaris-react#4510]
## Issue summary

Destructive secondary actions in a `Page` component are almost invisible

## Expected behavior

When using:

```typescript
<Page 
	  primaryAction={{content: 'Edit', url: '/edit'}}
	  secondaryActions={[
		  {content: 'Delete', url: '/delete', destructive: true}
	  ]}
/>...</Page>
```

the secondary action should be visible in the page.
    

## Actual behavior

![image](https://user-images.githubusercontent.com/3004111/137205493-127ea747-ad03-4e16-ac3a-c91a76bac42f.png)

The contrast between the button text and background is so light as to be almost invisible. It appears we're rendering without button outline and the text is defaulting to white, probably because it expects to be on a red button but in fact we should be using red text here as the action is rendered in outline mode.

## Steps to reproduce the problem

1. Create a page
2. Add a secondary action with `destructive` set to true

## Reduced test case

https://codesandbox.io/s/page-with-destructive-secondary-action-432wd?file=/src/App.tsx

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: ^7.0.0
- Browser: Chrome
- Device: Macbook Pro 2019
- Operating System: macOS Big Sur v11.6

**Comment by danwetherald** [comment]
I am also seeing this issue, what am I missing? It seems impossible to me that this could actually be a global issue?
