### ISSUE TITLE
Why example has useCallback?

### ISSUE THREAD

**Issue by angeloocana** [Shopify/polaris-react#4515]
Hi, I would like to understand why the example for [choice-list](https://polaris.shopify.com/components/forms/choice-list) has a `useCallback`:

```
const [selected, setSelected] = useState(['hidden']);

const handleChange = useCallback((value) => setSelected(value), []);
```

The `setSelected` function comes from `useState`, so it will always have the same reference in memory on every render.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by vanduc1102** [comment]
From my understanding, this is a React question :  https://reactjs.org/docs/hooks-reference.html#usecallback
```
  const handleChange = useCallback((value) => setSelected(value), []);
```

will run only once

while

```
  const handleChange = (value) => setSelected(value);
```
will run every times when the component needs to re-render

IMO, it is[ pre-optimization](https://softwareengineering.stackexchange.com/questions/80084/is-premature-optimization-really-the-root-of-all-evil)

**Comment by angeloocana** [comment]
We don't even need the `handleChange` function, we can just pass `setSelected` directly.

The example could be just:
```
function SingleChoiceListExample() {
  const [selected, setSelected] = useState(['hidden']);

  return (
    <ChoiceList
      title="Company name"
      choices={[
        {label: 'Hidden', value: 'hidden'},
        {label: 'Optional', value: 'optional'},
        {label: 'Required', value: 'required'},
      ]}
      selected={selected}
      onChange={setSelected}
    />
  );
}
```

The useCallback is unnecessary in this case, and it just makes the example more complex.

**Comment by kyledurand** [comment]
Hey Angelo. I wasn't on the team when these were made but I've always thought of the examples as best practices at scale. I've seen form pages that re-render every field on every change (i.e. any time you type a key into a text field the whole form re-renders). So creating these simple functions on every render can be taxing unless they're cached.

I agree that, especially with this example, it's weird to abstract the function into a useCallback but at the same time all of our examples are consistent.

That said, they're just examples and you should code your project as you see fit.
