### ISSUE TITLE
Issue with Tabs

### ISSUE THREAD

**Issue by badoet** [Shopify/polaris-react#455]
# Issue summary

Updated the polaris library
and now tabs looks not right,
it only show the first tab, the rest of tab is hidden on the side like mobile view

## Expected behavior

it should show all tabs

## Actual behavior

it only show the first tab, the rest of tab is hidden on the side like mobile view

## Steps to reproduce the problem

1. just load a page with multiple tab item in the tabs component

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.12.1
- Browser: any
- Device: any
- Operating System: any

**Comment by ry5n** [comment]
This sounds like the same issue as https://github.com/Shopify/polaris-react/issues/169—are you able to confirm @badoet?

**Comment by ry5n** [comment]
Without more info I’ll assume this is a duplicate of #169
