### ISSUE TITLE
Try-catch Syntax error in Modal 

### ISSUE THREAD

**Issue by youminkim** [Shopify/polaris-react#4552]
## Issue summary

After 7.0.0 update, try-catch syntax errors happens in any Modal component usages in some Android 

## Expected behavior

No syntax error

## Actual behavior

```
SyntaxError: Unexpected token {
  at ? (./node_modules/@shopify/polaris/build/esm/components/Modal/Modal.js:69:9)
```

```
    const iframe = evt.target;
    if (iframe && iframe.contentWindow) {
      try {
        setIframeHeight(iframe.contentWindow.document.body.scrollHeight);
      } catch {
        setIframeHeight(DEFAULT_IFRAME_CONTENT_HEIGHT);
      }
    }
    if (onIFrameLoad != null) {

```

## Steps to reproduce the problem

Any Modal component use.

Nextjs 

## Reduced test case
-

## Specifications

- Are you using the React components? Y
- Polaris version number: 7.0.0
- Browser: Chrome Mobile Webview (62.0.3202)
- Device: Vivo 1716
- Operating System: Version:8.1.0

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by youminkim** [comment]
Sentry error log sample

<img width="1217" alt="Screenshot 2021-10-27 at 2 49 15 PM" src="https://user-images.githubusercontent.com/317132/139014404-38413d11-a87f-4891-b96a-6f641e60fdb2.png">
