### ISSUE TITLE
DatePicker (translate/locale)

### ISSUE THREAD

**Issue by joohncruz** [Shopify/polaris-react#456]
Hi guys, fine?

I'm using Datepicker component however need translate months and days for my application. 

I read about internationalization, but this component uses the properties: 

DatePicker
   - nextMonth
   - previousMonth
   -  today

How could I solve my question? Could someone help me?

**Comment by solonaarmstrong** [comment]
Hi @joohncruz 👋   Currently, we expose the `weekStartsOn` prop that allows you to change the first day of the week, since different countries have different calendars. The rest is handled by the browser locale settings.

**Comment by joshuajay** [comment]
Hi! The Analytics Team is also impacted by this as we'd like to have our date pickers fully internationalised, including the calendars that come from Polaris.

My initial thought was to pass through a `locale` prop and use `Intl.DateTimeFormat` to format the dates in the required locale. That way we won't need to handle individual translations of every single month / day / year etc.

<img width="698" alt="screen shot 2019-01-14 at 11 00 23 am" src="https://user-images.githubusercontent.com/32902385/51124217-c0bee480-17eb-11e9-836a-e0d3d8b07aa9.png">

**Comment by joshuajay** [comment]
Also, happy to contribute on this, or pair, or whatever is necessary :)

**Comment by joshuajay** [comment]
I'm going to work on a PR and see where it gets me :)

**Comment by chloerice** [comment]
Thanks @joshuajay!!!

**Comment by chloerice** [comment]
The fix shipped in #1005 will be available in the 3.7.2 release.
