### ISSUE TITLE
Shopify App Bridge context consumer for migrating off legacy React context APIs

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react#457]
# Feature request summary

For current embedded apps trying to interact with the App Bridge, the suggestion is to use the legacy `static contextTypes`, as mentioned in the docs: https://polaris.shopify.com/components/structure/app-provider#section-access-to-the-shopify-app-bridge-instance. As of React 16.6, `StrictMode` will [now start warning](https://reactjs.org/blog/2018/10/23/react-v-16-6.html#deprecations-in-strictmode) that it's deprecated.

This request is for a `Context.Consumer` or HOC (or other mechanism) that gives us access to the App Bridge through the now stable context APIs built in React 16.3 as well as the additional `static contextType` added in React 16.6 (https://reactjs.org/blog/2018/10/23/react-v-16-6.html#static-contexttype). Since there's already an `AppProvider` that is required at the top level of Polaris apps, perhaps there just needs to be a corresponding `AppContextConsumer` component that can wrap components needing access to the App Bridge.

## Rationale

The biggest benefit would be to better prepare Polaris, and all downstream consumers of Polaris, for future React releases as they deprecate the legacy context APIs.

**Comment by tmlayton** [comment]
@mbaumbach thanks for bringing this up. With v3.0.0 release coming soon we will look at making this change in v4.0.0.

**Comment by BPScott** [comment]
This will be part of polaris v4, though we also recommend using `@shopify/app-bridge-react` instead of configuring AppProvider to setup app-bridge

**Comment by BPScott** [comment]
#1877 adds  `AppBridgeContext` as an export in v4 (which will hopefully have a final release in about 2 weeks time).

Though the recommended long term solution is to move onto using the [components from app-bridge-react](https://help.shopify.com/en/api/embedded-apps/app-bridge/react-components) (which also uses modenr context). See their docks on the [Provider component](https://help.shopify.com/en/api/embedded-apps/app-bridge/react-components/provider) for how to setup their context provider
