### ISSUE TITLE
Define spacing tokens with greater variation

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#4603]

**Comment by aveline** [comment]
Proposing these spacing values and custom property names based on the existing spacing scale and spacing explorations

```
--p-space-0: 0
--p-space-100: 4px
--p-space-200: 8px
--p-space-300: 12px
--p-space-400: 16px
--p-space-500: 20px
--p-space-600: 32px
```

**Comment by sarahill** [comment]
I actually did some more recent exploration linked in the doc below. What you've got there might be good enough for this first pass though https://docs.google.com/document/d/1oJuLuSs378uWFlk8MMfhdyy2kdeSmojLZdhoYB9op5U/edit?pli=1#heading=h.ds7vyvz4qn4l
