### ISSUE TITLE
Replace rem() function with tokens and postcss plugin

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#4605]
- [x] Investigate [pixrem](https://www.npmjs.com/package/pixrem) and [pxtorem](https://www.npmjs.com/package/postcss-pxtorem).

Release steps
- [x] Ship pxtorem in next release
- [x] Remove `rem()` function from public sass
- [x] Remove `px()` function from public sass
- [x] Update `html` `font-size` to `100%` and ensure any `rem` values are updated accordingly
- [x] #4776

**Comment by BPScott** [comment]
While you're poking at removing stuff in _utilities.scss, could you remove the `em()` and `px()` functions too?

Both the rem and em functions trigger deprecation warnings in dart-sass that can't be resolved without breaking compatibility with node-sass (short of just deleting the functions), so if we're getting rid of one it'd be good to get rid of both.

**Comment by aveline** [comment]
This issue should also include updating `html` `font-size` to `100%`
