### ISSUE TITLE
[EmptyState] Image not wrapping on medium viewports

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react#462]
# Issue summary

There seems to be a regression in the breakpoints for the empty state component, specifically for medium sized screens. When provided an image, it shrinks to a very small size instead of wrapping. 

## Expected behavior

The image should wrap below the desktop breakpoint.

![image](https://user-images.githubusercontent.com/18447883/47470054-f0e08380-d7b8-11e8-8472-a4f7d93f93c0.png)

## Actual behavior

The image shrinks to fit right of the content.

![empty-state-weird-breakpoint](https://user-images.githubusercontent.com/18447883/47470377-53864f00-d7ba-11e8-8ea6-10f238902c3e.gif)

## Steps to reproduce the problem

1. Log into a test shop's admin and navigate to `/admin/discounts/automatic`.
2. Resize the window.
3. You should see the image shrink to a very small size before wrapping to the next row.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: v3.0.0-rc.3
- Browser: Chrome (latest)
- Device: MacBook Pro (Retina, 15-inch, Mid 2014)
- Operating System: High Sierra (10.13.6)

**Comment by CameronGorrie** [comment]
Looks like the wrapping is fixed in 3.8. Is this the expected alignment though?

<img width="545" alt="screen shot 2019-02-20 at 6 08 59 pm" src="https://user-images.githubusercontent.com/3865674/53131908-1e0d2a80-353c-11e9-88be-84f62fd51e83.png">

I was expecting the illustration to be centered but perhaps this is intentional.
