### ISSUE TITLE
Unexpected origin error

### ISSUE THREAD

**Issue by minotaurrr** [Shopify/polaris-react#476]
# Issue summary

This is my first time building a shopify app so I'll try to describe the whole thing I did to get to the issue since I might have done something wrong that's not directly related to Polaris..

I have a Node.JS express server handling app install/oAuth. The same express server also serves the `build` directory for polaris front-end. When the oAuth process is done, i just do `res.sendFile(path.join(__dirname, 'build', 'index.html))`.
The express server is being proxied through ngrok.

This is the entry point of the front-end.
```
const shopOrigin = process.env.REACT_APP_HOST;
const apiKey = process.env.REACT_APP_API_KEY;
...
<AppProvider shopOrigin={shopOrigin} apiKey={apiKey}>
        <App />
</AppProvider>
```

When I go to the dev store app admin page I get this error in my browser console
`Shopify.AppMessenger received message null from unexpected origin https://xxxx.ngrok.io `

Does this mean the `shopOrigin` props value has to match the actual shop URL? 

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.12.1
- Browser: Chrome
- Device: Macbook Pro
- Operating System: macOS

**Comment by tmlayton** [comment]
Hey @minotaurrr 👋 

> Does this mean the shopOrigin props value has to match the actual shop URL?

That is correct, and the URL should include the scheme too (`https://`). See https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk/initialization for information.

Also, if your ngrok tunnel URL updates when you restart it, you will need to update your app URL and the callback URL in the Partners dashboard with the updated ngrok URL.

The good news is `shopOrigin` will no longer be needed in v3.0.0 as we sort that out for you in the background.

**Comment by minotaurrr** [comment]
Hi @tmlayton 
But when I do that the app page still doesn't load properly.

The error I get is `Uncaught SecurityError: Failed to read the 'sessionStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.`

Also getting this warning as well `Shopify.AppMessenger received message null from unexpected origin https://******.ngrok.io ; expecting http://******.ngrok.io or subdomain thereof`
