### ISSUE TITLE
Documentation: incorrect formatting for "Helper text and descriptions" example

### ISSUE THREAD

**Issue by ugarrda** [Shopify/polaris-react#4764]
## Issue summary

The "Do" example unordered list for **Helper text and descriptions** on polaris.shopify.com is formatted incorrectly.

https://polaris.shopify.com/content/grammar-and-mechanics#section-lists
## Expected behavior

The text "Reduces the number of fields required to check out. The billing address can still be edited." is helper text, and should be part of the first list item.
## Actual behavior

The text is displayed as its own separate list item.

## Steps to reproduce the problem

1. Navigate to https://polaris.shopify.com/content/grammar-and-mechanics#:~:text=Reduces%20the%20number%20of%20fields%20required%20to%20check%20out.%20The%20billing%20address%20can%20still%20be%20edited.

## Specifications

- Are you using the React components? (Y/N): not applicable
- Polaris version number: not applicable
- Browser: Chrome Version 96.0.4664.55 (Official Build) (x86_64)
- Device: MacBook Pro (16-inch, 2019)
- Operating System: macOS 11.6.1 (20G224)

**Comment by mbensch** [comment]
Thank you for bringing this to our attention! We have decided to remove this section for now since it was indeed confusing and didn't add any value.
