### ISSUE TITLE
Add small icon size for Cancel icon

### ISSUE THREAD

**Issue by loic-d** [Shopify/polaris-react#481]
# Feature request summary

Consider adding another size for the cancel icon.

## Rationale

In Discounts, we have the following UI allowing merchants to add products or collections to their discount. Once added, products or collections can also be removed using the `X` icon.

<img width="670" alt="screen shot 2018-10-26 at 1 29 12 pm" src="https://user-images.githubusercontent.com/3925905/47583657-1b9c1a80-d926-11e8-876e-7a1cf1eb5a40.png">

Originally, we came up with our own HTML `button` wrapping the `Icon` component. We added some CSS to force the Icon size.

```
<button
        type="button"
        className={styles.RemoveButton}
        onClick={this.handleRemoveItem}
        onTouchStart={this.handleRemoveItem}
      >
        <Icon source="cancel" color="skyDark" />
</button>

.RemoveButton {
  @include unstyled-button;
  width: 1.25rem;
  height: 1.25rem;
  margin-top: spacing(extra-tight);
}
```

To improve accessibility, we switched to the Polaris `Button` with an icon. But the icon size is too big, even when using `cancelSmall`.

```
<div className={styles.RemoveButton}>
        <Button
          id={`remove-btn-${id}`}
          icon="cancelSmall"
          plain
          onClick={this.handleRemoveItem}
        />
</div>
```

We've decided to keep the Polaris `Button` and added some CSS to force the size/position of the icon:
```
.RemoveButton {
  display: flex;

  svg {
    position: absolute;
    top: 50%;
    right: 0;
    left: 0;
    width: 1.5rem;
    height: 1.5rem;
    margin: auto;
    transform: translateY(-50%);
    text-align: center;
    color: color('sky', 'dark');
  }
}
```

Another solution would be to just add another icon size.

<img width="367" alt="screen shot 2018-10-26 at 1 52 36 pm" src="https://user-images.githubusercontent.com/3925905/47583785-6f0e6880-d926-11e8-8ae7-4c93ba9d01e0.png">

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by ry5n** [comment]
> But the icon size is too big, even when using `cancelSmall`.

Can you attach a screenshot? The small cancel icon is meant for this use case.

**Comment by loic-d** [comment]
As discussed in Slack, it seems like the right thing to do is to use `cancelSmall`.
Closing this issue for now.
