### ISSUE TITLE
Error in production: "Cannot read property 'removeChild' of null"

### ISSUE THREAD

**Issue by djhoughton** [Shopify/polaris-react#483]
# Issue summary

We're seeing some of these errors on the dashboard so I opened up an issue and linked to it here: https://github.com/Shopify/web/issues/7838

[Bugsnag](https://app.bugsnag.com/shopify/shopify-web-client/errors/5bb7b4390ef79e00191f854c?event_id=5bd360f600309179fb880000&i=gh&m=ci)

`TypeError · Cannot read property 'removeChild' of null`

node_modules/@shopify/polaris/esnext/components/Portal/Portal.js:26:22t.value
```
...
componentWillUnmount() {
   document.body.removeChild(this.portalNode);
}
render() {
   return this.state.isMounted
...
```

**Comment by solonaarmstrong** [comment]
Thank you @djhoughton. I've passed along the issue to the right team.

**Comment by AndrewMusgrave** [comment]
Looks like this is happening very frequently. Seems have started right after the recent changes to `Portal` @dleroux
