### ISSUE TITLE
Question about “breaking rules” with Polaris 

### ISSUE THREAD

**Issue by johnwheeler** [Shopify/polaris-react#4849]
@alex-page, apologies if this is the wrong venue for this question, but I figured it be better to ask here where other people might benefit instead of sending you an email.

 I recently watched the interview you did: https://youtu.be/z-duiMhoWKE

Throughout the interview, you alluded that you wanted Polaris users to “break rules” and build things that would distinguish apps from being made by shopify. You mentioned there have been cases where a 3rd party polaris app reflects negatively on Shopify even.

Being that Polaris users are tightly constrained from deviating from the styles put forth, what did you mean by “break rules”? Does that mean changing theme colors or forking Polaris and customizing it, adding components, changing styles? How far can and should Polaris users go in your mind?

thanks

**Comment by alex-page** [comment]
Hey @johnwheeler sorry for taking so long to get back to you.

When I said break the rules. I mean build the best solution for your user. If a color, shadow, font family could be changed to give the user the best experience. Do that.

The current system doesn't encourage this in components. We are working towards adding the ability to use the layers below them. Check out our new css custom properties in version 9.

**Comment by johnwheeler** [comment]
Nice I'll take a look at those. Thanks!
