### ISSUE TITLE
EASDK Header splitting into two rows

### ISSUE THREAD

**Issue by dansundy** [Shopify/polaris-react#487]
# Issue summary

My header in the EASDK is divided up onto two lines. See screenshot below:

<img width="1223" alt="screen shot 2018-10-27 at 12 44 26 pm" src="https://user-images.githubusercontent.com/1348412/47606911-ad1f9100-d9e7-11e8-9bf8-bd9b8493f02f.png">

This is only happening on our staging environment. It is not happening when tunnelling localhost through ngrok or on our production server (though we haven't pushed our latest app changes due to this issue).

We are using React Polaris and the new AppProvider for the EASDK. Our `Page` component is only specifying the actions. We are not declaring title, icon or breadcrumbs. Here's what the code looks like:

```
<Page
    primaryAction={this.primary}
    actionGroups={this.dropdown}
    secondaryActions={this.secondary}
>
    {this.props.children}
    {this.props.footer ? <Footer showMenu /> : null}
</Page>
```

## Expected behavior

The EASDK header should be on one line. It should not have the icon and it should not say "by Empyre" on the right. We're not sure where the latter comes from.

## Actual behavior

The EASDK header divides into two full width sections.

## Steps to reproduce the problem

No steps required, it's just happening on the staging build. If necessary, I can provide the staging URL.

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number:  2.9.0
- Browser: Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- Device: Macbook Pro
- Operating System: OSX El Capitan 10.11.6

**Comment by dansundy** [comment]
A couple of quick updates:

1) I pushed our master branch back up to the staging server and the issue remains so it is not something in the code.

2) There is a new "Navigation" section in Extensions --> Embedded app. (See screenshot below). This section is only there on our Staging app and there doesn't seem to be any way to disable it.

<img width="1072" alt="screen shot 2018-10-29 at 10 31 35 am" src="https://user-images.githubusercontent.com/1348412/47657525-a1f36f00-db67-11e8-91c5-f918ef9a2b50.png">

Maybe I'm posting this in the wrong place, now that I've seen this in the dashboard, but can somebody shed some light on what's happening here?

**Comment by mbaumbach** [comment]
@dansundy I believe this is part of the rollout of the new Shopify App Bridge (replacing the EASDK): https://ecommerce.shopify.com/c/api-announcements/t/shopify-app-bridge-548274

We noticed this too, only for some of our apps. The secondary and primary buttons being separated can be fixed by creating at least one navigation item in that new embedded app navigation section.

**Comment by dansundy** [comment]
Thanks, @mbaumbach. I just got that announcement as well. Is there going to be a way for Polaris to edit the parameters of the title bar? For example, we do not want the byline. We also do not want the second menu bar at all. It's a huge waste of space.

I can't find anything about this in the Polaris documentation. There is also no indication or screenshots of how different actions will affect the title bar in the App Bridge documentation.

**Comment by mbaumbach** [comment]
@dansundy I'm not too sure. There's a bunch of references to the App Bridge in the upcoming [3.0 Polaris code](https://github.com/Shopify/polaris-react/tree/v3.0.0-rc.4). I suspect we'll know more about how this all works with Polaris soon!

**Comment by tmlayton** [comment]
Hey @dansundy and @mbaumbach, yes the split title bar is part of the Shopify App Bridge rollout. Sorry, I can’t really speak to the ability to turn off the second menu bar or details around the embedded navigation. But just as `Page` and a few other components wrap the EASDK in <= v2.x, the components in v3 are updated to wrap the Shopify App Bridge and entirely remove the legacy EASDK code.

**Comment by dansundy** [comment]
I see that there is a [Top Bar component that is under construction](https://polaris.shopify.com/components/component-status), which may give us some control over what's going on up there. I guess we just have to hope that Polaris 3.0 comes out before the App Bridge fully rolls out? Is there a scheduled date for 3.0?

**Comment by tmlayton** [comment]
@dansundy because the split title bar is part of the design, for now the best place is provide feedback is https://ecommerce.shopify.com/c/shopify-apis-and-technology.

Top bar is not a component for embedded apps, it will be for standalone apps building with Polaris.  And v3.0.0 has a dependency on the Shopify App Bridge being fully rolled out so it has to come after. v3.0.0 release is planned for this week.

**Comment by dansundy** [comment]
Thanks @tmlayton and @mbaumbach. I appreciate the information.
