### ISSUE TITLE
[Autocomplete][v1] ComboBox mutates the options prop

### ISSUE THREAD

**Issue by jineshshah36** [Shopify/polaris-react#490]
# Issue summary

I get the following error when trying to use the autocomplete component: TypeError: Cannot add property id, object is not extensible. The reason is because of this function:

    function assignOptionIds(options, comboBoxId) {
        options.map(function (option, optionIndex) {
          option.id = comboBoxId + '-' + optionIndex;
        });
        return options;
    }

I user immer which freezes all of my state objects to ensure they are not mutated. However, this function in the ComboBox component is breaking that expectation by mutating every option. Even if I wasn't using immer, this is a big problem since you could likely be overriding existing values held in the options object (especially since id is such a common key). To see a clear example of the problem, visit this [codesandbox](https://codesandbox.io/s/o55n9w4w69) and open the console. On select, I am logging the original options list, which has now been mutated. 

## Expected behavior

Shopify Polaris components should never mutate any props given to them.

## Actual behavior

ComboBox is mutating the options prop.

## Steps to reproduce the problem

1. log the options prop after the autocomplete component has been rendered

## Reduced test case

To see a clear example of the problem, visit this [codesandbox](https://codesandbox.io/s/o55n9w4w69) and open the console. On select, I am logging the original options list, which has now been mutated. 

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.0.0-rc.4
- Browser: Chrome
- Device: Mac
- Operating System: MacOS

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.
