### ISSUE TITLE
Polaris v9

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#4910]
## Overview 

- Done criteria for v9 is removing sass functions and replacing with tokens. These are breaking changes that set us up for our goal of 100% token coverage.
- Some sass functions have long tentacles and removal is tied with other work. Document those that won't be removed in v9 and instead get pushed out to v9.x or v10.
- Removal of some sass mixins that are breaking changes and small enough in scope to be an easy win.

## Timeline

- **Release Goal Date**: Feb 8
- [x] #5180

## Prepare for RC
- [x] #5019
- [ ] Confirm legacy tokens are converted to `rem`
- [x] #5002
- [x] #5003

## Blockers
- [x] https://github.com/Shopify/polaris-react/issues/4896 getting the fontsize/spacing value calculation simplified

### Communication strategy
- [x] #4935
- [x] #5174

### Documentation page on polaris.shopify.com
- [x] #4936
- [x] https://github.com/Shopify/polaris-styleguide/issues/4904

### Migration guide
- [x] #5004
- [x] #5005
- [x] #5006
- [x] #4706
- [x] #5007
- [x] #4883
- [x] #5111
- [x] #5131

**Cleanup** 
- [x] #5126
- [x] #5127
- [x] #5128
- [x] #5129
- [x] #5130
- [x] #5140

### `/web`
- [x] #5152

### Deprecate public api
- [x] #4980

### SCSS functions

Replace SCSS functions related to tokens with css custom properties. If a scss function can be replaced with a css custom property it should. Document any scss functions that cannot be removed right now in Follow Up Tasks below.

**foundation/_accessibility.scss**
- [x] #4913
- [x] #4914

**foundation/_borders.scss**
- [x] #4915

**foundation/_colors.scss**
- [x] #4916

**foundation/_typography.scss**
- [x] #4918
- [x] #4919

**foundation/_utilities.scss**
- [x] #4920
- [x] #4921
- [x] #4937 Remove `@function em`

**shared/_icons.scss**
- [x] #4923

**shared/_interaction-state.scss**
- [x] #4988

**shared/_layout.scss**
- [x] #4926

**shared/_links.scss**
- [x] #4927

**shared/_lists.scss**
- [x] #4928

**shared/_printing.scss**
- [x] #4985
- [x] #4986

**shared/_private-breakpoints.scss**
- [x] #4930

**shared/_skeleton.scss**
- [x] #4983
- [x] #4984

**shared/_printing.scss**
- [x] #4929

**Comment by BPScott** [comment]
> `@function em` - keep until layout project

The web folks have a ticket to [investigate using dart-sass](https://github.com/Shopify/web/issues/53583) as node-sass has been deprecated for a while. Using dart-sass with polaris-react's public API spits out [lots of deprecation warnings](https://github.com/Shopify/polaris-react/issues/4725). I pushed for the removal of the rem/em/px functions as the vast majority of those deprecation warnings are due to the usage of those functions. I've been telling folks "lets wait till polaris v9 as that'll remove most of the deprecation warnings and thus make the investigation easier".

Would it be possible to reconsider this stance, and either get `em()` removed in v9, or adjust it so it doesn't spit out a warning every time it is used (which is lots of times because it is used in the breakpoint() function which is used by the various breakpoint mixins which are used extensively in `web`)?

**Comment by aveline** [comment]
@BPScott removing `em()` isn't so straightforward and would really increase the scope of `v9`. But yes we can look at adjusting it so it doesn't spit out a warning every time it's used. Is it a matter of refactoring the existing `em()` function to use `math.div()`?

**Comment by BPScott** [comment]
> Is it a matter of refactoring the existing `em()` function to use `math.div()`?

Per https://github.com/Shopify/polaris-react/issues/4725 `math.div` is a problem because it is present in dart-sass but not in node-sass.

**Comment by aveline** [comment]
@BPScott what approach would you suggest for quieting the `em()` down until we are able to remove it?

**Comment by BPScott** [comment]
It's not really fixable in place unfortunately. We'd need to reduce usage of `em()`. Fortunately it seems that `em()` is only used for values you pass into `breakpoint()`. So if we refactor `breakpoint()` to avoid relying on `em()`'s general-purpose behaviour then we get closer

I had an idea for how that could be done in https://github.com/Shopify/polaris-react/pull/4861#issuecomment-1005176633

> Perhaps we could do something like claiming that breakpoint() now only accepts values/ adjustments in pixels (make it throw errors on other units) and that it shall internally convert that value into an em value by multiplying 0.0625 - the same as dividing it by 16, except you don't need to use the division sign that would trigger the deprecation warning (as 1em always equals 16px when used within a media query at the default zoom level).

**Comment by BPScott** [comment]
#4937 removes the `em` function

**Comment by BPScott** [comment]
As we'll be removing lots of the content within `styles/_common.scss`, it is likely that many component scss files no longer reference the mixins/functions that remain within that file. Once the trimming of the API is done, it might be worthwhile to go audit cases where component files do `@import '../../styles/common';`, and if no mixins/functions from that file are used then the import can be removed.
