### ISSUE TITLE
Inconsistent styling for checkbox component

### ISSUE THREAD

**Issue by chrisdusyk-iq** [Shopify/polaris-react#492]
# Issue summary

I don't know if this is an issue for Polaris or Chrome, but when viewing the checkbox component in Chrome on a display scaled at anything other than 100%, the checkbox gets inconsistent drop shadows. I didn't see the same behaviour in Firefox or Edge, so I'm not sure if it's a problem for you guys or an inherent Chrome problem.

## Expected behavior

Styling should be consistent regardless of scaling. At standard 100% scaling, the checkboxes look like:

![image](https://user-images.githubusercontent.com/41026008/47682511-47bbd380-db92-11e8-8011-7da016a96608.png)

## Actual behavior

The checkboxes have inconsistent drop shadows in Chrome at greater than 100% scaling (125% tested in this case):

![image](https://user-images.githubusercontent.com/41026008/47682555-68842900-db92-11e8-9244-e1958f822bf5.png)

## Steps to reproduce the problem

1. Display a form with a checkbox
2. Change display scaling to 125%

## Reduced test case

[Codesandbox](https://codesandbox.io/s/7yxl94pqkq)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.12.1
- Browser: Chrome
- Device: PC
- Operating System: Windows 10

**Comment by ry5n** [comment]
Confirmed. This is an issue with the way the border is drawn on the checkbox. Switching to using `border` seems to have the same issue. Using `box-shadow` avoids the issue (and would reduce some of the markup complexity here). It would require work-arounds for windows high-contrast mode, but the current approach probably also has those issues.

The way forward depends on how serious we consider this. @chrisdusyk-iq do you think this is largely aesthetic, or is it impacting usability?

**Comment by chrisdusyk-iq** [comment]
@ry5n I don't think it impacts usability, and is mainly cosmetic. It leaps out at you but doesn't impact your ability to toggle the checkbox.
