### ISSUE TITLE
Remove `shared/_private-breakpoints.scss`

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react#4930]

**Comment by lgriffee** [comment]
**Quick wins for `shared/_private-breakpoints.scss` that should be pushed to v9.0.0**
- Move all variables and mixins to  `ResourceList.scss`
- Remove `shared/_private-breakpoints.scss` file

**Comment by BPScott** [comment]
If #4980 is completed, then it could also be possible to merge this file with _breakpoints.css.
