### ISSUE TITLE
[toast-web] 

### ISSUE THREAD

**Issue by Huiyufish** [Shopify/polaris-react#495]
# Feature request summary
Hi guys,

i saw the toast component already launched, but only Android and iOS, i wonder if Polaris will launch [web toast] in the future?

I'm using banner to instead of toast function now, but it's not perfect. cause for some unimportant notices, banner is too heavy and a bit interrupted, comparing banner, toast is subtle and slight.

i will appreciate so much if you tell me the further plan for Polaris [toast]. Thanks!

## Rationale

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by BPScott** [comment]
The [Toast component is currently in master](https://github.com/Shopify/polaris-react/tree/master/src/components/Toast) and will be released as part of Polaris v3.0.0, which we're hoping to release sometime this week.
