### ISSUE TITLE
[Feature request] Steps Breadcrumbs 

### ISSUE THREAD

**Issue by superwhykz** [Shopify/polaris-react#498]
Is there component similiar to `steps breadcrumbs`?  [Bootstrap Steps Breadcrumb](https://bootsnipp.com/snippets/DrKen)

**Comment by AndrewMusgrave** [comment]
Hi @superwhykz , polaris doesn't currently have any similar components to `steps breadcrumbs`.

**Comment by superwhykz** [comment]
Ehh.... I see :( Can this request be converted to `Feature request`? otherwise I am ok to close it.

**Comment by AndrewMusgrave** [comment]
I added a feature request label, feel free to upvote so we can gage interest 😄

**Comment by tmlayton** [comment]
Going to close this for now, but still feel free to upvote 👍as @AndrewMusgrave mentioned
