### ISSUE TITLE
[Autocomplete][v1] ComboBox events are unexpectedly triggered

### ISSUE THREAD

**Issue by darrenhebner** [Shopify/polaris-react#499]
# Issue summary
The ComboBox component's internal logic has some strange behaviour. When observing when the `handleBlur`, `handleClick`, and `handleFocus` events, they are being called in unexpected situations. This is making it difficult to hook in to these events to add new features to the ComboBox.

## Expected behavior
- `handleBlur` and `handleFocus` should not be called at the same time.
- The state of `popoverActive` should not be toggled multiple times for a single event.

## Actual behavior
Here are some examples of these handlers being called at strange times. Note that the boolean beside each item is the current `popoverActive` state. Notice that it is being updated multiple times for each event.

| Event | | | | |
| --- | --- | --- | --- | --- |
| **Click option in popover** `true` | handleBlur `false` | handleFocus `true` | handleClick `true` | |
| **Tab in to component** `false` | handleFocus `true` | **Hit tab again** | handleBlur `false` |  handleFocus`true` |
| **Tab between items in popover** `true` | handleBlur `false` | handleFocus `true` |

## Steps to reproduce the problem
Try adding some `console.log`s to these handlers. Try the events mentioned above.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: `3.0.0-rc.3`
- Browser: Chrome
- Device: Macbook
- Operating System: macOS High Sierra

**Comment by dpersing** [comment]
Hi @darrenhebner! Sorry for the quiet on this. Just to clarify, you're working with the new [AutoComplete](https://polaris.shopify.com/components/forms/autocomplete#navigation) component, correct?

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.
