### ISSUE TITLE
Modal.render may leak `onClose` handlers during server-side render

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/polaris-react#501]
# Issue summary
I'm still digging into the exact cause of this, but I think it's worth raising without 100% context.

Shopify's admin has a server side memory leak that _seems_ to be caused by a stateless functional component's `onClose` handler leaking via `Polaris.Modal`.

The exact link of code causing the leaks is at: https://github.com/Shopify/polaris-react/blob/6e441cb28e4549f0805b93d685094ef52712299e/src/components/Modal/Modal.tsx#L154

I'm a tad confused by this because:
- I don't understand why the bind is necessary 😅 
- I think modals aren't rendered server-side, so this seems like unnecessary work?

## Expected behavior
I _think_ that Polaris should defer Modal rendering work until after the component is mounted.  This is an optimization suggestion, that happens to work around admin's leak 😄 

## Actual behavior
`onClose` bindings prevent garbage collection of modal consumers.

## Steps to reproduce the problem
Ping me in Slack for more info.

## Reduced test case
N/A

## Specifications
- Are you using the React components? Y
- Polaris version number: 3.0.0-beta.13
- Browser: node
- Device: N/A
- Operating System: macOS High Sierra 10.13.6

**Comment by BPScott** [comment]
Closed in #502
