### ISSUE TITLE
ResourcePicker: failed import

### ISSUE THREAD

**Issue by lemarier** [Shopify/polaris-react#504]
# Issue summary
Attempted import error: 'ResourcePicker' is not exported from '@shopify/polaris'.

## Expected behavior
ResourcePicker should be exported

## Actual behavior
Can't use the product picker. All other components works.

## Steps to reproduce the problem

```
import { ResourcePicker } from '@shopify/polaris'
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.12.1

**Comment by BPScott** [comment]
Hi @lemarier,

In Shopify v2.12.1 the ResourcePicker, and other embedded components are imported using `import {ResourcePicker} from '@shopify/polaris/embedded';`
As per https://github.com/Shopify/polaris-react/blob/v2.12.1/documentation/Embedded%20apps.md


The current master branch is for (the currently unreleased) v3, which changes the location of our embedded components, moving them into the main component namespace and thus allowing them to be exported as `import { ResourcePicker } from '@shopify/polaris'`.
