### ISSUE TITLE
New License?

### ISSUE THREAD

**Issue by jho406** [Shopify/polaris-react#509]
Hi there!

I noticed a license change in this commit: https://github.com/Shopify/polaris-react/commit/a3c2898ac4d210b2eed6b4e91fa5d7c2a8021d3e

Is there a reason that Polaris no longer MIT Licensed? It would be pretty hard to use Polaris on an external application since `visually distinct` is open to interpretation and rest soley on `Shopify in its sole discretion`.  Although, i understand the intention.

What are the chances that it could be changed back to MIT?

**Comment by danrosenthal** [comment]
👋 Hey @jho406, thanks for the issue. 

> I noticed a license change in this commit: https://github.com/Shopify/polaris-react/commit/a3c2898ac4d210b2eed6b4e91fa5d7c2a8021d3e

That's correct, we're updating our license to a [custom license](https://github.com/Shopify/polaris-react/blob/master/LICENSE.md) once we release Polaris 3.0.0 (currently in a release candidate).

> Is there a reason that Polaris no longer MIT Licensed?

We made this change because the 3.0.0 release will contain [components for building an application frame](https://github.com/Shopify/polaris-react/blob/master/UNRELEASED.md). These components would make visually recreating the Shopify admin possible, so the change to the license was made in order to guard against that. 

> What are the chances that it could be changed back to MIT?

We are not considering changing back to MIT.

**Comment by jho406** [comment]
Thanks @danrosenthal. I'd love to build a new external product for the shopify ecosystem and my customers, but this license is a bit overprotective and overreaching, no? 

If I wanted to build a better version of the Shopify Digital Downloads App, let's call it SendOwl, then using this library would put me, as a partner, at risk of having my license revoked at the whims of Shopify at any moment. IANAL, but with this license, I feel like I have to make a pretty hefty investment in getting one.

Is there any way to escalate this on your end?

For ammo, here are some examples of successful opensource UI kits used to build ecosystem-ish apps, both can visually replicate the parent product:

1. https://atlaskit.atlassian.com/ Apache License
2. https://github.com/OfficeDev/office-ui-fabric-react MIT license

**Comment by markiiikram** [comment]
Hi @jho406, Thanks for sharing your concerns. We’re currently working to clarify what it means to be `visually distinct`. To give you a bit more context, these changes were added to promote recognition and trust. We’ve had Partners build experiences that look almost exactly like the Shopify admin which have caused confusion, eroded trust and had negative impact on everyone in the Shopify ecosystem. We added these guidelines to help our Partners create distinctive apps, not to police them. We admit that we’re in a bit of a transition stage, but our goal is to clarify our requirements, so it’s easier to build quality, sustainable apps. In the interim, if you’re open to sharing your designs I’d be happy to review and send you any feedback.

**Comment by jho406** [comment]
Thanks @markiiikram, could you also re-evaluate this clause: ` as determined by Shopify in its sole discretion`. I completely understand the why, but its effects are chilling for partners and developers who want to create tools that promote Polaris (e.g I want to build a Polaris/ Rails starter kit). Reminiscent of React's BSD + PATENT, but more chilling. 

Would that clause be more appropriate as a condition for your GraphQL or REST API usage? Or maybe a separate agreement as a precondition for being listed on the Marketplace?

**Comment by BPScott** [comment]
A tiny bit more context on the Atlassian front: Atlaskit packages are licensed individually and as per [the Atlaskit README](https://bitbucket.org/atlassian/atlaskit-mk-2#markdown-header-license) "packages containing styles, assets & icons are most likely licensed under the [Atlassian Design Guidelines license](https://atlassian.design/guidelines/handy/license)" which limits using their design to products related to the Atlassian ecosystem.
