### ISSUE TITLE
<Form /> submits when a child <Link /> gets clicked

### ISSUE THREAD

**Issue by kvendrik** [Shopify/polaris-react#510]
# Issue summary
`<Form />` submits when a child `<Link />` with an `onClick` callback gets clicked. Can be prevented by [calling `preventDefault` in the link's click handler](https://github.com/Shopify/merchant-feedback/pull/704/commits/ddb99a0f6f731909d62d9a5b94eedda22d086983).

## Reduced test case
[Example here](https://codesandbox.io/s/v3qk51m0v3).

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: v2.12.1
- Browser: Chrome v69.0
- Device: MacBook
- Operating System: OSX 10.13

**Comment by BPScott** [comment]
I believe this is fixed in v3 https://github.com/Shopify/polaris-react/commit/2d48d8e718f6e5b857f64da97d36dbda15fdeb91

**Comment by BPScott** [comment]
I've confirmed that this works with v3 in a codesandbox so going to close this.
