### ISSUE TITLE
SkeletonPage Header content is not laid out as expected

### ISSUE THREAD

**Issue by peterlazzarino** [Shopify/polaris-react#5241]
## Issue summary

When using `SkeletonPage`, the `primaryAction` and `secondaryActions` are not laid out in a way that's consistent with the `Page` component on a large screen.

## Expected behavior

The `SkeletonPage` component should approximate the layout and content that will be displayed once loading is complete.

#### `Page` Header with one `secondaryAction` and `primaryAction` on desktop

![Screen Shot 2022-03-08 at 2 56 17 PM](https://user-images.githubusercontent.com/2364849/157315002-e51ff2f9-a1db-4bd7-9565-04e3800b1627.png)

#### `SkeletonPage` Header with one `secondaryAction` and `primaryAction` on desktop

- `secondaryAction` displays on second row

![Screen Shot 2022-03-08 at 2 55 48 PM](https://user-images.githubusercontent.com/2364849/157315085-dbc99475-dd1c-4395-a785-152da668ccbe.png)

- images illustrating that the primaryAction doesn't fit within the parent and results in content that is not vertically aligned as it is with `Page`

![Screen Shot 2022-03-08 at 2 54 49 PM](https://user-images.githubusercontent.com/2364849/157315175-b8fa78a2-aded-4cfe-bcf6-42a3d0a6eb17.png)

![Screen Shot 2022-03-08 at 2 54 53 PM](https://user-images.githubusercontent.com/2364849/157315192-2a76febb-c8f3-4569-9ea8-914f5d5bdea4.png)

## Steps to reproduce the problem

See difference in code sandbox below.

## Reduced test case

[Skeleton Page](https://codesandbox.io/s/damp-smoke-e91xgx?file=/App.js
)
[Page](https://codesandbox.io/s/stoic-curie-8f9wx1?file=/App.js)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 8.2.2
- Browser: Chrome
- Device: M1 Mac
- Operating System: OSX

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by kyledurand** [comment]
The `secondaryActions` prop was deprecated and removed in v9: #4742 

For now I'd recommend removing the prop on your loading page since it's not very useful.

I'm going to leave this issue open and add to it. The title / primary action don't collapse elegantly:

![image](https://screenshot.click/08-47-a5huf-52bu9.png)
