### ISSUE TITLE
[Open development] Fix package scripts so they work with Windows

### ISSUE THREAD

**Issue by tmlayton** [Shopify/polaris-react#527]
After some testing in my Windows 10 VM, the scripts run but fail on certain parts like matching file patterns in the Jest config.

**Comment by AndrewMusgrave** [comment]
> looks like the scripts don’t entirely work on Windows (10 specifically), particularly around matching files like the jest config. Any insight here?

I use window's 10 a lot and often have issues with characters not being properly escaped. We use `sewing-kit` now for testing, could the issue be stemming from there?

**Comment by tmlayton** [comment]
I have not tried since we switch to `sewing-kit` so this might be resolved or partially resolved.
