### ISSUE TITLE
Percy false positives and test flakiness

### ISSUE THREAD

**Issue by tmlayton** [Shopify/polaris-react#528]
Experiencing Percy false positives and test flakiness? Post a comment with the test that incorrectly failed.

### Guidelines

1. Read though the existing flaky test comments before posting
1. Don’t post the same flaky test failure as someone else, instead upvote 👍 the other persons comment
1. One test per comment with: 
    - screenshot of the actual and expected 
    - a link to the build

**Comment by yourpalsonja** [comment]
@amrocha does https://github.com/Shopify/polaris-react/pull/1290 fix this? I don't have enough info to know for sure.

**Comment by amrocha** [comment]
It kinda does, this was more of an ongoing issue for tracking problems.

I haven't noticed any issues recently though, we might be good to close it!

**Comment by yourpalsonja** [comment]
I'm gonna close and if more issues come up, we can open a separate ticket for them, since this might not be super visible anymore.
