### ISSUE TITLE
Add jest-enzyme for cleaner tests

### ISSUE THREAD

**Issue by kvendrik** [Shopify/polaris-react#529]
https://github.com/Shopify/web/pull/7504/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R164

**Comment by yourpalsonja** [comment]
Hey all, just re-labelling this based on our new [labelling](https://docs.google.com/document/d/10Isykczvydj1YLvdxEYpeNEaiksGlKfeKp8VO4_gvw8/edit#) guidelines. 

If I got it wrong, please feel free to change it. If you're tackling this, you can move it into "In Progress" in the [backlog](https://github.com/orgs/Shopify/projects/485).

**Comment by danrosenthal** [comment]
Hey @kvendrik @BPScott should this still be open?

**Comment by BPScott** [comment]
If we're looking to move to [`@shopify/react-testing`](https://github.com/Shopify/quilt/blob/master/packages/react-testing) then it doesn't serve much value, so can be closed. As @kvendrik opened it I'd like him to confirm that he's happy to close it though.

**Comment by kvendrik** [comment]
@BPScott makes sense lets 📕 it!
