### ISSUE TITLE
[Grid] component based on CSS grid

### ISSUE THREAD

**Issue by solonaarmstrong** [Shopify/polaris-react#534]
# Grid

Proposal to adopt the new CSS grid in a component. 

`<Grid />` can be used for irregularly-sized elements and irregular layouts, as well as straightforward layouts.

Example:
The new home sidebar and other parts of the platform use CSS grid. Providing a `<Grid />` component would make future development easier to implement with CSS grid as things change over.

## Examples
...

## Best practices

The grid component should:

* Be used to align `n` number of items with specific or irregular column widths
* Be used for complex and unique arrangements
* Not be used for small-scale layout tasks already handled in stack

## Content guidelines

There are no content elements that are specific to grid.

## Related components

* Layout
* Stack
* FormLayout

**Comment by a-mooz** [comment]
I think this feature will really help design and implement elements quickly and provide a similar look and feel for all Polaris components, so 👍 from me!

If I can provide a suggestion:
If you look at, for example the Semantic framework, they break their grids up into 16 columns (I think Bootstrap is 14 columns?)  This makes doing layout super easy to visualize components for the UX team, and for devs to implement responsive designs.  You can add styles or property like `two wide` or `fourteen wide` to elements and the framwork knows how wide to make that element automagically.  It would be great to see something like that applied to the Polaris Grid system.  We could then, for example, create something like `<Link two wide> ... </Link>`.  You can even do 

One thing to keep in mind about a grid system like this is you need to declare a `<Grid>`, and then the area within that grid is divided up into 16 columns.  Each time you nest a grid, that subgrid gets sub-divided up into 16ths. More info here: https://semantic-ui.com/collections/grid.html

**Comment by tmlayton** [comment]
Like all feature requests, going to close this for now but please still keep upvoting (👍) the issue description if this is something you need.
