### ISSUE TITLE
[Modal] Height adjustments on small screen

### ISSUE THREAD

**Issue by cartogram** [Shopify/polaris-react#537]
Original issue ported from https://github.com/Shopify/polaris-react-deprecated/issues/2343

## Longer content should be full screen

|Currently|Should be|
|---|---|
|![image](https://user-images.githubusercontent.com/344839/46307974-42587280-c56d-11e8-9da4-45f355319655.png)|<img width="426" alt="screen shot 2018-10-01 at 11 31 40 am" src="https://user-images.githubusercontent.com/344839/46308163-cd396d00-c56d-11e8-9921-f964c7fe5fff.png">|

## Shorter content should only be as tall as it needs to be

|Currently|Should be|
|---|---|
|<img width="431" alt="screen shot 2018-10-01 at 11 32 01 am" src="https://user-images.githubusercontent.com/344839/46308211-ed692c00-c56d-11e8-9af3-47eb83b1c604.png">|<img width="433" alt="screen shot 2018-10-01 at 11 33 06 am" src="https://user-images.githubusercontent.com/344839/46308244-fbb74800-c56d-11e8-86f9-0fdc3fc89084.png">|

**Comment by tmlayton** [comment]
Looks like this has been fixed in v3.0.0. https://github.com/Shopify/web/pull/7611 bumps to the latest v3.0.0 release candidate so feel free to start working from there.
