### ISSUE TITLE
Make it possible to have a destructive primary footer on a Card

### ISSUE THREAD

**Issue by mehdi-loup** [Shopify/polaris-react#538]
# Enhancement request

The *Card component* does not currently support a destructive props for its primary footer action.

## Proposed solution

Replace the BaseAction interface with a DestructableAction interface

**Comment by yourpalsonja** [comment]
Hey @mehdi-loup,

This repo getting a makeover! We want to make it easier to find existing issues, remove duplicates, and increase community engagement. If you issue is closed, re-labelled, or moved, don’t panic–it may be a duplicate (check the comments), or there is a new label or repository that work better.

If you disagree with the changes or have any other thoughts on how we can make Polaris better, please let us know!

I'm moving this into the backlog now, while we work through triaging all the issues. :)

**Comment by gerwinbrunner** [comment]
Just looked at this issue and it seems to have been solved already.
https://codesandbox.io/s/jolly-roentgen-57iii

So I think this can be closed since it works :)

**Comment by danrosenthal** [comment]
This is now supported and can be closed
