### ISSUE TITLE
[ResourceList] Selecting all versus selecting my checkbox call back with different IDs

### ISSUE THREAD

**Issue by lemonmade** [Shopify/polaris-react#542]
# Issue summary

When using the "select all" part of the bulk action, the selection IDs are based on the IDs of the raw data. When using the individual checkboxes, the selection IDs are based on the ID of the resource list item.

## Expected behavior

It is always based on the IDs of the data.

## Reduced test case

```ts
const customers = [
  {id: 'gid://Shopify/Customer/1', displayName: 'Tim'},
  {id: 'gid://Shopify/Customer/2', displayName: 'Dan'},
]

class MyComponent extends React.Component {
  state = {selectedCustomers: []};

  render() {
    return (
      <ResourceList
        items={customers}
        selectedItems={this.state.selectedCustomers}
        bulkActions={[{content: 'Delete', onAction: () => {}}]}
        onSelectionChange={(selectedCustomers) => this.setState({selectedCustomers})}
        renderItem={(customer) => (
          <ResourceList.Item
            id={/* parseGid just gets the number portion */ `Customer${parseGid(customer.id)}`}
          >
            {customer.displayName}
          </ResourceList.Item>
        )}
      />
    );
  }
}
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: latest 2.x
- Browser:
- Device:
- Operating System:

**Comment by wshen001** [comment]
I have encountered the same issue! Here is another example that can reproduce the issue.
https://codesandbox.io/s/qk4r323mw6

I basically change the `id` to `eid` to the payload of each item. The bulk action will behave incorrectly when you perform `select all` action.

**Comment by s20lee** [comment]
I experienced similar issue and noticed that there is a prop in ResourceList called "idForItem".
If you specify this prop to select id of each item, selecting individually and selecting all will behave the same. 
For example:

`<ResourceList items={customers} idForItem={(customer)=>(customer.id)}`

and when you render item,

`renderItem={(customer, id) => 
(<ResourceList.Item id={id}> {customer.displayName} </ResourceList.Item>)}`
