### ISSUE TITLE
Popover doesn't open in Modal

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react#544]
# Issue summary

When a `Popover` is used inside of a `Modal`, the popover never activates in the "desktop" rendered version of the mobile. It works in the "mobile" version.

## Expected behavior

Interacting with the activator should cause the `Popover` content to show.

## Actual behavior

Interacting with the activator for the `Popover` does not trigger the popover content to show.

This does work when the modal is in its mobile rendering, as it tends to have enough space in its `Scrollable` container, but in the normal desktop rendering, the modal's `Scrollable` seems to be triggering the scrollout on the `Popover`.

![Image of issue](https://i.imgur.com/iah6a4M.gif)

## Steps to reproduce the problem

1. Place a `Popover` component inside of a `Modal`
1. Open the `Modal`
1. Interact with the `Popover` activator.

## Reduced test case

https://codesandbox.io/s/p7km9yv2vx . You may need to expand the browser viewport so that the `Modal` renders in the "desktop" version (centered in the middle of the screen). The mobile version tends to have enough space, and the popover works there.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.12.1
- Browser: Chrome 70.0.3538.77 (64 bit)
- Device: MacBook Pro
- Operating System: macOS Mojave 10.14.1

**Comment by mbaumbach** [comment]
This may be a more generic issue of "Popover doesn't open inside of a small Scrollable container," but this was an easy use case to reproduce and provide a reduced test case. We see this in some scrollable containers where the popover may be near the bottom of it.

I figured that might be useful to add, as we don't typically throw popovers into Modals like this specific test case. :)

I also suspect this could be an issue with v3's `Autocomplete` component too, but I haven't confirmed that yet. That's a component I might expect to be in a Modal more consistently than a basic Popover.

**Comment by rmaspoch** [comment]
We have a scenario where we use a Popover containing a calendar inside a modal and we experience the same issue.

**Comment by tmlayton** [comment]
@mbaumbach thanks for the issue 😄 

I dug in a bit more and it seems specific to when there is not enough space for the popover to render:

![not enough space](https://user-images.githubusercontent.com/344839/48030167-0d5bb480-e105-11e8-88f1-6b57aebc838f.gif)

**Comment by mbaumbach** [comment]
Confirmed this is also an issue with the `Autocomplete` component inside a `Modal`, which was expected since it uses a `Popover`.
