### ISSUE TITLE
Failed to compile ./node_modules/@shopify/polaris/styles.css

### ISSUE THREAD

**Issue by charanpahariapp** [Shopify/polaris-react#545]
./node_modules/@shopify/polaris/styles.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/@shopify/polaris/styles.css)
Unclosed bracket (3864:37)

  3862 |     background-color:#c4cdd5;
  3863 |     background-color:var(--progress-upper, #c4cdd5);
> 3864 |     background-image:linear-gradient(to right, transparent 0%, transparent 0%, transparent 100%, transparent 100% transparent;
       |                                     ^
  3865 |     background-image:linear-gradient(to right, var(--progress-lower, transparent) 0%, var(--progress-lower, transparent) var(--Polaris-RangeSlider-progress, 0%), var(--progress-upper, transparent) var(--Polaris-RangeSlider-progress, 100%), var(--progress-upper, transparent) 100%);
  3866 |     border:none;
  3867 |     border-radius:0.4rem; }

**Comment by mbaumbach** [comment]
I believe this is the same as #441. Looks like it may be fixed in 3.0 (commit 9abe51296353d97ff6d563de24a96a0737863c3b).

**Comment by BPScott** [comment]
Yep, thanks @mbaumbach.

@charanpahariapp please see https://github.com/Shopify/polaris-react/issues/441#issuecomment-429490870 for mitigation steps until v3.0 is released.
