### ISSUE TITLE
Navigation with user menu styles are off

### ISSUE THREAD

**Issue by HYPD** [Shopify/polaris-react#548]
# Issue summary

Text styles (size, colour) and spacing is off inside our mobile user menu.

## Expected behavior

We should use mobile text styles, colours, sizes, etc. And spacing can also be corrected, like lack of padding above the `Perform action` button in the centre. 

## Actual behavior

![s3yqh2x](https://user-images.githubusercontent.com/970304/48030408-f5912a00-e11e-11e8-8010-6f381acba3ce.png)

## Steps to reproduce the problem

1. https://polaris-styleguide-pr-2346.herokuapp.com/components/navigation/navigation#navigation
1. Select `Navigation with user menu` from 'Examples'
1. Shrink the viewport so it's showing you the mobile version

**Comment by danrosenthal** [comment]
Since the `UserMenu` is no longer part of `Navigation`, this should be closed
