### ISSUE TITLE
forceRedirect dont work

### ISSUE THREAD

**Issue by improck** [Shopify/polaris-react#549]
# Issue summary

forceRedirect don't work.
Select forceRedirect true, but app dont redirect to shopify admin panel

## Actual behavior

```
ReactDOM.render(
    <AppProvider
        apiKey={SP_API_TOKEN}
        shopOrigin={SP_DOMAIN}
        forceRedirect={true}
    >
        <ManagePlatforms />
    </AppProvider>
    , document.getElementById('root'));
```

## Specifications
React component
Polaris v. 2.12.1
Browser Chrome
OC: Windows

**Comment by mbaumbach** [comment]
This works for us in production in several apps. Perhaps you need specify the app as "embedded" in the Partner Portal app settings under **Extensions** and **Embedded app**?

**Comment by tmlayton** [comment]
@improck for directions on enabling an embedded app, take a look at https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk/getting-started#enabling-the-embedded-app-sdk.

Going to close this issue for now, feel free to reopen if this does not resolve the issue.

And @mbaumbach thanks for your help!

**Comment by improck** [comment]
Thanks 👍 . In the 3 version, the problem was solved by itself, everything is working.
