### ISSUE TITLE
Polaris card implements footer action buttons in the reverse order compared to similar components

### ISSUE THREAD

**Issue by sivakumar-kailasam** [Shopify/polaris-react#551]
# Issue summary

Whenever any of the polaris components implement a [button group with a primary & secondary action](https://polaris.shopify.com/components/actions/button-group#navigation), they always have the secondary action first followed by the primary action but in case of the card component it has been implemented the other way around

## Expected behavior

The `secondaryFooterAction` should be rendered first followed by the `primaryFooterAction`

## Actual behavior

The `primaryFooterAction`is rendered before the `secondaryFooterAction`.

## Steps to reproduce the problem

Implement a card with footer actions as shown in https://codesandbox.io/s/yvwy63yll9?module=App.js

## Specifications

- Are you using the React components? (Y/N):Y
- Polaris version number: latest
- Browser:All
- Device: N/A
- Operating System:N/A

I'd be happy to raise a PR for this if this is indeed a bug.

**Comment by dpersing** [comment]
Hi @sivakumar-kailasam! Agreed that this definitely looks like a bug. A PR would be welcome! 🎉
