### ISSUE TITLE
[Layout foundations] Audit breakpoints

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react#5514]
Explore current breakpoint usage, map out all use cases, and try to make sense of them.

**Comment by aaronccasanova** [comment]
Before experimenting with new breakpoint tokens I took some time to validate our usage of `em` units for `@media` conditions and wanted to share my findings, resources, and demos for future reference.

There are a few good articles discussing the tradeoffs of using `px`, `em`, and `rem` units in media query conditions, however, I found the most value in the following two:
- [PX, EM or REM Media Queries?](https://zellwk.com/blog/media-query-units/) - Deep dive of the difference in behavior across browsers
- [To em or not to em? That is the media query question.](https://medium.com/zoosk-engineering/to-em-or-not-to-em-that-is-the-media-query-question-22f4a65e9747) - Demonstrates what problem `em` media conditions solve

We currently think about our breakpoints in `px`s and [leverage a SCSS to transform them to `em`s](https://github.com/Shopify/polaris/blob/414583de7109fca634e29fc67662797bc99df7d4/polaris-react/src/styles/shared/_breakpoints.scss#L1-L11) for `@media` conditions. But why? As mentioned in the above articles, using `em`s for `@media` conditions has the most consistent cross browser behavior. I created two demos validating the browser inconsistencies as well as the effect it has on the Shopify admin.

The first and most relevant demo shows the issue with using `px` over `em` on the Shopify admin in Safari. The scenario is the user has zoomed in on the admin (with `cmd or ctrl +`) to the point where content shifted to use the mobile layout (even though we are still on a large screen). Because we are using `em`s, the Shopify admin looks as expected e.g. increased text size and using the mobile layout so all content is clearly visible. After running the script to convert all `em` `@media` conditions to `px`s, the text is still enlarged and content has shifted back to the desktop layout. This is problematic as content has increased in size and yet is crammed into it's original layout.

https://user-images.githubusercontent.com/32409546/163270624-af6138f1-a252-420f-ac4b-38d5b2209c26.mov

<details>
  <summary>Feel free to give this a try for yourself! Open the Shopify admin in Safari, open the devtools, zoom in until the content shifts to the mobile layout, and paste/execute the following script:</summary>
  
```js
const updatedMediaQueries = Array.from(document.styleSheets)
    // Filter styleSheets with cssRules and ignore CORS errors
    .filter(sheet => {
        try {
         return sheet.cssRules   
        } catch {
            return false
        }
    })
    // Create a list with all page rules
    .flatMap(sheet => Array.from(sheet.cssRules))
    // Filter only @media rules
    .filter(rule => rule.media)
    .map(mediaRule => {
      let hasEmMediaQuery = false
      const mediaText = mediaRule.media.mediaText
        
      // Convert em to px
      const pxMediaText = mediaText.replace(/([\d.]+)em/g, (match, unit) => {
        hasEmMediaQuery = true
        return `${unit * 16}px`
      })

      if (hasEmMediaQuery) {
        // Update @media condition to px
        mediaRule.media.mediaText = pxMediaText
        return `Updated ${mediaText} to ${pxMediaText}`
      }
    })
    .filter(Boolean)

// Dedupe
console.log(Array.from(new Set(updatedMediaQueries)).join('\n'))
```
</details>

<details>
  <summary>Additionally, here is a re-creation of the demo from the above linked <a href="https://zellwk.com/blog/media-query-units/">PX, EM or REM Media Queries?</a> article. Use this test to validate the difference in behavior across browsers. Simply copy/paste into a blank `index.html` file, right click and open in Safari or drag the file on to the Safari icon, zoom in with `cmd or ctrl +`, start resizing the window, and notice the opacity triggering at different times</summary>

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      * {
        margin: 0;
      }
      div {
        height: 33.33vh;
      }

      html {
        font-size: 100%;
      }

      .pixel {
        background: red;
      }

      @media (min-width: 600px) {
        .pixel {
          opacity: 0.5;
        }
      }

      .em {
        background: green;
      }
      /* 600 ÷ 16 = 25 */
      @media (min-width: 37.5em) {
        .em {
          opacity: 0.5;
        }
      }

      .rem {
        background: blue;
      }
      /* 600 ÷ 16 = 25 */
      @media (min-width: 37.5rem) {
        .rem {
          opacity: 0.5;
        }
      }
    </style>
  </head>
  <body>
    <div class="pixel">Pixel</div>
    <div class="em">EM</div>
    <div class="rem">REM</div>
  </body>
</html>
```
</details>

All that said, I'm convinced we should continue to use `em`s for `@media` conditions. I think some good next steps would be to explore how to expose tokens/mixins with these considerations and ensure we provide clear documentation/guidance wherever we land.

**Comment by aveline** [comment]
There are also some breakpoints that live here https://github.com/Shopify/polaris/blob/main/polaris-react/src/utilities/breakpoints.ts

**Comment by lgriffee** [comment]
I set up [a spreadsheet](https://docs.google.com/spreadsheets/d/1D2Y3y2_TpWU6T6r_H51n1-50nAehYyW7weX1_MKbkDw/edit?usp=sharing) to audit breakpoints related Sass Mixins, Sass Variables, Functions, and Components. I'll also create a simplified version below so we have a copy in GitHub. 

Based on this spreadsheet I've identified several mixins and variables that could possibly be deleted as well as several hard coded Sass variables in components that can be replaced with our new breakpoint tokens. I'll create a PR tomorrow to try replacing the hardcoded values first. 

<hr>

### Breakpoint Audit 

#### Sass Mixins 
| Mixin Name                                  | Uses in Polaris       | Uses in Web             | File                   |
| ------------------------------------------- | --------------------- | ----------------------- | ---------------------- |
| page-content-breakpoint-before()            | 3 results / 1 file    | 2 results / 2 files     | \_breakpoints.scss     |
| page-content-breakpoint-after()             | 6 results / 2 files   | 3 results / 1 file      | \_breakpoints.scss     |
| breakpoint-after()                          | 66 results / 20 files | 456 results / 181 files | \_breakpoints.scss     |
| breakpoint-before()                         | 18 results / 10 files | 300 results / 163 files | \_breakpoints.scss     |
| frame-with-nav-when-not-max-width()         | 0                     | 0                       | \_breakpoints.scss     |
| page-when-not-max-width()                   | 0                     | 0                       | \_breakpoints.scss     |
| page-content-when-layout-stacked()          | 0                     | 0                       | \_breakpoints.scss     |
| page-content-when-layout-not-stacked()      | 0                     | 0                       | \_breakpoints.scss     |
| page-content-when-partially-condensed()     | 0                     | 0                       | \_breakpoints.scss     |
| page-content-when-not-partially-condensed() | 0                     | 0                       | \_breakpoints.scss     |
| page-content-when-fully-condensed()         | 0                     | 0                       | \_breakpoints.scss     |
| page-content-when-not-fully-condensed()     | 0                     | 0                       | \_breakpoints.scss     |
| frame-when-nav-displayed()                  | 0                     | 0                       | \_breakpoints.scss     |
| frame-when-nav-hidden()                     | 0                     | 0                       | \_breakpoints.scss     |
| after-topbar-sheet                          | 0                     | 3 results / 1 file      | shared / \_layout.scss |

_Note: Wasn't related to breakpoints but did find mixin logic for page layout in `_page.scss` and `shared/_layout.scss` while doing this research_ 

#### Private/Public Legacy Sass Varaibles

| Variable Name                      | Variable Value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | Uses in Polaris     | Uses in Web           | File                       |
| ---------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------- | --------------------- | -------------------------- |
| $page-max-width                    | layout-width(primary, max) + layout-width(secondary, max) + layout-width(inner-spacing)<br><br>662px + 320px + 16px<br><br>998px                                                                                                                                                                                                                                                                                                                                                                                                    | 6 results / 3 files | 15 results / 11 files | \_breakpoints.scss         |
| $frame-with-nav-max-width          | layout-width(nav) + $page-max-width<br><br>240px + 998px<br><br>1238px                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 1 result / 1 file   | 0                     | \_breakpoints.scss         |
| $stacked-content                   | breakpoint(layout-width(primary, min) + layout-width(secondary, min) + layout-width(inner-spacing)<br><br>480px + 240px + 16px<br><br>breakpoint(736px)                                                                                                                                                                                                                                                                                                                                                                             | 2 results / 1 file  | 0                     | \_breakpoints.scss         |
| $not-condensed-content             | breakpoint(layout-width(page-content, not-condensed))<br><br>breakpoint (680px)                                                                                                                                                                                                                                                                                                                                                                                                                                             | 6 results / 2 files | 2 results / 1 file    | \_breakpoints.scss         |
| $partially-condensed-content       | breakpoint(layout-width(page-content, partially-condensed))<br><br>breakpoint(450px)                                                                                                                                                                                                                                                                                                                                                                                                                                        | 5 results / 1 file  | 24 results / 20 files | \_breakpoints.scss         |
| $not-condensed-outer-spacing       | breakpoint(2 \* layout-width(outer-spacing, max))<br><br>breakpoint(64px)                                                                                                                                                                                                                                                                                                                                                                                                                                                   | 7 results / 1 file  | 0                     | \_breakpoints.scss         |
| $partially-condensed-outer-spacing | breakpoint(2 \* layout-width(outer-spacing, min))<br><br>breakpoint(40px)                                                                                                                                                                                                                                                                                                                                                                                                                                                   | 7 results / 1 file  | 0                     | \_breakpoints.scss         |
| $not-condensed-min-page            | $not-condensed-content + $not-condensed-outer-spacing<br>breakpoint (680px) breakpoint(64px)<br><br>breakpoint(744px)                                                                                                                                                                                                                                                                                                                                                                                                       | 0                   | 0                     | \_breakpoints.scss         |
| $partially-condensed-min-page      | $partially-condensed-content + $partially-condensed-outer-spacing<br>breakpoint(450px) breakpoint(40px)<br><br>breakpoint(490px)                                                                                                                                                                                                                                                                                                                                                                                            | 0                   | 36 results / 20 files | \_breakpoints.scss         |
| $nav-size                          | breakpoint(layout-width(nav))<br><br>breakpoint(240px)                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | 6 results / 1 file  | 0                     | \_breakpoints.scss         |
| $nav-min-window                    | breakpoint(layout-width(page-with-nav))<br><br>breakpoint(769px)                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 9 results / 1 file  | 0                     | \_breakpoints.scss         |
| $navigation-width                  | 240px !default                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | 1 result / 1 file   | 0                     | foundation / \_layout.scss |
| $dangerous-magic-space-4           | 16px                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | 1 result / 1 file   | 0                     | foundation / \_layout.scss |
| $dangerous-magic-space-5           | 20px                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | 1 result / 1 file   | 0                     | foundation / \_layout.scss |
| $dangerous-magic-space-8           | 32px                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | 2 results / 1 file  | 0                     | foundation / \_layout.scss |
| $layout-width-data                 | primary: (<br>min: 480px,<br>max: 662px,<br>),<br>secondary: (<br>min: 240px,<br>max: 320px,<br>),<br>one-half-width: (<br>base: 450px,<br>),<br>one-third-width: (<br>base: 240px,<br>),<br>nav: (<br>base: $navigation-width,<br>),<br>page-with-nav: (<br>base: 769px,<br>),<br>page-content: (<br>not-condensed: 680px,<br>partially-condensed: 450px,<br>),<br>inner-spacing: (<br>base: $dangerous-magic-space-4,<br>),<br>outer-spacing: (<br>min: $dangerous-magic-space-5,<br>max: $dangerous-magic-space-8,<br>), | 1 result / 1 file   | 0                     | foundation / \_layout.scss |
| $dismiss-icon-size                 | 32px                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | 1 result / 1 file   | 0                     | foundation / \_layout.scss |

#### Component Sass Variables
| Variable Name                       | Variable Value    | File                 | Repo    |
| ----------------------------------- | ----------------- | -------------------- | ------- |
| BREAKPOINT                          | 768               | GridOverlay.tsx      | Polaris |
| $breakpoint                         | 768px             | SecondaryAction.scss | Polaris |
| $breakpoint                         | 768px             | DataTable.scss       | Polaris |
| $breakpoint                         | 550px             | DescriptionList.scss | Polaris |
| $breakpoint                         | 640px             | Toast.scss           | Polaris |
| $breakpoint-small                   | 458px             | IndexTable.scss      | Polaris |
| $portrait-breakpoint                | 804px             | MediaCard.scss       | Polaris |
| $button-style-breakpoint            | 768px             | Header.scss          | Polaris |
| $breakpoint-small                   | 458px             | ResourceItem.scss    | Polaris |
| $breakpoint-small                   | 458px             | \_variables.scss     | Polaris |
| \--                                 | breakpoint(600px) | ResourceList.scss    | Polaris |
| $breakpoint                         | 490px             | Tag.scss             | Polaris |
| $page-left-alignment-breakpoint-max | 1238px            | Header.scss          | Polaris |
| $context-control-expand-after       | 1400px            | Header.scss          | Polaris |
| $mobile-layout                      | 468px             | Header.scss          | Polaris |
| $medium-layout                      | 860px             | Header.scss          | Polaris |
| $desktop-layout                     | 1080px            | Header.scss          | Polaris |

#### Functions

| Function Name                                                        | Function Value                                                                                             | Uses in Polaris      | Uses in Web           | File                       |
| -------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------- | -------------------- | --------------------- | -------------------------- |
| navigationBarCollapsed()                                             | 768px                                                                                                      | 3 results / 1 file   | 0                     | breakpoints.ts             |
| stackedContent()                                                     | 1043px                                                                                                     | 1 result / 1 file    | 0                     | breakpoints.ts             |
| breakpoint()                                                         | \[num\]em                                                                                                  | 11 results / 2 files | 2 results / 1 file    | \_breakpoints.scss         |
| layout-width(primary, min)                                           | 480px                                                                                                      | 2 results / 2 files  | 4 results / 4 files   | foundation / \_layout.scss |
| layout-width(primary, max)                                           | 662px                                                                                                      | 5 results / 5 files  | 8 results / 5 files   | foundation / \_layout.scss |
| layout-width(secondary, min)                                         | 240px                                                                                                      | 2 results / 2 files  | 1 result / 1 file     | foundation / \_layout.scss |
| layout-width(secondary, max)                                         | 320px                                                                                                      | 3 results / 3 files  | 3 results / 3 files   | foundation / \_layout.scss |
| layout-width(one-half-width)<br>layout-width(one-half-width, base)   | 450px                                                                                                      | 1 result / 1 file    | 1 result / 1 file     | foundation / \_layout.scss |
| layout-width(one-third-width)<br>layout-width(one-third-width, base) | 240px                                                                                                      | 1 result / 1 file    | 1 result / 1 file     | foundation / \_layout.scss |
| layout-width(nav)<br>layout-width(nav, base)                         | $navigation-width<br><br>240px !default                                                                    | 16 results / 5 files | 10 results / 9 files  | foundation / \_layout.scss |
| layout-width(page-with-nav)<br>layout-width(page-with-nav, base)     | 769px                                                                                                      | 13 results / 6 files | 45 results / 20 files | foundation / \_layout.scss |
| layout-width(page-content, not-condensed)                            | 680px                                                                                                      | 1 result / 1 file    | 1 result / 1 file     | foundation / \_layout.scss |
| layout-width(page-content, partially-condensed)                      | 450px                                                                                                      | 1 result / 1 file    | 0                     | foundation / \_layout.scss |
| layout-width(inner-spacing)<br>layout-width(inner-spacing, base)     | $dangerous-magic-space-4<br><br>16px                                                                       | 3 results / 2 files  | 3 results / 3 files   | foundation / \_layout.scss |
| layout-width(outer-spacing, min)                                     | $dangerous-magic-space-5<br><br>20px                                                                       | 1 result / 1 file    | 0                     | foundation / \_layout.scss |
| layout-width(outer-spacing, max)                                     | $dangerous-magic-space-8<br><br>32px                                                                       | 1 result / 1 file    | 0                     | foundation / \_layout.scss |
| top-bar-height()                                                     | 56px                                                                                                       | 14 results / 7 files | 17 results / 14 files | foundation / \_layout.scss |
| mobile-nav-width()                                                   | calc(100vw - (#{$dismiss-icon-size} + #{$dangerous-magic-space-8}))<br>32px 32px<br><br>calc(100vw - 64px) | 1 result / 1 file    | 0                     | foundation / \_layout.scss |
| nav-min-window-corrected()                                           | 769px                                                                                                      | 19 results / 5 files | 50 results / 22 files | foundation / \_layout.scss |

#### Components 

| Component Name     | Uses in Polaris | Uses in Web | File                   |
| ------------------ | --------------- | ----------- | ---------------------- |
| MediaQueryProvider | 3               | 0           | MediaQueryProvider.tsx |

**Comment by aaronccasanova** [comment]
Breakpoint frequencies in `Web`:
```json
{
    "490px": 1487,
    "512px": 39,
    "400px": 35,
    "489px": 237,
    "360px": 29,
    "60px": 1,
    "450px": 72,
    "458px": 624,
    "457.84px": 28,
    "500px": 35,
    "480px": 9,
    "457px": 2,
    "380px": 5,
    "550px": 45,
    "551px": 18,
    "550.16px": 4,
    "375px": 5,
    "540px": 10,
    "370px": 7,
    "385px": 3,
    "359px": 1,
    "130px": 8,
    "8px": 3,
    "390px": 1,
    "388px": 1,
    "501px": 5,
    "420px": 3,
    "510px": 1,
    "468px": 12,
    "320px": 1,
    "444px": 2,
    "590px": 115,
    "730px": 444,
    "754px": 234,
    "720px": 405,
    "744px": 935,
    "640px": 739,
    "580px": 4,
    "700px": 14,
    "600px": 66,
    "567px": 2,
    "666px": 2,
    "575px": 2,
    "680px": 76,
    "743px": 43,
    "610px": 4,
    "568px": 6,
    "560px": 3,
    "620px": 3,
    "662px": 6,
    "696px": 2,
    "695px": 6,
    "678px": 2,
    "767px": 13,
    "576px": 3,
    "760px": 3,
    "621px": 6,
    "564px": 5,
    "650px": 3,
    "750px": 4,
    "639px": 3,
    "660px": 4,
    "570px": 1,
    "666.84px": 7,
    "667px": 10,
    "769px": 2018,
    "830px": 57,
    "768px": 218,
    "984px": 670,
    "768.84px": 71,
    "1000px": 15,
    "850px": 3,
    "940px": 6,
    "800px": 101,
    "804px": 38,
    "958px": 2,
    "768.16px": 1,
    "970px": 2,
    "986px": 8,
    "985px": 54,
    "998px": 10,
    "992px": 2,
    "802px": 16,
    "880px": 45,
    "996px": 7,
    "950px": 7,
    "980px": 8,
    "900px": 46,
    "770px": 2,
    "860px": 7,
    "935px": 4,
    "887px": 1,
    "861px": 6,
    "990px": 36,
    "828px": 1,
    "905px": 2,
    "901px": 1,
    "875px": 2,
    "960px": 1,
    "890px": 19,
    "920px": 4,
    "1260px": 2,
    "1400px": 12,
    "1210px": 4,
    "1238px": 19,
    "1175px": 54,
    "1614px": 1,
    "1040px": 77,
    "1200px": 42,
    "1440px": 11,
    "1024px": 36,
    "1159px": 8,
    "1160px": 17,
    "1399px": 14,
    "1750px": 1,
    "1044.16px": 9,
    "1044px": 24,
    "1045px": 12,
    "1300px": 3,
    "1060px": 3,
    "1240px": 13,
    "1043px": 14,
    "1025px": 9,
    "1439px": 1,
    "1100px": 14,
    "1460px": 1,
    "1280px": 1,
    "1236px": 1,
    "1320px": 3,
    "1020px": 5,
    "1180px": 11,
    "1164px": 4,
    "1360px": 3,
    "1080px": 65,
    "1090px": 5,
    "1239px": 1,
    "1404px": 3
}
```

Breakpoint frequencies in `Polaris`:
```json
{
    "458px": 23,
    "490px": 57,
    "457.84px": 1,
    "444px": 1,
    "468px": 3,
    "640px": 49,
    "730px": 25,
    "590px": 6,
    "744px": 30,
    "754px": 1,
    "720px": 6,
    "600px": 1,
    "680px": 1,
    "660px": 1,
    "769px": 88,
    "830px": 3,
    "768px": 4,
    "984px": 18,
    "800px": 5,
    "804px": 3,
    "768.84px": 4,
    "860px": 1,
    "1040px": 3,
    "1400px": 1,
    "1238px": 1,
    "1044px": 1,
    "1080px": 1
}
```

**Comment by lgriffee** [comment]
[New breakpoint audit data](https://docs.google.com/spreadsheets/d/144Oa5sGZyVJXAcWyPNqfHX_sNcdGgGdNKDfLKRtLBD0/edit#gid=863034351)
