### ISSUE TITLE
[AutoComplete] Enter key not confirming selection

### ISSUE THREAD

**Issue by maxariss** [Shopify/polaris-react#559]
# Issue summary
When tabbing through an `<Autocomplete />`'s option list, hitting the `enter` key doesn't confirm a selection and update the field.

## Expected behavior
Hitting `enter` on your keyboard should confirm your selection and update the field.

## Actual behavior
Hitting `enter` just closes the `<Popover />`

I’ve narrowed it down to `this.state.popoverActive` being `false` when it should be `true` on line:

https://github.com/Shopify/polaris-react/blob/master/src/components/Autocomplete/components/ComboBox/ComboBox.tsx#L335

## Steps to reproduce the problem
- Checkout https://github.com/Shopify/web/pull/8161 in `Shopify/web`
- Open a smart collection
- Change a condition to `product type` 
- Begin tabbing through types, and press `enter` on your keyboard

## Specifications
- Are you using the React components?: ✅
- Polaris version number: `3.0.0-beta.14`
- Browser: Chrome
- Device: MBP
- Operating System: _Not Mojave_

**Comment by solonaarmstrong** [comment]
Thanks @maxariss I'll have a look.

**Comment by solonaarmstrong** [comment]
I'm just looking at it right now, actually. I had another PR open that affected arrow keys and I wanted to make sure that wasn't the problem. I'm trying to reproduce it.

**Comment by solonaarmstrong** [comment]
I was able to see the bug, but I can't reproduce it in the playground, using nearly identical code.

![autocomplete-enter2](https://user-images.githubusercontent.com/6239480/48417198-00dbeb00-e707-11e8-8688-2341ccd4ccec.gif)

**Comment by maxariss** [comment]
@solonaarmstrong Interesting ! Can you identify any issue with the code used in `web` ? Or do you suspect there's a common discrepancy allowing the popover to work in the playground, but preventing it from working in web as expected ?

**Comment by solonaarmstrong** [comment]
@AndrewMusgrave is having a look. I'm caught up in a few other things.

**Comment by AndrewMusgrave** [comment]
@maxariss as Solona mentioned Dan asked me to look into this tonight. I'm not quite sure this is an `AutoComplete` issue, it's not that the auto complete isn't getting updated. When you press enter `TextField` is your focus, your form handler `handleSave` function is being called

**Comment by AndrewMusgrave** [comment]
As a consumer would you expect the form not to submit when you press enter with focus on the text field, while the combobox is open?

**Comment by maxariss** [comment]
@AndrewMusgrave is correct ! the binding for the form was overriding the binding in the component.
