### ISSUE TITLE
Parity between code examples and UI kit

### ISSUE THREAD

**Issue by tmlayton** [Shopify/polaris-react#561]
Originally brought up in https://github.com/Shopify/polaris-react/pull/558 in regards to adding a card example to the UI kit. I think it is fair if the scope of this issue is not just limited to `<Card />`.

<img width="778" alt="screen shot 2018-11-07 at 10 28 40 am" src="https://user-images.githubusercontent.com/344839/48152142-ef629100-e277-11e8-9321-c83211d0288c.png">

**Comment by tmlayton** [comment]
I don’t think the code examples need to be exhaustive, but at least providing the most common configurations is very helpful for those looking to grab code snippets and get started quickly.

That being said, I would like to have some reasonable thinking as to what examples are provided in the UI kit versus what examples are provided as code. But maybe there is too much variation from component to component and it needs to be a case by case decision.

My initial reaction is to have parity between the UI kit and code examples, but in some cases we added code examples in an effort to improve visual regression testing coverage. And I suspect this would make the UI kit very noisy.

**Comment by HYPD** [comment]
> ...in some cases we added code examples in an effort to improve visual regression testing coverage.
@tmlayton could you explain this a little more?

I haven't looked into this too much, but I think the UI kit's component page might be better used reflecting which examples are available on the style guide. 

This would allow people internally and externally to use the style guide to choose, and learn about components. Then being able to use that component in mocks through the ui kit.

**Comment by tmlayton** [comment]
> could you explain this a little more?

@HYPD and I chatted in Slack. tl;dr we want to keep many examples as code examples in the style guide at least for the purpose of visual regression testing.
