### ISSUE TITLE
[Autocomplete][v1] Sets popover state in update

### ISSUE THREAD

**Issue by tmlayton** [Shopify/polaris-react#563]
We should not set state in the update lifecycle because it can result in infinite loops. This is why we lint for it.

https://github.com/Shopify/polaris-react/blob/2da05f02f2b1b8c140dc87dbb15d3630170c345e/src/components/Autocomplete/components/ComboBox/ComboBox.tsx#L183-L184

The popover active prop should not be explicitly set by a state, rather only respond when the state and props meet certain conditions.

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.

**Comment by tmlayton** [comment]
Still an issue
