### ISSUE TITLE
Top bar with all of its elements divider color

### ISSUE THREAD

**Issue by HYPD** [Shopify/polaris-react#567]
# Top bar with all of its elements 

Divider used in the current `top bar with all of its elements` is pretty dark. The colors of this top bar will change based on your chosen base color. We should do the same with this divider, otherwise lighter top bars may have a divider that is far too dark.;

Currently the divider is set to `rgba(color('black'), 0.42)`.

@danrosenthal

**Comment by danrosenthal** [comment]
Here, let me fix that for you

**Comment by danrosenthal** [comment]
The `TopBar` no longer has a divider, so this can be closed
