### ISSUE TITLE
Move `app-bridge` to peer dependency

### ISSUE THREAD

**Issue by michelleyschen** [Shopify/polaris-react#569]
# Feature request summary

From what I understood about peer dependency,
I think we should move `app-bridge` from a dependency to peer dependency.

## Rationale
This will allow the consumer to decrease their bundle size if the consuming app does not need `app-bridge` feature.

I understand that polaris want to offer a easy way to setup and not worry about having to install another thing. But at the same time I also feel like having the consumer install `app-bridge` can offer up some better context of how some of the magic happen under the hood. Expose the consumer to the `app-bridge` documentation early. Which will be specially important since polaris are actively trying to remove some of the functionality such as `this.context.easdk.pushState()` and `this.context.easdk.redirect()` in favor for the consumer to implement app bridge action themselves.

**Comment by hughevans** [comment]
This would be great thanks. ~140KB presently.

<img width="817" alt="screen shot 2018-12-22 at 5 35 35 pm" src="https://user-images.githubusercontent.com/2580/50371494-084cb900-0610-11e9-9dce-126450d14152.png">

**Comment by michelleyschen** [comment]
cc @hughevans 

our workaround for now is to manually remove it using something like https://github.com/webpack-contrib/null-loader

```
module: {
    rules: [
      {
        test: /\.js$/,
        include: /@shopify\/app-bridge/,
        issuer: {
          include: /@shopify\/polaris/,
        },
        use: 'null-loader'
      }
    ]
  }
```

**Comment by BPScott** [comment]
Ping @AndrewMusgrave, this might be a candidate for v4. Though some input from the holidaying @tmlayton would be good to confirm if this is something we want to do as an interim measure before the full removal of app-bridge in v5

**Comment by tmlayton** [comment]
App bridge is not a peer dependency, though, so it should stay as-is. Agreed the extra bundle size is pretty bad if you are not using app bridge and is part of the reason we are removing app bridge entirely in v5: https://github.com/Shopify/polaris-react/issues/1767

For more info as to why, see https://github.com/Shopify/polaris-react/issues/814.
