### ISSUE TITLE
ResourcePicker Embeded component

### ISSUE THREAD

**Issue by mrdja026** [Shopify/polaris-react#574]
# Issue summary

Hi guys, i am currently developing a shopify app and using Polairs components to do so.
Until today when i was using Embeded ResourcePicker was returning all of the images that were associated with the product.
Now it returns first five? I am wondering is this expected behavior?  Sorry if my question was out of order.

## Specifications

- Are you using the React components? (Y/N): YES
- Polaris version number:  @shopify/polaris": "2.12.1
- Browser: Google Chrome v70.0.3538.77
- Device: PC
- Operating System: Windows 10 PRO

**Comment by markiiikram** [comment]
Hi @mrdja026, Can you provide a screenshot or a screen recording? Thanks.

**Comment by mrdja026** [comment]
Hi, best i can do is this.
This is a screen shot of the onSelection callback from around 16h GTM+1 (first picture)
notice that images[] property has 18 items 
![image](https://user-images.githubusercontent.com/15103310/48277811-078b0980-e44c-11e8-8445-a2630153f409.png)

Picture below is a screen shot from now
![image](https://user-images.githubusercontent.com/15103310/48277847-21c4e780-e44c-11e8-8517-4ee2d7a201d0.png)

Tnx for the quick reply :)

**Comment by markiiikram** [comment]
Hey @mrdja026, The new GraphQL API now implements a limit on product images in the resource picker to the first 5. If you require all the images you'll need to write a query separate from the resource picker.

**Comment by mrdja026** [comment]
@markiiikram tnx, can you please provide some directions on documentations about mention queries, since https://polaris.shopify.com/components/embedded/embedded-resource-picker returns a 404, or i am missing something.

**Comment by markiiikram** [comment]
thanks @mrdja026! i've created an issue to fix the 404 https://github.com/Shopify/polaris-react/issues/618
