### ISSUE TITLE
DropZone - error status not working correctly on Safari

### ISSUE THREAD

**Issue by cjhutchi** [Shopify/polaris-react#575]
# Issue summary

On Safari, the error flag for invalid filetypes is not getting raised correctly. Our dropzone is configured to only accept XML files, and when hovering with a PDF it should be showing an invalid file state. 

## Expected behavior

![chrome](https://user-images.githubusercontent.com/2898615/48279272-18248b00-e41e-11e8-8ba3-8daa85d19879.gif)

## Actual behavior

![safari](https://user-images.githubusercontent.com/2898615/48279289-207cc600-e41e-11e8-9bb8-ae09c8655b93.gif)

## Specifications

- Are you using the React components? (Y/N): y
- Polaris version number: 2.12.1
- Browser: Safari 12.0.1
- Device: MacBook Pro
- Operating System: macOS

**Comment by dfmcphee** [comment]
This is a known limitation with browsers other than Chrome, unfortunately. The validation on hover is seen more as an enhancement since it will still validate on drop.

**Comment by dfmcphee** [comment]
Going to go ahead and close this since there is nothing we can do on this one.

**Comment by cjhutchi** [comment]
@dfmcphee sorry meant to close this off last week. Totally forgot.
