### ISSUE TITLE
Add testing guidelines

### ISSUE THREAD

**Issue by solonaarmstrong** [Shopify/polaris-react#585]
Our tests are inconsistent.
- it statements are sometimes written in present, sometimes past tense
- `describe` sometimes describes individual props, sometimes entire components
- sometimes `toBe(true)`, other times `toBeTruthy`
- sometimes we use `simulate('click')`, other times `trigger`

We should add whatever is missing to the testing guidelines.

**Comment by dfmcphee** [comment]
Should this be moved to https://github.com/Shopify/web-foundation to get it added to our shared testing guide instead?

**Comment by solonaarmstrong** [comment]
Yes, that's a good idea.
