### ISSUE TITLE
[Autocomplete] Last example is listed in related components section 

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react#590]
# Issue summary
The "Autocomplete with empty state" example Markdown is not parsed with the other examples.

<img width="888" alt="screen shot 2018-11-09 at 1 29 56 pm" src="https://user-images.githubusercontent.com/18447883/48289244-98012400-e423-11e8-8eb2-566b3e79ce13.png">

## Expected behavior
It should be the last option in the Examples drop down and render in the playground.

## Actual behavior

It renders as content at the top of the related components section, parsed as a case study.

## Steps to reproduce the problem

1. Go to https://polaris.shopify.com/components/forms/autocomplete
2. Scroll the Related components section

## Specifications
- Polaris version number: v3.0.0

**Comment by solonaarmstrong** [comment]
Github has been giving me grief and I only just successfully got this up and running. I'm stumped by this one. Locally, with build-consumer, this works as it should.

![screen shot 2018-11-09 at 6 02 33 pm](https://user-images.githubusercontent.com/6239480/48296296-df021000-e449-11e8-8626-ea23077d4951.jpg)

The only changes I made were to move `textField` and `emptyState` markup into their own variables. 🤔 Here is the PR for that change: https://github.com/Shopify/polaris-react/pull/596
