### ISSUE TITLE
Missing period in "Simple errors" section

### ISSUE THREAD

**Issue by vladabee** [Shopify/polaris-react#5936]
In `Voice and tone` > `Adapting tone by situation` > `Simple errors`, there should be a period at the end of [this sentence](https://polaris.shopify.com/content/voice-and-tone#:~:text=In%20this%20case%2C%20our%20job%20is%20to%20help%20people%20understand%20what%20happened%20so%20that%20they%20can%20get%20back%20to%20work%20as%20quickly%20as%20possible):
>In this case, our job is to help people understand what happened so that they can get back to work as quickly as possible

**Comment by alex-page** [comment]
Hey @vladabee feel free to contribute a pull request in the future https://github.com/Shopify/polaris-styleguide/edit/main/pages/content/voice-and-tone.md

**Comment by alex-page** [comment]
This is fixed and should be live soon. 
https://github.com/Shopify/polaris-styleguide/commit/0f2708d56134333ca02aaa30bbbd0f666078f63f

**Comment by vladabee** [comment]
Hi Alex! I've never created a PR before, but I _am_ working my way through Patch, so hopefully soon 🤞🏻
Thanks for your help!
