### ISSUE TITLE
[Toggle] Import "Switch" as a new toggle component

### ISSUE THREAD

**Issue by solonaarmstrong** [Shopify/polaris-react#594]
# Toggle

Use toggle to present a single enable/disable selection.

### Basic toggle

Use toggle to let merchants enable or disable a setting.

![screen shot 2018-11-09 at 2 58 45 pm](https://user-images.githubusercontent.com/6239480/48293227-e7028580-e432-11e8-8bb6-50d677f17a2d.jpg)

## Props

List props and type declarations:

/** Toggles between enabled and disabled */
**checked** (optional): `boolean` defaults to `false`
/** Disables the toggle, disallowing interaction */
**disabled** (optional): `boolean` defaults to `false`
/** A unique identifier for the toggle */
**id** (optional): `string`
/** Label for the toggle */
**label** (required): `string`
/** Element to display before the input */
**prefix** (optional): `string`
/** Element to display after the input */
**suffix** (optional): `string`
/** Callback when the toggle value is changed */
**onChange()** (optional): `void`

## Best practices

The toggle component should:

- Always be used with an associated label component.
- Be used to switch a single setting on and off.
- Be disabled when the button is to the left and be enabled when the button is to the right. _(rework this phrase)_

## Content guidelines

Toggle labels should:

- Be clear what merchants are enabling or disabling
- Start with a capital letter
- Not end in punctuation if it’s a single sentence, word, or a fragment

| Off | off |
|------------|---------------|
| Off | Off; |

## Related components

- To present a list of options where merchants must make a single selection, use the radio button component
- To present a list of checkboxes, use the choice list component with the “allow multiple” option

**Comment by solonaarmstrong** [comment]
Being discussed further here: https://github.com/Shopify/polaris-ux/issues/216

**Comment by ziaulrehman40** [comment]
What happened to the issue? Link provided in comments(https://github.com/Shopify/polaris-ux/issues/216) also not working.

**Comment by sravanco** [comment]
So there is no switch on/off in polaris? Instead we should use a button(so called "Settings Toggle")?

**Comment by Crunchyman-ralph** [comment]
I would love to see this integrated in Polaris. Is there a way to use it anyway without having it integrated in polaris ? @solonaarmstrong-zz 
Do you maybe have some kind of documentation on the parameters of usage. Maybe a code example.

**Comment by ahmed-adly-khalil** [comment]
for anyone wondering, you can use https://polaris.shopify.com/components/actions/button-group
```
<ButtonGroup segmented>
  <Button>Bold</Button>
  <Button>Italic</Button>
  <Button>Underline</Button>
</ButtonGroup>
```

not the best solution IMHO but this is what's available now

**Comment by joeyfigaro** [comment]
Anyone at Shopify able to weigh in on implementing this component? Suggested workarounds with what is currently available is not a suitable replacement/stand-in.

**Comment by boxedcode** [comment]
Was there a final consensus on this component from the Shopify team?

**Comment by vpcarlos** [comment]
Any news?

**Comment by TimmJensen** [comment]
I would like to see such a switch as well! 🙏

**Comment by lpkobamn** [comment]
really want this..
