### ISSUE TITLE
Frame navigation component not working on mobile

### ISSUE THREAD

**Issue by RishabhTayal** [Shopify/polaris-react#598]
# Issue summary
The options are not selectable for navigation inside a frame when opened on mobile device.

**Comment by AndrewMusgrave** [comment]
Hi @RishabhTayal, are you using react components and what browser/device were you using?

**Comment by RishabhTayal** [comment]
@AndrewMusgrave I am using react components. I tried it on Safari and Chrome on desktop (resizing the window to make the width smaller for mobile device). Also ran the Shopify app inside the Shopify native iOS app. Doesn't work in any scenario.

**Comment by RishabhTayal** [comment]
Here is a video showing the issue. https://vimeo.com/300319146

**Comment by AndrewMusgrave** [comment]
Are you using anything for client side routing, i.e `react-router`? And if so have you set up a `linkComponent` on your [AppProvider](https://polaris.shopify.com/components/structure/app-provider)

**Comment by RishabhTayal** [comment]
We have not setup a `linkComponent` for the AppProvider. I see reference to `react-router` in code but I don't think we are using it for this flow.

**Comment by RishabhTayal** [comment]
@AndrewMusgrave The real concern is that it doesn't work on the example provided on polaris.shopify.com as well. I think that's why it's a bug in the component itself.

**Comment by AndrewMusgrave** [comment]
> The real concern is that it doesn't work on the example provided on https://polaris.shopify.com as well.

It does seems `onClick` is not being fired on small screens, it'll look into it.

**Comment by RishabhTayal** [comment]
That's correct. The `onClick` is not getting fired. Thanks.

**Comment by ctrlaltdylan** [comment]
I'm still experiencing this bug in 2023 with Polaris v10.11.0.
