### ISSUE TITLE
/snapit in the release branch publishes the next version instead of a snapshot

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#6001]
> **chloerice**
> /snapit

> @github-actions
> 
> 🫰✨ Thanks @chloerice! Your snapshot has been published to npm.
>
> Test the snapshot by updating your package.json with the newly published version:
>
> ```
> yarn add @shopify/polaris@9.12.0
> ```

https://github.com/Shopify/polaris/pull/5973#issuecomment-1143806254

**Comment by sam-b-rose** [comment]
I think this might be an issue with the `changeset version` command when run on a branch with the prefix `changeset-release/${branch}`

Just a guess based on [this line here](https://github.com/changesets/changesets/blob/main/packages/release-utils/src/run.ts#L111).

**Comment by alex-page** [comment]
@samrose It would be super if the `--snapshot` flag stopped it from getting the version from the branch. Unsure what that could mean for changesets package.

**Comment by BPScott** [comment]
Perhaps we add a check so that the `/snapit` command tells you to go away if you try to run it in a PR opened by the github-actions user?

**Comment by alex-page** [comment]
Well the intention is to do a final tophat in the release branch. So snapit in that branch would be super useful. The downside is that changesets has some logic to do an actual release from that branch.

**Comment by aaronccasanova** [comment]
Maybe we go back to the original `/snapit` implementation and create a temp snapshot branch before running all the changeset commands 🤷
```sh
git checkout main
git checkout feat/branch
git checkout -b temp-snapshot-release
yarn version-packages -- --snapshot snapshot-release
yarn release -- --no-git-tags --snapshot --tag snapshot-release
```

Basically, add `git checkout -b temp-snapshot-release` after [this step](https://github.com/Shopify/polaris/blob/267ea998be61eb8d448129169a7a638833890ab0/.github/workflows/snapit.yml#L32-L37)

**Comment by alex-page** [comment]
That is a good idea. That would definitely stop this from happening and the branch would get cleaned up when the action completes running.
