### ISSUE TITLE
Where did the tooltip arrow?

### ISSUE THREAD

**Issue by kadsystems** [Shopify/polaris-react#604]
In the new version of polaris the tooltip arrow has disappeared. 

![image](https://user-images.githubusercontent.com/27851002/48416822-3bbf3c80-e762-11e8-80f2-a8df0f78d473.png)

Please return it to its place.

**Comment by AndrewMusgrave** [comment]
Removing the arrow was a UX decision. Heres the [commit](https://github.com/Shopify/polaris-react/commit/17c2ef5e2b868f85295112706d4067a65f0af038) if you were curious.

**Comment by chloerice** [comment]
The arrow was removed purposefully, as it was buggy when popovers were aligned left or right and was also causing issues in the autocomplete component.

**Comment by kadsystems** [comment]
@chloerice I talk about tooltip. not popover. It's a bad decision, it degrade the intuitiveness of the interface. I am disappointed.

**Comment by danrosenthal** [comment]
@kadsystems, we intentionally removed the pointer, or caret from `Popover` and `Tooltip` for the following reasons:

- we believe that it is not needed to communicate a relationship with the activator, as proximity is enough. We are exploring adding motion to reinforce this relationship
- it creates a gap between the activator and the content, which is a source of visual noise
- implementation was difficult (problems with shadows and alignment), without much of a return in terms of user experience

> We used the tooltips for the setup wizard and they were a great solution because exactly indicate where to click the user

Using this component as a wizard or indicator of where to click is not the intended use-case of this component, and not one we will optimize for. The `Tooltip` component, as described in the docs you linked, is intended to provide additional context on text content, like a link or an icon, and is meant to be revealed when an action is taken by a merchant.

If this is still not acceptable, we invite you to fork the `Tooltip` component in your project and add the caret back in, or explore using another library.

> It's a bad decision, it degrade the intuitiveness of the interface. I am disappointed.
> With each update a new breakdown

Finally, we ask that you please avoid non-constructive criticism, maintain a respectful tone when commenting on this repository, and adhere to the [standards in our code of conduct](https://github.com/Shopify/polaris-react/blob/master/.github/CODE_OF_CONDUCT.md#our-standards).
