### ISSUE TITLE
v10 Breaking changes

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react#6070]
This list is bound to change. Feel free to comment, add, and remove

**Frame – Needs to be more flexible, less confusing**:
- [ ] Allow Frame / TopBar to accept `logo` as React.Node 
- [ ] Remove `contextControl` from Navigation, TopBar - confusing name, will be replaced by new logo prop

**Remove dark color scheme**:
- [ ] Remove `CustomProperties` component
- [ ] Remove `colors.dark` from `@shopify/polaris-tokens`
- [ ] Remove `colorScheme` prop from individual components: `TopBar.UserMenu``TopBar.Menu`, `Popover`, `AppProvider`, `PolarisTestProvider`. 

**Infra**
- [ ] Remove downlevel-dts typescript v3 support

**Comment by BPScott** [comment]
Infra request: Add engines fields specifying required node versions [in the style of quilt packages](https://github.com/Shopify/quilt/blob/ce65bd8151eb57fd47dde70c9a9985a1150e5a12/packages/react-hooks/package.json#L26-L28)


Infra not-critical idea: Investigate replacing `babel` with `swc` for faster build and test runs (this probably could be done in a minor as all being well functionality should remain the same

**Comment by BPScott** [comment]
Infra idea - not really a v10 thing as this could happen independently: Once we decide to kill off the old polaris site then we no longer need to distribute component readme information for inclusion in the docs site. The [`docs`](https://unpkg.com/browse/@shopify/polaris@9.19.0/build/docs/) folder can be removed - [it's generated here](https://github.com/Shopify/polaris/blob/af5aac63ff394ece8f4ebc8b1bb593b3440bc89e/polaris-react/package.json#L52).

**Comment by alex-page** [comment]
Going to close this issue and start a v11 one. Thanks @kyledurand and @BPScott
