### ISSUE TITLE
Toast and Loading display frame context required errors when in an embedded app

### ISSUE THREAD

**Issue by tmlayton** [Shopify/polaris-react#611]
These errors are non-blocking

![image](https://user-images.githubusercontent.com/344839/48442506-3b637900-e743-11e8-99a7-db51364add3b.png)

![image](https://user-images.githubusercontent.com/344839/48442532-533afd00-e743-11e8-8cd0-dbfd20155e67.png)

**Comment by tmlayton** [comment]
cc/ @AndrewMusgrave

**Comment by AndrewMusgrave** [comment]
Will take a look in the morning 👀

**Comment by AndrewMusgrave** [comment]
It was a small fix so I put up a PR however it seems I didn't set my embedded app up properly so I can
t 🎩 the components work, only that the errors are gone. Will do tomorrow.
