### ISSUE TITLE
labelInline property of Select component is not rendering the label inline

### ISSUE THREAD

**Issue by carrocon** [Shopify/polaris-react#616]
# Issue summary
_labelInline_ property of Select component is not rendering the label inline.

## Expected behavior
When _labelInline_ is set to true the label should be set to the left of the component within the same line.

## Actual behavior
The label of the component is always set on top of the Select component no matter the value of _labelInline_ .

## Steps to reproduce the problem
See CodeSandbox example below.

## Reduced test case
https://codesandbox.io/s/5xm006lo5k

## Specifications
- Are you using the React components? Y
- Polaris version number: 3.0.0
- Browser: Chrome
- Device: PC
- Operating System: Windows 10

**Comment by AndrewMusgrave** [comment]
👋 It appears your on `v2.1.1` of polaris and this feature was added in `v2.3.0`
