### ISSUE TITLE
Resource picker 404s

### ISSUE THREAD

**Issue by markiiikram** [Shopify/polaris-react#618]
# Issue summary

When searching for the resource picker the page 404s.

![polaris embedded](https://user-images.githubusercontent.com/3484321/48487698-ef6d0e80-e7ec-11e8-9f05-1b3373acc246.gif)

This is also an issue for any embedded component that shows up in the search, or for bookmarked urls. see: https://github.com/Shopify/polaris-react/issues/574#issuecomment-438604530.

## Expected behavior

Embedded components should no longer show up in the search. Old urls should redirect to new ones.

## Steps to reproduce the problem

1. Go to the search
1. Type in "resource picker" or "embedded"
1. Click on the link

cc: @katiedavis

**Comment by AndrewMusgrave** [comment]
Our search needs to be reindexed. @kaelig mentioned they we're working on it. AFAIK their's nothing we can do on our end

**Comment by BPScott** [comment]
ping @kaelig as IIRC he poked Agolia about this.

**Comment by tmlayton** [comment]
Closing in lieu of https://github.com/Shopify/polaris-styleguide/issues/2388
