### ISSUE TITLE
Serve Embedded Polaris App 

### ISSUE THREAD

**Issue by imgntn** [Shopify/polaris-react#619]
# Issue summary

Is it possible to serve an embedded app using EASDK and its API separately on different subdomains?

e.g. 
api on Elastic Beanstalk at https://api.product.com
polaris EASDK app on S3 at https://shopifyapp.product.com

## Expected behavior

I'd like to be able to serve my frontend app from a static CDN so that it scales up and user activity on the frontend doesn't slow down my api.  I'd like to be able to scale frontend and backend separately.  

## Actual behavior

When I get through the auth and charge activation process and then inject the shopOrigin when I redirect to the EASDK Polaris app on s3, I get an error from the frontend app.

I get the postmessage error about origins being different, even though both subdomains are on the same domain.

```Failed to execute 'postMessage' on 'DOMWindow' The target origin provided does not match the recipient window's origin .```

## Specifications

- Are you using the React components? (Y/N): Y 
- Polaris version number: 2.12
- Browser: Chrome
- Device: Desktop
- Operating System: Windows

**Comment by tmlayton** [comment]
Hey @imgntn thanks for the question, as long as the URL for your app matches what you have in the app setup in the Partners dashboard and your `shopOrigin` matches the url of the shop which is currently loading the app, then yes you could do this.

The error you are seeing is related to a mismatch in the `shopOrigin` and the shop URL which is currently loading your app. With Polaris v2.12, `shopOrigin` is required and should include the scheme (https://), for example `https://CURRENT_LOGGED_IN_SHOP.myshopify.com`. As of Polaris v3.0.0, the `shopOrigin` is no longer required.
