### ISSUE TITLE
Clean up `component` page typography

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react#6202]
* Do’s and don’ts
* the hierarchy
* Weird bullet points under do’s and don’ts. A bit jarring
* Tweak line heights and spacing, minor tweaks
* X and check don’t line up with the dot points below

**Comment by martenbjork** [comment]
I've done a bunch of touch ups to the dos and don'ts. I'll close this issue as this address mosts of the points above.

![Image](https://user-images.githubusercontent.com/875708/174905662-605b3b42-1e4b-40e3-95a0-75bb6c926728.png)

![Image](https://user-images.githubusercontent.com/875708/174905661-16a7f674-5c64-4f71-99c1-09044d556dc4.png)
