### ISSUE TITLE
[Mobile-friendly] Tokens page: Header overlaps mobile nav backdrop

### ISSUE THREAD

**Issue by gui-santos** [Shopify/polaris-react#6234]
<img width="369" alt="17-28-agbkq-uuwjy" src="https://user-images.githubusercontent.com/6597467/174329681-4f55333c-4795-4e6e-9e1d-b04e92a3874c.png">

- [x] Show tokens in a list until there is enough space for the table format
- [x] ~~table head is rendering over the backdrop of the `MobileNav`~~ (it seems to be fixed in https://github.com/Shopify/polaris/pull/6226)

**Comment by martenbjork** [comment]
Tokens page is now responsive. Let's have a look at the backdrop situation next week :)

**Comment by gui-santos** [comment]
I gave another check and there is a different bug with the backdrop in the main branch, BUT all the issues are fixed in https://github.com/Shopify/polaris/pull/6226
So maybe we don't need to do anything :)
