### ISSUE TITLE
Skeleton page example looks like card

### ISSUE THREAD

**Issue by jzazove** [Shopify/polaris-react#6284]
## Issue summary
The skeleton page example looks like a card (not a page). 
<img width="850" alt="21-15-lvthp-f073z" src="https://user-images.githubusercontent.com/588907/174942201-4c3c0236-c312-4b38-a6f2-0389840bbe64.png">

## Expected behavior
It should look like a page.
<img width="876" alt="21-15-c7pao-4q4kw" src="https://user-images.githubusercontent.com/588907/174942504-07d060fb-121d-4923-9be8-80990d056831.png">

**Comment by alex-page** [comment]
This is resolved. Thanks @jzazove
