### ISSUE TITLE
TitleBar support for multiple breadcrumbs?

### ISSUE THREAD

**Issue by janklimo** [Shopify/polaris-react#630]
#### Issue summary

I noticed that `TitleBar.create` accepts the following options:

```typescript
export interface Options {
    title?: string;
    buttons?: ButtonsOptions;
    breadcrumbs?: Button;
}
```
This would suggest that there can only be one breadcrumb passed. Is that by design or a bug?

#### Expected behavior

Since `breadcrumbs` is plural, I'd expect it supports an array of `Button`s as an input.

#### Actual behavior
Only one `Button` can be passed in.

#### Steps to reproduce the problem

```typescript
const titleBarOptions = {
  title: "My Title Bar",
  breadcrumbs: [Button.create(app, { label: "one" }), Button.create(app, { label: "two" })]
};

TitleBar.create(app, titleBarOptions);
```

## Specifications

- Are you using the React components? (Y/N): y
- Polaris version number: 3.0.0
- Browser: Chrome
- Device: MacBook Air
- Operating System: OS X El Capitan

**Comment by AndrewMusgrave** [comment]
This interface comes from an internal package. cc/ @gf3

**Comment by tmlayton** [comment]
As @AndrewMusgrave mentioned, this issue is related to the Shopify App Bridge. For now, I would recommend posting in https://ecommerce.shopify.com/c/shopify-apis-and-technology.
