### ISSUE TITLE
Polaris License Question

### ISSUE THREAD

**Issue by junaid33** [Shopify/polaris-react#632]
Hello,

We want to use Polaris to build our MVP, but just had a few questions about the license. It says restricted use for 3rd party and outside applications, but you also offer a Polaris design token to change the design specs for the components which is under a MIT license. Does that mean we can use Polaris as long as we change the design? Thank you for your help.

**Comment by danrosenthal** [comment]
@junaid33 thanks for your question. According to our updated license, Polaris is for use exclusively within the Shopify ecosystem. As seen below:

> may only be exercised to develop and distribute applications that integrate or interoperate with Shopify software or services

That means that, even with design changes, it is not permitted to use Polaris if your application does not integrate with or interoperate with Shopify software or services.

**Comment by Fiachralennon** [comment]
Hi Dan,

I have a question on the above. Whilst I understand your comment relating to point 1 of the licence for Polaris, however that point appears to be further clarified in point 2 "unless such External Application is not identical to and is dissimilar and visually distinct from Shopify products and services".

This would seem to suggest that as long as the application I'm designing bears little resemblance to Shopify it is fine to be used? Can you clarify this?

Thanks.

**Comment by paulrostorp** [comment]
@Fiachralennon is right. I too find art. 1 & 2 to be contradictory or at least confusing on this point.
Could you please clarify ?
Thanks

**Comment by chloerice** [comment]
> I have a question on the above. Whilst I understand your comment relating to point 1 of the licence for Polaris, however that point appears to be further clarified in point 2 "unless such External Application is not identical to and is dissimilar and visually distinct from Shopify products and services".
> 
> This would seem to suggest that as long as the application I'm designing bears little resemblance to Shopify it is fine to be used? Can you clarify this?

Hey @Fiachralennon, I agree, the second point in the license that mentions stand alone applications is a bit confusing. Polaris is *only* permitted to be used by applications that are part of the Shopify ecosystem, whether they're embedded or stand alone apps.

>  ...in the case of external, stand-alone applications that do not embed directly inside Shopify, the rights granted above may only be exercised to develop and distribute applications that are dissimilar and visually distinct from Shopify products and services

This is saying that steps must be taken to ensure an application using Polaris does not resemble the Shopify admin or any other Shopify product or service if it is not an embedded app. It needs to be clear to merchants using your app that it is not a Shopify product in order to prevent confusion.

**Comment by spchuang** [comment]
If I understand correctly, the new license only applies to Polaris versions after v3? So polaris code before 3 should be freely usable outside of Shopify system? Say we are building an embedded app within Shopify but also intend to use the tool for other ecommerce platforms.

**Comment by GeorgeWillaman** [comment]
Little bit late, possible to get a final confirmation though? Is SP correct?

**Comment by fmontada** [comment]
I am also confused, it is Polaris Free to use outside of Shopify ?
