### ISSUE TITLE
[polaris.shopify.com] 404 not found at /foundations/foundations/designing-apps

### ISSUE THREAD

**Issue by JoshHighland** [Shopify/polaris-react#6366]
404 coming from Google SERP

![image](https://user-images.githubusercontent.com/142943/175398419-8412e1bd-a69c-46d3-8440-d0de7f295ab7.png)

**Comment by alex-page** [comment]
Hey @JoshHighland this page was removed intentionally. The app guidance which lived under "Designing apps for Shopify" is now a part of the [App Design Guidelines on shopify.dev](https://shopify.dev/apps/design-guidelines). 

If there is something you are unsure about please feel free to add to the issue.

**Comment by alex-page** [comment]
@JoshHighland I am going to add some redirects to shopify.dev to help with this issue.
