### ISSUE TITLE
[polaris.shopify.com] Props table is missing for components

### ISSUE THREAD

**Issue by Epiffany** [Shopify/polaris-react#6371]
Just browsing the new component documentation - the props table is not there (or is hidden). Where'd it go? That was helpful to see the full capabilities or constraints of the component.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by alex-page** [comment]
Thanks @Epiffany, we have heard a lot of feedback on this feature missing. I don't have a timeline to share but it's on our radar 👀

**Comment by timup** [comment]
Just wanted to add a +1 on this... the props list was very helpful.

**Comment by MaxDesignFR** [comment]
I've been made aware that they're still available on https://legacy.polaris.shopify.com/ Until they release it in the new doc, this could be helpful for some of us.

**Comment by edlaver** [comment]
Along with having the props listed again on the polaris.shopify.com site, it'd also be great to be able to see them on the Storybook site (https://storybook.polaris.shopify.com/)

I like to be able to see the entire list of all components in one go, but currently there's no way (that I can see) to see any of the props there either.

There's a `Controls` section in the add ons, but it just says: `This story is not configured to handle controls.`, with a link pointing to: https://storybook.js.org/docs/react/essentials/controls

According to this page (https://github.com/storybookjs/storybook/blob/master/addons/docs/docs/props-tables.md) prop tables are meant to display automatically on the `Docs` page in Storybook?  Hopefully there's something simple that can be added to enable them there as well as on the main site.

Thanks!

**Comment by alex-page** [comment]
@edlaver we have a lot of duplication with storybook and the documentation site. We will work to consolidate this over the coming months. For now we won't be adding props to storybook and keep this focused to the site.
