### ISSUE TITLE
Settings navigation spacing bug

### ISSUE THREAD

**Issue by simon-callsen** [Shopify/polaris-react#6389]
## Issue summary

![image](https://user-images.githubusercontent.com/39070235/175563862-374c4abd-3993-42a7-b1df-e1044a77cc11.png)

Spacing on the setting navigation component is broken when text spans across two lines.

**Comment by alex-page** [comment]
@simon-callsen I am going to close this issue as it's a product issue. If you can replicate it in Polaris or add additional context that would be great.
