### ISSUE TITLE
Modal in Polaris not work

### ISSUE THREAD

**Issue by fchienvuhoang** [Shopify/polaris-react#641]
# Issue summary
I upgrade to Polaris 3x, and added apiKey to AppProvider But Modal not work and show this error!!!

<img width="585" alt="screen shot 2018-11-19 at 10 55 14 am" src="https://user-images.githubusercontent.com/4451749/48685595-a8668b00-ebe9-11e8-8870-be6ffb33fd73.png">

<img width="1413" alt="screen shot 2018-11-19 at 10 50 16 am" src="https://user-images.githubusercontent.com/4451749/48685536-64738600-ebe9-11e8-9a44-09d72fa2f5e6.png">

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.1.0
- Browser: Chrome
- Device: MacBook Pro
- Operating System: OSX Mojave

**Comment by dfmcphee** [comment]
Hey @fchienvuhoang. Thanks for opening the issue. The modal component does not support passing JSX children when using it through App Bridge.

Instead you will want to point the modal at your iframe source directly with something like:

```
<Modal
  open={this.state.instructionalVideoModal}
  onClose={this.closeInstructionVideo}
  title="Instruction Video"
  primaryAction={{
    content: 'Done',
    onAction: this.closeInstructionVideo,
  }}
  src="https://www.youtube.com/embed/xhta4n68p_g?rel=0&autoplay=1"
/>
```

**Comment by meecrobe** [comment]
> The modal component does not support passing JSX children when using it through App Bridge.

Hello, @dfmcphee!
Does the team plan to implement render of child components inside Modal? Current behavior makes Modal useless in most cases for me personally.

**Comment by fchienvuhoang** [comment]
@dfmcphee thank you, I will try it!

**Comment by fchienvuhoang** [comment]
Hi @dfmcphee, may be not a <iframe> error. I try other modal content but still get the error!
Thanks

```
 <Modal
          open={true}
          onClose={this.handleChange}
          title="Reach more shoppers with Instagram product tags"
          primaryAction={{
            content: 'Add Instagram',
            onAction: this.handleChange,
          }}
          secondaryActions={[
            {
              content: 'Learn more',
              onAction: this.handleChange,
            },
          ]}
        >
          <Modal.Section>
            <TextContainer>
              <p>
                Use Instagram posts to share your products with millions of
                people. Let shoppers buy from your store without leaving
                Instagram.
              </p>
            </TextContainer>
          </Modal.Section>
        </Modal>
```

**Comment by rmtngh** [comment]
Hi @dfmcphee,
I tried the code you provided with the same props (I just changed open and onClose props)
And in embedded app I get this error:
![image](https://user-images.githubusercontent.com/20207426/49019743-e2b0c900-f1a3-11e8-9b8f-1d82e75b4efc.png)

**Comment by mrdja026** [comment]
I dont know if this is relevant but the issue is also present in the 3.0.0 version of the library, just copy-pasted the examples from the doc, same AppBridgeError occurs.

**Comment by chloerice** [comment]
Hi @rmtngh and @mrdja026, the modal component currently still does not accept children when used in an embedded app. Happy to help you debug the AppBridge error if you post a code sample of how you're using the modal. This, albeit pretty unclear, error means the modal has props set that it cannot accept.

**Comment by rmtngh** [comment]
Hi @chloerice,
As I mentioned in my comment I'm trying the sample code suggested by @dfmcphee a few comments above, and there are **no children**.
I tried this too (removed actions):
```
<Modal
            open={this.state.testModalOpen}
            onClose={()=>this.setState({testModalOpen:false})}
            title="Instruction Video"
            src="https://www.youtube.com/embed/xhta4n68p_g?rel=0&autoplay=1"
          />
```
 ** Even if it was passed some wrong props, wouldn't it be better to just ignore them instead of breaking? currently the whole page that the modal is rendered in is breaking in an embedded app.

**Comment by AKarmanov** [comment]
Ok, so to make it work I had to add message and size parameters

**Comment by ckeyes88** [comment]
We're also experiencing this issue with a copy past from the polaris documentation using `"@shopify/polaris": "^3.2.1",`

Why do the documentation examples [here](https://polaris.shopify.com/components/overlays/modal#all-examples) show a child prop if the Modal does not accept child props.

```js
class ModalExample extends React.Component {
  state = {
    active: true,
  };

  render() {
    const {active} = this.state;

    return (
      <div style={{height: '500px'}}>
        <Button onClick={this.handleChange}>Open</Button>
        <Modal
          open={active}
          onClose={this.handleChange}
          title="Reach more shoppers with Instagram product tags"
          primaryAction={{
            content: 'Add Instagram',
            onAction: this.handleChange,
          }}
          secondaryActions={[
            {
              content: 'Learn more',
              onAction: this.handleChange,
            },
          ]}
        >
          <Modal.Section>
            <TextContainer>
              <p>
                Use Instagram posts to share your products with millions of
                people. Let shoppers buy from your store without leaving
                Instagram.
              </p>
            </TextContainer>
          </Modal.Section>
        </Modal>
      </div>
    );
  }

  handleChange = () => {
    this.setState(({active}) => ({active: !active}));
  };
}
```

**Comment by fchienvuhoang** [comment]
I tested modal in Polaris 3.10.0 and it worked, i should close this issue!

**Comment by fchienvuhoang** [comment]
I tested modal in Polaris 3.10.0 and it worked, i should close this issue!
