### ISSUE TITLE
ResourceList actions

### ISSUE THREAD

**Issue by roman-pauk** [Shopify/polaris-react#642]
# Issue summary
ResourseList component doesn't show selected items in the header.
I saved the selected items to the redux store and when I mount my component again it doesn't show any selected item in the header.

![image](https://user-images.githubusercontent.com/25792725/48705514-ff785a00-ec01-11e8-888b-0885eef4548e.png)
After selecting the item, it returns to normal work
![image](https://user-images.githubusercontent.com/25792725/48705749-aceb6d80-ec02-11e8-9e0c-8b7889f9907a.png)

**Comment by chloerice** [comment]
Hi @roman-pauk 👋, thanks for raising this.  

To clarify what's happening, the resource list doesn't update the header in response to its `selectedItems` prop updating until the third try? That's strange, as I wouldn't expect the checkboxes to work at all (show a selected state) if there were an issue with the method you passed to `onSelectionChange`. 

It sounds like it's not a problem with the component itselft, but rather a disconnect between the action you dispatch that updates selected items in your store and the component rendering the resource list receiving the updated state from the store. But it will be hard to help you debug that without any code. Can you create a reduced test case? Or post a code example including the reducer that handles the `selectedItems`, your action and action creator, and your `mapStateToProps`?

**Comment by roman-pauk** [comment]
Hi, I have created the basic project. You can see it on [http://tasteless-dogs.surge.sh/](url)

The code is here: [https://github.com/roman-pauk/shopify-polaris-issue](url)

Try to select items, go to the profile page and then go back.
Thanks.

**Comment by dpersing** [comment]
Hi @roman-pauk! Thanks for sharing the example with navigating away and back.

Can you share a bit about the use case here? Typically making multiple selections leads up to doing a bulk action on the current page. Navigating away seems to indicate that the user wants to leave that interaction and do something else, which would cancel the selection. Does that make sense?

**Comment by chloerice** [comment]
Thanks for putting together the reduced case @roman-pauk! Looks like the component is working as expected. If you want to persist your redux store, you'll can use localStorage directly, a session middleware in your backend, or some other cookie set up.

**Comment by roman-pauk** [comment]
@chloerice, @dpersing, thanks for answers. The expected behavior: for example, I select 2 items and go to another page(inside the app), when I return to this page I want to see selected items(it is still selected because I save it in redux store) and active checkbox and actions(but actions are hidden and checkbox is inactive as in pristine state)

@dpersing, yes, it makes sense, but not in my case :)
@chloerice I don't need to save selected items after the user leaves the app.

**Comment by roman-pauk** [comment]
I know where is the problem. 'ResourseList' component has 'selectMode' option in the state and it is 'false' by default(when the component has mounted, it equals to 'false'). That's why the component doesn't show the 'bulk actions' if it mounts with selected items in props.

![image](https://user-images.githubusercontent.com/25792725/48839733-1c916200-ed95-11e8-89d8-bc888411eb38.png)

![image](https://user-images.githubusercontent.com/25792725/48839764-2ca94180-ed95-11e8-9296-a2f47eb9db0d.png)

Can you help to solve this?

**Comment by chloerice** [comment]
@roman-pauk @AndrewMusgrave has a PR up to fix this 😁
