### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components/badge)

### ISSUE THREAD

**Issue by yemi-f** [Shopify/polaris-react#6450]
polaris.shopify.com does not have a list of props for each component like legacy.polaris.shopify.com. This list made info easy to find at a glance.
E.g.
Current: https://polaris.shopify.com/components/badge
Legacy: https://legacy.polaris.shopify.com/components/badge

**Legacy Props**
<img width="903" alt="image" src="https://user-images.githubusercontent.com/55517952/176690559-96a8a067-dec9-4ffe-a9b7-eb92bd1d2205.png">

**Comment by martenbjork** [comment]
Hi! Thanks for the feedback :) We're working on bringing the table back — we'll have more updates to share soon!

Closing this issue as we're tracking it here: https://github.com/Shopify/polaris/issues/6371
