### ISSUE TITLE
Date Picker - disableSpecificDates property example doesn't work

### ISSUE THREAD

**Issue by CharlyTalavera** [Shopify/polaris-react#6452]
Hi everyone! I tried to use the Polaris [Date Picker](https://polaris.shopify.com/components/date-picker) with the example "Date picker with specific disabled dates". I opened that exact example in the code sanbox, and it's not disabling the example dates. (10, 12, and 21 of february). They still available.

It's not disabling the example dates. I suspect that it' s related to my timezone.

I did a `console.log(disableSpecificDates)`, and the output was:
```js
[Mon Feb 12 2018 02:00:00 GMT-0300 (Argentina Standard Time), Sat Feb 10 2018 02:00:00 GMT-0300 (Argentina Standard Time), Wed Feb 21 2018 02:00:00 GMT-0300 (Argentina Standard Time)]
```

As you can see, the created dates has an offset.

If i replaced the Calendar dates with this format:
```js
  const disableSpecificDates = [
    new Date("2018-02-12T00:00:00"),
    new Date("2018-02-10T00:00:00"),
    new Date("2018-02-21T00:00:00")
  ];
```

It works fine. And the output is:
```js
[Mon Feb 12 2018 00:00:00 GMT-0300 (Argentina Standard Time), Sat Feb 10 2018 00:00:00 GMT-0300 (Argentina Standard Time), Wed Feb 21 2018 00:00:00 GMT-0300 (Argentina Standard Time)]
```

As you can see. There is not offset in the time now.

Then i tried:
```js
  const disableSpecificDates = [
    new Date("2018-02-12T03:00:00"),
    new Date("2018-02-10T03:00:00"),
    new Date("2018-02-21T03:00:00")
  ];
```

With the value at 3 am. And the dates are not disabled correctly.
So, what i suspect that is happening is the following:
* The Date Picker only works when the date time is "00:00:00". For people who have another timezone, the example in the documentation creates a Date with an offset, which means that it will not work on their end.

The way to reproduce is quite simple. Open the Date Picker example in a sandbox provided by the documentation, change the hour, and it will fail. For people who live in another timezone, that change will be done automatically. I created a sandbox where i modified the date time of the example: https://codesandbox.io/s/wizardly-mountain-xy0i5k?file=/App.js

Expected behavior: It should disable the date ignoring the hour. Like it does for the fields `disableDatesBefore` and `disableDatesAfter`.

Browser: Chrome Version 102.0.5005.61
OS: Linux

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by marcdelalonde** [comment]
Any news here?

**Comment by charlesmdp** [comment]
I'm having the exact same issue , any news @heyjoethomas @alex-page 😇 ?

**Comment by alex-page** [comment]
Hey folks happy for a contribution to resolve this issue.

**Comment by fabregas4** [comment]
Crazy this hasn't been fixed or looked at. How can there be a property on a Polaris component for so long that doesn't do what it's meant to do - like at all.
