### ISSUE TITLE
Dropping non-file type images in dropzone

### ISSUE THREAD

**Issue by singhprincejeet** [Shopify/polaris-react#646]
# Feature request summary
The DropZone component should allow non-file type images to be dropped and uploaded. 

## Rationale
Images are stored on various online platforms so it will be nice to have a feature where merchants can drop images from browsers or just drag an URL to upload an image.

I set the `Impact - Small` since its a nice to have feature and in the best of my knowledge, there is no demand for it.

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by chloerice** [comment]
Thanks for the request @singhprincejeet! 

I’ll close this issue for now, but we encourage everyone who wants this feature to add a 👍 to the original issue report. We take your collective interest into account when we look at what to work on next.
