### ISSUE TITLE
[polaris.shopify.com] Feedback 

### ISSUE THREAD

**Issue by dsenese** [Shopify/polaris-react#6468]
Hello, 

The new documentation is very clean and easy to find what I need. Really enjoy the search bar where you include icons and imagery in the results.  However it is difficult to utilize when you don't show any of the required fields or extra fields that are available on each component. Most times the example does not show it all and the field descriptions are the main thing that I use when referencing the docs.

I personally will be using the old layout until this is added.

**Comment by martenbjork** [comment]
Hi! Thanks for the feedback! Adding the props back is on our radar and we'll have an update for you soon. I'll close this issue as we're tracking all feedback about this in this thread:

https://github.com/Shopify/polaris/issues/6371
