### ISSUE TITLE
[polaris.shopify.com] 404 not found at /tokens/all-tokens

### ISSUE THREAD

**Issue by radscheit** [Shopify/polaris-react#6481]
Coming from `https://polaris.shopify.com/foundations/design/spacing` to study spacing tokens. Link is dead.

**Comment by martenbjork** [comment]
Appreciate the report! 🙌 We'll fix it!

**Comment by martenbjork** [comment]
The link to the spacing tokens on [this page](https://polaris.shopify.com/foundations/design/spacing) seems fine to me. Can you check if you're still able to find the broken link?

I'll close the issue for now but keep an eye out for replies!
