### ISSUE TITLE
[Figma Ui Kit] [Button] Full width button doesn't have all states

### ISSUE THREAD

**Issue by edmacovaz** [Shopify/polaris-react#6519]
Problem: Full width buttons don't have all states (like hover, focus, or loading)

Solution: Add all states for full width buttons

Branch in Figma: https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/branch/S6X2L7GjUeupMmYZqyKuaM/Polaris-Components?node-id=7%3A3

**Comment by heyjoethomas** [comment]
Hey @edmacovaz thanks for the contribution and opening an issue to track this. 

1. Would you be able to add the states for all full width variants of the Primary Button or, if you can swing it, the Basic Button as well? Having them all in the Primary Button sizes and small screen variants would be great.
2. I quick reorganized the variants to follow the pattern of the rest of the library so everything is neat and tidy. If you could follow that it would be much appreciated. Tying to practice good file hygiene 😄

**Comment by edmacovaz** [comment]
Thanks @heyjoethomas 

1. Done
2. Of course. You caught me with my desk in a mess there...

**Comment by heyjoethomas** [comment]
It's all good. Thanks again for the contribution.
