### ISSUE TITLE
[polaris.shopify.com] Feedback (general)

### ISSUE THREAD

**Issue by curtisburns** [Shopify/polaris-react#6529]
Searching for components is significantly more difficult, especially for people new to the library. The sidebar is ordered alphabetically only, whereas the previous site had categories. This would be fine except the search results are limited to three components. For example, if I search for 'list', I don't get all the list components, just the first three. I also can't find all list components quickly in the sidebar as they don't appear together because they start with a different letter. Categories help me quickly identify which components I have at my disposal for different situations. It's a shame this has been removed. Maybe a visible tag system for reference on the component page to be used as a search term and more visible results (horizontal scroll) might fix this?

Where have the props disappeared to? They're either removed or hidden away. They're essential to getting an 'at a glance' idea of how components are used without importing them and running through the type definition.

Missing information regarding the Avatar component on how the colours change (this is an issue on the legacy site too), I believe this may also be a problem with a number of other components, such as the IndexTable.Cell and the `data-primary-link` prop for handling links.

Hope this helps. Great work!

**Comment by heyjoethomas** [comment]
Hey Curtis. Thanks for the feedback. Really insightful. We will take it back as we continue to iterate on the site. Work on the props table can be followed here #6371 In the meantime you can still see prop tables at [legacy.polaris.shopify.com](https://legacy.polaris.shopify.com/)

**Comment by martenbjork** [comment]
Hi Curtis! Thanks for the thoughtful feedback! 🥰

### Components list
We have user research showing that many people prefer a long alphabetical list, so we went with that for the side nav. Simplifying a bit, we see 2 common user stories:

1. If I'm new to the system, categories help me explore the different sets of components in a nice, grouped way.
2. If I'm an experienced Polaris user and know which component I'm looking for, an alphabetical list helps helps me quickly find the right one without having to first figure out which category it would be in.

Our new design uses both patterns — the visual grid is grouped into categories, but the list to the left is not.

Having said all this, I don't think we have reached the best possible design here and I'm keep to improve the components page.

### Props list
Like Joe said, it's on our radar and is being worked on!

### Avatar preview
Thanks for highlighting this! We were talking about the examples this morning. I don't have any strong ideas just yet, but we agree that the examples sometimes don't highlight a component's variations in a meaningful way.

---

Anyways, thanks for the feedback — it helps a lot!

**Comment by martenbjork** [comment]
> I don't get all the list components, just the first three

BTW, this is clearly a mistake. Will fix!

**Comment by curtisburns** [comment]
Thanks, guys! I'm looking forward to seeing future developments 👍 It's looking great so far.

**Comment by chloerice** [comment]
Just an update on this issue, the props table is being improved in https://github.com/Shopify/polaris/pull/6757.
