### ISSUE TITLE
[polaris.shopify.com] Component navigation sidebar includes purpose/categories

### ISSUE THREAD

**Issue by joelzwarrington** [Shopify/polaris-react#6573]
## Feature request summary

It would be nice if the navigation sidebar was separated by category/purpose like it is on the main page, so that I can quickly navigate between components.

![image](https://user-images.githubusercontent.com/80279872/178041432-82ee7a43-cde9-4a57-8799-359f34e57bb5.png)

## Rationale

Seeing components by purpose/category in the sidebar would help me quickly navigate instead of having to always come back to the home page.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by alex-page** [comment]
@joelzwarrington we used to have this user experience and it made it difficult for users who were not familiar with the categories. I would actually prefer if the categories didn't exist at all on the /components page and we had better search and filter mechanics to adjust the list. What do you think about that?

**Comment by joelzwarrington** [comment]
@alex-page I can agree that it may be confusing for those not familiar with it. A better search and filters would be much better!

I'll mark this as won't do, and another issue can be created for the better searching! Cheers 🥂
