### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components/icon) Missing icons explorer

### ISSUE THREAD

**Issue by vicvans20** [Shopify/polaris-react#6586]
Cannot find the icon explorer anymore, https://polaris-icons.shopify.com/ is empty and cannot find a replacement anywhere on the new site if any

**Comment by martenbjork** [comment]
Hi! The icons explorer now lives here: https://polaris.shopify.com/icons

Please let us know if the updated icons explorer is missing a feature that was critical to you.

**Comment by alex-page** [comment]
@vicvans20 we set up a redirect to the new icons website. Do you have a screenshot of what you are seeing?

**Comment by vicvans20** [comment]
Sorry for the late reply, everything looks fine now, thanks!
