### ISSUE TITLE
[`withAppProvider.tsx`] add test coverage

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#660]
This file currently has no test coverage, and as a part of the `AppProvider`, is critical to Polaris functionality. Let's add test coverage to [`withAppProvider.tsx`](https://github.com/Shopify/polaris-react/blob/f506e8f27e5faccbeb67cd75827c53e094217f19/src/components/AppProvider/utilities/withAppProvider/withAppProvider.tsx).

**Comment by danrosenthal** [comment]
Related to #524

**Comment by yourpalsonja** [comment]
@danrosenthal can this ticket be closed, since App Bridge is moving out of the Polaris repo?

**Comment by danrosenthal** [comment]
While art of this HOC's responsibility is sharing AppBridge through context, it is not its only purpose. The code coverage of this Higher Order Component is also still not where we'd like it to be, so this should remain open. 

For more on the coverage: https://codecov.io/gh/Shopify/polaris-react/src/master/src/components/AppProvider/utilities/withAppProvider/withAppProvider.tsx

**Comment by danrosenthal** [comment]
This can now be closed as v4 brings coverage to 100%: https://codecov.io/gh/Shopify/polaris-react/src/master/src/utilities/with-app-provider.tsx
