### ISSUE TITLE
[IndexTable] Inconsistent scroll bar behavior

### ISSUE THREAD

**Issue by 666-arch** [Shopify/polaris-react#6600]
> When there are too many list headers, a scroll bar appears, but at this time, the scroll bar scrolls to the far right and cannot display the remaining column pages. But when I press and hold F12 Browser Check, it displays normally, weird?

![image](https://user-images.githubusercontent.com/65932450/178419878-fee1f711-483b-433c-b7dd-8a459aeb33ca.png)
![image](https://user-images.githubusercontent.com/65932450/178420013-fa40d93f-0a9b-4135-b7b7-940f5086c3a8.png)

**Comment by martenbjork** [comment]
Hi! I understand your frustration — it's not great that the actions disappear.

When you file an issue, could you please take a few minutes to write a good title and description? That makes it easier for the team to understand your issue and take action. 

When you create an issue, we provide these issue templates:

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/875708/178421097-299247f1-e4bf-4639-8042-561093915609.png">

Thank you! 🙌

**Comment by 666-arch** [comment]
> 理解
IndexTable When there are too many list headers, a scroll bar appears, but at this time, the scroll bar scrolls to the far right and cannot display the remaining column pages. But when I press and hold F12 Browser Check, it displays normally, weird?

**Comment by 666-arch** [comment]
> Hi! I understand your frustration — it's not great that the actions disappear.
> 
> When you file an issue, could you please take a few minutes to write a good title and description? That makes it easier for the team to understand your issue and take action.
> 
> When you create an issue, we provide these issue templates:
> 
> <img alt="image" width="1281" src="https://user-images.githubusercontent.com/875708/178421097-299247f1-e4bf-4639-8042-561093915609.png">
> 
> Thank you! 🙌

IndexTable When there are too many list headers, a scroll bar appears, but at this time, the scroll bar scrolls to the far right and cannot display the remaining column pages. But when I press and hold F12 Browser Check, it displays normally, weird?

**Comment by 666-arch** [comment]
> Hi! I understand your frustration — it's not great that the actions disappear.
> 
> When you file an issue, could you please take a few minutes to write a good title and description? That makes it easier for the team to understand your issue and take action.
> 
> When you create an issue, we provide these issue templates:
> 
> <img alt="image" width="1281" src="https://user-images.githubusercontent.com/875708/178421097-299247f1-e4bf-4639-8042-561093915609.png">
> 
> Thank you! 🙌

do you have a solution？

**Comment by jesstelford** [comment]
@666-arch Are you able to provide a reproduction using the Polaris Sandbox? [Here's one to get you started](https://polaris.shopify.com/sandbox?code=N4Igxg9gJgpiBcIAETIDsDOAXVBXbEAtjAE4ZIC8SA2gDpoorD2OMCWU8SA5AMwAsARkHcANC1ZJcJADZduAYjETWaAIbF5AWTVskAKRiE2GCGmUNJMiGDVY2Z%2BQBEYtrNNFIAqgGUAghaSSBAksGRcAEwADOKWrBoQuGhYPgAOMMnyACQRovxRUYGS2Hb48gDCJDB2MFBFrGAAFmpoaDByPAAKEGzJwQBmSD5qMjD1jKlqAJ7EyT5YpRjyAEow-UmwdbFB6zL9bDIysykL7ks8AGK4ewejWypIAL7bjMxx7Jw8EQCsAGwiL1Y0g6inGKHUmh4AFFDhkkAB5JoQNRgpDWNwONDyAAyEHIfjQAHN2jAMJ5fAFAYwQmFzrwYg8UAkkil0pkeFlBPlUSUzhUqjV7u8UE0Wm0QfC0DJejAhlgQmMqShJjMMidFvJOrohTtrvtDsd5hqeF40Lt9Xdxs8JABdADcEnQ2CQVVM0jAMAAchpZVQ3qwML1Cdc1CR5GB8PLiCRxqkZNIRuHI0RSBgio8HZYnThgBgSWAsLVVm6SB6yUgRjJi4lS6SfPnC1BPM00FBRvXRgXMeUW8THpQHvgYABJVswAAe1fdMCNhYAFBGCNGMABKTMiszOkgQADuOhIAGtcKlKHgl6mAHSENSpOcPO-CpD%2BoJIDhKxgQmDvlDouyY7-BKEqYAcycxslgAG8vgAGiq07QASqhqnNBjKMOatxIYs77Wo%2BvSwOOVIrpQAB8SAPkEAA8o74QAKmoABGowXssu6oSgHAUMAHCPGxSAHjAUycdxvF5p2jacaJriNlOtYYBevRgPGsAYHOHArjxj7KnibD2GYQljuOGlBMRvFUQZdGMTAF7lO0MgmZpjAUTRE44P0ZhYAA6jAbCEo0WAULQID0RAMhQIFFYYAFIAYJMaCBfZL6SMAn5GYlSAUQA9M545YAlL6ZdRE4WUxNmHHllGFeOxVWaVdnAL%2BuloI8BXmQxJW2eVkhmbRbU1R1vEoE5LkRVFMUtOFIw%2BWgxxRRkYXIGguDRmwYCdYlwA0qmqWJZl2W5aZGWVdV1n9Q53VFb1J1lQN6V7SNgVjXFyCTYS01qrNrbhYty2rTdTCgayarbflWUuWtjmHa1llXXZplHZdtXEbmyEYM1kM9dDiNw1D7VlcAsHimj8OY6dO3E7jdWIWqs74ETON9ddZ3kwzdXoQa1Mo3TGMU%2BDLXc1ZLE7p1K4vGu9ASFU7gkAw5GOdiMCEmoYBTOUoZQLzzO8a6NYet6xCcdr056zAwOsDpRjlIkyScYuUaXqMRJYI0puMJJBa1MOhaEBglsspxN2VjJZYdlJtRIAA-DwfiHNwSBcG70mkjrpIXg7hJO7xLsoGYIddmYPYtMSnEtm2M4Nt2vYm7xjTVFAQaRcAdAOUw9hYKM8jG9wOFpU%2BrftzwuIYmYXcAUwf0VtKr3HPIc2okEHDyJtJAALSQCyc%2BSH3MDyPCQEkKgVtYBvKDd2lz49y9b3stws%2Bjx88gA8vMVqsfjBb-IfiEIfSDP8kr%2Bn%2Btd%2BPAaZpgAS%2BYAQDuAFzgjIEeN0IE6X7twLUqo%2BhQVAXfBBbdt6XD1BhNUP8UZwIcjaLOaI1DYEtvGQgaB5grQPFMVC4MmDbj3KGI8qQXZ8wupZTqmV5aK2VqrUIeU1wgFECAJ2RhSQIGoCAX87cMggBtBIncHAnYYFkaQoAA) - I was unable to see the described behaviour unfortunately.
