### ISSUE TITLE
Polaris migrations platform

### ISSUE THREAD

**Issue by sam-b-rose** [Shopify/polaris-react#6614]
> 🛠️ Tooling to automate breaking changes and increase mainline adoption

## Problem

Mainline coverage for custom components in Shopify/web is at 29% and is negatively affected by [deprecated Sass functions](https://github.com/Shopify/web/blob/main/app/styles/legacy-polaris-v8-public-api.scss) that we added to unblock shipping v9. Shopify and third-party developers need tooling to apply feature and deprecation migrations between major versions.

Manual token and component updates are tedious and prone to error–[documentation tables](https://github.com/Shopify/polaris/blob/main/documentation/guides/migrating-from-v8-to-v9.md#spacing) are not a sufficient solution. Building a new migration platform would assist with large-scale, automated codebase refactors to ensure migration accuracy. This would remove tedious manual work and improve our overall speed and thoroughness when making system-wide updates or breaking changes. Providing this tooling would increase coverage and adherence to mainline.

## Outcomes

* 5% increase to mainline coverage
* 30% (15 to 40%) increase coverage of custom component tokens
* Start removing some of the [legacy-polaris-v8-public-api.scss](https://github.com/Shopify/web/blob/main/app/styles/legacy-polaris-v8-public-api.scss) from Shopify/web
* Create a new migration tool that will allow us to author and apply migrations (npm package [@shopify/polaris-migrator](https://github.com/Shopify/polaris/pull/5806) or @shopify/polaris-codemod)
Establish migration documentation on polaris.shopify.com ([Next.js docs example](https://nextjs.org/docs/advanced-features/codemods))
* Future migrations can build upon the patterns created
* Potentially unblock the usage of @shopify/polaris-stylelint in Shopify/web

## Create the platform

- [x] #6943
- [x] Test prototype in Shopify/web on `spacing` Sass function migration
- [x] Test prototype in Shopify/web on `Text` component migration
- [x] #7166 
- [ ] #7030

## Migrations

- [x] #7264 
- [x] #7342
- [x] #7310
- [x] #7264
- [x] #7216
- [x] #7153
- [x] #7375 
- [x] #7335
- [x] #7387
- [x] #7403
- [x] #7475
- [x] #7476
- [x] #7477
- [x] #6588]

**Comment by BPScott** [comment]
Is this for the `web` codebase only or is the idea to scale to other consumers of polaris too?


If it is just for web - or even if it is starting in web - , I wonder if placing this tooling in the web repo's tooling folder, would shorten testing and feedback loops - removing the need to perform snapit releases for testing.  Once the code is proven in the web, general-purpose aspects could be pulled out into the polaris monorepo.

**Comment by sam-b-rose** [comment]
> Is this for the web codebase only or is the idea to scale to other consumers of polaris too?

This will intended for all Polaris consumers! I do like the idea of possibly creating a prototype in web. Are there any smaller repos that would be another good testing ground?

**Comment by alex-page** [comment]
@samrose3 the platform is built, going to make issues for the docs on polaris.shopify.com
