### ISSUE TITLE
[`StickyManager.ts`] add test coverage

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#662]
This file currently has no test coverage, and as a part of the `AppProvider`, is critical to Polaris functionality. Let's add test coverage to [`StickyManager.ts`](https://github.com/Shopify/polaris-react/blob/f506e8f27e5faccbeb67cd75827c53e094217f19/src/components/AppProvider/utilities/withSticky/StickyManager.ts).

**Comment by danrosenthal** [comment]
Related to #524

**Comment by danrosenthal** [comment]
This pretty urgently needs code coverage, as it's currently at 27.17% 😢 

https://codecov.io/gh/Shopify/polaris-react/src/master/src/components/AppProvider/utilities/withSticky/StickyManager.ts

cc: @dleroux @AndrewMusgrave

**Comment by dleroux** [comment]
The issue I was having when building this was the lack of window scrolling tests. I dont think much has changed on that front.

**Comment by AndrewMusgrave** [comment]
> The issue I was having when building this was the lack of window scrolling tests. I dont think much has changed on that front. However I don't think we had Percy setup properly at the time, I wonder if they offer something that would allow for this.

Could we mock our position on the page, then when the component renders it'll be in the scrolled position?

**Comment by dleroux** [comment]
Maybe? At the time this was implemented we weren't able to for some reason.
