### ISSUE TITLE
[polaris.shopify.com] Documentation is missing

### ISSUE THREAD

**Issue by teknolog2000** [Shopify/polaris-react#6624]
What happened to the refernce documentation? The only pages I can find are now the useless ones on polaris.shopify.com. Accoring to them [TextField has no properties](https://polaris.shopify.com/components/text-field). Where's the real documentation?

**Comment by martenbjork** [comment]
Hi / hej Sebastian! 👋 Could you specify what why you think they are "useless"? It would help us improve them.

As for the "TextField has no properties" bit: We know, we'll be fixing that soon. We shipped the PR to add the props 2 days ago, knowing it had this flaw:

> The script assumes that props are defined using an interface called ComponentNameProps. Some components, like Avatar, uses other constructs (like union types) to define the props. The script can't yet parse these.

We intend on fixing this shortly.

**Comment by alex-page** [comment]
Closing this as it's a duplicate of https://github.com/Shopify/polaris/issues/6599

**Comment by teknolog2000** [comment]
@alex-page well step one is having property documentation. I seem to remember there used to be code examples too, and much better formatting. Right now it's just a wall of text.

Why was the old good documentation from shopify.dev removed?

**Comment by martenbjork** [comment]
>  I seem to remember there used to be code examples too

Code examples are available here. Did you not find it or are they not working for you?

<img width="701" alt="image" src="https://user-images.githubusercontent.com/875708/178771980-fb94138b-915a-43ab-817b-f9a96506b7a5.png">
