### ISSUE TITLE
Dependency versions should be explicit

### ISSUE THREAD

**Issue by aaronadamsCA** [Shopify/polaris-react#6666]
## Issue summary

We're getting this error:

```
Attempted import error: 'getMediaConditions' is not exported from '@shopify/polaris-tokens' (imported as 'getMediaConditions').
warning ../../node_modules/@shopify/polaris/build/esm/utilities/breakpoints.js
```

`@shopify/polaris` v9.20.0 is trying to import `getMediaConditions` from `@shopify/polaris-tokens@npm:5.4.0`, but this export has only existed since v5.5.0.

## Expected behavior

`@shopify/polaris` v9.20.0 should have shipped with a dependency on `@shopify/polaris-tokens` v5.5.0 or newer. This is the only signal to a package manager that the transitive dependency needs to be upgraded.

## Actual behavior

https://github.com/Shopify/polaris/blob/b3e027c9b45fa44d1137fd409b2f8a10687c90ef/polaris-react/package.json#L65-L67

## Steps to reproduce the problem

I can provide a test case if needed, but given this is a pretty obvious gap, I'm hoping you'll just accept the report as-is.

In the meantime we can work around this by directly installing and upgrading `@shopify/polaris-tokens` (and `@shopify/polaris-icons`) ourselves.

**Comment by sam-b-rose** [comment]
Thanks for catching this issue, @aaronadamsCA! Working on a fix now. 🔧

**Comment by aaronadamsCA** [comment]
Thank you for the quick fix!
