### ISSUE TITLE
AppProvider should not render children before redirecting to Shopify admin

### ISSUE THREAD

**Issue by aianus** [Shopify/polaris-react#667]
# Issue summary

AppProvider should not mount/render children before redirecting to Shopify admin

## Expected behavior

When the embedded app is accessed directly (not in an iFrame on Shopify), I expect the AppProvider to force the redirect to Shopify before/instead of rendering its children.

## Actual behavior

AppProvider mounts and renders its children and app bridge later or asynchronously redirects to the embedded iFrame in Shopify Admin. This causes unnecessary duplicate API requests to Shopify and ugly flickering to occur while the application renders before the redirect.

## Steps to reproduce the problem

1. Visit an embedded Shopify App directly (not through Shopify Admin) that is wrapped in an AppProvider component that has forceRedirect={true}
1. Observe flickering and duplicate API requests as it mounts/renders the whole application twice
1.

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 3.1.1
- Browser: Chrome 70.0.3538.102
- Device: Macbook Pro 13'' Late 2013
- Operating System: Mac OS X: 10.14.1

I think it applies to all browsers/devices/operating systems.

**Comment by AndrewMusgrave** [comment]
cc/ @tmlayton Do you have any context on this?

**Comment by aianus** [comment]
Was that a question for me or for @tmlayton ?

**Comment by tmlayton** [comment]
Thanks for the issue @aianus, I will take a look. We are also getting reports that App Bridge is not successfully redirecting even though `forceRedirect` is passed straight though to App Bridge. While it would appear to be an issue on the App Bridge end, it’s possible this is related.

**Comment by chloerice** [comment]
> Was that a question for me or for @tmlayton ?

(for @tmlayton 😊)

**Comment by tmlayton** [comment]
@aianus `forceRedirect` is a concern of App Bridge. We wrap app bridge simply as a matter of convenience for calling APIs to render title bar, modal, toast message, loading bar, and resource picker. I am looking at removing app bridge from Polaris entirely so this is something we likely won’t fix.
