### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components)

### ISSUE THREAD

**Issue by SomeBrujah** [Shopify/polaris-react#6710]
Please, add variants for components props!)

**Comment by martenbjork** [comment]
Hi! Just to be 110% clear about what we're talking about, could you elaborate on this request?

**Comment by SomeBrujah** [comment]
> Hi! Just to be 110% clear about what we're talking about, could you elaborate on this request?

Of course.In the old version of the site, component properties also had value options. In the new version of the site, this is not the case.
Now I'll show you what I mean.
![image](https://user-images.githubusercontent.com/47982319/180400096-8bd08e96-2425-4305-9a47-c030ce2f3c61.png)

**Comment by martenbjork** [comment]
Thanks! Got it! I got another PR almost ready that will add this. I hope to ship it early next week!

Four housekeeping purposes, I'll close this issue since we're tracking this feature in here: #6599
