### ISSUE TITLE
403 status code when calling figma styles

### ISSUE THREAD

**Issue by SimonLeclercq** [Shopify/polaris-react#6723]
## Issue summary
Status code: 🔴 403 when I need to get figma's style ID

## Expected behavior

When I click on `fix`, I would like selected fill color to be replaced by a remote figma style (from [polaris's color library](https://www.figma.com/community/file/1111359207966840858) available on figma's community)

## Actual behavior
Actually, nothing happen on Figma, because (_I guess_) figma's style ID is call from the shopify figma's environment, and not from an open library / environment

 
<img width="1912" alt="get   403 status" src="https://user-images.githubusercontent.com/50582328/180307753-99c3ebc4-880b-487e-8719-2c2526503dab.png">

## Steps to reproduce the problem

1. First step: run polaris-for-figma plugin
1. Second step: design random shape with random color
1. Third step: scan document and select a shape to fix
1. Forth step: click on "fix"

For more detail you can open console from inspector

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).
