### ISSUE TITLE
Documentation Versioning

### ISSUE THREAD

**Issue by hakimihamdan88** [Shopify/polaris-react#673]
how do I access Polaris documentation for version 2? can we have something like this

- https://polaris.shopify.com/3.1
- https://polaris.shopify.com/2.12

**Comment by danrosenthal** [comment]
As with all feature requests, we'll close this issue and folks to express their interest in this feature by adding a 👍 to the original issue comment. While this isn't a guarantee we will implement the feature, it does help us evaluate demand for a specific feature, and prioritize accordingly.

In the mean time, we encourage you to run `git checkout tags/v2.12.1` in a local instance of the Polaris react library. You will then be able to access any docs that were available then in the relevant component `README.md`, and prop documentation inline on the component.
