### ISSUE TITLE
Screenshot link broken in ResourcePicker markdown

### ISSUE THREAD

**Issue by joshiefishbein** [Shopify/polaris-react#675]
# Issue summary

https://github.com/Shopify/polaris-react/tree/master/src/components/ResourcePicker

Looks like the screenshot link is broken in component documentation for the ResourcePicker component. Definitely a low priority issue, but I wanted to use this as an opportunity to say I love the idea of having screenshots of an average use case for the component. It would make this a more browsable reference for when I'm building my UIs!

## Expected behavior

The screenshot to render inline.

## Actual behavior

404 resolves for the image that appears to be hosted on Github.

## Steps to reproduce the problem

1. Click the link above
2. Scroll down to the "Screenshot" section
3. Observe the issue

## Specifications

- Browser: Chrome
- Device: MBP "15 2016

**Comment by danrosenthal** [comment]
Thanks for the issue @joshiefishbein. As it happens, I'm actually working on pull request right now that will improve these docs (#653). I'll be sure to fix this link as part of those changes.

**Comment by kaelig** [comment]
Superseded by https://github.com/Shopify/polaris-react/issues/684
