### ISSUE TITLE
Set z-index of overlay component

### ISSUE THREAD

**Issue by BlazingBBQ** [Shopify/polaris-react#677]
# Feature request summary
Allow overlay components (Popover, tooltip, etc.) to recieve a `zIndex` prop. 

## Rationale
Should allow developers to set zIndex of overlay's in the case where two overlays overlap. 

<img width="739" alt="screen shot 2018-11-26 at 10 06 22 am" src="https://user-images.githubusercontent.com/7542789/49023800-06edb500-f166-11e8-9a81-fa2ef1df9eb2.png">
<img width="737" alt="screen shot 2018-11-26 at 10 09 58 am" src="https://user-images.githubusercontent.com/7542789/49023801-06edb500-f166-11e8-9347-9b4ff7a7e61c.png">

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by danrosenthal** [comment]
Closing this per our approach to feature requests, though this seems like an edge case we should definitely support. If folks want to show their support for this issue, please upvote with a 👍  so we can prioritize it appropriately.

**Comment by BPScott** [comment]
I don't think this should be user configurable. Instead we should fix this by default by increasing the z-index on tooltips so they sit on top of popovers.
