### ISSUE TITLE
Add consumer build test

### ISSUE THREAD

**Issue by kvendrik** [Shopify/polaris-react#678]
Currently we don't test the consumer build process and the validity of its output in CI which has led to several issues. It would be great if we would be able to create a test that validates the consumer build cc @dleroux @amrocha.

Some of the issues that would have been caught by this:
- https://github.com/Shopify/polaris-react-deprecated/pull/2411
- https://github.com/Shopify/polaris-react/pull/679
- https://github.com/Shopify/polaris-react/pull/938

Moved from https://github.com/Shopify/polaris-react-deprecated/issues/2413

**Comment by kvendrik** [comment]
example: https://github.com/Shopify/polaris-react/pull/679

**Comment by kvendrik** [comment]
Note: https://github.com/Shopify/polaris-react/pull/525 adds a [test](https://github.com/Shopify/polaris-react/pull/525/files#diff-8c83bf9e708453375e9d5806c53b58ddR85) that makes sure the generated type definitions are valid.

**Comment by chloerice** [comment]
This was implemented by @amrocha in #931
