### ISSUE TITLE
Viewport height can make popover unusable

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react#682]
# Issue summary

Here, I used my inspector docked to bottom of window to make a very short viewport height

<img width="373" alt="screen shot 2018-11-22 at 1 05 26 pm" src="https://user-images.githubusercontent.com/150352/48917924-69d60800-ee57-11e8-8636-a0856d198a90.png">

Short viewport height can cause the popover to assume it's better to render `up` than `down`
However, the bar at the top occludes it and makes it impossible to read the top item (you can still just barely click it)

<img width="341" alt="screen shot 2018-11-22 at 1 07 23 pm" src="https://user-images.githubusercontent.com/150352/48917957-938f2f00-ee57-11e8-8980-6d86709ededd.png">
Here, the top-most element is entirely unreadable

## Expected behavior

The popover should overlay the topbar in this situation

## Steps to reproduce the problem

1. Go to a page in the admin that's using Resource list with filtering i.e. order index
1. Make a selection of one or more items in the list
1. Shrink the height of the page and open the actions popover

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.0.0
- Browser: Chrome
- Device: MacBook
- Operating System: Mojave

**Comment by BPScott** [comment]
Tangentally related if you pick this up and start to review z-index ordering: #677 is a bug where popovers occlude tooltips.
