### ISSUE TITLE
Failing tests due to timezone issue

### ISSUE THREAD

**Issue by andrewpye** [Shopify/polaris-react#688]
# Issue summary
Running tests for `ResourceList`'s `DateSelector` component results in two failures:

![image](https://user-images.githubusercontent.com/5737342/49153504-91791480-f31e-11e8-941d-9050a3d5fa2d.png)

I'm guessing this is due to timezones (I'm on Eastern European Time/UTC+2) as we've seen a similar issue with our own internal date picker recently for timezones that are ahead of UTC 😬 

## Expected behavior
`DateSelector` tests should pass in all timezones.

## Actual behavior
`DateSelector` tests fail in UTC+2 timezone (and possibly other timezones that are ahead of UTC).

## Steps to reproduce the problem
Run tests with system set to UTC+2 timezone.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.1.1
- Browser: N/A
- Device: N/A
- Operating System: N/A

**Comment by lemonmade** [comment]
We have a library that can help with this: https://github.com/Shopify/quilt/tree/master/packages/jest-dom-mocks#clockmocknow-number--date-void

**Comment by andrewpye** [comment]
@dpersing I'm honestly not sure, I haven't had a chance to look into this (I actually work with Ember.js and was making a port of `ResourceList` when I found the issue). From what I can tell though the mock library won't help, since it doesn't seem to allow setting a time zone. I think this is a legitimate issue though rather than a test setup issue.

**Comment by danrosenthal** [comment]
@andrewpye not sure if it's of interest to you, but a Shopify Partner made an ember port of Polaris: https://github.com/smile-io/ember-polaris

**Comment by andrewpye** [comment]
@danrosenthal I'm actually one of the @smile-io guys behind [`ember-polaris`](https://github.com/smile-io/ember-polaris), that's how I stumbled across this issue 😉Appreciate the heads-up though, and nice to know you guys are aware of us! 🙌

**Comment by BPScott** [comment]
I believe this should be fixed by #710
