### ISSUE TITLE
[Autocomplete][v1] re-architect the underlying combobox component

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#689]
## Mea culpa
Consider this our admission of guilt. We rushed to release the existing `Autocomplete` component without ensuring it was ready for public consumption. In retrospect, our focus was divided and this complex component didn't get the attention it deserved. So we're starting from scratch, rebuilding it to address the myriad performance and testing problems reported about the component.

- https://github.com/Shopify/polaris-react/issues/644
- https://github.com/Shopify/polaris-react/issues/563
- https://github.com/Shopify/polaris-react/issues/499
- https://github.com/Shopify/polaris-react/issues/490
- https://github.com/Shopify/polaris-react/issues/559
- and other undocumented issues like it [lacking the ability to be disabled](https://github.com/Shopify/polaris-react/pull/602), and it [causing accidental form submissions on enter keypress](https://github.com/Shopify/polaris-react/pull/680)

We regret any inconvenience this causes, but from here on out, we will stop working to solve any of these issues, and instead focus on a rebuild of the component. All open PRs related to this component will be closed in favor of this rebuild.

### Technical design
Check out the [technical design doc available here](https://docs.google.com/document/d/1pLXEr0vp9Cp7Kj86oSfKog5uGRRlU0PS4ABHfX1aooM/edit#heading=h.pdg5l3kmo9fl), but please give feedback directly on this issue.

### Tracking
This issue will serve as a tracking and reference point for anyone interested, with updates on progress and links to PRs here. So please subscribe if you are interested.

**Comment by tulinn** [comment]
hey there, can I get an ETA on the new autocomplete component?

**Comment by dleroux** [comment]
I think I will keep the issues open and close them as I squash in the new build.

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.

**Comment by tmlayton** [comment]
Still an issue

**Comment by katdrobnjakovic** [comment]
Hey! Any further updates on this issue? We're seeing this bug creep up in our new feature that is launching in a few weeks https://github.com/Shopify/shopify/issues/229273. I've noticed the original project this issue is in is now closed. Is there a new project I should be following up with? Thanks! 🙂

**Comment by hypercomputer** [comment]
We are also running into this with our newly released signup form: https://github.com/Shopify/shopify/issues/240619

**Comment by plentz** [comment]
Some problems are been fixed in https://github.com/Shopify/web/pull/28197
