### ISSUE TITLE
[TextField] Long prefix crowds and overflows field on mobile screen widths

### ISSUE THREAD

**Issue by maxariss** [Shopify/polaris-react#693]
# Issue summary
If a lengthy value is provided to the TextField's prefix prop, on slim viewports, the prefix (understandably) crowds the input, but also overflows the input.

## Expected behavior
- Perhaps different UX for long prefixes ? (example, urls)
- No overflow outside of the input

## Steps to reproduce the problem
1. Open a collection page
2. Edit the collection's SEO values
3. Shrink the viewport until overflow is visible

### Screenshot from the styleguide
<img width="548" alt="screen shot 2018-11-29 at 1 23 42 pm" src="https://user-images.githubusercontent.com/12142249/49243264-e37f7000-f3da-11e8-9d2d-730b009a25d8.png">

### Screenshot from the admin
<img width="326" alt="screen shot 2018-11-29 at 1 26 52 pm" src="https://user-images.githubusercontent.com/12142249/49243280-eb3f1480-f3da-11e8-8594-f1b106085c87.png">

**Comment by dleroux** [comment]
We should probably do the same as rails component and add overflow hidden here but I'm not sure we should be doing anything the the design. In this case I think prefix might not be the best solution to this problem. @sarahill thoughts on this?
