### ISSUE TITLE
Titlebar formatting

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react#701]
Why is the "by Company ..." a thing. There is plenty of space to just right justify whatever is there and not use the old obnoxious dotdotdot that plagued Shopify Admin oh so many years ago. 

https://www.dropbox.com/s/uh5k7pqxles6npw/Screenshot%202018-11-30%2010.33.31.png?dl=0

I would think by now one could the display of a name without resorting to mangling unless absolutely necessary, ie, someone using a flip phone display to monitor their Shopify store.

## Expected behavior

See my name without dotdotdot mangling in the title bar.

## Actual behavior

Behaviour is mis-spelled in the template for reporting issues. And our company details or name of App developer is mangled with dotdotdot-ism. 

## Steps to reproduce the problem

View an embedded App, err, a Bridged App, err, you get it.

## Reduced test case

Nah. Sent in a screenshot that seems to explore the issue in a crystal clear manner. 

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.1.1
- Browser: modern
- Device: modern
- Operating System: yes.

**Comment by dleroux** [comment]
Thank you for reporting this @resistorsoftware. This actually not a Polaris-react issue per se but I agree with you there's ample room there so I've reported the issue in the proper internal repo.
l'll close this for now and it will be addressed there.

**Comment by iainmcampbell** [comment]
@resistorsoftware Just following up to say that this issue has been resolved. The ellipsis should now only appear at very small screen sizes.
