### ISSUE TITLE
[Sticky] / Should not stick when content height is greater than available screen space

### ISSUE THREAD

**Issue by loic-d** [Shopify/polaris-react#702]
# Issue summary

In cases where the content height of the `Sticky` component is greater than the available screen space, we should remove the sticky effect.

Example of the issue with a `Card` component wrapped by `Sticky`:

<img width="651" alt="screen shot 2018-11-30 at 10 30 16 am" src="https://user-images.githubusercontent.com/3925905/49299144-08ccb680-f48d-11e8-86f7-9fe22f8df776.png">

## Expected behavior

When the sticky content does not fit on the screen, the sticky effect should be removed. This way, the sticky content would not overlap with other content (main page action in this case).

## Actual behavior

When the sticky content does not fit on the screen, the sticky effect is still applied.

## Steps to reproduce the problem
To reproduce you can look at the discounts page. 

1. Enter a long discount code (255 characters max)
2. Scroll down to make the summary card sticky
3. The sticky card overlaps with the main page action button

## Reduced test case

Partial JSX Markup

```
<Layout.Section secondary>
      <Sticky offset disableWhenStacked>
                  Summary card content
      </Sticky>
</Layout.Section>
<Layout.Section>
       <PageActions {...pageActions} />
</Layout.Section>
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: `"@shopify/polaris": "3.1.1"`
- Browser: `Version 70.0.3538.102 (Official Build) (64-bit)`
- Device: Mac OS X
- Operating System: `10.13.6`

**Comment by loic-d** [comment]
This came up again in an internal bug hunt. Is this something you guys plan on tackling soon or should we take care of it?

**Comment by vladucu** [comment]
any thoughts on this?

**Comment by loic-d** [comment]
We should probably remove the sticky effect when the height of the sticky content is bigger than the available space.

**Comment by rabbit0321** [comment]
I have met the same issue too. It also overlaps with contextual save bar even I set offset true to sticky component.
![sticky](https://user-images.githubusercontent.com/14236588/93022624-d158db00-f61c-11ea-866a-ba9696ffbe02.png)
