### ISSUE TITLE
[ResourceList][Firefox] Item keeps the focus state after programmatically clearing the selection

### ISSUE THREAD

**Issue by tleunen** [Shopify/polaris-react#715]
# Issue summary

When the user clicks the checkbox of an item, the focus gets on that line. After clicking away, the focus should disappear but it seems to stay there for Firefox. So when clearing the selection programmatically, the background stays grey instead of going back to white.

![kapture 2018-12-04 at 14 24 07](https://user-images.githubusercontent.com/1972567/49467621-df839180-f7d0-11e8-85f9-0326a964f726.gif)

## Expected behavior

After clearing the selection programmatically, the background of all items should be white.

## Actual behavior

The background of all selected items stays grey

## Steps to reproduce the problem

Go here: https://codesandbox.io/s/mz87zw2lk8

1. On firefox:
1. Select an item
1. Pick an action
1. Notice the checkbox gets unselected and the background is grey

## Reduced test case

https://codesandbox.io/s/mz87zw2lk8

**Comment by ruairiphackett** [comment]
@tleunen I was unable to reproduce in the current version of Firefox `66.0.2`, do you know what version you saw the issue in?

![https://screenshot.click/2019-04-04_16-00-23.gif](https://screenshot.click/2019-04-04_16-00-23.gif)
