### ISSUE TITLE
Color transformation functions (hsbToHex, etc.) not exported anymore

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react#718]
# Issue summary

Importing `hsbToHex` and other color transformation functions is no longer available at the top-level `@shopify/polaris` package. These are often useful when working with the HSBA-based `ColorPicker` component. It appears to have been removed in commit f0e56546bc37d75f3a70b2c7c63d5e6fb695abe7.

## Expected behavior

The following import used to work:

```
import { hsbToHex } from '@shopify/polaris`;
```

## Actual behavior

As of Polaris 3.2.0, this throws an error saying that `hsbToHex` is not exported from `@shopify/polaris`.

## Steps to reproduce the problem

1. Attempt to import any of the color transformation functions.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.2.0
- Browser: Google Chrome 70.0.3538.110
- Device: MacBook Pro
- Operating System: macOS Mojave 10.14.1

**Comment by mbaumbach** [comment]
I'm not sure if this is considered a breaking change or was never meant to be public API and we should be providing/acquiring our own transformation functions. If it's not meant to be public API, feel free to close. :)

**Comment by danrosenthal** [comment]
Thanks @mbaumbach, and sorry for any trouble. This is indeed fixed in `3.2.1`
