### ISSUE TITLE
[Icon]: New icon Organization

### ISSUE THREAD

**Issue by clarkjennings** [Shopify/polaris-react#7233]
### How will these icons be used?

This icon represents a plus organization/business, to distinguish from individual Shops.

Context examples: 
- in the Store Login page
<img width="357" alt="image" src="https://user-images.githubusercontent.com/98601178/191279146-e0ef9ca0-561c-41e3-a57c-644488d01cfe.png">

- in Settings navigation (for context only, note the icon in this screenshot is an outdated version)
<img width="373" alt="image" src="https://user-images.githubusercontent.com/98601178/191279853-fd4d16c4-8d97-49ca-90ca-331f9597a79d.png">

### Icon name

Organization

### What type of icon set?

Major (20x20)

### Icon description

Used to represent an Organization

### Icon keywords

organization, business

### Icon author

Anna Borg

### Icon SVG code

```shell
<svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M14 5C13.4477 5 13 5.44772 13 6V18C13 18.5523 13.4477 19 14 19H18C18.5523 19 19 18.5523 19 18V6C19 5.44772 18.5523 5 18 5H14ZM16 9H15V11H16V9ZM16 13H15V15H16V13Z" fill="#5C5F62"/>
<rect x="5" y="5" width="2" height="2" fill="#5C5F62"/>
<rect x="5" y="8" width="2" height="2" fill="#5C5F62"/>
<rect x="5" y="11" width="2" height="2" fill="#5C5F62"/>
<rect x="9" y="5" width="2" height="2" fill="#5C5F62"/>
<rect x="9" y="8" width="2" height="2" fill="#5C5F62"/>
<rect x="9" y="11" width="2" height="2" fill="#5C5F62"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M3 17V3H13V17H9V19H14C14.5523 19 15 18.5523 15 18V2C15 1.44772 14.5523 1 14 1H2C1.44772 1 1 1.44772 1 2V18C1 18.5523 1.44772 19 2 19H7V17H3Z" fill="#5C5F62"/>
<path d="M6 19V16C6 15.4477 6.44772 15 7 15H9C9.55228 15 10 15.4477 10 16V19" stroke="#5C5F62" stroke-width="2"/>
</svg>
```

https://github.com/Shopify/polaris/issues/7233#tasklist-block-009b1328-a549-4746-926c-05e2e21617f1

**Comment by torben-nielsen** [comment]
@clarkjennings any word from Polaris yet on this?
