### ISSUE TITLE
Possible erroneous test success for `ResourceList/Item`

### ISSUE THREAD

**Issue by andrewpye** [Shopify/polaris-react#725]
# Issue summary
[This test](https://github.com/Shopify/polaris-react/blob/master/src/components/ResourceList/components/Item/tests/Item.test.tsx#L207) for `ResourceList/Item` passes, but I can't see that it should from tracing the code. It's quite possibly an error in test setup:

- I might be misunderstanding the way these tests are set up (I'm far more familiar with qunit and sinon), but the same `onSelectionChange` stub instances (e.g. in [`mockSelectableContext`](https://github.com/Shopify/polaris-react/blob/master/src/components/ResourceList/components/Item/tests/Item.test.tsx#L35) and [`mockSelectModeContext`](https://github.com/Shopify/polaris-react/blob/master/src/components/ResourceList/components/Item/tests/Item.test.tsx#L43)) seem to potentially be used for all tests in the file instead of creating a new one for each test;
- The test in question sets up the `Provider` with the [`mockSelectableContext`](https://github.com/Shopify/polaris-react/blob/master/src/components/ResourceList/components/Item/tests/Item.test.tsx#L210), but then checks `onSelectionChange` on the [`mockSelectModeContext`](https://github.com/Shopify/polaris-react/blob/master/src/components/ResourceList/components/Item/tests/Item.test.tsx#L221) instead.

## Expected behavior
[This test](https://github.com/Shopify/polaris-react/blob/master/src/components/ResourceList/components/Item/tests/Item.test.tsx#L207) for `ResourceList/Item` should fail, because from the test setup (with `context.selectMode` as `false`)  I can see no way that `context.onSelectionChange` should get called when `Item-Wrapper` is clicked.

## Actual behavior
The test passes.

**Comment by AndrewMusgrave** [comment]
Thanks for raising this issue. It seems the tests aren't running properly, if you add `only` the test runs correctly and fails.

**Comment by andrewpye** [comment]
Ah good catch @AndrewMusgrave, I didn't know you could do that :+1: I guess the erroneous pass is coming from the combination of the two bullet points I left in the issue description then.
