### ISSUE TITLE
Pass through `className` and `style` props

### ISSUE THREAD

**Issue by Introvertuous** [Shopify/polaris-react#726]
# Feature request summary
I feel that most components, at a minimum should provide two props for modifying styling: `className`, and `style`. This is probably something that has come up before, and if so I would certainly appreciate the rationale on not doing this and maybe a discussion on the merits of making components more extensible.

## Rationale
The reason this is useful is because you frequently run into situations where you need to modify the style of a component, and end up wrapping it in an element to achieve this, which is a terrible approach.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by Introvertuous** [comment]
Also, I would certainly be willing to create a PR for this, assuming there is interest from collaborators.

**Comment by danrosenthal** [comment]
@Introvertuous, as with all feature requests, I'm going to close this issue and allow interested folks to express their interest by upvoting with a 👍 on the original comment.

For a bit of background, this is a deliberate decision to not accept `style` or `className` props in our components. Historically, we have incurred a lot of support debt by allowing internal developers to style Polaris components directly. The consequence was typically lots of style regressions any time we changed something about the components folks were styling. This is less problematic for third party apps, but would still likely occur.

I'd be curious to hear what your specific need is. Can you tell me a bit more about what you're trying to style and how?

**Comment by Introvertuous** [comment]
@danrosenthal It is not any one particular use case, it is just a very common need to style the root element of a component. Without passing through those props the user is forced to wrap your component and apply styling to that wrapper. In my opinion this makes for a worse user experience than potential breaking of styles on upgrades. I would certainly incur the risk of style breaking over compromising on code.

**Comment by Skriptach** [comment]
Agree with @Introvertuous. It is a common need to customize components.

**Comment by richardscarrott** [comment]
Yeah a lot of libaries allow this so call sites can add layout properties, e.g. position / margin etc. but agree it means there's more risk for changes to break call sites. For now, we're just wrapping Polaris components with extra components to handle layout, e.g.

```js
<Select className={styles.select} />
```

```js
<div className={styles.select}>
   <Select />
</div>
```

```css
.select {
   margin: 0 0 20px;
}
```

**Comment by giladv** [comment]
with all due respect guys, this is literally the craziest thing not supporting passing className/style. 
i mean, name one mainstream framework not supporting this accept this one? 
common, this is not a feature request, this is design bug.

**Comment by CPerinet** [comment]
Wow — had not realised that. Trying to build a third party app here, well `yarn remove @shopify/polaris`

**Comment by youminkim** [comment]
Bump - it is pretty painful to write test codes without this

**Comment by ChBernat** [comment]
Bump - it's pain.
