### ISSUE TITLE
[Toast] Multiple toasts not working in embedded apps

### ISSUE THREAD

**Issue by mrdja026** [Shopify/polaris-react#728]
# Issue summary

Showing multiple toast notifications on embedded shopify app does not seems to be working

## Expected behavior
Should be able to show multiple toast notifications

## Actual behavior

Only first toast is fired. Tried replicating problem with code provided on the https://polaris.shopify.com/components/feedback-indicators/toast with multiple toasts selected from dropdown. In my App i have something like this (shown below)
https://codesandbox.io/s/7kwq2n2891 (just a preview); and this component is the child of Frame -> Page component also this #652 

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.0.0
- Browser: Google Chrome Version 70.0.3538.110
- Device: Desktop PC
- Operating System: Windows 10 pro

**Comment by dpersing** [comment]
Hi @mrdja026! It seems likely this was related to the issue with `ToastProps` fixed in #722 and pushed as part of [version 3.2.1](https://github.com/Shopify/polaris-react/releases/tag/v3.2.1). Can you verify?

**Comment by tmlayton** [comment]
Hi @mrdja026 thanks for the issue, unfortunately multiple toast messages have never been supported for embedded apps. If you would like to see this supported, please raise an issue in https://ecommerce.shopify.com/c/shopify-apis-and-technology.
