### ISSUE TITLE
[polaris.shopify.com] MobileNav missing StatusBadge

### ISSUE THREAD

**Issue by gil--** [Shopify/polaris-react#7294]
## Issue summary

The mobile nav components list is missing the StatusBadge (such as deprecated or alpha) that the desktop Menu has.

Copy https://github.com/Shopify/polaris/blob/3711739a5a49aa52f25560239fe60f22dc830167/polaris.shopify.com/src/components/Nav/Nav.tsx#L62 to https://github.com/Shopify/polaris/blob/3711739a5a49aa52f25560239fe60f22dc830167/polaris.shopify.com/src/components/MobileNav/MobileNav.tsx#L191

## Expected behavior

Show status of component in mobile nav

## Steps to reproduce the problem

1. Open https://polaris.shopify.com/components on mobile
2. Open menu and see no status badge

**Comment by martenbjork** [comment]
Thanks Gil! 🔥  I'll fix this in #7232 this week!
