### ISSUE TITLE
Contribution docs typos

### ISSUE THREAD

**Issue by jjgali** [Shopify/polaris-react#7298]
## Issue summary

Noticed a couple bugs/typos in our contribution docs:
- In the `Adding new documentation` section of https://polaris.shopify.com/contributing/documentation, the numbered list is broken, presumably by the bulleted list under number 1.
- There is a missing link on the [When to contribute new patterns page](https://polaris.shopify.com/contributing/when-to-contribute-new-patterns): `[contribute the new pattern to the system](insert link to contribution page}` (thanks for reporting @SeanyB!)

**Comment by jared-fanning** [comment]
should the missing link point to: https://polaris.shopify.com/contributing

**Comment by jjgali** [comment]
@jared-fanning I started to do that, but thought getting straight to the documentation contribution page would be more valuable since they're already in the Contribution section. I could go either way on it!
