### ISSUE TITLE
Select Component Clickable Area in Safari 12.0

### ISSUE THREAD

**Issue by davidwoolf** [Shopify/polaris-react#736]
# Issue summary

In Safari 12.0 in macOS Mojave 10.14, the select component's clickable area isn't what you would expect based on the visible borders of the component. 

## Expected behavior

Clicking the Select should open up the options picker with the correct font size.

## Actual behavior

Only the top half of the visible select component is clickable, and the font size is too small.

## Steps to reproduce the problem

1. Add the Select component inside of a React Project
1. Open the project in Safari 12.0
1. Try clicking the bottom half of the visible Select component. Nothing happens

Note: there is an easy fix for this: add -webkit-appearance: none to the actual select input and it will work properly (tested using the inspector console).

## Reduced test case

The sandbox does not reproduce the issue, but I am experiencing it in my own app.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.12.1
- Browser: Safari 12.0
- Device: MacBook Pro (Retina, 13-inch, Mid 2014)
- Operating System: macOS Mojave 10.14

**Comment by markiiikram** [comment]
Hi @davidwoolf, Thanks for the issue. Are you able to upgrade Polaris? I'm running "@shopify/polaris": "^3.1.1", Safari 12.0 on macOS Mojave 10.14 without issue.

![safari-select](https://user-images.githubusercontent.com/3484321/49817305-d8fb9980-fd3d-11e8-8d64-2818618a6456.gif)

**Comment by davidwoolf** [comment]
Sorry for the confusion. I had the latest version of polaris in npm, but the way I have stylesheets setup right now (just starting out setting up a project), they were still on version 2.12.1, which explains a lot. I'm closing this issue and sorry for wasting your time looking into this.

Thanks for pointing out the version discrepancy to me!
