### ISSUE TITLE
[Banner] Long title does not wrap properly

### ISSUE THREAD

**Issue by loic-d** [Shopify/polaris-react#737]
# Issue summary

Long `Banner` `title` does not wrap properly.

<img width="1481" alt="screen shot 2018-12-11 at 3 44 30 pm" src="https://user-images.githubusercontent.com/3925905/49829406-533b1680-fd5c-11e8-8d9c-6d7d6a4e4531.png">

## Expected behavior

Long title should wrap, even if it's one word.

## Actual behavior

Long title does not wrap properly and overflows the `Banner` container.

## Steps to reproduce the problem

1 - Go to the Discounts section in the Admin
2 - Create a new discount code with a long discount code (250 characters for example)
3 - The title in the creation banner overflows

## Reduced test case

```
function CreationBanner({title, action, children}: Props) {
  return (
    <Banner title={title} status="success" action={action}>
      {children}
    </Banner>
  );
}
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: `"@shopify/polaris": "3.1.1",`
- Browser: Chrome `Version 70.0.3538.110 (Official Build) (64-bit)`
- Device: Mac OS X
- Operating System: `10.13.6`

**Comment by loic-d** [comment]
Suggested fix:
Apply `word-break: break-word;` on `.Polaris-Heading`

<img width="1433" alt="screen shot 2018-12-11 at 3 55 29 pm" src="https://user-images.githubusercontent.com/3925905/49829735-33f0b900-fd5d-11e8-884a-b51bf65350bc.png">

**Comment by BPScott** [comment]
From #771 it sounds like this is working as we intend, and long words should not be broken.

@paulstairmand can you offer any guidance?

**Comment by chloerice** [comment]
I've been trying to find a way that this won't cause weirdness, but adding `word-break: break-word` to the banner text can result in some strange wrapping.

<img width="899" alt="screen shot 2018-12-12 at 12 29 48 pm" src="https://user-images.githubusercontent.com/18447883/50110674-b0691900-01ef-11e9-8223-775109c9f800.png">

 Given that the case where this comes up is extremely long discount codes that are at this time come at the beginning of the sentence, the case in the screenshot above shouldn't come up. But if anyone knows of another way to fix this I'll ship that instead.
