### ISSUE TITLE
ResourcePicker not working

### ISSUE THREAD

**Issue by AKarmanov** [Shopify/polaris-react#739]
# Issue summary

ResourcePicker doesn't open up. It is completely ignored, no errors or anything strange in the console.

## Expected behavior

I should see ResourcePicker when I have this code and state.open is set to true: 

`render() {

    const { shopOrigin, apiKey } = window;
    return (
      <AppProvider apiKey={ apiKey }>
        <ResourcePicker
          resourceType="Product"
          open={this.state.open}
          showHidden
          allowMultiple={ false }
          showVariants
          onSelection={({selection}) => {
            console.log('Selected products: ', selection);
            this.setState({open: false});
          }}
          onCancel={() => this.setState({open: false})}
        />
      </AppProvider>
    );
  }`

## Actual behavior

I can see that the state is changing but the picker never shows up :( I can also see that graphql requests are made and the app seems to be authenticated ok.

I can see that the issue was there before and was supposed to be fixed but unfortunately I have no luck with this component. Should I do something specific to make it work?

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 3.2.1
- Browser: Chrome
- Device: iMac
- Operating System: Ubuntu 18.x.x

**Comment by junaid33** [comment]
Facing the same issue with the product picker component. I'm using Next.js which is SSR and I think the AppProvider component or the Shopify App bridge does not work with SSR yet. I think we may have to make the product picker using graphQL and the ResourceList component.

**Comment by AKarmanov** [comment]
For me the issue is not even SSR related, it simply doesn't work, it worked for version 2.x.x but stopped working for 3.2.1

**Comment by AKarmanov** [comment]
After debugging I can tell that this command 

`this.appBridgeResourcePicker.dispatch(ResourcePicker.Action.OPEN);`

is executed but picker doesn't show up.

 Any ideas why? Anybody?

**Comment by AKarmanov** [comment]
Yes, I am using ngrok, in context, I can see all them shopify menus on the left etc.

**Comment by junaid33** [comment]
Yep maybe the issue isn't SSR, but I am also using ngrok and embedded app is turned on in the partner dashboard.

**Comment by AKarmanov** [comment]
Ok, so I have steps to reproduce this issue in an accessible way. I did a quick modification of shopify node app to use polaris 3.3.0 and resource picker component. You can access it here: [https://github.com/AKarmanov/shopify-resource-picker](https://github.com/AKarmanov/shopify-resource-picker) Build instructions are in the readme. 

Let me know if this type of overly simplistic setup works for anybody (you won't need redis or anything like that). I just can get resource picker to display, old (2.x.x) resource picker was showing up fine.

**Comment by AKarmanov** [comment]
Got it working now, the issue was that my app was loading a script that was breaking things.

**Comment by Kcin1993** [comment]
Any idea about this issue?

I start this tutorial Build a [Shopify app with Node and React](https://help.shopify.com/en/api/tutorials/build-a-shopify-app-with-node-and-react). Meet the same issue

**Comment by Kcin1993** [comment]
Apologize for my above commented.

If someone follow this [Shopify app with Node and React](https://help.shopify.com/en/api/tutorials/build-a-shopify-app-with-node-and-react).

In the chapter [Build your user interface with Polaris](https://help.shopify.com/en/api/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris) mentions that

```
...
      <React.Fragment>
        <Head>
          <title>Sample App</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta charSet="utf-8" />
        </Head>
-       <AppProvider>
+       <AppProvider shopOrigin={this.state.shopOrigin} apiKey={API_KEY} forceRedirect>
          <Component {...pageProps} />
        </AppProvider>
      </React.Fragment>
...
```

The props in <AppProvider> Tag `apiKey={API_KEY}`. `API_KEY` had defined in next.config.js so API_KEY can be used directly.

**Comment by ashok-essence** [comment]
in my case it was http link of the ngrok , if you are using http link of ngrok then change it to https , this also causes issue.

**Comment by nickjuntilla** [comment]
This is still an issue for me. I tried app bridge first and now polaris resource picker and I can't get it to show up. There are no errors. My providers is set. It's just nothing shows up.

**Comment by arhumalihaider** [comment]
> This is still an issue for me. I tried app bridge first and now polaris resource picker and I can't get it to show up. There are no errors. My providers is set. It's just nothing shows up.
i hope you found any solution. if yes then please share that with me .thanks

**Comment by arhumalihaider** [comment]
@nickjuntilla  did you find any solution?

**Comment by nickatrokit** [comment]
@arhumalihaider My solution was that shopify only allows one white listed domain at a time so I had to us nginx to map both my back end and front end dev to the same proxy server. Then I was able to point ngrok to that server for https. It would really help if shopify had some kind of error or allowed more dev servers. It's really a nightmare to develop.

**Comment by OzzyTheGiant** [comment]
This is still an issue as of June 2021. Tried switching between October20, April21, and July21 APIs and none of them allow me to use ResourcePicker. There's no error output, nothing.

**Comment by ahurlburt** [comment]
for anyone that comes across this try ensuring that you are setting the host param correctly when you are initiating app bridge config, i had an incorrect host and the app was working but the resource picker wasn't showing (no errors in console, etc). I'm using app bridge v2.0.5

**Comment by gonzacaminos** [comment]
A quick note for anyone that might be facing this: Check the domain you're using on the admin.

Shopify is migrating to new domans: **https://XXX.myshopify.com/** -> **https://admin.shopify.com/store/XXX/**

Admin defaults to **https://admin.shopify.com/store/XXX/** but your app might be using the **.myshopify.com** equivalent, if so your app will fail to work properly on your new domain.

- Change your legacy domain to your new domain your app config.
- Use your legacy url as:https://STORE.myshopify.com/admin/apps/APP_NAME?force_legacy_domain=1

The ResourcePicker was failing without an error so this was really difficult to troubleshoot.
