### ISSUE TITLE
DropZone height is not respected

### ISSUE THREAD

**Issue by asalisbury** [Shopify/polaris-react#742]
# Issue summary

The [`<DropZone />`](https://polaris.shopify.com/components/actions/drop-zone) determines its size (height and width) based on width only. This makes certain valid use cases, where the default `DropZone` height isn't appropriate, impossible. For instance, this one:

<img width="450" src="https://user-images.githubusercontent.com/916549/49893115-ab375300-fe18-11e8-9fb5-09dc83a407d3.png" />

`DropZone` is configurable to work at various sizes, however. For example:

**Default**
<img width="450" src="https://user-images.githubusercontent.com/916549/49892477-12ec9e80-fe17-11e8-8058-976d06863bda.png">

**50 height, 50 width**
<img width="450" alt="screen shot 2018-12-12 at 2 06 50 pm" src="https://user-images.githubusercontent.com/916549/49892565-462f2d80-fe17-11e8-82f0-2feb35af79f9.png">

So far, so good. Until...

**50 height, unspecified width**
<img width="450" alt="screen shot 2018-12-12 at 2 08 19 pm" src="https://user-images.githubusercontent.com/916549/49892625-6c54cd80-fe17-11e8-9ff8-cd3495777aee.png">

## Expected behavior

I would expect something more like:

**50 height, unspecified width**
<img width="450" alt="screen shot 2018-12-12 at 2 12 07 pm" src="https://user-images.githubusercontent.com/916549/49892830-f0a75080-fe17-11e8-9c2e-c01664711498.png">

## Actual behavior

**50 height, unspecified width**
<img width="450" alt="screen shot 2018-12-12 at 2 08 19 pm" src="https://user-images.githubusercontent.com/916549/49892625-6c54cd80-fe17-11e8-9ff8-cd3495777aee.png">

Notice that the DropZone is cut off at the bottom. That is because it actually returns to its default size (shown above).

## Steps to reproduce the problem

1. Go to https://polaris.shopify.com/components/actions/drop-zone
2. Paste this code: `<div style={{height: 50}}><DropZone /></div>`

## Specifications

- Are you using the React components? (Y):
- Polaris version number: latest
- Browser: All
- Device: All
- Operating System: All

**Comment by marisveide** [comment]
This bug is not fixed - still the DropZone doesn't respect the given height of the wrapper div.
Is this working for anybody?

**Comment by asalisbury** [comment]
Looks like #1138 is under review. This should probably be reopened until that PR merges. Does that sound right, @elizabethletourneau?

**Comment by elizabethletourneau** [comment]
Yes, I’ll open this now.

**Comment by marisveide** [comment]
Thanks so much!

**Comment by BerkiAttila** [comment]
Is there an update on this issue? We ran into a similar problem, the height of the DropZone is not calculated correctly.
