### ISSUE TITLE
Make Polaris fully themeable

### ISSUE THREAD

**Issue by kvendrik** [Shopify/polaris-react#744]
# Feature request summary
I think the first step would be to make the colours more theme-able, this by itself already poses certain challenges:

1. How does the interface to theme a component work? (we have one in place but it might be good to review if this is the way we want to do it for everything)
2. Where do we store a component's default colours and its types?
3. What is our recommended way of storing and inserting those colours? Should we find a way to export them from our SCSS somehow? Or is hardcoding them into JS good enough?

## Rationale
The Polaris functionality is amazing. What if third-parties could use our awesome components and also have it align with their own branding.

## Notes
- I know @dfmcphee explored this at some point so he might have some thoughts.
- I mocked up some quick [tech design ideas](https://gist.github.com/kvendrik/a0163898d34285d4212aa8ab0db8de69) yesterday which might be useful for inspiration.

**Comment by dfmcphee** [comment]
I had started exploring this in [this branch](https://github.com/Shopify/polaris-react/compare/color-themes?expand=1). Feel free to use as inspiration or a starting point if you want.

**Comment by danrosenthal** [comment]
Closing in favor of #1593
