### ISSUE TITLE
Replace `focus-ring` mixin with simplification

### ISSUE THREAD

**Issue by sam-b-rose** [Shopify/polaris-react#7475]
The current `@include focus-ring` mixin adds a lot of unnecessary styling code in order to achieve a focus ring. This code could be greatly simplified to a `box-shadow`. We can then migrate the `focus-ring` mixin to this simplified version.

**Comment by gwyneplaine** [comment]
Closed in favor of #7595 
See [this comment](https://github.com/Shopify/polaris/issues/7595#issuecomment-1314580432) for context
