### ISSUE TITLE
Top bar - color mode switch

### ISSUE THREAD

**Issue by bantikyan** [Shopify/polaris-react#7591]
## Top bar - color mode switch

I was not able to find a way to place some icon-button on the top bar for color mode switching

**Comment by kyledurand** [comment]
Polaris doesn't support dark mode, so you might encounter some issues with what you're trying to build, but have you tried using the `secondaryMenu` prop for this toggle?

**Comment by bantikyan** [comment]
It does support, I'm using that right now. AppProvider > theme > colorScheme
secondaryMenu I need to use for Notifications
There is no way to add some extra menu icon?

**Comment by kyledurand** [comment]
It seems like you might be using an older version of Polaris because we've removed the theme object. We have examples of how you can add an icon or button to the top bar [here](https://polaris.shopify.com/components/top-bar)

**Comment by bantikyan** [comment]
1) From the link you provided I can see only userMenu and secondaryMenu, how I can add 3th item?
2) If I update to a newer version I will not able to use colorScheme anymore?
