### ISSUE TITLE
Embedded Page not rendering title text or action buttons

### ISSUE THREAD

**Issue by mfurniss** [Shopify/polaris-react#760]
# Issue summary

Since updating from Polaris 2.12.1 to 3.3.0 our embedded Polaris app no longer renders Page title or action buttons.

## Expected behavior

Page title and action buttons should render next to the application title.

## Actual behavior

Title or action buttons are not rendered. No error messages in console.

![image](https://user-images.githubusercontent.com/1683021/49972258-ece1ff80-fee5-11e8-9ff5-ab0a0916878c.png)

## Steps to reproduce the problem

1. Create an app using the AppProvider component
2. Create a Page component a title and a primary action

```
<Page
    title="All Influencers"
    primaryAction={{
        content: 'Data Sources',
        onAction: () => {
            this.props.history.push('/settings');
        },
    }}
    fullWidth
>
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.3.0
- Browser: Chrome 70.0
- Device: MacBook Pro
- Operating System: 10.13.6

**Comment by AndrewMusgrave** [comment]
Any ideas @tmlayton ?

**Comment by tmlayton** [comment]
Hey @mfurniss, this is going to be some kind of issue with the app bridge handshake. Make sure your app provider has the correct API key and a shop origin provided. Even though shop origin is no longer required, it turns out the underlying function provided from app bridge is only able to determine the shop origin if it is passed via query string. Try installing the [Redux DevTools](https://github.com/reduxjs/redux-devtools) to help with debugging.

Side note, per your example `fullWidth` is not supported and will have no effect when using an embedded page.

**Comment by tmlayton** [comment]
Also, try turning on verbose mode in the console because I am not confident app bridge reports handshake issues as console errors, but perhaps as warnings.

If you are continuing to have issues, feel free to reopen this issue with a code example which includes app provider as well.

**Comment by mfurniss** [comment]
Hi @tmlayton 

My AppProvider looks like this. I'm not using the shopOrigin.

`      <AppProvider
        apiKey={process.env.REACT_APP_SHOPIFY_API_KEY}
      >`

I do see a warning in the console. Would this affect the App Bridge?

`main-0b375f7d47030afdf2aaea33873bc05b8cdaec740fe083c2352073b77a5eb199.js:1 Shopify.AppMessenger received message null from unexpected origin https://dev-store-black.myshopify.com ; expecting https://furniss.ngrok.io or subdomain thereof`

I see App Bridge in Redux Tools. The titleBar property is null.

I tried removing fullWidth, but then my page is very narrow. Looks like that property does still work on embedded pages.

**Comment by markdavies** [comment]
@mfurniss I had the same issue when I was upgrading too. 

Not sure if you're using [shopify_app](https://github.com/Shopify/shopify_app), but @shop_session used to need a protocol prepended to it, but now it doesn't.

Anyway, check your shop origin is what I'm saying - that fixed it for me.
