### ISSUE TITLE
ResourcePicker showHidden for collections

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react#770]
# Feature request summary

The `showHidden` prop for the `ResourcePicker` provides a way for hiding products not visible on the storefront, it would be great if that could work for collections that are not published on the storefront as well. I thought this worked in Polaris v2, but I don't remember exactly. Might just be wishful thinking. :)

## Rationale

We often provide these resource pickers to allow people to choose products or collections they can link to on their storefront. By not being able to effectively stop them from picking a collection that's hidden to the online storefront, we can't have them safely pick something that will be able to be linked.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by mbaumbach** [comment]
If the intention of the existing `showHidden` prop should be controlling visibility of collections available to the storefront too, then this can be changed to a bug. I created this as a feature request since the current docs describe it as such: `Whether to show hidden products or not`

**Comment by dleroux** [comment]
@mbaumbach thanks once again for submitting an issue. I think you are correct that this is a bug. Asking around right now. Will update with an answer ASAP.

**Comment by dleroux** [comment]
I confirmed it's a bug in another internal repo. I've opened  an issue there for you.

**Comment by danrosenthal** [comment]
Closing in favor of https://github.com/Shopify/app-bridge/issues/639
