### ISSUE TITLE
Prevent line breaks occurring in middle of words

### ISSUE THREAD

**Issue by paulstairmand** [Shopify/polaris-react#771]
# Issue summary

In the Partner Dashboard there are places where line breaks occur in the middle of words. This is **not** happening in English, but it **is** happening in other languages.

In many languages, such as Italian and German, there are strict rules on where you can break words at a line break. We believe there is no way to set lines to break at the right places in each language, so we would prefer to prevent line breaks from occurring in the middle of words in **all languages**.

We're unsure as to whether this is a system-wide problem, or a problem specifically with the React implementation in the Partner Dashboard.

## Expected behavior

Lines should only break between words, not in the middle of words.

## Actual behavior

Lines are breaking in the middle of words.

## Steps to reproduce the problem

1. Go to Partners Internal https://partners.shopify.com/internal
2. Go to your profile in the top right and change your language to Italiano or Deutsch
3. Go to this page: https://partners.shopify.com/internal/betas
4. As you scroll down through the list of betas, you'll see several instances where lines break in the middle of words.

## Specifications

- Are you using the React components? (Y/N): Yes I believe so
- Polaris version number: Don't know
- Browser: Chrome v70.0.3538.110
- Device: MacBook Pro 13 inch 2017
- Operating System: macOS Mojave 10.14

**N.B. The Internationalization guidelines in the style guide will need to be updated to reflect this rule once any change has been made in React**

@nimzco @giuliagreco @SebastianSzturo

**Comment by dleroux** [comment]
Hi @paulstairmand 

This page is built in Polaris-rails. I'll close this and open it there and tag you on the issue.
