### ISSUE TITLE
Modern Sass does not like color math

### ISSUE THREAD

**Issue by lemonmade** [Shopify/polaris-react#779]
# Issue summary

When processing Polaris's Sass with a recent version of node-sass (4.10), I get a deprecation complaining about color math:

<img width="889" alt="screen shot 2018-12-17 at 7 13 46 pm" src="https://user-images.githubusercontent.com/3012583/50164031-aa3a7180-02af-11e9-9d4c-c4238ffa0264.png">

[`color-multiply`](https://github.com/Shopify/polaris-react/blob/master/src/styles/foundation/colors.scss#L77) seems to be the culprit.

## Expected behavior

No deprecations when building Sass.

**Comment by chloerice** [comment]
Thanks for raising this @lemonmade!

**Comment by kaelig** [comment]
🗒 Related issues: https://github.com/sass/libsass/issues/2414
