### ISSUE TITLE
Make Polaris StrictMode compliant

### ISSUE THREAD

**Issue by jineshshah36** [Shopify/polaris-react#785]
# Issue summary

Currently, there are many components that are not StrictMode compliant within Polaris because they using the legacy context API or use deprecated lifecycle methods. Given that React 16.7 will support a concurrent mode which should hopefully improve application performance for most situations, it would be great if Polaris because StrictMode compliant so that we could use it in the future without issue.

## Expected behavior

Polaris should be StrictMode compliant

## Actual behavior

Polaris is not StrictMode compliant

## Steps to reproduce the problem

1. Wrap Polaris components with the <React.StrictMode></React.StrictMode> component
2. The console will begin spitting out errors.

## Reduced test case

N/A

## Specifications

N/A

**Comment by mbaumbach** [comment]
Related issue: #457. Also, React 16.7 was just released and doesn't include concurrent mode (it's now in an unannounced future version), but agreed, it would be great to see Polaris compliant with `StrictMode`.

**Comment by AndrewMusgrave** [comment]
Hi @jineshshah36 , as Ben mentioned we're currently in the process of removing deprecated lifecycle hooks as tracked in #519. We don't have an issue tracking the switch to the new context api, but we've already begun using the new context api in a few components and will be switching more in the future.

**Comment by jineshshah36** [comment]
I'm getting a 500 error when I try to visit https://github.com/Shopify/polaris-react/issues/519, but that is good to hear
