### ISSUE TITLE
Resource index layout - content

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react#7931]
### Primary content
- [x] Draft subtitle
- [x] Draft annotations for key pattern characteristics
- [x] Draft merchant use cases
- [x] Inventory what critical decisions builders need to make
- [x] Draft guidelines to critical decisions

### Secondary content
- [x] Sketch asset ideas
  - [x] Pattern overview
  - [x] Critical decisions
- [x] Identify and list related resources

### Moved to issue #7943 
- [ ] Draft code template and component list
  - [x] Find out if it's feasible to use new index tabs and filters

[Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4204%3A173485&t=Kg5sYithPQzevUFl-1)

**Comment by johanstromqvist** [comment]
First draft is complete 🎉

I'll give it some fresh eyes myself in the morning, but would appreciate some critical feedback. Primarily on what information that is currently included (is it complete, something missing, etc), and secondarily on the language used. Dropped a few annotations where I currently have the lowest confidence. After the first iteration, we can run it by our layout SMEs.

[Figma: Resource index layout – First draft, Jan 5th](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4216%3A180272&t=Kg5sYithPQzevUFl-1)

CC: @SeanyB @selenehinkley

**Comment by SeanyB** [comment]
Thanks, @johanstromqvist. I've left detailed comments in Figma. 

One important thing I noticed, The "tabs" at the top of the resource list aren't Polaris tabs. They appear to be a custom component. I think we'll need to start a discussion of how to handle this. Do we adapt the pattern to use Tabs, or do we try to make it feasible to share this pattern, as is, with all builders (since it's being used in the admin)?

**Comment by johanstromqvist** [comment]
Regarding tabs. It turns out that the index has several implications.
- The new index design has tabs, filter, and likely other index design updates that aren't in Polaris yet
- The current index design has filters from global components

We currently can't offer a code template on mainline.

As discussed here: [Slack](https://shopify.slack.com/archives/C036CGUL4SE/p1673033349533659) (expires early March)

**Comment by johanstromqvist** [comment]
Created an escalated issue (https://github.com/Shopify/polaris/issues/8020) for variable index page widths

**Comment by johanstromqvist** [comment]
- Marking this issue as done.
- Content in [Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4204%3A173481)
- Creating new issues:
  - [x] #7943 
  - [x] #8050 
  - [x] #8061 

<details><summary>🌄 Screenshot</summary>

![Image](https://user-images.githubusercontent.com/38329124/212430549-4e4b5fd8-3c2c-43d5-80ff-a9e5c7fbea66.png)

</details>
