### ISSUE TITLE
[AlphaStack] `align` should map to the `justify-content` property

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react#7945]
## Issue summary

The `AlphaStack` component currently maps its `align` prop to the CSS `align-items` property. It should instead map to the `justify-content` property since `Inline` is meant for horizontal layout and `AlphaStack` is meant for vertical layout.

## Expected behavior

The following should vertically center its contents:

```jsx
<AlphaStack align="center">
  <Placeholder width="320px" label="Center" childAlign="center" />
  <Placeholder width="320px" childAlign="center" />
  <Placeholder width="320px" childAlign="center" />
</AlphaStack>
```
<img width="1033" alt="Screenshot 2022-12-16 at 5 55 44 PM" src="https://user-images.githubusercontent.com/18447883/208202634-42e455d8-2c84-4222-9db4-04c8b7a265dd.png">

## Actual behavior

The following horizontally centers its contents:

```jsx
<AlphaStack align="center">
  <Placeholder width="320px" label="Center" childAlign="center" />
  <Placeholder width="320px" childAlign="center" />
  <Placeholder width="320px" childAlign="center" />
</AlphaStack>
```
<img width="1053" alt="Screenshot 2022-12-16 at 5 54 48 PM" src="https://user-images.githubusercontent.com/18447883/208202570-d7762629-5e3c-4315-b020-cda16bfd0d9a.png">

## Reduced test case

[CodeSandbox demo](https://codesandbox.io/s/alpha-stack-align-prop-bug-9inyhf)

**Comment by rohitm-anncode** [comment]
Alpha Stack in not working you have alternative of it
