### ISSUE TITLE
[a11y] [RangeSlider] usability/a11y: increase track hit zone?

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-react#798]
The track in the RangeSlider component is pretty thin and could be tough to point to and click on for some people with poor motor skills or simply not in an optimal position to use their mouse/trackpad.

### Current design

The clickable zone is a 4px tall line:

![screen_shot_2018-06-18_at_9_46_03_am](https://user-images.githubusercontent.com/85783/41550213-f393c4ac-72dc-11e8-86d3-55dcfa410220.png)

### Proposal

An extended hit zone (invisible but clickable) could make it easier to click the track:

![screen_shot_2018-06-18_at_9_46_03_am](https://user-images.githubusercontent.com/85783/41550300-35988b30-72dd-11e8-9dc1-37c25fb0b403.png)

Not depicted: the thumb would float above the virtual hit zone.

**Comment by solonaarmstrong** [comment]
⭐️

**Comment by ruairiphackett** [comment]
The minimum touch target [being proposed by the W3C](https://www.w3.org/WAI/GL/mobile-a11y-tf/wiki/Proposed_SC_Target_Size) is 48x48px and 44x44 [by Apple](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/).

Do you think this might be overkill in this case (a height of 44px)? The visual design might be affected by the increased whitespace 🤔

**Comment by ruairiphackett** [comment]
Oops, spotted there was a [PR put in already](https://github.com/Shopify/polaris-react/pull/987), is this issue resolved @solonaarmstrong?

**Comment by kaelig** [comment]
Thanks for digging into this, @ruairiphackett!

Closing the issue.
