### ISSUE TITLE
Pattern detail page - Related resources

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react#8057]
We are reducing the visual weight of the Related resources section so that it doesn't compete with the rest of the pattern page.

- [x] Update the Related resources section to be a list with links, similar to component pages.
- [x] Update link content for App settings layout pattern (see [Figma for 7938](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4822%3A219175&t=Wfh8XdUzAQkojg9N-1))
- [x] Update link content for Date picker pattern (see [Figma for 7930](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4822%3A219513)).

[Figma design](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4622%3A191580&t=Wfh8XdUzAQkojg9N-1)

![Image](https://user-images.githubusercontent.com/421723/212749821-3af9cb7f-c150-457e-8c44-3c634d57d920.png)

**Comment by gwyneplaine** [comment]
Work committed here 
https://github.com/Shopify/polaris/pull/7843/commits/70cc467c0758b45090e727cf3aaac7ab01af2bf1 

Waiting on staging deployment for review.

**Comment by johanstromqvist** [comment]
Haven't seen it in action, but it's such a simple design and the markdown is there so I'll just mark this as done.

![Image](https://user-images.githubusercontent.com/38329124/213570652-2ccdc8b5-96df-4886-8456-75b736262a3e.png)
