### ISSUE TITLE
Embedded modal does not work

### ISSUE THREAD

**Issue by ptcampbell** [Shopify/polaris-react#809]
The old modal chestnut. Here goes.

I have an embedded app which is using the `AppProvider` component. I have managed to use the `ResourcePicker` component without trouble. 

Following [the modal documentation](https://polaris.shopify.com/components/overlays/modal#section-use-in-an-embedded-application) does not work. 

Upon triggering the modal I get this error…

<img width="836" alt="screen shot 2018-12-30 at 6 51 56 pm" src="https://user-images.githubusercontent.com/876594/50553833-057f4300-0c64-11e9-9aa7-2ba381aa1622.png">

> Note in the props table that a number of properties are only available in stand-alone applications, and won't work in an embedded context.

In the documentation it is not clear which props will / will not work in an embedded context. 

I'm on Polaris 3.3, Typescript 3.1.3, React 16.7

**Comment by AndrewMusgrave** [comment]
Hi @ptcampbell , thanks for letting us know the example doesn't work. We'll take a look into it.

**Comment by imgntn** [comment]
i've been trying to migrate from 2.12 to 3.3 and can't get modals to open in my embedded app. no error but they don't show up.

**Comment by imgntn** [comment]
so it appears to be related to the 'optional' shopOrigin parameter for the AppProvider - if i leave it off nothing ever happens when I try to open a modal

**Comment by sam-cnet** [comment]
@imgntn Sounds like your app is set as an embedded app in your partners dashboard > app extensions. And you are not redirecting to the Shopify admin and then trying to open the Modal. If your app is embedded in the Shopify admin than you may not be able to open it when loaded outside of Shopify admin. I will tell you for certain you need the shopOrigin for an embedded app and that it should only open when loaded in the Shopify admin.

**Comment by ptcampbell** [comment]
To clarify, the original issue describes the modal not working in an embedded app (an iframe inside of the Shopify admin).

**Comment by sam-cnet** [comment]
Embedded Modal needs at least a **title** prop and either **src** prop or **message** prop with a value. You cannot use a child component in an embedded Modal. So if you're doing this:

```
<Modal>
 <Modal.Section>
 </Modal.Section>
</Modal>
```
**dont** because it has caused me those app-bridge errors. Hope this helps I pretty much spent this week reading, testing and playing with embedded Modal.

**Comment by ptcampbell** [comment]
Thanks @sam-cnet.

Unfortunately I still had trouble getting the example set out in the docs to work, which is using a self closing `<Modal/>` element.

**Comment by sam-cnet** [comment]
Hi Patrick my current setup is Polaris @3.4.0 and app-bridge @1.0.3 running chrome

Sent from my iPhone

On Jan 17, 2019, at 9:34 PM, Patrick Campbell <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @sam-cnet<https://github.com/sam-cnet>.

Unfortunately I still had trouble getting the example set out in the docs to work, which is using a self closing <Modal/> element.

**Comment by ptcampbell** [comment]
I got it working, although I didn't really narrow down what it was. Either I was setting both the `message` and `src` together — or maybe my version of the app-bridge was the problem. Anyway, thank you!

**Comment by ptcampbell** [comment]
@AndrewMusgrave for folks in future: the example should probably include a `message` string rather than a URL in `source` since the example does not resolve and the console error is unclear. 😇

**Comment by sam-cnet** [comment]
Sweet! Happy for you! The docs are updated very frequently so I’m sure we’ll see many changes very quickly.

Sent from my iPhone

On Jan 18, 2019, at 11:00 PM, Patrick Campbell <notifications@github.com<mailto:notifications@github.com>> wrote:


@AndrewMusgrave<https://github.com/AndrewMusgrave> for folks in future: the example should probably include a message string rather than a URL in source since the example does not resolve and the console error is unclear. 😇

**Comment by spinlock99** [comment]
It looks like I've hit a similar problem. I can get `message` or `src` to work but I can't get the Modal to render children.

My app is an embedded app that redirects to the shopify admin.

**Comment by sam-cnet** [comment]
I’ll have a look sometime tomorrow. I do believe you need to load an iframe in a modal for content.

Sam Bazargan

On Sep 6, 2019, at 3:15 PM, Andrew Dixon <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like I've hit a similar problem. I can get message or src to work but I can't get the Modal to render children.

My app is an embedded app that redirects to the shopify admin.
