### ISSUE TITLE
Polaris Empty state illustration rendering very small

### ISSUE THREAD

**Issue by markiiikram** [Shopify/polaris-react#810]
# Issue summary

Hi Team, Happy New Year! When building [Build a Shopify app with Node and React]( https://help.shopify.com/en/api/tutorials/build-a-shopify-app-with-node-and-react) the Polaris Empty state component illustration sometimes renders very small.

## Expected behavior

It should render as shown in Polaris https://polaris.shopify.com/components/structure/empty-state

## Actual behavior

<img width="1425" alt="screen shot 2019-01-02 at 11 22 35 am" src="https://user-images.githubusercontent.com/3484321/50601294-c29ab680-0e81-11e9-96bb-2fa8650a8541.png">

<img width="775" alt="screen shot 2019-01-02 at 11 05 01 am" src="https://user-images.githubusercontent.com/3484321/50601305-c595a700-0e81-11e9-90e5-4fd40627c030.png">

## Steps to reproduce the problem

1. Complete the [Build your user interface with Polaris](https://help.shopify.com/en/api/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris) of the Tutorial

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.2.1
- Browser: Chrome
- Device: MacBook Pro
- Operating System: Mojave 10.14.1

cc: @katiedavis

**Comment by AndrewMusgrave** [comment]
Odd, shouldn't the illustration be rendering under the title and actions?

**Comment by solonaarmstrong** [comment]
Odd, I thought this was fixed.

**Comment by markiiikram** [comment]
@nwtn is getting a slightly different version of this problem today. 

![Screen Shot 2019-03-11 at 11 28 03 AM](https://user-images.githubusercontent.com/3484321/54136278-d4ed1f80-43f1-11e9-9a6f-0866c22d25e6.png)

Related to this issue is a "double rendering" that seems to happen because of SSR and AppProvider. AppProvider checks for client, it's not ready, then it checks it again and renders "properly".

![broken-empty-state](https://user-images.githubusercontent.com/3484321/54136752-b9364900-43f2-11e9-8d2f-c3e257cf7901.gif)

**Comment by yourpalsonja** [comment]
This repo getting a makeover! We want to make it easier to find existing issues, remove duplicates, and increase community engagement. If you issue is closed, re-labelled, or moved, don’t panic–it may be a duplicate (check the comments), or there is a new label or repository that work better.

If you disagree with the changes or have any other thoughts on how we can make Polaris better, please let us know!
