### ISSUE TITLE
Date picking pattern tab list flash on page refresh

### ISSUE THREAD

**Issue by gwyneplaine** [Shopify/polaris-react#8179]
If we're linked to a tab on the date-picking pattern page that isn't the default tab, there will be a flash (default tab rendered active) before the correct tab is focused. 

![gif of described date-picking tab list bug](https://user-images.githubusercontent.com/12119389/214999743-342a5eca-9dab-4db3-9740-3fbbcf497ca0.gif)

**Comment by SeanyB** [comment]
Good catch. Not strictly blocking the release, but something worth doing as soon as those blocker issues are complete.

**Comment by jesstelford** [comment]
Fixed in #8129
