### ISSUE TITLE
[Autocomplete] - Chrome autocompletion conflicts with `Autocomplete` options

### ISSUE THREAD

**Issue by loic-d** [Shopify/polaris-react#819]
# Issue summary

In some scenarios, the Google Chrome autocompletion seems to be conflicting with the `Autocomplete` options. 

<img width="638" alt="50654374-a3238c80-0f5a-11e9-9a0a-7b5e95528a38" src="https://user-images.githubusercontent.com/3925905/50695597-197fc780-100b-11e9-922b-0e8f34976cd5.png">

<img width="305" alt="screen shot 2019-01-04 at 10 28 57 am" src="https://user-images.githubusercontent.com/3925905/50695772-aaef3980-100b-11e9-87cf-bef893b3230a.png">

## Expected behavior

The Google Chome autocompletion should be disabled in favour of the `Autocomplete` options. This way, only the `Autocomplete` options would be displayed to merchants.

## Actual behavior

The Google Chrome auto completion is displayed on top of the `Autocomplete` options. This is confusing for merchants. The only options they should be able to choose from are the `Autocomplete` options.

## Steps to reproduce the problem

1. Go to a Discount Details page (code or automatic) in React
2. Enter a time manually in the start or end field and blur
3. Empty the field and blur
4. Click on the field. Google autocompletion is displayed

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

```
 <Autocomplete
              id="StartTimeField"
              label={i18n.translate('startTime')}
              placeholder={i18n.translate('startTime')}
              showDisclosure={startTimePickerVisible}
              value={
                userInputStartTime === undefined
                  ? this.getTimeString(currentStartDate)
                  : userInputStartTime
              }
              prefix={<Icon source={stopwatch} color="skyDark" />}
              options={this.getAllPossibleStartTimes(currentStartDate)}
              idForOption={getDateISOString}
              labelForOption={this.getTimeString}
              onFocus={this.openStartTimePicker}
              onClose={this.closeStartTimePicker}
              onSelect={this.handleStartTimeSelected}
              onChange={this.handleStartTimeChange}
              onBlur={this.handleStartTimeBlur}
            />
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: `"@shopify/polaris": "3.3.0",`
- Browser: Chrome
- Device: Mac 
- Operating System:

**Comment by solonaarmstrong** [comment]
Closing this because it turns out that this is using a [different version of autocomplete](https://github.com/Shopify/web/blob/master/packages/%40shopify/polaris-next/components/Autocomplete/Autocomplete.tsx). The Polaris autocomplete uses [text field as its base](https://github.com/Shopify/polaris-react/blob/master/src/components/Autocomplete/components/ComboBox/components/TextField/TextField.tsx#L5), which defaults to `autocomplete="off"`.
