### ISSUE TITLE
Create a visual source-of-truth for FEDs

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react#8195]
FEDs need a visual reference to rely on.

**Include latest versions of**
- features and content blocks
- spacing and light mode styling

**Don't include**
- Dark mode (reference site + individual issues)
- Content, images, code examples (reference those separately, as keeping those up-to-date would take lots of effort and provide little value)

**Suggested process**
1. Create the source-of-truth (One-off)
    - [x] Consolidate previous template and recent visual changes
      - [x] Updates to related resources
      - [x] Updates to the code feature
      - [x] Updates to tabbed content and margins
2. Respective designer updates the reference after we've made new decisions in various GitHub issues

**Comment by bernardojoaogarcia** [comment]
All current updates have been made to Figma designs. Issue is ready for review.

https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=5276%3A245987&t=fBfE8ErLIPk2zBKy-1

**Comment by bernardojoaogarcia** [comment]
![Image](https://user-images.githubusercontent.com/107587671/216168937-6e4a8d1d-f2cb-4588-99bb-7348bde8eef5.png)

The Up-to-date design page can now be located under the Overview section

**Comment by johanstromqvist** [comment]
Cross-posting it here for visibility:

I suggest only presenting three pages:
1. Pattern index
2. Single variant pattern page
3. Multi variant pattern page

In other words, excluding the specific content, images and code examples of each pattern page. This makes it clear that this is the source of truth for _the features_ and _visual design_ only. The content, images and code examples get tweaked so frequently and happens elsewhere, that it would be a lot of work to keep that up to date in Figma.
