### ISSUE TITLE
Update App Bridge to 1.0.3

### ISSUE THREAD

**Issue by vividviolet** [Shopify/polaris-react#820]
We would like to update Polaris to consume the latest version of App Bridge as [v1.0.0](https://github.com/Shopify/app-bridge/releases/tag/v1.0.0) has been released with a bunch of bug fixes and new features

**Comment by vividviolet** [comment]
@tmlayton Can you give us some guidance on how to test Polaris when updating App Bridge?

**Comment by AndrewMusgrave** [comment]
Hi @vividviolet , when testing polaris with an app bridge update you'll want to build your `polaris-react` branch to your embedded app. We have a script for building to other `dev` cloned repos. Once you are on your `polaris-react` branch you'll want to run `yarn build-consumer DIRNAME`. Unfortunately until our next release you'll need to install `@shopify/polaris-icons` in your embedded app.

From the top of my head the components that use app bridge are; page, modal, loading and resource picker.

**Comment by danrosenthal** [comment]
> From the top of my head the components that use app bridge are; page, modal, loading and resource picker.

Also Toast.

**Comment by vividviolet** [comment]
Thanks everyone! I'll give it a shot
