### ISSUE TITLE
Resource Picker constantly reflows as you type

### ISSUE THREAD

**Issue by imgntn** [Shopify/polaris-react#825]
# Issue summary

If you use the resource picker, as you're typing the resource picker constantly reflows down to zero results.

It's very jarring.

## Expected behavior

Once you haven't typed anything for a moment you'd expect new results to show and the reflow to happen when the query is completed. 

Or if the results are the same, it should not reflow at all.

For comparison, in the Shopify admin at /admin/products there isn't constant reflow as you type.

## Actual behavior

Constant reflow.

## Steps to reproduce the problem

1. Type the name of a product
2. Type a space afterward.  Or anything.
3. Watch as the resourcepicker reflows down to zero results and then pops back up to the same or new results

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.3
- Browser: Chrome
- Device: Desktop
- Operating System: Windows

**Comment by solonaarmstrong** [comment]
Hi @imgntn 👋 Nice handle, it sounds short for "imagination". I'm going to recreate this and respond further...

**Comment by solonaarmstrong** [comment]
A quick follow-up that I have filed this as a bug.

**Comment by imgntn** [comment]
thanks!  you're right about my handle it is short for 'imaginiation'.  best!

**Comment by imgntn** [comment]
bump
