### ISSUE TITLE
SubNavigationItems Never display

### ISSUE THREAD

**Issue by wshen001** [Shopify/polaris-react#826]
# Issue summary

SubNavigationItems doesn't show even if it provideds in props. Example of code snippet:

```
      <Navigation location="/" userMenu={navigationUserMenuMarkup}>
        <Navigation.Section
          title="Shop"
          items={[
            {
              label: 'Dashboard',
              icon: 'home',
              badge: '15',
              disabled: false,
              // onClick: this.toggleState('isLoading'),
              subNavigationItems: [
                {
                  url: '/test1',
                  label: 'test1',
                  disabled: false,
                },
                {
                  url: '/test1',
                  label: 'test2',
                },
              ],
            },
            {
              label: 'Manage Orders',
              icon: 'orders',
              onClick: this.toggleState('isLoading'),
              subNavigationItems: [
                {
                  url: '/test3',
                  label: 'test3',
                  onClick: () => {},
                },
                {
                  url: '/test4',
                  label: 'test4',
                },
              ],
            },
          ]}
          action={{
            icon: 'conversation',
            accessibilityLabel: 'Contact support',
            onClick: this.toggleState('modalActive'),
          }}
        />
      </Navigation>
```

## Expected behavior

Expect to see test1 to test4 sub items shown up in navigation panel.

## Actual behavior

I've tried all the settings I could apply but the sub items never shown up.

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: v3.3.0
- Browser: Chrome Version 71.0.3578.98
- Device:  Desktop
- Operating System: Mac OS 10.14

**Comment by wshen001** [comment]
Just figured out the problem... I use the typescript 3.2.2 which would cause some problem. It works after switching back to typescript 3.1.6.

**Comment by wshen001** [comment]
I think the problem is that the `expended` state of each subNavigationItem didn't set properly when the window size is larger than 769px. The expanded state only changes when the navigationBar is collapsed. Any idea?

**Comment by solonaarmstrong** [comment]
Thank you, @wshen001 👋  We'll look into it.

**Comment by solonaarmstrong** [comment]
Hi @wshen001 The path in the navigation prop needs to match the URL for the top level nav item. Here is a working example. Try changing your paths and see if it works properly. Let us know if you need any further help!

Here's the code I used.

```
        items={[
            {
              label: 'Dashboard',
              icon: 'home',
              onClick: this.toggleState('isLoading'),
            },
            {
              url: '/admin/orders',
              label: 'Orders',
              icon: 'orders',
              disabled: false,
              subNavigationItems: [
                {
                  label: 'All orders',
                  url: '/admin/orders',
                  disabled: !false,
                },
                {
                  label: 'test2',
                  url: '/test2',
                  disabled: false,
                },
                {
                  label: 'test3',
                  url: '/test2',
                  disabled: false,
                },
              ],
            },
          ]}
```

**Comment by wshen001** [comment]
Thank you, I forgot to close the ticket. Really appreciate your explanation.

**Comment by stoleruedgar** [comment]
@solonaarmstrong Actually wshen001 is right about 769px. When using the Navigation component the subNavigationItems are not displayed because of breakpoints.ts -> navigationBarCollapsed(). There is no mentioning of this in the documentation and there is no fallback when window is > 769px. 

This ticket should be reopened. 

Easy test is to go the Shopify React Components showcase Navigation or Frame, open in the sandbox, add subNavigationItems to an item  and then open the rendering window in a new window the page . Navigation not working as expected.

**Comment by baorv** [comment]
Is it fixed?

**Comment by wshen001** [comment]
What documentation missed are A) url of props needs to match with the current route. B) the 769 px breakpoint. 

There two factors should be noted in documentation.

**Comment by alainfd82** [comment]
And if I don't want to use url and instead use onClick?

**Comment by eugene-kim** [comment]
@solonaarmstrong-zz @wshen001  thoughts on reopening this issue? onClick is a valid use case that isn't addressed by the solution proposed by @solonaarmstrong-zz
