### ISSUE TITLE
Feature request: currency/price display

### ISSUE THREAD

**Issue by ice-lenor** [Shopify/polaris-react#828]
# Feature request summary

It would be nice to have a special control (say, something similar to DisplayText or TextStyle) which would display the price in the formatted manner.

If I get shop settings from `/admin/shop.json`, I get several price-related fields, such as `currency`,  `money_with_currency_format`, etc:

```
"currency": "EUR",
"money_format": "€{{amount_with_comma_separator}}",
"money_with_currency_format": "€{{amount_with_comma_separator}} EUR",
"money_in_emails_format": "€{{amount_with_comma_separator}}",
"money_with_currency_in_emails_format": "€{{amount_with_comma_separator}} EUR",
```

So it would be nice to have a control accepting the amount of money and the format (currency is not needed, as far as I understand?), and printing a string according to the format.
```
<TextMoney format="money_with_currency_format" amount="5000.40" />
```

Would print:
```
€4.567,89 EUR
```

## Rationale

Right now I am not sure how to, using Polaris, print the price according to one of the formats that are being set by the shop owner.

P.S. If I'm missing something, and there is actually a way to do that with Polaris, please point that out for me! I'm rather new to shopify development, and might be mistaken.

Thank you very much!

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by danrosenthal** [comment]
@ice-lenor thanks for the issue, and for the great idea. This is not something we currently implement in Polaris, but I can see it being really useful. We have improving localization in Polaris on our roadmap for the first quarter of this year, so I can definitely see something like this getting built in the next several months.

For now, as with any feature request, I'm going to close this and encourage anyone interested to express their interest by upvoting the original issue with a 👍. I've already added mine 😄

**Comment by ice-lenor** [comment]
Thank you for your reply, Dan! Good to know this might be useful.

Maybe this is off-topic, but how would you advise to print prices with currencies right now? Is there any way to make use of these "money_with_currency_format" fields? Or should I simply use the js's default method `toLocaleString( ..., {style: 'currency', ...)`?

Thanks again!

**Comment by danrosenthal** [comment]
Using `toLocaleString` sounds like your best bet for now!
