### ISSUE TITLE
DataTable column widths

### ISSUE THREAD

**Issue by arieljaw12** [Shopify/polaris-react#832]
Hello,

It will be nice to control column width's in the DataTable component. For example I had this table with a few columns:
![image](https://user-images.githubusercontent.com/32110225/50847138-9a162f00-134f-11e9-9246-78e5f7feb46f.png)

And I would like to give more width to the first column so I don't have to truncate the strings. One workaround that I found was to wrap the row data in a `div` and harcoded the `width` in the `style` prop like:
```
<div style={{
  width: '200px'
}}>
  <Link>
    Alvarez Windey's Retailers
  </Link>
</div>
```
But I think if you add more columns they will be crashing each other.

Also found that if in the `Link` component you use `onClick` instead of `url` with `truncate={true}` the three dots ("...") does not appear.

For the feature I'm thinking something like:
```
<DataTable
  columnWidths={[70, 15, 15]}
/>
```
Where you define column width in percentages. Also it will be nice that you define the percentage you want and distribute the rest of the percentages equally.

Regards,
Ariel

**Comment by chloerice** [comment]
Thanks for the request, @arieljaw12. We treat all feature requests as part of our backlog, so I’ll close this issue for now, but **we encourage everyone who wants this feature to add a 👍** to the original issue report. We take your collective interest into account when we look at what to explore next.

💜

**Comment by chloerice** [comment]
> Also found that if in the Link component you use onClick instead of url with truncate={true} the three dots ("...") does not appear.

The link component renders an HTML `button` element when it is not provided a `url`. Button elements do not inherit text styles from parent elements.

**Comment by marisveide** [comment]
Please, make this change happen, otherwise, it doesn't make sense to use Polaris tables for displaying data.
Having equal column widths for all the columns, regardless of their contents, generates a really unusable table, where 1 digit column takes the same amount of space as the long text column.
