### ISSUE TITLE
Prevent pattern details page from scrolling when a new tab is selected

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react#8322]
Ideally, switching tabs should not cause the pattern details page to scroll.

See current behaviour:

https://user-images.githubusercontent.com/421723/218536144-70623732-3e63-44ed-9992-261886a7553a.mp4

Tripwire: This isn't a critical bug, so just let @SeanyB know if this isn't a quick fix.

**Comment by jesstelford** [comment]
Fixed and shipped 👍
