### ISSUE TITLE
[Layout foundations] Clean up css in `LegacyCard`

### ISSUE THREAD

**Issue by aveline** [Shopify/polaris-react#8376]
Remove: https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Card/Card.scss#L16-L22

Remove: https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/LegacyCard/LegacyCard.scss#L16-L22

Remove Polaris-Card css overrides in admin.

**Comment by laurkim** [comment]
Closed with https://github.com/Shopify/polaris/pull/8468.
