### ISSUE TITLE
[Range slider] add code coverage for dual thumb implementation

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-react#841]
Looking at the [code coverage report](https://codecov.io/gh/Shopify/polaris-react/src/range-slider-dual-input/src/components/RangeSlider/components/DualThumb/DualThumb.tsx) for #784, you can see that the majority of the code is uncovered by tests. We should add tests for each of the event handlers, as well as other critical logic like sanitization of the value prop and lifecycle methods.

- [x] test value sanitization
~- [ ] test lifecycle methods~
- [x] test keyboard event handlers
- [ ] test mouse event handlers
- [ ] test resize event handler

**Comment by solonaarmstrong** [comment]
[ ] test value sanitization
[ ] test lifecycle methods
[ ] test mouse event handlers
[ ] test resize event handler

**Comment by yourpalsonja** [comment]
I moved these tests as items needed before merging into the PR itself. :)
