### ISSUE TITLE
Mouseover on a UserMenu component shows 'altText'

### ISSUE THREAD

**Issue by cmccauley** [Shopify/polaris-react#842]
# Issue summary

The title inside of the UserMenu is defined as `altText` https://github.com/Shopify/polaris-react/blob/master/src/components/TopBar/components/UserMenu/UserMenu.tsx#L52

When a user does a mouseover on the component, it shows `altText`

There is no props to override the value.

## Expected behavior

To not show `altText` by default

## Actual behavior

<img width="424" alt="screen shot 2019-01-09 at 2 05 24 pm" src="https://user-images.githubusercontent.com/9267763/50923189-5b00e000-141a-11e9-9eca-469ea3755553.png">

## Steps to reproduce the problem

1. Open a page with a TopBar that has a UserMenu (Admin)
2. Mouseover the name for a few seconds.

## Specifications

- Are you using the React components? Y
- Browser: Chrome

**Comment by solonaarmstrong** [comment]
Thanks for pointing this out! I will forward it to the right people.
