### ISSUE TITLE
[storybook] Hot reloading only working for the first save

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-react#858]
It seems like consecutive saves don't hot-reload the example preview.

### How to reproduce:

1. run `yarn dev`
1. open [the Caption component example in Storybook](http://localhost:6006/?selectedKind=All%20Components%7CCaption&selectedStory=Default%20caption&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
1. open `src/components/Caption/README.md`
1. modify the React example, **save**
1. the storybook example should have changed (without needing to refresh the page)
1. modify the example again, **save**

### Expected behavior

The example is showing the edits.

### Actual behavior

No changes show up, a page refresh is necessary.

**Comment by BPScott** [comment]
Known bug :p

This only affects README files. Component tsx files / the playground are unaffected. I've got something I want to try that might fix it but didn't want to string that initial PR out any longer
