### ISSUE TITLE
App Icon component 

### ISSUE THREAD

**Issue by laranoell** [Shopify/polaris-react#867]
# Component name
AppIcon

> The Thumbnail component is primarily used to display product thumbnails, but this component has been leveraged to display other images, like app icons in places. 

## Components dependencies
This component could extend the existing thumbnail component, the difference being that it has no box-shadow (which looks like a light grey border)

"The pattern for apps in Shopify doesn’t have a border around the icon, following the styling of the app section and embedded apps." 
- https://shopify.slack.com/archives/C4Y8N30KD/p1547227607125700

**Comment by ry5n** [comment]
This seems reasonable to me. I like the idea of this being explicitly for app icons, rather than adding a prop to Thumbnail to turn the border on/off. It better aligns the components with their purposes.

**Comment by claudiomunoz** [comment]
I agree, a component for app icons will also give us more flexibility to scale and make modifications based on future requirements. Thanks for starting this @laranoell !

**Comment by AndrewMusgrave** [comment]
👋 How's the progress on this, is it safe to say it's a `work in progress`? @claudiomunoz

**Comment by claudiomunoz** [comment]
Sorry, I thought this was done. I'm not sure what's pending, as the design have been done for a very long time. See here: https://share.goabstract.com/dabc4b91-351d-45b2-bfb7-293ed8295563
