### ISSUE TITLE
ResourcePicker not showing in version 3.4.0

### ISSUE THREAD

**Issue by alexdover** [Shopify/polaris-react#875]
# Issue summary

I am working on updating an existing app from version 2.4.0 to the latest version, 3.4.0 - everything has worked well except the ResourcePicker component, which no longer displays.

I have set the Api Key on the AppProvider and even with the most basic example, the picker will not display.

## Expected behavior

ResourcePicker should show when setting the open boolean to true

## Actual behavior

No ResourcePicker is displayed.

## Steps to reproduce the problem

1. Use the ResourcePicker
2. Ensure wrapped in AppProvider

## Reduced test case

Here is the simple code I am using - I'm hoping I am doing something obvious wrong!

```
import React from 'react';
import ReactDOM from 'react-dom';

import { AppProvider } from '@shopify/polaris';

import EmbeddedAppResourcePickerExample from './components/EmbeddedAppResourcePickerExample';

const apiKey = window.ShopifyAppSettings.apiKey;

ReactDOM.render(
    <AppProvider apiKey={apiKey} shopOrigin="al-local-apps.myshopify.com">
        <EmbeddedAppResourcePickerExample />
    </AppProvider>,
    document.getElementById('app'),
);
```

My basic example component

```
import React, {Component} from 'react';

import {
    ResourcePicker,
    Button
} from '@shopify/polaris';

class EmbeddedAppResourcePickerExample extends Component {
    constructor(props) {
        super(props);

        this.state = {
            resourcePickerOpen: false,
        }
    }
    
    render() {
        return (
            <div>
                <pre>{JSON.stringify(this.state.resourcePickerOpen)}</pre>
                <ResourcePicker
                  resourceType="Product"
                  open={this.state.resourcePickerOpen}
                  onSelection={({selection}) => {
                    console.log('Selected products: ', selection);
                    this.setState({resourcePickerOpen: false});
                  }}
                  onCancel={() => this.setState({resourcePickerOpen: false})}
                ></ResourcePicker>
                <Button onClick={() => this.setState({resourcePickerOpen: true})}>Open...</Button>
            </div>
        );
    }
}

export default EmbeddedAppResourcePickerExample;
```
When clicking the button to open, I see the resourcePickerOpen variable change to true, but the picker does not show.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: 3.4.0
- Browser: Chrome
- Device: Mac
- Operating System:

**Comment by sam-cnet** [comment]
What version of @shopify/app-bridge are you using?

**Comment by dan-gamble** [comment]
Never mind, this was just me being stupid and me thinking there was an issue with the docs.

If anyone does come by this for whatever reason the line for `AppProvider` is:

```javascript
<AppProvider shopOrigin={this.state.shopOrigin} apiKey={API_KEY} forceRedirect>
```

And not
```javascript
const { SHOPIFY_API_KEY } = process.env;
<AppProvider shopOrigin={this.state.shopOrigin} apiKey={SHOPIFY_API_KEY} forceRedirect>
```

I didn't read the

```javascript
  webpack: config => {
    const env = { API_KEY: JSON.stringify(process.env.SHOPIFY_API_KEY) };

    config.plugins.push(new webpack.DefinePlugin(env));
    return config;
  }
```

In the `next.config.js`

Sorry for derailing this issue

**Comment by sam-cnet** [comment]
@alexdover Thanks for sharing that I too plan on integrating with Shopify POS so hopefully things will be sorted out by then :p

**Comment by nathan-lapinski** [comment]
@dan-gamble Thanks for sharing that, it just solved my issue. I made the exact same mistake!

**Comment by chipmunkgeek** [comment]
@dan-gamble I did the **exact** same thing in departing from the tutorial instructions and inserting my `API_KEY` the way I *thought* it was supposed to be done (as `process.env.SHOPIFY_API_KEY`). Your discovery resolved the issue for me. I'll go back to following instructions like they're written. :sweat_smile:
