### ISSUE TITLE
Cannot use child component in Modal (Embedded App)

### ISSUE THREAD

**Issue by sam-cnet** [Shopify/polaris-react#876]
## Here is my dilemma:

I want to display modal content in an embedded app but I am only limited to **message** and **src** properties. I can render a new component using **src**, that has a form with a submit btn. When the user submits the form I would like to do anyone of the following which I have been unable to do:

* Close the Modal by dispatching `this.context.polaris.dispatch(Modal.Action.CLOSE);`
* Close the Modal by dispatching `this.modal(Modal.Action.CLOSE)` 
* Display a Toast using app-bridge while the Modal is opened. 

If I were able to use a child component in Modal for an embedded app, I may be able to do something like this:

`<Modal>
  <Modal.Section>
    <Route path="/modal/content" component={modalContent} />
  </Modal.Section>
</Modal>
`

Because **modalContent** would be a child of Modal I would then be able to dispatch `this.context.polaris.dispatch(Modal.Action.CLOSE);` 

## Ultimate question 

**How to close Modal without using the 'X' close button in an embedded app?**
**Or how to dispatch Modal.Action.CLOSE from outside the component that created the Modal**
## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.4.0
- Browser: Chrome
- Device: Desktop
- Operating System: Windows

**Comment by sam-cnet** [comment]
If you've seen my activity you'll know I've been struggling with Modal component. Ultimately it was a bad idea to have a user input in a modal in an embedded app. Right now I can't think of a single benefit to using a modal in an embedded app unless you desperately need the users attention and for that use the built-in props for primary and secondary actions that way you can use callbacks. This however does not answer the question and I would like some response to this because I know I'm not crazy and as I was coding forward this created a road block for a most of the time logical mind.

**Comment by chloerice** [comment]
Hi @sam-cnet, thanks for raising this. Have you tried invoking a callback that changes the state of the value passed to the `Modal`'s `open` prop within the submit handler you pass to the `primaryAction`?

**Comment by sam-cnet** [comment]
Yup you're right I should have passed a function from my parent component to the **primaryAction** prop in the `<Modal />` component that way I would know when the user has submitted. I think ultimately this is my lack of ReactJS experience, because I ended up doing the same thing just without using the `<Modal />` component. I am going to close this because I believe you have answered my question. So for you newbies out there do something like this:

```
class Parent extends React.Component {
constructor(){
  super();
  //just open it, forget the handler
  this.state = {
    modalOpen: true
  } 
  this.handleModalAction = this.handleModalAction.bind(this);
}

handleModalAction() {
  this.setState({modalOpen: !this.state.modalOpen});
}

render() {
  <Modal
      open={this.state.modalOpen},
      src={/path/to/component},
      title={'title'},

      //I'm passing a callback as a prop (child to parent state changes)
      primaryAction={{this.handleModalAction}}
    />
  }
}
```
This is also **documented** in the docs, however intuitively you may keep all of your logic in `src={/path/to/component}`, but you shouldn't because you then lose access to the state of the parent component. React patterns teach us to pass your callback as a prop to the child component and that way you can change state from child to parent. Parent to child state changes are pretty obvious and can be seen in the above example.
