### ISSUE TITLE
[Button] Add “pressed” state

### ISSUE THREAD

**Issue by dleroux** [Shopify/polaris-react#877]
## Problem

Sometimes buttons are used like a radio button, usually in a group but potentially on their own (as a toggle).

As implemented in polaris-rails: https://github.com/Shopify/polaris-ux/issues/58

## Examples

<img width="315" alt="screen shot 2017-10-12 at 6 21 06 pm" src="https://user-images.githubusercontent.com/804014/31557049-5590d798-b015-11e7-92a0-bc040d5d19af.png">

**Comment by yourpalsonja** [comment]
@dleroux can we close this in favour of the ToggleButton component that is currently in polaris-next?

**Comment by dleroux** [comment]
@yourpalsonja we can but this is the issue and not the pr so it should probably be closed once that that toggle buttons makes it into Polaris?

**Comment by mirualves** [comment]
After a chat with @yourpalsonja, we decided to leave this issue for now and figure out how to move the `ToggleButton` into Polaris from Polaris-next (instead of adding a confusing prop to `Button`).

**Comment by dpersing** [comment]
This work is currently on hold while the P-BOP team supports Tooling with updating the UI Kit for Figma.

**Comment by dpersing** [comment]
Hi @AndrewMusgrave! Any updates on this issue?

**Comment by AndrewMusgrave** [comment]
@dpersing  Had a slight delay, in the beginning, pinged Sonja for some information before I realized she was OOO 😅I opened a WIP draft pr (not up to date) #2148. I'm curring working on adding the pressed state for all the button types/modifiers. I'll probably be messaging @mirualves for some opinions on styles / UI kit updates Friday.
