### ISSUE TITLE
Make sure deprecation versions are correct when releasing the next version

### ISSUE THREAD

**Issue by kvendrik** [Shopify/polaris-react#879]
Not sure what would be the best way to address this so figured I would make a note here. When the next version of Polaris gets released the version number in [`Navigation.UserMenu`'s deprecation rationale](https://github.com/Shopify/polaris-react/blob/master/src/components/Navigation/README.md#deprecation-rationale) will need to be validated. It might be good to in the future have some kind of workflow for this.

cc @danrosenthal @tmlayton

**Comment by tmlayton** [comment]
Probably remove all of these rationales after each major version?

**Comment by tmlayton** [comment]
But yeah we need this on a checklist somewhere or it will be forgotten.

**Comment by AndrewMusgrave** [comment]
> But yeah we need this on a checklist somewhere or it will be forgotten.

I have an idea of how we might automate this so we won't need a list that I want to explore on fridaetion.

**Comment by tmlayton** [comment]
Nice! Keep in mind we won’t always want to remove every deprecation `console.warn` and deprecation rationale in each major version. For example, we will likely have the deprecation notices and rationale for App Bridge shipped before v4, but won’t be removing until v5.
