### ISSUE TITLE
[TextField] Spinner sometimes indefinitely updates value of number type field

### ISSUE THREAD

**Issue by lemonmade** [Shopify/polaris-react#882]
# Issue summary

We have a case in the admin (which I can't create a smaller reproduction of, unfortunately) where a number input sometimes continuously decrements/ increments the value when clicking on the spinner. While I couldn't create a reproduction, I think I found the issue: `<Spinner />` unmounts before its `onMouseUp` callback happens (I guess, for some reason, the Spinner goes away as part of a separate state update). Because `onMouseUp` is never called, the timeout that `<TextField />` sets up for continuing the increment/ decrement is never cleared, resulting in infinite value changes.

I think the best solution is to call spinner's mouse up handler on `componentWillUnmount` just in case it gets unmounted mid-click.

**Comment by chloerice** [comment]
Fix shipped by @tmlayton in #1029 will be available in the v3.7.2 release 🎉
