### ISSUE TITLE
[ChoiceList] Allow passing a string to the `selected` prop if `allowMultiple` is false

### ISSUE THREAD

**Issue by clauderic** [Shopify/polaris-react#903]
# Feature request summary
- Allow passing a string to the `selected` prop of `ChoiceList` if `allowMultiple={false}`.
- Update the type of the `selected` argument in the `onSelect` callback to `string | string[]`

## Rationale

Currently, the `ChoiceList` component only accepts passing an array of selected choices to the `selected` prop. The `onChange` handler also returns an array of selected choices, even if `allowMultiple` is false and only one option can ever be selected.

Having to map the selected option as an array and receiving an array in the change handler makes things a bit awkward from the consumer's perspective. 

This forces consumers to have to map their state as an array, as suggested by the documentation. This feels wrong because you’re representing a singular slice of state as an array (`selectedItem: ['handle']`).

Alternatively, you can store the `selected` item as a string but then convert it to an array in the render method and getting the first item in the array in the change handler. This is also less than ideal because it forces the `<ChoiceList>` component to re-render on each render (unless the selected prop is memoized, but I feel like that would unnecessarily increases the complexity of the consuming component):

```jsx
class MyComponent extends React.Component {
  state = {
    selected: 'choice',
  };

  render() {
    const selected = [this.state.selected];
    
    return (
      <ChoiceList
        selected={selected}
        onChange={this.handleChange}
        allowMultiple={false}
      />
    )
  }

  @autobind
  private handleChange(selected: string[]) {
    if (selected[0] == null) {
      return;
    }

    this.setState({
      selected: selected[0],
    });
  }
}
```

In isolation, this isn’t a huge deal, and I understand it makes for a simpler implementation from the library’s perspective, but it makes everything more awkward for consumers, and at scale I’m sure there are quite a few places where this ends up making the implementation of the components consuming `ChoiceList` a bit less elegant than it could be.

The implementation could look something like this for single selection:

```jsx
import {ChoiceList, ChoiceListSelection, isMultipleSelection} from '@shopify/polaris';

class MyComponent extends React.Component {
  state = {
    selected: 'choice',
  };

  render() {    
    return (
      <ChoiceList
        selected={this.state.selected}
        onChange={this.handleChange}
        allowMultiple={false}
      />
    )
  }

  @autobind
  private handleChange(selected: ChoiceListSelection) {
    if (isMultipleSelection(selected)) { // custom type guard 
      return;
    }

    // TypeScript now infers that selected is a string
    this.setState({
      selected,
    });
  }
}
```

Where the implementation for the custom type guard would look something along the lines of:
```ts
type SingleChoiceSelection = string;
type MultipleChoiceSelection = string[];
type ChoiceListSelection = SingleChoiceSelection | MultipleChoiceSelection;

function isMultipleSelection(selected: ChoiceListSelection): selection is MultipleChoiceSelection {
    return Array.isArray(selected);
}
```

The main downside of this approach is that it would also mean that the change handler of multiple selection would also need to use the `isMultipleSelection` type guard, so there would be added complexity there.

## Alternative solutions

Perhaps Polaris should ship with a `SingleChoiceList` component instead of trying to support both use-cases within the same component. This would avoid having to use a type guard in the change handler, while still allowing the state to be mapped to the right shape.

The `SingleChoiceList` and `MultipleChoiceList` components could be thin wrappers around `ChoiceList` to reduce the duplication cost.

If we're reluctant to change the internal implementation of `ChoiceList`, something like this would allow the implementation to remain the same within `ChoiceList`:

```tsx
import {ChoiceList, ChoiceListSelection, isMultipleSelection} from '@shopify/polaris';
import memoizeOne from 'memoize-one';

interface Props extends ChoiceListProps {
  selected: string;
  onChange(selected: string): void;
}

class SingleChoiceList extends React.Component<Props, never> {
  render() {
    const {onChange: _, selected, ...props} = this.props;

    return (
      <ChoiceList
        {...props}
        selected={this.mapSelectedValue(selected)}
        onChange={this.handleChange}
        allowMultiple={false}
      />
    );
  }

  @autobind
  private handleChange(selected: ChoiceListSelection) {
    const {onChange} = this.props;
    const selected = selected[0];

    onChange(selected);
  }

  @memoizeOne()
  private mapSelectedValue(selected: string) {
    return [selected];
  }
}
```

**Comment by asalisbury** [comment]
To avoid having extra conditional logic scattered everywhere for what looks like a a common solution, I would favor something like `<SingleChoiceList />` if it means that consumers of `<ChoiceList allowMultiple={false} />` won't need to duplicate that type-guard conditional wherever used.

**Comment by ry5n** [comment]
If we ultimately decide two separate components is best, I would much prefer to stick to HTML naming and go with something like `RadioList` and `CheckList` (or `CheckboxList`).

I’m in support of making this easier for the consumer regardless of the ultimate solution.

**Comment by marytal** [comment]
Just came up against this issue again. Thought it might be worth re-opening.
