### ISSUE TITLE
"ProductVariant" Resource Picker doesn't display product name

### ISSUE THREAD

**Issue by imgntn** [Shopify/polaris-react#905]
# Issue summary
"ProductVariant" Resource Picker doesn't display the product name -- so if you have variants with the same name on different products, it's almost impossible to tell them apart when using this type of picker.

## Expected behavior

It should show the product name somewhere (and allow it to be searched on).

## Actual behavior
 Doesn't show product name; it's confusing.

## Steps to reproduce the problem
1. Have multiple products w/ same name for variants
2. Add a resource picker w/ type "ProductVariant"
3. Observe confusion
![confusion w picker image ](https://i.imgur.com/d4mQkNm.jpg) 
## Reduced test case

```
            <ResourcePicker
              resourceType="ProductVariant"
              showVariants={true}
              allowMultiple={true}
              open={true}
              onSelection={this.handleResourceSelected}
              onCancel={this.handleResourceCancel}
            />
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.4
- Browser: Chrome
- Device: PC
- Operating System: Windows

**Comment by imgntn** [comment]
my use case is actually just trying to select a single variant for a product -- for the "Product" type picker (where the formatting is nice) unfortunately the "allowMultiple={false}" property only applies to products, not variants.  so you can still select multiple variants there (expected or bug?).  that led me to try the "ProductVariant" type picker, but you can't differentiate between variants.  

Thanks!

**Comment by AndrewMusgrave** [comment]
Thanks for submitting the request @imgntn . We close all feature requests and encourage everyone interested to upvote the original comment by adding 👍 to help us gage interest.
