### ISSUE TITLE
Allow changing the app title

### ISSUE THREAD

**Issue by ptcampbell** [Shopify/polaris-react#906]
I want the ability to change the App Title since… 

* The app's title is more verbose than is required in the UI. 
* The truncation occurs at an unfortunate position.
* The logo is enough and the area looks cluttered.

It would also be really nice to have an `onAction` method as per #416 — it looks pretty janky when you reload the frame (plus the state is reset) etc. 

Thanks!

**Comment by AndrewMusgrave** [comment]
Hi @ptcampbell thanks for taking the time to create this issue. I'm going to label it as a feature request and close the issue. Please feel free to upvote the first comment so we can gage intrest 😄

**Comment by carlosforero** [comment]
I need this feature ASAP, especially for the `onAction` callback.

**Comment by tmlayton** [comment]
Hey @ptcampbell and @carlosforero, thanks for this issue/comment and makes sense. This would be a feature request for the App Bridge team. We simply use the `TitleBar` action under the hood and are limited by their API. https://help.shopify.com/en/api/embedded-apps/app-bridge/actions/titlebar

They accept feature requests through the Shopify forums: https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology

---

For more context, we will be removing app bridge delegation entirely from Polaris as of v5 and offer React wrappers around the App Bridge actions from a different package: `@shopify/app-bridge-react`. See this comment for more details https://github.com/Shopify/polaris-react/issues/814#issuecomment-493249756
