### ISSUE TITLE
Layout 1/2 + 1/2 'oneHalf' not working 

### ISSUE THREAD

**Issue by imgntn** [Shopify/polaris-react#907]
# Issue summary
When you use the <Layout.Section oneHalf> components, it doesn't work and just stacks full width columns.  Problem apparent in Polaris docs.

## Expected behavior

Two columns, side by side

## Actual behavior

The columns stack at all widths :/

## Steps to reproduce the problem

1. Visit docs or try two <Layout.Section oneHalf>
![these should be 1/2 and 1/2, my screen is 1920x1080](https://i.imgur.com/SYlkSPW.jpg)
## Reduced test case

https://polaris.shopify.com/components/structure/layout#navigation

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.5
- Browser: Chrome
- Device: PC
- Operating System: Windows 10

**Comment by AndrewMusgrave** [comment]
Hi @imgntn the the section we use to display examples is just a little small in the styleguide. The prop seem to be working on a [larger screen](https://codesandbox.io/s/n0mqzkr49m). Please feel free to let me know if your still having issues;

**Comment by imgntn** [comment]
It still doesn't work for me inside of an app that's embedded in the Shopify Admin - maybe because of the Shopify sidebar?

My resolution is 1920x1080.  

I think the breakpoint may be set a little wide, or behave differently when it's embedded.

![not breaking](https://i.imgur.com/a0ooZEW.jpg)

```
  render() {


    return (
      <Page 
       title="Test Half Width" 
      primaryAction={{
        content:'Save'
      }}
      >

      <Layout> 
           <Layout.Section oneHalf>
             <Card title="Half" sectioned><p>This should be half.</p></Card>
            </Layout.Section>

            <Layout.Section oneHalf>
             <Card title="Half" sectioned><p>This should be half.</p></Card>
            </Layout.Section>
      </Layout>

      </Page>
    );
  }

```

**Comment by AndrewMusgrave** [comment]
> I think the breakpoint may be set a little wide, or behave differently when it's embedded.

I'll see if I can reproduce this within an embedded app later. Do you know what the width of the content is within `Layout`? I believe the breakpoint for `oneHalf` is hit around 984

**Comment by imgntn** [comment]
oof yeah that's my bad -- i had a style somewhere settings a max-width to 960, so just under the breakpoint.  that combined w/the docs made me think the problem was on your end, but it wasn't.  would be good to have it work as expected in the docs though!

thanks for your time :)

**Comment by AndrewMusgrave** [comment]
> would be good to have it work as expected in the docs though!

Fair point. I'll open up an internal issue for our styleguide to see if there's anything we can do to improve this.

**Comment by electrikfreak** [comment]
Hey guys just curious to know if you guys are looking into fixing this one?

**Comment by hadomskyi** [comment]
Just try to add manual 

`  .Polaris-Layout__Section.Polaris-Layout__Section--oneHalf {
    max-width: calc(50% - 2rem) !important;
  }`

**Comment by rnovacek** [comment]
This is still an issue, here is a simple reproducer. No matter what the screen size is, the inner cards (it doesn't have to be cards) are always wrapped. Sectioned `Card` inside `Page` triggers the wrap.

```
import React from "react";
import { Card, Layout, Page } from "@shopify/polaris";

export default class App extends React.Component {
  render() {
    return (
      <Page>
        <Card sectioned>
          <Layout>
            <Layout.Section oneHalf>
              <Card title="Order details" sectioned>
                <p>View a summary of your order.</p>
              </Card>
            </Layout.Section>
            <Layout.Section oneHalf>
              <Card title="Tags" sectioned>
                <p>Add tags to your order.</p>
              </Card>
            </Layout.Section>
          </Layout>
        </Card>
      </Page>
    );
  }
}
```
