### ISSUE TITLE
[DropZone] Uses the old ref React syntax

### ISSUE THREAD

**Issue by elizabethletourneau** [Shopify/polaris-react#910]
# Issue summary
-Update `ref` occurrences in `DropZone` to follow current proper syntax. 

## Expected behavior

React supports a special attribute that you can attach to any component. The ref attribute can be an object created by React.createRef() function.

## Actual behavior

ref={this.setNode}

**Comment by whitetig3r** [comment]
Is this issue up for grabs? I would like to work on it.

**Comment by elizabethletourneau** [comment]
@whitetig3r please go ahead!
