### ISSUE TITLE
Generate atomic css from tokens

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react#9124]
## Feature request summary

Our token system is getting to a pretty good place but to use them you need to write new css every time we use them (if not using a primitive component)

## Rationale

To reduce css bloat in our primitive components we've defaulted to using css vars which in trade creates a problem with inheritance. To address this we reset the custom properties to something like `initial` in the css file. This is becoming difficult to maintain, and also creates DOM bloat by injecting custom properties on every primitive.

Building out a stylesheet of atomic css generated from tokens we could access token values directly from component files, eliminating most of the css in primitive files, removing the need for inheritance resets and reducing bloat in general.

**Comment by alex-page** [comment]
I would like to make this a dedicated roadmap item with a vault project and alignment across orgs. Let me know what you think @kyledurand.
