### ISSUE TITLE
[DataTable] Slight offset between fixed column and the rest of the table

### ISSUE THREAD

**Issue by solonaarmstrong** [Shopify/polaris-react#913]
# Issue summary

Brought up here: https://github.com/Shopify/polaris-react/issues/387#issuecomment-456335668

## Actual behavior

![image](https://user-images.githubusercontent.com/6239480/51543435-6983ca00-1e12-11e9-92f6-aba07f5f56c1.png)

## Specifications

polaris: 3.5.0
chrome browser
mac osx

**Comment by solonaarmstrong** [comment]
@fchienvuhoang Is there a specific environment that causes this bug? Screen size? Does it happen with or without headings? I've played around with it and can't reproduce. Thanks.

**Comment by chloerice** [comment]
This is fixed, there is no longer a fixed column.
