### ISSUE TITLE
[Prototype] Add `polaris-patterns` to prop generation script

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react#9190]
Assuming we are including prop api's in our pattern page documentation, we need to add `polaris-pattern` components to the prop generation.

Additionally, I think we will want the api of subcomponents to be included. i.e. `AppSettingsLayout.AnnotatedSection` should also have an api table

**Comment by martenbjork** [comment]
Heads up, we're probably going to replace the prop generation script soon. (WIP PR: https://github.com/Shopify/polaris/pull/8752)

**Comment by sophschneider** [comment]
@gwyneplaine see above comment!
