### ISSUE TITLE
[ResourceList] support shift-key range selections

### ISSUE THREAD

**Issue by dmeeking** [Shopify/polaris-react#935]
# Feature request summary

Resource Lists should support shift-key based range selection. Example:
Select item #1
Shift-click to select item #10 
Result: I have selected all 10

## Rationale
Many bulk workflows originate from resource lists. This should be default behaviour to speed up selection of multiple items.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by ry5n** [comment]
Absolutely, this is something I always wanted to support. @StephPoce We may have some time in Q2 to look at this.
