### ISSUE TITLE
[Resource List] Bulk action buttons not always showing when selectedItems are set

### ISSUE THREAD

**Issue by maxariss** [Shopify/polaris-react#936]
While building a custom `filters` component to be used with the `<ResourceList />` – I noticed that programatically updating the `selectedItems` doesn't toggle the `<BulkActions />` button visibility. 

Here is a gif outlining my predicament (see when I click on the `Red` filter): 

![screen recording 2018-07-31 at 02 51 pm](https://user-images.githubusercontent.com/12142249/43481668-9581daa6-94d4-11e8-8ebe-f044baaa7ee8.gif)

And here is a snap from dev tools showing the `selectedItems` array with a length of 3, but no visible bulk action buttons:

<img width="979" alt="screen shot 2018-07-31 at 3 13 15 pm" src="https://user-images.githubusercontent.com/12142249/43481689-a469e856-94d4-11e8-8b86-fbcb44a91b3d.png">

**Comment by AndrewMusgrave** [comment]
@maxariss can you confirm this is still broken? I think we have fix this in past release

**Comment by AndrewMusgrave** [comment]
Looks like this issue was only fixed for initial load
