### ISSUE TITLE
[Grid] Columns attribute / breakpoints feedback

### ISSUE THREAD

**Issue by rcass** [Shopify/polaris-react#9374]
It would be nice to declare a `columns` size that could apply to all break point sizes (without having to write out each break point size).

For example:
```js
 <Grid columns={{xs: 10, sm: 10, md: 10, lg: 10, xl: 10}}> /* watch this line */
      <Grid.Cell columnSpan={{xs: 2, md: 1}}>
        <ResourceThumbnail
          size="small"
          source={image?.src}
          alt={image?.altText || `${title} ${variantTitle}`}
        />
      </Grid.Cell>
      <Grid.Cell columnSpan={{xs: 4, md: 6}}>
        <LegacyStack vertical spacing="none">
          <Text variant="bodyMd" as="span" fontWeight="semibold">
            {title}
          </Text>
            <Text variant="bodyMd" as="span" color="subdued">
              {variantTitle}
            </Text>
        </LegacyStack>
      </Grid.Cell>
      <Grid.Cell columnSpan={{xs: 3, md: 2}}>
        <NumberInput   />
      </Grid.Cell>
      <Grid.Cell columnSpan={{xs: 1, md: 1}}>
        <Button> Click here </Button>
      </Grid.Cell>
    </Grid>
```
It would be nice to write something like this:
```js
 <Grid columns={{10}}> /* watch this line */
      <Grid.Cell columnSpan={{xs: 2, md: 1}}>
        <ResourceThumbnail
          size="small"
          source={image?.src}
          alt={image?.altText || `${title} ${variantTitle}`}
        />
      </Grid.Cell>
      <Grid.Cell columnSpan={{xs: 4, md: 6}}>
        <LegacyStack vertical spacing="none">
          <Text variant="bodyMd" as="span" fontWeight="semibold">
            {title}
          </Text>
            <Text variant="bodyMd" as="span" color="subdued">
              {variantTitle}
            </Text>
        </LegacyStack>
      </Grid.Cell>
      <Grid.Cell columnSpan={{xs: 3, md: 2}}>
        <NumberInput   />
      </Grid.Cell>
      <Grid.Cell columnSpan={{xs: 1, md: 1}}>
        <Button> Click here </Button>
      </Grid.Cell>
    </Grid>
```

Basically with no breakpoint size (ie `sm`) declared it would be nice for the number given to apply to all breakpoints. 
Or 
If that would be a bit to hard type wise, it would be nice that if only one breakpoint is given, it is assumed the other sizes what the same amount of columns instead of defaulting to 12. (for example ` <Grid columns={{xs: 10}}>` would result in all breakpoint sizes having 10 columns, instead of changing past the `xs` breakpoint.

[Here](https://github.com/Shopify/web/pull/93654#discussion_r1218103610) is a related PR from core that would benefit from this change.

**Comment by chloerice** [comment]
Hey @rcass 👋🏽 You could use the [`HorizontalGrid`](https://polaris.shopify.com/components/layout-and-structure/horizontal-grid), its `columns` prop supports a single value. We're in the process of aligning component types and APIs across several libraries but it's on pause right now. In the long term there will eventually be parity here, but feel free to contribute this support to `Grid` now 😁

**Comment by rcass** [comment]
>  but feel free to contribute this support to Grid now 

Okay! I'll take a stab at it :)

I created a [feature request issue](https://github.com/Shopify/polaris/issues/9390) to summarize the above and assigned it to myself. Seems like the correct way forward via the [contribution guidelines,](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) but correct me if I am wrong.

**Comment by rcass** [comment]
**[FYI]** Just wanted to note that I do not believe this work is completed (according to https://polaris.shopify.com/ and just verifying via code sandbox).
