### ISSUE TITLE
[Autocomplete][v1] Requesting access to options popover visible state

### ISSUE THREAD

**Issue by maxariss** [Shopify/polaris-react#940]
# Feature request summary
I'm hoping we can add something to the `<Autocomplete />` component's API which allows us to know whether or not the options `<Popover />` is visible.

## Rationale
We have an `<Autocomplete />` used in a rather large form. We would like all fields in the form to submit the form if the <kbd>enter</kbd> key is pressed while they are focued. Except for when the options `<Popover />` is active and being used. 

Alteratively, I believe stopping event propogation from `<ComboBox />`'s `handleEnter()` method would also fix our problem – but perhaps that is too opinionated.

**Comment by ry5n** [comment]
@maxariss Can you share the details about this form (either here or in Slack)? It sounds unusual. cc @dpersing

**Comment by yourpalsonja** [comment]
@ry5n @maxariss @dpersing any follow-up on this? Wondering if a conversation happened somewhere else and this can be closed or should be moved to the backlog so we can plan work for it?

**Comment by ry5n** [comment]
I don’t recall having discussed this offline, and I  don’t have any additional information.

**Comment by dpersing** [comment]
> We would like all fields in the form to submit the form if the enter key is pressed while they are focued. Except for when the options <Popover /> is active and being used.

I wonder if this could be addressed by changing the `implicitSubmit` prop of the form component to be more flexible about specific fields, versus making a change to the autocomplete component?

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.
