### ISSUE TITLE
Form onSubmit is not working with "Topbar.SearchField"

### ISSUE THREAD

**Issue by tabrez96** [Shopify/polaris-react#942]
# Issue summary

I have used Topbar from polaris. In my `searchFieldMarkup` I have included a `Form` with `Topbar.SearchField` like this:

```
<Form onSubmit={handleFormSubmit}>
        <TopBar.SearchField
          onChange={handleSearchChange}
          value={searchText}
          placeholder="Search"
        />
</Form>
```

## Expected behavior
Pressing enter after entering the search string should trigger form submit.

## Actual behavior
Currently, form submit is working with `TextField`. But on replacing `TopBar.SearchField` with `TextField`, the CSS features (of `TopBar.Search` like  themed background) are lost.

## Steps to reproduce the problem

1. Create a searchFieldMarkup with a `Form` and `TopBar.SearchField`
2. After entering the search string, pressing enter should trigger the onSubmit event in `Form`

## Reduced test case

Refer this demo -> https://codesandbox.io/s/r768kkkvyo.

Here I have used `TextField`. Form submit is working here. But while `TopBar.SearchField` is used Form submit is not being triggered.

My use case: Search has to happen only when form is submitted and not on textChange.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.5.0
- Browser: Chrome
- Device: Macbook
- Operating System: MacOS Mojave

**Comment by tarunbhardwaj** [comment]
This is the expected behavior https://github.com/Shopify/polaris-react/blob/5ffde736e486ef25df4315ef69375e671a2d1c02/src/components/TopBar/components/SearchField/SearchField.tsx#L149

**Comment by AndrewMusgrave** [comment]
@tabrez96 Can you listen for a keypress on the document?
```tsx
...
handleKeyup = (e) => {
 const {keyCode} = e;
 if (key === 13) { // enter
   ...
 }
}

...
<EventListener event="keyup" handler={this.handleKeyup}>
```

**Comment by tabrez96** [comment]
Thanks, for the update
