### ISSUE TITLE
[Stack] Vertical prop causes children to bleed outside of container padding on Chrome 72+

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react#947]
# Issue summary

When using a vertical `Stack` the contents appear to break out of the container and "bleed" into surrounding padding when one of the children starts to wrap.

## Expected behavior

The `Stack` contents should be contained by the parent padding regardless of whether children wrap.

## Actual behavior

Whenever a child wraps in a vertical `Stack`, all of the children of that `Stack` will layout into the right padding of the component containing the `Stack`. I'm only able to reproduce this on Chrome 72+ (including Chrome 74/Canary). All other browsers are rendering this fine. This may be a bug in Chrome, but I did confirm that this worked fine with Polaris 2.8 and below even on the latest Chrome. I noticed that if I reverted the change made in commit ab23144519d5793e41f0a4933d75f077d972fdae, the problem went away. I didn't see a regression in Safari after doing that, which appears to be the reason for the change, though I'm not sure of what combination of code caused that issue to appear in Safari to confirm if it's still needed there.

Screenshot of the bleeding (the top Card is the bug, the bottom card shows it correct when wrapping isn't occurring):

![Image of bleeding](https://i.imgur.com/4X25jIh.png)

## Steps to reproduce the problem

1. Create a `Stack` with the `vertical` property set to `true`.
1. Create a child of the `Stack` that will wrap to at least one line.
1. All children will "bleed" into the right padding of the component containing the `Stack`

## Reduced test case

A reduced test case can be found here: https://codesandbox.io/s/lynyx43v4l. The first `Card` with `Stack` shows the problem. The second `Card` shows how the `Stack` is correctly contained when the content doesn't wrap. The third `Card` shows that setting `wrap` to `false` on the `Stack` works around the issue too.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.9.0-3.6.0
- Browser: Google Chrome 72.0.3626.81 (Official Build) (64-bit)
- Device: MacBook Pro
- Operating System: macOS High Sierra 10.14.3

**Comment by mbaumbach** [comment]
Looking at the Shopify Partner Portal on an app's summary page, you can see a couple of areas where this comes up like the Earnings, Growth, and Uninstalls cards. Only in Chrome 72+, of course. :)

**Comment by ry5n** [comment]
This is being investigated in PR #1024. It’s related to changes in Chrome, we’re working to determine the best way to address it.
