### ISSUE TITLE
How to redirect from inside a Polaris component in an embedded app?

### ISSUE THREAD

**Issue by paulisloud** [Shopify/polaris-react#949]
I am attempting to redirect customers of my app to the confirmation_url to accept a billing charge in a Shopify Polaris embedded app. Per the billing API documentation, once we create the charge we need to redirect merchants to the charge's confirmation_url.

Neither a standard server-side nor client side redirect work due to CORS, so I pursued the [App Provider documentation](https://polaris.shopify.com/components/structure/app-provider) which describes creating redirects at the absolute top level of the app where we pass the API key to the AppProvider, and then creating a redirect via `const redirect = Redirect.create(...` at the same time.

Is the idea here that we would then pass `redirect` down as a prop down the component chain to every component that might need to make a redirect? The reason I ask is that it doesn't seem like the method implied for creating redirects would enable creating them at the component level.

**Comment by dpersing** [comment]
Hi @paulisloud! Sorry for our delay in getting to your question. Were you able to find the info you needed in the [Redirect](https://help.shopify.com/en/api/embedded-apps/app-bridge/actions/navigation/redirect) documentation linked from the app provider page you mentioned?

**Comment by paulisloud** [comment]
Thanks for getting back to me @dpersing, but unfortunately that documentation also asks you to create the `redirect` instance using the `shopOrigin` and `apiKey`, meaning we would need to:

* `createApp` while in a component, which is inside the app already, and pass `shopOrigin` and `apiKey` all the way down to the component, or
* should we instead create `redirect` at the top level of the app and attach it to state and make it available to components around via Redux / Context?

Or, is there some other way to instantiate the redirect while already in a component, say, a Card on a Page and perhaps I am making this harder than it needs to be?

**Comment by WesKetch** [comment]
@paulisloud not sure if this helps you but I just started playing around with this library and got a redirect working using something like this 

```jsx
import { Redirect } from "@shopify/app-bridge/actions";

class ProductForm extends React.Component {
  static contextTypes = {
    polaris: PropTypes.object
  };

  handleSubmit = () => {
     // after form is submitted redirect to admin product show page
     const redirect = Redirect.create(this.context.polaris.appBridge);

    return redirect.dispatch(
      Redirect.Action.ADMIN_PATH,
      `/products/${product.id}`
    );
  }
```

this is in a component that is a child of app provider

```jsx
<AppProvider apiKey={apiKey}>
  <Router>
    <div>
      <ProductForm />
    </div>
  </Router>
</AppProvider>
```

**Comment by puc94** [comment]
Hi @WesKetch!
I followed the guidance on https://polaris.shopify.com/components/structure/app-provider.
Redirect should work after button click, no errors appears but no redirect also. I have attached my source code briefly.
Could you tell me why it doesn't works for me?

import * as PropTypes from 'prop-types';
import { Redirect } from "@shopify/app-bridge/actions";

class Help extends Component {
	static contextTypes = {
		polaris: PropTypes.object
	};

	gotoInstallPage = () => {
		const redirect = Redirect.create(this.context.polaris.appBridge);
		return redirect.dispatch(Redirect.Action.APP,'/install');
	}

	render() {
		return(
			<Link monochrome onClick={() => this.gotoInstallPage()}>troubleshooting</Link>
		)
	}
}

**Comment by marguskoiduste** [comment]
Hi!

I am facing a similar issue. I am using version 3.12.0. I have implemented the redirection according to the example at https://polaris.shopify.com/components/structure/app-provider. 

This is the message that is posted to the parent window, but the redirection is not happening. I have checked and the apiKey and shopOrigin are correct. I'm not seeing any errors in the browser console.

```{"payload":{"payload":{"id":"9907fe05-d0bb-0623-86f2-e8b4f60c3412","path":"/products"},"group":"Navigation","type":"APP::NAVIGATION::REDIRECT::ADMIN::PATH","version":"1.2.0","clientInterface":{"name":"@shopify/polaris","version":"3.12.0"}},"source":{"apiKey":"cb68c5a1c5a2ae6cc9f0ab78937f6dc4","shopOrigin":"t-sargid.myshopify.com"},"type":"dispatch"}```

My code:
```javascript
import React, { Component } from 'react'
import ReactDOM from 'react-dom'
import { AppProvider } from '@shopify/polaris'
import * as PropTypes from 'prop-types'
import { Page, Button } from '@shopify/polaris'
import { Redirect } from '@shopify/app-bridge/actions'

class Dashboard extends Component {
  render () {
    let redirectToProducts = () =>{
      const redirect = Redirect.create(this.context.polaris.appBridge)
      redirect.dispatch(Redirect.Action.ADMIN_PATH, '/products')
    }

    return (
      <Page title = "Settings">
        <Button onClick = {redirectToProducts}>Test</Button>
      </Page>
    )
  }
}

Dashboard.contextTypes = {
  polaris: PropTypes.object
}

export default Dashboard

if (document.getElementById('dashboard')) {
  const apiKey = window.SHOPIFY_API_KEY
  const origin = window.SHOPIFY_ORIGIN

  ReactDOM.render(
    <AppProvider apiKey = {apiKey} shopOrigin = {origin}>
      <Dashboard />
    </AppProvider>,
    document.getElementById('dashboard')
  )
}
```

**Comment by marguskoiduste** [comment]
Are you sure your "App URL" matches the URL where the app is actually loaded from? I had exactly the same behavior, but it turned out there was a mismatch between the "App URL" and the origin of the postMessage the AppBridge was sending. Please see this issue: #1332

**Comment by puc94** [comment]
Hi @marguskoiduste!
Yes, I have checked App URL and the origin of the postMessage the AppBridge.
Everything seems okay but redirect is not working.
Currently I am using react-redux in a polaris react.
I think both of libraries doesn't compatible each other.

**Comment by cgenevier** [comment]
For me the problem was that I had "https://" preceding the app URL. If your including it, try taking it out (ex: "store.myshopify.com" instead of "https://store.myshopify.com") and see if that helps?

**Comment by coler-j** [comment]
How would you do this within a `FC`? Where are the docs in how to access the App Bridge context?

**Comment by ggtaylor** [comment]
I'm using an older version of app-bridge-react that doesn't have useAppBridge, so I used useContext for now. 

Ref: https://shopify.dev/tools/app-bridge/react-components/provider

`
import React, { useContext } from 'react';
import { Context } from '@shopify/app-bridge-react';
import { Redirect } from '@shopify/app-bridge/actions';

const YourPage: React.FC = () => {
  const app = useContext(Context);
  const redirect = Redirect.create(app);
  ...
  redirect.dispatch(Redirect.Action.APP, '/otherpage?somequeryparam=123');
`
