### ISSUE TITLE
Page title missing and breaks Polaris HTML output

### ISSUE THREAD

**Issue by juliantrueflynn** [Shopify/polaris-react#952]
# Issue summary

The element `Polaris-Page-Header` is wrapping around entire page content. Leaving the title hidden, breaking the HTML output, and removing styling.

@hannachen outlined the issue more [here](https://github.com/Shopify/polaris-react/issues/824#issuecomment-454571430). Note: Hanna in this said this was due to Next.js, but I believe this is an issue with all SSR which is a problem with Polaris.

## Expected behavior

Correctly formatted HTML output for Polaris with Page component title showing.

## Actual behavior

`Polaris-Page-Header` element is swallowing up the child elements on page load.

See images provided from [this ticket here](https://github.com/Shopify/polaris-react/issues/824#issuecomment-454571430)

![Broken formatting](https://user-images.githubusercontent.com/2709526/51213227-73746d00-18e8-11e9-8c43-40f228794a25.png)

## Steps to reproduce the problem

Please see [this repo](https://github.com/juliantrueflynn/shopify-koa-app-example/tree/error__page-header), where I outlined steps. It is important that it is viewed in Shopify admin, that is where the break happens.

## Reduced test case

Please see [this repo](https://github.com/juliantrueflynn/shopify-koa-app-example/tree/error__page-header) to replicate the error. Again, it's important to view this in Shopify Admin because that is where the issue happens.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.6.0
- Browser: Chrome Version 71.0.3578.98
- Device: Desktop
- Operating System: Ubuntu 16.04

**Comment by juliantrueflynn** [comment]
I ended up figuring this out. Turns out `forceRender` is required for `Page` component for the title to show. Even when using CRA (without SSR), I had the title missing, so I don't think this is exclusive to just SSR. Maybe make this more clear in the documentation?

**Comment by dan-gamble** [comment]
This fixed it for me too @juliantrueflynn.

I was following https://help.shopify.com/en/api/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris and it kept breaking. Adding `forceRender` is the fix but i feel like it shouldn't need it.

**Comment by chloerice** [comment]
Hey @juliantrueflynn, thanks for raising this and linking to the related discussion in #824! Can you explain or share a code snippet of where you forcing the render to fix this for future reference? Are you using `this.forceUpdate`?

**Comment by juliantrueflynn** [comment]
@chloerice the repo in the original post [here](https://github.com/juliantrueflynn/shopify-koa-app-example/tree/error__page-header). The edit was made to [this line](https://github.com/juliantrueflynn/shopify-koa-app-example/blob/error__page-header/app/App.js#L22) to add `forceRender` prop. I tested this on Next.js Shopify App project too and it also worked.

**Comment by chloerice** [comment]
Sorry, I'm not seeing that prop anywhere. I do see `forceRedirect` is set on the `AppProvider`, is that what's fixing it?
