### ISSUE TITLE
TopBar.UserMenu has unnecessary scrollbar 

### ISSUE THREAD

**Issue by kvendrik** [Shopify/polaris-react#955]
**Screenshot from `3.6.0`**
![3 6 0](https://user-images.githubusercontent.com/4029894/52151268-7f7a6180-2640-11e9-9d1a-9716142c58a3.png)

**Screenshot from `3.5.0`**
![3 5 0](https://user-images.githubusercontent.com/4029894/52151276-8608d900-2640-11e9-89b2-c4acf7085d3a.png)

**Comment by amireynoso** [comment]
Hi, we're seeing this too in the Vault, using `3.9.0`:

![image](https://user-images.githubusercontent.com/1855829/58283329-08471580-7d76-11e9-9787-3af1528d8fb5.png)

**Comment by tmlayton** [comment]
Do we know if this is still an issue in the current version? If so, can you create a reduced test case using codesandbox? Here is a starter: https://codesandbox.io/s/tender-cannon-4dl8z

**Comment by kvendrik** [comment]
Closing this in favour of https://github.com/Shopify/polaris-react/issues/1673.
