### ISSUE TITLE
Search field alignment seems off

### ISSUE THREAD

**Issue by kvendrik** [Shopify/polaris-react#956]
Should we align it with the page title on pages like this?

![screen_shot_2019-02-01_at_4 42 32_pm](https://user-images.githubusercontent.com/4029894/52151514-50b0bb00-2641-11e9-97e8-a1f6e8647283.png)

**Comment by jakob-stecher** [comment]
Afaik Home is the only (although arguably the most prominent) page that uses this layout. I'm not too concerned with it looking off here, given that the alternative would be a search bar that jumps around horizontally.
