### ISSUE TITLE
Input Group Component

### ISSUE THREAD

**Issue by wshen001** [Shopify/polaris-react#961]
Is there a way to make input group like the following image?

![Image of Yaktocat](https://i.ibb.co/hcwfN6R/Screen-Shot-2019-02-03-at-1-29-23-PM.png)

Basically it combines input field with button, I have tried a few ways but not as easy as I thought with current <Stack> component.

**Comment by mbaumbach** [comment]
@wshen001 You can use the `connectedRight` prop on the `TextField` component. Something like this should work:

```
<TextField
    placeholder="Search products"
    prefix={<Icon source="search" />}
    connectedRight={<Button>Browse products</Button>} />
```

**Comment by wshen001** [comment]
It works, thanks for pointing it out @mbaumbach.
