### ISSUE TITLE
[TextField, Select, etc.] Slim and large variants to align with equivalent buttons

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react#963]
Internal issue for [feature request](https://github.com/Shopify/polaris/issues/373) asking that our form input components, like text field and select, be enhanced to have size variant props like buttons do. 

This makes sense to me and should be low difficulty to implement.

**Comment by dpersing** [comment]
@ry5n Is this something we want to add to the road map, or shall we close it out for now?

**Comment by ry5n** [comment]
I think we can close this out. It would be nice to have but I haven’t heard any requests for it.

**Comment by chloerice** [comment]
Yeah, since we moved to open dev this is now a duplicate issue of #373, so closing 👍
