### ISSUE TITLE
[Autocomplete][v1]disabled is not fully disabled.

### ISSUE THREAD

**Issue by supervee** [Shopify/polaris-react#972]
# Issue summary

A disabled AutoComplete field can still be clicked and selections can still be made.
An example can be seen here: https://bullandcleaver.myshopify.com/admin/marketing/activities/666dcce8-6389-425f-bcf0-6c9469b6716f?activity_id=3152707618

(Specific Interests field -- there are no available options but I was able to replicate this on the Polaris site sandbox)

## Expected behavior

Clicking the field should do nothing

## Actual behavior

See above.

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.

**Comment by Brydom** [comment]
Hey @dleroux, was there any update to that? I'm still seeing the same issue on `6.3.0`. Thought I'd check in as probot closed this last year.
