### ISSUE TITLE
Page should to apply bottom spacing below content

### ISSUE THREAD

**Issue by benwolfram** [Shopify/polaris-react#9729]
## Issue summary

Currently, there is no way to organically apply spacing to the bottom of a Page. PageActions will apply bottom padding, but when there are no actions for a Page, there is no way to do this. You may try empty PageActions, but this will still apply a divider line.

With the changes to Uplift, Cards no longer apply padding to the bottom of themselves so content becomes flush with the end of the browser bottom.

## Expected behavior

<img width="1511" alt="image" src="https://github.com/Shopify/polaris/assets/3689812/11f2d4ae-9b54-495f-90d6-389f94fc4b40">

## Actual behavior

![image](https://github.com/Shopify/polaris/assets/3689812/2785da80-f5bd-4d9a-ba7b-dbc52742a456)

## Steps to reproduce the problem

In Uplift, I don't see the same Page.content class that applies vertical padding.

https://polaris.shopify.com/sandbox?code=N4Igxg9gJgpiBcIA8AFAhgcxgPgDoDsACQpAGTQE8IBXAFzyOJPKroDoBlGMWgSwnwMmTJAGE0AJyhDhIgCowAHrUJoAzgF5cIAA7bCAN0m80%2BWlpAAjaBQCyUbTNlMOEALYxCC5QWfEkAPTe9L6ygeJSTiQBLDS0nNx8AlFklHEJPPyCocJiktI5YcGqmtp6IIbGpuba1lB2DiBRzq4eXkq0hblBHc3REQWM-jFp7FyZyYWprPHjSdlDIgN9-sXqFuWVEiZmFnUNjl2yrZ7BR8PBfeH5KSMzGfMpsWOJWVfL5yRrpbr6RtvVPY2eyHRYtdynDqfQKXI7XSJTO7pOZvKbPWavSZgkgfbGrDolDZ-Kq7WrAxorFwQ9o%2BPHRWHY%2BGDbroh6oxbTZGYhbOPIIulIb5Eir-HY1Kzk0F%2BKltM4CnrKK4BXEs0YYiY8kSslFY3kqvyCgnrMrEgGkiX1EFNT7EE40zryhm85U3RHa7lPNVs3VhfW8oUmkUk8X7K2U23UuXSmG9OEu-mq%2B46zX%2Bd0a96ugUB35Bs0hyXWukR2VQx2xxnx5kiJEvdOhQLohiBdBYBggAA0IFoAAsYB41AgANogAA2EDAaBHMHgMHwIAAup2AO68KA9gfwQcAdgAbAAOdsARgALMeAAzzgC%2BQA

**Comment by mbaumbach** [comment]
Related issue: https://github.com/Shopify/polaris/issues/7163
