### ISSUE TITLE
AppBridge throws error regarding shopOrigin

### ISSUE THREAD

**Issue by imgntn** [Shopify/polaris-react#979]
# Issue summary

I'm using AppBridge in an Embedded app w/ Polaris.

I'm getting an uncaught error from AppBridge regarding 'shopOrigin' -- it doesn't matter whether I defined a shopOrigin on my AppProvider or not. 

Any insight?

Thanks!

## Expected behavior

the app should load w/o errors

## Actual behavior
this error stack
```
1.a2259fad.chunk.js:1
 Uncaught u {name: "AppBridgeError", message: "APP::ERROR::INVALID_CONFIG: shopOrigin must be provided", action: undefined, type: "APP::ERROR::INVALID_CONFIG", stack: "AppBridgeError: APP::ERROR::INVALID_CONFIG: shopOrigin must be provided"}
action: undefined
message: "APP::ERROR::INVALID_CONFIG: shopOrigin must be provided"
name: "AppBridgeError"
type: "APP::ERROR::INVALID_CONFIG"
stack: "AppBridgeError: APP::ERROR::INVALID_CONFIG: shopOrigin must be provided"
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number:
    "@shopify/app-bridge": "^1.0.7",
    "@shopify/polaris": "^3.6.0",
- Browser: Chrome
- Device: PC
- Operating System: Windows

**Comment by tmlayton** [comment]
Hey @imgntn, thanks for the issue. Can you provide a full code snippet? Did you include the API key?

**Comment by imgntn** [comment]
it looks like it was because i was including the shopOrigin as

```  render(
  <AppProvider 
  apiKey={apiKey} 
  shopOrigin={shopOrigin} 
  forceRedirect={true}
  useLinkComponent={Link}>
    <Provider store={store}>
      <ConnectedRouter history={history}>
        <ErrorBoundary>
        <App />
        </ErrorBoundary>
      </ConnectedRouter>
    </Provider>
  </AppProvider>,
    target
  );```

but my origin was undefined.  whoops.  

not sure why it still threw when i commented out the shopOrigin but at any rate, i've moved on so i'll reopen this if i run into it again.

**Comment by meiskv** [comment]
I'm getting this error too. Outside Shopify Iframe/Admin.

And I can't fetch any data using the ngrok url as well.

<img width="1430" alt="Screen Shot 2019-07-19 at 10 49 39 PM" src="https://user-images.githubusercontent.com/939470/61558488-372cef80-aa78-11e9-870a-a98282bdc95d.png">
<img width="763" alt="Screen Shot 2019-07-19 at 10 48 55 PM" src="https://user-images.githubusercontent.com/939470/61558489-372cef80-aa78-11e9-84a5-dfdbe989b59d.png">
<img width="719" alt="Screen Shot 2019-07-19 at 10 49 05 PM" src="https://user-images.githubusercontent.com/939470/61558490-37c58600-aa78-11e9-83ad-9fb620591f3b.png">

**Comment by gil--** [comment]
@meiskv The starter app sets shopOrigin from the props which Nextjs populates via server.ctx.query.shop but it's null since you're not loading the app within the iframe so there's no shop parameter in the url. You either need to set it as a cookie or load the app within the admin.

`ctx.cookies.set("shopOrigin", shop, { httpOnly: false });` within the `async afterAuth(ctx) {` function inside server.js

**Comment by GherghelAndrei** [comment]
I'm using koa-shopify-auth, and i have the same issue with App Bridge on Safari and on Incognito. 
`const static_pages = new Koa();
static_pages.use(serve(__dirname + "/static/build"));
app.use(mount("/", static_pages));

app.use(
        shopifyAuth({
            apiKey: SHOPIFY_API_KEY,
            secret: SHOPIFY_API_SECRET_KEY,
            scopes: ['read_products', 'read_themes', 'write_themes', 'read_script_tags', 'write_script_tags'],
            afterAuth(ctx) {
                const { shop } = ctx.session;
                ctx.cookies.set('shopOrigin', shop, {
                    httpOnly: false,
                    secure: true,
                    sameSite: 'none'
                });
                ctx.redirect('/');
            },
        })
    )
app.use(verifyRequest());`

I'm serving React from koa. I don't know if this matters or not. Anyway, I've tried to create my own function in <head> index.html, to get shopOrigin from the Embedded URL that contains state hmac and shop, but it still fails... Any idea on how I can send shopOrigin from Koa to App Bridge? 

By the way, this error happend only during auth.

**Comment by GherghelAndrei** [comment]
I'm using koa-shopify-auth, and i have the same issue with App Bridge on Safari and on Incognito. 

I'm serving React from koa. I don't know if this matters or not. Anyway, I've tried to create my own function in <head> index.html, to get shopOrigin from the Embedded URL that contains state hmac and shop, but it still fails... Any idea on how I can send shopOrigin from Koa to App Bridge? 

By the way, this error happend only during auth in Safari and Incognito.
window.name is written in javascript bymyself, to tell me if i'm in the iframe or not 

code:
<img width="685" alt="Screen Shot 2020-08-07 at 6 24 24 PM" src="https://user-images.githubusercontent.com/18439989/89661543-804a1e80-d8db-11ea-9f8a-361089fefd15.png">



and frontend:
<img width="377" alt="Screen Shot 2020-08-07 at 6 27 01 PM" src="https://user-images.githubusercontent.com/18439989/89661710-b25b8080-d8db-11ea-83d1-fd2d6f412712.png">


@gil-- any ideas? :D
