### ISSUE TITLE
Polaris performance considerations

### ISSUE THREAD

**Issue by lemonmade** [Shopify/polaris-react#980]
This isn't strictly speaking an issue, more a request for the team to investigate some opportunities for optimization. While profiling the start up of Shopify Web, I noticed some things where Polaris was not living up to my expectations:

1. It brings in lodash/ lodash decorators. We have been too relaxed about having this as a dependency, and I feel it is time we treat our core dependencies as a "no lodash" zone.
2. It includes a slew of translations in the bundle by default. These take time to parse and execute, and in the end, they are completely unnecessary if a project instead supplies its own translations (as Web does)
3. (the most "needs exploration"-ey point): some components are beefy. Here were a few measurements for components (sorry, I didn't get measurements for everything):

    * ResourceList: 21ms evaluating
    * ActionList: 11ms evaluating
    * Popover: 12ms evaluating
    * Nav: 10ms evaluating, >30ms render

    It is possible that these are as small as they can be, but I think it's worth looking at whether our use in Web can be optimized here.

For Shopifolks, I will link up this issue with the one where I did the profiling so you'll see it linked below.

**Comment by AndrewMusgrave** [comment]
> It brings in lodash/ lodash decorators. We have been too relaxed about having this as a dependency, and I feel it is time we treat our core dependencies as a "no lodash" zone.

Iv’e previously looked at our uses of lodash and lodash decorators and we can 🔥  them fairly easily.

**Comment by BPScott** [comment]
>2 It includes a slew of translations in the bundle by default

Half baked idea: Make `i18n` a required key on <AppProvider> in v4? I guess we can look into what that means in depth later as IIRC we have some translations based stuff on our roadmap. (hi @danrosenthal)

**Comment by tmlayton** [comment]
I’m confused about the lodash decorators piece because each of our JS utils is just importing the lodash decorator under the hood:  https://github.com/Shopify/javascript-utilities/blob/master/src/decorators/debounce.ts#L1

**Comment by tmlayton** [comment]
I wrote these and IIRC have parity with lodash and are faster https://github.com/Shopify/polaris-rails/blob/master/admin/lib/utilities.js

**Comment by BPScott** [comment]
Tagging this with v4, as reworking translations is probably going to be a breaking change.

As part of that it might be worth looking into seeing if we want to use [`@shopify/react-i18n`](https://github.com/Shopify/quilt/tree/master/packages/react-i18n) rather than rolling our own

**Comment by yourpalsonja** [comment]
Hey Andrew, I assigned this to you since we're going through perf issues during the audit! It would be great if we could break this down into more manageable tasks, and then close this tix. Let's chat when you get a chance and figure out what we can do.

@tmlayton has also been looking into some benchmark testing.
