### ISSUE TITLE
Polaris Modal Component has unclear behaviour while connected to the App Bridge

### ISSUE THREAD

**Issue by danielkermode** [Shopify/polaris-react#983]
# Issue summary

If the Polaris Modal Component renders in "App Bridge" mode, it does not allow children. 

## Expected behavior

The Modal Component should render when passed children, as it behaves in standalone mode.

At the very least, give the option to prevent the Polaris Modal Component from working in "App Bridge" mode by passing through a prop to disable "App Bridge" mode.

## Actual behavior

The modal doesn't render and no error is given in the console when in "App Bridge" mode. I have no option to use the standalone Modal component.

## Steps to reproduce the problem

1. Create an app and connect to the App Bridge with the AppProvider component.
2. Use the Modal component in the app with children and be confused when it doesn't render.
3. Realise it renders correctly when the app is not connected to the App Bridge, resulting in further confusion at what on earth the developers of the App Bridge were thinking. Very unclear behaviour.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.6.0

**Comment by dpersing** [comment]
Hi @danielkermode! Could you provide a code snippet (even a reduced skeleton if you're more comfortable with that) showing what you've got in the `<AppProvider apiKey={API_KEY}>` wrapper? That can help us pinpoint the issue. Thank you!

**Comment by danielkermode** [comment]
Sure. `window.shopifyApiKey` contains the public API key for the application. The app bridge is working otherwise, as `ResourcePicker` renders correctly.

```
<AppProvider 
  apiKey={window.shopifyApiKey} 
  shopOrigin={window.shop} 
  forceRedirect={false}>
              <App/>
</AppProvider>
```

**Comment by dpersing** [comment]
Thanks @danielkermode. @tmlayton is this something you can take a look at?

**Comment by tmlayton** [comment]
> If the Polaris Modal Component renders in "App Bridge" mode, it does not allow children.

Hey @danielkermode, thanks for the issue, though the modal component when used in an embedded app does not allow children. The option here is to build a view in your application and use the `src` option on `Modal` to render a modal with an iframe.

<img src="https://user-images.githubusercontent.com/344839/52504278-cd411d80-2b9c-11e9-9036-d3605dce6328.png" width="300" />
