### ISSUE TITLE
[Autocomplete][v1] Using actionBefore prop throws uncaught invariant violation

### ISSUE THREAD

**Issue by sdn90** [Shopify/polaris-react#989]
# Issue summary

## Expected behavior

Should render when using actionBefore prop

## Actual behavior
React throws:

<details>
main.bundle.js:sourcemap:48448 Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
</details>

## Steps to reproduce the problem

1. Click on input

## Reduced test case

https://codesandbox.io/s/ov662j63z9

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.6.0
- Browser: Chrome
- Device: Macbook
- Operating System: MacOS 10.13

**Comment by PARAGJYOTI** [comment]
Any update yet?

**Comment by dleroux** [comment]
None yet @PARAGJYOTI. Sorry for the delay on this. It will be tackled soon as we are prioritizing this at the moment.

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.

**Comment by adriana45silva** [comment]
Hey people! 🖖Do we have any fallback for this prop that we can use at the moment?

**Comment by dleroux** [comment]
Unfortunately not at the moment. We do welcome pull requests, but tackling this from the ground up is the next thing on my plate.

**Comment by macs91** [comment]
Is this public api that is just supposed to crash?
