### ISSUE TITLE
Remove lodash / lodash-decorators

### ISSUE THREAD

**Issue by AndrewMusgrave** [Shopify/polaris-react#991]
### Lodash decorators
- [x] Throttle #1009
- [x] Remove from package #1009

### Lodash
- [x] Merge #1018
- [x] Get #1013
- [x] Replace #1012
- [ ] isEqual #1017
- [x] capitalize #1015
- [x] pick #1020
- [x] isObject #1011
- [ ] remove from package #1016

### Lodash in `examples/create-react-app`
- [x] Merge #1010

Related - #980

**Comment by sijad** [comment]
`denounce` is missed in above list:

https://github.com/Shopify/polaris-react/blob/b16c134fe6e450daf04a94c60d76e121ee118c8d/src/components/MediaQueryProvider/MediaQueryProvider.tsx#L2
https://github.com/Shopify/polaris-react/blob/44060b1ef10a346408675af954d48e03ac1286f6/src/components/Frame/components/Loading/Loading.tsx#L2
...

`isEqual` can replaced with https://www.npmjs.com/package/fast-deep-equal or https://www.npmjs.com/package/react-fast-compare
