### ISSUE TITLE
[Tabs] Support actions in Tab panel

### ISSUE THREAD

**Issue by jim-chou-shopify** [Shopify/polaris-react#995]
# Feature request summary
Tabs should support actions to enable more flexible layout.

## Rationale
This feature will allow actions to exit on the right of tabs.
```
--------------------------
Container
[Tabs]              [Reload]
--------------------------
[Tab content]
--------------------------
```
![52427419-dc0ccf00-2acd-11e9-90b6-1d65df4a9707](https://user-images.githubusercontent.com/39597748/52512871-304ea680-2bd5-11e9-9393-02bd6882fb95.png)

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by jim-chou-shopify** [comment]
FYI, I opened a misalignment issue when using `Card.Header` and `Button`.
https://github.com/Shopify/polaris-react/issues/996

**Comment by ry5n** [comment]
This is definitely something we should support.

There was some discussion offline about how to achieve this:

1. Add a dedicated prop for placing elements to the right of the tabs
2. Expose the tab strip and tab content container as separate components, the way we give you the option of using `Card.header` manually if you need more control over that part of a `Card`. You could import the tab strip and content container, place them within any desired layout, and then wire them together manually (insert hand waving here).

@elizabethletourneau When you have a second, is this something you could look at? cc @dpersing

**Comment by elizabethletourneau** [comment]
@ry5n I will take a look.
